nix-community/home-manager

home-manager/default.nix, home-manager/home-manager, modules/home-environment.nix
Fix for PR #11. Other than this, works great for me on Mac. Thanks.
=> Small correction to bash PATH

modules/default.nix, modules/misc/fontconfig.nix, modules/misc/news.nix
@Mic92, @uvNikita: If you have the time and will then please have a quick look at this. It implements the suggestion I made in #87.
=> fonts: add module

home-manager/default.nix, modules/files.nix, modules/home-environment.nix, modules/lib/file-type.nix, modules/misc/news.nix, modules/misc/xdg.nix, modules/xsession.nix
@nonsequitur I took the liberty of rebasing your nice branch from #59 on the latest master and also implemented some of the suggestions I made in the PR. If you have the time please look through and see if there is anything you disapprove of. I reused your commits so you are still listed as author and I don't want to include something you dislike under your name :-)
=> Rebase and expansions of PR #59

modules/services/dunst.nix
=> dunst: add option `services.dunst.iconTheme`

.travis.yml
Just to do an minimal evaluation for now.
=> Add simple Travis-CI configuration

modules/misc/nixpkgs.nix
To help explain the situation in #226.
=> Expand description of nixpkgs.config and nixpkgs.overlays

modules/services/owncloud-client.nix, modules/services/syncthing.nix
=> Fix qt services startup

modules/services/network-manager-applet.nix, modules/services/udiskie.nix, modules/xsession.nix
Add `xsession.preferStatusNotifierItems` option and make `network-manager-applet` and `udiskie` honor it.
=> Add xsession.preferStatusNotifierItems option

modules/programs/msmtp.nix, modules/programs/notmuch.nix, modules/services/polybar.nix, modules/services/window-managers/i3.nix, modules/services/window-managers/xmonad.nix
Also remove a few trailing whitespaces.
=> Remove unnecessary `dag` variables

modules/programs/fzf.nix
Fixes #401
Suggested-by: Alex Vorobiev
Suggested-by: Mario Rodas
=> fzf: only enable when line editing is available

modules/programs/astroid.nix, modules/programs/notmuch.nix
=> Notmuch synchronize flags option

README.md, doc/installation.xml, doc/manual.xml
Also minor cleanups in README.
=> doc: add installation instructions to manual

README.md, doc/installation.xml
Also add instructions for non-NixOS users to add the user channel directory to `NIX_PATH`.
=> readme: add notice that relog may be needed

modules/misc/dconf.nix, modules/misc/gtk.nix, modules/misc/news.nix, modules/modules.nix, modules/programs/gnome-terminal.nix
This module allows unified configuration of dconf settings.
=> dconf: add module

modules/services/flameshot.nix
=> flameshot: add bars to systemd After

modules/programs/tmux.nix, tests/modules/programs/tmux/default.nix, tests/modules/programs/tmux/hm-session-vars.sh, tests/modules/programs/tmux/secure-socket-enabled.nix
=> programs.tmux: implement secureSocket

README.md, doc/installation.xml, doc/release-notes/release-notes.xml, doc/release-notes/rl-1903.xml, doc/release-notes/rl-1909.xml, modules/misc/version.nix
=> Update stable version to 19.03

modules/programs/khal-calendar-accounts.nix, modules/programs/khal.nix, modules/programs/vdirsyncer.nix
* vdirsyncer: fix options `userName`, `userNameCommand`
* khal: add khal-account options `color` and `priority`
=> khal, vdirsyncer: add and fix options

modules/modules.nix, modules/services/muchsync.nix
This PR adds a service module for [muchsync](http://www.muchsync.org/).
=> muchsync: add module

modules/programs/kakoune.nix
=> kakoune: prepend extra configuration with newline

modules/systemd.nix
This fixes #355, fixes #798, and fixes #909.
=> systemd: perform reload even in degraded state

modules/programs/beets.nix
=> beets: allow custom package

modules/services/spotifyd.nix
Following nixos/nixpkgs@54433c4
=> spotifyd: update flags

modules/programs/termite.nix
Just a little change to `programs.termite.scrollbar`'s description
=> Fix termite scrollbar description

modules/programs/neomutt.nix
Closes #1035 
This seems to work great on my system, but please do let me know if there is anything that can be improved.
@teto
=> add reverse sort options to neomutt

modules/programs/starship.nix, tests/default.nix, tests/modules/programs/starship/default.nix, tests/modules/programs/starship/settings-expected.toml, tests/modules/programs/starship/settings.nix
This more readily allows merging configurations.
Fixes #1023
=> starship: give `settings` option more specific type

modules/misc/debug.nix, modules/modules.nix, tests/default.nix, tests/modules/misc/debug/default.nix
=> debug: add module

FAQ.md
=> faq: outline how to override packages

modules/services/window-managers/i3-sway/lib/options.nix
```
```
See [CONTRIBUTING](https://github.com/rycee/home-manager/blob/master/CONTRIBUTING.md#commits) for more information and [recent commit messages](https://github.com/rycee/home-manager/commits/master) for examples.
=> Fix typo in [...]/i3-sway/lib/options.nix

modules/programs/bat.nix
Add the ability to add custom theme files to bat.
```
```
=> bat: add custom themes

flake.lock, flake.nix
Update `flake.nix` and `flake.lock` to latest version of flakes.
```
```
=> flakes: update to latest version

modules/programs/neomutt.nix
=> neomutt: Add SMTP port to smtp_url

.github/CODEOWNERS
Was wondering why I wasn't getting mentioned in sway prs and it's because I can't spell
=> CODEOWNERS: fix typo

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/nushell.nix, tests/default.nix, tests/modules/programs/nushell/default.nix, tests/modules/programs/nushell/settings-expected.toml, tests/modules/programs/nushell/settings.nix
Add module for https://github.com/nushell/nushell
```
```
=> nushell: add module

modules/services/unison.nix
=> unison: fix escaping of arguments

README.md
=> Update README.md to point to new url

README.md
"Minimal" flakes example is a bit more complex than needed, and doesn't work :|
I made it a bit more approachable.
```
```
=> readme: less complex minimal example

modules/programs/mpv.nix
Make the generated `mpv` package available to the rest of the configuration.
```
```
=> mpv: make package available via programs.mpv.package

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/github_pages.yml, .github/workflows/test.yml, README.md, doc/contributing.adoc, doc/default.nix, doc/installation.xml, doc/man-home-manager.xml, doc/manual.xml, home-manager/install.nix, modules/misc/news.nix, modules/programs/zsh.nix, modules/services/window-managers/i3-sway/i3.nix, modules/services/window-managers/i3-sway/lib/options.nix, modules/targets/darwin.nix, modules/targets/generic-linux.nix, tests/modules/programs/waybar/broken-settings.nix, tests/modules/programs/waybar/default.nix, tests/modules/targets-darwin/default.nix
Automate the publication of the manual.
```
```
=> Publish GitHub pages

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/gammastep.nix
=> gammastep: init

README.md
=> README: Remove dangling reference to IcedTea

README.md
Improves experience before people manually find
https://github.com/nix-community/home-manager/issues/1561
```
```
=> README: mention that nixUnstable is not supported

modules/services/parcellite.nix
This makes the parcellite package configurable; for instance, someone
might want to use the better-maintained clipit fork which has better
support for appindicators.
```
```
=> parcellite: make package configurable

modules/programs/mpv.nix
This is a continuation of discussion from #1417.
There exist mpv configurations which cannot be expressed in
programs.mpv.config currently. For example, it is impossible to use
multiple 'profile' attributes. This commit changes the way config and
profiles are parsed, using lib.generators.toKeyValue and
lib.generators.toINI, to allow for these kinds of configurations through
the use of listsAsDuplicateKeys.
```
```
=> mpv: use lib.generators to render config

tests/modules/programs/kakoune/no-plugins.nix, tests/modules/programs/kakoune/use-plugins.nix
Fix broken kakoune tests
Following https://github.com/NixOS/nixpkgs/pull/91792
```
```
=> kakoune: fix tests

modules/programs/waybar.nix
- Change the `attrsOf unspecified` to `pkgs.formats.json` for the module settings
- Add new (missing) default modules
- Expand the `with lib` with every function used
- Add inline documentation about the generated warnings
```
```
=> waybar: fix null modules-{left,center,right} error

modules/services/emacs.nix
This allows providing a custom package to the Emacs service.
This is a fix for #1556 
I didn't see any other test cases for customized package, but could add it if you think I should.
```
```
=> emacs: make service package configurable

tests/default.nix
Fixes excessive memory use when running all tests.
=> tests: update nmt version

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/pbgopy.nix, tests/default.nix, tests/modules/services/pbgopy/default.nix, tests/modules/services/pbgopy/service.nix
A very simple service for [pbgopy](https://github.com/nakabonne/pbgopy).
This is my first contribution to home-manager, feedback is much appreciated :)
```
```
=> pbgopy: add service

modules/programs/neovim.nix
Implementation:
https://github.com/nix-community/home-manager/pull/1342
```
```
=> neovim: mark plugins as optional (possibly)

modules/systemd.nix
=> systemd: support mount units

modules/systemd.nix
This adds support for sd-switch, a tool to perform systemd generation switches. It can be activated by setting
systemd.startServices = "sd-switch";
=> systemd: support sd-switch

README.md, doc/installation.adoc
=> Make nix-channel choice more clear.

modules/programs/mcfly.nix
McFly 0.5.1 added support for fuzzy searching.
```
```
=> mcfly: add option to enable fuzzy search

modules/services/imapnotify.nix
This changes the implementation of the existing `imapnotify` module to use  `goimapnotify` instead of `node-imapnotify`. All of the existing options are retained.
I also made some modifications to the systemd service to match the [AUR version](https://aur.archlinux.org/cgit/aur.git/tree/goimapnotify@.service?h=goimapnotify) of `goimapnotify`. In particular, restarting is useful in case a network failure causes `imapnotify` to exit - that shouldn't mean that it stops trying when the network comes back up.
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for …
=> imapnotify: switch to goimapnotify instead of node-imapnotify

modules/misc/news.nix, modules/misc/pam.nix
See #1691 for more information.
=> pam: add note about future deprecation

modules/programs/broot.nix
Allow for overriding the package.
```
```
=> broot: add package option

README.md
It took me a long time to understand what home manager is about. I am
used to single-user nixos installations, where there's little
distinction between user env and global env, so it was unclear to me
what is the purpose of home manager if I already have a declarative
config in configuration.nix.
=> Clarify what is user environment

modules/programs/mpv.nix
mpv supports loading profiles with the `profile` option. Options set by a profile can then be overridden with other configuration options. For example one could set
profile=gpu-hq
deband=no
which enables `gpu-hq` (which normally would enable debanding) but explicitly disables debanding.
With the current home-manager module, all configuration options are written alphabetically and since `profile` comes after `deband`, setting `deband=no` will have no effect.
This PR adds the option `programs.mpv.defaultProfiles` which writes the `profile=…` setting to the beginning of the configuration file.
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and …
=> mpv: add defaultProfiles option

modules/services/gpg-agent.nix
=> gpg: export GPG_TTY for fish

flake.nix
https://github.com/NixOS/nix/blob/1c0e3e453d41b869e4ac7e25dc1c00c349a7c411/src/nix/flake.cc#L537
=> flake.nix: add nixosModule and darwinModule

modules/programs/termite.nix
=> Remove alias to allow using with allowAlias = false

modules/misc/xdg-user-dirs.nix
It automatically creates all the XDG user directories. Set to `false` as default to not break backwards compatibility.
```
```
=> xdg-user-dirs: add createDirectories option

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/pass-secret-service.nix
Added pass secret service.
```
```
=> pass-secret-service: add module

modules/misc/gtk.nix, tests/default.nix, tests/modules/misc/gtk/default.nix, tests/modules/misc/gtk/gtk-basic-config-expected.conf, tests/modules/misc/gtk/gtk2-basic-config.nix, tests/modules/misc/gtk/gtk2-config-file-location.nix
=> gtk2: allow configuration of gtkrc file

modules/home-environment.nix, modules/programs/bash.nix, modules/programs/scmpuff.nix, tests/modules/misc/gtk/gtk-basic-config-expected.conf, tests/modules/misc/gtk/gtk2-basic-config.nix, tests/modules/programs/bash/logout-expected.txt, tests/modules/programs/bash/logout.nix, tests/modules/programs/bash/session-variables-expected.txt, tests/modules/programs/bash/session-variables.nix, tests/modules/programs/scmpuff/bash.nix, tests/modules/programs/scmpuff/no-bash.nix, tests/modules/programs/scmpuff/no-shell.nix, tests/modules/programs/scmpuff/no-zsh.nix, tests/modules/programs/scmpuff/zsh.nix
Also fix gtk2-basic-config test and use `pkgs.scmpuff` instead of `pkgs.gitAndTools.scmpuff`.
=> Check bash syntax in home-environment and bash modules

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/foot.nix, tests/default.nix, tests/modules/programs/foot/default.nix, tests/modules/programs/foot/empty-settings.nix, tests/modules/programs/foot/example-settings-expected.ini, tests/modules/programs/foot/example-settings.nix, tests/modules/programs/foot/systemd-user-service-expected.service, tests/modules/programs/foot/systemd-user-service.nix
Add a module for `foot`, a "fast, lightweight and minimalistic Wayland terminal emulator". Fixes #1547.
Homepage: https://codeberg.org/dnkl/foot
```
```
=> foot: add module

modules/files.nix, modules/lib/file-type.nix
See discussion in https://github.com/nix-community/home-manager/pull/2031.
=> files: remove assertion on recursive onChange

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/rbw.nix, tests/default.nix, tests/modules/programs/rbw/default.nix, tests/modules/programs/rbw/empty-settings.nix, tests/modules/programs/rbw/overlay.nix, tests/modules/programs/rbw/settings.nix, tests/modules/programs/rbw/simple-settings.nix
`rbw` is a Bitwarden client written in `rust`. 
```
```
=> rbw: add module

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/modules.nix, modules/programs/senpai.nix
Adds a module for the senpai IRC client.
```
```
=> programs.senpai: add module

modules/services/sxhkd.nix, tests/modules/services/sxhkd/service.nix
Before it generated a nonsense test script.
=> sxhkd: fix service test

tests/default.nix
Allows running, e.g.,
nix-build --pure tests -A build.all
```
```
=> tests: update nmt

README.md
- The config is changed in https://github.com/nix-community/home-manager/commit/d99f54b51b7395e0652ddb2212676b7076c9af4f, however #1571 didn't fix the state and still says "enabled" when smooth scroll is actually disabled (`"general.smoothScroll" = false`).
- Similarly for 356c0bf751a55878c448461d8ef1d17f43911acd, 93b10bcf3cf09df990908f4ca428b18eab34aa3f missed another place to change.
```
```
=> README: fix outdated description

modules/programs/obs-studio.nix
The packaging in nixpkgs for obs plugins has changed and there's a `wrapOBS` function.
The name of the plugins has also changed so the example needed updating to reflect that.
Related: https://github.com/NixOS/nixpkgs/pull/125308
This PR is done in the style of the `neovim` module that has `package` and a hidden `finalPackage`
I have not added a news update as this is more of a behind-the-scenes change but I can if you'd like.
Is there any issue with merging this before `wrapOBS` and the plugin changes make it to stable?
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commit …
=> obs-studio: use wrapobs and the new plugin layout

modules/programs/qutebrowser.nix
Add a `onChange` entry for qutebrowser, allowing it to react to configuration changes.
Qutebrowser can reload its configuration with the `:config-source` command, which can be run through its IPC socket too.
```
```
Here's how it looks:
https://user-images.githubusercontent.com/5727578/125020477-49cad580-e04f-11eb-8d61-0ea1a1cb333e.mp4
I was using something similar to [this script](https://github.com/qutebrowser/qutebrowser/blob/master/scripts/open_url_in_instance.sh) to update my qutebrowser instance …
=> qutebrowser: add onChange ipc reloading

modules/misc/news.nix, modules/modules.nix, modules/services/xsettingsd.nix
=> xsettingsd: add service module

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/volnoti.nix
=> volnoti: add module

modules/services/volnoti.nix
=> volnoti: fix package option namespace

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/notify-osd.nix
=> notify-osd: init

modules/services/window-managers/i3-sway/lib/options.nix
=> sway: workspaceLayout: `stacked` -> `stacking`

modules/services/window-managers/awesome.nix
See https://github.com/NixOS/nixpkgs/pull/135117
```
```
=> service/window-manager/awesome: replace not existing package

modules/services/gpg-agent.nix
Make `gpgconf` only perform an import from derivation when the GPG `homedir` is set to a non-default value (which I expect shouldn't be the case for most users).
```
```
=> gpg-agent: remove unnecessary IFD

flake.nix
Provide an easy way to access the manual via flakes.
```
```
=> flake: Add docs to packages output

nixos/default.nix
If the user has a running systemd session, source their environment from the systemd manager and export a few variables in order to allow activation scripts to reload applications on the fly.
The list of variables to export is arbitrary and could be extended in the future.
Fixes #1399, fixes #2112.
```
```
=> nixos: expose user session environment during activation

home-manager/home-manager
=> Fix command line option for nix build

modules/accounts/email.nix
Just providing imap/smtp servers for fastmail.com
=> Add email account flavor for fastmail.com

modules/services/lieer.nix
=> lieer: use configured package in service

docs/default.nix
Bump nmd to make prompts unselectable in shell session program listings.
```
```
=> docs: bump nmd

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/sqls.nix
Add module for sqls https://github.com/lighttiger2505/sqls
```
```
=> sqls: add module

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/navi.nix
Add module for https://github.com/denisidoro/navi
```
```
=> navi: add module

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/services/opensnitch-ui.nix
After opensnitch module for the daemon got merged in NixOS https://github.com/NixOS/nixpkgs/pull/132319 , I wanted to submit a service for the client part here.
```
```
=> opensnitch-ui: add module

modules/services/window-managers/i3-sway/sway.nix, tests/modules/services/window-managers/sway/default.nix, tests/modules/services/window-managers/sway/sway-bar-focused-colors.conf, tests/modules/services/window-managers/sway/sway-bindkeys-to-code.conf, tests/modules/services/window-managers/sway/sway-default.conf, tests/modules/services/window-managers/sway/sway-followmouse-expected.conf, tests/modules/services/window-managers/sway/sway-followmouse-legacy-expected.conf, tests/modules/services/window-managers/sway/sway-modules.conf, tests/modules/services/window-managers/sway/sway-no-xwayland.nix, tests/modules/services/window-managers/sway/sway-null-package.conf, tests/modules/services/window-managers/sway/sway-workspace-default-expected.conf, tests/modules/services/window-managers/sway/sway-workspace-output-expected.conf
=> sway: add 'xwayland disable' to sway config if disabled

modules/programs/direnv.nix
Add documentation on how to enable the direnv fish integration with
```nix
{
environment.pathsToLink = [ "/share/fish" ];
}
```
```
```
=> direnv: Add troubleshooting to fish integration.

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/window-managers/herbstluftwm.nix, tests/default.nix, tests/modules/services/window-managers/herbstluftwm/autostart, tests/modules/services/window-managers/herbstluftwm/default.nix, tests/modules/services/window-managers/herbstluftwm/herbstluftwm-simple-config.nix
Add a new module for the [HerbstluftWM](https://herbstluftwm.org) window manager.
```
```
=> herbstluftwm: init module

modules/programs/rbw.nix
=> rbw: Fix a typo

modules/programs/waybar.nix
- The check did not account the default value of `settings.modules` to be `{}`.
The default value was changed to `null`.
- The `settings.modules` option is now hidden from the docs.
Closes #2546 
```
```
=> waybar: fix deprecated "modules" setting check

README.md
The README is corrected to mention using `home-manager switch --flake` with Flakes.
See https://github.com/nix-community/home-manager/issues/2434#issuecomment-1016667711 for the context.
```
```
=> Fix README flake commands

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/programs/tint2.nix
=> tint2: add module

modules/services/unison.nix
Pairs are named attribute sets. One level was missing.
GitHub: see #2662
```
```
=> unison: fix option example

modules/programs/chromium.nix
- Add support for command line arguments, this allows arguments to be
persistently set if needed (i.e workaround hardware bugs or enabling
certain flags).
- Document setting a custom package will nullify the `commandLineArgs`
option.
- Fix `mkRemovedOption` assertion from being apply even when the `extensions`
option is unused for google chrome modules.
~~There is currently no brave support as of yet, but it will once either https://github.com/NixOS/nixpkgs/pull/136591 or https://github.com/NixOS/nixpkgs/pull/115961 is merged (if following the first, the interface can then be standardized, but I am biased).~~
The aforementioned PR has been merged.
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contribu …
=> chromium: add commandLineArgs option

docs/nix-flakes.adoc
Quick one-liner doc issue that I came across while trying to get started.
=> docs: fix standalone flake setup

docs/usage.adoc
Add a new section "Updating" to usage docs.
Add a new section "Updating" to usage docs.
```
```
Resolves: #2685
=> docs: section how to update system

modules/launchd/default.nix
When there are multiple launchd agents, wrong symbolic link file is generated.
Is should be like below.
```
```
=> launchd: fix multiple agents

home-manager/home-manager, home-manager/po/home-manager.pot, modules/files.nix, modules/home-environment.nix, modules/lib-bash/activation-init.sh, modules/po/hm-modules.pot
=> nix: add support for `nix profile`

README.md
Finding the Appendices of the manual is nigh impossible. Therefore i place a link to the first and most important one prominently in the readme. 
```
```
=> doc: Add link to configuration options.html

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/modules.nix, modules/programs/sioyek.nix
Adds the module for the pdf reader sioyek.
```
```
=> sioyek: add module

modules/misc/xdg-mime-apps.nix
This convenience function allows automatic assignment of a package's associations to `xdg.mimeApps.defaultApplications`.
For example,
xdg.mimeApps.defaultApplications =
config.lib.xdg.mimeAssociations [ pkgs.gnome.evince ];
Based on code suggestion from @ryantrinkle.
```
```
=> xdg-mime-apps: add function `mimeAssociations`

flake.nix
=> Simplify function

modules/lib/types-dag.nix, modules/programs/gpg.nix, tests/lib/types/dag-merge.nix, tests/modules/programs/i3status-rust/with-custom.nix, tests/modules/programs/i3status-rust/with-default.nix, tests/modules/programs/i3status-rust/with-extra-settings.nix
Backports https://github.com/nix-community/home-manager/pull/2823 and https://github.com/nix-community/home-manager/pull/2822
```
```
=> [21.11] gpg: create homedir with 700 permissions

modules/programs/git.nix
Add the option to use [diff-so-fancy](https://github.com/so-fancy/diff-so-fancy) as diff tool in git. This makes the shown diffs human readable (and pretty) instead of machine readable.
This PR was inspired by https://github.com/nix-community/home-manager/pull/2850
```
```
=> git: Add option to use diff-so-fancy as diff tool

flake.nix, nix-darwin/default.nix, nixos/common.nix, nixos/default.nix
Applies review comments from https://github.com/nix-community/home-manager/pull/2971#pullrequestreview-1008311355
=> Clean up after #2971

modules/services/udiskie.nix
Adds option settings, which writes settings to `.config/udiskie/config.yml`
The option takes precedence against other options like `notify`, `automount` or `tray` if they are configured in `settings.program_options`
```
```
=> udiskie: add option settings

modules/services/fusuma.nix
The example for settings is including the top level options, which is misleading.
```
```
=> fusuma: fix settings example

modules/programs/vscode.nix
Fixes https://github.com/nix-community/home-manager/issues/3094
Fixed in https://github.com/nix-community/home-manager/pull/2506 then unfixed in https://github.com/nix-community/home-manager/pull/2613
```
```
=> vscode: avoid unnecessary IFD (again)

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/bashmount.nix
As my first contribution, a straightforward module.
```
```
=> bashmount: add module

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/pueue.nix
Bring pueue module to home-manager.
Code provided by rycee
Closes https://github.com/nix-community/home-manager/issues/3111
```
```
=> pueue: add module

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/yt-dlp.nix
[yt-dlp](https://github.com/yt-dlp/yt-dlp) is a command-line tool to download videos from YouTube.com and other sites (youtube-dl fork)
```
```
=> yt-dlp: add module

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/window-managers/fluxbox.nix
=> fluxbox: add module

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/services/safeeyes.nix
=> Add safeeyes

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/tmate.nix, tests/default.nix, tests/modules/programs/tmate/default.nix, tests/modules/programs/tmate/tmate.nix
=> tmate: add module

modules/services/kdeconnect.nix
=> kdeconnect: pkgs.kdeconnect -> pkgs.plasma5Packages.kdeconnect-kde

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/pls.nix, tests/default.nix, tests/modules/programs/pls/bash.nix, tests/modules/programs/pls/default.nix, tests/modules/programs/pls/fish.nix, tests/modules/programs/pls/zsh.nix
Add module with aliases for [pls](https://dhruvkb.github.io/pls/)
```
```
=> pls: add module

modules/services/lorri.nix
Adds `nixPackage` option, which allows lorri to use `nixUnstable`,
and therefore flake based shell.s
Adds a little notifier service, so that starts and ends of builds can be reported.
```
```
=> lorri: add nixPackage option; add notifier

modules/services/mpd.nix
It's always useful to have the man pages available.
```
```
=> mpd: add package to home path

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/ledger.nix
Add module for https://www.ledger-cli.org/
```
```
=> ledger: add module

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/havoc.nix
=> havoc: add module

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/discocss.nix
Rewrite of #3079
~~Waiting for https://github.com/NixOS/nixpkgs/pull/189164 to pass Hydra.~~
```
```
=> discocss: add module

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/borgmatic.nix, modules/services/borgmatic.nix, tests/default.nix, tests/modules/programs/borgmatic/basic-configuration.nix, tests/modules/programs/borgmatic/default.nix, tests/modules/services/borgmatic/basic-configuration.nix, tests/modules/services/borgmatic/basic-configuration.service, tests/modules/services/borgmatic/basic-configuration.timer, tests/modules/services/borgmatic/default.nix
add [borgmatic](https://torsion.org/borgmatic/) module.
```
```
=> borgmatic: add module

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/programs/k9s.nix, tests/default.nix, tests/modules/programs/k9s/default.nix, tests/modules/programs/k9s/empty-settings.nix, tests/modules/programs/k9s/example-config-expected.yml, tests/modules/programs/k9s/example-settings.nix, tests/modules/programs/k9s/example-skin-expected.yml
Signed-off-by: Paul Meyer <49727155+katexochen@users.noreply.github.com>
Add k9s module. [K9s](https://k9scli.io/) is a stylish Kubernetes CLI.
Hope my code quality is okay, I'm quite new to Nix/Nixos.
```
```
=> k9s: add module

README.md
link to https://mipmip.github.io/home-manager-option-search/ in readme
=> Readme: add inofficial option search

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/oh-my-posh.nix, tests/default.nix, tests/modules/programs/oh-my-posh/bash.nix, tests/modules/programs/oh-my-posh/default.nix, tests/modules/programs/oh-my-posh/fish.nix, tests/modules/programs/oh-my-posh/zsh.nix
Add a new module for [oh-my-posh](https://ohmyposh.dev/)
```
```
=> oh-my-posh: add module

modules/programs/opam.nix
=> opam: add fish integration

modules/programs/zsh.nix
=> programs.zsh: generate a more compact config

modules/programs/newsboat.nix
This PR adds 2 QoL changes: an option to manage the "urls" file imperatively and an option to enable a systemd service which would refresh the feeds periodically.
The former option is valuable if the user doesn't want to expose feeds in a git repo AND doesn't want to use `gitcrypt`, while still enjoying the benefits of managing Newsboat. It makes it possible to use `Syncthing`, `agenix` or `sops-nix` to manage "urls" in a safe way.
The latter option adds a simple systemd service that updates the Newsboat feeds (1 hour by default).
```
``` …
=> newsboat: allow imperative "urls" management

modules/services/mpd-discord-rpc.nix
"graphical-session.target", not "graphical-session.desktop".
```
```
=> mpd-discord-rpc: fix typo

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/services/clipman.nix, tests/default.nix, tests/modules/services/clipman/clipman-sway-session-target.nix, tests/modules/services/clipman/clipman-sway-session-target.service, tests/modules/services/clipman/default.nix
Add support for [clipman](https://github.com/yory8/clipman), a simple clipboard manager for Wayland.
```
```
=> clipman: add module

modules/programs/feh.nix
Resolve the request I made in: https://github.com/nix-community/home-manager/issues/3495
@rycee Thank you for the indications and I remain attentive to any problem!
```
```
=> feh: Add package option

modules/programs/firefox.nix
[Details](https://gitlab.com/rycee/nur-expressions/-/commit/b70c44e8575e65ff63c5f52eb726aa3fc9a86af7)
```
```
=> firefox: update example to remove https-everywhere

docs/contributing.adoc
See https://github.com/nix-community/home-manager/issues/3495#issuecomment-1364708228
=> docs: mention how to override the home-manager flake input

modules/programs/firefox.nix
Continuing from the suggestion in https://github.com/nix-community/home-manager/pull/2984#issuecomment-1287893159, this refactors firefox search generation to be easier to read.
```
```
=> firefox: refactor search.json.mozlz4 generation to be easier to read

modules/services/gpg-agent.nix
Fixes #3244.
Seems to have been left out by #1846.
```
```
=> gpg: fix ssh support for fish

docs/nix-flakes.adoc, modules/config/home-cursor.nix, modules/programs/fish.nix, modules/programs/kodi.nix, modules/programs/mbsync.nix, modules/programs/mujmap.nix, modules/services/mako.nix, tests/modules/misc/debug/default.nix, tests/modules/programs/aerc/extraAccounts.expected, tests/modules/programs/aerc/settings.nix, tests/modules/programs/mbsync/mbsync-master-slave-change.nix, tests/modules/programs/mbsync/mbsync.nix
Fixed some typos in the source code
```
```
=> treewide: fix typos

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/rbenv.nix
Add module for [rbenv](https://github.com/rbenv/rbenv)
```
```
=> rbenv: add module

docs/3rd-party.adoc, docs/manual.xml
=> docs: add chapter on 3rd-party extensions

modules/programs/broot.nix
Remove some unnecessary IFD
```
```
=> broot: remove unnecessary IFD

modules/programs/starship.nix
Reverts nix-community/home-manager#3776
=> Revert "starship: condition nushell integration on nushell 0.73+"

modules/programs/starship.nix
Reverts nix-community/home-manager#3777
=> Revert "[backport 22.11] starship: condition nushell integration on nushell 0.73+"

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/copyq.nix
Add service for https://hluk.github.io/CopyQ/
```
```
=> copyq: add module

modules/programs/thunderbird.nix, tests/modules/programs/thunderbird/thunderbird.nix
=> thunderbird: add userChrome and userContent options (rebased)

flake.nix
Not the smartest removal: it just copy-pastes the code from flake-utils.
Closes #3859 (hopefully)
```
```
=> flake.nix: get rid of flake-utils

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/batsignal.nix
=> services.batsignal: init

modules/services/avizo.nix, tests/default.nix, tests/modules/services/avizo/default.nix, tests/modules/services/avizo/with-settings.nix, tests/modules/services/avizo/without-settings.nix
Rebase of PR #3871 with various minor additions.
=> avizo: don't write a config file if settings are empty

modules/programs/aerc-accounts.nix
Support oauth params for authentication mechanisms oauthbearer and xoauth2.
This is useful e.g. when adding a microsoft account as documented here: https://man.sr.ht/~rjarry/aerc/providers/microsoft.md
=> aerc: add oauth params

README.md
This is important information that people still have [trouble finding](https://github.com/nix-community/home-manager/pull/3454#issuecomment-1527173043), let's make it more obvious.
=> README: move releases section higher

.github/CODEOWNERS, modules/programs/ledger.nix, tests/default.nix, tests/modules/programs/ledger/default.nix, tests/modules/programs/ledger/ledger.nix
=> ledger: add structural `settings` option

.github/CODEOWNERS, modules/modules.nix, modules/programs/translate-shell.nix, tests/default.nix, tests/modules/programs/translate-shell/default.nix, tests/modules/programs/translate-shell/translate-shell.nix
Add module for https://www.soimort.org/translate-shell/
```
```
=> translate-shell: add module

.github/labeler.yml
- ci: tag aerc changes with 'mail'
- ci: tag some files with 'shell' tag
```
```
=> autolabel PRs for aerc changes and some zsh files

modules/misc/news.nix, modules/modules.nix, modules/programs/script-directory.nix
Added a module for github.com/ianthehenry/sd
The [PR](https://github.com/NixOS/nixpkgs/pull/232287) was just merged yesterday https://nixpk.gs/pr-tracker.html?pr=232287
```
```
=> script-directory: add module

.github/dependabot.yml, LICENSE, README.md, docs/installation.adoc, docs/nix-flakes.adoc, docs/release-notes/rl-2211.adoc, docs/release-notes/rl-2305.adoc, docs/usage.adoc, home-manager/home-manager
Marks the release-23.05 branch as the current stable.
=> Mark 23.05 as stable version

docs/release-notes/rl-2305.adoc, docs/release-notes/rl-2311.adoc
Merged https://github.com/nix-community/home-manager/pull/4012 too fast
=> Fix release notes

modules/programs/khal-calendar-accounts.nix, modules/programs/khal.nix
* khal: Do not hard code globbing.
* khal: Provide a default and description for type.
I've tried to fix the khal config generation based on feedback here: https://github.com/nix-community/home-manager/issues/2335#issuecomment-1589137573
```
```
=> khal: improve module

.github/workflows/github_pages.yml, .github/workflows/test.yml, .github/workflows/update-flake.yml
Fixes an issue with the macos runner
=> Bump install-nix-action to v22

modules/programs/himalaya.nix, tests/modules/programs/himalaya/basic-expected.toml, tests/modules/programs/himalaya/basic.nix, tests/modules/programs/himalaya/default.nix, tests/modules/programs/himalaya/imap-smtp-expected.toml, tests/modules/programs/himalaya/notmuch-sendmail-expected.toml, tests/modules/programs/himalaya/notmuch-sendmail.nix
=> himalaya: adjust module for 0.8.X

modules/programs/zellij.nix
=> zellij: fix module description for shell integrations

docs/default.nix
Mainly to work around recent changes in Nixpkgs with respect to `_module.args`.
```
```
=> docs: update nmd

tests/modules/programs/broot/broot.nix
Backport https://github.com/nix-community/home-manager/pull/4170
```
```
=> [23.05] broot: fix test

.github/labeler.yml
=> ci: autolabel calendars PRs

modules/accounts/calendar.nix, modules/programs/khal.nix, tests/default.nix, tests/modules/programs/khal/config.nix, tests/modules/programs/khal/default.nix
I fixed a small issues in khal because it excepts a certain setting only in the default section and I fixed a small docs error in the calendar infra. 
```
```
=> Fixing some minor issues with calendar infra.

.github/PULL_REQUEST_TEMPLATE.md
Add a "maintainer cc" section to the PR template, mirroring the issue template.
=> PULL_REQUEST_TEMPLATE.md: add maintainer cc section

modules/misc/news.nix, modules/modules.nix, modules/services/swayosd.nix, tests/default.nix, tests/modules/services/swayosd/default.nix, tests/modules/services/swayosd/swayosd.nix
Add swayosd module: a gtk-3 osd 
```
```
=> swayosd: add module

docs/default.nix
These are already documented in the system-level manuals and have no particular relevance to the `home-manager.*` options.
You always notice something right after merge...
```
```
=> docs: hide `_module.*` from NixOS/nix-darwin docs

modules/misc/news.nix, modules/modules.nix, modules/programs/gh-dash.nix, tests/default.nix, tests/modules/programs/gh-dash/config.nix, tests/modules/programs/gh-dash/default.nix
Addin a module for gh-dash https://github.com/dlvhdr/gh-dash
```
```
=> gh-dash: add module

modules/programs/gpg.nix
=> gpg: fix typo

modules/programs/fish.nix
=> fish: fix session vars build in cross-compiled system

modules/programs/himalaya.nix
This updates a dead link in comment. No functional changes intended.
```
```
@soywod @toastal
=> himalaya: Update a link to ticket

modules/programs/browserpass.nix, tests/modules/programs/browserpass/browserpass.nix
=> browserpass: support librewolf

modules/misc/news.nix, modules/modules.nix, modules/programs/pqiv.nix, tests/default.nix, tests/modules/programs/pqiv/default.nix, tests/modules/programs/pqiv/settings.nix
Adds https://github.com/phillipberndt/pqiv
```
```
=> pqiv: add module

tests/default.nix, tests/modules/i18n/input-method/fcitx5-stubs.nix
=> pqiv: only run tests on Linux platforms

modules/config/home-cursor.nix
The current cursor configuration poorly accomodate applications not following the XDG icon theme spec. As a result, some applications fail to locate user defined icons and themes.
To address this, a symlink from $HOME/.icons to the home-manager profile icons directory was added for backwards compatibility with applications using hardcoded icons directories. In addition, the default index.theme file was moved from XDG_DATA_DIRS back to $HOME/.icons for greater compatibility. As per the XDG icon theme spec, applications are to search in $HOME/.icons first for icons and themes so the existing behavior should not break for XDG compliant applications. [1]
[1] - https://specifications.freedesktop.org/icon-theme-spec/latest/ar01s03.html
fixes …
=> home-cursor: make icon configuration compatible with more applications

modules/misc/news.nix, modules/modules.nix, modules/programs/yazi.nix, tests/default.nix, tests/modules/programs/yazi/bash-integration-enabled.nix, tests/modules/programs/yazi/default.nix, tests/modules/programs/yazi/keymap-expected.toml, tests/modules/programs/yazi/settings-expected.toml, tests/modules/programs/yazi/settings.nix, tests/modules/programs/yazi/theme-expected.toml, tests/modules/programs/yazi/zsh-integration-enabled.nix
Add module of [Yazi - ⚡️ Blazing Fast Terminal File Manager](https://github.com/sxyazi/yazi)
https://github.com/NixOS/nixpkgs/pull/250697 cc @teto 
```
```
=> yazi: add module

modules/programs/aerc-accounts.nix, modules/programs/aerc.nix, modules/programs/antidote.nix, modules/programs/offlineimap-accounts.nix, modules/programs/offlineimap.nix
I was experimenting with my LSP setup in Emacs and opened a few files
to check some features. 
```
```
=> Remove some unused bindings

.github/workflows/test.yml
=> ci: use nixos-23.05 channel

modules/programs/just.nix
Simplifies the code of this removed module.
```
```
=> just: simplify

modules/modules.nix
Adds the missing xplr module import, as per https://github.com/nix-community/home-manager/pull/4230#issuecomment-1712350411.
CC: @rycee
=> xplr: add module

modules/programs/git.nix
Remove the function gitToInit and underlying functions in favor of using the function lib.generators.toGitINI from nixpkgs. 
closes #4354
depends on https://github.com/NixOS/nixpkgs/pull/250220
- works when run against https://github.com/VwCSXg/nixpkgs/tree/update-gitINI-generator: `nix develop --override-input nixpkgs 'git+https://github.com/VwCSXg/nixpkgs?ref=update-gitINI-generator' --ignore-environment .#all`
```
```
@rycee
=> git: replace gitToInit with lib function

modules/programs/waybar.nix, tests/modules/programs/waybar/systemd-with-graphical-session-target.service
=> waybar: fix service After value

modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/programs/bacon.nix, tests/default.nix, tests/modules/programs/bacon/bacon.nix, tests/modules/programs/bacon/default.nix, tests/modules/programs/bacon/expected.toml
bacon is a background rust code checker.
https://dystroy.org/bacon/
```
```
=> bacon: added programs.bacon

modules/misc/news.nix, modules/modules.nix, modules/programs/thefuck.nix, tests/default.nix, tests/modules/programs/thefuck/default.nix, tests/modules/programs/thefuck/integration-disabled.nix, tests/modules/programs/thefuck/integration-enabled.nix
Add thefuck module: https://github.com/nvbn/thefuck
```
```
=> thefuck: add module

modules/programs/fish.nix
Query the `pname` and `version` attributes for completion generation, if the `name` attribute is not available.
Fixes #2813
This is pretty much @stopbystudent's approach from the issue. 
I tried using `pkgs.lib.getName`, but didn't find a good way to integrate it. 
```
```
I couldn't find a `meta.maintainers`, so:
```
$ git log --since='2023-01-01' --follow --format='%an <%ae>' -- modules/programs/fish.nix | sort | uniq
```
@emilazy 
@yu-re-ka 
@marsam
=> fish: also query pname and version for completions

modules/services/recoll.nix
=> recoll: update option descriptions

docs/installation.adoc
=> docs: fix option name

modules/programs/helix.nix
Closes #2923 based on how arnarg solves this in his personal config.
Co-authored-by: Arnar Gauti Ingason <arnarg@fastmail.com>
```
```
=> helix: add extraPackages option

modules/lib/maintainers.nix, modules/modules.nix, modules/programs/swayr.nix, tests/default.nix, tests/modules/programs/swayr/basic-configuration.nix, tests/modules/programs/swayr/basic-configuration.toml, tests/modules/programs/swayr/default.nix, tests/modules/programs/swayr/empty-configuration.nix
Add module: swayr
https://sr.ht/~tsdh/swayr
```
```
=> swayr: add module

modules/programs/firefox.nix
Without this, when a user references `config.programs.firefox.package` in its configuration, s·he will get a different path as what is in its $PATH variable.
I didn't add any test. I will add one if you believe that is useful in this cases.
```
```
/cc @rycee @kira-bruneau
=> firefox: make programs.firefox.package the same as what is in PATH

modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/programs/openstackclient.nix, tests/default.nix, tests/modules/programs/openstackclient/clouds-public.yaml, tests/modules/programs/openstackclient/clouds.yaml, tests/modules/programs/openstackclient/default.nix, tests/modules/programs/openstackclient/openstackclient.nix
=> openstackclient: add module

modules/programs/yazi.nix, tests/modules/programs/yazi/fish-integration-enabled.nix, tests/modules/programs/yazi/nushell-integration-enabled.nix
- Update shell integrations (https://yazi-rs.github.io/docs/quick-start#changing-working-directory-when-exiting-yazi)
- Update doc links
Fixed https://github.com/nix-community/home-manager/issues/4697
```
```
=> yazi: update shell integrations and docs

flake.nix
With this it is possible to build a specific test by running
$ nix build -L .#test-{test name}
For example
$ nix build -L .#test-files-text
```
```
=> flake: add packages for tests

docs/manual/nix-flakes.md
this addresses a small typo i noticed while reading the manual.
=> docs: fix typo in nix-flakes.md

modules/programs/yazi.nix, tests/modules/programs/yazi/nushell-integration-enabled.nix
=> yazi: fix nushell integration

modules/lib/maintainers.nix, modules/programs/gradle.nix
Follow up to 0360475ee0fc870bc450874da5b5d7b2a85a091b
=> gradle: Re-add maintainer

modules/programs/firefox.nix
Fixes issues described in #4936
Instead of linking the directory we're symlinkJoining cfg.finalPackage and cfg.nativeMessagingHosts, we're also building an empty package containing the folder $out/lib/mozilla/native-messaging-hosts in case there is nothing configured.
We're then listing the directory of the joined package and creating individual home.file entries for each one of them.
We're also configuring a .keep file to keep the native messaging hosts folder around even if there's nothing configured, for those that might install native messengers outside of HM.
Tested:
While a bit more complex, this solution should be rock solid for any usecase.
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for …
=> Better implementation of native messaging hosts for firefox

modules/misc/nix.nix
Nix 2.20 deprecates `nix show-config` in favour of `nix config show` and this
causes a build error when generating the nix.conf file.
See also nixos/nixpkgs#271423
```
```
=> nix: fix error while generating nix.conf for nix >= 2.20

modules/targets/darwin/fonts.nix
When a lot of fonts are used, the `copyFonts` step can take multiple seconds. It currently deletes and again copies the fonts from the Nix store, even if the files are identical.
This PR makes two changes:
1. Skip font installation if the derivation hasn't changed: the path to the build in the Nix store is written to a file. As long as the Nix store path doesn't change (ie, the font build is the same), the copyFonts step is skipped.
1. Use `rsync` instead of `install` to copy font files. Rsync will only copy files that are new or have actually changed.
With these changes the `copyFonts` step is instant when no fonts are changed, and quite a lot faster when there are changes.
```
```
See …
=> Speed up copyFonts

modules/services/xscreensaver.nix
Signed-off-by: Christina Sørensen <christina@cafkafk.com>
```
```
=> nixos/xscreensaver: add package option

modules/programs/yazi.nix, tests/modules/programs/yazi/bash-integration-enabled.nix, tests/modules/programs/yazi/nushell-integration-enabled.nix, tests/modules/programs/yazi/zsh-integration-enabled.nix
https://yazi-rs.github.io/docs/quick-start#shell-wrapper
cc @sxyazi
```
```
=> yazi: update shell integrations

README.md
=> Correct rollback link

modules/programs/eza.nix
rograms.eza.enableAliases -> programs.eza.enableAliases
```
```
=> eza: fix typo in docs

modules/services/nix-gc.nix
Let systemd use any time configuration with nix.gc.frequency
```
```
@shivaraj-bh
=> nix.gc.frequency: let systemd use any time config

modules/misc/nix.nix
(cherry picked from commit 880d9bc2110f7cae59698f715b8ca42cdc53670c)
Fixes nix.conf generation for newer Nixes.
```
```
=> [backport] nix: fix generation of nix.conf for nix >= 2.20

modules/services/kdeconnect.nix
Fixes issue #5188 
```
```
@adisbladis
=> kdeconnect: Add package option

modules/programs/fzf.nix
[fzf 0.48.0](https://github.com/junegunn/fzf/releases/tag/0.48.0) changed the way it integrates with shells.
Fixes https://github.com/nix-community/home-manager/issues/5242
```
```
=> fzf: add compatibility with fzf≥0.48.0

modules/systemd.nix
=> systemd: add `enable` option

modules/misc/qt/kconfig.nix
Fixes https://github.com/nix-community/home-manager/issues/5306#event-12546824495
```
```
=> konfig: fix missing quoting

modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/services/swaync.nix, tests/default.nix, tests/modules/services/swaync/default.nix, tests/modules/services/swaync/swaync.nix
Adds module `services.swaync` See #4249 for prior context
```
```
=> swaync: add module

modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/services/conky.nix, tests/default.nix, tests/modules/services/conky/basic-configuration.conf, tests/modules/services/conky/basic-configuration.nix, tests/modules/services/conky/default.nix
Add new module to enable [conky](https://github.com/brndnmtthws/conky) as service on Linux 
```
```
=> conky: Init module

README.md, docs/manual/installation/nix-darwin.md, docs/manual/installation/nixos.md, docs/manual/installation/standalone.md, docs/manual/nix-flakes/standalone.md, docs/manual/usage/configuration.md, docs/release-notes/release-notes.md, docs/release-notes/rl-2405.md, docs/release-notes/rl-2411.md, home-manager/home-manager, modules/misc/uninstall.nix, release.json, tests/integration/nixos/basics.nix, tests/integration/standalone/alice-home-init.nix, tests/integration/standalone/alice-home-next.nix
Prepare 24.05 release and 24.11 development branch.
=> Prepare 24.05 and 24.11-pre

modules/programs/khal.nix
=> khal: add package option

tests/modules/programs/mpv/mpv-stubs.nix
This fixes a broken overlay in the mpv tests. There were multiple errors and none of them were specific to Darwin despite the tests currently succeeding on Linux.
I only ran `mpv-example-settings` and `mpv-invalid-settings`, since this PR only affects those.
```
```
=> tests: fix Darwin failure

modules/programs/yazi.nix, tests/modules/programs/yazi/flavor/init.lua, tests/modules/programs/yazi/init.lua, tests/modules/programs/yazi/plugin/init.lua, tests/modules/programs/yazi/settings.nix
Support plugins and flavors for yazi.
```
```
=> yazi: support plugins and flavors

modules/misc/news.nix, modules/modules.nix, modules/services/blanket.nix, tests/default.nix, tests/modules/services/blanket/basic-configuration.nix, tests/modules/services/blanket/default.nix
Add the blanket service from [blanket on github](https://github.com/rafaelmardojai/blanket)
```
```
=> blanket: add module

modules/programs/yazi.nix, tests/modules/programs/yazi/flavor/README.md, tests/modules/programs/yazi/flavor/flavor.toml, tests/modules/programs/yazi/flavor/init.lua, tests/modules/programs/yazi/settings.nix
Fixes #5478 
I would also like to try backporting this PR and the new yazi plugin & flavor options to `release-24.05`. Should I send a PR for that?
- Append suffix `.yazi` to symlink targets of yazi plugins, if needed.
- Improve some docs, especially links to upstream docs.
- Update tests to make use of this feature.
```
```
@XYenon
=> yazi: Ensure plugin suffix `.yazi`

docs/manual/introduction.md, docs/manual/manual.md
Adds an introduction chapter to the manual.
```
```
=> docs: introduction chapter

modules/services/window-managers/i3-sway/sway.nix
=> sway: fix systemd variables example

modules/programs/firefox.nix
Port the `programs.firefox.languagePacks` option from NixOS.
**Edit** Forgot to add earlier: closes #5186 
```
```
=> firefox: add languagePacks option

modules/programs/micro.nix
add package option for micro
```
```
@MForster
=> micro: add package option

modules/services/poweralertd.nix
Follow up from https://github.com/nix-community/home-manager/pull/5836.
I made the false assumption that utils would have propagated from nixpkgs to home-manager. Copy in `escapeSystemdExecArgs` to fix the immediate issue, perhaps we can pull this in some other way later down the line.
```
```
=> poweralertd: Fix regression introduced by me in 8d7e352

modules/programs/git.nix
Adds module for https://git-scm.com/docs/git-maintenance. Feel free to propose any grammar nitpicks, I am not a native, so will gladly accept them.
Example usage:
```nix
programs.git = {
maintenance = {
enable = true;
repositories = [ "/home/perchun/dev/nixpkgs" ];
};
}
```
```
```
=> git: add module for `git maintenance`

modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/programs/zed-editor.nix, tests/default.nix, tests/modules/programs/zed-editor/default.nix, tests/modules/programs/zed-editor/extensions.nix, tests/modules/programs/zed-editor/keymap.nix, tests/modules/programs/zed-editor/settings.nix
Add a module for the Zed editor.
```
```
=> Zed editor

modules/lib/maintainers.nix, modules/programs/bemenu.nix
I am no longer using NixOS/Nix on my main desktop, so I will not be able to actively maintain the configuration for bemenu if there are any new features or breaking changes. I greatly appreciate the home-manager project for accepting my contributions. I learned a lot during my time using NixOS and Home Manager. Thank you!  
```
```
=> maintainers: remove omernaveedxyz

modules/misc/news.nix
=> news: fix typo

modules/programs/aerc-accounts.nix
=> aerc: add support of account gpg config

modules/misc/version.nix
nixpkgs updated upstream: https://github.com/NixOS/nixpkgs/commit/90fcf3aa7eba70f18dad15b634e9336b997d25ac
=> version: allow 25.05 as state version

modules/programs/zsh/zsh-abbr.nix
Path changes on nixpkgs: https://github.com/NixOS/nixpkgs/commit/d90af1448cfa1d7a013c80d435878023f92471bf
```
```
=> zsh-abbr: update source path

modules/services/emacs.nix, tests/default.nix, tests/modules/services/emacs-darwin/basic.nix, tests/modules/services/emacs-darwin/default.nix, tests/modules/services/emacs-darwin/expected-agent.plist
=> emacs: add darwin service

modules/programs/zed-editor.nix
Closes #6052
Added the `programs.zed-editor.extraPackages` option to make for example language servers available to Zed without having to add them to `home.packages` or similar.
Code has been copied from the helix module.
```
```
@libewa
=> zed-editor: Add extraPackages option

modules/misc/news.nix, modules/modules.nix, modules/programs/nix-your-shell.nix, tests/default.nix, tests/modules/programs/nix-your-shell/default.nix, tests/modules/programs/nix-your-shell/enable-shells.nix
This is alternative to #4645 which stalled. More along the lines of how starship and zoxide is implemented.
Closes #4645
```
```
=> programs.nix-your-shell: add module

tests/modules/i18n/input-method/fcitx5-configuration.nix, tests/modules/misc/nix/empty-settings.nix, tests/modules/misc/nix/example-channels-xdg.nix, tests/modules/misc/nix/example-channels.nix, tests/modules/misc/nix/example-registry.nix, tests/modules/misc/nix/example-settings.nix, tests/modules/misc/nix/keep-old-nix-path.nix, tests/modules/programs/cmus/cmus.nix, tests/modules/xresources/empty.nix, tests/modules/xresources/xresources.nix
=> Various test fixes and cleanups

modules/misc/news.nix, modules/programs/mbsync-accounts.nix, modules/programs/mbsync.nix, tests/modules/programs/mbsync/mbsync-expected.conf, tests/modules/programs/mbsync/mbsync.nix
Update isync to use new features in isync 1.5.0.
Closes #5884 and #3317.
```
```
=> isync/mbsync: update module for 1.5.0 changes

modules/programs/thunderbird.nix
Closes: #5654
This is a near verbatim transplant of firefox option to thunderbird module. With it, I was able to deploy thunderbird profile with an extension pre-installed.
```
```
=> thunderbird: Implement `extensions` for profiles

modules/services/mako.nix
add center-left and center-right
https://man.archlinux.org/man/mako.5.en
```
```
=> mako: add center-left & center-right

modules/programs/ranger.nix, tests/modules/programs/alacritty/default.nix, tests/modules/programs/alacritty/example-settings.nix, tests/modules/programs/alacritty/settings-merging.nix, tests/modules/programs/alacritty/toml-config.nix, tests/modules/programs/broot/broot.nix, tests/modules/programs/ranger/configuration.nix, tests/modules/programs/vim-vint/basic-configuration.nix, tests/modules/programs/zsh/history-ignore-pattern.nix, tests/modules/programs/zsh/history-path-new-custom.nix, tests/modules/programs/zsh/history-path-new-default.nix, tests/modules/programs/zsh/history-path-old-custom.nix, tests/modules/programs/zsh/history-path-old-default.nix, tests/modules/programs/zsh/history-substring-search.nix, tests/modules/programs/zsh/prezto.nix, tests/modules/programs/zsh/session-variables.nix, tests/modules/programs/zsh/syntax-highlighting.nix, tests/modules/programs/zsh/zsh-abbr.nix, tests/modules/programs/zsh/zsh-stubs.nix
Stub some tests to make the test suite run faster.
```
```
=> treewide: stub tests

modules/services/network-manager-applet.nix
This makes it a bit easier to find.
```
```
@rycee @midirhee12
=> network-manager-applet: add nm-applet to description

modules/services/hypridle.nix, modules/services/hyprpaper.nix
Just some cleanup while I was looking at stuff. 
```
```
@fufexan @rycee
=> {hypridle, hyrpaper}: remove with lib;

modules/programs/tealdeer.nix
Repo was [moved](https://github.com/tealdeer-rs/tealdeer). 
The old link is no longer accessible.
```
```
@pedorich-n
=> tealdeer: update docs link

modules/programs/aerospace.nix
=> aerospace: enable option desc fix

modules/programs/btop.nix
=> btop: remove with lib;

modules/programs/wezterm.nix
=> wezterm: remove with lib

modules/programs/bat.nix
=> bat: remove with lib

modules/services/window-managers/hyprland.nix, tests/modules/services/window-managers/hyprland/default.nix, tests/modules/services/window-managers/hyprland/null-all-packages-config.nix, tests/modules/services/window-managers/hyprland/null-package-config.nix, tests/modules/services/window-managers/hyprland/null-portal-package-config.nix
Closes https://github.com/nix-community/home-manager/issues/6373
```
```
@fufexan
=> hyprland: fix null package conditions

modules/programs/neovim.nix
=> neovim: remove with lib

modules/programs/yazi.nix
=> yazi: remove with lib and cleanup

modules/accounts/email.nix
migadu is a very friendly and no-fuzz email service that presumably will be highly valued by HM users
```
```
=> email: add migadu.com flavor

modules/programs/git.nix
=> git-maintenance: More details in the documentation

modules/programs/fish.nix
closes https://github.com/nix-community/home-manager/issues/6414
```
```
=> fish: accept multiple events

modules/modules.nix, modules/programs/vinegar.nix, tests/default.nix, tests/modules/programs/vinegar/default.nix, tests/modules/programs/vinegar/empty-settings.nix, tests/modules/programs/vinegar/example-config-expected.toml, tests/modules/programs/vinegar/example-settings.nix
Adds a module for [vinegar](https://vinegarhq.org/Home/index.html)
```
```
=> vinegar: add module

modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/programs/earthly.nix, tests/default.nix, tests/modules/programs/earthly/default.nix, tests/modules/programs/earthly/earthly-settings.nix, tests/modules/programs/earthly/earthly-settings.yml
Earthly is a build configuration framework utilizing buildkit and Dockerfile-like syntax for simplicity and fast builds.
Ref: https://docs.earthly.dev/
```
```
=> earthly: init module

modules/programs/chromium.nix
Added native messaging hosts option, for `plasma-browser-integration` for example. Tested it, and it works, From my research, it should work on darwin too.
```
```
=> chromium: add nativeMessagingHosts option

modules/lib/maintainers.nix, modules/modules.nix, modules/services/clipse.nix, tests/default.nix, tests/modules/services/clipse/clipse-sway-session-target.nix, tests/modules/services/clipse/default.nix
This adds a module for https://github.com/savedra1/clipse
```
```
=> clipse: add module

modules/programs/dircolors.nix, tests/modules/programs/dircolors/default.nix, tests/modules/programs/dircolors/settings.nix, tests/modules/programs/dircolors/xdg-config-settings.nix
=> dircolors: respect preferXdgDirectories if set

modules/programs/git.nix
Adds https://github.com/walles/riff as an available diff tool for `git`
```
```
@rycee
=> git: add option to use riff as diff tool

modules/services/clipse.nix
Adding keyBindings and imageDisplay to the module
```
```
=> clipse: add additional options

modules/services/mpd.nix, tests/modules/services/mpd/basic-configuration.conf, tests/modules/services/mpd/xdg-music-dir.conf
Remove with lib, reorganize, cleanup conditionals, hide options that are linux only from darwin.
```
```
=> mpd: refactor implementation

modules/services/xidlehook.nix
Follow up to https://github.com/nix-community/home-manager/pull/6533
```
```
=> idlehook: fix service.restart merge

modules/launchd/launchd.nix, modules/launchd/types.nix
We haven't updated to match changes done upstream in a while. Updating to reflect changes for expanding support / proper types.
```
```
=> launchd: sync up with changes from nix-darwin

.github/labeler.yml
=> ci: autolabels  firefox PRs

modules/modules.nix, modules/programs/lazydocker.nix, tests/default.nix, tests/modules/programs/lazydocker/custom-settings.nix, tests/modules/programs/lazydocker/custom-settings.yml, tests/modules/programs/lazydocker/default-settings.nix, tests/modules/programs/lazydocker/default.nix, tests/modules/programs/lazydocker/default.yml
Closes https://github.com/nix-community/home-manager/pull/5584
Closes https://github.com/nix-community/home-manager/issues/4924
```
```
=> lazydocker: add module 

modules/modules.nix, modules/services/jankyborders.nix, tests/default.nix, tests/modules/services/jankyborders/config.nix, tests/modules/services/jankyborders/default.nix, tests/modules/services/jankyborders/jankyborders-config-expected
=> jankyborders: add module

modules/modules.nix, modules/services/skhd.nix, tests/default.nix, tests/modules/services/skhd/config.nix, tests/modules/services/skhd/default.nix, tests/modules/services/skhd/skhd-config-expected
=> skhd: add module

modules/services/davmail.nix
Davmail package has multiple overrides people might want to use. 
```
```
=> davmail: add package option

modules/programs/vscode.nix
The version check for VSCode fails when using Cursor.
Cursor has its own versioning and is 
currently at 0.45.14 (based on VSCode version 1.96.2).
The version checks for generating the `extensions.json`
in the module look at the package version,
which causes them not to be generated for Cursor.
```
```
@Reputable2772 @HyunggyuJang
=> vscode: Fix version checks when using Cursor

modules/programs/zsh/zsh-abbr.nix
zsh-abbr has a global abbreviations feature. The global abbreviations expand anywhere on the line and are defined by using the `-g` option.
https://zsh-abbr.olets.dev/types.html#global
However, home-manager did not have this setting, so I added it in this PR.
Following the naming of `zsh.shellGlobalAliases`, I named it `zsh-abbr.globalAbbreviations`.
```
```
=> zsh-abbr: Add global abbreviations

modules/programs/vscode.nix
Backport of https://github.com/nix-community/home-manager/pull/6417
```
```
=>  [24.11 backport] vscode: Support Cursor AI

modules/programs/firefox/mkFirefoxModule.nix
=> firefox: fix missing lib

tests/default.nix
Building causing massive CI delays
```
```
=> tests: stub notmuch darwin

tests/modules/programs/firefox/profiles/userchrome/chrome/extraFile.css, tests/modules/programs/firefox/profiles/userchrome/default.nix, tests/modules/programs/firefox/profiles/userchrome/expected-userchrome.css
Not sure why I had two of them..
```
```
=> tests/firefox: consolidate userChrome.css test files

.github/labeler.yml
Add rules, fill in missing files for existing rules.
```
```
=> labeler: expand labels

modules/programs/eza.nix
fixes https://github.com/nix-community/home-manager/issues/6313
```
```
@cafkafk
=> eza: add theme option

modules/programs/zed-editor.nix, tests/modules/programs/zed-editor/default.nix, tests/modules/programs/zed-editor/themes/default.nix, tests/modules/programs/zed-editor/themes/one.json
based on helix themes option
```
```
@libewa
=> zed-editor: add themes option

modules/programs/atuin.nix
related #6271
```
```
@hawkw @water-sucks
=> atuin: add support for str + path themes

.github/PULL_REQUEST_TEMPLATE.md
=> PR_TEMPLATE: mention nix fmt

modules/lib/maintainers.nix, modules/misc/news/2025-04-20_20-12-03.nix, modules/modules.nix, modules/programs/clock-rs.nix, tests/default.nix, tests/modules/programs/clock-rs/default.nix, tests/modules/programs/clock-rs/empty-settings.nix, tests/modules/programs/clock-rs/example-settings-expected.toml, tests/modules/programs/clock-rs/example-settings.nix
Closes https://github.com/nix-community/home-manager/pull/6395
```
```
=> clock-rs: add module 

modules/misc/news/2025-04-20_20-27-49.nix, modules/modules.nix, modules/programs/television.nix, tests/default.nix, tests/modules/programs/television/basic-config.nix, tests/modules/programs/television/default.nix
=> television: add module

modules/i18n/input-method/fcitx5.nix
=> fcitx5: refactor logic

modules/programs/vesktop.nix
=> vesktop: fix config path on darwin

modules/i18n/input-method/default.nix
=> input-method: fix enable condition

modules/programs/lsd.nix, tests/modules/programs/lsd/example-settings.nix
=> lsd: enableAliases -> enableShellIntegration; refactor; add package option

modules/misc/news/2025-04-26_18-56-13.nix
=> espanso: fix alias in news

modules/i18n/input-method/fcitx5.nix
fcitx5 overwrites config files unless the entire folder is readonly. With this PR, a single `fcitx5`  symlink is made instead of multiple fcitx5/* ones. The link is only created when relevant options are set.
```
```
@awwpotato
=> fcitx5: ensure config doesn't get overwritten

modules/modules.nix, modules/programs/onagre.nix, tests/default.nix, tests/modules/programs/onagre/default.nix, tests/modules/programs/onagre/example-config.nix, tests/modules/programs/onagre/style
This PR adds a module for configuring Onagre. Didn't added plugins options since those are for Pop-launcher, not exclusive to Onagre. Closes #5446.
```
```
=> onagre: add module

modules/services/mako.nix, tests/modules/services/mako/example-config.nix
Follow up to https://github.com/nix-community/home-manager/pull/6948#issuecomment-2849614919
Fix backwards compatibility
```
```
=> mako: use ini atom type

.github/PULL_REQUEST_TEMPLATE.md
Update the [permalink](https://github.com/nix-community/home-manager/blob/a51598236f23c89e59ee77eb8e0614358b0e896c/modules/programs/lesspipe.nix#L11) to show a version of the module that follows current best practices (no `with lib;`, and nixfmt’d).
```
```
@awwpotato @khaneliman @rycee
=> PR_TEMPLATE: update example for module maintainer

modules/programs/direnv.nix
Reverts nix-community/home-manager#6999
=> Revert "direnv: update nushell env conversion logic"

modules/programs/television.nix, tests/modules/programs/television/basic-config.nix
=> television: add support for channels

modules/programs/zellij.nix, tests/modules/programs/zellij/default.nix, tests/modules/programs/zellij/theme.nix
=> zellij: add themes option

modules/modules.nix, modules/programs/halloy.nix, tests/default.nix, tests/modules/programs/halloy/default.nix, tests/modules/programs/halloy/example-config.nix, tests/modules/programs/halloy/example-config.toml
This PR adds a module for configuring Halloy. Closes #7033.
```
```
=> halloy: add module

modules/misc/news/2025-03-21_03-19-14.nix, modules/misc/news/2025-03-22_03-18-58.nix, modules/misc/news/2025-03-22_03-19-06.nix, modules/misc/news/2025-04-26_03-16-59.nix, modules/misc/news/2025-04-27_03-17-07.nix, modules/misc/news/2025-04-28_03-17-15.nix, modules/misc/news/2025-04-28_03-17-23.nix, modules/misc/news/2025-05-02_03-14-27.nix, modules/misc/news/2025-05-02_03-14-36.nix, modules/misc/news/2025-05-03_03-14-19.nix, modules/misc/news/2025-05-04_03-14-11.nix, modules/misc/news/2025-05-05_03-14-02.nix, modules/misc/news/2025-05-08_03-13-52.nix, modules/misc/news/2025-05-09_03-13-20.nix, modules/misc/news/2025-05-11_03-13-09.nix
=> news: catchup with recent modules

modules/programs/gnome-terminal.nix
=> gnome-terminal: add package option

modules/programs/halloy.nix
=> halloy: fix themes example

modules/dbus.nix, modules/modules.nix, tests/default.nix, tests/modules/dbus/default.nix, tests/modules/dbus/packages.nix
=> dbus: Create with packages options 

modules/modules.nix, modules/programs/ptyxis.nix, tests/default.nix, tests/modules/programs/ptyxis/default.nix, tests/modules/programs/ptyxis/palette.nix
=> ptyxis: init module

README.md, docs/manual/installation.md, docs/manual/installation/nix-darwin.md, docs/manual/nix-flakes/nix-darwin.md, modules/launchd/launchd.nix, modules/launchd/types.nix, templates/nix-darwin/flake.nix
=> treewide: lnl7 -> nix-darwin

modules/misc/news/2025/03/2025-03-25_19-48-21.nix, modules/misc/news/2025/03/2025-03-25_20-44-04.nix, modules/misc/news/2025/03/2025-03-25_21-37-24.nix, modules/misc/news/2025/03/2025-03-29_23-32-11.nix
=> news: add some more missing news items

.github/workflows/github_pages.yml, .github/workflows/test.yml, flake.nix
=> flake.nix: pin to nixos-25.05

modules/services/podman-linux/install-quadlet.nix
Fixes potentially unwanted variable substitution that came with writing the Quadlet configuration directly into the `installPhase`.
```
```
@bamhm182
=> podman: use quadlet source from file drv

modules/programs/zed-editor.nix
Allow for nullable zed-editor package.
```
```
=> zed-editor: allow for nullable package

modules/modules.nix, modules/programs/lazysql.nix, tests/default.nix, tests/modules/programs/lazysql/default.nix, tests/modules/programs/lazysql/example-config.nix, tests/modules/programs/lazysql/example-config.toml
This PR adds a module for configuring `lazysql`. Closes #7227.
```
```
=> lazysql: add module

modules/modules.nix, modules/programs/nyxt.nix, tests/darwinScrublist.nix, tests/default.nix, tests/modules/programs/nyxt/default.nix, tests/modules/programs/nyxt/example-config.lisp, tests/modules/programs/nyxt/example-config.nix
This PR adds a module for configuring Nyxt, a web browser written in Lisp. Closes #7223.
```
```
=> nyxt: add module

modules/services/opensnitch-ui.nix
=> opensnitch-ui: add package option

modules/lib/maintainers.nix
=> maintainers: update aguirre-matteo email

modules/services/window-managers/labwc/function.nix, modules/services/window-managers/labwc/labwc.nix, tests/modules/services/window-managers/labwc/labwc-menu.nix, tests/modules/services/window-managers/labwc/menu.xml
fix pipemenu and icon generation in menu.xml generator
and not manage file when user not define any option related to the file
```
```
=> labwc: fix pipemenu and icon generation and not manage file

modules/services/window-managers/i3-sway/sway.nix
Allows the user to choose the dbus implementation for the environment import.
See https://github.com/swaywm/sway/wiki#systemd-and-dbus-activation-environments
```
```
@Scrumplex @alexarice @sumnerevans @oxalica
=> sway: add `wayland.windowManager.sway.systemd.dbusImplementation`

modules/lib/maintainers.nix
Follow up to https://github.com/nix-community/home-manager/pull/7350#issuecomment-3025898357
```
```
=> maintainers: fix incorrect entries

.github/workflows/update-flake.yml
=> ci: fix which branch to show on pr

.github/workflows/tag-maintainers.yml, lib/python/manage-reviewers.py
cleaning up more after further testing and work in nixvim version
```
```
=> ci: tag-maintainers further refactoring

.github/labeler.yml, modules/programs/gurk-rs.nix, tests/modules/programs/gurk-rs/basic-config.nix, tests/modules/programs/gurk-rs/default.nix
=> gurk-rs: add module

modules/programs/yofi.nix, tests/modules/programs/yofi/blacklist, tests/modules/programs/yofi/default.nix, tests/modules/programs/yofi/example-config.nix, tests/modules/programs/yofi/yofi.config
This pull request adds a module for configuring yofi. Closes #7520.
```
```
=> yofi: add module

modules/programs/hyprlock.nix, tests/modules/programs/hyprlock/basic-configuration.conf, tests/modules/programs/hyprlock/basic-configuration.nix, tests/modules/programs/hyprlock/complex-configuration.conf, tests/modules/programs/hyprlock/complex-configuration.nix
Some breaking changes from upstream
```
```
=> hyprlock: update example config 

.github/PULL_REQUEST_TEMPLATE.md
We now use the stable release.
```
```
=> PULL_REQUEST_TEMPLATE: nixfmt-rfc-style -> nixfmt

modules/programs/television.nix, tests/modules/programs/television/basic-config.nix
taking the functional changes from https://github.com/nix-community/home-manager/pull/7568 (author hasn't responded to feedback after 5 days)
Closes: https://github.com/nix-community/home-manager/issues/7594
cc: @elanora96 @Posiedon-Rises 
```
```
=> television: update channel location

modules/misc/news/2025/08/2025-08-05_14-13-10.nix, modules/misc/news/2025/08/2025-08-05_14-13-23.nix, modules/misc/news/2025/08/2025-08-05_14-13-33.nix
=> news: add new module entries

modules/misc/news/2025/08/2025-08-05_14-17-36.nix
Closes https://github.com/nix-community/home-manager/issues/7623
```
```
=> news: fix font config entry

.github/labeler.yml, modules/misc/news/2025/08/2025-08-05_21-18-50.nix, modules/services/rescrobbled.nix, tests/modules/services/rescrobbled/basic-config.nix, tests/modules/services/rescrobbled/default.nix
closes https://github.com/nix-community/home-manager/issues/7586
```
```
=> rescrobbled: add module

modules/lib/maintainers.nix, modules/programs/sheldon.nix, tests/modules/programs/sheldon/default.nix, tests/modules/programs/sheldon/plugins.toml
Add module for https://github.com/rossmacarthur/sheldon
Closes PR #5672 and Issue  #5656
Thank you @Kyure-A for doing most of the work!
```
```
=> sheldon: add module

.github/PULL_REQUEST_TEMPLATE.md
Automatic markdown formatting messes with the display format..
[example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and
[recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.
[example](https://github.com/nix-community/home-manager/blob/a51598236f23c89e59ee77eb8e0614358b0e896c/modules/programs/lesspipe.nix#L11). …
=> PULL_REQUEST_TEMPLATE: fix commit message link formatting

modules/programs/swaylock.nix
Simply installing swaylock through Home Manager does not also configure PAM, and on non-NixOS, it would be inconvenient to manually do so because the path to `linux-pam` in the store changes. Thus recommend installing swaylock from the distribution's repository instead of through Home Manager.
Fixes #7717.
```
```
=> swaylock: document how to fix PAM on non-NixOS

modules/services/blueman-applet.nix
copy pasta error
https://github.com/nix-community/home-manager/pull/7702/files#r2290600709
```
```
=> blueman-applet: fix typo in systemdTargets

modules/programs/hyprpanel/default.nix
Also, add more daemons to check
```
```
=> hyprpanel: fix dontAssertNotificationDaemons

modules/services/activitywatch.nix
=> add service status cmd to desc

modules/programs/vscode/default.nix
Add support for [Kiro](https://kiro.dev)
```
> realpath ~/.kiro/extensions
/home/rhoriguchi/.kiro/extensions
> realpath ~/.config/Kiro
/home/rhoriguchi/.config/Kiro
```
```
```
=> vscode: add config and exension dir for kiro

modules/misc/news/2025/09/2025-09-18_13-25-16.nix, modules/programs/abaddon.nix, tests/modules/programs/abaddon/abaddon.ini, tests/modules/programs/abaddon/default.nix, tests/modules/programs/abaddon/example-config.nix
This PR adds a module for configuring [Abaddon](https://github.com/uowuo/abaddon).
```
```
=> abaddon: add module

modules/misc/news/2025/09/2025-09-18_14-05-15.nix, modules/programs/acd-cli.nix, tests/modules/programs/acd-cli/acd_cli.ini, tests/modules/programs/acd-cli/acd_client.ini, tests/modules/programs/acd-cli/cache.ini, tests/modules/programs/acd-cli/default.nix, tests/modules/programs/acd-cli/example-config.nix, tests/modules/programs/acd-cli/fuse.ini
This PR adds a module for configuring [acd-cli](https://github.com/yadayada/acd_cli).
```
```
=> acd-cli: add module

modules/programs/mpvpaper.nix
Fixed small typos in the comments. 
```
```
=> mpvpaper: fix typos

modules/misc/news/2025/09/2025-09-24_16-33-28.nix, modules/programs/aiac.nix, tests/modules/programs/aiac/aiac.toml, tests/modules/programs/aiac/default.nix, tests/modules/programs/aiac/example-config.nix
This PR adds a module for configuring [aiac](https://github.com/gofireflyio/aiac).
```
```
=> aiac: add module

modules/misc/news/2025/09/2025-09-26_11-46-57.nix, modules/programs/airlift.nix, tests/modules/programs/airlift/config.yaml, tests/modules/programs/airlift/default.nix, tests/modules/programs/airlift/settings.nix
This PR adds a module for configuring [Airlift](https://github.com/jl178/airlift).
```
```
=> airlift: add module

modules/misc/news/2025/09/2025-09-26_11-20-32.nix, modules/programs/aider-chat.nix, tests/modules/programs/aider-chat/aider.conf.yml, tests/modules/programs/aider-chat/default.nix, tests/modules/programs/aider-chat/example-config.nix
This PR adds a module for configuring [Aider-Chat](https://github.com/Aider-AI/aider).
```
```
=> aider-chat: add module

tests/tests.py
Pulling out of another PR for treewide test coverage I've been working on. Includes the actual path to the generated home manager generation from the failed test so you can inspect the files generated and understand why a test might not be successful with its assertions easier.
```
```
=> tests: improve debugging for failed test runs

modules/misc/news/2025/09/2025-09-29_16-23-12.nix, modules/programs/aliae.nix, tests/modules/programs/aliae/aliae.yaml, tests/modules/programs/aliae/default.nix, tests/modules/programs/aliae/settings.nix
This PR adds a module for configuring [aliae](https://github.com/jandedobbeleer/aliae).
```
```
=> aliae: add module

all-maintainers.nix, modules/programs/nushell.nix
=> treewide: remove aidalgol

modules/misc/news/2025/10/2025-10-05_15-18-28.nix, modules/programs/amber.nix, tests/modules/programs/amber/ambr.toml, tests/modules/programs/amber/ambs.toml, tests/modules/programs/amber/default.nix, tests/modules/programs/amber/settings.nix
This PR adds a module for configuring [Amber](https://github.com/dalance/amber).
```
```
=> amber: add module

modules/misc/news/2025/10/2025-10-06_20-28-22.nix, modules/programs/amfora.nix, tests/modules/programs/amfora/bookmarks.xml, tests/modules/programs/amfora/config.toml, tests/modules/programs/amfora/default.nix, tests/modules/programs/amfora/settings.nix
This PR adds a module for configuring [Amfora](https://github.com/makew0rld/amfora).
```
```
=> amfora: add module
