nix-community/home-manager

modules/default.nix, modules/programs/browserpass.nix
A module that installs the host application required by the [browserpass](https://github.com/dannyvankooten/browserpass) extension.
I just hacked this together this evening. A better alternative may be to ditch the install script and use `home.file` instead, but this works as well. I would also prefer to build from source.
=> browserpass: add module

README.md, default.nix, home-manager/default.nix, home-manager/home-manager, home-manager/home-manager.nix, modules/misc/news.nix, modules/programs/home-manager.nix
Instead of having the `<home-manager>` path point to the modules directory we let it point to the project root, i.e., the parent of the modules directory. With a few tweaks this allows the home-manager tool work directly with the GitHub archive. As a result the installation can be simplified and the home-manager module can automatically keep the installation up to date.
=> Change home-manager Nix path semantics

modules/files.nix, modules/lib/file-type.nix
It is currently possible to use a directory as source in `home.file` and the directory will be linked to the home directory. Sometimes, however, it is convenient to not link the directory itself but rather recursively link the files within the directory. This could possibly be accomplished by adding a Boolean option `recursive` that when `true` makes the `home-manager-files` derivation use `lndir` to link the directory.
=> Support recursive linking of source directories

CONTRIBUTING.md, modules/programs/gnome-terminal.nix
In particular, refer to the Nixpkgs guidelines and add a note about attribute names referencing packages in Nixpkgs. See #115 and https://github.com/NixOS/nixpkgs/pull/31668.
=> contributing: add basic style guidelines

README.md, default.nix, home-manager/install.nix
This changes the installation command from
nix-shell $HM_PATH -A install --run 'home-manager switch'
to
nix-shell $HM_PATH -A install
The added shell hook will print some useful information and run `home-manager switch`.
=> home-manager: use `shellHook` to install

modules/files.nix, modules/home-environment.nix, modules/lib/default.nix, modules/modules.nix, modules/programs/gnome-terminal.nix, modules/programs/home-manager.nix, modules/programs/info.nix, modules/services/polybar.nix, modules/services/window-managers/i3.nix, modules/services/window-managers/xmonad.nix, modules/systemd.nix
Also replace all imports of `dag.nix` by the entry in `config.lib`.
=> Add dag library to `config.lib`

README.md, modules/home-environment.nix, modules/lib/default.nix, modules/lib/shell.nix, modules/misc/news.nix, modules/misc/pam.nix, modules/programs/bash.nix, modules/programs/zsh.nix, modules/xsession.nix
This makes the `home.sessionVariables` explicitly use POSIX.2 style option values (like Bourne shell).
=> Session variables cleanup

modules/services/polybar.nix
Polybar treats 'include-file' property differently.
In particular, its value can't be enclosed in
double quotes. Fixes #185.
=> polybar: fix the case when config value is a path

default.nix, modules/home-environment.nix, modules/misc/news.nix, modules/modules.nix, modules/programs/home-manager.nix, modules/systemd-activate.sh, modules/systemd.nix, nixos/default.nix
With this it is possible to put, e.g.,
```nix
{
imports = [
(import (builtins.fetchTarball https://github.com/rycee/home-manager/archive/nixos-module.tar.gz) {}).nixos
];
users.users.jimdumree.isNormalUser = true;
home-manager.users.jimdumree = {
home.file."TEST".text = "foo";
home.packages = [ pkgs.nload ];
services.random-background = { enable = true; imageDirectory = "bgs"; };
};
}
```
in the system `configuration.nix` and the user environment will be set up when `nixos-rebuild switch` runs. No need to install Home Manager first.
Hacky for now and some HM modules won't work.
=> Experimental NixOS module

modules/programs/neovim.nix
so that we have the same options as in nixpkgs.
The configure options is a pain to use so I hope to improve it in nixpkgs at later date (to set $MYVIMRC, fix paths for neovim etc) but meanwhile we have to stick with this.
=> neovim: add 'configure' flag

modules/systemd.nix
Curiously the `who` command sometimes does not list logged-in users, resulting in systemd not being reloaded. Instead we use
systemctl --user is-system-running
to more directly detect whether systemd is running.
=> systemd: remove use of `who` command

modules/misc/news.nix, modules/programs/ssh.nix
This is needed to support overriding these options inside match blocks. A new option `programs.ssh.extraOptionOverrides` has been added to allow global overrides.
See #232 for rationale.
@league @Infinisil @jwiegley @Nadrieril Do you have any concerns about this change?
=> ssh: move options to end of configuration file

modules/xresources.nix
This adds an option xresources.include - this way bigger xresources file can easily included.
I added an example for solarized dark, directly from github.
A fair warning: I'm not very adept at nix yet, so I might have missed a thing or two, but I did my best. 
I'm not really sure if the example I've included is something that "works by accident" or something that "works by design" in nix, so I'd like your input on that :)
=> xresources: add option extraConfig

modules/programs/zsh.nix
This allows adding plugins to fpath without sourcing anything
My usecase is adding just the single plugin [pass](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/pass/_pass) from oh-my-zsh by doing:
```nix
{
programs.zsh.plugins = [
{
name = "pass";
src = "${pkgs.oh-my-zsh}/share/oh-my-zsh/plugins/pass";
}
];
}
```
Edit: Nothing gets sourced because the default used file `pass.plugin.zsh` doesn't exist. Before this change it would've given an error.
=> zsh: only source plugin file if it exists

modules/programs/bash.nix
This should allow use of the apostrophe character within aliases without having to escape them manually.
Fixes #273
=> bash: escape alias values

modules/services/compton.nix
`builtins.toString` returns the empty string or `1` for boolean values, so `toJSON` is required instead.
In other places this was done correctly so this just seems to be a missed case.
=> compton: fix syntax error

modules/misc/nixpkgs.nix
The `traceValIfNot` function is deprecated in Nixpkgs master. Instead use `traceSeqN`.
Fixes #301
=> nixpkgs: replace use of `traceValIfNot`

home-manager/home-manager
This adds an experimantal, undocumented, and unsupported flag `-2` for the `home-manager` command that enables the use of the new `nix` command instead of `nix-build`.
=> home-manager: add support for the nix tool

home-manager/home-manager
Home Manager needs an absolute and resolved path to its configuration file. The default configuration path is absolute but not necessarily resolved. For example, some users may have `~/.config` be a symbolic link to somewhere else. We therefore run the default configuration path through the `realpath` tool to resolve it.
Fixes #304
=> home-manager: resolve default configuration file path

home-manager/home-manager
It was previously possible to create the news information and lose it in a Nix GC before being able to view it. This also causes a switch to error out. This change makes the news information a root in the garbage collector.
Note, this change also removes the need for `nix eval` so the `doBuildAttr` function is simplified accordingly.
Fixes #327
=> home-manager: fix GC issue

modules/accounts/email.nix, modules/programs/mbsync-accounts.nix, modules/programs/mbsync.nix, modules/programs/notmuch-accounts.nix, modules/programs/notmuch.nix
This reworks the way program specific email account options are specified. In particular, we no longer use the deprecated `options` field of `mkOption`. Instead submodules are used.
=> Use submodules for program email accounts

modules/accounts/email.nix
This defaults to `/etc/ssl/certs/ca-certificates.crt` and will be picked up as default by the account specific option.
=> accounts.email: add global certificatesFile option

modules/services/window-managers/i3.nix
Add two missing bindings that are present in config generated by i3-config-wizard
1. window moves
2. switching focus between floating window and tiling windows
=> i3 module: add missing pieces to default config

modules/home-environment.nix
This _internal_ option indicates extra commands that should be run in the `postBuild` step of the profile environment build.
Fixes #386
=> home-environment: add option `home.extraProfileCommands`

modules/programs/go.nix
Fixes wrong example, which was added in #368
=> go: Fix package example

modules/services/mbsync.nix
The ExecStartPost command is currently started when the mbsync is
invoked succesfully. However, we typically want to run something like
'mu index' or 'notmuch new' after mbsync completes.  This changes the
unit type to oneshot, so that the ExecStartPost command is run after
mbsync finishes succesfully.
=> mbsync: change service unit type to 'oneshot'

home-manager/default.nix, home-manager/home-manager
This adds a new command to the home-manager shell script that allows
generations to be removed that are older than an given absolute or
relative date.
This allows users to manage the expiration of their home-manager
generations separately from their system or user profiles via
nix-collect-garbage. It is most important if the user desires to have
a convenient way to have different expiration times for Home Manager
generations than other system or user profiles.
=> home-manager: add generation expiration command

modules/programs/home-manager.nix
The manual install has been long deprecated so it should be safe to no longer attempt to do an uninstall on each activation.
=> home-manager: remove uninstall activation phase

modules/services/pasystray.nix
This enables the "volume control" and "control local sound server" menu options.
Fixes #461
=> pasystray: add paprefs and pavucontrol

.travis.yml, README.md, home-manager/install.nix
This avoids the uncontrollable nature of fetching the tarball as part of the evaluation. Instead the user can decide when to update and also perform rollbacks, if necessary.
=> Change installation instructions to use nix-channel

modules/services/dunst.nix, modules/services/polybar.nix, modules/services/window-managers/i3.nix
Unlike `attrs` type, `attrsOf` uses `mergeDefinitions` function when merging multiple declarations, see [nixpkgs/lib/types.nix#L284](https://github.com/NixOS/nixpkgs/blob/3873f43fc39d6662ffedc3e0413a8741558e5952/lib/types.nix#L284). This allows to override attribute values defined in another module.
The changes in the i3 module are trivial. Polybar and dust modules, however, use attributes to further transform it to INI format which makes the type definition quite advanced:
```
with types; either str (either bool (either int (listOf str)));
```
It would be nice to give users a possibility to override the values, especially because in the current implementation, nix will just choose one of the definitions (randomly?) and will silently ignore the other one.
Do you think it would be possible …
=> Sitch from attrs to attrsOf

modules/programs/emacs.nix
This option enables overriding packages within the generated Emacs package set.
Fixes #486
=> emacs: add `overrides` option

modules/misc/news.nix, modules/modules.nix
In particular, mark Linux specific modules as such.
=> Support conditional module loading

modules/services/dunst.nix
Since Dunst is DBus activated it is OK to simply kill it since DBus will restart it when necessary.
=> dunst: kill daemon on configuration change

modules/services/window-managers/i3.nix
For options that are not covered by the current nix options.
=> i3: add bar.extraConfig option

modules/programs/fish.nix
Makes fish use global scope for abbreviations.
This makes it so that they don't stick across config changes.
Before, an abbreviation would still exist even if removed from the config.
=> fish: use global for abbr

modules/programs/git.nix, tests/default.nix, tests/modules/accounts/email-test-accounts.nix, tests/modules/programs/git-with-email-expected.conf, tests/modules/programs/git-with-email.nix
This will allow, e.g., the character `@` in the email identity.
Also adds a test case.
Fixes #557
=> git: quote sendemail section header

modules/programs/git.nix, tests/modules/programs/git-expected.conf, tests/modules/programs/git.nix
This makes sure that values added to
programs.git.aliases
or
programs.git.extraConfig
are merged as expected.
Also add a few option examples.
=> git: use `attrsOf` instead of `attrs`

.travis.yml, default.nix
Having it there prevented, e.g., `nix-env -qaP` from working in some cases.
=> tests: remove tests attribute from root default.nix

modules/programs/firefox.nix
Since no official source of packages exist the option is hidden for now. For adventurous people there is an overlay of a few selected add-ons available at
https://rycee.gitlab.io/nixpkgs-firefox-addons/overlay.tar.gz
This overlay is automatically built daily using the REST API available on https://addons.mozilla.org/.
=> firefox: add support for add-on packages

home-manager/default.nix, modules/files.nix, modules/home-environment.nix
Instead use `runCommand`, which by default uses `stdenvNoCC` resulting in a reduced dependency footprint.
Fixes #612
=> Remove some use of `mkDerivation`

modules/default.nix
This is needed, for example, to support relative paths when disabling modules.
Related to #602.
=> modules: inform module system about the base modules path

modules/home-environment.nix, modules/xsession.nix
When set to `null` then the `xsession` module will not attempt to manage the keyboard settings.
=> home-environment: make `home.keyboard` optional

modules/misc/news.nix, modules/systemd.nix
This should allow more sensible merging behavior. In particular, with this change it is possible to use, for example, `mkForce` for greater control of merging.
Fixes #543
=> systemd: make the unit option type more robust

modules/services/emacs.nix, modules/systemd-activate.rb
Having 
```ini
X-RestartIfChanged = false
```
in the unit file will prevent the file from being restarted if a change is detected. This is useful if data loss may occur if the unit is suddenly restarted. For example, restarting the Emacs service may result in the loss of unsaved open buffers.
@nonsequitur I'm no Ruby expert so if you have time to have a look at my changes I'd appreciate it!
=> Support X-RestartIfChanged in systemd-activate.rb

modules/home-environment.nix, modules/misc/pam.nix, modules/programs/bash.nix, modules/programs/zsh.nix, tests/default.nix, tests/modules/home-environment/default.nix, tests/modules/home-environment/session-variables-expected.txt, tests/modules/home-environment/session-variables.nix, tests/modules/misc/pam/default.nix, tests/modules/misc/pam/session-variables-expected.txt, tests/modules/misc/pam/session-variables.nix, tests/modules/programs/bash/default.nix, tests/modules/programs/bash/session-variables-expected.txt, tests/modules/programs/bash/session-variables.nix, tests/modules/programs/zsh/default.nix, tests/modules/programs/zsh/session-variables.nix
Unfortunately, using `attrsOf` is not possible since it results in too eager evaluation. In particular, the
home.sessionVariables = {
FOO = "Hello";
BAR = "${config.home.sessionVariables.FOO} World!";
};
example will cause an infinite recursion.
This commit restores the option type of
- `home.sessionVariables`,
- `pam.sessionVariables`,
- `programs.bash.sessionVariables`, and
- `programs.zsh.sessionVariables`
to `attrs`. It also adds test cases for the above options to avoid regressions.
=> Fix type of various `sessionVariables` options

modules/misc/fontconfig.nix, tests/default.nix, tests/modules/misc/fontconfig/default.nix, tests/modules/misc/fontconfig/multiple-font-packages.nix, tests/modules/misc/fontconfig/no-font-package.nix, tests/modules/misc/fontconfig/single-font-package.nix, tests/modules/programs/tmux/not-enabled.nix
This fixes a build error occurring when building a configuration having fontconfig enabled and `home.packages` only containing one package installing things to `/lib`.
Also adds a number of test cases to verify the fontconfig cache generation functionality.
Fixes #703
=> fontconfig: fix build error

modules/programs/tmux.nix, tests/modules/programs/tmux/default.nix, tests/modules/programs/tmux/disable-confirmation-prompt.conf, tests/modules/programs/tmux/disable-confirmation-prompt.nix, tests/modules/programs/tmux/emacs-with-plugins.conf
Add a new option to tmux module in order to be able to disable confirmation prompt before killing a pane or window
=> tmux: Disable confirmation prompt

doc/default.nix, doc/man-home-manager.xml, doc/manual.xml, home-manager/completion.bash, home-manager/home-manager
This rewrite allows "long options" but unfortunately does not allow merged options such as `-vn`.
Also improve the home-manager manual page, with this it should include all sub-commands and arguments.
Finally, include the home-manager manual page in the generated HTML documentation.
=> home-manager: rewrite argument parsing

modules/services/gpg-agent.nix
This lets gpg-agent serve specific keys with authentication capability as SSH keys. Note `null` is different from an empty list for this option - `null` means the `sshcontrol` file is manually controlled, `[]` means all SSH keys are disabled.
=> gpg-agent: add sshcontrol configuration

modules/misc/qt.nix, modules/services/taffybar.nix, modules/xsession.nix, tests/default.nix, tests/modules/misc/xsession/basic-xprofile-expected.txt, tests/modules/misc/xsession/basic-xsession-expected.txt, tests/modules/misc/xsession/basic.nix, tests/modules/misc/xsession/default.nix
This option lists the environment variables to be imported into the systemd user session.
Also add a basic test of the xsession module.
=> xsession: add option `importedVariables`

modules/misc/xdg.nix
We can avoid the activation block by instead creating a hidden file in the directory.
=> xdg: create cache directory using keep file

modules/systemd-activate.rb
Hey, this little commit enables `home-manager` to automatically handle systemd sockets during activation.
Resolves https://github.com/rycee/home-manager/issues/708
=> systemd-activate.rb: add start/stop/restart sockets

modules/programs/alot.nix
By adding these settings we'll be able to access drafted/sent messages.
=> alot: added send/draf_box to configuration file

modules/programs/zsh.nix
I added a new config option for zsh:
The new initExtraBeforeCompInit option enables the user to inject commands in zshrc before compinit is executed.
I need this option because I want to set the fpath and other options manually before compinit is executed
=> zsh: add initExtraBeforeCompInit config option

modules/programs/zsh.nix
Add envExtra option in zsh to inject commands into .zshenv
=> zsh: add envExtra option

modules/accounts/email.nix, modules/programs/irssi.nix, modules/programs/ssh.nix, modules/services/mpd.nix, modules/services/mpdris2.nix
This changes the type of all options that specify ports to `types.port`. This type restricts values to between 0 and 65535.
=> Use `types.port` where applicable

doc/man-home-manager.xml, home-manager/home-manager
These options will be passed through to the `nix-build` tool.
=> home-manager: support a few extra pass-through options

modules/programs/chromium.nix, modules/programs/emacs.nix, modules/programs/firefox.nix, modules/programs/fish.nix, modules/programs/git.nix, modules/programs/go.nix, modules/programs/keychain.nix, modules/programs/mbsync.nix, modules/programs/mercurial.nix, modules/programs/neovim.nix, modules/programs/opam.nix, modules/programs/pidgin.nix, modules/programs/tmux.nix, modules/programs/urxvt.nix, modules/services/compton.nix, modules/services/dwm-status.nix, modules/services/mbsync.nix, modules/services/mpdris2.nix, modules/services/polybar.nix, modules/services/redshift.nix, modules/services/stalonetray.nix, modules/services/status-notifier-watcher.nix, modules/services/taffybar.nix, modules/services/unclutter.nix, modules/services/window-managers/awesome.nix, modules/services/window-managers/i3.nix, modules/services/window-managers/xmonad.nix, modules/services/xembed-sni-proxy.nix
By using `literalExample` the documentation will show the option default without surrounding quotes.
=> Fix option `defaultText` when referencing packages

doc/default.nix, modules/manual.nix
This is to allow network-less rebuilding of a generation after a garbage collection.
Fixes #819
=> manual: add nmd as a generation dependency

modules/programs/vim.nix
Hey, I introduced a bug in https://github.com/rycee/home-manager/pull/792 where the default plugin `sensible` was not added if any plugins were defined. This fixes the issue.
Fixes https://github.com/rycee/home-manager/pull/792#issuecomment-526342006
=> vim: always add sensible plugin

modules/programs/rofi.nix
Seems to be one missing `types.string` in `modules/programs/rofi.nix`
=> rofi: string -> str

modules/xsession.nix, tests/modules/misc/xsession/basic-xprofile-expected.txt, tests/modules/misc/xsession/basic-xsession-expected.txt
=> xsession: remove bashisms in start scripts

modules/services/mpd.nix
This allows specifying, for example, the music directory using path literals without causing the directory to be copied to the Nix store.
Suggested-by: Silvan Mosberger <infinisil@icloud.com>
=> mpd: allow path literal values in options

modules/programs/git.nix
Add suport for [`gitattributes(5)`](https://www.git-scm.com/docs/gitattributes)
=> git: add attributes support

modules/programs/termite.nix
depends on https://github.com/NixOS/nixpkgs/pull/70776
closes #864
=> termite: use vte-ng at pkgs.termite.vte-ng

modules/programs/getmail.nix, tests/modules/programs/getmail-expected.conf
Fixed bug where "accounts.email.accounts.\<name\>.imap.port" option was being ignored in getmail.
Note: I'm new to Nix language.
=> getmail: add port option

tests/modules/misc/xsession/basic.nix, tests/modules/misc/xsession/keyboard-without-layout.nix, tests/modules/programs/alacritty/empty-settings.nix, tests/modules/programs/alacritty/example-settings.nix, tests/modules/programs/bash/session-variables-expected.txt, tests/modules/programs/bash/session-variables.nix, tests/modules/programs/firefox/profile-settings.nix, tests/modules/programs/firefox/state-version-19_09.nix, tests/modules/programs/git-with-email.nix, tests/modules/programs/git-with-str-extra-config.nix, tests/modules/programs/git.nix, tests/modules/programs/gpg/override-defaults.nix, tests/modules/programs/tmux/disable-confirmation-prompt.nix, tests/modules/programs/tmux/emacs-with-plugins.conf, tests/modules/programs/tmux/emacs-with-plugins.nix, tests/modules/programs/tmux/vi-all-true.nix, tests/modules/programs/zsh/session-variables.nix, tests/modules/services/window-managers/i3-keybindings-expected.conf, tests/modules/services/window-managers/i3-keybindings.nix
This replaces some derivation outputs by simple strings rather than full Nix store paths. This removes the need to download the whole derivation when all we need is a static string.
=> tests: reduce number of downloads

modules/programs/emacs.nix
It's deprecated and since Nixos 19.09 it's an alias to `emacsPackages`.
This fixes using home-manager with the [emacs overlay](https://github.com/nix-community/emacs-overlay).
Note: This will break for users on 19.03.
=> emacs: Don't use emacsPackagesNg

modules/programs/astroid.nix
Using the absolute path of maildir folders is required for Astroid to save
messages in those.
=> astroid: fix maildir folder paths

modules/programs/khal-calendar-accounts.nix, modules/programs/khal.nix, modules/programs/vdirsyncer.nix
* khal: add option `locale`
Plus same changes as in #775 which got lost, probably when 8450842e4957915243decef882f3cece2b54463d was force-pushed, now manually rebased on top of the latter:
* vdirsyncer: fix options `userName`, `userNameCommand`
* khal: add khal-account options `color` and `priority`
=> khal, vdirsyncer: add and fix options (lost #775 rebased on top of current branch and extended)

modules/programs/vscode.nix
If I enable this module without using the userSettings option it will
create an empty settings.json. We use mkIf to prevent this on the default
value.
=> vscode: don't create an empty settings.json

modules/programs/mbsync.nix
=> mbsync: skip maildir creation if no account is defined

modules/systemd.nix
The reload can actually fail when trying to warn about degraded units because it was running the `--state=failed` query incorrectly, and then it wouldn't actually reload anything:
```
The user systemd session is degraded:
Failed to connect to bus: No such file or directory
home-manager.service: Main process exited, code=exited, status=1/FAILURE
```
=> systemd: fix degraded warning

modules/programs/keychain.nix
The shell command is added in the interactiveShellInit, as it is the
equivalent of initExtra in bash or zsh.
=> keychain: add fish shell integration

home-manager/install.nix
This sets the state version in recent installs to the latest released version. It is beneficial for people to be aware of this option and it is also good to help new users get a more recent setup.
=> install: add state version to initial configuration

modules/programs/lsd.nix
Introduces a fish (Friendly Interactive SHell) support for the `programs.lsd.enableAliases` option.
=> lsd: add shell aliases for fish

modules/programs/neovim.nix
The `programs.neovim.configure` option is consistent with NixOS's [`wrapNeovim`](https://github.com/NixOS/nixpkgs/blob/bd62dd3bb37a5d9686a92e4be8a36d2e13637b2b/pkgs/applications/editors/neovim/wrapper.nix#L22).
closes #971
closes https://github.com/kalbasit/shabka/issues/286
=> neovim: un-deprecate the `configure` option

modules/programs/neovim.nix
This is a back-porting of #971 
Closes https://github.com/kalbasit/shabka/issues/286
Mentioning participants:
@rycee 
@Gerschtli 
@kalbasit
=> neovim: un-deprecate the `configure` option (backport)

doc/default.nix, doc/release-notes/rl-2003.adoc, modules/default.nix, modules/files.nix, modules/home-environment.nix, modules/lib/default.nix, modules/lib/file-type.nix, modules/lib/stdlib-extended.nix, modules/lib/types.nix, modules/manual.nix, modules/misc/dconf.nix, modules/misc/qt.nix, modules/modules.nix, modules/programs/info.nix, modules/programs/mbsync.nix, modules/systemd.nix, nix-darwin/default.nix, nixos/default.nix, tests/default.nix
This change makes use of the `extend` function inside `lib` to inject a new `hm` field containing the Home Manager library functions. This simplifies use of the Home Manager library in the modules and reduces the risk of accidental infinite recursion.
=> Switch to extended Nixpkg's `lib`

modules/programs/vim.nix
I am doing some work on the nixpkgs vim infra that broke vim aliases for me, which made me spot this.
=> vim: avoid using alias of vim-sensible

modules/services/window-managers/i3-sway/sway.nix
The restart command does not exists in sway, only reload.
See https://github.com/swaywm/sway/blob/1.4/sway/sway.5.scd
```
```
See [CONTRIBUTING](https://github.com/rycee/home-manager/blob/master/CONTRIBUTING.md#commits) for more information and [recent commit messages](https://github.com/rycee/home-manager/commits/master) for examples.
=> sway: remove restart command from sway configuration

modules/programs/kakoune.nix
The `ModuleLoaded` hook was missing.
- ~[ ] Test cases updated/added. See [example](https://github.com/rycee/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).~
```
```
=> kakoune: add missing hook name

modules/programs/git.nix, tests/modules/programs/git/git-expected-include.conf, tests/modules/programs/git/git-expected.conf, tests/modules/programs/git/git-with-email-expected.conf, tests/modules/programs/git/git-with-str-extra-config-expected.conf, tests/modules/programs/git/git.nix
This should handle the special characters that typically occur.
Fixes #1206
=> git: escape string values in configuration

modules/files.nix, tests/modules/files/default.nix, tests/modules/files/out-of-store-symlink.nix
Using this function it is possible to make `home.file` create a symlink to a path outside the Nix store. For example, a Home Manager configuration containing
home.file."foo".source = config.lib.file.mkOutOfStoreSymlink ./bar;
would upon activation create a symlink `~/foo` that points to the absolute path of the `bar` file relative the configuration file.
Inspired by https://github.com/adisbladis/nixconfig/blob/53457d0f20a67571b3847cb32a49a143d9c99c2d/home-adisbladis-nixpkgs/home.nix#L6-L8
=> files: add helper function `mkOutOfStoreSymlink`

.travis.yml, README.md, doc/installation.xml, modules/lib-bash/activation-init.sh
Using the `nix-env` command is far more robust. It also has the benefit that if the per-user `profiles` and `gcroots` directories do not exist then they will be created with the correct permissions.
Because of the second point this commit also removes the `mkdir` step of the installation instructions.
=> home-manager: use `nix-env` to list generations

modules/lib-bash/activation-init.sh
This adds an empty `nix-build` command to verify that the user is having a good Nix install. It also, as a side effect, will create the necessary per-user `profiles` and `gcroots` directories.
=> activation: add Nix sanity check

modules/programs/firefox.nix
This adds a note that the extensions will only apply to profiles managed through Home Manager.
=> firefox: update extensions option description

.github/CODEOWNERS, modules/misc/vte.nix, modules/modules.nix, modules/programs/gnome-terminal.nix
This abstracts out the VTE setup from the gnome-terminal module into its own module and options.
=> vte: add module

modules/services/fluidsynth.nix
I messed up the description of fluidsynth in #1326. The description as "music player daemon" was left over from the MPD module I used as a basis. Fluidsynth should really be described as midi synthesizer. :)
=> fluidsynth: fix description

modules/accounts/email.nix, modules/programs/alot.nix, modules/programs/astroid.nix, modules/programs/getmail.nix, modules/programs/lieer.nix, modules/programs/mbsync.nix, modules/programs/msmtp.nix, modules/programs/neomutt.nix, modules/programs/notmuch.nix, modules/programs/offlineimap.nix, modules/services/lieer.nix
This removes the long list of submodules from
modules/accounts/email.nix
and instead move each entry to its owning module.
=> Move email account options to their owning modules

modules/programs/kakoune.nix
The option `keyMappings.*.mode` only supported the builtin modes, but in kakoune you can define custom ones.
The option now accepts a string instead of the enum so one can define key mappings for user modes as well.
User modes are declared automatically.
- ~[ ] Test cases updated/added. See [example](https://github.com/rycee/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).~
```
```
=> kakoune: support user modes in keyMappings

modules/services/window-managers/i3-sway/sway.nix
The example for wayland.windowManager.sway.config.output has to
contain a mode behind the filename to be correct.
The example for wayland.windowManager.sway.config.output has to
contain a mode behind the filename to be correct. This does not break
anything but is confusing.
The `emacs-service` testcase fails. But I believe that is not something I have caused.
```
```
=> sway: Fix output example

modules/home-environment.nix, nix-darwin/default.nix, nixos/default.nix
Before the profile directory value would point directly to the build output in the Nix store. Unfortunately this would cause an infinite loop if the user's configuration directly or indirectly refers to the profile directory value.
CC @cole-h
=> home-environment: use per-user profile path in /etc

modules/programs/zsh.nix
Adds [global aliases](http://zsh.sourceforge.net/Intro/intro_8.html) to programs.zsh.
```
```
=> zsh: add shellGlobalAliases

modules/programs/zsh.nix
The `cdpath` option in Zsh makes it easy to `cd` to sub-directories of the paths specified. [ThoughtBot wrote a blog post](https://thoughtbot.com/blog/cding-to-frequently-used-directories-in-zsh) about it which includes a nice example.
```
```
=> zsh: add `cdpath` option

doc/release-notes/rl-2009.adoc, modules/misc/nixpkgs.nix, modules/modules.nix
This removes the dependency on the `nixpkgs` channel within the modules. This can be used to override the Nixpkgs version. It is also a prerequisite for creating a Home Manager flake.
=> nixpkgs: take Nixpkgs path from argument

modules/files.nix, tests/modules/files/default.nix, tests/modules/files/target-with-shellvar.nix
The previous implementation would allow variables to sneak into the file names. This commit makes sure the resulting target file path exactly matches the expected path.
=> files: make sure the target file name is escaped

doc/release-notes/rl-1903.adoc, modules/lib/file-type.nix
loaOf has been deprecated for a long time and is now in the process of
removal (see https://github.com/NixOS/nixpkgs/pull/96042). Thus, we
remove it here, too.
Fixes https://github.com/rycee/home-manager/issues/1472.
```
```
=> lib/file-type: remove types.loaOf

modules/programs/htop.nix
There's some new configuration options since the 3.0.0 release of htop, so I went through and made sure to add everything I could find.
=> htop: Add new configuration options

modules/programs/zplug.nix, tests/modules/programs/zplug/modules.nix
Running `zplug install` will always product output, even if there is
nothing to do.
Gating it behind a `zplug check` eliminates that output when there is
nothing to do, and is recommended in the zplug README.
```
```
=> zplug: Reduce noise

modules/misc/news.nix, modules/systemd.nix
systemd is supposed to be spelled systemd (lowercase d) or sÿstëmd (only on high holidays) according to https://www.freedesktop.org/wiki/Software/systemd/.
```
```
=> systemd: fix systemd spelling

modules/services/mpd.nix
Allows using [Storage Plugins](https://www.musicpd.org/doc/html/plugins.html?highlight=nfs#storage-plugins) other than local.
```
```
=> mpd: change musicDirectory to str

modules/misc/news.nix, modules/programs/man.nix, tests/default.nix, tests/modules/programs/man/apropos.nix, tests/modules/programs/man/default.nix, tests/modules/programs/man/no-manpath.nix
man: Add support for apropos by building a manpage database
The apropos software is useful to get a list of manpages matching a description or to get a list of all manpages. The latter feature is used by Emacs to get manpage completion (M-x man).
To have apropos working, a database of all available manpages must be built with mandb. This is what this commits does.
A [similar change was done for NixOS](https://github.com/NixOS/nixpkgs/commit/edc6a76cc025ef972979dad6692e0fd5d5cfcbbb).
=> Generate man cache files

modules/programs/info.nix
This avoids the need for the activation block. The `dir` file is instead built directly in the installed profile.
CC @league
```
```
=> info: generate dir file directly in profile

.github/CODEOWNERS, modules/misc/numlock.nix, tests/default.nix, tests/modules/misc/numlock/default.nix, tests/modules/misc/numlock/numlock.nix
- Add evanjs to CODEOWNERS for numlock and numlock test
- Add evanjs to maintainers for numlock module
```
```
=> numlock: add test

modules/services/window-managers/i3-sway/sway.nix
I use home-manager as a NixOS module which means there's a systemd unit running as part of the boot process as opposed to when you use home-manager separately from your NixOS config (or when you're not on NixOS I suppose). That's likely when one would encounter this issue.
So, with that said, for a while now - many months actually - I've had an error from home-manager on boot at the "Activating onFIlesChange" message which in turn meant that the unit didn't run properly. As soon as I started sway and reran the unit however, it ran successfully. For a while I thought it may be something odd in my configuration since it's quite customized so I didn't look too closely at home-manager since I figured others would have encountered this issue.
When I finally had a look I found that the cause of …
=> sway: fix onChange for sway config when sway isn't running

modules/services/window-managers/i3-sway/lib/options.nix
Fixes #1515 . Example for `wayland.windowManager.config.startup`
referenced options `notification` and `workspace` which are not valid
for sway.
```
```
=> sway: fix startup example

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/mu.nix
mu: add module
mu is a Maildir indexing program. Right now, there are 2 common
versions (that I know of) that are in-use: 1.2.x and 1.4.x.
Right now, the mu package maintainer does NOT anticipate adding a
configuration file, so there is no need to add options to allow that
to happen. Additionally, there are a few notable differences between
the 2. However, these options are handled as command-line
flags/options when performing the initial index and database creation.
These changes happened in v1.4, and are documented at
https://github.com/djcb/mu/releases/tag/1.4
mu: add myself, KarlJoad, as maintainer to Repo
```
```
See [CONTRIBUTING](https://github.com/rycee/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more …
=> mu: add module

modules/programs/feh.nix, tests/default.nix, tests/modules/programs/feh/default.nix, tests/modules/programs/feh/feh-bindings-expected-buttons, tests/modules/programs/feh/feh-bindings-expected-keys, tests/modules/programs/feh/feh-bindings.nix, tests/modules/programs/feh/feh-empty-settings.nix
In feh you can bind multiple keys to the same action, but home-manager
only let you set a single key to an action. Now you could cheat and pass
a string with space-separated keys, but with this change you can pass
a list for each action to bind multiple keys to it.
I've also added a couple of tests.
Fixes #1366
```
```
=> feh: allow binding actions to multiple buttons/keys by passing a list

modules/home-environment.nix, tests/modules/home-environment/default.nix, tests/modules/home-environment/session-path.nix
Sometimes I'll have some things installed to my dot files that provide
a collection of executables (doom-emacs, org-capture), or need a
`$HOME/bin` or similar to keep a handful of quick scripts and wanted to
be able to do it decrlaratively.
```
```
=> home-environment: allow adding to $PATH

home-manager/home-manager
Resolves https://github.com/nix-community/home-manager/issues/1496. It turns out that `exec` does not support $EDITOR values containing arguments, eg. "code --wait". This is in contrast to the majority of tools (git, etc) that do support this usage.
```
```
=> Use `eval` instead of `exec` when running $EDITOR

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/autojump.nix, modules/programs/bash.nix, tests/default.nix, tests/modules/programs/autojump/default-settings.nix, tests/modules/programs/autojump/default.nix
Add a standalone module for autojump
This adds (implicitly enabled) options for bash (already available), fish, and zsh.
- Add test case for autojump (`programs.autojump.enable = true`)
- Add `mkRenamedOptionModule` option for `programs.bash.enableAutojump`
```
```
___
I have not done any home-manager tests before, and I'm open to any feedback related to the naming of the test cases, if additional tests should be added, or the existing test should be modified.
Also, I was initially tempted …
=> autojump: add module

modules/programs/neomutt.nix, tests/modules/programs/neomutt/hm-example.com-expected, tests/modules/programs/neomutt/hm-example.com-msmtp-expected.conf
The `accounts.email.accounts.<name>.neomutt.extraConfig` option is included twice in the resulting config file for the account. One time as part of the `mraSection`, one time as part of `accountStr` (`accountStr` includes the `mraSection`). This removes that duplication. I opted to keep the one in `accounStr`, since `extraConfig` doesn't necessarily have anything to do with the `mraSection`.
Fixes #1214.
```
```
=> neomutt: fix duplicated extraConfig in account

modules/programs/neovim.nix
Add an option to add packages to the PATH of nvim.  This may be usefull to make extra programes availible for plugins and/or for usage in `:! myprogram`
Fixes: #894 
I created this because I needed this myself. This is my first PR here, feedback is very welcome.
```
```
- Added myself as module maintainer. See [example](https://github.com/rycee/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).
- Added myself and the module files to …
=> neovim: add extraPackages

modules/modules.nix
Make module `programs.chromium` available on all platforms, rather than restricting it on Linux only.
Although nixpkgs doesn't provide a usable chromium app on macOS, users can still implement their own derivation for installing chromium app, such as:
```nix
{ stdenv, fetchurl, unzip, undmg }:
stdenv.mkDerivation rec {
pname = "chromium";
version = "804618";
buildInputs = [ unzip undmg ];
sourceRoot = ".";
phases = [ "unpackPhase" "installPhase" ];
installPhase = ''
mkdir -p "$out/Applications"
cp -r chrome-mac/Chromium.app "$out/Applications/Chromium.app"
'';
src = fetchurl {
name = "Chromium-${version}.zip";
url = "https://commondatastorage.googleapis.com/chromium-browser-snapshots/Mac/${version}/chrome-mac.zip";
sha256 = "12hq4sr7i7qm6qrz4pqgcdaxd9nw30blhvpki2m6ck3lmk0zc0a3";
};
meta = …
```
=> chromium: enable it for all platforms

nixos/default.nix
Pass NixOS system configuration as an optional parameter to home-manager modules when home-manager is invoked as part of NixOS configuration.
My specific use case is building user-level VMs which reference host system config, but this seems like something generally useful.
```
```
=> nixos: pass system config to HM modules

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/zsh.nix, modules/programs/zsh/prezto.nix, tests/modules/programs/zsh/default.nix, tests/modules/programs/zsh/prezto.nix
This commit adds support for [prezto](https://github.com/sorin-ionescu/prezto), an alternative to oh-my-zsh. Currently it depends on https://github.com/NixOS/nixpkgs/pull/59134 to some extent (this pull request actually makes it so that `$HOME/.zpreztorc` is sourced).
=> zsh: add support for prezto configuration framework

modules/programs/firefox.nix
Because this module overrides firefox nixpkgs config, Gnome Shell integration doesn't work.
See [services.gnome3.chrome-gnome-shell.enable](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/desktops/gnome3/chrome-gnome-shell.nix).
This PR fixes it.
```
```
=> firefox: add enableGnomeExtensions option

modules/services/emacs.nix, tests/modules/services/emacs/emacs-emacsclient.desktop
Can generate the file directly to avoid the dependency on the `makeDesktopItem` API.
=> emacs: remove use of makeDesktopItem

modules/lib/maintainers.nix, modules/programs/waybar.nix
I recently had my first package added to nixpkgs and am now in the official list of maintainers so this information is no longer required here.
``` console
$ nix flake list-inputs
git+file:///home/nicolas/dev/github.com/home-manager
└───nixpkgs: github:NixOS/nixpkgs/a920bf43082e35faad01a5cc43d5212dfc3c9f26
$ nix eval 'github:NixOS/nixpkgs/a920bf43082e35faad01a5cc43d5212dfc3c9f26#lib.maintainers.berbiche'
{ email = ...; github = ...; ... }
```
=> Remove myself from HM's maintained maintainers list

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/gh.nix, tests/default.nix, tests/modules/programs/gh/config-file.nix, tests/modules/programs/gh/default.nix
Add module for new GitHub CLI Tool.
**Note**: I ran all tests but like in master the evaluation failed but my added test cases work.
```
$ nix-shell --pure tests -A run.all
trace: warning: In file /home/tobias/projects/home-manager/tests/lib/types/list-or-dag-merge.nix
a list is being assigned to the option 'tested.dag'.
This will soon be an error due to the list form being deprecated.
Please use the attribute set form instead with DAG functions to
express the desired order of entries.
trace: warning: In file /home/tobias/projects/home-manager/tests/lib/types/list-or-dag-merge.nix
a list is being assigned to the option 'tested.dag'.
This will soon be an error due to the list form being deprecated.
Please use the attribute set form instead with DAG functions to
express the desired order of …
```
=> gh: add module

modules/misc/xdg.nix, tests/modules/misc/xdg/default.nix, tests/modules/misc/xdg/file-attr-names.nix
Currently, the following results in chaos:
```nix
{
xdg = {
configFile.name.text = "config";
dataFile.name.text = "data";
#dataFile.name.source = ./file; # or for more confusion!
};
#home.file.name.text = "root"; # this would conflict as well
}
```
The xdg module tries to `mkMerge` the separate definitions into `home.file` because they have the same attr name, even though their `.target` paths differ. Adding any sort of unique prefix prevents this from happening. This change technically isn't backward-compatible because it could be observed in the case that someone is actually relying on the existing behaviour (is there any sane reason to set both `xdg.configFile.name.x` and `home.file.name.y`, expecting them to be the same file?).
```
```
See …
=> xdg: disambiguate file attr names

modules/systemd.nix, tests/modules/systemd/services-expected.conf, tests/modules/systemd/services.nix
This causes list values to be emitted as a list of key-value pairs instead of a single key-value pair where the value is space separated.
This is useful, e.g., for socket units that would like to specify more than one `ListenStream=` address.
=> systemd: use `listsAsDuplicateKeys` in `toINI`

modules/services/emacs.nix
Using `emacsGit` or `emacsGcc` from `nix-community/emacs-overlay` with `services.emacs.client.enable = true` results in a collision at `$home-path/share/applications/emacsclient.desktop`.
The collision is avoided by wrapping the desktop item derivation with `hiPrio`. 
```
```
=> emacs: avoid desktop file collision

modules/services/mpd.nix
Support systemd socket activation and allow the mpd binary to be customized.
the choice of making it an enum could be broken out into separate enable options, though I wasn't sure how to have home-manager spit out multiple `ListenStream` lines into the generated ini.
```
```
=> MPD socket activation

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/caffeine.nix
> Caffeine is a little daemon that sits in your systray, and prevents the screensaver from showing up, or the system from going to sleep. It does so when an application is fullscreened (eg: youtube), or when you click on the systray icon (which you can do, when, eg: reading).
See https://github.com/caffeine-ng/caffeine-ng.
I didn't add any tests since we are not generating any config for the service at the moment.
```
```
=> caffeine: add service

.github/workflows/test.yml
CI: Update nix-install-action to v11
Release notes: https://github.com/cachix/install-nix-action/releases/tag/v11
```
BREAKING: By default it has no nixpkgs configured, you have to set nix_path
by picking a channel
or pin nixpkgs yourself.
Support self-hosted runners by not installing Nix if it's already installed
Add extra_nix_config option to specify extra nix.conf options
```
```
```
=> CI: Update nix-install-action to v11

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/i3status-rust.nix, tests/default.nix, tests/modules/programs/i3status-rust/default.nix, tests/modules/programs/i3status-rust/with-custom.nix, tests/modules/programs/i3status-rust/with-default.nix, tests/modules/programs/i3status-rust/with-extra-settings.nix, tests/modules/programs/i3status-rust/with-multiple-bars.nix
This adds the i3status-rust module, a replacement for `i3status` written in pure Rust.
See: https://github.com/greshake/i3status-rust
Configuration file is in TOML format, and I chose to keep the options loosely typed (according to https://github.com/Infinisil/rfcs/blob/config-option/rfcs/0042-config-option.md) to avoid expected frequent breaking with upstream changes in i3status-rust.
```
```
=> i3status-rust: add module

doc/release-notes/rl-2103.adoc, modules/misc/news.nix, modules/programs/broot.nix
The `invocation` is an optional attribute, so it doesn't make sense to use it as the key in an attribute set. See https://dystroy.org/broot/documentation/configuration/#verb-definition-attributes
Actually, `invocation` should not be defined when one wants to rebind a built-in verb to a different key, so the current configuration is restrictive.
Also added documentation for the `key` attribute.
This change is not backwards compatible.
```
```
=> broot: improve configuration

modules/programs/zsh.nix
This change add dirHashes option for `zsh` module to utilize the named directory hash table feature offered by `zsh`. Once example configuration is added, at shell prompt one can then refer to `$HOME/Documents` as `~docs`, `$HOME/Downloads` as `~dl`, et. al.
```
```
=> zsh: Add dirHashes option

modules/services/window-managers/i3-sway/sway.nix, tests/modules/services/window-managers/sway/sway-default.nix, tests/modules/services/window-managers/sway/sway-followmouse-legacy.nix, tests/modules/services/window-managers/sway/sway-followmouse.nix, tests/modules/services/window-managers/sway/sway-post-2003.nix
Using the final package in the `onChange` block broke some use cases. This restores the old behavior and instead solves the test dependencies in a different way.
Fixes #1611
=> sway: restore use of pkgs.sway

modules/programs/zsh.nix
Some zsh features must go at top of `.zshrc` e.g.:
```
initFirst = ''
if [[ -r "''${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-''${(%):-%n}.zsh" ]]; then
source "''${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-''${(%):-%n}.zsh"
fi
'';
```
```
```
=> zsh: add initFirst option

modules/programs/alacritty.nix, modules/programs/astroid-accounts.nix, modules/programs/astroid.nix, modules/programs/beets.nix, modules/programs/direnv.nix, modules/programs/git.nix, modules/programs/matplotlib.nix, modules/programs/mercurial.nix, modules/programs/neovim.nix, modules/programs/qutebrowser.nix, modules/programs/taskwarrior.nix, modules/programs/urxvt.nix, modules/programs/vscode.nix, modules/services/dwm-status.nix, modules/services/hound.nix, modules/services/xsuspender.nix, tests/modules/programs/alacritty/default.nix, tests/modules/programs/alacritty/settings-merging-expected.yml, tests/modules/programs/alacritty/settings-merging.nix, tests/modules/programs/vscode/keybindings.nix
Replaces all instances of:
- `types.attrs` with `types.attrsOf types.anything` where it made sense
- `types.attrs` with `pkgs.format.{json,yaml,ini}` where it made sense
There are places where replacing `types.attrs` broke the evaluation and so wasn't done:
- pam
- home-environment
- bash
- zsh
- [x ] Code formatted with `./format`.
```
```
=> treewide: replace attrs by formats or types.anything

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/services/wlsunset.nix, tests/default.nix, tests/modules/services/wlsunset/default.nix, tests/modules/services/wlsunset/wlsunset-service-expected.service, tests/modules/services/wlsunset/wlsunset-service.nix
This PR adds a service module for `wlsunset`, a program for day/night gamma adjustments
on wayland. This module was requested in #1625.
Only think that I am not quite satisfied with is the description for `gamma`, but I couldn't figure out what exactly it does and upstream doesn't seem to say much about it aswell.
```
```
=> wlsunset: add module

modules/programs/waybar.nix, tests/modules/programs/waybar/systemd-with-graphical-session-target.service
The current definition makes waybar wait for dbus.service, but that never happens because dbus.service is started on demand by dbus.socket.
Per systemd docs: https://www.freedesktop.org/software/systemd/man/systemd.service.html#Implicit%20Dependencies
- Services with Type=dbus set automatically acquire dependencies of type Requires= and After= on dbus.socket.
- Socket activated services are automatically ordered after their activating .socket units via an automatic After= dependency. Services also pull in all .socket units listed in Sockets= via automatic Wants= and After= dependencies.
Removing Requisite/After makes the service properly start for me, simply specifying Type=dbus is enough.
Refs #1370
```
```
See …
=> waybar: fix systemd service

modules/programs/zathura.nix
=> zathura: allow configuring the package used

modules/systemd.nix
This PR allows creating systemd slices.
```
```
=> systemd: allow creating slices

modules/programs/msmtp.nix
msmtp fails with broken pipe error: #1635
Removing the newline from the command output makes the error disappear. As of version 1.8.0 the newline is also not required anymore: https://marlam.de/msmtp/news/msmtp-1-8-0/
NixOS stable has msmtp version 1.8.x, so this should be backwards compatible for at least stable.
```
```
=> msmtp: fix passwordeval

modules/targets/generic-linux.nix, tests/modules/targets-linux/generic-linux.nix
export LOCALE_ARCHIVE_2_27 to fix locales on non nixos. this environment variable is nixpkgs-specific so it should not interfere with other software.
```
```
=> targets/genericLinux: make locales work

README.md, flake.nix
Hello o/
Accessing the home-manager lib is useful, especially for extending home manager functionality such as adding entries to dags.
When using flakes, we cannot do path imports such as `<home-manager/modules/lib>`, this MR adds the attribute `lib.hm` to the flake provided by home-manager.
=> Add home-manager lib to flake.nix

modules/programs/chromium.nix
Brave Browser is a chromium-based browser, too.
+ it use the same web store with Chromium and Google Chrome.
+ the machanism of installing extensions works, and it's verified on
my macOS box.
```
```
=> chromium: add support for brave

modules/services/dunst.nix
Fixes #744
Only adds support for legacy icons for dunst
```
```
=> dunst: Include also legacy icons

modules/programs/tmux.nix, tests/modules/programs/tmux/default.nix, tests/modules/programs/tmux/prefix.conf, tests/modules/programs/tmux/prefix.nix, tests/modules/programs/tmux/shortcut-without-prefix.conf, tests/modules/programs/tmux/shortcut-without-prefix.nix
It was not possible to set an arbitrary tmux prefix, ctrl was hardcoded
in the module.
To avoid breaking existing configs I implemented a new option which can
conveniently use the tmux terminology but defaults to null and doesn't
affect behavior when set to null.
I did not completely replicate the behavior for the shortcut option,
i.e., I do not bind "b" to send-prefix but stick to the default of the
prefix binding sending prefix (C-b C-b instead of C-b b) and I do not
bind repetition of the prefix (C-b C-b) to `last-window`, both of these
bring the option closer to the default tmux configuration.
Fixes #1237
I added a test for the new option and one to ensure it doesn't break the old one when set to null.
```
```
See …
=> Add a prefix option overruling shortcut if defined

modules/programs/starship.nix, tests/modules/programs/starship/settings-expected.toml, tests/modules/programs/starship/settings.nix
As of Starship 0.45.0, [`prompt_order` has been replaced with `format`](https://starship.rs/migrating-to-0.45.0/#prompt-order-has-been-replaced-by-a-root-level-format).
> Previously to v0.45.0, prompt_order would accept an array of module names in the order which they should be rendered by Starship.
> 
> Starship v0.45.0 instead accepts a format value, allowing for customization of the prompt outside of the modules themselves.
```
```
=> starship: update prompt_order to format in example

modules/services/mako.nix
Mako allows for more configuration, specifically options in sections of the form `[field=value field2=value2 ...]`. This can be useful for things like in the example and having different colors for urgency levels.
```
```
=> mako: Add extraConfig attribute

README.md
The only other place this is documented is here: https://github.com/nix-community/home-manager/blob/8b3fca4ec5e879f608473fe851cc5077dfb19bbd/modules/misc/news.nix#L515-L525
That is not enough clarity. This change disambiguates by virtue of the well known Jon Doe placeholder.
=> Disambiguate

.github/dependabot.yml
Configure GH's dependabot to file pull requests automatically that updates our GitHub actions. 
This is needed to avoid finding the CI in a failing status as I did in https://github.com/nix-community/home-manager/pull/1673.
```
```
=> github: configure dependabot to file PRs to auto-update GH actions

README.md, flake.nix
cherry picked commit 6dc8de259a36313ebd1ee25b075174e396f53329 authored in https://github.com/nix-community/home-manager/pull/1634.
```
```
=> flake: expose Home Manager lib

modules/programs/gnome-terminal.nix
Turn on/off the terminal's bell. A small video showcasing how the `audible-bell` key controls the terminal's bell: 
```
```
=> gnome-terminal: Add audibleBell option

modules/programs/waybar.nix, tests/modules/programs/waybar/settings-complex-expected.json, tests/modules/programs/waybar/settings-complex.nix
Fixes #1682.
Previously, a warning would be emitted if a module was specified with a CSS identifier `battery#bat1` (the part after the hash).
cc: @jwijenbergh
```
```
=> waybar: improve warnings to allow using CSS ids in a module's name

modules/programs/neovim.nix, tests/modules/programs/neovim/plugin-config.nix
instead of wrapping the configuration, which has sideeffects just put the init.vim in its expected place
https://github.com/NixOS/nixpkgs/issues/55376
This relies on a function I may change in the future so not sure we should merge this (but if I change it in nixpkgs, I would update the module straightaway).
```
```
=> programs.neovim: write config in $XDG_CONFIG_HOME/init.vim

tests/asserts.nix, tests/default.nix, tests/modules/programs/git/git-with-str-extra-config.nix, tests/modules/programs/lieer/lieer.nix, tests/modules/programs/waybar/broken-settings.nix, tests/modules/programs/waybar/settings-complex.nix, tests/modules/services/lieer/lieer-service.nix
This adds basic support for asserting the presence/content of warnings. All tests will by default assert that no warnings are present.
See https://github.com/nix-community/home-manager/pull/1687 and https://github.com/nix-community/home-manager/pull/1687
```
```
=> Support test assertions on warnings

modules/programs/direnv.nix
This is needed for the latest version of direnv. See
https://github.com/direnv/direnv/issues/742
```
```
=> direnv: fix the fish source

modules/misc/news.nix, modules/modules.nix, modules/programs/octant.nix
Added octant module based on obs module
Might need to wait for octant & starboard-octant-plugin to make it to nixpkgs unstable before this is useful
Octant is in unstable but the starboard plugin isn't yet https://search.nixos.org/packages?channel=unstable&show=starboard&from=0&size=30&sort=relevance&query=octant
```
```
=> octant: add module

modules/programs/nushell.nix
=> nushell: fix link in the description (fixes #1693)

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/plan9port.nix
Add a services module for setting up the plan9port file-systems, these are closely related to the acme editor.
```
```
=> plan9port: init services module

home-manager/completion.zsh, home-manager/default.nix
Add zsh completion to home-manager based on work from @Sean1708 see  #1075
Looks like
```
$ home-manager<TAB>
-- command --
build               -- build
edit                -- edit
expire-generations  -- expire generations
generations         -- list generations
help                -- help
news                -- read the news
packages            -- managed packages
remove-generations  -- remove generations
switch              -- switch
uninstall           -- uninstall
$ home-manager -<TAB>
-- option --
-b                 -- backup files                                                                                                                                         
--cores            -- cores …
```
=> home-manager: add zsh completion

README.md
Rephrases the warning section of the README file.
```
```
=> docs: rephrase warning section slightly

modules/programs/fish.nix
Fix for changes in nixpkgs fish plugin organisation on unstable:
https://github.com/NixOS/nixpkgs/commit/d94921db12d9c9e2d3e9c2e6e25e50f03f789ecb
fixes #1701  #1702 
```
```
=> fish: Fix regression due to changes in nixpkgs.

README.md
=> Remove extra ` from README.md

modules/services/window-managers/i3-sway/lib/options.nix, tests/modules/services/window-managers/sway/default.nix, tests/modules/services/window-managers/sway/sway-null-package.conf, tests/modules/services/window-managers/sway/sway-null-package.nix
Fixes #1714
First commit refactors the `moduleName` check to use variables, it can be dropped if unnecessary.
cc: @alexarice
```
```
=> Sway: fix bar command when package is null

modules/programs/neomutt.nix, tests/modules/programs/neomutt/hm-example.com-expected
neomutt's smtp_pass configuration option was incorrectly quoted to evaluate a shell command given by `accounts.email.accounts.<name>.passwordCommand`.
```
```
=> neomutt: fix smtp_pass option

modules/services/sxhkd.nix, tests/modules/services/sxhkd/configuration.nix, tests/modules/services/sxhkd/service.nix
Fixes #1598.
@JonathanReeve I don't use sxhkd, can you confirm this PR resolves your issue?
```
```
=> sxhkd: configurable package and command line arguments

modules/programs/mu.nix
----
This just adds the command line flag to the `mu` command to specify the personal email addresses.
I think the email addresses specified as aliases should also be included, should I open a new pull req for that?
```
```
=> mu: fix command

modules/programs/chromium.nix
The guessed browser name is wrong here, ungoogled-chromium simply uses "chromium" as configuration name.
```
```
=> chromium: Support ungoogled-chromium

modules/misc/dconf.nix
Fixes #1731
-------
Hopefully fixes error when activating a configuration containing dconf settings when no previous dconf setup exists for the user.
```
```
=> dconf: make sure the configuration directory exists

modules/programs/chromium.nix
We currently check `isPath` and `isString` on crxPath and version
respectively, which is
(1) pointless because the module system already does such checks
(2) wrong because isPath means path literal. a derivation therefore is not a path.
```
```
=> chromium: Fix preinstallation of crx files

doc/default.nix, doc/manual.xml, nix-darwin/default.nix, nixos/default.nix
Makes the manual include generated option documentation for NixOS and nix-darwin modules.
```
```
=> docs: NixOS and nix-darwin option documentation

doc/release-notes/rl-2103.adoc, modules/lib/maintainers.nix, modules/programs/mpv.nix, tests/default.nix, tests/modules/programs/mpv/default.nix, tests/modules/programs/mpv/mpv-example-settings-expected-bindings, tests/modules/programs/mpv/mpv-example-settings-expected-config, tests/modules/programs/mpv/mpv-example-settings.nix, tests/modules/programs/mpv/mpv-invalid-settings-expected.json, tests/modules/programs/mpv/mpv-invalid-settings.nix
This allows mpv module to be customized with support for more advanced features than the `programs.mpv.scripts` current support. For example, with this change now this is possible:
```nix
{
programs.mpv.package = (pkgs.wrapMpv (pkgs.mpv-unwrapped.override {
vapoursynthSupport = true;
}) {
extraMakeWrapperArgs = [
"--prefix" "LD_LIBRARY_PATH" ":" "${pkgs.vapoursynth-mvtools}/lib/vapoursynth"
];
});
}
```
Since `programs.mpv.package` doesn't necessary reflect the final derivation anymore (see #1524), we introduce `programs.mpv.finalPackage` that has the resulting derivation.
Closes issue #1725.
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and …
=> mpv: fix issue #1725 and add tests

modules/services/nextcloud-client.nix
Allows one to configure nextcloud to use a different package than the
default package.
```
```
=> Add option services.nextcloud.package

modules/programs/chromium.nix
Provide brave browser on the release-20.09 branch.
```
```
=> [release-20.09 backport] chromium: add support for brave

.github/CODEOWNERS, modules/config/i18n.nix, modules/modules.nix, modules/targets/generic-linux.nix, tests/default.nix, tests/modules/config/i18n/default.nix, tests/modules/home-environment/session-path.nix, tests/modules/home-environment/session-variables-expected.txt, tests/modules/home-environment/session-variables.nix, tests/modules/systemd/session-variables-expected.conf, tests/modules/systemd/session-variables.nix, tests/modules/targets-linux/generic-linux.nix
Currently, Home Manager sets the `LOCALE_ARCHIVE_2_27` environment variable when `targets.genericLinux` is enabled. However, this doesn't cover NixOS, where it's common to mix stable and unstable versions of nixpkgs, causing occasional locale breakages.
This PR addresses the NixOS use case by setting `LOCALE_ARCHIVE_2_27` environment variable for all Linux platforms with some additional improvements:
- Also enable for GUI applications with systemd session variables
- Set the appropriate `LOCALE_ARCHIVE_x_xx` by checking the version of glibcLocale
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit …
=> i18n: set the appropriate LOCALE_ARCHIVE_x_xx variable

.github/CODEOWNERS, doc/release-notes/rl-2103.adoc, modules/programs/rofi.nix, tests/modules/programs/rofi/default.nix, tests/modules/programs/rofi/valid-config-expected.rasi, tests/modules/programs/rofi/valid-config.nix
The Xresources configuration format is deprecated in Rofi. For example, using Rofi from unstable (1.6.1 as of now) you get the following warnings when starting the application:
```
(process:9272): Rofi-WARNING **: 01:38:48.596: The old Xresources based configuration format is deprecated.
(process:9272): Rofi-WARNING **: 01:38:48.596: Please upgrade: rofi -upgrade-config.
``````
So this commit migrates it for its new configuration format, called rasi instead.
This new implementation uses attrsets manipulation instead of using strings, making the code clearer and also fixing some bugs found during the way. This is mostly an implementation detail though, since this change is mostly backwards compatible with the old one (the only option that is not backwards compatible is …
```
=> rofi: migrate to rasi configuration format

modules/services/redshift.nix
If you disable the redshift's fade animation with options `[ "-o" "-P" ]`, you'll
notice that redshift continually reddens your screen every three
seconds. Running `journalctl --user -lfu redshift` confirms that this is because
redshift is restarting every three seconds per the systemd configuration that
home-manager currently generates. You can confirm this `systemctl --user cat
redshift`.
I'm unsure why we should continually restart redshift. I'm using the
"on-failure" setting for my setup, which works just fine.
=> Change systemd restart policy for redshift

modules/services/spotifyd.nix
#1754 
configure spotifyd with toml as it now expects, instead of ini
- [N/A] Change is backwards compatible.
- [N/A] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).
=> fix: change spotifyd config format ini -> toml

modules/programs/rofi.nix, tests/modules/programs/rofi/custom-theme-config.rasi, tests/modules/programs/rofi/custom-theme.nix, tests/modules/programs/rofi/custom-theme.rasi, tests/modules/programs/rofi/default.nix, tests/modules/programs/rofi/valid-config.nix
With this PR now it is possible to define a custom theme directly using Nix, like this:
```nix
{
programs.rofi.theme = {
"*" = {
background-color = "#000000";
border-color = "FFFFFF";
width = 512;
};
listview = {
cycle = true;
};
};
}
```
And this will be converted to the proper rasi format to be used in rofi.
```
```
=> rofi: add support to custom themes

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/services/playerctld.nix, tests/default.nix, tests/modules/services/playerctld/basic.nix, tests/modules/services/playerctld/default.nix
Add a module that sets up playerctld as a service
```
```
=> playerctld: add module

modules/default.nix
`stdenv.lib` is deprecated with `pkgs.lib` being it's replacement.
```
```
=> modules: don't reference deprecated stdenv.lib

modules/programs/rofi.nix, tests/modules/programs/rofi/custom-theme.nix, tests/modules/programs/rofi/custom-theme.rasi
Just a small thing that I missed from #1748. This is now supported without the need of using strings to represent them:
https://github.com/davatorium/rofi-themes/blob/9a843caa86d15038fda5455b7fb951569dbd227a/Official%20Themes/solarized.rasi#L134
```
```
=> rofi: add support for lists in rasi

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/programs/sbt.nix, tests/default.nix, tests/modules/programs/sbt/credentials.nix, tests/modules/programs/sbt/default.nix, tests/modules/programs/sbt/plugins.nix
Adds a new module for the sbt build tool (https://scala-sbt.org). I'm using this in my home manager config, thought someone else could also benefit from it :)
For now, it only supports adding global plugins / credentials.
```
```
=> sbt: Add new module

modules/programs/vscode.nix, tests/modules/programs/vscode/keybindings.nix
=> vscode: Add `args` option to keybindings, make `when` optional

modules/programs/neovim.nix
@jlesquembre  like this ?
Fixes https://github.com/nix-community/home-manager/issues/1739 
```
```
=> neovim: suffix path with extraPackages

modules/programs/mbsync-accounts.nix, modules/programs/mbsync.nix
The `SubFolders` option in mbsync controls the folder naming style
in the maildir.  There are three different styles:
* Verbatim - `<maildirPath>/top/sub/subsub`
* Maildir++ - `<inboxPath>/.top.sub.subsub` (used by Dovecot)
* Legacy - `<maildirPath>/top/.sub/.subsub`
Previously, the `SubFolders` option was hardcoded to `Verbatim`.  This
change allows configuration of the `SubFolders` option.
```
```
=> mbsync: add subFolders option

doc/release-notes/rl-2105.adoc, modules/services/redshift-gammastep/gammastep.nix, modules/services/redshift-gammastep/lib/options.nix, modules/services/redshift-gammastep/redshift.nix, tests/modules/services/redshift-gammastep/gammastep-basic-configuration-expected.service, tests/modules/services/redshift-gammastep/gammastep-basic-configuration-file-expected.conf, tests/modules/services/redshift-gammastep/gammastep-basic-configuration.nix, tests/modules/services/redshift-gammastep/redshift-basic-configuration-expected.service, tests/modules/services/redshift-gammastep/redshift-basic-configuration-file-expected.conf, tests/modules/services/redshift-gammastep/redshift-basic-configuration.nix
Not every option is exposed by redshift/gammastep parameters, for example gamma options are only exposed in configuration file. So this PR refactors this module to generate a configuration file and pass it to the redshift/gammastep using -c parameter.
This is a breaking change since there is no support for some of the older options like `extraOptions`, but unless you use `extraOptions` it should work without changes.
Partial port of https://github.com/NixOS/nixpkgs/pull/108739, but with the necessary changes that makes more sense for how HM module evolved (since it is quite different from the Nixpkgs one).
This refactoring also follows RFC42 as much as possible.
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/maste …
=> redshift/gammastep: use ini file instead of passing parameters

doc/release-notes/rl-2105.adoc, modules/services/redshift-gammastep/gammastep.nix, modules/services/redshift-gammastep/lib/options.nix, modules/services/redshift-gammastep/redshift.nix, tests/modules/services/redshift-gammastep/gammastep-basic-configuration-expected.service, tests/modules/services/redshift-gammastep/gammastep-basic-configuration-file-expected.conf, tests/modules/services/redshift-gammastep/gammastep-basic-configuration.nix, tests/modules/services/redshift-gammastep/redshift-basic-configuration-expected.service, tests/modules/services/redshift-gammastep/redshift-basic-configuration-file-expected.conf, tests/modules/services/redshift-gammastep/redshift-basic-configuration.nix
Second try of PR #1751, including fix for `latitude`/`longitude`/`duskTime` options.
```
```
=> redshift/gammastep: use ini file instead of passing parameters, 2nd try

modules/programs/obs-studio.nix
This PR adds an option to specify which obs package to install.
```
```
=> obs-studio: Allow package to be configurable

modules/programs/firefox.nix
Drop the `enableAdobeFlash` option for firefox.
It was removed in nixpkgs (https://github.com/NixOS/nixpkgs/pull/112335) and now causes an error on rebuilds.
```
error: Your configuration mentions firefox.enableAdobeFlash. All plugin related options have been removed, since Firefox from version 52 onwards no longer supports npapi plugins (see https://support.mozilla.org/en-US/kb/npapi-plugins).
```
- sans the newsboat test
```
```
=> firefox: drop enableAdobeFlash option

modules/programs/rofi.nix, tests/modules/programs/rofi/custom-theme.nix, tests/modules/programs/rofi/custom-theme.rasi
Support `@import` (or any other top-level option) in `programs.rofi.theme`.
See https://github.com/nix-community/home-manager/pull/1748#issuecomment-774995577 for details.
```
```
=> rofi: support top-level clauses in rasi

flake.nix, modules/default.nix
This allows flake user to pass extra arguments to all modules.
Backport of commit cf5dad76c1ee452224da39f13129c4ff84351a5c.
```
```
=> [20.09] flake: add extraSpecialArgs

modules/programs/bash.nix
The bash module always sets `HISTFILE="$HOME/.bash_history"` in the bashrc. This makes it impossible to tell bash to use a different `HISTFILE` by setting the `HISTFILE` environment variable
HISTFILE=/tmp/bash_history bash
This changes the default value of `programs.bash.historyFile` to `"${HISTFILE:-$HOME/.bash_history}"`, so the environment variable is used when it is set.
Fixes #962 
- I got this error running the tests, but it doesn't seem related:
error: --- EvalError ----------------------------------------------------------- nix-shell
at: (17:20) in file: /home/olmo/.local/src/home-manager/modules/programs/i3status-rust.nix
16| 
17|   settingsFormat = pkgs.formats.toml { };
|                    ^
18| 
attribute 'formats' missing
```
``` …
=> bash: don't unconditionally set HISTFILE variable

modules/services/redshift-gammastep/gammastep.nix, modules/services/redshift-gammastep/redshift.nix
It was not working since I forgot to inherit imports from commonOptions.
Closes the issue from this comment: https://github.com/nix-community/home-manager/pull/1751#discussion_r576446407. Alternative PR for #1803.
```
```
=> redshift/gammastep: fix deprecated options warning

doc/release-notes/rl-2105.adoc, modules/programs/neovim.nix
The `configure` option is not type checked and an artifact of how
nixpkgs is implemented.
We now have the equivalent options in home-manager and managing
interactions between the 2 systems complexifies maintainance of the
module.
Please use the other options at your disposal:
configure.packages.*.opt  -> programs.neovim.plugins = [ { plugin = ...; optional = true; }]
configure.packages.*.start  -> programs.neovim.plugins = [ { plugin = ...; }]
configure.customRC -> programs.neovim.extraConfig
```
```
- If …
=> neovim: deprecate programs.neovim.configure

modules/misc/news.nix, modules/services/polybar.nix, tests/modules/services/polybar/basic-configuration.conf, tests/modules/services/polybar/basic-configuration.nix
Polybar's config format is a bit strange, and lists in particular are annoying to handle. This enables using normal nix lists and nested attrsets instead.
I had to  create a new option because this change would not be backwards-compatible, because the INI converter currently converts lists of strings to space-separated values, and this new option does something else. I expect that this is only relevant for the `modules-left` etc bar setting, but that's enough to break things :(.
I'm not sure how to name this new option. I named it `settings` because I thought we might decide to deprecate `config` in its favor later.
```
```
See [CONTRIBUTING](https://github.com/rycee/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more …
=> polybar: allow config to be more nix-like

modules/targets/darwin/default.nix, modules/targets/darwin/fonts.nix
Enable Home Manager fonts on macOS. Fonts are copied instead of being symlinked because macOS won't recognize symlinked fonts.
```
```
=> targets/darwin: copy fonts to ~/Library/Fonts/HomeManager

modules/programs/gpg.nix, tests/modules/programs/gpg/override-defaults-expected.conf, tests/modules/programs/gpg/override-defaults.nix
Fixes #1644 by converting lists to duplicate keys.
The second commit fixes the example `settings` configuration to use `literalExample`.
```
```
=> gpg: allow for duplicate keys in config

nix-darwin/default.nix, nixos/default.nix
closes #1698
This allows users of the nixos and nix-darwin module to set shared modules for all users and extra specialArgs to be available to home-manager modules.
The latter is named extraSpecialArgs just like the argument to modules/default.nix. This could be confusing since the the two are independent in code, but they do mean the same thing so I think the name fits.
```
```
=> nixos: add sharedModules and extraSpecialArgs options

modules/programs/fzf.nix
Fixes #1020 
The environment variable FZF_CTRL_R_COMMAND has never existed
according to `git grep FZF_CTRL_R_COMMAND $(git rev-list --all)`
and `git log -G FZF_CTRL_R_COMMAND`.
This PR marks the option `historyWidgetCommand` as removed and removes all associated logic.
```
```
=> fzf: remove non-working historyWidgetCommand option

modules/programs/kakoune.nix
Fix `undefined variable 'group' ...` error when trying to configure kakoune hook.
```
```
=> Fix kakoune hook group

modules/programs/starship.nix
Matches zsh's check with bash and fish, checking for a dumb terminal and
allowing vterm inside Emacs.
See #1238 and #1248
```
```
=> Starship: improve zsh terminal check

modules/services/pulseeffects.nix
Fix #1824 by adding an option to specify the pulseeffects package
```
```
=> pulseeffects: add option to specify package

modules/programs/alot.nix
Fixes #1601
Alot uses the first email in the config as primary email. Because the order in which the email.accounts were sorted was alphabetical, the account set to `primary = true` was not put first in the alot config and thus not considered as primary email for alot.
This was fixed by sorting the email accounts again such that accounts with `primary = true` come first.
```
```
=> alot: set primary email first

modules/programs/gh.nix, tests/modules/programs/gh/config-file.nix
This PR fixes setting the git protocol that the `gh` tool uses.
home-manager currently sets the key to `gitProtocol`, which is incorrect.
This PR sets the key to `git_protocol`.
```
```
=> gh: fix protocol setting

modules/misc/news.nix, modules/programs/git.nix, tests/modules/programs/git/default.nix, tests/modules/programs/git/git-with-msmtp-expected.conf, tests/modules/programs/git/git-with-msmtp.nix
If a user using msmtp to send all their email, it would be preferred if
git used it as well.
The only settings necessary are to set the smtp server to the msmtp
binary and set envelop sender to true, which makes git call msmtp with
the -f flag to set the from address from the email.
```
```
=> git: rely on msmtp for smtp if msmtp is enabled

modules/misc/news.nix, modules/programs/git.nix, tests/modules/programs/git/git-with-msmtp-expected.conf, tests/modules/programs/git/git-with-msmtp.nix
The value should be "auto", not `true`.
Also fix news entry.
```
```
=> git: correct value of envelopeSender for msmtp

modules/programs/getmail.nix, tests/modules/programs/getmail/getmail-expected.conf
Getmail's configuration mailboxes value must be a tuple of string or the string "ALL". The generated value was broken if `accounts.email.accounts.<name>.getmail.mailboxes` was a list of only one string (but not "ALL"): the generated expression `( "str" )` was not a tuple but a string. It worked for "ALL" because getmail accept this string as a special case.
Now, we always generate a tuple (by adding a comma, even with a list of size one) except if the option is set to "ALL":
- `"ALL"` generates `mailboxes = ( 'ALL' )`
- `[ "INBOX" ]` generates `mailboxes = ( 'INBOX',  )` (instead of incorrect `mailboxes = ( 'INBOX' )`)
- `[ "INBOX" "Drafts" ]` generates `mailboxes = ( 'INBOX', 'Drafts',  )`
- to maintain backwards compatilibty, `[ "ALL" ]` still generates `mailboxes = ( 'ALL' )`
``` …
```
=> getmail: fix configuration mailboxes generation

doc/release-notes/rl-2105.adoc, home-manager/home-manager, modules/lib-bash/color-echo.sh, modules/misc/news.nix
This PR changes home-manager to respect the NO_COLOR environment
variable to disable coloring from output generated by home-manager.
This initiative can be found more on https://no-color.org/
- ~~[ ] Code formatted with `./format`.~~
- ~~[ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).~~
```
```
- ~~[ ] Added myself as module maintainer. See …
=> home-manager: Respect NO_COLOR

modules/programs/git.nix, tests/modules/programs/git/git-with-email-expected.conf, tests/modules/programs/git/git-with-email.nix, tests/modules/programs/git/git-with-msmtp-expected.conf
If you have a custom SSL certificate configured for SMTP TLS, git should
use it.
```
```
=> git: Add configured SSL certificate for SMTP

modules/misc/qt.nix, tests/default.nix, tests/modules/misc/qt/default.nix, tests/modules/misc/qt/qt-platform-theme-gnome.nix, tests/modules/misc/qt/qt-platform-theme-gtk.nix
This allows you to set a theme for Qt applications. For example, if you want to use `adwaita-qt` theme to have uniform look between Gtk and Qt applications, you can use it like this:
```nix
{
qt = {
enable = true;
platformTheme = "gnome";
style = {
name = "adwaita";
package = pkgs.adwaita-qt;
};
};
}
```
```
```
=> qt: add qt.style option

modules/programs/qutebrowser.nix, tests/modules/programs/qutebrowser/keybindings.nix, tests/modules/programs/qutebrowser/settings.nix
Fix #1774 by adding a `loadAutoconfig` option 
```
```
=> qutebrowser: add option to load autoconfig

modules/programs/waybar.nix, tests/modules/programs/waybar/systemd-with-graphical-session-target.service
Set the systemd user service to use "mixed" killmode, which lets waybar stop its module scripts itself. This fixes issues where waybar blocks shutdown until systemd sends a SIGKILL to waybar child processes.
This is mostly relevant when waybar is run with custom scripts, but should not have any negative impact otherwise. Also see man pages for `systemd.kill(5)`. 
```
```
=> waybar: fix slow service stop

modules/targets/generic-linux.nix, tests/modules/targets-linux/generic-linux.nix
This makes terminfo descriptions in installed packages available to shell sessions. Not needed for NixOS, which does the same thing already.
```
```
=> targets/genericLinux: set TERMINFO_DIRS

doc/release-notes/rl-2105.adoc
Add documentation for `qt.style` and `programs.rofi.theme` changes in release notes for 21.05 release.
```
```
=> docs: document qt.style and programs.rofi.theme changes

modules/programs/offlineimap.nix
This allows me to use offlineimap with passwordstore. I guess nobody uses a newline in their password?
Tests seem to be broken atm? `attribute 'anything' missing`
```
```
=> offlineimap: Strip newlines from offlineimap passwordcommand

modules/programs/broot.nix, modules/programs/nushell.nix, modules/programs/starship.nix
Use [`formats.toml`](https://nixos.org/manual/nixos/stable/#sec-settings-nix-representable) to build configurations
```
```
=> Use formats.toml to generate configurations

modules/programs/lsd.nix
lsd 0.19.0 added support for a configuration file
```
```
=> lsd: add support for config file 

modules/programs/neovim.nix
I have some ad-hoc neovim plugins in my home-manager config. I don't really care about plugin versions so I prefer to define them with just `name` instead of needing both `pname` and `version`. If you search github for `buildVimPluginFrom2Nix` you'll see lots of others doing the same thing. Right now if you use a package without `pname` with a config snippet you'll get an error about missing `pname` because of this comment in the neovim config labeling the plugin's config. This PR falls back to `name` when `pname` isn't present.
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit …
=> neovim: fall back to plugin name if pname does not exist

modules/programs/chromium.nix
Fixes #1383 by removing the `extensions` option for proprietary Chromium versions (Google Chrome, Google Chrome Beta, Google Chrome Dev).
```
```
cc @bb2020 @ivankovnatsky
=> chromium: remove 'extensions' option for proprietary Chrome versions

doc/installation.adoc
Fixing the `darwin-rebuild --switch` command on the manual 
to `darwin-rebuild switch` because the `--switch` flag does 
not exists.
```
```
=> docs: fix darwin-rebuild command

modules/programs/jq.nix
As documented here: https://stedolan.github.io/jq/manual/#Colors
```
```
=> jq: Use default upstream values for colors

modules/programs/git.nix
Install delta when it's enabled, similar to `git-lfs` a few lines above. Without this change, `delta` isn't available outside `git` (running `delta` outputs: `The program ‘delta’ is currently not installed`)
```
```
=> git: install delta when it's enabled

nix-darwin/default.nix, nixos/default.nix
functionTo tries to evaluate functions too quickly and prevents sharedModules from accessing the pkgs argument.
Fixes #1878.
```
```
=> nixos/nix-darwin: switch sharedModules type to anything instead of functionTo

modules/services/dunst.nix
Fix a small discrepancy in the documentation for the dunst module.
```
```
=> dunst: update documentation on settings

modules/services/window-managers/xmonad.nix
The libFiles option allows home-manager to manage additional files for
xmonad in `.xmonad/lib`. The advantage of doing it like this compared to
just using `home.file.".xmonad/lib/File.hs".source` is, that we can
detect file changes and recompile xmonad accordingly.
This commit adds an option `libFiles` that allows to add additional files to `.xmonad/libs/`.
The xmonad recompilation process can access files stored in this directory as modules, therefore they can influence the configuration. When we would add these files via  `home.file.".xmonad/lib/File.hs".source`, changes to them would not cause xmonad to be recompiled, thereby making it necessary to call `xmonad --recompile && xmonad -- restart` after `home-manager switch`.
If such files are added via the new `libFiles` option, changes …
=> xmonad: add libFiles option

modules/programs/bash.nix
Resolves #1843. Allows aliases to be expanded in `initExtra`, and adds a visible `bashrcExtra` option for commands that should be run in `~/.bashrc` even by non-interactive shells.
```
```
=> bash: improve initialisation

modules/misc/news.nix, modules/programs/dircolors.nix, tests/modules/programs/dircolors/settings-expected.conf
This patch changes the `dircolors` module so that `dircolors.extraConfig` is applied after `dircolors.settings`. This allows `extraConfig` to override the default settings.
Previously if a colour was set in both `settings` and `extraConfig`, `settings` would take precedence. The reverse is now the case and so this is a **breaking change**. Consequently, I have added a news entry. The impact should be fairly minor: I don't see how this could break an existing config, just slightly modify the behaviour for a config that was arguably ill-formed in the first place. 
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and [recent commit …
=> dircolors: apply extraConfig after settings

modules/programs/git.nix, tests/modules/programs/git/default.nix, tests/modules/programs/git/git-with-signing-key-id-expected.conf, tests/modules/programs/git/git-with-signing-key-id.nix, tests/modules/programs/git/git-without-signing-key-id-expected.conf, tests/modules/programs/git/git-without-signing-key-id.nix
Thus by default the signing key is selected by commit’s author.
Imagine you have 2 PGP keys with these UIDs:
1. `John Smith <john.smith@foo.bar>`
2. `John Smith <john.smith@at.work>`
By default you set Git `user.name` as `John Smith` and `user.email` as `john.smith@foo.bar` (e.g. via Home Manager). But in some repo you do `git config user.email 'john.smith@at.work'`. If you provide a signing key in `home-manager.users.USERNAME.programs.git.signing.key` (which is currently a required field, before this MR) your commits will be signed with that key in all the repos by default. Even in that one where you changed `user.email`, you would have to pay attention to not forget to change the signing key explicitly in that repo too along with the email. But with this change if you don’t set that …
=> Make Git signing key id be optional

modules/services/window-managers/xmonad.nix
Fixes #1891 
If the configuration is `null`, the compiled configuration`xmonadBin` should not be used and instead the WM startup command should be set to the bare `xmonad` binary.
```
```
=> xmonad: use compiled configuration when config is not null

doc/man-home-manager.xml, home-manager/home-manager, modules/home-environment.nix
Improves on #1828. Afer looking at the home-manager script I realized it wouldn't actually be too much work to just implement a flake option to home-manager. `home-manager build/switch --flake uri[#name]` now builds/switches to the
`homeConfigurations.<name>` output of the flake located at `uri` (name defaults to username). The lock-file options should also work*.
Hasn't been implemented for:
* Instantiate: NixOS/nix#3908. Shouldn't (?) be implemented.
* Edit: Not sure if it can be done in a nice way, `nix edit` currently opens a read-only version even if the flake uri is a path.
* News: Shouldn't be too difficult, but I'm not quite sure how the news output works.
I have also added an entry to man page, but it doesn't mention the lock-file options (`man nixos-rebuild` doesn't mention them …
=> home-manager: Add --flake option to home-manager

modules/programs/neomutt.nix, tests/modules/programs/neomutt/default.nix, tests/modules/programs/neomutt/hm-example.com-gpg-expected.conf, tests/modules/programs/neomutt/hm-example.com-msmtp-expected.conf, tests/modules/programs/neomutt/neomutt-with-gpg.nix
Adds support for `encryptByDefault` to the neomutt module using the `crypt_opportunistic_encrypt` option.
```
```
=> neomutt: Add encryptByDefault support

modules/programs/git.nix, tests/modules/programs/git/default.nix, tests/modules/programs/git/git-with-signing-key-id-expected.conf, tests/modules/programs/git/git-with-signing-key-id.nix, tests/modules/programs/git/git-without-signing-key-id-expected.conf, tests/modules/programs/git/git-without-signing-key-id.nix
Backport #1886 to `release-20.09` branch.
```
```
=> Backport “Make Git signing key id be optional” to “release-20.09”

modules/misc/gtk.nix
After #1848, if specified, home-manager will use `gtk.font.size` when writing `.config/gtk-3.0/settings.ini,` but won't when writing Dconf settings.
Simply apply the same change made to the ini attribute.
```
```
=> gtk: use font.size option in dconf

modules/programs/msmtp.nix
It is appended to the end of msmtprc instead of top like extraConfig.
Fix: #1707 
```
```
=> msmtp: add extraAccounts option

modules/programs/neomutt.nix, tests/modules/programs/neomutt/neomutt-expected.conf, tests/modules/programs/neomutt/neomutt-not-primary-expected.conf, tests/modules/programs/neomutt/neomutt-with-binds-expected.conf
I need to set `$folder` manually because I'd like to use multiple accounts with neomutt. `home-manager` just sets `$folder` to the location of the primary account, which makes sense if you only want to use one account, but messes up the way mailboxes are displayed if you use multiple accounts. This PR makes it possible to override settings already configured by home-manager, such as `$folder`.
```
```
=> programs.neomutt: Make manual configuration have higher precedence than generated settings

.github/CODEOWNERS, modules/services/window-managers/i3-sway/sway.nix, tests/modules/services/window-managers/sway/default.nix, tests/modules/services/window-managers/sway/sway-default.conf, tests/modules/services/window-managers/sway/sway-followmouse-expected.conf, tests/modules/services/window-managers/sway/sway-followmouse-legacy-expected.conf, tests/modules/services/window-managers/sway/sway-modules.conf, tests/modules/services/window-managers/sway/sway-modules.nix
Supersedes and Closes #1663
* Added seat configuration to sway config. Also improved the way that the configuration is generated to reduce superfluous whitespace.
* I also added myself as a maintainer of the sway module. Please let me know if I'm not allowed to do this.
```
```
- If this PR adds a new module (this is not a new module, but I added myself anyway)
=> sway: add seat config

.github/CODEOWNERS, doc/release-notes/rl-2105.adoc, modules/programs/newsboat.nix, tests/modules/programs/newsboat/default.nix, tests/modules/programs/newsboat/newsboat-basics-2105.nix
As of Newsboat 2.19, configuration using XDG_CONFIG_HOME/newsboat is supported: https://newsboat.org/releases/2.19/docs/newsboat.html#_xdg_base_directory_support
This is a continuation of #1331 and includes gating logic so that the change doesn't happen until state version 21.05.
Supersedes and Closes #1331
I also added myself as maintainer, please let me know if I should not do this.
```
```
- If this PR adds a new module (not a new module, but there is no maintainer currently for this module)
=> newsboat: use $XDG_CONFIG_HOME/newsboat

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/programs/exa.nix
Add the exa program as a module: 
Exa is a ls replacement, which have a saner colors cheme than lsd on white backgrounds.
https://github.com/ogham/exa
No tests needed, very simple configurations alike 'lsd'.
```
```
=> exa: Add exa module

flake.nix
Modify flake.nix to provide the the `home-manager` binary for each supported platform as mentioned in https://github.com/nix-community/home-manager/pull/1856#issuecomment-815077415. "Supported platforms" is equivalent to the set provided in `meta.platforms` in the home-manager derivation, `lib.platforms.unix`.
**One problem**: `nix run github:nix-community/home-manager/pull/1913/head` does not run because nix wants to write a lock file. Passing `--no-write-lock-file` fixes this, but this must be passed on each invocation of `nix run`. To fix this, we could start to track `flake.lock` (and I think this will be necessary if we want to provide a package output), but I'm hesitant to do so mostly because it would have to be updated every so often. Probably worth discussing before merging this. …
=> flake.nix: Add packages and defaultPackage outputs

modules/programs/gpg.nix, modules/services/gpg-agent.nix, tests/modules/programs/gpg/override-defaults.nix, tests/modules/services/gpg-agent/default-homedir.nix, tests/modules/services/gpg-agent/default.nix, tests/modules/services/gpg-agent/override-homedir.nix
As I do not want `.gnupg` to pollute my `$HOME`, here is an option to configure `$GNUPGHOME` declaratively.
Tradeoff: Now yet another session variable pollutes the environment, but it seems impractically cumbersome to wrap every program using `$GNUPGHOME` appropriately.
=> gpg: make homedir configurable

modules/services/gpg-agent.nix
this fixes #1931: if `programs.gpg.homedir` was not set to default, calls to
`gpg` would fail to pick up anything related to secrets.
```
```
=> gpg-agent: add GNUPG_HOMEDIR to environment

modules/programs/pet.nix, tests/default.nix, tests/modules/programs/pet/default.nix, tests/modules/programs/pet/snippet.toml, tests/modules/programs/pet/snippets.nix
Add missing `tag` option for elements of `programs.pet.snippets`.
```
```
=> pet: Add support for tags in snippets

flake.nix
This includes two changes:
When I passed a custom pkgs which adds a few new packages via overlays, they did not end up in my configuration modules, but when I updated `extraSpecialArgs` to include the `pkgs` then all worked fine.
I have a bunch of custom home-manager modules, some private ones not ready for prime-time and some coming from third party packages. I think it would be nice to separate those from the regular configuration (just like home-manager itself does). I named it `extraModules`.
Instead of:
```
configuration = {
imports = [
emacs-config.homeManagerModules.emacsConfig
./home.nix
];
};
```
You can do:
```
configuration = ./home.nix;
extraModules = [ emacs-config.homeManagerModules.emacsConfig ];
```
```
```
=> Improve flake homeManagerConfiguration

modules/programs/termite.nix
Instead of having an unconditional and undocumented addition to both `bash` and `zsh` to source the VTE integration, declare an option and make it use the VTE module directly. This allows bug fixes regarding VTE integration to be done at a single module.
I wasn't sure if `mkDefault` is needed for those options, so I omitted them for now.
Closes #1909.
```
```
=> termite: add option to enable VTE integration

modules/programs/tmux.nix, tests/modules/programs/tmux/default-shell.nix, tests/modules/programs/tmux/disable-confirmation-prompt.nix, tests/modules/programs/tmux/emacs-with-plugins.nix, tests/modules/programs/tmux/not-enabled.nix, tests/modules/programs/tmux/prefix.nix, tests/modules/programs/tmux/shortcut-without-prefix.nix, tests/modules/programs/tmux/vi-all-true.nix
[Tmux 3.2](https://github.com/tmux/tmux/raw/3.2/CHANGES) includes support to use `$XDG_CONFIG_HOME/tmux/tmux.conf` as
well as `~/.config/tmux/tmux.conf` for configuration file.
Fixes https://github.com/nix-community/home-manager/issues/1558
```
```
=> tmux: use xdg config path

modules/services/dunst.nix
Supercedes and Closes #1796 
Adds `package` and `waylandDisplay` options to the dunst module.
```
```
=> dunst: add service package option

modules/services/pass-secret-service.nix
Fixes https://github.com/nix-community/home-manager/pull/1898#issuecomment-827879711
```
```
=> pass-secret-service: fix systemd unit install option

modules/programs/gpg.nix, modules/services/gpg-agent.nix
This allows for the gnupg package to be configurable.
I am using this, and now my agent and cli tools are running 2.3.1 (using this commit on nixpkgs to provide the gnupg23 package: https://github.com/colemickens/nixpkgs/commit/3989c71f5cb0eca2764f9025dfe848f7143d2103)
```
```
=> gnupg/gpg-agent: gnupg package is configurable

modules/programs/ssh.nix
Attempting to build a flake configuration using `ssh.remoteForwards` results in
evaluation errors when `port` is undefined, as `!(entry ? port)` evaluates to
false. This was verified in the nix repl, and also occurs for `nix flake
check`.
Set optional attrs in `bindOptions` and `forwardModule` to `null` by default
and adjust the assertion to check for `null` instead of attr definitions.
```
```
=> programs.ssh: Use nullable types for optional forward attrs

modules/programs/gpg.nix
Related to:
- https://dev.gnupg.org/T4673 (an upcoming change in gnupg-2.3 and eventually 2.4 behavior)
It is useful for users to be able to configure their gnupg's `scdaemon.conf`.
This PR enables this.
```
```
=> gpg: can configure scdaemon.conf

modules/programs/qutebrowser.nix, tests/modules/programs/qutebrowser/keybindings.nix, tests/modules/programs/qutebrowser/settings.nix
=> qutebrowser: fix config location on darwin

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/mpris-proxy.nix
This adds a new module service running mpris-proxy from Bluez. It can be used to control media players with bluethooth headsets' buttons. I use it for a few months and it works well.
I welcome feedback for the systemd service (should we use `default.target`? Restart policy? etc).
I did not add tests as the only thing the module does is generating a systemd service (which I assume is well tested). There is no option, no configuration file, etc.
It is also my first new module to home-manager so please tell me if I did something wrong. I have a few more modules that I would like to upstream.
Please note that I'm listed as a maintainer in NixOS so I didn't add myself to home-manager's maintainers.
```
```
See …
=> mpris-proxy: add module

.github/CODEOWNERS, modules/services/window-managers/i3-sway/i3.nix, modules/services/window-managers/i3-sway/lib/functions.nix, modules/services/window-managers/i3-sway/sway.nix, tests/modules/services/window-managers/i3/i3-followmouse-expected.conf, tests/modules/services/window-managers/i3/i3-keybindings-expected.conf
Converted the i3 module to use `default_border` and `default_floating_border` and extracted that functionality out to be shared between the i3 and sway modules.
Also add myself as maintainer for i3.
Closes #1938
```
```
=> i3, sway: extract border functionality to common function

format, modules/programs/afew.nix
See #1953 (feel free to close this and my other formatting PRs if you want to keep the exceptions)
Remove the format script exception for the afew module.
Reasons:
* the PR that touches this module is stale (last activity was in September of 2019) https://github.com/nix-community/home-manager/pull/608
* even if the PR eventually becomes un-stale, it will need to be rebased anyway due to the transition from Travis CI to GitHub Actions.
```
```
=> format: remove exception for afew module

format
Starts work on #1953 by removing exceptions that don't do anything.
Removed format exclusion exceptions for modules that are already
formatted correctly (that is, when running nixfmt, no changes happen) or
have been moved (in the case of i3.nix).
**Note** I wasn't sure what to call the component, so I used `format`
```
```
=> format: removed exceptions already formatted files

.github/stale.yml
Closes #1957 
This PR adds configuration for [probot/stale](https://github.com/probot/stale) to the repository. The configuration is as follows:
* Issues & PRs get marked as stale after 60 days.
* After 7 days in the stale state, the issue/PR is closed.
* The message from the stalebot when it marks issues as stale looks like this: https://github.com/sumnerevans/sumnerevans/issues/1#issuecomment-828588816
* The message from the stalebot when it marks PRs as stale looks like this: https://github.com/sumnerevans/sumnerevans/issues/1#issuecomment-828638816
* Both of the messages were inspired by the text here: https://github.com/NixOS/nixpkgs/blob/master/.github/STALE-BOT.md
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/b …
=> github: configure probot/stale

modules/services/pbgopy.nix, tests/modules/services/pbgopy/service.nix
I noticed a few options were missing from the pbgopy module i added a while ago, so i added them.
```
```
=> services/pbgopy: add missing options

tests/modules/programs/kitty/example-settings.nix
Also remove assignment to non-existent option `programs.kitty.package`.
=> kitty: use dummy package in test

format, modules/services/kbfs.nix, modules/services/keybase.nix
See #1953 (feel free to close this and my other formatting PRs if you want to keep the exceptions)
Remove the format script exception for the afew module.
Reasons:
* the PR that touches this module is stale (last activity in April of 2020) #973
* even if the PR eventually becomes un-stale, it will need to be rebased anyway due to:
* existing merge conflicts
* the transition from Travis CI to GitHub Actions
```
```
=> format: remove exception for keybase and kbfs modules

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/programs/topgrade.nix, tests/default.nix, tests/modules/programs/topgrade/default.nix, tests/modules/programs/topgrade/settings-expected.toml, tests/modules/programs/topgrade/settings.nix
[topgrade](https://github.com/r-darwish/topgrade) is a CLI tool written in Rust that can detect and upgrade packages across nearly all package managers that can be present on a device.
```
```
=> topgrade: add module

modules/home-environment.nix
When profile installation fails during activation we'll print an extra message that explain that, if the error is due to conflicting packages, then it may be that the user has a manually installed copy of the package.
```
```
=> home-environment: extra message on nix-env error

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/barrier.nix, tests/default.nix, tests/modules/services/barrier/basic-configuration.nix, tests/modules/services/barrier/default.nix
Adds a background service for the Barrier client. Partially closes #712
```
```
=> services/barrier: Add service

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/lazygit.nix
lazygit uses different configuration folders for mac and for linux.
lazygit is a interactive program for working with git. If you are using a light colored terminal, then 
the suggested configuration is crucial for a good experience.
I'm unsure how to test this module.
```
```
=> lazygit: add module

modules/programs/zsh.nix, tests/modules/programs/zsh/default.nix, tests/modules/programs/zsh/history-ignore-pattern.nix
This option allows user to prevent commands matching a specific pattern from going to history.
The corresponding variable is `HISTORY_IGNORE` described in [zshparam(1)](https://man.archlinux.org/man/zshparam.1).
```
```
=> zsh: add history.ignorePatterns option

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/ncspot.nix
[ncspot](https://github.com/hrkfdn/ncspot) is a ncurses Spotify client written in Rust using librespot.
```
```
=> ncspot: add module

modules/programs/fzf.nix
Added options for tmux which will be read by fzf shell integrations.
The env variables are not read by the fzf binary, they only change behaviour of fzf shell integrations.
(Like FZF_CTRL_*_* and FZF_ALT_*_* env variables.)
(there arent any test cases for fzf)
```
```
=> fzf: option for tmux usage in shell integration

modules/services/lieer.nix, tests/modules/services/lieer/lieer-service-expected.service
This change makes the services created via the `lieer` module aware of the `notmuch` config created by the home-mangager `notmuch` module (which is stored in a non-standard location).
Without this change all the `lieer` services created by the `lieer` module failed for me, as they were unable to find the `notmuch` config.
```
```
=> lieer-service: add path to notmuch config to environment

modules/programs/neovim.nix
Nixpkgs did the same in https://github.com/NixOS/nixpkgs/pull/121339.
```
```
=> neovim: drop python2 support

modules/services/window-managers/i3-sway/i3.nix, modules/services/window-managers/i3-sway/lib/functions.nix, modules/services/window-managers/i3-sway/lib/options.nix, modules/services/window-managers/i3-sway/sway.nix, tests/modules/services/window-managers/i3/default.nix, tests/modules/services/window-managers/i3/i3-followmouse-expected.conf, tests/modules/services/window-managers/i3/i3-fonts-deprecated.nix, tests/modules/services/window-managers/i3/i3-fonts-expected.conf, tests/modules/services/window-managers/i3/i3-fonts.nix, tests/modules/services/window-managers/i3/i3-keybindings-expected.conf, tests/modules/services/window-managers/sway/sway-default.conf, tests/modules/services/window-managers/sway/sway-followmouse-expected.conf, tests/modules/services/window-managers/sway/sway-followmouse-legacy-expected.conf, tests/modules/services/window-managers/sway/sway-modules.conf, tests/modules/services/window-managers/sway/sway-null-package.conf
This applies to both the root-level and the bar configs.
Closes #1937.
```
```
=> i3, sway: replace fonts with submodule

modules/services/window-managers/i3-sway/lib/options.nix
Fixes #1979
Though the module options themselves had examples, they're unfortunately not reflected individually in the manual (I'm guessing because of `type = with types; either (listOf str) fontOptions;`?), so add examples for both font options
```
```
=> i3, sway: description and example for font options

modules/programs/zsh.nix
Before the documentation for the `programs.zsh.history.path` had a dependency on the configuration.
```
```
=> zsh: break configuration dependency in documentation

modules/services/window-managers/i3-sway/lib/options.nix
Before the documentation for a number of options had a dependency on the configuration.
```
```
=> i3,sway: break documentation dependency on configuration

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/etesync-dav.nix
Module for the local dav proxy component of [etesync](https://www.etesync.com/), etesync-dav.
It's a pretty trivial module that only adds a systemd file. Not sure what I would test for, just the existence of the systemd files and its contents from the variables?
```
```
=> etesync-dav: add module

modules/programs/msmtp.nix
=> msmtp: add note about account commands in extraConfig

modules/misc/xdg.nix, modules/programs/home-manager.nix, tests/lib/types/dag-merge.nix, tests/lib/types/dag-submodule.nix, tests/lib/types/list-or-dag-merge.nix
The `lib.hm.dag` attribute set should always be preferred.
=> Remove some usage of config.lib.dag

modules/programs/firefox.nix
Closes #1962.
This commit changes the module so that it only overrides *some* of the attributes in `cfg` of the firefox wrapper. This allows the user to enable other features by providing the appropriate `package` option, like so:
```nix
config.programs.firefox = {
enable = true;
package = pkgs.firefox.override {
cfg = {
enableTridactylNative = cfg.tridactyl.enable;
};
};
};
```
```
```
=> firefox: do not override other attributes in 'cfg'

.github/CODEOWNERS, modules/misc/news.nix, modules/misc/xdg-system-dirs.nix, modules/modules.nix, modules/systemd.nix, modules/targets/generic-linux.nix, tests/modules/home-environment/session-variables.nix, tests/modules/misc/xdg/default.nix, tests/modules/misc/xdg/system-dirs.nix, tests/modules/systemd/session-variables.nix, tests/modules/targets-linux/generic-linux.nix
There is a need to manage XDG Base Directory system directory environment variables in Home Manager modules; see #284. There is an existing mechanism in `targets.genericLinux.extraXdgDataDirs`, but this does not apply to NixOS systems.
Furthermore, it is important that `XDG_CONFIG_DIRS` and `XDG_DATA_DIRS` are set in both login shells (to support getty and SSH sessions) as well as the systemd user manager (to propagate them to user services and
desktop environments); see #1794.
The first need is addressed by adding the `xdg.systemDirs` module, which configures lists of directory names for both `config` and `data` directories. These are then wriiten to `$XDG_CONFIG_DIR/environment.d/10-home-manager.conf` and picked up by
the systemd user manager, via the existing …
=> xdg.systemDirs: init module

modules/services/kanshi.nix
Adds documentation for the `services.kanshi.profiles` submodule.
```
```
=> services/kanshi: add module example

modules/misc/xdg-system-dirs.nix, modules/systemd.nix, tests/modules/home-environment/session-variables.nix, tests/modules/misc/xdg/system-dirs.nix, tests/modules/systemd/session-variables.nix
Reverts nix-community/home-manager#1797
See #1999 ; in addition, since updating to latest nixpkgs-master, I've lost XDG_RUNTIME_DIR with this change.
=> Partially revert "xdg.systemDirs: init module"

modules/services/window-managers/i3-sway/i3.nix, modules/services/window-managers/i3-sway/lib/functions.nix, modules/services/window-managers/i3-sway/lib/options.nix, modules/services/window-managers/i3-sway/sway.nix, tests/modules/services/window-managers/i3/default.nix, tests/modules/services/window-managers/i3/i3-fonts-expected.conf, tests/modules/services/window-managers/i3/i3-keybindings-expected.conf, tests/modules/services/window-managers/i3/i3-workspace-default-expected.conf, tests/modules/services/window-managers/i3/i3-workspace-default.nix, tests/modules/services/window-managers/sway/default.nix, tests/modules/services/window-managers/sway/sway-default.conf, tests/modules/services/window-managers/sway/sway-followmouse-expected.conf, tests/modules/services/window-managers/sway/sway-followmouse-legacy-expected.conf, tests/modules/services/window-managers/sway/sway-modules.conf, tests/modules/services/window-managers/sway/sway-null-package.conf, tests/modules/services/window-managers/sway/sway-workspace-default-expected.conf, tests/modules/services/window-managers/sway/sway-workspace-default.nix
As offered, in #1967 first split PR for ability to set default-workspace for i3 and now also for i3-sway.
=> i3,sway: default workspace

modules/programs/i3status-rust.nix
=> i3status-rust: Fix formatting

modules/misc/news.nix, modules/services/syncthing.nix, tests/default.nix, tests/modules/services/syncthing/default.nix, tests/modules/services/syncthing/tray-as-bool-triggers-warning.nix, tests/modules/services/syncthing/tray.nix
Also sets the default syncthing tray package to
https://github.com/Martchus/syncthingtray instead of
https://github.com/sieren/QSyncthingTray, which indirectly fixes #603
```
```
See [CONTRIBUTING](https://github.com/rycee/home-manager/blob/master/CONTRIBUTING.md#commits) for more information and [recent commit messages](https://github.com/rycee/home-manager/commits/master) for examples.
=> syncthing: make syncthing tray package configurable

modules/services/status-notifier-watcher.nix
This reverts commit 02c1f8d416d55d8bc8d4de62f65f62fef40e5e80.
As I described in #1480, this causes more issues than it fixes for me.
To recap, there is some kind of timings issue with status-notifier-watcher and various system tray icons on startup. This was first identified to affect flameshot in #1312. The proposed fix in that PR was to introduce a pre unit start delay for flameshot, but instead 
a post unit start delay for status-notifier-watcher was adopted.
Following this, the following system tray icons fail to show on startup without manually restarting them:
* pasystray
* udiskie
* network-manager-applet
* blueman-applet (@meck could you check this please? I don't use this)
It would be helpful if someone could verify the behaviour of flameshot with and without this commit reverted …
=> Revert "status-notifier-watcher: introduce unit start delay"

.github/CODEOWNERS, doc/release-notes/rl-2105.adoc, modules/programs/htop.nix, tests/default.nix, tests/modules/programs/htop/default-settings.nix, tests/modules/programs/htop/default.nix, tests/modules/programs/htop/example-settings.nix
Add some meters supported in htop but missing from the configuration.
```
```
=> htop: replace individual option with 'settings'

modules/programs/gpg.nix
=> gpg: document lists are converted to duplicate keys

modules/programs/firefox.nix, tests/modules/programs/firefox/default.nix, tests/modules/programs/firefox/deprecated-native-messenger.nix
Fixes #1990.
As discussed in #1990.
I did not add a `mkRemovedOptionModule` because the option has only been deprecated, and is not yet removed.
I have not touched the `browserpass` module even though it is a native messenger extension because it only adds files to the home directory, not touching the browser packages in any way.
```
```
=> firefox: deprecate 'enableGnomeExtensions'

modules/programs/htop.nix
Previous patch on deprecation warnings broke use of old options due to function
call with too many arguments. This fixes the arguments so deprecation warnings
are properly traced while preserving old configuration options.
```
```
=> htop: fix deprecation warnings

modules/misc/news.nix
https://github.com/nix-community/home-manager/pulls/1257 (goes to search page)
vs.
https://github.com/nix-community/home-manager/pull/1257 (goes to PR)
=> syncthing: fix news link

modules/services/blueman-applet.nix, modules/services/cbatticon.nix, modules/services/flameshot.nix, modules/services/network-manager-applet.nix, modules/services/parcellite.nix, modules/services/pasystray.nix, modules/services/polybar.nix, modules/services/stalonetray.nix, modules/services/status-notifier-watcher.nix, modules/services/syncthing.nix, modules/services/taffybar.nix, modules/services/udiskie.nix, modules/xsession.nix
Previously, we had some units have
```
After = [ ... "taffybar.service" "polybar.service" "stalonetray.service" ];
```
This is my attempt to abstract over system trays by adding a new `tray.target`.
I also fixed `taffybar.service`: because of the way it works, (due to dyre) when the taffybar binary is launched, systemd considers it active, and only after that does it actually launch your compiled taffybar binary in `~/.cache/taffybar/`. This was causing a bunch of race issues, because units set to run after `taffybar.service` would be immediately started before the locally compiled taffybar runs, and was ready to accept tray icons.
This caused the following issues:
* #1312
* #1480
* #2020
I made it a dbus unit, so now systemd only considers it active when `org.taffybar.Bar` comes up on …
=> Add a separate tray.target for systemd units which require a system tray

modules/services/nextcloud-client.nix
Added an option that will make nextcloud-client run in the background.
```
```
=> nextcloud-client: add startInBackground option

modules/programs/neovim.nix
Set customRC for nvim
Previously with newer nixpkgs revisions extraConfig would not make it into init.nvim
Requires https://github.com/NixOS/nixpkgs/pull/124577 to maintain the
same behavior.
Not sure if this is a proper fix for the changes introduced in
https://github.com/NixOS/nixpkgs/pull/120445 but might be a helpful to
someone..
```
```
=> Set customRC for nvim

modules/files.nix, modules/lib/file-type.nix
Previously, the comparison would not handle directory comparison correctly, always finding that the source and target differed. This would trigger the `onChange` script on each activation.
Fixes #2004
```
```
=> files: fix use of onChange with directory source

modules/programs/jq.nix
Sometimes, I use a different jq build.
```
```
=> jq: add `package` option

modules/programs/neovim.nix, tests/modules/programs/neovim/plugin-config.nix, tests/modules/programs/neovim/plugin-config.vim
makes more sense to have extraConfig afterwards in case use want to override config
```
```
=> programs.neovim: fix tests + swap extraConfig and pluginconfig

modules/programs/foot.nix, tests/modules/programs/foot/systemd-user-service-expected.service
`foot`'s terminal spawning feature (`Control+Shift+n` by default) does not work with the `foot` user service supplied with the `foot` module. The error in the system journal is:
```
Jun 01 18:09:17 foureightynine foot[30948]:  err: spawn.c:89: footclient: failed to spawn: No such file or directory
Jun 01 18:09:17 foureightynine foot[30948]: spawn: footclient: failed to spawn: No such file or directory
```
Adding foot's `bin` folder to the services path fixes this issue.
```
``` …
=> foot: add foot binaries to user service's path

modules/programs/i3status-rust.nix
The format keys have changed in `i3status-rust` ([source](https://github.com/greshake/i3status-rust/blob/master/doc/blocks.md#removed-format-keys)), resulting in an error when using the default configuration.
```
```
=> i3status-rust: replace deprecated memory format keys

modules/programs/htop.nix, tests/modules/programs/htop/example-settings.nix
Pass meters for formatting in a list of attrsets so that ordering can be
preserved. In addition provide some mode-specific functions to create these
attrsets, to make for a bit nicer config.
This fixes #2060.
When approved I'll make a backport for 21.05.
```
```
=> htop: fix preserving the order of meters

.github/CODEOWNERS, modules/misc/xdg-desktop-entries.nix, modules/modules.nix, tests/modules/misc/xdg/default.nix, tests/modules/misc/xdg/desktop-entries.nix, tests/modules/misc/xdg/desktop-full-expected.desktop, tests/modules/misc/xdg/desktop-min-expected.desktop
This is a module to manage .desktop files in ~/.local/share/applications/, which define entries in your desktop environment's app launcher.
It allows you to override app launcher entries that are already installed in your nix profile, and to create new ones.
It uses the [makeDesktopItem](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/make-desktopitem/default.nix) package, and its options mostly follow the package's parameters.
```
```
=> xdg-desktop-entries: add module

doc/faq.adoc, modules/misc/gtk.nix, modules/programs/gnome-terminal.nix, modules/programs/rofi.nix, modules/services/dunst.nix, modules/services/gnome-keyring.nix, modules/services/pulseeffects.nix
To avoid use of gnome3 alias.
```
```
=> Replace references to pkgs.gnome3 by pkgs.gnome

modules/programs/texlive.nix
I've at least personally had the need to swap out `pkgs.texlive`. This is basically a `package` option.
```
```
=> texlive: add `packageSet` option

modules/programs/htop.nix, tests/modules/programs/htop/example-settings.nix
Pass meters for formatting in a list of attrsets so that ordering can be
preserved. In addition provide some mode-specific functions to create these
attrsets, to make for a bit nicer config.
This fixes #2060 on 21.05. See #2065 for these fixes on master.
```
```
=> htop: fix preserving the order of meters (backport to 21.05)

modules/programs/foot.nix, tests/modules/programs/foot/systemd-user-service-expected.service
This reverts commit cb227dc6c29eb4f768d04958f4fe6d9d3d4aba46 (#2061).
That PR broke usage of foot as a server as `PATH` would be overriden, and shells inside the terminal could not find binaries. Also the workaround for the spawning feature no longer seems necessary: it now is working for me without the patch. 
```
```
=> Revert "foot: add foot binaries to user service's path (#2061)"

modules/services/dunst.nix
The `dunst` package provides the `dunstctl` and `dunstify` command-line utilities which are useful to have.
```
```
=> dunst: add the whole package to home.packages

doc/man-home-manager.xml, home-manager/completion.bash, home-manager/completion.zsh, home-manager/home-manager
Teach `home-manager` to pass on the `--debug` option.
```
```
=> home-manager: pass on `--debug` option

modules/services/etesync-dav.nix
[Upstream](https://github.com/etesync/etesync-dav/blob/master/README.md#configuration-and-running) uses 37358 as default port.
```
```
=> etesync-dav: fix typo

modules/programs/irssi.nix, tests/default.nix, tests/modules/programs/irsii/default.nix, tests/modules/programs/irsii/example-settings-expected.config, tests/modules/programs/irsii/example-settings.nix
I was following [these instructions](https://www.oftc.net/NickServ/CertFP/ ) and found that the `/server add -ssl_cert` option was needed.
This patch therefore adds an optional `programs.irssi.networks.<name>.server.ssl.certificateFile` path.
Perhaps this could also be done with a `settings` attribute, but that would probably require most of this module to be reworked.
=> irssi: add ssl_cert option for servers

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/pantalaimon.nix, tests/default.nix, tests/modules/services/pantalaimon/basic-configuration.nix, tests/modules/services/pantalaimon/default.nix
Add a module for [pantalaimon](https://github.com/matrix-org/pantalaimon), a E2EE aware proxy daemon for matrix clients.
Tested the new module with [fractal](https://wiki.gnome.org/Apps/Fractal), which doesn't support E2EE by itself.
nixpkgs-PR for the "headless" version: https://github.com/NixOS/nixpkgs/pull/123896#issuecomment-851006235
```
```
=> pantalaimon: add module

modules/xcursor.nix
closes #2081
Writes the file `~/.icons/default/index.theme`, which allows AwesomeWM (perhaps others?) to use the pointerCursor setting.
```
```
- If this PR ~~adds a new module~~
=> xsession.pointerCursor: .icons file for AwesomeWM

modules/programs/zsh.nix
Adds `programs.zsh.completionInit` option, Factored out from original .zshrc construction.
Example usage from my personal configuration:
```nix
{ programs.zsh.completionInit = /*zsh*/''
setopt EXTENDED_GLOB
autoload -U compinit
for dump in ''${ZDOTDIR:-$HOME}/.zcompdump(#qN.mh+1); do
compinit
if [[ -s "$dump" && (! -s "$dump.zwc" || "$dump" -nt "$dump.zwc") ]]; then
touch "$dump"
zcompile "$dump"
else
touch "$dump"
touch "$dump.zwc"
fi
done
compinit -C
''; }
```
```
```
=> zsh: add `completionInit` option

modules/programs/foot.nix, tests/modules/programs/foot/empty-settings.nix, tests/modules/programs/foot/systemd-user-service.nix
Fixes #2090 
Creates foots config file at `xdg.configFile."foot/foot.ini"` as long as `programs.foot.enable` is `true`
```
```
=> foot: Always create config file

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/mangohud.nix, tests/default.nix, tests/modules/programs/mangohud/basic-configuration-mpv.conf, tests/modules/programs/mangohud/basic-configuration.conf, tests/modules/programs/mangohud/basic-configuration.nix, tests/modules/programs/mangohud/default.nix
since i recently packaged mangohud for nixpkgs seems like a good time to also add a home-manager module
https://github.com/flightlessmango/MangoHud
<details>
<summary>neovim failed, but i have hard time believing that's my fault</summary>
```
--- actual
+++ expected
@@ -1,2 +1,10 @@
set packpath^=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-vim-pack-dir
set runtimepath^=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-vim-pack-dir
+
+" vim-commentary {{{
+" This should be present too
+autocmd FileType c setlocal commentstring=//\ %s
+autocmd FileType c setlocal comments=://
+
+" }}}
+" This should be present in vimrc
For further reference please introspect /nix/store/7mmydymjnqv70ifr2rvz6syigxals67g-nmt-report-neovim-plugin-co
```
</details>
Edit: ah yes it's #2100
```
{component}: …
```
=> mangohud: add module

modules/programs/password-store.nix
This ensures that any systemd services that need pass will have the
correct environment variables.
```
```
=> password-store: add environment variables to xsession.importedVariables

nixos/default.nix
Sets `systemd.services.home-manager-${user}.stopIfChanged` to false in the NixOS module. The service has no `ExecStop`, so I don't think there's a point in stopping it in the old configuration and starting it in the new, we can just restart it.
One more line of code for one less line of logs seems like a good deal to me.
```
```
=> nixos: set stopIfChanged to false

modules/files.nix, modules/systemd.nix
Robust escaping & automounts.
```
```
=> systemd: bring more in line with upstream

modules/programs/direnv.nix, tests/modules/programs/direnv/nix-direnv.nix, tests/modules/programs/direnv/stdlib-and-nix-direnv.nix
NixOS/nixpkgs@03310df843a344215b45b2e8aef11ae9402a40e2 disabled flake
support by default, so we now need to build a custom package and use it
if the user wants to `use flake` successfully.  This should fix #2087.
I'm not wedded to the backwards-incompatible change to the configuration,
but adding a `programs.direnv.enableNixDirenvFlakeIntegration` option
seemed excessively unwieldy.
```
```
=> direnv: add enableFlakes option for enableNixDirenvIntegration

modules/programs/qutebrowser.nix, tests/modules/programs/qutebrowser/default.nix, tests/modules/programs/qutebrowser/quickmarks.nix
Closes: https://github.com/nix-community/home-manager/issues/1230
This allows the qutebrowser derivation to parse quickmarks, which I've been wanting to use for a while. If unset, qutebrowser will manage the file instead of home-manager. 
When quickmarks are set through home-manager, they cannot be edited at runtime.
```
```
=> qutebrowser: add quickmark support

modules/services/sxhkd.nix, tests/modules/services/sxhkd/service.nix
This allows relogging into graphical session.
```
```
=> sxhkd: stop scope before creating

modules/xresources.nix
Adds an `xrdb` call to `xsession.initExtra`, so that X resources are loaded on startup for people using `startx` (or a display manager that doesn't automatically load `~/.Xresources`).
```
```
=> xresources: load .Xresources in xsession.initExtra

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/programs/gnome-terminal.nix, tests/default.nix, tests/modules/programs/gnome-terminal/default.nix, tests/modules/programs/gnome-terminal/gnome-terminal-1.conf, tests/modules/programs/gnome-terminal/gnome-terminal-1.nix
- Add support for showing bold as bright colors
- Add support to configure the background transparency
- Fix the scrollOnOutput, it was not being dumped to the config
- Add tests!
- Add myself as maintainer
- ![image](https://user-images.githubusercontent.com/47480384/120058374-03299a80-c010-11eb-9e01-1714103b8b4a.png)
- ![demo](https://user-images.githubusercontent.com/47480384/120057273-81357380-c007-11eb-8bad-1ecee927cc36.gif)
```
```
=> programs.gnome-terminal: terminal options

doc/man-home-manager.xml, home-manager/completion.bash, home-manager/completion.zsh, home-manager/default.nix, home-manager/home-manager
Add a `home-manager option` subcommand which acts like `nixos-option` by constructing a home-manager–based invocation of `nixos-option`.
Doesn't work on flake configurations currently.
```
```
=> home-manager: add `home-manager option` (like nixos-option)

home-manager/default.nix
=> home-manager: fix nixos-option evaluation

modules/services/dunst.nix
This makes `settings.global.icon_path` a `separatedString ":"` so that the user can add their own paths.
I need this because the current `icon_path` setting is quite flaky (but I don't think there's a better way apart from implementing the icon theme specification, or waiting until dunst does).
```
```
=> dunst: make icon_path extensible

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/modules.nix, modules/programs/terminator.nix, tests/default.nix, tests/modules/programs/terminator/config-file.nix, tests/modules/programs/terminator/default.nix
Added configuration for terminator.
```
```
=> terminator: added

modules/services/rsibreak.nix
Otherwise rsibreak cannot find its icon and is a blank gap on the
notification tray.
```
```
- If this PR ~adds a new module~
=> rsibreak: Add package when enabled; fixes #2092

modules/programs/fzf.nix
Previously, if the user customised `programs.fzf.package`, that package
is only put into `home.packages`, and the shell integration hooks use
the files from `pkgs.fzf`.  If a different package is needed for the
shell integration, the user would need to manually source it into their
shell configuration.  With this PR, `cfg.package` is used throughout.
```
```
=> fzf: also use custom package for shell integrations

.github/CODEOWNERS, modules/services/window-managers/bspwm/default.nix, modules/services/window-managers/bspwm/options.nix, tests/default.nix, tests/modules/services/window-managers/bspwm/bspwmrc, tests/modules/services/window-managers/bspwm/configuration.nix, tests/modules/services/window-managers/bspwm/default.nix
- Allows the user to reload their config on-the-fly by exposing the configuration file to `~/.config/bspwm/bspwmrc`
- Fixes some shell escaping issues using `lib.strings.escapeShellArg`
- Style improvements
- Adds myself as a maintainer since this module doesn't have one. @Valodim, is this OK with you?
This has been tested with a reasonably general config.
```
```
=> bspwm: various improvements

modules/services/window-managers/bspwm/default.nix, modules/services/window-managers/bspwm/options.nix, tests/modules/services/window-managers/bspwm/bspwmrc, tests/modules/services/window-managers/bspwm/configuration.nix
Removed by mistake in e70524c, but `ignore_ewmh_fullscreen` still needs it.
cc @berbiche 
```
```
=> bspwm: re-add support for lists as config option values

modules/programs/command-not-found/command-not-found.nix, modules/programs/command-not-found/command-not-found.pl
=> command-not-found: update from nixpkgs

modules/misc/news.nix, modules/services/window-managers/xmonad.nix
- xmonad: document breakage of recompilation
- news: add warning about xmonad recompilation
Whether this fixes #1895 is up to the author.
cc: @dnaq @markusscherer @woffs
```
```
=> xmonad: document recompilation issue

modules/services/window-managers/i3-sway/lib/functions.nix, modules/services/window-managers/i3-sway/lib/options.nix, tests/modules/services/window-managers/i3/default.nix, tests/modules/services/window-managers/i3/i3-bar-focused-colors-expected.conf, tests/modules/services/window-managers/i3/i3-bar-focused-colors.nix, tests/modules/services/window-managers/i3/i3-followmouse-expected.conf, tests/modules/services/window-managers/i3/i3-fonts-expected.conf, tests/modules/services/window-managers/i3/i3-keybindings-expected.conf, tests/modules/services/window-managers/i3/i3-workspace-default-expected.conf, tests/modules/services/window-managers/i3/i3-workspace-output-expected.conf, tests/modules/services/window-managers/sway/default.nix, tests/modules/services/window-managers/sway/sway-bar-focused-colors.conf, tests/modules/services/window-managers/sway/sway-bar-focused-colors.nix, tests/modules/services/window-managers/sway/sway-default.conf, tests/modules/services/window-managers/sway/sway-modules.conf, tests/modules/services/window-managers/sway/sway-workspace-default-expected.conf, tests/modules/services/window-managers/sway/sway-workspace-output-expected.conf
Both i3bar and swaybar can use different colors for the bar on the currently focused monitor output; add color options for this feature.
It is not possible to add these options using `xsession.windowManager.i3.config.bars.*.extraConfig` while using other bar color options at the same time, because all color options must be inside the `colors { ... }` block, so the only way to use `extraConfig` is to move the whole bar color configuration there, losing the convenience of existing options.
New tests added for both i3 and sway, and the expected output for existing tests is adjusted (changes are limited to extra blank lines; avoiding the changes completely would result in much less readable code in `modules/services/window-managers/i3-sway/lib/functions.nix`, which would also be significantly …
=> i3,sway: add bar color options for the focused output

.github/CODEOWNERS, modules/i18n/input-method/default.nix, modules/i18n/input-method/fcitx.nix, modules/i18n/input-method/fcitx5.nix, modules/i18n/input-method/hime.nix, modules/i18n/input-method/kime.nix, modules/i18n/input-method/nabi.nix, modules/i18n/input-method/uim.nix, modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, tests/default.nix, tests/modules/i18n/input-method/default.nix, tests/modules/i18n/input-method/fcitx5-configuration.nix, tests/modules/i18n/input-method/fcitx5-overlay.nix
Addition of the i18n.inputMethod module from the system-wide NixOS modules.
Ibus support not added yet due to it depending on a couple of options which are currently only available in the system-wide configuration.
```
```
=> i18n.inputMethod: add module

doc/faq.adoc
This is a good alternative to uninstalling packages one by one.
I found this here: https://stackoverflow.com/questions/53905406/how-can-i-reset-my-nix-environment-to-the-original-user-profile
Document how to reset the nix-env to avoid conflicts. 
```
```
No, it is not. But I wouldn't know what the component would be. "documentation"? "faq"? 
=> Document how to reset the nix-env

.github/CODEOWNERS, modules/accounts/email.nix, modules/misc/news.nix, modules/modules.nix, modules/programs/himalaya.nix, tests/default.nix, tests/modules/programs/himalaya/default.nix, tests/modules/programs/himalaya/himalaya-expected.toml, tests/modules/programs/himalaya/himalaya.nix
`himalaya` is a simple TUI mail client.
```
```
=> Add himalaya

modules/files.nix, tests/modules/files/default.nix, tests/modules/files/target-conflict.nix
Improve error handling of conflicting target files.
Fixes #1807
```
```
=> files: assert that target files are unique

modules/programs/zsh.nix
Adds a simple way to enable syntax highlighting for zsh using https://github.com/zsh-users/zsh-syntax-highlighting
This was brought up in https://github.com/nix-community/home-manager/issues/1321.
```
```
=> zsh: add `enableSyntaxHighlighting` option

modules/xresources.nix
This allows the user to move .Xresources somewhere else, which can help with decluttering their home directory.
```
```
=> xresources: Add path configuration option

modules/xsession.nix, tests/modules/misc/xsession/basic-xsession-expected.txt
This allows the user to move .xprofile somewhere else, which can help with decluttering their home directory.
```
```
=> xsession: Add profilePath configuration option

modules/programs/rofi.nix
It was possible to add plugins to `rofi` only via overriding package in `package` option. Adds option to list plugins in separate `plugins` option.
```
```
=> Add option "plugins" to Rofi module

modules/programs/rbw.nix
`pinentry_mac` does not use bin/pientry as path for its binary, instead
it sets `binaryPath` pointing to its binary.
```
```
=> rbw: use pientry.binaryPath when available

modules/programs/foot.nix, tests/modules/programs/foot/empty-settings.nix, tests/modules/programs/foot/systemd-user-service.nix
This reverts commit 666eee4f72979b0ebbd2e065a3846d7a8a16895c. ( aka #2091 )
As of https://github.com/NixOS/nixpkgs/pull/128121 we don't need to generate this file if there is no config.
```
```
=>  programs.foot: revert always create config file (#2091) 

home-manager/default.nix
This reverts commit 2c9fe368c1b5d79d504e3111ebaa97e90192fbb4.
In I accidentally pushed to master which I believed was my own fork:
https://github.com/nix-community/home-manager/commit/2c9fe368c1b5d79d504e3111ebaa97e90192fbb4
However since it also broke home-manager according to my information, this might have been a good thing.
However here is the revert of the revert just in case
Note if this PR is applied evaluation on my system fails as follows:
```
Exception: error: attempt to call something which is not a function but a set at /nix/store/wg5hvwq8p85872am5wjslnvrjzbb0mjh-source/home-manager/default.nix:14:18: 13| 14| nixos-option = pkgs.nixos-option or callPackage | ^ 15| (pkgs.path + "/nixos/modules/installer/tools/nixos-option") { };; type: nix::TypeError
```
=> Revert "Revert "home-manager: use nixos-option from pkgs""

modules/xsession.nix, tests/modules/misc/xsession/basic-setxkbmap-expected.service, tests/modules/misc/xsession/keyboard-without-layout-expected.service
Resets setxkbmap options before setting new ones. Quoting `setxkbmap(1)`:
> Note that setxkbmap adds options specified in the command line to the options that were set before (as saved in root window properties). If you want to replace all previously specified options, use the -option flag with an empty argument first.
```
```
=> setxkbmap: reset options before setting new ones

modules/programs/chromium.nix
Not if the user overrides `programs.brave.package` with an older version of Brave.
```
```
=> brave: fix config dir path

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/sm64ex.nix, tests/default.nix, tests/modules/programs/sm64ex/default.nix, tests/modules/programs/sm64ex/settings.nix
This adds a module for sm64ex, in which you can configure compile-time options, and also run-time options.
```
```
=> sm64ex: add module

modules/services/window-managers/i3-sway/i3.nix, modules/services/window-managers/i3-sway/lib/functions.nix, modules/services/window-managers/i3-sway/sway.nix, tests/modules/services/window-managers/sway/default.nix, tests/modules/services/window-managers/sway/sway-bindkeys-to-code.conf, tests/modules/services/window-managers/sway/sway-bindkeys-to-code.nix
Propagates the `bindkeysToCode` setting which adds `--to-code` to the keybinding to mode configs.
Closes #2174
```
```
=> sway: add propagate --to-code for modes

modules/services/xcape.nix
Add `setxkbmap.service` to `After` of `xcape`, if keyboard options are set. Fixes #2198 
```
```
=> xcape: run xcape after setxkbmap (#2198)

modules/home-environment.nix, nixos/default.nix
Explicitly add the system's Nix package to the activation script PATH.
Fixes #2178
```
```
=> nixos: add nix package to activation script path

modules/programs/taskwarrior.nix
My use-case is having programs.taskwarrior.dataLocation =
/absolute/path (outside of $HOME), but the current implementation
wrongly creates $HOME/absolute/path (due to how home.file is
implemented).
Since taskwarrior creates the dataLocation automatically on first run,
there is actually no need for HM to create that directory.
Additional benefit, the .keep symlink that HM creates as a side-effect
no longer appears in the taskwarrior data directory.
Fixes #2207.
```
```
=> taskwarrior: don't create dataLocation with home.file

.github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/issue.yaml
We cannot assign teams to issues yet.
See <https://github.com/dear-github/dear-github/issues/170>.
The current list of assignees is me, @rycee and @sumnerevans.
If you do not wish to be pinged, please indicate it here.
```
```
=> meta: github: fix issue template assignees

home-manager/default.nix
`share/fish/completions` is for completions vendored by fish, the correct location for other vendors is `share/fish/vendor_completions.d`.
```
```
=> fish: fix `home-manager` completion path

modules/programs/neovim.nix, tests/modules/programs/neovim/coc-config.expected, tests/modules/programs/neovim/coc-config.nix, tests/modules/programs/neovim/default.nix
Adds options to enable [coc](https://github.com/neoclide/coc.nvim) and provide content of `coc-settings.json`
```
```
=> neovim: Add coc support

modules/services/barrier.nix
Closes #2066 by removing the non-functional `tray` option
```
```
=> barrier: remove `tray` option

modules/programs/neovim.nix
Expose the generated viml config, this has 2 advantages:
1/ user can choose to write the generated config to a file of its choice
2/ the user can prepend/append to the config before writing it
xdg.configFile."nvim/init.vim".text = ''
" prepend some config
${programs.neovim.generatedConfigViml}
" append some config
'';
```
```
=> programs.neovim: expose generatedConfigViml

modules/lib-bash/activation-init.sh
This marks the setup variables as read-only. Just to add a bit extra safety.
```
```
=> home-environment: use `declare -gr` in activation init

doc/installation.adoc
Fixing documentation for *nix-darwin module*, you must specify a user in your darwin config or home-manager will fail.
```
```
=> For nix darwin need a valid user

nixos/default.nix
=> NixOS: remove indirection via activate-${username}, fixes #2191

modules/programs/powerline-go.nix, tests/modules/programs/powerline-go/default.nix, tests/modules/programs/powerline-go/fish.nix
Add fish integration for powerline-go.
```
```
=> powerline-go: add fish integration

tests/modules/programs/fish/functions.nix, tests/modules/programs/fish/no-functions.nix, tests/modules/programs/fish/plugins.nix, tests/modules/programs/nix-index/assert-on-command-not-found.nix, tests/modules/programs/nix-index/integrations.nix
Avoid pulling in fish in test suite.
```
```
=> nix-index: use dummy fish package in tests

.github/workflows/test.yml, modules/programs/emacs.nix, tests/default.nix, tests/modules/programs/emacs/default.nix, tests/modules/programs/emacs/extra-config.nix
This would make it easy to set variables with Nix-computed paths in the configuration.
```
```
=> emacs: add extraConfig option

doc/installation.adoc
`user.users` doesn't exist on `nix-darwin`. It's `users.users` instead. I ran into this when trying to set up my Mac with Home Manager this morning. This PR makes a minor change to fix that.
```
```
=> doc: user.users.eve -> users.users.eve for nix-darwin

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/java.nix
Create a module `programs.java` that install the java package specified by the `package` attribute and set the corresponding `JAVA_HOME` using `home.sessionVariables`.
Solve issue #845 
Note: Due to `sessionVariables` issue #1011, this may not work out of the box on graphical sessions.
As a workaround, if you use `xsession.windowManager.command`, add the line
```sh
. "${config.home.profileDirectory}/etc/profile.d/hm-session-vars.sh"
```
before starting the session.
If you do not use Home Manager to manage the graphical session, put the above line in the init scripts or source it when needed.
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more information and …
=> programs.java: init

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/easyeffects.nix, modules/services/pulseeffects.nix
Added `services.easyeffects` as a PipeWire replacement for `services.pulseeffects`.
```
```
=> easyeffects: add module

modules/lib/gvariant.nix, tests/lib/types/gvariant-merge.nix
Handle Nix strings that contain newline characters. See #2096
```
```
=> lib.gvariant: escape newlines in strings

tests/modules/programs/scmpuff/no-shell.nix, tests/modules/programs/scmpuff/no-zsh.nix, tests/modules/programs/scmpuff/zsh.nix
Avoid pulling down zsh in tests.
```
```
=> Remove test dependency on zsh

modules/lib/gvariant.nix, modules/lib/types.nix, tests/lib/types/gvariant-merge.nix
Before, empty arrays would always be rendered as an empty string array.
```
```
=> lib.gvariant: fix rendering of empty non-string arrays

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/git-sync.nix, tests/default.nix, tests/modules/services/git-sync/basic.nix, tests/modules/services/git-sync/default.nix
This service module uses git-sync-on-inotify to automatically keep a git repository in sync by
- Auto committing any changes it detects from its inotifywait
- Periodically synchronizing a configurable amount with the remote 
```
```
=> Add git-sync

modules/programs/git.nix
This adds an example for the `programs.git.includes.*.contents` section
since it was a bit ambiguous as to what kind of format it expects.
```
```
=> doc: Add an example for a git includes section

modules/files.nix, modules/programs/i3status-rust.nix, modules/programs/qutebrowser.nix, modules/services/dunst.nix, modules/services/window-managers/i3-sway/i3.nix, modules/services/window-managers/i3-sway/sway.nix, modules/services/window-managers/xmonad.nix, modules/xresources.nix
Fixes #751, see there for background.
I cleaned up the existing `onChange` hooks according to the following guidelines:
- don't use `DRY_RUN`(`_CMD`)
- don't output generic "Reloading foo" messages, but do make use of `VERBOSE`(`_ECHO`) where applicable
and general good Bash practice.
```
```
=> files: factor the dry run logic out of onChange hooks

home-manager/completion.bash, home-manager/completion.fish, home-manager/completion.zsh, home-manager/home-manager
This allows running home-manager with `--builders` option passed through to `nix-build`, which will then pass build execution to remote builders on other machines.
This may be useful with relatively complex home-manager configurations where building the profile on a local machine is not feasible.
=> home-manager: allow remote builders for nix-build

modules/xsession.nix
=> xsession: handle parameter passed from display-manager

modules/programs/fish.nix
This is a very opinionated change so it's OK to keep it as-is.
I think the examples provided in `shellAliases` are bad because they are provided by Fish out of the box.
- `ll` is aliased to `ls -lh` by default.
- `cd` can be omitted when changing directories. That is, `..` is equivalent to `cd ..`.
I replaced them with two different examples but if there's better one, suggestions welcome.
```
```
=> fish: provide different examples for `shellAliases`

docs/man-home-manager.xml, home-manager/completion.bash, home-manager/completion.fish, home-manager/completion.zsh, home-manager/home-manager
In macOS, I'm trying use flake with home-manager, then I encountered error: 
```
error: access to path '/System/Volumes/Data/nix/store/2kn3jicr9rab7j4d0mgajz6fcnydcmlh-source/nix/flake.nix' is forbidden in restricted mode
```
I investigated the error, it seems like a bug of flake., it can not use the directory other than `/nix/store`, in order to avoid this problem, I need to use `nix build --impure`
```
```
=> home-manager: add command line argument: --impure

modules/programs/neomutt-accounts.nix, modules/programs/neomutt.nix, tests/modules/programs/neomutt/default.nix, tests/modules/programs/neomutt/neomutt-not-primary-expected.conf, tests/modules/programs/neomutt/neomutt-with-binds-expected.conf, tests/modules/programs/neomutt/neomutt-with-named-mailboxes-expected.conf, tests/modules/programs/neomutt/neomutt-with-named-mailboxes.nix
These options allow to add other folders than the inbox, for example the
Trash, Spam folder or Drafts to be added on a per-account basis. Using
extraOptions is not possible here, as those are lazily loaded on mailbox
open and thus would appear at the bottom and not sorted by account.
This commit also changes the default sidebar format string to use %D
instead of %B because %B will ignore named mailboxes and show the folder
name instead.
```
```
=> neomutt: Allow named mailboxes

modules/services/gpg-agent.nix
This happens commonly if someone using home manager with gpg-agent
acting as ssh-agent on both machines.
@rycee brought up how gpg-itself has some support for agents on both
ends, but in that case one is forwarding the gpg-agent socket rather
than forwardning the gpg-agent-as-ssh-agent socket. There is no need to
forward both.
So I think this is a good default:
- Forward just gpg-agent socket and this doesn't matter.
- Forward just the ssh-agent socket and this does the right thing.
- Forward both sockets and now the ssh one takes priority instead, but
forwarding both was always a silly thing to do.
Fixes #667
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/doc/contributing.adoc#sec-commit-style) for more …
=> local gpg-agent acting as ssh-agent should yield (#667)

modules/services/window-managers/i3-sway/lib/functions.nix, modules/services/window-managers/i3-sway/lib/options.nix
Allows criteria used by Sway and i3 to be empty (different from the empty string)
using a boolean value of `true`.
Fixes #2274
```
```
=> i3/sway: allow empty criterias using a value of 'true'

nixos/default.nix
One of the things managed by the `home-manager-<username>` unit is the systemd user directory `.config/systemd/user`.  However, this directory needs to be in place completely before systemd user sessions start up or the user sessions will come up with an incomplete listing of enabled units, etc.
There was a race condition where nothing prevented `systemd-user-sessions.service` from starting ahead of the systemd user
directory's initialization completing.  This commit makes `home-manager-<username>` finishes _before_ we start `systemd-user-sessions.service` to avoid such race condition.
This issue was probably not all that noticeable in most cases, but when using a non-persistent root config (i.e. tmp on / or https://grahamc.com/blog/erase-your-darlings) the race condition triggering …
=> nixos: Fix race condition with user units

nixos/default.nix
This PR just backports #2286 into the release-21.05 branch.
```
```
=> [nixos] Fix race condition with user units (#2286)

modules/programs/neomutt.nix
This makes it possible to easily use a different (e.g. more recent or patched) neomutt package.
Many modules already expose an API to specify a different package, so this is nothing fundamentally new.
Background/off-topic: I'm using home-manager in a Flakes context (/etc/nixos). I only found two ways to inject a different neomutt package into home-manager's module: either by forking nixpkgs (`inputs.nixpkgs.follows = "nixpkgs"`) and patching neomutt there, or by exposing the `package` option in home-manager. Then I can use my nixpkgs **with overlays** (since I'm in the `outputs` context) and simply say `package = pkgs.neomutt`. If anyone knows a way to use nixpkgs with overlays in the `inputs` section of Nix flakes, I'd be happy to know.
``` …
```
=> modules/programs/neomutt: configurable package

format
I couldn't run the format shell script becaues it's nixpkgs revision
does not support recent changes done in Nix or nixpkgs in regards
to the `nix-shell` command.
The script's previous nixpkgs revision was dated March 28th, 2020.
```
```
=> Update format script nixpkgs revision

modules/programs/mcfly.nix
mcfly migrated its initialization method to a subcomand called `init`,
which is available since mcfly 0.5.4 released on Feb 28, 2021.
```
```
=> mcfly: switch to init command

modules/programs/broot.nix, tests/default.nix, tests/modules/programs/broot/broot.nix, tests/modules/programs/broot/default.nix
Expose the `modal` option in the broot program configuration.
```
```
=> broot: expose modal option

nixos/default.nix
oneshot services do not have a timeout by default, so a misbehaving activation script can stall and prevent a system from ever booting.
90sec was taken from the systemd defaults, but could be lowered if something lower would be more tolerable.
```
```
=> nixos: add timeout to hm-activate service

README.md, docs/faq.adoc, docs/installation.adoc
The docs seemed to me to imply that fish was not really supported, but
if fish is managed by home-manager, the generated config does use fenv
to source the session-vars file. Update the faq to mention that fish
does work, and mention fenv in the README.
```
```
=> docs: update session-vars info about fish shell

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/betterlockscreen.nix
As Maintainer and user of Betterlockscreen I wished an easier way to use it as screen-locker under NixOS/with HM.
I would like to extend the module in the future - making arguments configurable and adding tests then.
```
```
=> betterlockscreen: add module

modules/programs/bash.nix
I wished to unset a shell option, and, since this already allows setting shell options, I thought it might be appropriate to extend it to allow unsetting a shell option by prefixing it with `-`. (I chose `-` as a prefix rather than `no` because Bash has options which begin with `no`.)
I know that I could unset an option by adding a line to `initExtra`, but this way makes for a cleaner-looking configuration.
=> bash: Allow unsetting shell options

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/bottom.nix, tests/default.nix, tests/modules/programs/bottom/default.nix, tests/modules/programs/bottom/empty-settings.nix, tests/modules/programs/bottom/example-settings.nix
Bottom is a cross-platform graphical process/system monitor with a customizable
interface and a multitude of features.
Two unit tests were added validate the module behavior for an empty
configuration and the example configuration.
```
```
=> bottom: add module

modules/files.nix
Codespaces didn't put in the correct PR template.
I found this error message confusing. It wasn't clear to me how and where to use the `-b` option and what the `-b` option does.
=> Clarify "Please move the above files" message

modules/programs/sbt.nix, tests/modules/programs/sbt/credentials.nix
I hadn't realized I actually never used this functionality. When I tried, I noticed the result of any command would include a trailing newline, which is never part of a password so it would virtually never work.
This ensures we only keep the content actually present in the file.
```
```
=> sbt: Run passwordCommand without trailing newline

modules/programs/starship.nix
=> starship: initialize using command in profile

docs/faq.adoc, modules/services/easyeffects.nix, modules/services/pulseeffects.nix
Specifically, instead of
services.dbus.packages = with pkgs; [ gnome.dconf ];
we now recommend
programs.dconf.enable = true;
which does the same and more.
```
```
=> dbus: improve recommended NixOS configuration

modules/programs/astroid.nix
By maildir spec, emails should be under mailbox/folder/[cur,tmp,new].
Even the [default astroid config](https://github.com/astroidmail/astroid/wiki/Configuration-Reference#accountsaccountnamesave_sent_to) specifies `Default : /home/root/Mail/drafts/`
```
```
=> astroid: fix maildir paths

modules/services/xsettingsd.nix, tests/default.nix, tests/modules/services/xsettingsd/basic-configuration.conf, tests/modules/services/xsettingsd/basic-configuration.nix, tests/modules/services/xsettingsd/default.nix
This introduces a `config` option for xsettingsd, making it fully configurable through home-manager. 
I've also added a `configLocation` option, which works by setting xsettingsd's `-c` option on the systemd unit.
The unit now can reload its configuration ([as documented here](https://github.com/derat/xsettingsd/wiki/Installation#configuration)), which it does when the managed config is changed.
I took extra care to include a `mkIf` to avoid writing the configuration if it's not set, to keep backward compatibility with configurations not managed through home-manager.
Please let me know if you have any feedback!
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more …
=> xsettingsd: make configurable through module

.github/CODEOWNERS, Makefile
The idea of this file is to make it easier to run tests. It will ensure that the tests are running with the correct `NIX_PATH` (pointing it to e.g.: unstable), and also allowing it to run either one or all tests.
The reason I am creating this is that I always forget the correct incantation to run `home-manager` tests (yeah, it is on the manual, however I use stable generally so I also need to remember to point it to unstable).
This is just an idea to make it easier for newcomers or people that rarely commit to this repo (like me).
```
``` …
=> Makefile: init

modules/services/emacs.nix, tests/modules/services/emacs/emacs-service-27.nix, tests/modules/services/emacs/emacs-service-28.nix, tests/modules/services/emacs/emacs-service-emacs.service, tests/modules/services/emacs/emacs-socket-27.nix, tests/modules/services/emacs/emacs-socket-28.nix, tests/modules/services/emacs/emacs-socket-emacs.service
=> emacs: allow adding command-line arguments to the emacs daemon.

modules/misc/gtk.nix, tests/modules/misc/gtk/gtk-basic-config-expected.conf
Thunar seems to force a newline at the end of the GTK bookmarks file.
```
```
=> gtk: add final newline to bookmarks to avoid conflicts

modules/services/kanshi.nix, tests/modules/services/kanshi/basic-configuration.conf, tests/modules/services/kanshi/basic-configuration.nix
kanshi configurations can have more than one exec statement in a profile. This change allows `services.kanshi.profiles.<name>.exec` to be a list of strings rather than a single string. Bare strings are coerced to single-element lists for backwards compatibility.
```
```
=> kanshi: allow multiple exec statements per profile

modules/misc/fontconfig.nix
Creating actual files is a bit silly here, it suffices to create two directories.
```
```
=> fontconfig: use a prettier "real directory" hack

nixos/default.nix
Fixes #1792
cc @berbiche @lilyball
```
```
=> nixos: add modulesPath to specialArgs

README.md, docs/installation.adoc, modules/programs/fish.nix
`config.fish` generated by Home Manager have superfluous config guards, at least to my eyes.
We don't have them in neither bash and zsh config. And even if the guard does make sense, there's no need to use separate variables for each section.
These are present when Fish module is added, ~~we may never the reason behind it~~ (edit: it seems inherited from the corresponding Nixpkgs/NixOS module), but it doesn't affect the fact theses are unnecessary and can be removed safely.
```
``` …
=> fish: simplify config guards

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/misc/news.nix, modules/services/screen-locker.nix, tests/default.nix, tests/modules/services/screen-locker/basic-configuration.nix, tests/modules/services/screen-locker/default.nix, tests/modules/services/screen-locker/moved-options.nix, tests/modules/services/screen-locker/no-xautolock.nix
xautolock isn't really needed to trigger xss-lock on the basis of time
since the built-in screensaver functionality of X serves as one of the
event sources for xss-lock. Keeping it around and defaulting to
"enabled" to avoid unexpected breakage.
Also shuffled around the options to submodules for xss-lock and
xautolock to get rid of prefixes in option names and to make detectSleep
a bit clearer.
Resolves #2341 
```
```
=> screen-locker: Make xautolock optional, reorganize options

modules/programs/fzf.nix
This is to better integrate with more advanced shell history managers like McFly and Atuin. By initializing fzf first, we allow the history managers to steal the C-r key binding from fzf.
Could potentially cause problems if somebody relies on the existing order. Should be easy to fix by using `mkBefore`.
```
```
=> fzf: do shell initialization a bit earlier

Makefile
- Add `NIXPKGS_REV`, so we can pass arbitrary revisions for testing (for example, `release-21.05` so we can test backports).
- Add `format` target, that calls the format script.
```
```
=> Makefile: improvements

modules/programs/vim.nix
Feel free to suggest a better option name.
```
```
=> vim: add option to specify pkgs.vim_configurable

nix-darwin/default.nix, nixos/default.nix
Having either argument defined based on the OS is a problem when
trying to write generic Nix code.
The current workaround is to use accept both and specify a default
value for each argument:
```
{ config, lib, nixosConfig ? {}, darwinConfig ? {}, ... }:
let
osConfig = nixosConfig // darwinConfig;
in
{
}
```
```
```
=> nix-darwin,nixos: replace {darwin,nixos}Config with osConfig

modules/programs/hexchat.nix
The original example was very complex, involving `mkDerivation` with `pkgs.unzip` as `buildInputs`. However, this can be heavily simplified by using `pkgs.fetchzip` instead.
The only non-obvious issues are:
- Since the extension ends with `.hct`, `pkgs.fetchzip` doesn't know what to do with it. However there is a workaround here: https://github.com/NixOS/nixpkgs/issues/60157#issuecomment-524965720
- The `.hct` file doesn't have any directories (`pkgs.fetchzip` expects either a file or a directory). Passing `stripRoot = false;` solves this issue
```
``` …
=> hexchat: simplify theme example

Makefile, home-manager/home-manager.nix, modules/lib/dag.nix, modules/lib/file-type.nix, modules/lib/gvariant.nix, modules/lib/strings.nix, modules/lib/types-dag.nix, modules/lib/types.nix, tests/lib/types/dag-merge.nix, tests/lib/types/dag-submodule.nix, tests/lib/types/gvariant-merge.nix, tests/lib/types/list-or-dag-merge.nix
Probably [this PR from nixpkgs](https://github.com/NixOS/nixpkgs/pull/101139) summarizes the reason better than I can.
This PR only tackles `lib` and `home-manager` for now, that should brings the most benefits and performance improvements (if any). Most modules also uses this pattern, but I don't think we should enforce this tree-wide unless there is a better way to migrate this (maybe with a tool).
```
```
=> {lib,home-manager}: remove top-level with

modules/programs/htop.nix, tests/modules/programs/htop/default.nix, tests/modules/programs/htop/header_layout.nix
When `header_columns` is in settings it must appear before any of the
`column_meters_*` options.
Fixes #2426.
```
```
=> htop: fix order or header_columns setting

docs/release-notes/rl-2111.adoc, modules/home-environment.nix
If the keyboard configuration is an empty set, don't run the setxkbmap service.
The default values for all keyboard options are null or empty so long as the state version is set to 19.09 or higher (21.05 being the
latest version).
Fixes #2219 
CC; @sigprof @dschrempf 
If you need guidance to test this PR, let me know.
```
```
=> xsession: don't reset the inherited keyboard options

modules/home-environment.nix
The example for `home.sessionPath` included a tilde in one of the paths. The tilde would end up in the `PATH` verbatim and not get expanded by the shell. This PR changes the example and documents how the paths are quoted before they end up in the `PATH`.
```
```
=> home-environment: document how home.sessionPath paths are escaped

modules/programs/zplug.nix, tests/modules/programs/zplug/modules.nix
Add an option to set custom $ZPLUG_HOME. Changing it with home.sessionVariables doesnt work, since it has to be exported before Zplug is initialised
```
```
=> programs.zsh.zplug: add zplugHome option

home-manager/install.nix, modules/misc/xdg.nix, tests/modules/home-environment/session-variables.nix, tests/modules/misc/xdg/file-gen.nix
It corresponds to the newly introduced `XDG_STATE_HOME`.
See: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables
```
```
=> xdg: add option 'xdg.stateHome'

modules/home-environment.nix
Implements #1809. I'm not sure that this is the best way to do it. Maybe it is better to do something like `default = config.home.shellAliases`?
```
```
=> shell agnostic aliases

tests/modules/programs/kakoune/default.nix, tests/modules/programs/kakoune/no-plugins.nix, tests/modules/programs/kakoune/stubs.nix, tests/modules/programs/kakoune/use-plugins.nix, tests/modules/programs/kakoune/whitespace-highlighter-corner-cases.nix, tests/modules/programs/kakoune/whitespace-highlighter.nix
- Enable use-plugins test.
- Stub out `kakoune-unwrapped` to avoid unnecessary downloads.
- Unwrap unnecessary `config` attributes.
```
```
=> kakoune: clean up tests

modules/programs/direnv.nix
Since https://github.com/NixOS/nixpkgs/pull/144197 flake support is
always available. The upstream `enableFlakes` option is scheduled to be
removed altogether in https://github.com/NixOS/nixpkgs/pull/145236
```
```
=> direnv.nix-direnv: remove enableFlakes

home-manager/default.nix, home-manager/install.nix, modules/home-environment.nix, modules/programs/fish.nix, tests/modules/programs/firefox/profile-settings.nix, tests/modules/programs/firefox/state-version-19_09.nix
See, e.g., https://github.com/NixOS/nix/issues/4442 for wider discussions.
```
```
=> Remove remaining `allowSubstitutes = false`

README.md, nix-darwin/default.nix, nixos/default.nix
Clarifies, with an example, the use of `extraSpecialArgs`.
See #2433, #698 for examples of confused users
cc @berbiche 
```
```
=> doc: improve extraSpecialArgs docs

README.md
Make it easier for other people to use flakes with home-manager on none NixOS.
```
```
=> Add example how to use flakes on none NixOS

home-manager/home-manager
=> home-manager: forward --no-write-lock-file

README.md, docs/installation.adoc, docs/usage.adoc
This gives a single source of truth of installation instructions and
we can also point to instructions for the NixOS and nix-darwin
modules.
```
```
=> docs: make README refer to installation chapter

modules/services/polybar.nix
Allow merging of lists and attrsets in polybar configs.
(I believe I need to set a description or something to fix recursive types in the docs, what do I need to do again?)
```
```
=> polybar: use recursive config type

modules/programs/offlineimap.nix
Nixpkgs switched to OfflineIMAP version 8 which means that Python 3 is
now used instead of Python 2. As a result, get_pass() now returns a
byte array instead of a string and the argument to get_pass() must be
a byte array too. See
https://github.com/OfflineIMAP/offlineimap3/issues/103.
```
```
=> offlineimap: Fix for OfflineIMAP 8

modules/programs/ssh.nix, tests/modules/programs/ssh/default-config-expected.conf, tests/modules/programs/ssh/default.nix, tests/modules/programs/ssh/forwards-dynamic-valid-bind-no-asserts-expected.conf, tests/modules/programs/ssh/includes.nix, tests/modules/programs/ssh/match-blocks-attrs-expected.conf
Add support for `Include` directive in ssh config files.
```
```
=> ssh: add includes option

docs/release-notes/rl-2111.adoc, modules/programs/pet.nix, tests/modules/programs/pet/default.nix, tests/modules/programs/pet/settings_21_05.nix, tests/modules/programs/pet/settings_21_11.nix
related gh issue: https://github.com/nix-community/home-manager/issues/2413
```
```
=> pet: Fix settings format issue

home-manager/home-manager
home-manager will now exit early if any nix builds fail and will ext with the right exit code.
Before the change if the nix builds failed home-manager would proceed presenting the news and would exit with 0 which breaks multiple script automation and aliases I use.
```
```
=> Fix exit codes

modules/home-environment.nix
This option has been stable for a long time and may be generally useful.
```
```
=> home-environment: make `home.profileDirectory` public

modules/services/flameshot.nix
Extend module for package-option, tested chages
```
```
=> flameshot: extend module with package-option

modules/misc/xdg.nix, tests/modules/misc/xdg/default-locations.nix, tests/modules/misc/xdg/default.nix
Fix typo which cause evaluation failure when `xdg.enable = false` and `home.stateVersion` >= 20.09.
```
```
=> xdg: fix typo and add test

modules/services/fnott.nix
I had forgotten to add myself as the maintainer when initially writing the module.
```
```
=> fnott: add polykernel as maintainer

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/window-managers/i3-sway/swaynag.nix, tests/modules/services/window-managers/sway/default.nix, tests/modules/services/window-managers/sway/swaynag-empty-settings.nix, tests/modules/services/window-managers/sway/swaynag-example-settings-expected.conf, tests/modules/services/window-managers/sway/swaynag-example-settings.nix
Swaynag is a replacement of i3-nag for sway. Swaynag is embedded in Sway's build
process albeit it is not an integral part of Sway, therefore it has been added
under `wayland.windowManager.sway` instead of `programs`. It can be moved at a later
time if necessary.
Two unit tests were added validate the module behavior for an empty
configuration and the example configuration.
```
```
=> swaynag: add module

modules/systemd.nix, tests/modules/systemd/default.nix, tests/modules/systemd/services-disabled-for-root.nix
For the user root, there are no user services provided by systemd.
Therefore, these files will never be used.
```
```
=> systemd: do not install systemd files when user is root

flake.nix
=> add flake attribute apps to make it easier to run

docs/release-notes/rl-2111.adoc, modules/misc/news.nix, modules/programs/taskwarrior.nix, tests/default.nix, tests/modules/programs/taskwarrior/default.nix, tests/modules/programs/taskwarrior/taskwarrior.nix
After taskwarrior 2.6.0, its default config file now locates in `$XDG_CONFIG_HOME/task/taskrc`, and builtin themes can be included via relative path.
This change relies on taskwarrior >= 2.6.0, which is already in `nixos-unstable`. Our `master` is also targeting unstable.
```
```
=> taskwarrior: change config file location and use relative theme path

modules/programs/vscode.nix
We can avoid doing an import from derivation for extensions that have a `vscodeExtUniqueId` attribute (i.e. the extensions generated by [`buildVscodeExtension`](https://github.com/NixOS/nixpkgs/blob/e75245614ee24b1e8bfafa836982013abca33642/pkgs/misc/vscode-extensions/vscode-utils.nix#L3)), which should be the excruciating majority of extensions people use.
```
```
=> vscode: avoid unnecessary IFD

modules/programs/gpg.nix, tests/modules/programs/gpg/default.nix, tests/modules/programs/gpg/immutable-keyfiles.nix, tests/modules/programs/gpg/mutable-keyfiles.nix, tests/modules/programs/gpg/override-defaults.nix
Adds a new option `programs.gpg.keyfiles` to be an array of paths to gpg key exports.
Is implemented as an activation script that runs `gpg --import $key` for each key.
=> gnupg: Support declarative GPG keysfiles

home-manager/home-manager
Two misplaced quotations were introduced in `doBuild` by https://github.com/nix-community/home-manager/pull/2501, which
caused the parameter expansion of DRY_RUN to include an extraneous tab. Since the flake uri is passed
later into the command, Nix assumes the whitespace sequence as the flake uri and returns that it is not
a valid flake reference.
This PR removes the misplaced quotations in `doBuild` and also places the flake uri as the first argument for
calls to `doBuildFlake` for consistency with `doBuildAttr`. Placing the uri first in the command line also guards
against possible security issues if arbitrary uris are expanded prior to the user given uri.
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/d …
=> home-manager: fix home-manager build error

modules/programs/htop.nix
Backport of #2435 to fix #2426 on release 21.05 branch.
Relevant change is the addition of the `before` settings; the rest of the changed lines is `./format`.
```
```
=> htop: fix order or header_columns setting (backport)

modules/programs/direnv.nix
This reverts commit 1e5c8e9bff00d0844bc3d25d1a98eab5633e600b.
see https://github.com/NixOS/nixpkgs/issues/147974
```
```
=> Revert "direnv.nix-direnv: remove enableFlakes (#2458)"

modules/programs/firefox.nix
fix issue #2492 
Previously, home-manager would not create a user.js for a certain
profile if profile.bookmarks was not empty but
profile.settings was empty and profile.extraConfig was an
empty string.
```
```
=> firefox: create user.js when only bookmarks are specified in config (issue #2492)

.github/CODEOWNERS, modules/misc/news.nix, modules/targets/darwin/default.nix, modules/targets/darwin/options.nix
This includes the following changes to keep up to date with the latest version of macOS.
- darwin: keep the options for the "defaults" system up-to-date
- darwin: add midchildan to maintainers
It also adds myself to maintainers of the darwin module.
```
```
=> darwin: keep the options for the "defaults" system up-to-date

modules/programs/powerline-go.nix, tests/modules/programs/powerline-go/bash.nix, tests/modules/programs/powerline-go/bashmodulesright.nix, tests/modules/programs/powerline-go/default.nix, tests/modules/programs/powerline-go/zshmodulesright.nix
- Add `modulesRight` setting to instruct powerline-go to configure the right-hand side prompt.
- Use eval mode when `modulesRight` setting is set.
- Cleanup how the argument string is built to avoid double whitespace characters.
```
```
=> powerline-go: add support for -modules-right

modules/config/i18n.nix, modules/misc/xdg-mime.nix, modules/services/window-managers/xmonad.nix, modules/targets/darwin/fonts.nix
We are attempting to deprecate these top-level attrs in upstream nixpkgs.
See also bc0acdad8c001843d4e22cfa20a6ce84b462ab19
```
```
=> modules: pkgs.hostPlatform -> pkgs.stdenv.hostPlatform

modules/services/gpg-agent.nix, tests/default.nix, tests/modules/services/gpg-agent/default-homedir.nix, tests/modules/services/gpg-agent/override-homedir.nix
Rewrite the hash algorithm used for mimic `gpgconf` output in Nix to avoid IFD (import from derivation). IFD is not allowed in restricted mode, which is the default mode for Hydra. `nixos-install` seems also restrict it according to https://github.com/nix-community/home-manager/issues/1262#issuecomment-748672342
Also tests of `gpg-agent` seem not enabled. They're enabled now.
```
```
=> gpg-agent: rewrite hash algo in Nix to avoid IFD

modules/misc/news.nix, modules/programs/less.nix, tests/modules/programs/less/less-with-custom-keys.nix
Follow-up to https://github.com/nix-community/home-manager/pull/2463#issuecomment-968335345.
```
```
=> less: store 'lesskey' under XDG_CONFIG_HOME

docs/man-home-manager.xml, modules/misc/gtk.nix, modules/programs/alacritty.nix, modules/programs/atuin.nix, modules/programs/beets.nix, modules/programs/direnv.nix, modules/programs/hexchat.nix, modules/programs/htop.nix, modules/programs/kakoune.nix, modules/programs/kitty.nix, modules/programs/lazygit.nix, modules/programs/lsd.nix, modules/programs/mangohud.nix, modules/programs/mpv.nix, modules/programs/ncspot.nix, modules/programs/noti.nix, modules/programs/nushell.nix, modules/programs/rtorrent.nix, modules/programs/sm64ex.nix, modules/programs/starship.nix, modules/programs/topgrade.nix, modules/services/grobi.nix
Currently, dot directories and xdg base directories are used inconsistently in the home-manager
option declarations. This creates ambiguity for the user as to where the location of the file
should be albeit this is rarely encountered in practice as it is sufficient to read upstream
documentation. The rationale for the generalization is to make declarations consistent and make
a clear distinction between hardcoded and modular specifications.
References to ~/.config in relevant nixpkgs modules were untouched as the location is hardcoded
upstream[1]. Furthermore, modules of programs which do not follow xdg specifications were also untouched.
Generalization of tilde(~) expansions to $HOME were also considered, however there isn't sufficent
rationale despite the use of $HOME being more …
=> treewide: generalize dot directories to xdg base directories

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/gromit-mpx.nix, tests/default.nix, tests/modules/services/gromit-mpx/basic-configuration.cfg, tests/modules/services/gromit-mpx/basic-configuration.nix, tests/modules/services/gromit-mpx/default-configuration.cfg, tests/modules/services/gromit-mpx/default-configuration.nix, tests/modules/services/gromit-mpx/default.nix, tests/modules/services/gromit-mpx/nmt-script.nix
Add a new module for the [Gromit-MPX](https://github.com/bk138/gromit-mpx) service.
Since Gromit-MPX uses a non-standard, custom configuration file format, *and* the configuration options have been stable for many years, this module provides all configuration options as Nix options.  I originally wrote this module back in 2015 and none of the Nix options have changed since then.
Note: I'm also the maintainer of the Gromit-MPX module in nixpkgs.
```
```
=> gromit-mpx: add module

modules/programs/navi.nix
Otherwise we get the following warning:
bash: bind: warning: line editing not enabled
```
```
=> navi: don't install widget on terminals with limited capabilities

README.md, home-manager/default.nix, home-manager/home-manager, home-manager/po/home-manager.pot, home-manager/po/sv.po, lib/bash/color-echo, lib/bash/home-manager.sh, modules/files.nix, modules/home-environment.nix, modules/lib-bash/activation-init.sh, modules/po/hm-modules.pot, modules/po/sv.po, xgettext
The support for translated strings is, for now, limited to strings generated in Bash code.
Resurrection of #1972 with more polished implementation and support for i18n in (bundled) activation scripts.
```
```
=> home-manager: add basic i18n support

home-manager/install.nix, home-manager/po/home-manager.pot, xgettext
Make it possible to translate the installation script output.
```
```
=> home-manager: support i18n of install script

modules/services/window-managers/xmonad.nix
Starting from
[~v0.17.0](https://github.com/xmonad/xmonad/commit/9813e218b034009b0b6d09a70650178980e05d54),
xmonad moved the location of its recompile output binary. This change
accommodates that. We might want to drop support for v0.15.0 at some point,
when it hits stackage LTS making `haskellPackages.xmonad` resolve to v0.17.0
(currently, it does not, although there is a separate
`haskellPackages.xmonad_0_17_0`).
```
```
=> xmonad: add support for v0.17.0

modules/programs/gpg.nix, tests/modules/programs/gpg/immutable-keyfiles.nix
Allow setting `trust` by name (unknown, never, marginal, full, ultimate) instead of magic value (1-5).
Also make `importTrust` output `y` only when [required](https://github.com/gpg/gnupg/blob/283ccbc824d8062b86e27818a84ab5a29facd7a5/g10/pkclist.c#L332-L335).
cc @MilesBreslin 
```
```
=> gpg: allow specifying trust levels by name

modules/programs/waybar.nix, tests/modules/programs/waybar/default.nix, tests/modules/programs/waybar/settings-complex-expected.json, tests/modules/programs/waybar/settings-complex.nix, tests/modules/programs/waybar/settings-with-attrs.nix
This change allows using attrs for waybar settings while still keeping backward compatibility and allowing lists.
Motivation: having a name for each bar makes it possible to override specific values easily.
```
```
=> waybar: allow using attrs for settings

modules/misc/gtk.nix
Fixes https://github.com/nix-community/home-manager/issues/2572 . Adding support to configure GTK4. I use this to prefer dark theme styling:
```
gtk.gtk4.extraConfig = {
gtk-application-prefer-dark-theme = true;
};
```
```
```
=> gtk: Add support for GTK4 configuration

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/systembus-notify.nix
Sets up a user systemd service for [`systembus-notify`](https://github.com/rfjakob/systembus-notify)
```
```
=> modules/services/systembus-notify: init

modules/xsession.nix
This fixes #1638; xplugd will restart setxkbmap if a new keyboard is
plugged in to ensure it is also configured correctly.
```
```
=> xsession: add xplugd service to accompany setxkbmap

modules/programs/waybar.nix, tests/modules/programs/waybar/systemd-with-graphical-session-target.nix, tests/modules/programs/waybar/systemd-with-graphical-session-target.service
Before this PR, a user needed to override the systemd target that
would start Waybar with `mkForce`, this is no longer necessary.
I think the option name needs to be changed, but I don't have any better idea.
Linked to: https://github.com/nix-community/home-manager/issues/2505#issuecomment-977442048
```
```
=> waybar: configurable systemd WantedBy target

.github/CODEOWNERS, modules/misc/dconf.nix
I removed gnidorah from the maintainers list of dconf and the codeowners file, matching https://github.com/NixOS/nixpkgs/pull/121119.
```
$ nix eval .#homeConfigurations.lun
error: attribute 'gnidorah' missing
at /nix/store/x594sxkl8gd42rxbispbq924qzk89nj1-source/modules/misc/dconf.nix:14:24:
13| in {
14|   meta.maintainers = [ maintainers.gnidorah maintainers.rycee ];
|                        ^
15|
```
```
```
=> Remove gnidorah from maintainers/CODEOWNERS due to being removed from nixpkgs maintainers

modules/programs/hexchat.nix, modules/programs/lf.nix, modules/programs/mbsync.nix, modules/programs/neovim.nix, modules/programs/vim.nix, modules/services/fnott.nix, modules/services/window-managers/i3-sway/lib/functions.nix
See https://github.com/nix-community/home-manager/pull/2566.
```
```
=> treewide: use `remove` when possible

modules/programs/alacritty.nix
Since the repository was moved, the old link was pointing nowhere.
```
```
=> alacritty: correct example config link

.github/CODEOWNERS, .github/workflows/test.yml, default.nix, docs/default.nix, modules/lib/maintainers.nix, modules/misc/xdg-desktop-entries.nix, modules/programs/broot.nix, modules/programs/exa.nix, modules/programs/hexchat.nix, modules/programs/htop.nix, modules/programs/lazygit.nix, modules/programs/ncmpcpp.nix, modules/programs/xmobar.nix, modules/services/kanshi.nix, modules/services/pasystray.nix, modules/services/playerctld.nix, modules/services/status-notifier-watcher.nix, modules/services/trayer.nix, modules/services/wlsunset.nix
Many entries in maintainers either had no entry in maintainers.nix, or were missing `hm.`.
One more was removed from nixpkgs' maintainers list and should probably be removed here.
Marked this as a draft so it doesn't ping everyone involved asking for review on Christmas day, it can wait!
```
```
=> Fix more missing / removed maintainer entries

modules/programs/bash.nix, tests/modules/programs/bash/logout.nix, tests/modules/programs/bash/session-variables.nix
Remove unnecessary shebang and executable bit for bash dotfiles while keeping the syntax checks.
I was not able to run the tests in my setup (without any channels).
```
```
=> bash: remove unnecessary shebang and executable bit for dotfiles

tests/modules/programs/bottom/empty-settings.nix, tests/modules/programs/bottom/example-settings-expected.toml, tests/modules/programs/bottom/example-settings.nix
The empty configuration test for the bottom module introduced as of https://github.com/nix-community/home-manager/pull/2323
is not cross platform. Specifically, it silently fails under a darwin environment due to
the configuration file not being generated at $XDG_CONFIG_HOME. This PR add cross platform support
by specifying the platform-dependent configuration directories to check. The expected unit test data
was also extracted to a separate file to differentiate between test data changes and
changes to the test itself.
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commit …
=> bottom: fix empty-settings test on darwin

docs/man-home-manager.xml, home-manager/completion.bash, home-manager/completion.fish, home-manager/completion.zsh, home-manager/home-manager
=> home-manager: document the `--version` command option

tests/big-test.nix, tests/default.nix, tests/modules/misc/debug/default.nix, tests/modules/programs/emacs/extra-config.nix, tests/modules/programs/firefox/deprecated-native-messenger.nix, tests/modules/programs/firefox/profile-settings.nix, tests/modules/programs/firefox/state-version-19_09.nix
This makes it possible to identify the test as big in the test file itself. It also seems like a more natural way to control the test running.
```
```
=> tests: make `enableBig` an option

home-manager/po/home-manager.pot, modules/home-environment.nix, modules/lib-bash/activation-init.sh, modules/po/hm-modules.pot
=> treewide: make a few more strings translatable

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/swayidle.nix, tests/default.nix, tests/modules/services/swayidle/basic-configuration.nix, tests/modules/services/swayidle/default.nix
Add module `services.swayidle`. This module has been running stable on my laptop for about a year. I thought it might be nice to contribute it :)
```
```
=> swayidle: add module

modules/programs/rofi.nix, tests/modules/programs/rofi/custom-theme.rasi
Move `@import` and `@theme` directives to the top of custom theme definitions so as to allow extending other themes.
Without this, a theme like
```nix
{
"@import" = "default";
"*".background = background;
}
```
would have the default background colour because `*` sorts before `@`.
@thiagokokada @lilyinstarlight 
```
```
=> rofi: allow extending themes

modules/services/emacs.nix, tests/modules/services/emacs/default.nix, tests/modules/services/emacs/emacs-default-editor.nix, tests/modules/services/emacs/emacs-default-editor.sh
Adds a `defaultEditor` option to `modules/services/emacs.nix` that sets `emacsclient` as the default text editor using the `EDITOR` environment variable. Also passes `--create-frame` to `emacsclient` if no arguments are given, so a new frame is opened instead of a file (otherwise, `emacsclient` fails with `file name or argument required`).
```
```
=> services/emacs: add option to set `emacsclient` as the default editor

tests/modules/programs/gh/credential-helper.nix
See https://github.com/nix-community/home-manager/pull/2628#issuecomment-1009558143
```
```
=> gh: remove git overlay in tests

modules/programs/skim.nix
Closes https://github.com/nix-community/home-manager/issues/2627
I hastily merged the previous Skim PR without looking at the entire file.
```
```
=> skim: use cfg.package in shell integrations

docs/installation.adoc
This includes the root Nix channels in `NIX_PATH` in the instructions for setting up Home Manager on non-NixOS (at the end of the second step under [Standalone installation](https://nix-community.github.io/home-manager/index.html#sec-install-standalone)). On system-wide Nix installations, the `nixpkgs` channel is located in `/nix/var/nix/profiles/per-user/root/channels` (instead of `~/.nix-defexpr/channels`), which is now by default not included in `NIX_PATH` on non-NixOS. Mentioning that it must be added manually should help users running into #2564.
This also links to a reply on the NixOS Discourse that explains the `NIX_PATH`-related changes made to Nix and removes the note on logging out and back in on NixOS as that does not seem necessary (please correct me if I'm wrong).
``` …
```
=> docs: clarify stand-alone installation instructions

modules/misc/news.nix
The gnome3.dconf alias doesn't exist anymore, it's now in pkgs.dconf
directly.
=> modules/misc/news.nix: fix instructions

modules/programs/kitty.nix
Add an option to specify which kitty package should be installed.
```
```
=> kitty: Allow package to be configurable

modules/programs/direnv.nix
Add direnv hook to fish shell. 
The end result is that the auto-generated `~/.config/fish/config.fish` will have `/nix/store/<hash>-direnv-<ver>/bin/direnv hook fish | source` to initiate direnv's fish hook (see: https://direnv.net/docs/hook.html#fish)
```
```
=> direnv: Add fish shell hook

modules/programs/kakoune.nix
These were renamed in v2021.08.28, commit [7e66846172165eb1f860f26f51f7a20790b0af29](https://github.com/mawww/kakoune/commit/7e66846172165eb1f860f26f51f7a20790b0af29#diff-7b9337fcff3141736997afd31f7a2764b3538153922282c8407af5f43d543cab).
`xdg-desktop-entries` fails but that is unrelated (fails on `master` as well).
```
```
=> kakoune: fix ui options

modules/i18n/input-method/kime.nix, tests/modules/i18n/input-method/default.nix, tests/modules/i18n/input-method/kime-configuration.nix
Fix `i18n.inputMethod.kime` systemd service. (`PartOf` -> `Unit.PartOf`)
```
```
=> kime: Fix kime systemd service broken

modules/programs/rofi.nix
Extract only the `finalPackage` change from #2432.
cc: @thiagokokada
```
```
=> rofi: add finalPackage option

modules/services/window-managers/bspwm/default.nix
Otherwise the fix doesn't affect applications launched via sxhkd.
```
```
=> bspwm: set _JAVA_AWT_WM_NONREPARENTING in xsession.profileExtra

modules/programs/kakoune.nix
Backporting #2641 because nixpkgs 21.11 has kakoune 2021.11.08.
```
```
=> backport to 21.11: kakoune: fix ui options

.github/stale.yml
fixed a couple of typos in the messages emitted by the stale bot
```
```
=> github: copyedit stale bot's messages

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/programs/helix.nix, modules/programs/watson.nix, tests/default.nix, tests/modules/programs/helix/default.nix, tests/modules/programs/helix/example-settings.nix, tests/modules/programs/helix/languages-expected.toml, tests/modules/programs/helix/settings-expected.toml, tests/modules/programs/helix/theme-base16-expected.toml, tests/modules/programs/watson/default.nix, tests/modules/programs/watson/empty-settings.nix, tests/modules/programs/watson/example-settings-expected.ini, tests/modules/programs/watson/example-settings.nix
Watson is a CLI for tracking your time.
Two unit tests were added to validate the module behavior for
an empty configuration and the example configuration.
```
```
=> watson: add module

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/programs/helix.nix, tests/default.nix, tests/modules/programs/helix/default.nix, tests/modules/programs/helix/example-settings.nix, tests/modules/programs/helix/languages-expected.toml, tests/modules/programs/helix/settings-expected.toml, tests/modules/programs/helix/theme-base16-expected.toml
Adds helix-editor as module supporting the options settings, languages and themes and package.
This currently requires (and is tested with) helix-editor from master (using the current https://docs.helix-editor.com/ as reference), which is why I marked this as a draft (I'm not sure what helix-editor 0.5 supports, and it's not officially documented AFAIK)
Apart from this version issue, this PR is ready to merge.
I'm not sure if it makes sense to merge this as is, or to wait for a new release of helix.
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for …
=> helix: add module

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/programs/timidity.nix
Add a module for timidity, originally inspired by https://discourse.nixos.org/t/adding-soundfont-for-timidity-requires-rebuilding/16784
By default, timidity does not consider any configuration files in `~`, so I did not add an intermediate config file via `home.file` in this case, but I have no strong opinion here.
```
```
=> timidity: Add module

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/pandoc.nix, tests/default.nix, tests/modules/programs/pandoc/csl.nix, tests/modules/programs/pandoc/default.nix, tests/modules/programs/pandoc/defaults-expected.json, tests/modules/programs/pandoc/defaults.nix, tests/modules/programs/pandoc/example.csl, tests/modules/programs/pandoc/output-expected, tests/modules/programs/pandoc/stub.nix, tests/modules/programs/pandoc/template.latex, tests/modules/programs/pandoc/templates.nix
Add a module for pandoc that provides the following:
1. Setting default configuration options.
2. Installing teampltes.
3. Installing citation styles.
```
```
=> pandoc: Add new module

modules/programs/atuin.nix, tests/modules/programs/atuin/default.nix, tests/modules/programs/atuin/fish.nix, tests/modules/programs/atuin/no-shell.nix
This adds an enableFishIntegation config key to atuin, which allows atuin to be used in the fish shell without needing to manually add it to fish's config.
Don't use this yet, I need to ~~re-commit for proper formatting~~ done, ~~now I need to make the tests not fail.~~
I think that this is done! LMK if I need to make any changes!
```
```
=> Add Atuin Fish integration

tests/default.nix
The issue is now fixed in Nixpkgs.
```
```
=> tests: re-enable commented tests

modules/services/syncthing.nix, tests/modules/services/syncthing/default.nix, tests/modules/services/syncthing/extra-options.nix
Add escape hatch for adding additional command line options.
```
```
=> syncthing: add option `extraOptions`

modules/misc/nix.nix, modules/modules.nix
Adds `nix.registry` option to allow users to generate the user registry `~/.config/nix/registry.json` (the precedence of this file can be found at: https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-registry.html#description)
This should be useful for non-NixOS users as it will make it easier for them to generate this file and set flake registry overrides, and for NixOS users they will be able to set user level overrides.
This was lifted with love from https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/misc/nix-daemon.nix#L503-L553
```
``` …
=> nix: add module

.github/CODEOWNERS, modules/modules.nix, modules/programs/exa.nix, modules/programs/ion.nix, modules/programs/starship.nix
Add basic configuration options for ion shell with support for exa and starship.
```
```
=> ion: Add module

docs/installation.adoc
Yes, something did go wrong, and no, I had no clue what it was nor how to have more info.
Thankfully I fell upon [this issue](https://github.com/nix-community/home-manager/issues/2464)
which gave me the key to getting HM's output.
The issue was trivial to fix (a config file was in HM's way), but I had to have the info.
Add note in the 1.2 NixOS Module section of the manual to help solve issues when using home-manager as a nixos module.
```
```
=> Help debug issues when using as a NixOS module

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/modules.nix, modules/services/home-manager-auto-upgrade.nix, tests/default.nix, tests/modules/services/home-manager-auto-upgrade/basic-configuration.nix, tests/modules/services/home-manager-auto-upgrade/default.nix
Hi,
Add a simple module to periodically upgrade Home Manager (it just runs `home-manager switch` in a SystemD's service)
```
```
I wrote test, but it might be better
i don't really know neither what and how to test
---
The documentation generation failed on a file that i didn't changed, i don't know how to fix it
```
nix-build -A docs.html
error: attribute 'anything' missing, at /home/pinage404/Project/home-manager/modules/programs/matplotlib.nix:26:28
(use '--show-trace' to …
```
=> home-manager.auto-upgrade: add module

modules/programs/sbt.nix, tests/modules/programs/sbt/credentials.nix
Follows from #2337 - the code didn't actually work in sbt 1.0 because `lazyLines` isn't a thing in Scala 2.12.
This kind of reverts the above change, but adds trimming the password command's output under the assumption that passwords don't have surrounding whitespace.
I've checked the credentials sbt receives and they match the file's contents (`.last` char isn't whitespace)
```
```
=> sbt: trim output of password command

modules/programs/bash.nix
Allows using extglob in initialisation files. See https://github.com/NixOS/nixpkgs/pull/151371
That change got into `master` 2 days ago and into `nixos-unstable` an hour ago, so we might want to wait a bit before merging.
```
```
=> bash: use shellDryRun to check scripts

modules/programs/vscode.nix
Add `programs.vscode.immutableExtensionsDir` option to prevent extensions from being installed/updated imperatively.
```
```
=> vscode: Add immutable extensions dir option

.github/CODEOWNERS, modules/modules.nix, modules/services/plex-mpv-shim.nix
Adds a home-manager module to create a config file and run a systemd user service for [plex-mpv-shim](https://github.com/iwalton3/plex-mpv-shim)
```
```
=> plex-mpv-shim: init service

modules/programs/man.nix
=> man: add package option

nix-darwin/default.nix
The fix for https://github.com/nix-community/home-manager/issues/2178
did not apply the patch to nix-darwin too.
See: https://github.com/nix-community/home-manager/issues/2178#issuecomment-1029015498
```
```
=> darwin: add Nix package to activation $PATH

modules/programs/kitty.nix, tests/modules/programs/kitty/example-settings-expected.conf
Add a new option to use the recently added `kitty-themes` nix package to set the theme. Use the friendly name of the theme seen in `kitty +kitten themes` 
https://github.com/kovidgoyal/kitty-themes
The current test for kitty is a simple match against a example file. Because this change adds a path to the nix store, that will no longer work because the path can change. I'm not sure if it's worth re-writing all the kitty tests just to cover themes
```
```
=> kitty: add option `theme`

README.md, docs/manual.xml, docs/nix-flakes.adoc, docs/usage.adoc
Move the flake-based setup documentation from `README.md` to Home Manager Manual.
This makes the `README.md` more compact while allowing us to document the step-by-step instructions for the three kinds of flake setup (standalone installation /NixOS module / nix-darwin module) the way we have done for the channel-based setup.
This is the first time I make a PR about the README.md and the manual, and I'm not so familiar about writing documentations. Feel free to tell me about how to improve it.
```
```
- If …
=> docs: Move Nix Flakes setup documentation from README.md to the manual

docs/nix-flakes.adoc, home-manager/completion.bash, home-manager/completion.fish, home-manager/completion.zsh, home-manager/home-manager
This change enable the `home-manager` command-line utility to pass through `--experimental-features` and `--extra-experimental-features` to override or extend the Nix configuration in the environment and enable unprivileged users to use `home-manager --flake` when `nix-command` and `flakes` is not included in the system `experimental-featuers`. 
```
```
=> home-manager: pass through `--experimental-features` and `--extra-experimental-features`

modules/programs/neovim.nix, tests/modules/programs/neovim/plugin-config.nix
Extend neovim program to allow specifying additional lua libraries that will become available to neovim at runtime.  See #1964 for further details.
```
```
This is a rebased version of the #1970 which got closed by some reason, without being merged.  Can we please merge this? @teto ?
=> neovim: add `extraLuaPackages` to neovim, fixes #1964.

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/programs/zellij.nix
=> zellij: add module

modules/programs/zsh.nix, tests/modules/programs/zsh/session-variables.nix
This patch moves both home.sessionVariables and
programs.zsh.sessionVariables from .zshrc to .zshenv. Additionally,
these two kinds of session variables will not be sourced more than
once to allow user-customized ones to take effect.
Before, session variables are in .zshrc, which causes non-interactive
shells to not be able to get those variables. For example, running a
command through SSH is in a non-interactive and non-login shell, which
suffers from this. With this patch, all kinds of shells can get
session variables.
The reason why these session variables are not moved to .zprofile is
that programs started by systemd user instances are not able to get
variables defined in that file. For example, GNOME
Terminal (gnome-terminal-server.service) is one of these programs and
doesn't get …
=> zsh: move sessionVariables from .zshrc to .zshenv

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/eww.nix
=> eww: add module

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/espanso.nix, tests/default.nix, tests/modules/services/espanso/basic-configuration.nix, tests/modules/services/espanso/basic-configuration.service, tests/modules/services/espanso/basic-configuration.yaml, tests/modules/services/espanso/default.nix
Espanso is a text expanding application, this PR adds a module to declaratively configure it.
With Nix it's possible to make very interesting abstractions, that are more integrable than the default yaml format.
```
```
=>  espanso: add module 

modules/programs/atuin.nix
Otherwise we get the following warning for terminals with limited
capabilities:
bash: bind: warning: line editing not enabled
```
```
=> atuin: don't install widget on limited terminals

modules/programs/himalaya.nix
The `smtp-starttls` option was previously to the value of `account.imap.tls.useStartTls`, when I believe `account.smtp.tls.useStartTls` should be used instead
```
```
=> himalaya: fix smtp-starttls option

modules/programs/foot.nix, tests/modules/programs/foot/systemd-user-service-expected.service
Previously, if a process inside a foot client triggered the OOM killer,
systemd would also kill the parent unit, namely the foot server.
This is not ideal if a user has a lot of clients attached, and it's
usually not the terminal emulator's fault that a process inside it has
ended up using all the available memory.
```
```
=> foot: set OOMPolicy=continue for foot server

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/programs/gitui.nix
Gitui module added to programs.
I'm not sure how to test this module.
```
```
=> gitui: Add module

modules/programs/vscode.nix
Changed name of extension `bbenoist.nix` to all lowercase as nix would complain about a missing `Nix` attribute otherwise.
```
```
=> vscode: fix name of extension in example

modules/programs/neovim.nix
Removing the trace log statement of vim plugins within the Neovim module.  Fixes https://github.com/nix-community/home-manager/issues/2756
```
```
=> neovim: remove trace log of vim plugins (#2756)

.github/CODEOWNERS, docs/release-notes/rl-2205.adoc, format, modules/launchd/default.nix, modules/launchd/launchd.nix, modules/misc/news.nix, modules/modules.nix, tests/default.nix, tests/modules/launchd/agents.nix, tests/modules/launchd/default.nix, tests/modules/launchd/expected-agent.plist
Add support for macOS LaunchAgents, the equivalent of systemd user services.
Here's a little example of how to use this module:
```nix
launchd.agents.syncthing = {
enable = true;
config = {
ProgramArguments = [ "${pkgs.syncthing}/bin/syncthing" "-no-browser" "-no-restart" ];
KeepAlive = {
Crashed = true;
SuccessfulExit = false;
};
ProcessType = "Background";
};
};
```
```
```
=> launchd: initial support for LaunchAgents

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/modules.nix, modules/programs/tiny.nix
Added module for [tiny](https://github.com/osa1/tiny), a TUI IRC client written in Rust. Thanks to @ratsclub for helping me write my first Nix module!
```
```
=> tiny: add module

modules/misc/xdg-desktop-entries.nix, tests/modules/misc/xdg/desktop-entries.nix, tests/modules/misc/xdg/desktop-full-expected.desktop, tests/modules/misc/xdg/desktop-min-expected.desktop
My system wouldn't build due to different errors after #2496 (nixpkgs unstable, hm master - both local checkouts contains what I've seen the relevant commits made for this), I adjusted the module from what I found as "wrong". (with [help](https://github.com/NixOS/nixpkgs/commit/066a581a80c0939423ff8b2d4b451a07ea8e5865) of and the current code)
I'm unsure if there is a replacement for "extraEntries = config.extraConfig;" as changelog says it got removed (but I left it in for feedback). Currently not even the example from the HM-Docs was working for me, which brought me on point - maybe we should add a test against it.
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) …
=> Issues with DesktopEntries after #2496

tests/default.nix, tests/modules/services/mpd/basic-configuration.conf, tests/modules/services/mpd/basic-configuration.nix, tests/modules/services/mpd/basic-configuration.service, tests/modules/services/mpd/default.nix
Just a simple test case.
```
```
=> mpd: add basic test case

modules/programs/i3status-rust.nix, tests/modules/programs/i3status-rust/with-default.nix
The i3status-rust format has changed. The default in home-manager is not valid format anymore. Without defining a bar, it generates a cryptic error about format and {Mup} .
This PR just updates to the latest format.
```
```
=> update i3status-rust default to new format

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/programs/just.nix
Adds a module for [just](https://github.com/casey/just) and its shell completions.
```
```
=> just: add module for the just command runner

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/programs/pubs.nix, tests/default.nix, tests/modules/programs/pubs/default.nix, tests/modules/programs/pubs/pubs-example-settings-expected-pubsrc, tests/modules/programs/pubs/pubs-example-settings.nix
Add [pubs](github.com/pubs/pubs) program module bringing basic configuration via `programs.pubs.config`. 
pubs configuration file uses ConfigObj syntax, which is similar to the INI files syntax but with extra functionnalities like nested sections. These functionnalities are used within pubs configuration file and prevent from using Nix's INI format parser. Here is an example of pubs configuration that cannot be parsed using Nix's INI format parser:
```ini
[plugins]
[[git]]
manual=False
```
For this reason, I opted for a stringly-typed configuration since the use of a structured `settings` option would require a custom parser.
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-s …
=> pubs: add module

modules/programs/irssi.nix
TL;DR: Don't nest concatStringsSep
`concatStringsSep` will return an empty string when called with empty array. The `concatStringsSep` called with `v.channels` would generate an empty string for each channel:
```
programs.irssi = {
networks = {
network1 = {
...
};
network2 = {
...
};
};
};
```
generates `[ "" "" ]`, which the `concatStringsSep` called with `v.networks` will use to generate
```
,
```
```
```
=> irssi: fix syntax error when no channels are specified

modules/programs/mu.nix, tests/default.nix, tests/modules/programs/mu/basic-configuration.nix, tests/modules/programs/mu/default.nix
This has no effect if the user does not have any aliases defined for
any accounts.
This will also only add `--my-address=` to only accounts that are
enabled to be tracked by mu.
home-manager allows for users to define a list of aliases for a main email address.
Previously, this `mu` module did not understand these aliases.
Now `mu` will understand aliases and allow them to be treated "my-address", which makes them special in the eyes of mu.
This allows for filtering based on threads containing your email addresses and/or their aliases.
#2724
```
``` …
=> mu: allow aliases to be used by mu configuration file

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/services/fusuma.nix, tests/default.nix, tests/modules/services/fusuma/default.nix, tests/modules/services/fusuma/expected-service.service, tests/modules/services/fusuma/expected-settings.yaml, tests/modules/services/fusuma/service.nix, tests/modules/services/fusuma/settings.nix
Fusuma is a tool that supports multitouch gestures with libinput driver on Linux. This commit introduces a nix module for home-manager.
Signed-off-by: iosmanthus <myosmanthustree@gmail.com>
```
```
=> fusuma: introduce a service module for fusuma.

modules/programs/autorandr.nix, tests/modules/programs/autorandr/basic-configuration.nix
xrandr's `--filter` option is useful for enabling integer scaling on displays that don't have support for it at a graphics card level; autorandr doesn't add this option itself to generated profiles, but happily accepts it if the user adds it to the config.
As an alternative to this change, perhaps an `extraConfig` attribute would be suitable; I didn't take that approach because I only needed this one option added.
FIXME(?): seems that `modules/misc/xdg-desktop-entries.nix` made them fail on my machine...?
```
```
=> autorandr: add filter option

modules/misc/xdg.nix, tests/modules/misc/xdg/system-dirs.nix, tests/modules/systemd/session-variables-expected.conf, tests/modules/systemd/session-variables.nix
Make sure those variables are set in systemd user services. This mirrors the situation for `XDG_*_DIRS` variables.
cc @tadfisher https://github.com/nix-community/home-manager/pull/1797
```
```
=> xdg: add `XDG_*_HOME` variables to `systemd.user.sessionVariables`

modules/programs/neovim.nix
Specifically, refactored all places that use cfg.plugins to use a new combined list that includes CoC if it's enabled.
Closes #2386
```
```
=> neovim/coc: fix loading CoC plugin

.github/CODEOWNERS, modules/misc/nix.nix, tests/default.nix, tests/modules/misc/nix/default.nix, tests/modules/misc/nix/empty-settings.nix, tests/modules/misc/nix/example-registry-expected.json, tests/modules/misc/nix/example-registry.nix, tests/modules/misc/nix/example-settings-expected.conf, tests/modules/misc/nix/example-settings.nix
Nix permits user level configurations through ~/.config/nix/nix.conf that allow
customization of system-wide settings and behavior. This is beneficial in chroot
environments and for per-user configurations. System level Nix configurations in the
form of /etc/nix/nix.conf can be specified declaratively via the NixOS nix module but as
of currently no counter part exists in home-manager.
This PR is a port of the RFC42 implementation for the NixOS nix module[1]
to home-manager. Non-applicable options have been excluded and the config generation
backends have been tweaked to the backends offered by home-manager. A notable change
from the NixOS module is a mandatory option to specify the Nix binary corresponding
to the version "nix.conf" should be generated against. This is necessary because …
=> nix: add structural settings

modules/services/window-managers/bspwm/default.nix, modules/services/window-managers/bspwm/options.nix, tests/modules/services/window-managers/bspwm/bspwmrc, tests/modules/services/window-managers/bspwm/configuration.nix
If set to true, desktops configured in `monitors` will be reset every time the config is run.
If set to false, desktops will only be configured the first time the config is run.
This is useful if you want to dynamically add desktops and you don't want them to be destroyed if you re-run `bspwmrc`.
Tested.
```
```
=> bspwm: add alwaysResetDesktops

modules/programs/vscode.nix
Currently home manager does not provide a way to define VSCode [user level tasks](https://code.visualstudio.com/docs/editor/tasks#_user-level-tasks)
```
```
=> vscode: add user tasks

modules/programs/tmux.nix, tests/modules/programs/tmux/disable-confirmation-prompt.conf, tests/modules/programs/tmux/emacs-with-plugins.conf, tests/modules/programs/tmux/prefix.conf, tests/modules/programs/tmux/shortcut-without-prefix.conf, tests/modules/programs/tmux/vi-all-true.conf
This PR adds notes to the keybindings created in the tmux config, making them show up when checking `C-b ?` or `tmux list-keys -N`, fixing #2540. I also adjusted the reference configs in the test cases to expect the notes.
Keys without notes are not displayed when checking `C-b ?` (since tmux 3.1), making them hard to discover for users.
The explanations are mostly taken from/based on the tmux man-page (which is licensed under Zero-Clause BSD).
I ran all tests which don't complain about the `shellDryRun` attribute missing (see #2722) and all tests that pass without the commit also pass with it (only `herbstluftwm-simple-config` fails, both with and without my commit).
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob …
=> tmux: add notes to existing keybindings (#2540)

.github/stale.yml
Makes the stalebot less aggressive by disabling its auto-close functionality.
Closes #2799
Example rendered messages:
* Issues: https://github.com/sumnerevans/home-manager/issues/1#issuecomment-1071914675
* PRs: https://github.com/sumnerevans/home-manager/issues/1#issuecomment-1071915401
```
```
=> stalebot: disable auto-closing of issues and pull requests

modules/xcursor.nix
See discussion at https://github.com/nix-community/home-manager/pull/2481#issuecomment-1072973278.
I'd like this to be merged quickly as I think the warning will only create confusion and cause users to stop using the xcursor module. Then we can decide how to structure cursor options at peace.
```
```
=> xcursor: remove warning and use mkDefault for GTK options

modules/misc/gtk.nix, tests/modules/misc/gtk/gtk2-basic-config-expected.conf, tests/modules/misc/gtk/gtk2-basic-config.nix
The conversion from `concatMapStrings` to `concatStringsSep` introduced in https://github.com/nix-community/home-manager/pull/2481
creates an unintended behavior change where the formatted config does not end in a newline.[1]
This is problematic for manipulation at the Nix level. In particular, this cause a regression in
the generation of gtk2 settings due to concatenated of the formatted config and `gtk2.extraConfig`
without a newline in between.
This commit restores `concatMapStrings` to match the previous behavior and adds a newline to
the final string for the generated gtk2 config. The test case for gtk2-basic-config
was also updated to check behavior at concatenation boundaries.
[1] - https://github.com/nix-community/home-manager/pull/2481#discussion_r830648706
```
{component}: …
```
=> gtk: fix missing newline in formatted config

modules/xcursor.nix
- Escape special character in the cursor name and default cursor file name
in the cursor path for the xsetroot command.
small change to address https://github.com/nix-community/home-manager/issues/2081#issuecomment-859580927
```
```
=> xsession.pointerCursor: escape special characters in the cursor path

tests/modules/services/mpd/basic-configuration.service, tests/modules/services/window-managers/herbstluftwm/autostart
Fix current failing tests for herbstluftwm and mpd.
```
```
=> Fix tests for herbstluftwm and mpd (bash-version)

modules/programs/tmux.nix
Keybindings have wrong order of arguments: the -N flag should go before the binding key. https://www.man7.org/linux/man-pages/man1/tmux.1.html#KEY_BINDINGS
```
```
=> tmux: fix broken vi bindings

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/services/window-managers/i3-sway/i3.nix, modules/services/window-managers/i3-sway/lib/functions.nix, modules/services/window-managers/i3-sway/sway.nix, tests/modules/services/window-managers/i3/i3-bar-focused-colors-expected.conf, tests/modules/services/window-managers/i3/i3-followmouse-expected.conf, tests/modules/services/window-managers/i3/i3-fonts-expected.conf, tests/modules/services/window-managers/i3/i3-keybindings-expected.conf, tests/modules/services/window-managers/i3/i3-null-config.nix, tests/modules/services/window-managers/i3/i3-workspace-default-expected.conf, tests/modules/services/window-managers/i3/i3-workspace-output-expected.conf, tests/modules/services/window-managers/sway/sway-bar-focused-colors.conf, tests/modules/services/window-managers/sway/sway-bindkeys-to-code.conf, tests/modules/services/window-managers/sway/sway-default.conf, tests/modules/services/window-managers/sway/sway-followmouse-expected.conf, tests/modules/services/window-managers/sway/sway-followmouse-legacy-expected.conf, tests/modules/services/window-managers/sway/sway-modules.conf, tests/modules/services/window-managers/sway/sway-null-package.conf, tests/modules/services/window-managers/sway/sway-workspace-default-expected.conf, tests/modules/services/window-managers/sway/sway-workspace-output-expected.conf
Issue #2030 should describe it well :)
Didn't fixed the tests yet, just wanted to ask if there is feedback before about the way2go here? :)
Yes but formats some code parts really bad?
```
```
=> Improve i3.nix to handle options as list like in sway, adjusted functions for less new-lines

modules/programs/irssi.nix, modules/services/picom.nix
These options should permit multiple definitions.
```
```
=> Use `types.lines` for `irssi.extraConfig`  and `picom.extraOptions`

tests/default.nix, tests/modules/misc/gtk/gtk3-basic-settings.nix, tests/modules/services/mpd/basic-configuration.service, tests/modules/services/window-managers/herbstluftwm/autostart
Also updated golden files to match new store path normalization
output.
```
```
=> tests: bump nmt

docs/faq.adoc, modules/misc/dconf.nix
Before enabling dconf in home manager, dconf must be enabled in system config.
Otherwise it will fail like this:
```
↪ home-manager switch                                                                                                                                                                    13:04
Starting Home Manager activation
Activating checkFilesChanged
Activating checkLinkTargets
Activating writeBoundary
Activating installPackages
replacing old 'home-manager-path'
installing 'home-manager-path'
Activating dconfSettings
error: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit dconf.service not found.
```
I hit this issue and I couldn't find this piece of information anywhere else. So thought I'd add here.
```
```
See …
=> Dconf: add note - dconf must be enabled in system config.

flake.nix
This is to prevent errors with `flake check` because for example cygwin can't even build bash
Closes #2829
```
```
=> Only support linux + darwin, not bsd, cygwin, sunos or redox

overlay.nix
Signed-off-by: lucasew <lucas59356@gmail.com>
Renaming of the overlay parameters to pass the `nix flake check` test that for some reason requires that [standarize](https://nixos.wiki/wiki/Flakes) the name of the parameters.
I already [did the same alteration](https://github.com/lucasew/borderless-browser.nix/commits/master/flake.nix) in other repo.
```
```
=> overlay: rename parameters to flake specification

modules/programs/browserpass.nix, tests/modules/programs/browserpass/browserpass.nix
Add support of [Brave browser](https://brave.com/) to browserpass module
```
```
=> browserpass: add brave support

modules/lib/types-dag.nix, tests/lib/types/dag-merge.nix
This makes definitions like `home.activation.foo = mkIf false "bar"` work, where previously they would complain about `home.activation.foo.data` being used but not defined.
The crucial part is that we don't call `convertAllToDags` in `dagOf.merge`, because we need to process `mkIf`/`mkMerge` properties first. So we let `attrEquivalent.merge` do its job normally, but give it a type `dagEntryOf` that does the conversion.
Ideally this shouldn't require so much boilerplate; I'd like to implement something like `types.changeInto dagContentType elemType dagEntryAnywhere` in nixpkgs.
```
``` …
=> types: fix `dagOf` behaviour with `mkIf`

modules/programs/zellij.nix
Zellij uses a different path to hold its configuration on Darwin.
See: https://zellij.dev/documentation/configuration.html
```
```
=> zellij: fix configuration for darwin

nix-darwin/default.nix
Currently activation is run with `sudo -i` this defaults to the user's login
shell. This can lead to problems if the user's shell isn't set properly.
By passing `-s` rather than `-i`, `sudo` runs `activate` in `SHELL` instead.
I'm assuming at this point in the activation `SHELL` contains the path to a
bash in the nix store. This should always be a valid shell to run the
`activate` script with.
From the `sudo` manual it seems like this cannot be fixed if `SHELL`
isn't set at this point or by passing a command to `-s` because that
command is then passed to the user's shell.
I had some trouble turning off `useUserPackages` in the darwin module because I'd set my shell manually using `chsh -s $(which fish)`. This set the shell to `/etc/profiles/per-user/${USER}/bin/fish` and that directory …
=> Run sudo with -s in the darwin module

nix-darwin/default.nix
Backport #807 to release-21.11 as I can't get 21.11 to work on M1.
```
```
=> Backport: nix-darwin: run sudo with -s

nix-darwin/default.nix
Changing from `sudo -i` to `sudo -s` messes up activation when multiple
users are managed. `--set-home` should have similar behavior to `-i` in
that the activation script is run from the user's home directory.
Fixes #2856
My previous fix broke use cases. Hopefully this fixes it again.
```
```
=> nix-darwin: sudo --set-home for multiple user activation

nix-darwin/default.nix
Changing from `sudo -i` to `sudo -s` messes up activation when multiple
users are managed. `--set-home` should have similar behavior to `-i` in
that the activation script is run from the user's home directory.
Fixes #2856
(cherry picked from commit e1fab012e872c129099535b5b535fc2347cfa6f4)
```
```
=> nix-darwin: sudo --set-home for multiple user activation (#2857)

flake.nix
Since Nix 2.7.0, `defaultPackage` is deprecated and instead we should
use `packages.<system>.default`.  This commit adds the new field but
keep the old for backward compatibility.
```
```
=> flake: add `packages.<system>.default`

modules/programs/git.nix
Add the option to use [difftastic](https://github.com/Wilfred/difftastic), a syntax-aware diff tool, with git
```
```
=> git: Add option to use difftastic as diff tool

modules/misc/xdg-user-dirs.nix
Changed the type of the user directory options from `str` to ~`either str path`~(`coercedTo path toString str`) to allow using path values.
The related session variable is defined for the default and the extra user directories now.
Closes #2694
```
```
=> xdg-user-dirs: allow paths and define sessionVariables

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/services/screen-locker.nix, tests/modules/services/screen-locker/no-xautolock.nix
Some screen lockers which will be used with `xss-lock` might require
to set x screensaver timeout with cycle.
Resolves: #2852
```
```
=> screen-locker: Add option to configure x screensaver cycle

modules/programs/gpg.nix
It can happen in some cases that home-manager first runs before gpg creates its homedir, and it creates it with 755 permissions which the user then needs to change by hand.
Do this in the module instead: before linking files, make sure the homedir exists, and if it doesn't, create it with the right permissions.
We might drop the `mkMerge` if https://github.com/nix-community/home-manager/pull/2822 gets merged first. (EDIT: done)
```
```
=> gpg: create homedir with 700 permissions

.github/CODEOWNERS, modules/modules.nix, modules/services/mpd-discord-rpc.nix
This PR adds a configurable service that runs [mpd-discord-rpc](https://github.com/JakeStanger/mpd-discord-rpc).
~~I am waiting for the upstream package to merge this pull request https://github.com/JakeStanger/mpd-discord-rpc/pull/16 so the package can be added to nixpkgs.~~
The module has also been tested to be working fine on my personal system with an overlay for the package mpd-discord-rpc ~~since it is not in nixpkgs yet.~~ ,it is now.
```
```
=> mpd-discord-rpc: init service

modules/systemd.nix, tests/modules/programs/helix/settings-expected.toml
Fix #2846, diff provided by @yu-re-ka.
```
```
=> systemd: fix creation of user service unit files

README.md
=> docs: fix link to rollback instructions

modules/programs/taskwarrior.nix, tests/modules/programs/taskwarrior/taskwarrior.nix
This is an updated duplicate of #2697, where I attempted to fix/add tests too.
1. Make the default `$HOME/.config/taskrc`writeable for users, so as to e.g. allow `task context` commands.
2. Update tests to check for this.
```
```
=> taskwarrior: make .taskrc writable (attempt nr. 2)

modules/programs/starship.nix
The code that is being evaled without the `--print-full-init` flag is this:
```sh
__main() {
local major="${BASH_VERSINFO[0]}"
local minor="${BASH_VERSINFO[1]}"
if ((major > 4)) || { ((major == 4)) && ((minor >= 1)); }; then
source <(/nix/store/...-starship-1.3.0/bin/starship init bash --print-full-init)
else
source /dev/stdin <<<"$(/nix/store/...-starship-1.3.0/bin/starship init bash --print-full-init)"
fi
}
__main
unset -f __main
```
This code checks for bash version >= 4.1 , which has been released in 2009. Since this version  is widely unavailable in nixpkgs, we can skip one program invocation and directly call  `starship init bash --print-full-init`.
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/ …
=> starship: skip one program invocation on each shell init

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/modules.nix, modules/programs/pylint.nix
Adds a module for the Python linter pylint.
```
```
=> pylint: add module

modules/home-environment.nix
The fix is exactly as suggested in #2675, otherwise during cross compiles the incorrect architecture is used.
```
```
=> home-manager: Fix cross-compiles, fixes #2675

modules/services/picom.nix, tests/default.nix, tests/modules/services/picom/default.nix, tests/modules/services/picom/picom-basic-configuration-expected.conf, tests/modules/services/picom/picom-basic-configuration-expected.service, tests/modules/services/picom/picom-basic-configuration.nix
Remove `services.picom.refreshRate`. This option was deprecated since release [v9](https://github.com/yshui/picom/releases/tag/v9), and it is generating the following warn in the log:
```
[ DD/MM/YYYY HH:MM:SS.mmm parse_config_libconfig WARN ] The refresh-rate option has been deprecated. Please remove it from your configuration file. If you encounter any problems without this feature, please feel free to open a bug report
```
To ensure that I didn't break anything, I decided to add a test to the module (since it didn't had before). To make testing easier, I did a small refactoring in the module, that includes adding the file to the `~/.config/picom/picom.conf` path that is the expected one for the application. This change should also make it easier to debug errors in the config (no more …
=> picom: remove deprecated option, add tests

modules/programs/waybar.nix, tests/modules/programs/waybar/systemd-with-graphical-session-target.nix, tests/modules/programs/waybar/systemd-with-graphical-session-target.service
Currently, trying to run `systemctl --user reload waybar.service` fails with:
```
Apr 05 19:31:39 StarBook-MkV systemd[2313]: Reloading Highly customizable Wayland bar for Sway and Wlroots based compositors....
Apr 05 19:31:39 StarBook-MkV systemd[46289]: waybar.service: Failed to locate executable kill: No such file or directory
Apr 05 19:31:39 StarBook-MkV systemd[46289]: waybar.service: Failed at step EXEC spawning kill: No such file or directory
Apr 05 19:31:39 StarBook-MkV systemd[2313]: waybar.service: Control process exited, code=exited, status=203/EXEC
Apr 05 19:31:39 StarBook-MkV systemd[2313]: Reload failed for Highly customizable Wayland bar for Sway and Wlroots based compositors..
```
Fixed this by inserting the full path to the `kill` command from the `busybox` package.
``` …
```
=> waybar: fix command not found when reloading

modules/programs/keychain.nix
Explicitly sets the `SHELL` environment variable, which should force Keychain to use the correct initialization code for the respective shells.
Tested with the integration enabled, and entering the `fish` shell with an incorrect environment variable (`SHELL=/run/current-system/sw/bin/zsh`). Previously gave a warning, which disappeared with the fix.
Fixes #2256
```
```
=> keychain: set SHELL during initialization

modules/programs/neomutt.nix, tests/modules/programs/neomutt/hm-example.com-expected, tests/modules/programs/neomutt/hm-example.com-gpg-expected.conf, tests/modules/programs/neomutt/hm-example.com-msmtp-expected.conf, tests/modules/programs/neomutt/hm-example.com-no-folder-change-expected.conf
=> neomutt/signature: unset if disabled

modules/default.nix
This makes it a lot easier to access the `pkgs` that would be used to
build the home configuration, e.g.
nix build ./dotfiles#homeConfigurations."user@host".pkgs.vim
This is useful as it allows access to a Nixpkgs that has been
instiantiated with config and overlays.
Currently you would need to do:
nix build ./dotfiles#homeConfigurations."user@host".options._module.args.value.pkgs.vim
```
```
=> modules: Export `pkgs` to match NixOS

modules/misc/nix.nix
nix/nix.conf should generate if cfg.extraOptions is not empty.
I've encountered `nix/nix.conf` not generated with the following config:
```
nix.extraOptions = ''
experimental-features = nix-command flakes
'';
```
By checking the config files, this file is only generated when `cfg.settings != {}`. It missed one case that `extraOptions` is outside `settings`.
This PR fixes the logic and generates `nix/nix.conf` correctly.
It doesn't involve any package change so I guess most of the checklists are not applicable?
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) …
=> misc: fix nix.conf generation

modules/misc/xdg-desktop-entries.nix, tests/modules/misc/xdg/desktop-entries.nix, tests/modules/misc/xdg/desktop-full-expected.desktop
Adds the `actions` option to fix #2777.
The option `fileValidation` is removed because validation cannot be disabled anymore.
```
```
=> xdg-desktop-entries: add 'actions' option, deprecate fileValidation

flake.nix, modules/default.nix
Add a `lib` argument to `homeManagerConfiguration` to specify the lib to use instead of the one from `pkgs`.
=> Add lib argument to homeManagerConfiguration

nix-darwin/default.nix, nixos/default.nix
`modulesPath` is usually used with antiquotation (`"${modulesPath}/some-module.nix"`). Antiquoted paths are copied to the Nix store and one must do `"${toString modulesPath}/some-module.nix"` to avoid the copying. Ideally `modulesPath` should be a string to avoid this. Note that `modulesPath` is already defined as a string in `<home-manager>/modules/default.nix` and `<nixpkgs>/nixos/lib/eval-config.nix`.
```
```
=> nix-darwin,nixos: convert `modulesPath` to string

modules/targets/generic-linux.nix
This commit appends system-wide icon and pixmap directory and the icon
directory in the home-manager profile to the XCURSOR_PATH session variable
for the generic linux target. This is necessary because the default prefix
for libXcursor resolves to the Nix store which excludes the aforementioned
directories from being searched for cursor themes. [1]
[1] - https://github.com/nix-community/home-manager/pull/2891#issuecomment-1101064521.
cc: @EHfive
```
```
=> targets.genericLinux: include additional directories in XCURSOR_PATH

modules/services/window-managers/i3-sway/sway.nix
Constrain the pgrep command to only return results for the current user.
Additionally, quote the socket variables to prevent splitting.
Previously, if multiple users on a system were running `sway`, the
`pgrep` used in finding `swaySocket` would return multiple results. As a
result, reloads of sway would fail.
Fixes #2912.
- I was only able to run the Sway tests because my local build is blocked by #2693 as I don't currently use `unstable`:
```sway-bar-focused-colors: OK
sway-bindkeys-to-code: OK
sway-default: OK
sway-followmouse: OK
sway-followmouse-legacy: OK
sway-modules: OK
sway-no-xwayland: OK
sway-null-config: OK
sway-null-package: OK
sway-post-2003: OK
sway-workspace-default: OK
sway-workspace-output: OK
swaynag-empty-settings: OK
swaynag-example-settings: OK
```
- Not sure how to …
=> i3-sway: only return current user's socket

modules/services/xscreensaver.nix
Added to systemd-service:
```
Environment = "PATH=${makeBinPath [pkgs.xscreensaver]}";
```
Otherwise journal will spam:
```
xscreensaver[468297]: sh: line 1: xscreensaver-command: command not found
xscreensaver-systemd: 12:29:22: exec: "xscreensaver-command -quiet -deactivate" exited with status 127
```
Which might be trying to deactivate it when watching video's, which I
have had issues with.
```
```
=> xscreensaver: have xscreensaver-command in PATH

modules/services/gpg-agent.nix
In esoteric setups, automatically setting GPG_TTY to current tty is not
desired on every shell startup. This change adds configuration options
to allow user to disable that if desired.
Appears an unrelated test case is failing even before my change:
```
❯ nix-shell --pure tests -A run.all
error: attribute 'shellDryRun' missing
at /home/user/projects/home-manager/modules/programs/bash.nix:12:9:
11|     checkPhase = ''
12|       ${pkgs.stdenv.shellDryRun} "$target"
|         ^
13|     '';
(use '--show-trace' to show detailed location information)
```
However, all the gpg-agent related tests do pass:
```
❯ for t in gpg-agent-default-homedir gpg-agent-override-homedir; do nix-shell --pure tests -A run.$t; done
❯ for t in gpg-agent-default-homedir gpg-agent-override-homedir; do nix-shell …
```
=> gpg-agent: shell integration is configurable

.github/CODEOWNERS, modules/modules.nix, modules/programs/tealdeer.nix
Add https://github.com/dbrgn/tealdeer
```
```
=> tealdeer: add module

modules/services/gpg-agent.nix
In esoteric setups, automatically setting GPG_TTY to current tty is not
desired on every shell startup. This change adds configuration options
to allow user to disable that if desired.
(cherry picked from commit df6010551daa826217939641ab805053f0890239)
Backports #2927
N/A
```
```
N/A
=> gpg-agent: make shell integrations optional (#2927)

modules/programs/fish.nix
Was browsing issues and noticed fixing #2910 looked straightforward.
I checked that Python 3 is now used in the script that generates completions, and sampled what was generated to see if there were any differences and didn't find any.
```
```
=> fish: generate completions using python 3

modules/misc/specialization.nix, modules/modules.nix, tests/default.nix, tests/modules/misc/specialization/default.nix, tests/modules/misc/specialization/specialization.nix
Adds support for configuration specialization similar to the same feature in NixOS.
```
```
=> specialization: basic configuration specialization

modules/services/swayidle.nix
The `extraArgs` were passed to `swayidle` at the end of the command, while `swayidle` expects them **before** the `events` and `timeouts`, causing it to exit with an error. This PR fixes the order of the arguments.
```
```
=> swayidle: Fix ordering of arguments

modules/config/home-cursor.nix
=> home-cursor: fix x11 cursor path using invalid option

modules/services/window-managers/i3-sway/sway.nix
On some machines, `pkgs.sway` is not usable and the `wayland.windowManager.sway.package` config can be used to substitute a working version. However `pkgs.sway` is still used for the `onChange` script, so the user may end up with two copies of sway installed or a broken build if `pkgs.sway` doesn't work.
Now if the `package` option is overriden, the `onChange` script will call `swaymsg` without pulling in `pkgs.sway`.
*I attempted this and was given an error "attribute 'shellDryRun' missing" in modules/programs/bash.nix*
```
```
=> sway: Make onChange script use cfg.package if set

modules/misc/gtk.nix
Change the example value of `gtk.theme.package` from `pkgs.gnome.gnome_themes_standard`, which was an alias that was removed on 2022-01-13, to `pkgs.gnome-themes-extra`, which references the actual package.
Change the example value of `gtk.icon.package` from `pkgs.adwaita-icon-theme` to
`pkgs.gnome.adwaita-icon-theme`, as this package is in the `gnome` package set.
```
```
=> gtk: Update example strings for gtk.theme.package

modules/programs/offlineimap.nix
Remove the dependency on `python2` and instead use the `python` version packaged with `oflineimap`.
```
```
=> offlineimap: remove dependency on python2 (#2909)

modules/programs/pywal.nix
pywal allows to change your theme for much software:
https://github.com/dylanaraps/pywal/wiki/Customization#table-of-contents
home-manager is the perfect tool to leverage since a single setting
could enable wal-compatible theming for all this software.
In this PR, I've just enabled zsh, kitty and i3 but I hope follow up PRs will
enable more software.
At some point we may even need a blacklist.
Once enabled, run:
wal --theme random
to change your colorschemes.
edit: for neovim support we would need  https://github.com/dylanaraps/wal.vim/pull/26
```
``` …
=> programs.pywal: init

modules/services/mako.nix
Add a `package` option to the `mako` module.
```
```
=> mako: add package option

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/services/mopidy.nix, tests/default.nix, tests/modules/services/mopidy/basic-configuration.conf, tests/modules/services/mopidy/basic-configuration.nix, tests/modules/services/mopidy/default.nix
Hey there! I've made this service initially [for myself](https://github.com/foo-dogsquared/nixos-config/blob/8608009146f864134f4bf5b2d86155b9a0cc264e/modules/home-manager/services/mopidy.nix) but I thought this would be a good addition for home-manager.
This is adapted from NixOS module with some changes to make it more suited for home-manager. I know mpd service is already available but I thought I would be nice especially that mopidy can be more powerful and extensible as a music server for the desktop.
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for …
=> Add Mopidy service

modules/programs/htop.nix, tests/modules/programs/htop/header_layout.nix, tests/modules/programs/htop/settings-without-fields.nix
`M_SHARE` is not a valid column on Darwin. It seems that previously htop ignored unknown columns, but the current version does not display all subsequent columns:
```
```
=> htop: fix darwin defaults

modules/programs/neovim.nix
Adds a `package` option for the CoC.
Allows users to override the coc package so that things like #2966 can be fixed.
CC: @t4ccer 
```
```
=> neovim/coc: add package option

modules/programs/emacs.nix, tests/modules/programs/emacs/extra-config.nix
Fixes https://github.com/nix-community/home-manager/pull/1758#issuecomment-1113706592.
```
```
=> emacs: allow cfg.extraConfig to require packages in cfg.extraPackages

modules/programs/himalaya.nix, tests/modules/programs/himalaya/himalaya-expected.toml
The syntax for specifying the location of mailboxes in himalaya has changed,
and the old method doesn't work anymore.
This commit fixes the himalaya module to support the new syntax.
More about the syntax can be read [here](https://github.com/soywod/himalaya/wiki/Configuration:config-file#account-config)
```
```
=> himalaya: fix account.folders to new config syntax

README.md
Making the documentation links stand out more - previously it was easy to miss them, because they were only single words. Also adding a Usage section to highlight them even more - I can't begin to tell you how many times I've googled "home-manager configuration" or ended up on the URL https://rycee.gitlab.io/home-manager/options.html instead of https://nix-community.github.io/home-manager/options.html .
```
```
=> doc: make documentation links more visible

modules/services/getmail.nix
The `getmail` package will soon be removed from nixpkgs. The
`nixos-unstable` channel already has it removed and using the service
will result in:
error: getmail has been removed from nixpkgs, migrate to getmail6
Upgrade to the getmail6 package which is already available and backwards
compatible.
=> getmail: Use newer getmail6 over getmail package

modules/programs/htop.nix
These new fields were added in htop 3.0.3 (PERCENT_NORM_CPU) and 3.1.0 (ELAPSED).
```
```
=> htop: add missing fields

.gitignore, default.nix, docs/default.nix, flake.lock, flake.nix, format, home-manager/default.nix, integration-common.nix, modules/misc/xdg-desktop-entries.nix, nix-darwin/default.nix, nixos/default.nix, tests/default.nix
Lays the groundwork for https://github.com/NixOS/nixos-search/issues/323 by making
```
nix run nixos-search#flake-info -- flake github:nix-community/home-manager
```
succeed. Note that this PR does **NOT** solve the [problem](https://github.com/nix-community/home-manager/issues/2297#issuecomment-1079698898) of how to expose Home Manager modules/options in the flake, it only ensures that we can index packages and NixOS options.
Best reviewed one commit at a time.
This PR partly supersedes https://github.com/nix-community/home-manager/pull/1934, although it does not add an auto-update workflow.
Tested the NixOS module and the manual. nix-darwin testers welcome.
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/d …
=> Prepare inclusion in nixos-search

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/modules.nix, modules/programs/swaylock.nix, tests/default.nix, tests/modules/programs/swaylock/config, tests/modules/programs/swaylock/default.nix, tests/modules/programs/swaylock/disabled.nix, tests/modules/programs/swaylock/settings.nix
This adds a module to configure [swaylock](https://github.com/swaywm/swaylock) (a screen locker for Wayland). All swaylock options must be specified through `programs.swaylock.settings` and the user must give them appropriate types (because there are no Home Manager options for specific swaylock options). This is done for forward compatibility (but could be changed if necessary). Unless `programs.swaylock.settings` is an empty set, the swaylock configuration file is automatically added to the user's home directory (this should be fine because the user can forcefully disable it by setting `programs.swaylock.settings` to `lib.mkForce { }`).
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc …
=> swaylock: Add module

modules/programs/neovim.nix
Saw some examples rendered wrong in the `neovim` docs. Easy fix.
```
```
=> neovim: add missing literalExpression in module docs

nixos/default.nix
Fixes https://github.com/nix-community/home-manager/commit/cd3dd2188c19416bc70d9703f84e07a0646af5bf#r75997641. 
```
```
=> nixos: fix fontconfig mkDefault call

modules/modules.nix, modules/programs/pywal.nix
module was never imported and thus useless. This adds a neovim plugin too.
```
```
=> pywal: fixed i3 config

docs/faq.adoc, docs/installation.adoc
Channels should be added for the normal user, not for root, because the home-manager configuration is not supposed to be evaluated as root.
Fixes https://github.com/nix-community/home-manager/issues/2985
=> docs: use `$` prompts for nix-channel commands

modules/services/emacs.nix, tests/modules/services/emacs/default.nix, tests/modules/services/emacs/emacs-socket-and-startWithUserSession.nix
Add services.emacs.startWithUserSession boolean to indicate that Emacs
must be started with the systemd user session. This is true by default
unless socket activation is also true.
In the past, the user had to choose between socket activation (to get
the Emacs service started when the user uses emacsclient) and
immediate start with the user session. When choosing immediate start
over socket activation and if the Emacs service is stopped at some
point, using emacsclient would start a new Emacs daemon but the
service would still be turned off. This situation would prevent
`home-manager switch` from completing successfully because it wouldn't
be able to start the Emacs service as Emacs is already running.
This new setting makes it possible to have both socket activation and
immediate start …
=> services/emacs: Add option to make service start with the session

docs/installation.adoc
See https://github.com/nix-community/home-manager/pull/3025#issuecomment-1159565524, sorry about that.
I don't understand how nix-darwin works so I'm not sure how the channels should be added there.
=> docs: revert to `#` prompt on NixOS

docs/release-notes/rl-2211.adoc, modules/misc/version.nix, tests/default.nix
The user should always explicitly set the state version they wish to use. Indeed, the configuration generated by the Home Manager install script has set this option for a long time. This removal should therefore not affect many users.
Not backwards compatible, but easy to restore a working configuration by adding `home.stateVersion = "18.09";`.
```
```
=> version: remove default value

modules/programs/mangohud.nix, modules/programs/tiny.nix, modules/services/fnott.nix, modules/services/mpd-discord-rpc.nix, tests/modules/programs/i3status-rust/with-extra-settings.nix
This patch removes the trailing white spaces from the files with the help of VSCode regex search and replace (pattern `[ \t]+$`).
Reference files and strings that would probably affect the test results are manually excluded.
We may want to modify the ./format file to prevent such problem, but I'm not sure how to do it properly.
```
```
=> treewide: remove trailing white spaces and tabs (test cases excluded)

modules/services/mopidy.nix
Follow-up to #2656:
I use `extraConfigFiles` to avoid storing secrets in the Nix store with sops-nix, and this config option (or a functionally similar one that allows importing files at runtime) is required for that to work. See code at https://github.com/lilyinstarlight/foosteros/blob/08fb35ccff35af18d6436149002665ca703858ba/hosts/bina/configuration.nix#L551-L553 in which I've been using `extraConfigFiles` for an example
cc: @foo-dogsquared
```
```
=> mopidy: add support for extraConfigFiles

modules/services/dunst.nix
Dunst has deprecated the `geometry` setting and introduced some other settings replacing `geometry`. The documentation of Home Manager is still using the old `geometry` setting.
This small PR fixes the example of `services.dunst.settings`.
=> dunst: fix settings example

.github/CODEOWNERS, modules/accounts/email.nix, modules/misc/news.nix, modules/modules.nix, modules/programs/mujmap.nix, tests/default.nix, tests/modules/programs/mujmap/default.nix, tests/modules/programs/mujmap/mujmap-defaults-expected.toml, tests/modules/programs/mujmap/mujmap-defaults.nix, tests/modules/programs/mujmap/mujmap-fqdn-and-session-url-specified.nix
mujmap is a tool which synchronizes mail between a mail server and
notmuch via JMAP. It's very similar to lieer, so I heavily based the
implementation of the notmuch module on lieer's. I did not include an
equivalent to lieer's periodic synchronization service, however, because
I plan to soon introduce a daemon mode to mujmap.
https://github.com/elizagamedev/mujmap
This isn't quite ready for merge yet, as I'm still waiting on
NixOS/nixpkgs#172648. However, this is my first module contribution to
home-manager, and I thought it was worth it to receive early feedback.
```
``` …
=> mujmap: add module

flake.lock
=> flake.lock: use SRI hash for nmd

modules/programs/neovim.nix
Coc needs nodejs. This changes the enabling logic to use 'boolean or' instead of an 'attr or default' expression.
Currently, nodejs is enabled by a 'select attrpath or default' expression:
> withNodeJs = cfg.withNodeJs or cfg.coc.enable;
However, the option `neovim.withNodeJs` defaults to false and will exist, which means if you only set `neovim.coc.enable = true;` then node will be missing.
I don't know how to test for this from the test suite, but am willing to try if someone can suggest how to proceed.
CC @sumnerevans Looks like a very minor oversight from nix-community/home-manager#2801
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and …
=> neovim/coc: fix `withNodeJs` value when enabling coc

modules/programs/mcfly.nix
Per the [docs], MCFLY_FUZZY is no longer a boolean, taking now a
positive integer that controls the fuzziness factor.
[docs]: https://github.com/cantino/mcfly#fuzzy-searching
Thanks for writing and maintaining home-manager 🎉 !
<details>
<summary>PR checklist</summary>  
</details>
=> mcfly: add fuzzy search factor option

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/misc/news.nix, modules/modules.nix, modules/programs/pistol.nix, tests/default.nix, tests/modules/programs/pistol/config.nix, tests/modules/programs/pistol/default.nix
Adds a module for the [pistol file previewer](https://github.com/doronbehar/pistol). Pistol's configuration syntax is very simple and translates well into an attrset from mime type or path to command string.
```
```
=> pistol: add module

docs/nix-flakes.adoc
The nix-darwin documentation uses `darwin` not `nix-darwin` to refer to its own flake, and so this is now consistent (and correct) and uses `darwin`.
There are no code changes.
```
```
=> Documentation: Fix typo in nix-darwin flake example

docs/default.nix
Currently we're maintaining a "mock" module made of sink options, which requires updating whenever the definitions in the nixos/nix-darwin modules change.
Instead, set `_module.check` to false so that definitions in those modules are simply ignored.
This is [what we do](https://github.com/NixOS/nixos-search/blob/75e8457105ee6a9d3f60c71add59661bb809f236/flake-info/src/commands/flake_info.nix#L53) in nixos-search.
This could probably also be done in nmd by default.
```
```
=> docs: disable `_module.check` for nixos/nix-darwin modules

docs/nix-flakes.adoc, docs/release-notes/rl-2211.adoc, flake.nix
Updates the docs after https://github.com/nix-community/home-manager/pull/3028, removes the now useless `system` argument, and removes the default `stateVersion` value because it's now quite old and the user should set it explicitly anyway.
Fixes https://github.com/nix-community/home-manager/pull/2647
=> homeManagerConfiguration: remove default stateVersion, update docs

modules/services/mpd-discord-rpc.nix
The service now restarts if it crashes which usually happens when it starts before `mpd` initializes.
~~[ ] Code tested through `nix-shell --pure tests -A run.all.`~~ No tests for my change.
~~[ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).~~
```
```
=> mpd-discord-rpc: restart on failure

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/sctd.nix
This adds a module for enabling the `sctd` daemon, as well as setting the preferred base temperature.
I'm not quite sure if a test should be added given the functionality of this module is basic enough, the only real thing it adds is a systemd user service.
```
```
=> sctd: initial module

flake.lock, nixos/common.nix
Depends on https://github.com/NixOS/nixpkgs/pull/173621 which just landed, let's wait a couple weeks before merging.
```
```
=> integration-common: set hmModule's description directly

default.nix, docs/default.nix, flake.lock, flake.nix, tests/default.nix
This simplifies the code a bit and avoids using experimental Flake functionality. If Flakes become stable before NixOS 22.11 then we can consider having nmd and nmt as Flake inputs. Maybe could then also avoid the need for flake-compat.
Note, instead of `pkgs.fetchFromGitLab` this commit uses the builtin function `fetchTarball` to avoid the `pkgs` dependency.
```
```
=> Unflake nmt and nmd

modules/services/window-managers/bspwm/options.nix, tests/modules/services/window-managers/bspwm/bspwmrc, tests/modules/services/window-managers/bspwm/configuration.nix
Also add a `freeformType` so that we don't have to do this in the future.
```
```
=> bspwm: add missing rule setting `rectangle`

modules/programs/nushell.nix
Allows null/non-defined `configFile` and `envFile`
fixes #3050
```
```
=> nushell: fix non-nullable configFile and envFile, fixes #3050

modules/services/window-managers/i3-sway/sway.nix, tests/modules/services/window-managers/sway/sway-bar-focused-colors.conf, tests/modules/services/window-managers/sway/sway-bar-focused-colors.nix, tests/modules/services/window-managers/sway/sway-bindkeys-to-code.conf, tests/modules/services/window-managers/sway/sway-bindkeys-to-code.nix, tests/modules/services/window-managers/sway/sway-default.conf, tests/modules/services/window-managers/sway/sway-default.nix, tests/modules/services/window-managers/sway/sway-followmouse-expected.conf, tests/modules/services/window-managers/sway/sway-followmouse-legacy-expected.conf, tests/modules/services/window-managers/sway/sway-followmouse-legacy.nix, tests/modules/services/window-managers/sway/sway-followmouse.nix, tests/modules/services/window-managers/sway/sway-modules.conf, tests/modules/services/window-managers/sway/sway-modules.nix, tests/modules/services/window-managers/sway/sway-no-xwayland.nix, tests/modules/services/window-managers/sway/sway-null-config.nix, tests/modules/services/window-managers/sway/sway-null-package.conf, tests/modules/services/window-managers/sway/sway-null-package.nix, tests/modules/services/window-managers/sway/sway-post-2003.nix, tests/modules/services/window-managers/sway/sway-workspace-default-expected.conf, tests/modules/services/window-managers/sway/sway-workspace-default.nix, tests/modules/services/window-managers/sway/sway-workspace-output-expected.conf, tests/modules/services/window-managers/sway/sway-workspace-output.nix
Supersede and closes #2385 
Fix #2806 and #2028
- Importing all environment variables is considered deprecated for
`systemdctl import-environment`. The list of variables are picked
from:
https://github.com/swaywm/sway/wiki/Systemd-integration#managing-user-applications-with-systemd
The `XDG_CURRENT_DESKTOP` is said to be required for portals, see:
https://github.com/nix-community/home-manager/pull/2385#issuecomment-1026454162
- DBus activation environment should also be updated. Otherwise, DBus
activated programs, without a coresponding systemd service, cannot get a
correct environment and would fail, eg. `mako`.
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for …
=> sway: import dbus env vars and explicitly specify them 

modules/programs/zsh.nix
`zsh-syntax-highlighting.zsh` must be sourced at the end of the `.zshrc` file, otherwise widgets created after are not properly highlighted (e.g. from oh-my-zsh...): https://github.com/zsh-users/zsh-syntax-highlighting#faq
~I moved `zsh-autosuggestions` with it for style only, I think it is good to keep these 2 plugins grouped, and it should not cause any issue.~
```
```
=> zsh: source zsh-syntax-highlighting at the end of .zshrc

tests/default.nix
This patch fixes the impurity caused by the last element of the above `modules` (i.e. `pkgsModule`) setting `pkgsPath` with `mkDefault` to `<nixpkgs>` if `config.home.stateVersion` is before 20.09.
Considering that this piece of configuration is used for testing, it should be fine to specify pkgsPath directly.
If applied, it will allow the flake-based test  running (provided by by #3024) work without the `--impure` flag.
```
```
=> tests: fix impurity of _module.args.pkgsPath

modules/lib/types-dag.nix, tests/lib/types/dag-merge-result.txt, tests/lib/types/dag-merge.nix
Fixes https://github.com/nix-community/home-manager/issues/2944
Removes the `uniq` constraint on `after` and `before` so that we can merge multiple definitions for the same DAG entry:
```nix
{
dag = mkMerge [
{
foo = lib.hm.dag.entryBefore [ "bar" ] {
};
}
{
foo = lib.hm.dag.entryBefore [ "qux" ] {
};
}
{
foo = {
};
}
];
}
```
In this example `foo` will come before `bar` and `qux`.
It might also be worth considering enabling things like
```nix
{
foo.after = "qux";
}
```
which currently would be treated as a definition of the underlying data (so the change wouldn't be backwards compatible), though that can be done with the current PR as
```nix
{
foo = lib.hm.dag.entryAfter "qux" (mkMerge []);
}
```
```
```
See …
=> lib/types: make DAG entries mergeable

.github/CODEOWNERS
We've tried to keep the CODEOWNERS file alphabetized, but it's drifted some with people accidentally adding to the bottom. This fixes all of those issues.
One question that I have is whether the few at the top were intentionally clustered (they are mainly @rycee). If they need to be clustered together, maybe it's worth adding "sections" to the file and noting the exceptions. Alternatively, we just go with what I have right now which aggressively alphabetizes everything.
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/ …
=> codeowners: cleanup alphabetization

docs/installation.adoc, docs/nix-flakes.adoc
With #2840, Nix 2.4 is supported.
This resolves #3061.
```
```
=> docs: remove bit about Nix 2.4 not being supported

modules/programs/keychain.nix
bash apparently handles command substitution slightly differently than
fish and zsh. in bash:
```console
$ export FOO=x
$ FOO=y echo $(sh -c 'echo $FOO')
x
```
whereas in zsh:
```console
$ export FOO=x
$ FOO=y echo $(sh -c 'echo $FOO')
y
```
so we have to assign $SHELL within the substitution in bash.
see #2256 and #2880.
```
```
=> keychain: set SHELL correctly in bash

modules/programs/mpv.nix
Strings as scripts don't currently work, and probably haven't worked since b567d273.
See #983.
```
```
=> mpv: prohibit string values in scripts

modules/programs/firefox.nix
This uses the `escapeXML` function provided by Nixpkgs instead of redefining it in the Firefox module.
```
```
=> firefox: Reuse `escapeXML` from Nixpkgs

.github/ISSUE_TEMPLATE/issue.yaml
We seem to be getting a [lot](https://github.com/nix-community/home-manager/issues/3011) [of](https://github.com/nix-community/home-manager/issues/3057) [bug](https://github.com/nix-community/home-manager/issues/3101) [reports](https://github.com/nix-community/home-manager/issues/3102) coming from people using `home-manager/master` with `nixpkgs/nixos-22.05` or similar scenarios. (currently exacerbated by https://github.com/nix-community/home-manager/pull/3013)
Let's add a checkbox in the issue template to warn people about that. Wording suggestions welcome.
[Preview](https://github.com/ncfavier/home-manager/blob/issue-template-branch/.github/ISSUE_TEMPLATE/issue.yaml)
=> ISSUE_TEMPLATE/issue.yaml: ensure using the right branch of home-manager

modules/programs/firefox.nix
This uses `coercedTo` to make a type for the `programs.firefox.profiles.<name>.bookmarks` option that automatically converts its value to a list. This simplifies the checks on the option value in the rest of the module. A comparison that tests whether any bookmarks are specified is also modified to compare the option value against `[ ]` instead of `{ }`.
```
```
=> firefox: Use `lib.types.coercedTo` to normalise the bookmarks declared

modules/programs/firefox.nix, tests/modules/programs/firefox/profile-settings-expected-bookmarks.html, tests/modules/programs/firefox/profile-settings.nix
With this change, the `toolbar` dir will be shown in the browser toolbar.
```
```
=> firefox: make it possible that bookmarks are shown on toolbar

flake.nix
In https://github.com/nix-community/home-manager/pull/2859, the library became self-referential, so we need to use the stdlib-extended helper instead of importing directly.
```
```
=> flake.nix: fix self referential lib output

modules/misc/news.nix, modules/targets/darwin/default.nix, modules/targets/darwin/user-defaults/default.nix, modules/targets/darwin/user-defaults/opts-allhosts.nix, modules/targets/darwin/user-defaults/opts-currenthost.nix, tests/modules/targets-darwin/default.nix, tests/modules/targets-darwin/user-defaults.nix
This adds a new option, `targets.darwin.currentHostDefaults`, which exposes additional macOS preferences. It is similar to `targets.darwin.defaults`, but it contains options that are only applicable for the current host instead of all hosts the logged in user has accounts on.
Closes #2615.
```
```
=> darwin: add support for 'defaults -currentHost' options

modules/programs/fish.nix
This patch follows a similar patch[1] in nixpkgs. With this patch,
fish can complete manpages for programs installed through
home-manager, e.g. using home.packages.
[1]: https://github.com/NixOS/nixpkgs/pull/91794
```
```
=> fish: enable manpage completion

modules/misc/xdg-user-dirs.nix
In the scenario where some XDG user directory is a symlink defined by `home.file`, we want the symlink to be created before we try to `mkdir -p` that directory, as it will then silently succeed.
On the other hand, if we create the directory first, creating the symlink will fail (in a surprising way, see https://github.com/nix-community/home-manager/pull/3018).
We lose nothing by doing this as `linkGeneration` creates the directories it needs.
We can also fix the `mkIf` weirdness since https://github.com/nix-community/home-manager/pull/2822.
cc @thiagokokada 
```
``` …
=> xdg-user-dirs: `createXdgUserDirectories` after `linkGeneration`

modules/misc/xdg-mime-apps.nix
The XDG Desktop Entry spec mentions that multiple values per key may be optionally terminated by a semicolon. An example for this is the Firefox desktop file, which has no trailing semicolon. This breaks the sed regex used in `mimeAssociations`.
Fix the regex by matching the end of string, optionally preceded by a semicolon, or any other semicolon. This makes it work with both semicolon-terminated and non-semicolon-terminated desktop files.
Before:
```
❯ export name=firefox.desktop && sed -n "/^MimeType=/ { s/.*=//; s/;/;$name\n/g; p; }" /nix/store/rzmiq36p92i1arjfjxkvahmqdcka02gy-firefox-101.0.1/share/applications/firefox.desktop
text/html;firefox.desktop
text/xml;firefox.desktop
application/xhtml+xml;firefox.desktop
application/vnd.mozilla.xul+xml;firefox.desktop …
```
=> xdg-mime-apps: fix regex in `mimeAssociations`

docs/contributing.adoc
- docs/contributing.adoc: fix name of file generated by `$ nix-build -A docs.manPages`
- docs/contributing.adoc#Commits: add exception to seven rules
- why: most commits have not followed "Capitalize the subject line". Not even the example commit message (closely below this change) follows this rule.
```
```
=> docs/contributing.adoc: fix generated manpages filename, fix seven rules guideline

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/services/recoll.nix, tests/default.nix, tests/modules/services/recoll/basic-configuration.conf, tests/modules/services/recoll/basic-configuration.nix, tests/modules/services/recoll/config-format-order.conf, tests/modules/services/recoll/config-format-order.nix, tests/modules/services/recoll/default.nix
Added [Recoll](https://www.lesbonscomptes.com/recoll/), a file index service for the desktop. It is oriented to be used by a normal user so it is a good addition to home-manager.
I use this module myself for two weeks but I don't feel confident for the custom settings format I created for this module so feel free to roast it. :)
Recoll
```
```
=> recoll: add module

modules/programs/librewolf.nix
A 'r' were missing to LibreWolf.
A 'r' were missing to LibreWolf. I correct it.
```
```
=> LibreWolf: Fix typo

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/hyfetch.nix, tests/default.nix, tests/modules/programs/hyfetch/default.nix, tests/modules/programs/hyfetch/hyfetch.json, tests/modules/programs/hyfetch/settings.nix
Adds a simple module for [hyfetch](https://github.com/hykilpikonna/hyfetch), which is in nixpkgs now (NixOS/nixpkgs#182944)
I've not actually contributed a module before and this one is pretty minimal, but I think I covered everything I saw in the contribution docs (except a news item which I'm happy to add if desired). Let me know if I'm missing something though!
```
```
=> hyfetch: add module

modules/programs/hyfetch.nix, tests/modules/programs/hyfetch/default.nix, tests/modules/programs/hyfetch/empty-settings.nix
Follow-up to #3123
cc: @rycee @luxus
```
```
=> hyfetch: prevent writing config with default/empty settings

modules/programs/tint2.nix
Currently it fails with `error: attribute 'package' missing`.
Not needed. It's a trivial change
```
```
=> Use correct package reference in tint2 module

modules/services/polybar.nix, tests/modules/services/polybar/basic-configuration.nix
The old name is deprecated and causes a warning to be logged.
```
```
=> polybar: use add `.ini` suffix to configuration file

modules/programs/bash.nix, tests/modules/programs/atuin/bash.nix, tests/modules/programs/bash/completion.nix, tests/modules/programs/bash/default.nix, tests/modules/programs/bash/logout.nix, tests/modules/programs/bash/session-variables.nix
Add option to enable Bash completion. It is true by default as it doesn't interfere with the NixOS completion option (the system one is used when both are enabled).
```
```
=> bash: support bash completion

modules/services/redshift-gammastep/lib/options.nix
When configured with geoclue2 as a provider, gammastep should wait for the agent
to come up, otherwise it cannot determine your location and produces an annoying
error message.
```
```
=> gammastep: wait on geoclue-agent when configured

modules/programs/gh.nix, tests/modules/programs/gh/default.nix, tests/modules/programs/gh/extensions.nix, tests/stubs.nix
Allows to configure [gh extensions](https://cli.github.com/manual/gh_extension). Naturally, the imperative commands such as `gh extension install` and `gh extension remove` then stop working as expected.
```
```
=> gh: add `extensions` option

modules/programs/zathura.nix
added 'mappings' option for zathura.
```
```
=> programs.zathura: added 'mappings' option

.github/workflows/update-flake.yml
This PR implements suggestions from #1913, adding a flake.lock file so we can `nix run github:nix-community/home-manager` without any hiccups. The nixpkgs input is currently set to track `nixos-unstable`. If you want to test this out, you can run `nix run github:nix-community/home-manager/pull/1934/head`, which should give you the help text.
To keep this file up to date, the PR also adds a GitHub workflow that
- Runs every Sunday and Wednesday at 03:51 (I just picked a random time)
- Runs `nix flake update --commit-lock-file`, committing as a nonexistent user called `flakebot`
- Pushes this commit ~~directly to master~~ to a new branch called `flake-update` with a custom token `FLAKEBOT_TOKEN` (this needs to be added to the repo)
- Opens a PR (or updates an existing PR) to merge this …
=> Add flake.lock & workflow to update it

modules/services/udiskie.nix, tests/default.nix, tests/modules/services/udiskie/basic.nix, tests/modules/services/udiskie/basic.yml, tests/modules/services/udiskie/default.nix, tests/modules/services/udiskie/no-tray.nix, tests/modules/services/udiskie/no-tray.yml
This PR removes the dependecy on `tray.target` when configuring udiskie to not use the system tray (motivated by me having `services.udiskie.tray = "never"` in my hm config but also no `tray.target` in my system, leading to errors even though `tray.target` is unnecessary)
I additionally added tests for the old and new behaviors for udiskie configuration (and made a drive-by typo fix). Quick question though: Do I need to add the `tests/modules/services/udiskie` directory to `.github/CODEOWNERS` and if so, should I add myself rather than the module maintainer or both of us or something else?
Edit: The test failure on Ubuntu in GHA seems unrelated to this PR and caused by neovim changes in nixpkgs. It looks like #3168 will fix that test, though
```
{long …
```
=> udiskie: avoid dependency on tray.target when tray is disabled

.github/CODEOWNERS, modules/lib/maintainers.nix, modules/services/xidlehook.nix
Add detect sleep configuration option. Allows to execute the specified commands with more accurate timings if the system wakes from a sleep state.
```
```
=> service.xidlehook: add detect-sleep option

modules/services/window-managers/i3-sway/lib/options.nix, modules/services/window-managers/i3-sway/sway.nix
Allow setting "container" and "output" as options for [`wayland.windowManager.sway.config.focus.mouseWarping`](https://nix-community.github.io/home-manager/options.html#opt-wayland.windowManager.sway.config.focus.mouseWarping).
Fixes #2956
(Yes, `true` and `false` are still accepted as value)
(Kinda --  I've actually put this in my system and tested `true` and `container`)
```
```
=> i3-sway: allow "container" and "output" in focus.mouseWarping

modules/accounts/email.nix
=> email: add yandex and outlook.office365 email flavor

modules/config/home-cursor.nix, modules/home-environment.nix, modules/lib/file-type.nix, modules/programs/firefox.nix, modules/programs/go.nix, modules/programs/zsh.nix, modules/services/window-managers/i3-sway/lib/options.nix
Replace unnecessarily complicated docbook code.
```
```
=> treewide: replace <link> by <xref> where appropriate

modules/services/clipmenu.nix
This adds an option to set the launcher command for Clipmenu (which is set with the `CM_LAUNCHER` session variable).
```
```
=> clipmenu: add launcher option

modules/programs/git.nix, tests/modules/programs/git/git-expected.conf, tests/modules/programs/git/git.nix
* adds a option to set the store names for git inclues
* uses gitconfig instead of content  as default to help with the meaning of filenames
```
```
=> git: add option to define store names for generated include files

modules/programs/neovim.nix
everything is now covered by other settings that are more user friendly
than this big opaque attrset
```
```
=> programs.neovim: remove 'configure' setting

modules/programs/firefox.nix, tests/modules/programs/firefox/profile-settings-expected-bookmarks.html, tests/modules/programs/firefox/profile-settings.nix
This makes it possible to have a dir in a dir. This is needed to have a dir in the bookmark toolbar since that is already a dir.
```
```
=> firefox: make it possible to have nested folders (for boomarks)

docs/nix-flakes.adoc, flake.nix, templates/nix-darwin/flake.nix, templates/nixos/flake.nix, templates/standalone/flake.nix
Add example flakes from `docs/nix-flakes.adoc` as templates.
Format standalone flake in `docs/nix-flakes.adoc`
```
```
=> flake: add templates

modules/accounts/email.nix
Tested and changed the smtp host to the one specified in the [documentation](https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-8361e398-8af4-4e97-b147-6c6c4ac95353). Thanks to @ambroisie for pointing out the error.
```
```
=> email: fix the office365 smtp host

.github/CODEOWNERS, modules/services/git-sync.nix, tests/modules/services/git-sync/basic.nix
This fixed automated pushing to repository
```
```
=> git-sync: added ssh to path

modules/programs/git.nix, tests/modules/programs/git/git-expected.conf, tests/modules/programs/git/git-with-signing-key-id-expected.conf, tests/modules/programs/git/git-without-signing-key-id-expected.conf
The `tag.gpgSign` config option was added in Git 2.23.0 and seems like it should be set in addition to `commit.gpgSign` when `programs.git.signing.signByDefault` is enabled
This does introduce a minor change in behavior, but it seems a reasonable one to take. Do you have any thoughts on that @rycee or other maintainers?
```
```
=> git: gpg sign tags with signing.signByDefault set

modules/services/swayidle.nix
Allow another Wayland targets, as river-session.target or hyprland-session.target, to use swayidle.service which is  
hard-coded to sway-session.target.
```
```
=> swayidle: allow wayland targets other than sway-session.target

modules/systemd.nix
Units with `Install.RequiredBy` set will now set up `unit.requires/` links, in the same way that `Install.WantedBy` already sets up `unit.wants/`
```
```
=> systemd: Install.RequiredBy

modules/programs/git.nix, tests/modules/programs/git/default.nix, tests/modules/programs/git/git-pre-commit-hook.sh, tests/modules/programs/git/git-with-hooks.nix
This adds a configuration option to `programs.git` that aids in the configuration of custom Git [hooks](https://git-scm.com/docs/githooks). 
```nix
{
programs.git = {
enable = true;
hooks = {
pre-commit = ./path-to-hook.sh;
};
};
}
```
This seems to be failing with an unrelated error?
=> git: add config helper for hooks

.github/CODEOWNERS, modules/misc/news.nix, modules/modules.nix, modules/programs/gallery-dl.nix, tests/default.nix, tests/modules/programs/gallery-dl/default.nix, tests/modules/programs/gallery-dl/gallery-dl.nix
[gallery-dl](https://github.com/mikf/gallery-dl) is a cli to download image galleries from several image
hosting sites.
```
```
=> gallery-dl: add module

.github/CODEOWNERS
Fix typo in codeowners file
```
```
=> codeowners: fix typo

docs/installation.adoc, docs/manual.xml
To me it was not obvious that when using home-manager as a module in the nixos config it will use the channels of the root user when running `sudo nixos-rebuild switch`.
`sudo nixos-rebuild switch` uses the channels configured for the root user. The instructions should contain a Note pointing this out so new users are aware of this.
```
```
=> mention `sudo nixos-rebuild switch` uses root user channels

modules/programs/zsh.nix
Add an option for installing [zsh-history-substring-search](https://github.com/zsh-users/zsh-history-substring-search) outside of `prezto`.
I added it as a submodule of `zsh` but perhaps it would make more sense within the `zsh.history` module?
```
```
=> zsh: add option for `zsh-history-substring-search`

modules/programs/rtorrent.nix
Per NixOS RFC #42, settings should be reserved to structured configuration
settings, whereas extraConfig is used for stringly configuration.
```
```
=> rtorrent: change settings to extraConfig

docs/release-notes/rl-2211.adoc, modules/misc/xdg-user-dirs.nix, modules/services/mpd.nix, tests/modules/services/mpd/before-state-version-22_11.nix, tests/modules/services/mpd/default.nix, tests/modules/services/mpd/xdg-music-dir.conf, tests/modules/services/mpd/xdg-music-dir.nix, tests/modules/services/mpdris2/basic-configuration.nix, tests/modules/services/mpdris2/with-password.nix
- Makes paths `xdg.userDirs` use `home.homeDirectory` rather than `$HOME` to make them shell agnostic.
- Makes the MPD module use the XDG music directory if `xdg.userDirs.enable` is set, otherwise leave undefined so the user has to specify its value. To maintain backwards compatibility this only applies to state version 22.11 and later.
```
```
=> Update handling of mpd music directory option
