nix-community/home-manager

nix-darwin/default.nix

In #807 I changed the flag passed to `sudo` from `-i` to `-s` so `sudo`
wouldn't use a non-existent shell defined in the `passwd` file. kalbasit
also reported in that PR that `-i` didn't work for them anymore on an M1
Mac, presumably because Apple changed something in newer versions of
macOS.
Some users reported that this broke the behavior for them because
`SHELL` was set to a path that didn't even exist on their system. It's
unclear how this came to be but it shows that my assumption that `SHELL`
would be set to a reasonable shell by Home-Manager at this point in the
activation is false.
As a way around this problem we can explicitly set `SHELL` when running
the activation script to a value that we know will be good, like
`${pkgs.bash}`.
One change in behavior this causes is that the …

Provide SHELL for sudo -s invocation of activation script

---

modules/programs/mbsync-accounts.nix
tests/modules/programs/mbsync/mbsync-expected.conf
tests/modules/programs/mbsync/mbsync.nix

This supports multi-string values, like `SSLVersions TLSv1.3 TLSv1.2`.
Fixes #3228 
It uses `lib.types.oneOf`, introduced in 2019.
```
```

Allows lists of strings in extra configuration of `mbsync` (mail accounts).

---

.github/CODEOWNERS
modules/programs/yt-dlp.nix
tests/default.nix
tests/modules/programs/yt-dlp/default.nix
tests/modules/programs/yt-dlp/yt-dlp-simple-config-expected
tests/modules/programs/yt-dlp/yt-dlp-simple-config.nix

Adds a structured `settings` option for the recently added `yt-dlp` module. Also adds a test for the generated configuration file.
```
```

yt-dlp: add `settings` option

---

modules/programs/neovim.nix
tests/modules/programs/neovim/no-init.nix
tests/modules/programs/neovim/plugin-config.vim

We change the current logic: instead of writing an init.vim which loads lua/init-home-manager.lua, we write an init.lua that sources init.vim
This commit also avoids writing any of these files if the plugins have no config.
Should fix https://github.com/nix-community/home-manager/issues/1907
Needs some tests
```
```

programs.neovim: default to init.lua

---

modules/programs/neovim.nix
tests/modules/programs/neovim/plugin-config.nix

Fixes a syntax error that prevents neovim from loading the vimscript configuration file.
closes #3250
```
```

neovim: fix a typo in the generated init.lua

---

modules/programs/broot.nix
tests/modules/programs/broot/broot.nix

Fix `conf.hjson` path in `broot.nix`, unblocking builds.
For broot version >= 1.14.0, the default config file should be at
[`resources/default-conf/conf.hjson`](https://github.com/Canop/broot/blob/master/resources/default-conf/conf.hjson).
This PR fixes this error:
FileNotFoundError: [Errno 2] No such file or directory: '/nix/store/dikbik0phcq4lf7al6s1g6imcx2grfqs-broot-1.15.0.tar.gz/resources/default-conf.hjson'
`btop` test fails on master as well.
```
```

broot: fix build

---

flake.nix

I retained the use of `throwIf` on the off chance that someone intentionally overrides it.
```
```

list deprecated args in throw

---

modules/services/picom.nix

Mirrors https://github.com/NixOS/nixpkgs/commit/77307fcff86d3e56285b006b3e9204c6b45d90f0
```
```

picom: use `types.numbers.between`

---

docs/nix-flakes.adoc

- Added documentation how to enable flakes on NixOs
- Slightly extended non-NixOs instructions
Changes inspired by [Xe's article on flakes](https://xeiaso.net/blog/nix-flakes-1-2022-02-21).
```
```

docs: explain how to enable flakes on NixOs

---

docs/writing-modules.adoc
modules/lib/gvariant.nix
modules/lib/types.nix
tests/lib/types/gvariant-merge.nix

Add GVariant variant and dictionary entry types
Added support for GVariant variant and dictionary entry types.
```
```

lib: add two new gvariant types

---

modules/services/window-managers/fluxbox.nix

fluxbox: use mkPackageOption instead of mkOption

---

modules/programs/urxvt.nix

At nixpkgs, `rxvt_unicode` alias was deprecated in favor of `rxvt-unicode`. Updating accordingly.
https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/aliases.nix#L1005

urxvt: fix package name

---

modules/services/syncthing.nix

Make sure syncthing is only enabled on GNU/Linux.
- Well, technically the service would be successfully generated on e.g. Darwin but I think it is best to fail here.
```
```

syncthing: add platform assertion

---

modules/programs/lieer.nix
tests/modules/services/lieer/lieer-service-expected.service
tests/modules/services/lieer/lieer-service.nix

Fixes #3261 
The gmailieer attribute was aliased to lieer in nixpkgs.
```
```

programs/lieer: use lieer package

---

modules/programs/sbt.nix
tests/modules/programs/sbt/default.nix
tests/modules/programs/sbt/deprecated-options.nix
tests/modules/programs/sbt/repositories.nix
tests/modules/programs/sbt/user-config-path.nix

`sbt` allows overriding the default repositories to use to resolve
dependencies. This is often used with proxies and/or private
repositories to host internal packages.
This change adds a `repositories` attribute to `sbt` to allow specifying
the values that will go in `~/.sbt/repositories` file.
NOTE: I had to use `${baseConfigPath}/../repositories` to place the file in the right place. This seems brittle, but I can't find a better way without breaking compatibility (which seems worse).
```
```
- If this …

sbt: allow managing the `~/.sbt/repositories` file

---

modules/programs/sbt.nix
tests/modules/programs/sbt/credentials.nix

This will cache the output of `passwordCommand` per authentication realm.
Context: the `credentials` key in `sbt` is a `TaskKey[Seq[Credentials]]`. In `sbt`, tasks are evaluated on-demand and their output is not cached. This particular key is referenced by all submodules in a project. When the command is relatively expensive (e.g.: `pass show foo`), this results in several seconds of delay when doing basic things like `compile` or `test` which makes this unusable without some kind of caching.
```
```
- …

sbt: cache `passwordCommand` output

---

modules/systemd.nix
tests/modules/systemd/default.nix
tests/modules/systemd/slices.nix

Systemd slices should have names like `app.slice` (singular slice) instead of `app.slices` (plural)
```
```

systemd: name slice units correctly

---

.github/labeler.yml
.github/workflows/labeler.yml

automatically tag PRs depending on touched files
```
```

ci: introduce labeler workflow

---

modules/programs/sioyek.nix
tests/default.nix
tests/modules/programs/sioyek/default.nix
tests/modules/programs/sioyek/sioyek-basic-configuration.nix
tests/modules/programs/sioyek/test_keys_user.config
tests/modules/programs/sioyek/test_prefs_user.config

In Sioyek, [multiple keybindings can be set for the same command](https://github.com/ahrm/sioyek/blob/749a88fb927419ec85f795881c8f0c76600a06b3/pdf_viewer/keys.config#L26-L27). It would be nice for home-manager to be able to set that as well.
Since the configuration is getting a teeeeeny more complex, I also added a test.
```
```

sioyek: enable multiple bindings for the same command

---

home-manager/home-manager

Otherwise the switch exits with an error.
Fixes #3320
```
```

home-manager: set state version when uninstalling

---

.github/labeler.yml

ci: specify files that should be tagged "mail"

---

modules/misc/dconf.nix

Reduce divergence by resetting previously defined keys if their values
didn't change.
Closes: #1444
```
```

dconf: reset previously defined keys

---

modules/programs/firefox.nix

gnome3.chrome-gnome-shell is now gnome.gnome-browser-connector
```
```

rename chrome-gnome-shell suggestion.

---

modules/i18n/input-method/fcitx5.nix

The fcitx5 module doesn't add the appropriate `GLFW_IM_MODULE=ibus` session variable required for use of the input engine within the kitty terminal emulator (and presumably anything using GLFW). This fix is documented [here on the Arch Wiki](https://wiki.archlinux.org/title/Kitty#Enable_IME_support). I've added this variable.
Setting it to `ibus` works because fcitx5 apparently has an ibus-comaptible interface. I don't know if legacy fcitx has this, I haven't tried.
This is my first Nix/NixOS PR! I'm sorry if I've missed anything.
```
``` …

i18n.inputMethod.fcitx5: Add GLFW_IM_MODULE session variable for kitty support

---

modules/programs/i3status.nix
tests/modules/programs/i3status/with-custom.nix

i3status: add missing `package` attribute

---

modules/misc/news.nix
modules/programs/firefox.nix
tests/modules/programs/firefox/profile-settings-expected-search.json
tests/modules/programs/firefox/profile-settings.nix

With this change, it's now possible to configure the default search engine in Firefox with `programs.firefox.profiles.<name>.search.default` and add custom engines with `programs.firefox.profiles.<name>.search.engines`.
It's also recommended to enable `programs.firefox.profiles.<name>.search.force = true` since Firefox
will replace the symlink for the search configuration on every launch, but note that you'll loose any existing configuration by enabling this. 
Here's an example of how I'm using this in my home-manager config: https://gitlab.com/kira-bruneau/home-config/-/blob/028c1a50c82f8cad2be3d6693e6c53c67bf7e7c2/package/firefox/default.nix#L9-93.
**NOTE**: The hash verification is only required for custom search engines, it's ignored when setting your default engine to a builtin …

firefox: support setting search engine & adding custom engines

---

modules/services/borgmatic.nix
tests/modules/services/borgmatic/basic-configuration.service

Fix issue #3348 by specifying the full path of `sleep` referenced in
borgmatic.service.
```
```

borgmatic: specify where to find sleep

---

modules/home-environment.nix

This commits adds a file `hm-version` to the generated generation directory. This file will contain the release version, and if available, the Git commit hash.
```
```

home-environment: add hm-version file

---

modules/home-environment.nix
modules/misc/version.nix

Instead of home-made script use the Nixpkgs library functions. This will hopefully be more robust and give more accurate results.
```
```

home-environment: update hm-version generation

---

modules/programs/irssi.nix
tests/modules/programs/irssi/example-settings-expected.config
tests/modules/programs/irssi/example-settings.nix

Add option `programs.irssi.networks.<name>.saslExternal`. When enabled, this sets `sasl_username` for the network to the same value as `programs.irssi.networks.<name>.nick`, and sets `sasl_mechanism` to `EXTERNAL` (this means irssi will authenticate using SASL + certFP, the latter being configured with `programs.irssi.networks.<name>.server.ssl.certificateFile`).
An alternative would be to add three separate options for setting `sasl_username`, `sasl_password` and `sasl_mechanism` (which can be `PLAIN` to use `sasl_password`, or` EXTERNAL` to use certFP), but the approach I have taken avoids duplicating the nick/username, and prevents people from putting passwords in their config.
SASL + certFP is quite popular now, and LiberaChat restricts connecting without using SASL (i.e. depending on …

irssi: add option for SASL external authentication

---

modules/services/window-managers/i3-sway/sway.nix
tests/modules/services/window-managers/sway/sway-bar-focused-colors.conf
tests/modules/services/window-managers/sway/sway-bindkeys-to-code-and-extra-config.conf
tests/modules/services/window-managers/sway/sway-default.conf
tests/modules/services/window-managers/sway/sway-followmouse-expected.conf
tests/modules/services/window-managers/sway/sway-followmouse-legacy-expected.conf
tests/modules/services/window-managers/sway/sway-modules.conf
tests/modules/services/window-managers/sway/sway-null-package.conf
tests/modules/services/window-managers/sway/sway-workspace-default-expected.conf
tests/modules/services/window-managers/sway/sway-workspace-output-expected.conf

- The `XDG_SESSION_TYPE` environment variable is used by some applications and frameworks to detect wayland sessions (i.e qt5/6, electron/chromium). It is set by wlroots since version 0.13.0 [1].
- Propagating `XDG_SESSION_TYPE` to the systemd user environment is necessary when processes launched by services (e.g emacs) need to inherit the environment variable.
[1] - https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/90c8452959470461497c4a83aac0bd93efb0a524
```
```

sway: import XDG_SESSION_TYPE in systemd user environment

---

.github/workflows/github_pages.yml
.github/workflows/test.yml

Tokens are easier to rotate 
```
```

ci: use the cachix auth token

---

modules/services/window-managers/awesome.nix

Mirroring my change to awesome module in nixos:
https://github.com/NixOS/nixpkgs/commit/b79f9e9b8a822ac64710d67d26b558f9aba6d47b
```
```

awesome: fix luaModules using pkgs.lua instead of awesome.lua

---

modules/programs/vscode.nix
tests/modules/programs/vscode/default.nix
tests/modules/programs/vscode/tasks.nix

I fixed invalid examples of userSettings and userTasks and added userTasks' test.
```
```

vscode: fix examples and add a test

---

modules/launchd/default.nix
modules/targets/darwin/user-defaults/default.nix
tests/modules/targets-darwin/user-defaults.nix

Addresses https://github.com/nix-community/home-manager/pull/3381#issuecomment-1302716716.
```
```

darwin: use full path to commands in activation script

---

.github/workflows/test.yml

Seems we've been using the wrong Nixpkgs channel for all this time…

ci: use the right Nixpkgs channel for 22.05 tests

---

modules/home-environment.nix

this is a hackish workaround for https://github.com/NixOS/nix/issues/6349
(nix profile does not yet have a equivalent for nix-env --set)
supersedes: https://github.com/nix-community/home-manager/pull/3210 (a bit stalled)

fix #2848: delete home-path before re-adding on modern nix profiles

---

modules/services/window-managers/i3-sway/i3.nix

this can happen after logout/login
fixes https://github.com/nix-community/home-manager/issues/527
```
```

modules/i3: fix reloading when there are several sockets

---

docs/release-notes/rl-2211.adoc
modules/home-environment.nix
modules/programs/mu.nix
modules/systemd.nix
nixos/common.nix
tests/modules/programs/mu/basic-configuration.nix

Starting with state version 22.11 we completely reset the PATH variable in the activation script. This is to avoid impurities and unexpected results if the activation script accidentally uses a command found in the user's PATH.
```
```

home-environment: reset PATH in activation script

---

modules/programs/kodi.nix

syntax error. corrected the error in the example kodi plugins config together with helpfull irc chat :)
```
```

Kodi: fixed syntax error in example

---

modules/misc/news.nix
modules/programs/thunderbird.nix

While the Nix packages for Thunderbird are not available for macOS, the module can still be used to manage profiles and configuration.
Fixes #3407.
Pinging @jkarlson for review, @gbrindisi for testing.
```
```

thunderbird: allow using the module on Darwin

---

modules/services/udiskie.nix

Closes #3153
FYI @dschrempf
```
```

udiskie: add note about needing to enable system-wide config

---

modules/services/picom.nix
tests/modules/services/picom/picom-basic-configuration-expected.service
tests/modules/services/picom/picom-basic-configuration.nix

`--experimental-backends` flag was removed in the recent released picom v10. Using it now will result in the program exiting.
v10 also introduces its counter-part, `--legacy-backends`. However this will be removed soon. Instead of adding this as an separate option, add `extraArgs` option so for those that they want they can pass it manuall. It is also more future proof.
+ Removal of option, but it will trigger a proper warning.
```
```

picom: remove experimentalBackends, add extraArgs

---

modules/programs/fzf.nix

Add an option to specify fzf colors with an attribute set rather than writing the entire option string.
```
```

fzf: add colors option

---

modules/programs/scmpuff.nix
tests/modules/programs/scmpuff/default.nix
tests/modules/programs/scmpuff/fish.nix
tests/modules/programs/scmpuff/no-fish.nix

Add fish integration to the `scmpuff` program
```
```

feat(scmpuff): add fish integration flag

---

modules/programs/kitty.nix

Rather than reject a configuration when this option is set, just silently ignore it when the platform isn't darwin. The name makes it obvious that it won't be applied outside of darwin, and this allows people to use the same configuration between hosts without any special concern.

kitty: silently drop darwin-specific options

---

.github/CODEOWNERS
modules/services/polybar.nix
tests/modules/services/polybar/basic-configuration.nix
tests/modules/services/polybar/default.nix
tests/modules/services/polybar/empty-configuration.nix

The polybar module will no longer assume you want a declarative config unless you have configured either `services.polybar.settings`, `services.polybar.config` or `services.polybar.extraConfig`. This closes #3326
```
```

polybar: don't generate config if no options are set

---

docs/contributing.adoc
flake.nix
tests/modules/programs/zplug/modules.nix

The existing way to run tests with `nix-shell` relies on impure usage of `<nixpkgs>`. This can lead to failures when the local nixpkgs is incompatible with the locked one. I.e., where CI is passing but a contributor may experience a failure.
So, expose tests as `devShells.tests` to use the locked nixpkgs and allow easy invocation via `nix develop`.
I did not change the existing `nix-shell` docs or usage in CI, as unsure if that’s wanted at this point as flakes are still technically experimental, but of course can if desired.
This change was born out of me trying to contribute and run the tests, but them failing because my local nixpkgs is nixos-22.05 and home-manager master is nixos-unstable. Compare e.g. right now on a nixos-22.05 system:
```
$ nix-shell --pure tests -A run.broot …
```

flake: Expose tests to allow running purely

---

modules/programs/kakoune.nix

Other tools such as neovim allow a custom package to be defined. This PR aims to allow the same for kakoune.
This is handy, especially when kakoune is not up to date with the latest version in nixpkgs. It allows you to override it to use the latest one for example, or when developing using a fork.
```
```

kakoune: allow custom package

---

modules/programs/nushell.nix
modules/programs/starship.nix
tests/modules/programs/nushell/config-expected.nu
tests/modules/programs/nushell/env-expected.nu

This PR adds the two options `extraConfig` and `extraEnv` to nushell. These value of these options are appended/merged with `configFile` and `envFile`. This is to ensure backwards compatibility.
Motivation for this is the starship nushell integration, which requires to extend either env and config files.
Unfortunately nushell is limited in sourcing or conditionally setting global environment variables, which is why the terminal compatibility check isn't done compared to the other starship shell integrations.
Fixes #3058
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commit …

Support starship nushell integration

---

modules/services/picom.nix

Mirrors: https://github.com/NixOS/nixpkgs/commit/2beff9375cda53f2ab42844eb85d9c60175f3434
Picom v10 added a new `egl` experimental backend.
@thiagokokada
```
```

picom: add `egl` backend to options

---

modules/programs/zplug.nix

This is a minor bugfix. The option `zplugHome` of the `zplug` module allows to set the directory to which `zplug` downloads plugins. The option sets the shell variable `ZPLUG_HOME` accordingly. However, currently this is set **after** initializing `zplug` via `source ${pkgs.zplug}/init.zsh`. To be taken into account, the variable must be set before the initialization. To fix this, I simply swapped the two lines. This order is also used in `zplug`'s own tests, see [misc/zshrc in zplug](https://github.com/zplug/zplug/blob/c4dea766566b168a32dbfa8d10335e525ce39fcc/misc/zshrc#L6-L11).
```
``` …

programs.zsh: set ZPLUG_HOME before loading zplug

---

.github/labeler.yml

more specifically thunderbird and himalaya
```
```

ci: autolabel more programs to 'mail'

---

modules/programs/direnv.nix

Direnv >=2.21.0 (released on Jan 25, 2020) uses [`$XDG_CONFIG_HOME/direnv/config.toml` as configuration path](https://github.com/direnv/direnv/commit/54cb3c5a91edb377b4b7387e2cda43dc39064a4a
).
```
```

direnv: fix direnv configuration path

---

modules/programs/neovim.nix
tests/modules/programs/neovim/plugin-config.nix
tests/modules/programs/neovim/plugin-config.vim

The previous version linked the file into home, then sourced that. Since
nothing else expects that file to be there, this is unnecessary.
Additionally, doing so made it impossible to test a built config without
switching, e.g. using `XDG_CONFIG_HOME=… nvim` or `nvim -u`. This
remedies that, at least for this particular reference.
To test this, change from asserting contents of the config file to
actually starting nvim, outputting sentinel values, and then asserting
their values are present. This way it’s tested that nvim loaded the
config, rather than that some config is in a specific place.
This is all in one commit as the test, as written now, would not have
worked before since the previously hard-coded home path was not an
actual file in the test environment.
```
{component}: …
```

neovim: Source neovimRcContent directly from store

---

modules/programs/just.nix

Closes #3449. Also deprecates the entire thing as completions work out of the box now! Also removes the old completions implementation to avoid double-initializing them
Note: there are no tests for this module and the tests fail with unrelated `No such file or directory: '/nix/store/61h76ya021588gp3g6my168pib7in8w9-broot-1.12.0.tar.gz/resources/default-conf/conf.hjson'` so I'm just ignoring that requirement
```
```

just: deprecate since completions work out of the box now

---

modules/programs/fish.nix
tests/modules/programs/fish/default.nix
tests/modules/programs/fish/format-scripts.nix

Create a `runCommand` based wrapper to indent fish code using `fish_indent`.
Addresses #2303
```
```

fish: Format fish code

---

modules/services/polybar.nix
tests/modules/services/polybar/basic-configuration.nix
tests/modules/services/polybar/empty-configuration.nix

The old trigger would actually never cause a restart since the path doesn't change. With this change the trigger is now using the actual configuration path in the Nix store, which depends on the content.
```
```

polybar: fix restart trigger

---

modules/programs/pet.nix

Pet snippets can be managed with HM or with Pet gist support.
This stops HM from generating an empty file if no snippets are provided in the configuration; allowing Pet to sync the snippet file with the gist.
```
```

pet: don't create file without snippets

---

modules/programs/thunderbird.nix
tests/modules/programs/thunderbird/thunderbird-expected-first.js
tests/modules/programs/thunderbird/thunderbird-expected-second.js

This allows users to have multiple accounts on the same domain within the same profile.
Fixes #3448.
```
```

thunderbird: use account id for IMAP directory name

---

docs/nix-flakes.adoc
templates/nix-darwin/flake.nix

Corrects copy/paste mistake in the nix-darwin flake description.
```
```

flake: correct nix-darwin flake description

---

modules/programs/yt-dlp.nix

The yt-dlp settings should be an attribute set.
```
```

yt-dlp: fix settings example

---

modules/programs/hexchat.nix
modules/programs/irssi.nix
tests/modules/programs/hexchat/basic-configuration-expected-serverlist-config
tests/modules/programs/hexchat/basic-configuration.nix

Freenode was taken over by a wannabe bitcoin millionaire [1], which prompted the migration of communities to Libera Chat [2].
[1] https://blog.bofh.it/debian/id_461
[2] https://hackaday.com/2021/05/20/freenode-debacle-prompts-staff-exodus-new-network/
```
```

treewide: use liberachat in examples

---

modules/programs/emacs.nix

Hopefully this can avoid a bit of confusion.
```
```

emacs: add note about `inhibit-startup-message`

---

modules/programs/fish.nix
tests/modules/programs/atuin/fish.nix
tests/modules/programs/atuin/no-shell.nix
tests/modules/programs/fish/functions.nix
tests/modules/programs/fish/no-functions.nix
tests/modules/programs/fish/plugins.nix
tests/modules/programs/nix-index/assert-on-command-not-found.nix
tests/modules/programs/nix-index/integrations.nix
tests/modules/programs/oh-my-posh/fish.nix
tests/modules/programs/pls/fish.nix
tests/modules/programs/powerline-go/fish.nix
tests/modules/programs/scmpuff/fish.nix
tests/modules/programs/scmpuff/no-fish.nix

Always run fish_indent, remove option, and remove test stubs
```
```

fish: always run fish_indent

---

home-manager/default.nix

Before the home-manager tool got hostname from the system, which was not declarative or reproducible.
```
```

home-manager: use `hostname` from Nixpkgs

---

tests/modules/programs/gpg/immutable-keyfiles.nix

The tests are failing:
`nix-shell --pure tests -A run.all` gives
```
building '/nix/store/85gsm9z5y0ihh87nmc3pqrlbwfvdpwbn-pgp_keys.asc?fingerprint=36cacf52d098cc0e78fb0cb13573356c25c424d4.drv'...
building '/nix/store/0y5b1apdsilck5dcgahhi1rhxb3kjxnv-pubkey.txt.drv'...
created 296 symlinks in user environment
trying https://www.rsync.net/resources/pubkey.txt
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
trying https://keybase.io/rycee/pgp_keys.asc?fingerprint=36cacf52d098cc0e78fb0cb13573356c25c424d4
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  1855  100  1855    0     0   1757      0  0:00:01  0:00:01 --:--:--  1756
100 18048  100 …
```

tests/immutable-keyfiles: update sha256

---

tests/modules/programs/i3status-rust/with-custom.nix
tests/modules/programs/i3status-rust/with-default.nix
tests/modules/programs/i3status-rust/with-extra-settings.nix
tests/modules/programs/i3status-rust/with-multiple-bars.nix

Nix 2.12.0 slightly changed the JSON output format. This updates the i3status-rust test cases to match.
```
```

i3status-rust: fix test

---

modules/programs/borgmatic.nix
tests/modules/programs/borgmatic/basic-configuration.nix

In particular, we should be able to specify `exclude_backups` in our configuration.
This fixes #3489.
```
```

borgmatic: allow lists in extraConfig

---

.github/CODEOWNERS
modules/misc/news.nix
modules/modules.nix
modules/services/megasync.nix

Add the `megasync` module.
It basically starts the megasync client through a systemd service.
```
```

megasync: add module

---

modules/programs/pistol.nix
tests/modules/programs/pistol/associations.nix
tests/modules/programs/pistol/config.nix
tests/modules/programs/pistol/default.nix
tests/modules/programs/pistol/double-association.nix
tests/modules/programs/pistol/missing-association.nix

This pull requests refactors the pistol configuration options, since the current options are deficient in a few ways. Closes #3486.
**No**, see https://github.com/nix-community/home-manager/issues/3486#issuecomment-1345354257
```
```

pistol: refactor

---

modules/programs/lazygit.nix

Added a package option for lazygit
Tested locally using:
```
programs.lazygit = {
enable = true;
package = (pkgs.lazygit.overrideAttrs (oldAttrs: {
patches = (oldAttrs.patches or [ ]) ++ [
(pkgs.fetchpatch {
name = "fix-credential-prompt.patch";
url = "https://patch-diff.githubusercontent.com/raw/jesseduffield/lazygit/pull/2239.patch";
sha256 = "sha256-olj4xV1AU93R76drDuISQRNpxv/85GBfXJe6WgO33xc=";
})
];
}));
settings = {
git.autoFetch = false;
};
};
```
NOTE: there was no test-case available, should I add one?
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) …

lazygit: add package option

---

home-manager/home-manager

Depending on DHCP settings you might end up with different output from running `hostname`. Eg, your local hostname is `mylaptop`, and your home router is configured with a local domain of `.home.arpa`. In this case:
$ hostname
mylaptop.home.arpa
$ hostname -s
mylaptop
If you then go to cafe which has its router configured with `.lan` as its local domain. Then, if your DHCP settings accept the local domain from the router,
$ hostname
myalaptop.lan
$ hostname -s
mylaptop
With the pre-existing behaviour, if you had a `"me@mylaptop.home.arpa"` entry in `outputs.homeConfigurations`, running `home-manager switch` would fail:
$ home-manager switch
error: flake 'git+file:///home/me/.config/nixpkgs' does not provide
attribute 'packages.aarch64-darwin.homeConfigurations."me".activationPackage', …

home-manager: Try short hostname in flake config lookup

---

modules/programs/nushell.nix
tests/modules/programs/nushell/example-settings.nix

Updates the nushell program to support the correct config file locations on Darwin systems.
- No existing tests exist, none added
```
```

fix: nushell supports darwin config file locations

---

modules/services/window-managers/herbstluftwm.nix
tests/modules/services/window-managers/herbstluftwm/default.nix
tests/modules/services/window-managers/herbstluftwm/herbstluftwm-no-tags-autostart
tests/modules/services/window-managers/herbstluftwm/herbstluftwm-no-tags.nix
tests/modules/services/window-managers/herbstluftwm/herbstluftwm-simple-config-autostart
tests/modules/services/window-managers/herbstluftwm/herbstluftwm-simple-config.nix

The default value for `xsession.windowManager.herbstluftwm.tags` is an
empty list, but the config file uses `builtins.head` on it, which causes
an error upon evaluation. With this change the tags configuration is
skipped if the list is empty.
Also included a minor change to reset mousebinds on reload for
consistency with the keybinds. 
```
```

herbstluftwm: Fix evaluation error when no tags are set

---

modules/programs/bash.nix

Since this option is very unlikely to contain a shell variable we should be safe doing a full shell escaping.
Fixes #3249
```
```

bash: escape historyIgnore value

---

modules/home-environment.nix

Before we used dirname and readlink from the ambient environment, which caused problems when they don't behave as expected.
Fixes #3516
```
```

home-environment: explicitly use coreutils

---

modules/misc/news.nix
modules/modules.nix
modules/services/cachix-agent.nix
tests/default.nix
tests/modules/services/cachix-agent/basic-setup.nix
tests/modules/services/cachix-agent/default.nix

Add support for running a Cachix Deploy Agent as a user service.
CC @domenkozar
```
```

cachix-agent: add module

---

docs/man-home-manager.xml
home-manager/completion.bash
home-manager/completion.fish
home-manager/completion.zsh
home-manager/home-manager

When building from a flake, `nix build` hides the build output by default, with a `-L`/`--print-build-logs` option to show it. Pass this option along from `home-manager` if the user provides it.
```
```

Pass along -L/--print-build-logs when building from a flake

---

modules/programs/starship.nix

Overwrite starship/init.nu if already exists, since this is a cache file for sourcing in `init.nu`.
This will be necessary when nushell 0.73 lands in nixpkgs.
```
```

starship: fix nushell integration

---

modules/programs/starship.nix

which was apparently mistakenly removed in commit 7ae7250
```
```

starship: re-add ion integration

---

tests/modules/programs/broot/broot.nix

Make test match new result.
Fixes #3527
CC @aheaume 
```
```

broot: update test to match upstream changes

---

modules/programs/direnv.nix
tests/modules/programs/direnv/default.nix
tests/modules/programs/direnv/nushell.nix

This enables nushell integration by default for direnv, similar to bash/zsh/fish. The slightly verbose way of setting this is to ensure that peoples' existing nushell configuration isn't overwritten, only appended to, as would be the case if we just used the integration example from the nushell docs (https://www.nushell.sh/cookbook/direnv.html) to preserve backwards compatibility.
Closes #3520
```
```

direnv: enable nushell integration

---

modules/programs/fish.nix

Adds `$HOME=$(mktemp -d)` to silence errors, as in #3501 
```
```

fish: set tmp $HOME to silence errors

---

modules/services/parcellite.nix
tests/default.nix
tests/modules/services/parcellite/default.nix
tests/modules/services/parcellite/parcellite-expected.service
tests/modules/services/parcellite/parcellite.nix

Add `extraOptions` option to Parcellite service.
Even though `--no-icon` is currently the only viable option for both `parcellite` and `clipit`, other options may be added to later releases.
```
```

parcellite: Add extraOptions option

---

modules/programs/gitui.nix

Update gitui default theme to match [upstream values](https://github.com/extrawurst/gitui/blob/761cb104050ef622765ec739e2c6e9c551830913/src/ui/style.rs#L308-L328).
Fixes #3506
CC @Mifom
```
```

gitui: update default theme to match upstream

---

modules/programs/neovim.nix
tests/modules/programs/neovim/runtime.nix

Assigning to `programs.neovim.extraLuaPackages` a function taking a lua package set as input and returning a list of packages, as described in the documentation, threw an error because the rest of the code assumed that the value was always a plain list.
Using `lib.types.coercedTo`, we can accept such functions, as per the documentation, as well as plain lists, which we then convert to a function ignoring its input argument.
We print a warning when a plain list is assigned, since the function form is preferred, as it ensures that the right lua package set is used.
For the lua packages, we also get the lua package set from the finalPackage, to make sure that we are always using the same package set as the actual unwrapped neovim package being built.
For `programs.neovim.extraPythonPackages` …

neovim: fix extraLuaPackages type.

---

modules/programs/kakoune.nix

Some hooks were removed in Kakoune, and some were added. This PR updates the list so they are aligned with the latest version of Kakoune.
https://github.com/mawww/kakoune/commit/e4fb70ebec80edcd17f0e00823780e4798a3fb1a
- `NormalBegin`
- `NormalEnd`
- `InsertBegin`
- `InsertEnd`
https://github.com/mawww/kakoune/commit/78419bc76f833b493b700bf3262c52fd93544744
- `InsertCompletionSelect`
https://github.com/mawww/kakoune/commit/c8839e79041ef37849a4cb8ac5017eadc8ec9653
- `ClientCreate`
- `ClientClose`
https://github.com/mawww/kakoune/commit/47ba36c66e0e38c5bb5c832bfa751d553f769baa
- `RegisterModified`
https://github.com/mawww/kakoune/commit/f2cc7bc891922ad48c4372c0b69239ef74bce004
- `User`
```
```
See …

kakoune: update hooks

---

modules/services/window-managers/i3-sway/i3.nix

In nix `${` is escaped like this `''${` and not like this `\${`
```
```

Fix escaping in i3 documentation

---

modules/home-environment.nix

`attrs` has unreasonable merge semantics and is deprecated. `attrsOf` doesn't support variables depending on each other as is recommended in the option's description.
Context:
- https://github.com/NixOS/nixpkgs/pull/97119
- https://github.com/NixOS/nixpkgs/pull/70138
- https://github.com/nix-community/home-manager/pull/1595 (cc @berbiche)
- https://github.com/nix-community/home-manager/pull/1769 
- https://github.com/nix-community/home-manager/pull/3496#issuecomment-1367534054
```
```

home-environment: use `lazyAttrsOf` for `home.sessionVariables`

---

modules/programs/neovim.nix
modules/programs/vim.nix

Also rename `vim_configurable` to `vim-full` per https://github.com/NixOS/nixpkgs/pull/204438
```
```

vim,neovim: add `defaultEditor`

---

modules/services/window-managers/i3-sway/lib/options.nix
tests/modules/services/window-managers/sway/sway-bar-focused-colors.conf
tests/modules/services/window-managers/sway/sway-bindkeys-to-code-and-extra-config.conf
tests/modules/services/window-managers/sway/sway-default.conf
tests/modules/services/window-managers/sway/sway-followmouse-expected.conf
tests/modules/services/window-managers/sway/sway-followmouse-legacy-expected.conf
tests/modules/services/window-managers/sway/sway-modules.conf
tests/modules/services/window-managers/sway/sway-null-package.conf
tests/modules/services/window-managers/sway/sway-stubs.nix
tests/modules/services/window-managers/sway/sway-workspace-default-expected.conf
tests/modules/services/window-managers/sway/sway-workspace-output-expected.conf

Sway recommends foot as the default terminal emulator. It runs natively on wayland, which urxvt does not.
Replace urxvt with foot as the default terminal for sway.
https://github.com/swaywm/sway/commit/009c58fc9529e284569bf58b73964cb3dc7c5baf
Also aligns with http://github.com/nixos/nixpkgs/commit/2e719d1cdab9e81750c19425a1f5c7678b5e73ad.
```
```

i3-sway: Use foot as default terminal on sway

---

modules/services/window-managers/fluxbox.nix

This issue causes my nixos update (nixos-rebuild switch) to fail with the following error:
```
error: attribute 'windowMenu' missing
at /nix/store/[...]-source/modules/services/window-managers/fluxbox.nix:115:15:
114| ".fluxbox/windowmenu" = 
115| mkIf (cfg.windowMenu != "") { text = cfg.windowmenu; };
|       ^
116| };
Did you mean windowmenu?
```
Closes #3559 
```
```

fluxbox: Fixed a typo, windowMenu -> windowmenu

---

modules/config/home-cursor.nix

This commit fixes conflicting definitions of the XCURSOR_PATH environment variable with the same priority under `home.sessionVariables` introduced in https://github.com/nix-community/home-manager/pull/2902. Rather than raising the priority of the XCURSOR_PATH set in `targets.genericLinux`, the priority of the environment variable set in `home.pointerCursor` is lowered via mkDefault. This is done to avoid the `target.genericLinux` module overriding user set values silently.
fixes https://github.com/nix-community/home-manager/issues/3551
```
``` …

home.pointerCursor: use mkDefault to set XCURSOR_PATH

---

modules/services/easyeffects.nix

Add package option to `service.easyeffects'.
There is some bugs in package, that you may want to fix by overriding. F.e. https://github.com/NixOS/nixpkgs/issues/189481
```
```

easyeffects: add package option

---

docs/default.nix

- Introduces support for Markdown documentation in modules.
```
```

docs: bump nmd

---

modules/programs/ncmpcpp.nix
tests/modules/programs/ncmpcpp-linux/default.nix
tests/modules/programs/ncmpcpp-linux/ncmpcpp-issue-3560-expected-config
tests/modules/programs/ncmpcpp-linux/ncmpcpp-issue-3560.nix

The default value of `programs.ncmpcpp.mpdMusicDir` is taken from `services.mpd.musicDirectory` if the mpd module is enabled, which has type `either path str`. `programs.ncmpcpp.mpdMusicDir` did not accept `str` values, though, so an error was raised when the default value was used and `services.mpd.musicDirectory` was set to a value of type `str`.
This commit changes the type of `programs.ncmpcpp.mpdMusicDir` to also accept `str` to reflect the type of `services.mpd.musicDirectory`.
Fixes the ncmpcpp part of #3560
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/mas …

ncmpcpp: Allow `str` type values for `mpdMusicDir` option

---

docs/release-notes/rl-2305.adoc
modules/misc/news.nix
modules/services/window-managers/i3-sway/i3.nix
modules/services/window-managers/i3-sway/lib/options.nix

[i3 4.22 has been released](https://i3wm.org/downloads/RELEASE-NOTES-4.22.txt). The main change is the merge of i3-gaps features.
This (now merged) [PR](https://github.com/NixOS/nixpkgs/pull/208861) brings this update to nixpkgs/NixOS.
Hence, we should update the `services.window-managers.i3` module by removing all the "`i3` vs `i3-gaps`" distinctions.
My only interrogation is the default value of the [`i3.config.floating.titlebar`](https://nix-community.github.io/home-manager/options.html#opt-xsession.windowManager.i3.config.floating.titlebar) and [`i3.config.window.titlebar`](https://nix-community.github.io/home-manager/options.html#opt-xsession.windowManager.i3.config.window.titlebar) options.
Before, there were set to `false` by default when using `i3-gaps`. The i3 documentation …

i3: remove i3/i3-gaps distinction

---

modules/files.nix

In the unlikely (but possible) event that a directory is created in place of a target file *after* `checkLinkTargets` but *before* `linkGeneration`, currently the link is created *inside* the directory, which is surprising (see https://github.com/nix-community/home-manager/pull/3017 for context).
To avoid this, use `ln -T` and bail if it fails.
~Also bail if backing up the target fails.~
Ideally, `checkLinkTargets` and `linkGeneration` should be more tightly coupled.
```
```

files: avoid surprises when linking files

---

modules/services/window-managers/i3-sway/i3.nix

The previous code prevents one from specifying a custom i3 package with the error "`xsession.windowManager.i3.package` is defined multiple times".
`mkDefault` is another way to fix that, but it's not needed here as the package option definition already defaults to the i3 package (where `mkPackageOption` is called).
Resolves #3584
```
```

i3: Do not set i3 package

---

docs/installation.adoc
home-manager/home-manager

Since 2.4, the Nix installer [no longer](https://github.com/NixOS/nix/commit/ec9dd9a5aeb9b7fca170d86b8906ffac7e5ef057) adds the `NIX_PATH` environment variable to shell profiles, because Nix now has a built-in search path if it's unset. However, home-manager still relies on it being set and prepends search paths for `home-manager`. Even though the documentations have been updated to include instructions for non-NixOS users, this is a bad first-time experience (https://github.com/nix-community/home-manager/issues/2564, https://github.com/nix-community/home-manager/issues/3020, https://github.com/nix-community/home-manager/issues/2580).
Instead of relying on NIX_PATH being set and prepending to it, let's not touch it at all and add our paths as `-I` arguments. We trust that Nix will use a …

home-manager: Add home-manager search path to EXTRA_NIX_PATH

---

modules/services/window-managers/i3-sway/i3.nix
modules/services/window-managers/i3-sway/lib/options.nix
modules/services/window-managers/i3-sway/sway.nix
tests/modules/services/window-managers/i3/i3-bar-focused-colors-expected.conf
tests/modules/services/window-managers/i3/i3-followmouse-expected.conf
tests/modules/services/window-managers/i3/i3-fonts-expected.conf
tests/modules/services/window-managers/i3/i3-keybindings-expected.conf
tests/modules/services/window-managers/i3/i3-workspace-default-expected.conf
tests/modules/services/window-managers/i3/i3-workspace-output-expected.conf

Stop using the [legacy syntax](https://i3wm.org/docs/userguide.html#_focus_wrapping) for focus wrapping.
```
```

i3-sway: config.focus.wrapping deprecates forceWrapping

---

modules/programs/opam.nix

Fixes #3595.
Fish shell doesn't require arguments to `eval` to be double quoted like in a bash shell. At the moment doing so gives us the following error:
```
~/.config/fish/config.fish (line 12): $(...) is not supported. In fish, please use '(/nix/store/8asq…)'. eval "$(/nix/store/8asqgnhs89wzyjvs8p1n5hvxn7lkn9wa-opam-2.1.3/bin/opam env --shell=fish)"
^
from sourcing file ~/.config/fish/config.fish
called during startup
source: Error while reading file “/home/user/.config/fish/config.fish”
```
This commit fixes the above error.
```
``` …

opam: fix enableFishIntegration

---

.github/CODEOWNERS
modules/misc/news.nix
modules/modules.nix
modules/programs/papis.nix
tests/default.nix
tests/modules/programs/papis/default.nix
tests/modules/programs/papis/papis.nix

Add module for https://papis.readthedocs.io/
```
```

papis: add module

---

modules/programs/password-store.nix
modules/services/pass-secret-service.nix
tests/default.nix
tests/modules/services/pass-secret-service/basic-configuration.nix
tests/modules/services/pass-secret-service/default-configuration.nix
tests/modules/services/pass-secret-service/default.nix

Allow setting the application package and storePath used by the config.
Since the programs.password-store home-manager module sets config values
via global environment variables, the default behavior of the module
should continue to behave as before for the user.
Additionally, performs some cleanup and adds a few tests that helped me
catch some bugs.
Closes #2962 
```
```

pass-secret-service: Add Tests, Remove Dependency on password-store Module

---

flake.nix

Add link https://nix-community.github.io/home-manager/release-notes.html#sec-release-22.11-highlights to the 'homeManagerConfiguration' argument deprecation message
New Message:
```
The 'homeManagerConfiguration' arguments
- 'configuration',
- 'username',
- 'homeDirectory'
- 'stateVersion',
- 'extraModules', and
- 'system'
have been removed. Instead use the arguments 'pkgs' and
'modules'. See the 22.11 release notes for more.
https://nix-community.github.io/home-manager/release-notes.html#sec-release-22.11-highlights
```
Justification: I just ran into this problem and it would have been helpful to have this link in the command line output instead of having to search around. 
Notes: I did not intentionally adjust the spaces in front of the message. './format' added them.
```
{component}: …
```

home-manager: edit `homeManagerConfiguration` err

---

modules/programs/git.nix

Remove `core.pager = "${pkgs.less}/bin/less -XF"` since Git already sets `LESS=FRX` and it prevents from using another pager while difftastic does not require a specific pager.
```
```

git: unset `pager` while using difftastic

---

.github/CODEOWNERS
modules/misc/news.nix
modules/modules.nix
modules/services/autorandr.nix

[autorandr](https://github.com/phillipberndt/autorandr) already has a home-manager module: [`programs.autorandr`](https://github.com/nix-community/home-manager/blob/master/modules/programs/autorandr.nix).
The latter configures the profiles and adds the package (`pkgs.autorandr`) to `home.packages`. This is meant for a CLI usage.
Meanwhile, the NixOS has a (unique) module for autorandr: [`services.autorandr`](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/misc/autorandr.nix) which does the same as the home-manager `programs.autorandr` module as well as adding a `systemd` service to run autorandr automatically.
This PR adds a second home-manager autorandr module: `service.autorandr` which simply adds a `systemd` user service that starts `autorandr` …

services.autorandr: add module

---

modules/programs/mbsync.nix
tests/modules/programs/mbsync/mbsync-expected.conf

`mbsync` treats option `accounts.email.accounts.<name>.passwordCommand` like a shell command, whereas other command like `himalaya`, `getmail` and `aerc` treat it like a command to be executed directly. This PR makes `mbsync`'s behavior consistent with other mail clients.
```
```

mbsync: make passwordCommand escaping consistent

---

modules/programs/tmux.nix
tests/modules/programs/tmux/default-shell.conf
tests/modules/programs/tmux/default.nix
tests/modules/programs/tmux/disable-confirmation-prompt.conf
tests/modules/programs/tmux/emacs-with-plugins.conf
tests/modules/programs/tmux/mouse-enabled.conf
tests/modules/programs/tmux/mouse-enabled.nix
tests/modules/programs/tmux/shortcut-without-prefix.conf
tests/modules/programs/tmux/vi-all-true.conf

tmux: mouse support

---

modules/programs/java.nix

Some JVMs pass through `home` as a derivation rather than as a string, as `openjdk` does. Since the module option for session variables expects a string, this is a type error. I suspect that this incorrect, and have changed the assignment here to coerce the `cfg.package.home` attribute to a string to be safe.
After discussing with @NobbZ, we have decided it is best to mitigate this problem in HM rather than to make potentially breaking changes to Nixpkgs.
Please do mention if you think we ought to propose a change to Nixpkgs instead.
```
``` …

modules: java: fix setting JAVA_HOME

---

.github/CODEOWNERS
modules/lib/maintainers.nix
modules/modules.nix
modules/programs/vim-vint.nix
tests/default.nix
tests/modules/programs/vim-vint/basic-configuration.nix
tests/modules/programs/vim-vint/basic-configuration.yaml
tests/modules/programs/vim-vint/default.nix

Adds the [Vint](https://github.com/Vimjas/vint) Vimscript linter as a module.
This is my first PR to Home-Manager; if I've done something wrong please tell me!
```
```

vim-vint: add module

---

modules/services/borgmatic.nix
tests/modules/services/borgmatic/basic-configuration.service

This reflects a systemd service sample file change made in [borgmatic 1.7.6](https://github.com/borgmatic-collective/borgmatic/releases/tag/1.7.6), commit [2e9f70d49647d47fb4ca05f428c592b0e4319544](https://github.com/borgmatic-collective/borgmatic/commit/2e9f70d49647d47fb4ca05f428c592b0e4319544):
When backing up a machine with a monitor using logind to control
idle timeout and things like DPMS, borgmatic can block the screen
from turning on/off with systemd-inhibit. This is because by
default systemd-inhibit will block
"idle:sleep:shutdown". Borgmatic does not need to care about idle,
only about suspend and shutdown. So, add an explicit `--what` flag
for what borgmatic should inhibit.
For more information see systemd-inhibit(1).
```
```
See …

borgmatic: Do not inhibit idle in service

---

modules/programs/tmux.nix
tests/modules/programs/tmux/secure-socket-enabled.nix

I don't know why it was escaped, but if `XDG_RUNTIME_DIR` is not defined, then `TMUX_TMPDIR=/run/user/$(id -u)`.
```
```

tmux: fix secureSocket environment variable

---

modules/programs/neovim.nix
tests/modules/programs/neovim/default.nix
tests/modules/programs/neovim/extra-lua-init.nix

Suggestion to fix: https://github.com/nix-community/home-manager/issues/3457
Adds a configuration `programs.neovim.extraLuaConfig` that is added to the `init.lua` generated by home-manager.
```
```

programs.neovim: add extraLuaConfig

---

docs/release-notes/rl-2305.adoc
modules/programs/firefox.nix

Internally we already managed them per-profile but exposed a global option to maintain backwards compatibility. The benefit to having per-profile extensions is quite large though, so it is time to switch.
Users of the global extensions option will get an error message that indicates how to edit their configuration to work again.
```
```

firefox: manage add-ons per-profile

---

modules/misc/nix.nix

Sync it with the condition for generating nix.conf so that it triggers if `extraOptions` is set but `package` isn't. See https://github.com/nix-community/home-manager/pull/2718#discussion_r1097082480
```
```

nix: fix package assertion

---

modules/lib-bash/activation-init.sh

This is not a standalone script, it's only meant to be included from the activation script.
```
```

activation-init.sh: remove shebang, execute bit

---

modules/services/blueman-applet.nix
modules/services/dunst.nix
modules/services/gpg-agent.nix
modules/services/kdeconnect.nix
modules/services/keepassx.nix
modules/services/mpd-discord-rpc.nix
modules/services/owncloud-client.nix
modules/services/pasystray.nix
modules/services/picom.nix
modules/services/random-background.nix
modules/services/stalonetray.nix
modules/services/swayidle.nix
modules/services/syncthing.nix
modules/services/taffybar.nix
modules/services/tahoe-lafs.nix
modules/services/udiskie.nix
modules/systemd.nix

This is related to https://github.com/nix-community/home-manager/pull/2497#discussion_r754814040.
The systemd module currently contains checks to make sure user services aren't defined on Darwin hosts. But with launchd support now in HM, this can result in feature gating boilerplate when trying to create modules that supports both systemd and launchd.
After this change, modules would be able to define both systemd services and launchd agents without the boilerplate. The systemd module would just ignore them on macOS and vice versa for launchd. I'm hoping this wouldn't be a big issue because most consumers of the systemd module already checks if it supports the target OS. I've also added checks for those that didn't.
For a more concrete example, here's how a module supporting both systemd …

Remove platform check from the systemd module

---

tests/modules/programs/scmpuff/bash.nix
tests/modules/programs/scmpuff/fish.nix
tests/modules/programs/scmpuff/no-bash.nix
tests/modules/programs/scmpuff/no-fish.nix
tests/modules/programs/scmpuff/no-shell.nix
tests/modules/programs/scmpuff/no-zsh.nix
tests/modules/programs/scmpuff/zsh.nix

Stub the scmpuff package. Also remove unnecessary `config` wrapping.
```
```

scmpuff: clean up tests

---

modules/services/xsuspender.nix

It's G\_MESSAGE**S**\_DEBUG, not "G_MESSAGE_DEBUG".
```
```

xsuspender: fix typo that made debug option a noop

---

modules/programs/vscode.nix

Add `extensions.json` file in `.share/vscode/extensions`. This allows extensions to be used with vscode 1.74.1. See #3507.
I haven't thoroughly tested behaviour with `mutableExtensionsDir = false`.
```
```

vscode: add extensions.json file in extensions dir

---

modules/programs/vscode.nix

I made an error in my previous PR and didn't test it, meaning it didn't have the functionality it was supposed to. This fixes that error.
```
```

vscode: fix erroneous application of lib.optional

---

modules/programs/mbsync.nix
tests/modules/programs/mbsync/mbsync-expected.conf

Reverts nix-community/home-manager#3630
See https://github.com/nix-community/home-manager/issues/3650, https://github.com/nix-community/home-manager/commit/e2c1756e3ae001ca8696912016dd31cb1503ccf3#commitcomment-99863177

Revert "mbsync: make passwordCommand escaping consistent"

---

tests/default.nix

One of the lines in the file was indented using a hard tab instead of a space.
```
```

tests: fix formatting (tab -> spaces)

---

modules/programs/keychain.nix

There is [no equivalent](https://www.nushell.sh/book/thinking_in_nu.html#think-of-nushell-as-a-compiled-language) of `eval` in nushell. Instead, this commit parses the output of keychain and pipes it directly into `load-env`, inspired by the recommendation for [`ssh-agent`](https://www.nushell.sh/cookbook/misc.html#manage-ssh-passphrases).
I also haven't set the `SHELL` variable as I don't see why? `keychain` only seems to [check](https://github.com/funtoo/keychain/blob/master/keychain.sh#L437-L439) for `fish` and `csh`.
I've tested the functionality of this commit on my own computer and it works.
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information …

keychain: add nushell integration

---

tests/modules/programs/gpg/mutable-keyfiles.nix
tests/modules/services/gpg-agent/default-homedir.nix
tests/modules/services/gpg-agent/override-homedir.nix

The gpg-agent tests fail to eval: https://github.com/nix-community/home-manager/actions/runs/4213809304/jobs/7316649158
systemd now depends on `gnupg.override`, so we need a stub for systemd too.
This is a quick workaround to fix the tests, not a long-term solution. Ideas:
- use the old package as a base instead of a dummy package so that we keep its `override`. This causes evaluation problems with unfree packages like `dropbox`.
- add an `override` (and `overrideAttrs`?) to the dummy package.
- add stubs for *all* packages by default, and only whitelist the ones that are needed for evaluation (?)

tests: fix gnupg stub

---

modules/programs/zsh/prezto.nix

prezto: fix bug preventing prompt.showReturnVal from evaluating

---

modules/services/owncloud-client.nix

Add a `package` option to `services.owncloud-client` module.
```
```

Add a package option to services.owncloud-client

---

modules/programs/direnv.nix

direnv: nushell integration should not be read only

---

modules/misc/qt.nix
tests/modules/misc/qt/qt-platform-theme-gnome.nix

Auto-detect style package from style name. Fixes https://github.com/nix-community/home-manager/issues/3691
```
```

qt: auto-detect style package from name

---

.github/CODEOWNERS
modules/misc/news.nix
modules/modules.nix
modules/services/mpd-mpris.nix
tests/default.nix
tests/modules/services/mpd-mpris/configuration-basic.nix
tests/modules/services/mpd-mpris/configuration-basic.service
tests/modules/services/mpd-mpris/configuration-with-local-mpd.nix
tests/modules/services/mpd-mpris/configuration-with-local-mpd.service
tests/modules/services/mpd-mpris/configuration-with-password.nix
tests/modules/services/mpd-mpris/configuration-with-password.service
tests/modules/services/mpd-mpris/default.nix

Adds a module for [mpd-mpris](https://github.com/natsukagami/mpd-mpris).
```
```

mpd-mpris: init

---

modules/launchd/default.nix

The example given for StartCalendarInterval doesn't work because this option expects a list of attribute sets, not a single attribute set.
```
```

launchd: fix example of StartCalendarInterval

---

modules/programs/firefox.nix
tests/modules/programs/firefox/profile-settings-expected-search-without-default.json
tests/modules/programs/firefox/profile-settings.nix

Fixes a bug where you couldn't define firefox search engine settings without a default engine specified.
Fixes #3569
```
```

firefox: fix search options without a default engine

---

modules/programs/starship.nix

Some enable options were not using `mkEnableOption`. This PR corrects this.
```
```

starship: Use mkEnableOption

---

tests/modules/programs/gpg/mutable-keyfiles.nix
tests/modules/services/gpg-agent/default-homedir.nix
tests/modules/services/gpg-agent/override-homedir.nix

Backport https://github.com/nix-community/home-manager/pull/3685
```
```

[backport 22.11] tests: fix gnupg stub

---

tests/modules/programs/broot/broot.nix
tests/modules/programs/i3status-rust/with-custom.nix
tests/modules/programs/i3status-rust/with-default.nix
tests/modules/programs/i3status-rust/with-extra-settings.nix
tests/modules/programs/i3status-rust/with-multiple-bars.nix

Make tests green again.
```
```

Fix 22.11 tests

---

modules/programs/gpg.nix

The [document that is previously linked encourages to refer to the respective manpage that came with the package](https://gnupg.org/documentation/manpage.html) so I replace the references of the web version with the manpages.
```
```
This is only an update on the module option description so I didn't test the modules and only built the documents (e.g., `nix-build -A docs.html`, `nix-build -A docs.manPages`) to see how it looks.

programs.gpg: update references to respective manpages

---

docs/installation.adoc
docs/nix-flakes.adoc
flake.nix
home-manager/home-manager

A collection of quick (individually unrelated changes):
- docs: slight improvement of Flake documentation
- flake: avoid recursive set
- home-manager: make `--version` report 23.05-pre. It is a bit misleading to report 22.11 when running from the master branch.
```
```

Various minor improvements

---

modules/programs/keychain.nix

Xsession (and hence ~/.xsession) is executed in bash but does not set SHELL to the full path to bash. In case the user's login shell is something other than bash then SHELL is set to that shell. Keychain inspects the SHELL variable to find out what shell it has to generate code for, so in .xsession it generates code for the user's login shell instead for bash.
This change forces SHELL to bash for keychain when invoked from .xsession, the same way it's done when generating keychain's code for bash integration.
Closes #3693
```
``` …

Set the SHELL environment variable for keychain in .xsession

---

modules/programs/git.nix

The `-X` prevents that screen is cleared when showing a diff that's
larger than my screen.
I.e. when running `git diff` and press `q`, the last thing I want to see
is the prompt with `git diff` and *not* the part of the diff I browsed,
to be clear
$ git diff
$ <cursor>
Considering that this is somewhat opinionated, I decided to build an
option which allows you to pass arbitrary commands to the less
invocation.
cc @rycee 
```
```

modules/git: make options passed to `less(1)` for `diff-so-fancy` configurable

---

modules/services/redshift-gammastep/lib/options.nix

This is needed to make sure that the tray icon is actually found. Otherwise an empty icon indicating that it wasn't found is shown.
```
```

modules/redshift-gammastep: install package into the profile

---

modules/programs/aerc-accounts.nix

Update aerc account auth mechanisms. Add oauthbearer and xoauth2 as supported auth mechanisms.

aerc: update auth mechanisms

---

modules/programs/exa.nix

This PR adds more configuration options for the `exa` module.
```
```

`exa`: add more options

---

.github/workflows/github_pages.yml
.github/workflows/test.yml
.github/workflows/update-flake.yml

2.14 has a bug related to profile locations that breaks nix-env, which in turn breaks cachix. Pin to 2.13 for now.
More info at https://github.com/NixOS/nixpkgs/pull/218858#issuecomment-1448758169

.github: pin nix 2.13 in workflows

---

modules/misc/specialization.nix

If used inside the NixOS/nix-darwin module, we get conflicting definitions of `name` inside the specialization: one is the user name coming from the NixOS module definition and the other is `configuration`, the name of this option. Thus we need to explicitly wire the former into the module arguments.
Fixes https://github.com/nix-community/home-manager/issues/3716
```
```

specialization: fix `name` conflict inside NixOS module

---

modules/programs/exa.nix

Otherwise the `icons`, `git` and `extraOptions` options have no effect unless `enableAliases` is true.
```
```

exa: always configure `exa` alias

---

.github/workflows/github_pages.yml
.github/workflows/test.yml
.github/workflows/update-flake.yml

cherry picked from commit 9438e56a7b7df5e02091027dccdd8d86768f1a2d
See #3720.
```
```
cc @ncfavier

[backport #3720] .github: pin nix 2.13 in workflows

---

modules/programs/neovim.nix
tests/modules/programs/neovim/default.nix
tests/modules/programs/neovim/extra-lua-init.nix

cherry picked from commit 9621e9ab80a038cd11c7cfcae4df46a59d62b16a
See #3639.
```
```
cc @GuillaumeDesforges

[backport #3639] programs.neovim: add extraLuaConfig

---

modules/services/mako.nix

Renamed `programs.mako` to `services.mako`
```
```

mako: programs.mako -> services.mako

---

modules/programs/git.nix

Before [this commit](https://github.com/nix-community/home-manager/commit/140aaed3dffbe33bb8b2e0cf333c67f36765c85e), tag signing wasn’t automatically enabled with `signing.signByDefault`. It’s now automatically enabled, which forces you to always use annotated tags (it seems like there’s no flag to tell git to use a lightweight tag).
This commit only sets tag and commit signing as defaults, allowing you to override them.
Unfortunately I wasn’t able to run the tests, the test command gave me the following error:
```
error: builder for '/nix/store/v8ny0pzdm47lsl8xxk3rnqa86mrv49j3-default-conf.json.drv' failed with exit code 1;
last 10 log lines:
> Traceback (most recent call last):
>   File "/nix/store/xpwwghl72bb7f48m51amvqiv1l25pa01-python3-3.9.13/lib/python3.9/runpy.py", line 197, in …
```

git: allow tags to be unsigned when signing.signByDefault=true

---

modules/programs/git.nix

(cherry picked from commit d331cceec7cc05061a3c6073eee06c4dba9cf5d3)
Backport https://github.com/nix-community/home-manager/pull/3479
```
```

[backport 22.11] gpg: allow unsigned tags

---

modules/services/recoll.nix
tests/modules/services/recoll/basic-configuration.conf
tests/modules/services/recoll/basic-configuration.nix
tests/modules/services/recoll/config-format-order.conf

The updated implementation will quote string lists as per the description at
https://www.lesbonscomptes.com/recoll/usermanual/#RCL.INSTALL.CONFIG
Fixes #3732
```
```

recoll: fix generation of string lists

---

modules/services/mpd.nix
tests/modules/services/mpd/basic-configuration.nix
tests/modules/services/mpd/basic-configuration.service
tests/modules/services/mpd/before-state-version-22_11.nix
tests/modules/services/mpd/xdg-music-dir.nix

Allow passing arguments to the MPD command line. Currently the only interesting one is `--verbose`.
```
```

mpd: add `extraArgs`

---

modules/misc/xfconf.nix

fix https://github.com/nix-community/home-manager/pull/3378#issuecomment-1368015573
ref: https://github.com/nix-community/home-manager/blob/693d76eeb84124cc3110793ff127aeab3832f95c/modules/misc/dconf.nix#L102-L106
output:
```
Feb 26 23:58:53 laptop hm-activate-cgq[1076]: Activating xfconfSettings
Feb 26 23:58:53 laptop hm-activate-cgq[1455]: dbus-daemon[1455]: [session uid=1000 pid=1455] Activating service name='org.xfce.Xfconf' requested by ':1.0' (uid=1000 pid=1458 com>
Feb 26 23:58:53 laptop hm-activate-cgq[1455]: dbus-daemon[1455]: [session uid=1000 pid=1455] Successfully activated service 'org.xfce.Xfconf'
Feb 26 23:58:53 laptop xfconfd[1465]: Name org.xfce.Xfconf lost on the message dbus, exiting.
Feb 26 23:58:53 laptop systemd[1]: Finished Home Manager environment for cgq.
```
``` …
```

xfconf: fix dbus may not be started in the startup of NixOS.

---

docs/nix-flakes.adoc

- install home-manager via `nix run` rather than `nix-build` then running the activation script out of the store manually
- suggest simply using `home-manager switch` when the configuration lives in `~/.config/nixpkgs`
The flake setup was needlessly complicated and a bit overwhelming for beginners whom home-manager might be their entry point in the world of Nix.

docs: simplify flake-specific instructions in the documentation

---

modules/programs/git.nix

Backport https://github.com/nix-community/home-manager/pull/3704
```
```

[backport 22.11] modules/git: make options passed to `less(1)` for `diff-so-fancy` configurable

---

modules/programs/starship.nix

Backport #3347, #3519, #3528, #3701 to `release-22.11`.
```
```

[Backport release-22.11] starship: add nushell integration #3701

---

.github/CODEOWNERS
modules/lib/default.nix
modules/lib/generators.nix
modules/programs/zellij.nix
tests/default.nix
tests/lib/generators/default.nix
tests/lib/generators/tokdl-result.txt
tests/lib/generators/tokdl.nix

Added a generator for the KDL document language.
This is in order for home-manager to natively generate the new config format for zellij, as described in #3364.
There is not a one to one mapping between KDL and nix types, but I've used KDLs JSON-IN-KDL syntax to translate attrsets.
Closes #3364 
```
```

lib, zellij: move zellij configuration to the new KDL format

---

modules/programs/zellij.nix

Fixes a typo in the `programs.zellij` module:
`versionAtleast` -> `versionAtLeast`
```
```

zellij: fix typo

---

modules/programs/home-manager.nix

Just make a note that the home-manager channel will be attempted when trying to find a Home Manager repo.
```
```

home-manager: slightly expand option description

---

modules/programs/kitty.nix

The theme files were moved to `share/kitty-themes` in nixos/nixpkgs#220872.
```
```

Fix path to Kitty theme files

---

modules/programs/vscode.nix
tests/modules/programs/vscode/default.nix
tests/modules/programs/vscode/snippets.nix

Add options to vscode module for defining global and language specific user snippets.
```
```

vscode: add options for global and user snippets

---

docs/faq.adoc
docs/man-configuration.xml
docs/man-home-manager.xml
docs/nix-flakes.adoc
docs/release-notes/rl-2305.adoc
docs/usage.adoc
home-manager/home-manager
home-manager/install.nix
home-manager/po/home-manager.pot
modules/po/hm-modules.pot

This changes the default configuration location for Home Manager configurations from
$XDG_CONFIG_HOME/nixpkgs
to
$XDG_CONFIG_HOME/home-manager
The old location is still supported but using it will trigger a warning message.
I also included a few minor unrelated changes.
Fixes #3640
```
```

New default configuration home

---

modules/programs/atuin.nix
tests/modules/programs/atuin/bash.nix
tests/modules/programs/atuin/default.nix
tests/modules/programs/atuin/fish.nix
tests/modules/programs/atuin/set-flags.nix
tests/modules/programs/atuin/zsh.nix

atuin: add disable key options

---

modules/programs/qutebrowser.nix
tests/modules/programs/qutebrowser/keybindings.nix

This command adds the ability to specify lists of qutebrowser commands as values for key bindings,
which avoids the need for concatenating commands with ` ;; `.
```
```

qutebrowser: allow for specifying multiple commands in bindings

---

modules/config/home-cursor.nix

The `XCURSOR_*` environment variables specified in libxcursor
are used by many applications and libraries to load and configure
cursor settings. Setting these variables is a no-op if ignored but
is useful as a fallback when other sources of configuration are
unreliable.
This commit sets some commonly used `XCURSOR_*` environment variables
(i.e XCURSOR_THEME, XCURSOR_SIZE) by default when `home.pointerCursor`
is enabled.
Fixes https://github.com/nix-community/home-manager/issues/3645
```
```
- If this PR …

home.pointerCursor: set common XCURSOR_* environment variables by default

---

.github/CODEOWNERS
modules/misc/news.nix
modules/programs/i3status-rust.nix
tests/modules/programs/i3status-rust/default.nix
tests/modules/programs/i3status-rust/with-custom.nix
tests/modules/programs/i3status-rust/with-default.nix
tests/modules/programs/i3status-rust/with-extra-settings.nix
tests/modules/programs/i3status-rust/with-multiple-bars.nix
tests/modules/programs/i3status-rust/with-version-02xx.nix

0.30.0 is a major release that brings many breaking changes to the configuration file. See:
https://github.com/greshake/i3status-rust/blob/master/NEWS.md#i3status-rust-0300
The only one that actually affects the module though is the change in how the theme/icons are defined. Other changes are mostly on how to specify formatting/blocks, and since we just generate the TOML as-is, it needs changes in the user side.
So most changes in this commit are documentation updates, having up-to-date examples from things that changed, e.g.: the new `click` attribute that now can be applied to any block.
Fixes #3771.
Related nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/217546
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/m …

i3status-rust: update it to handle 0.30.x releases

---

modules/programs/starship.nix

Older versions are not supported, see https://github.com/nix-community/home-manager/pull/3697#issuecomment-1473739415, https://starship.rs/#nushell
```
```

starship: condition nushell integration on nushell 0.73+

---

modules/programs/starship.nix

Backporting https://github.com/nix-community/home-manager/pull/3776
```
```

[backport 22.11] starship: condition nushell integration on nushell 0.73+

---

.github/workflows/github_pages.yml
.github/workflows/test.yml
.github/workflows/update-flake.yml

The new release addresses the issue with Nix 2.14. Previously: https://github.com/nix-community/home-manager/pull/3720
https://github.com/cachix/install-nix-action/releases/tag/v20

.github: bump install-nix-action

---

home-manager/home-manager

This adds a few commented example configuration elements to help guide the user to possible usages.
```
```

home-manager: make generated home.nix more helpful

---

docs/3rd-party.adoc

-------
Reference [Stylix](https://github.com/danth/stylix/) in `docs/3rd-party.adoc`.

docs: reference Stylix in 3rd-party extensions

---

modules/programs/borgmatic.nix
tests/modules/programs/borgmatic/default.nix
tests/modules/programs/borgmatic/exclude-hm-symlinks-nothing-else.nix
tests/modules/programs/borgmatic/exclude-hm-symlinks.nix
tests/modules/programs/borgmatic/include-hm-symlinks.nix

-------
Make it easy to generate a borgmatic's exclusion list containing all
symlinks generated by home manager.
```
```

borgmatic: Optionally exclude home-manager symlinks from backup

---

.github/CODEOWNERS
modules/programs/mpv.nix
tests/modules/programs/mpv/default.nix
tests/modules/programs/mpv/mpv-example-settings-expected-osc-opts
tests/modules/programs/mpv/mpv-example-settings.nix
tests/modules/programs/mpv/mpv-invalid-settings.nix

Manage mpv script-opts files declaratively.
```
```

mpv: add scriptOpts option, fix tests

---

.github/CODEOWNERS
modules/misc/news.nix
modules/modules.nix
modules/services/listenbrainz-mpd.nix

Adds a simple service to configure [listenbrainz-mpd](https://codeberg.org/elomatreb/listenbrainz-mpd).
```
```

listenbrainz-mpd: add module

---

modules/programs/zathura.nix

As [this comment](https://github.com/nix-community/home-manager/pull/3134#issuecomment-1475944069) points out, the current zathura module does not support mode-specific mappings.
This PR allows the user to provide for a mapping an attrs that contains both the action and the mode.
Of course, the user can still provide a simple string which ensures backward compatibility.
```
```

zathura: add documentation for mode-specific mappings

---

modules/accounts/email.nix
modules/programs/alot.nix

Some of the email providers (like GMail and Fastmail) save Sent messages
automatically, so make the folders optional in the configuration.
Make Drafts folder optional as well, to allow it to be configured
manually in the extraConf with location outside of the maildir.

programs/alot: make Sent and Drafts folder optional

---

tests/modules/programs/gpg/immutable-keyfiles.nix

gpg: fix URL of key in test case

---

modules/programs/zoxide.nix

Add zoxide nushell integration.
```
```

zoxide: enable nushell integration

---

.github/CODEOWNERS
modules/lib/maintainers.nix
modules/misc/news.nix
modules/modules.nix
modules/programs/hstr.nix

This adds options to configure hstr. bash and zsh shell history suggest box - easily view, navigate, search and manage your command history.
```
```

hstr: hstr module added

---

home-manager/home-manager

Showing news is not yet supported in flake setups.
```
```

home-manager: error out when showing news in flake

---

modules/launchd/launchd.nix
tests/modules/launchd/agents.nix
tests/modules/launchd/expected-agent.plist

This includes 2 changes:
1. Make Launch Agents config a freeform setting so that Home Manager can process options that aren't listed in the option definition
2. Sync the option definition for Launch Agents with nix-darwin
```
```

launchd: update option definition

---

modules/misc/nixpkgs.nix

tried to copy paste the example overlay from the docs, there seems to be an additional `;`. Also adapted function parameters to reflect new guidelines and layout to be more "list" like
```
```

nixpkgs: fix semicolon and list layout in docs

---

modules/services/copyq.nix

copyq: Add QT_QPA_PLATFORM=xcb to service environment (#3530)

---

modules/misc/dconf.nix

This disables the dconf module on darwin, since it always fails to activate as
dbus is unavailable there.
```
```

dconf: disable on darwin

---

modules/services/pass-secret-service.nix

Renamed in nixpkgs https://github.com/NixOS/nixpkgs/pull/223976, so now our tests are [failing](https://github.com/nix-community/home-manager/actions/runs/4599709875/jobs/8125413653?pr=3837#step:6:7)... @rycee we need to find a way to avoid that, but I'm not sure how.
cc @cyntheticfox 
```
```

maintainers: rename houstdav000 → cyntheticfox

---

modules/programs/man.nix

man: use cfg when possible

---

.github/workflows/test.yml
tests/modules/programs/broot/broot.nix

The workflow used the wrong channel before.
```
```

ci: use the right channel

---

modules/misc/xdg-desktop-entries.nix
tests/modules/misc/xdg/desktop-entries.nix
tests/modules/misc/xdg/desktop-min-expected.desktop

The [specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html) does not require those keys to be set, and the type reflects that, so they should default to null.
Remove a dead binding.
Fixes https://github.com/nix-community/home-manager/issues/3825
```
```

xdg-desktop-entries: make `exec` default to null

---

home-manager/home-manager
home-manager/po/home-manager.pot
modules/lib-bash/activation-init.sh
modules/po/hm-modules.pot

If the user runs a recent Nix version that places per-user profiles in `$XDG_STATE_DIR/nix/profiles`, then migrate the home-manager profile there.
Also clean up `setupVars` a bit.
```
```

home-manager: migrate profiles to Nix state directory

---

modules/config/home-cursor.nix

Currently, the `home.pointerCursor` module creates a file in the `~/.icons/` folder.
~~According to the [XDG spec for _Icon Theme Specification_](https://www.freedesktop.org/wiki/Specifications/icon-theme-spec/), it seems that [this folder can be located in one of the `$XDG_DATA_DIRS` folders](https://specifications.freedesktop.org/icon-theme-spec/latest/ar01s03.html).~~
This PR moves the `icons/` folder to this location.
EDIT:  According to [the Arch wiki](https://wiki.archlinux.org/title/Cursor_themes#Manually) and my testing, it seems to work better when using `$XDG_DATA_HOME/icons/`.
Maybe it is better to put it in both places.
For information, the implementation of `$XDG_DATA_DIRS` is the following:
```nix
xdg.systemDirs.data = [
(toString (pkgs.writeTextDir …
```

home-cursor: follow xdg spec for icons folder

---

modules/lib-bash/activation-init.sh

The Nix profiles path may not exist right after installing Nix. In that case, it is created on demand by the Nix CLI tools. But after #3861, Home Manager assumes it exists and fails if it doesn't. This caused problems when testing Home Manager configurations on GitHub Actions and cachix/install-nix-action was used to install Nix.
This change makes sure to trigger the creation of the Nix profiles path before attempting to access it.
```
```

activation-init.sh: create the Nix profiles path before accessing it

---

modules/programs/swaylock.nix
tests/modules/programs/swaylock/default.nix
tests/modules/programs/swaylock/enabled.nix
tests/modules/programs/swaylock/legacy.nix
tests/modules/services/git-sync/basic.nix

Signed-off-by: Paul Meyer <49727155+katexochen@users.noreply.github.com>
Adding `enable` and `package` options to the swaylock module. 
:warning: These changes are not fully backwards compatible, as the config file from `settings` won't be written if enable isn't set. We could write the settings file when non-empty even if the module isn't enabled to retain backwards compatibility, but I couldn't find another module that does this, so I didn't implement it for now.
```
```

swaylock: add enable and package option

---

home-manager/home-manager

home-manager: ignore errors from notify-send

---

modules/services/window-managers/i3-sway/lib/functions.nix
modules/services/window-managers/i3-sway/lib/options.nix

Add option trayPadding (tray_padding) for bars.
Didn't find an example if I should create a test-case if there is no change in default behavior as we don't test them currently from what I found?
```
```

i3-sway: add option trayPadding (tray_padding) for bars

---

modules/services/copyq.nix

Fix typo in documentation for `services.copyq.systemdTarget`.
```
```

copyq: fix typo in documentation

---

docs/contributing.adoc

The link to the Nix RFC 42 is invalid. Replace this with a valid link to the upstream NixOS/rfcs repo, pinning it to the commit that introduced the RFC.
The link to the Nix RFC 42 is invalid and yields a 404. This fixes that issue.
```
```

doc: replace invalid link

---

modules/programs/lazygit.nix

Use `xdg.configHome` if `xdg.enable` is true, like most other tools on darwin.
Lazygit supports XDG path if XDG_CONFIG_HOME is defined: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
Fixes #3634.
```
```

lazygit: use xdg.configHome on darwin too if xdg.enable

---

modules/programs/bottom.nix
tests/modules/programs/bottom/empty-settings.nix
tests/modules/programs/bottom/example-settings.nix

Use `xdg.configHome` like most other tools on darwin.
Bottom supports both config locations: https://clementtsang.github.io/bottom/nightly/configuration/config-file/default-config/
```
```

bottom: use xdg.configHome on darwin too

---

modules/programs/nushell.nix
tests/modules/programs/nushell/config-expected.nu
tests/modules/programs/nushell/example-settings.nix

This PR adds a `programs.nushell.shellAliases` option to allow nushell users to define shell aliases which are inserted into nushell's config.nu. It also integrates it with the general `home.shellAliases` configuration option, similar to bash/zsh/fish.
Closes #3525
```
```

nushell: Add shellAliases option

---

modules/programs/atuin.nix

The latest atuin supports nushell now, this just adds the option to handle it.
nixpkgs has just merged the latest atuin on master, so we might need to wait until the change gets reflected to nixpkgs-unstable. Happy to leave this open in the meanwhile for review.
```
```

atuin: enable nushell integration

---

modules/programs/rofi.nix

Avoid needless calls to `override` (also allows using `pkgs.rofi-unwrapped` with no plugins).
```
```

rofi: skip override if there are no plugins

---

modules/programs/firefox.nix

This commit adds a clear example of how to get bookmarks into the bookmarks toolbar.

docs: add `toolbar` to firefox bookmarks example

---

.github/CODEOWNERS
modules/lib/maintainers.nix
modules/misc/news.nix
modules/modules.nix
modules/programs/mr.nix

This adds options to configure `mr` (aka myrepos), a tool to manage all your version control repos.
```
```
NOTE: sorry I screwed up last pr #3518

myrepos: add module

---

home-manager/home-manager

During a recent installation I was receiving the error:
```
error: flake 'git+file:///home/paulo.casaretto/.config/home-manager' does not provide attribute 'packages.x86_64-linux.homeConfigurations."paulo.casaretto".activationPackage', 'legacyPackages.x86_64-linux.homeConfigurations."paulo.casaretto".activationPackage' or 'homeConfigurations."paulo.casaretto".activationPackage'
```
Upon inspection it became clear that this line was the culprit:
```
homeConfigurations.paulo.casaretto = home-manager.lib.homeManagerConfiguration {
```
Changing to 
```
homeConfigurations."paulo.casaretto" = home-manager.lib.homeManagerConfiguration {
```
Fixed the problem.

Fix flake install template to account for usernames with "."

---

home-manager/home-manager

Fixes #3900 
Since the `set -u` option turned on, the `home-manager` script errors and exits when trying to expand `$configFile` when no config file is found and the variable is unset. Instead, use `[[ -v configFile ]]` which tests if variable is unset without causing a fatal error in case it is not.
```
```

home-manager: fix config file variable check

---

modules/programs/zellij.nix

Use `xdg.configHome` like most other tools on darwin.
Zellij supports both config locations: https://zellij.dev/documentation/configuration.html#where-does-zellij-look-for-the-config-file
```
```

zellij: use xdg.configHome on darwin too

---

modules/services/window-managers/herbstluftwm.nix
tests/modules/services/window-managers/herbstluftwm/herbstluftwm-simple-config-autostart

The previous implementation tried to rename the tag named "default" to the first tag in `cfg.tags`. This was a wrong approach because if a tag with the same name already existed, the renaming failed and the default tag would continue to exist.
The looking up of the default tag also contained a bug (introduced in #3509) because it should have used `by-name` in the path.
```
```

herbstluftwm: Fix default tag renaming

---

modules/services/fnott.nix
tests/modules/services/fnott/systemd-user-dbus-service-expected.service
tests/modules/services/fnott/systemd-user-service.nix

This is needed to make fnott bus-activatable. Otherwise it won't be started when a bus request is made [0].
Done in the same way as e.g. dunst sets that up [1,2].
Fixes notifications through fnott on my machine.
Tested using a simple `nix-shell -p libnotify --run 'notify-send test'`.
[0] https://www.freedesktop.org/software/systemd/man/systemd.service.html#id-1.10.6
[1] https://github.com/nix-community/home-manager/blob/master/modules/services/dunst.nix#L139
[2] https://github.com/dunst-project/dunst/blob/master/org.knopwob.dunst.service.in
```
``` …

fnott: add DBus service file

---

modules/programs/zsh.nix

Adds a `package` option to `programs.zsh.oh-my-zsh`, which allows omz to be overridden with a custom package. My motivation was being able to use `pkgs.unstable.oh-my-zsh` with it, without doing so via another overlay.
This is my first small contribution to the nix ecosystem, and I'm unsure how I would add tests for this, since I couldn't find existing tests for `programs.zsh.oh-my-zsh`.
Maybe the same option should also be added to `programs.zsh.prezto`?
```
```

zsh: add `package` option to `oh-my-zsh`

---

tests/default.nix

Checked on Apple Silicon laptop with both `aarch64-darwin` and `x86-64-darwin`. All tests succeeded on both.
```
```

neovim: Enable tests on Darwin

---

modules/services/window-managers/i3-sway/sway.nix
tests/modules/services/window-managers/sway/sway-bar-focused-colors.conf
tests/modules/services/window-managers/sway/sway-bindkeys-to-code-and-extra-config.conf
tests/modules/services/window-managers/sway/sway-default.conf
tests/modules/services/window-managers/sway/sway-followmouse-expected.conf
tests/modules/services/window-managers/sway/sway-followmouse-legacy-expected.conf
tests/modules/services/window-managers/sway/sway-modules.conf
tests/modules/services/window-managers/sway/sway-null-package.conf
tests/modules/services/window-managers/sway/sway-workspace-default-expected.conf
tests/modules/services/window-managers/sway/sway-workspace-output-expected.conf

Without this, even if you configure a preference for Electron apps to
use Ozone by setting `NIXOS_OZONE_WL=1`, GUI apps launched through
systemd user services use XWayland, since the envvar is not set in their
environment.
This fixes that issue by importing it, like we do other vars.
```
```

sway: import NIXOS_OZONE_WL environment variable into systemd

---

flake.nix

I assume it was erroneously lost during flake-utils removal in https://github.com/nix-community/home-manager/pull/3860
```
```

flake: Move tests back to devShells.*.tests

---

modules/programs/neomutt-accounts.nix
modules/programs/neomutt.nix
modules/programs/notmuch-virtual-mailbox.nix
tests/modules/programs/neomutt/hm-example.com-expected
tests/modules/programs/neomutt/hm-example.com-signature-command-expected
tests/modules/programs/neomutt/hm-example.com-signature-expected

This enables the arbitrary control of Notmuch virtual mailboxes in NeoMutt, which was impossible before without extraConfig and tedious manipulations.
Plus, it makes it now possible to have Notmuch and remove "My INBOX" from NeoMutt.
```
```

notmuch & neomutt: Control virtualboxes being set in NeoMutt for Notmuch integration

---

modules/programs/atuin.nix

The nushell integration for atuin was not using the `flags` option. 
```
```

atuin: Use flags option with nushell integration

---

nixos/common.nix

This allows users to pass a lib with custom attributes and have those available to custom HM modules.
EDIT: marked as draft since it doesn't work and I was testing wrong.
```
```

nixos: use `lib` argument instead of `pkgs.lib`

---

flake.nix

This reverts commit 6f9781b1b0cf3fedbe9d2d0a785aeec4d6085c10 to fix errors of `nix flake check` and `nix flake show`. `devShells` expects an attrset of derivations, not nested attrsets.
This also breaks [nil](https://github.com/oxalica/nil)'s flake evaluation with `nix flake show`.
See also https://github.com/nix-community/home-manager/pull/3905#issuecomment-1521259152
```
```

Revert "flake: Move tests back to devShells.*.tests (#3905)"

---

.github/CODEOWNERS
modules/misc/news.nix
modules/modules.nix
modules/programs/jujutsu.nix
tests/default.nix
tests/modules/programs/jujutsu/default.nix
tests/modules/programs/jujutsu/empty-config.nix
tests/modules/programs/jujutsu/example-config.nix

Adding Jujutsu with config and completions.
```
```

Add Jujutsu

---

modules/programs/zplug.nix
tests/modules/programs/zplug/modules.nix

The current zplug nixpkgs puts everything under `$out/`. It pollutes the nix
profile dir.
This is a breaking change. It depends on an change of the output path in the
nixpkgs zplug package.
Please see https://github.com/nix-community/home-manager/pull/3916 for the reason that we decided to go with a breaking change, and the alternative we considered there. @ncfavier FYI I create a new PR here as I failed to get Github branch rename work for the old PR.
```
```

zplug: Update the path of init.zsh

---

modules/programs/zsh.nix
tests/modules/programs/zsh/default.nix
tests/modules/programs/zsh/history-substring-search.nix

It's pretty common to need multiple bindings to
history-substring-search, since different terminals will send different
keys for up/down.
This does not break back-compatibility, and introduces a new test
```
```

zsh: allow multiple bindings to history-substring-search

---

modules/programs/i3status-rust.nix
tests/modules/programs/i3status-rust/with-custom.nix
tests/modules/programs/i3status-rust/with-default.nix
tests/modules/programs/i3status-rust/with-extra-settings.nix
tests/modules/programs/i3status-rust/with-multiple-bars.nix
tests/modules/programs/i3status-rust/with-version-02xx.nix

From the [0.31.0 news](https://github.com/greshake/i3status-rust/blob/49499c1ca624228c4b9e88b62b36cd0fa5e2dce5/NEWS.md#i3status-rust-0310):
> `block = "..."` is now required to be the first field of block configs.
The approach taken here normalizes numbers like `10.0` to `10`, but I think this should be inconsequential.
```
```

i3status-rust: satisfy new 0.31 TOML output requirements

---

modules/programs/nushell.nix
tests/modules/programs/nushell/env-expected.nu
tests/modules/programs/nushell/example-settings.nix

Much like what was done with shellAliases, I wanted a convenient way to set environment variables.
Admittedly that can be done in extraEnv. The one use case where this becomes very convenient is with the appearance of those CLI tools that require an API key in your env. That is env var should be a secret and ideally read from a path. This is just a more convenient way of having an env var be a string or read from a path.
```
```

nushell: add envVars attribute

---

modules/programs/helix.nix
tests/modules/programs/helix/example-settings.nix
tests/modules/programs/helix/settings-expected.toml

Helix changed the definition of options. E.g. editor specific options need to be prefixed with editor. This PR reflects this and also adds some more common settings. 
Tests failed with unrelated borgmatic test
```
```

helix: provide more detailed settings description

---

modules/programs/firefox.nix
tests/modules/programs/firefox/profile-settings-expected-bookmarks.html
tests/modules/programs/firefox/profile-settings.nix

Closes https://github.com/nix-community/home-manager/issues/3941
cc @kira-bruneau 
```
```

firefox: support bookmark tags

---

modules/misc/xfconf.nix

The xfconf module of home-manager can't distinguish between `int` and `uint`, all exported integer types in xml are `int`, e.g. the result of this module is `<property name="dpms-on-ac-sleep" type="int" value="15"/>`, while the correct config in xml should be `<property name="dpms-on-ac-sleep" type="uint" value="15"/>`.
Some xfconf consumers use `xfconf_channel_get_uint()` to get config, and this function discards values with wrong types, e.g. it will discard `15` from `<property name="dpms-on-ac-sleep" type="int" value="15"/>`.
change from
```
"xfce4-power-manager/dpms-on-ac-sleep" = 15;
```
to
```
"xfce4-power-manager/dpms-on-ac-sleep" = { type = "uint"; value = 15; };
```
```
```
See …

xfconf: support uint

---

flake.nix

This makes sure that a NIX_PATH entry is added for use by non-flake commands, for example `home-manager uninstall`.
Fixes #3948
Replaces #3949
```
```

flake: set source path in home-manager tool

---

docs/writing-modules.adoc
modules/misc/dconf.nix

Try to preempt a frequent pain point, most recently in https://discourse.nixos.org/t/dash-to-dock-does-not-respect-max-icon-size-when-set-with-dconf-settings-in-configuration-nix/27904.
```
```

dconf: Improve docs

---

modules/programs/i3status-rust.nix
tests/modules/programs/i3status-rust/default.nix
tests/modules/programs/i3status-rust/with-custom.nix
tests/modules/programs/i3status-rust/with-default.nix
tests/modules/programs/i3status-rust/with-extra-settings.nix
tests/modules/programs/i3status-rust/with-multiple-bars.nix
tests/modules/programs/i3status-rust/with-version-02xx.nix
tests/modules/programs/i3status-rust/with-version-0311.nix

See https://github.com/nix-community/home-manager/pull/3938#issuecomment-1532862992
https://github.com/NixOS/nixpkgs/pull/230355 has been merged, but it will still take a few days until it reaches the relevant channels.
```
```

i3status-rust: revert #3938

---

modules/misc/xfconf.nix

Submodules must come after strings, otherwise strings are treated as paths and implicitly imported.
Fixes https://github.com/nix-community/home-manager/issues/3960
```
```

xfconf: fix type order

---

modules/home-environment.nix

When `nix.settings.use-xdg-base-directories` is true, the `home.profileDirectory` should be updated so that the environment is sourced correctly.
Related: https://github.com/NixOS/nix/pull/5588.
```
```

home: fix profileDirectory if use-xdg-base-directories

---

modules/programs/atuin.nix

This PR simply replaces a dead link, which was to a documentation markdown file, which is now hosted properly elsewhere.
It would also be possible to link to the new md file, which would be in a different directory. https://github.com/ellie/atuin/blob/main/docs/docs/config/config.md would be the link for that
```
```

atuin: Replace dead link in documentation

---

.github/CODEOWNERS
modules/services/gnome-keyring.nix
modules/services/pass-secret-service.nix

Add the dbus service file in the package folder to XDG_DATA_HOME, as well as adding an assertion to ensure both it and `gnome-keyring` aren't enabled at the same time.
```
```

pass-secret-service: Add dbus file, assert

---

modules/xsession.nix
tests/modules/misc/xsession/basic-xprofile-expected.txt
tests/modules/misc/xsession/basic-xsession-expected.txt

The xsession module imports variables into the systemd user session, but does not clean up after itself once the session ends. This can lead to issues where a `DISPLAY` variable remains set for services while X is not available or running anymore.
In one particular case when using xresources, [it can cause unnecessary switch failures](https://github.com/nix-community/home-manager/blob/782cb855b2f23c485011a196c593e2d7e4fce746/modules/xresources.nix#L96).
```
```

xsession: cleanup systemd variables

---

modules/services/gnome-keyring.nix

gnome-keyring: fix pass-secret-service assertion

---

modules/programs/zsh.nix

Much like it is already available for many other modules, add it here too.
[ Also, I noticed there is no explicitly assigned maintainer/codeowner for the `zsh` module. I'd be willing to take over and actively maintain if that would be desired, as I'm using it since many years now and care about it. ] 
```
```

zsh: add `package` option

---

modules/services/emacs.nix
tests/modules/services/emacs/default.nix
tests/modules/services/emacs/emacs-service-28-after-graphical-session-target.nix
tests/modules/services/emacs/emacs-service-emacs-after-graphical-session-target.service

It's useful if you want emacs daemon to get some environment variables, e.g. ibus related variables when using Gnome.
```
```

emacs: extend startWithUserSession to start after graphical session

---

.github/CODEOWNERS
modules/programs/beets.nix
tests/default.nix
tests/modules/programs/beets/default.nix
tests/modules/programs/beets/mpdstats-expected.service
tests/modules/programs/beets/mpdstats-expected.yaml
tests/modules/programs/beets/mpdstats-external-expected.service
tests/modules/programs/beets/mpdstats-external-expected.yaml
tests/modules/programs/beets/mpdstats-external.nix
tests/modules/programs/beets/mpdstats.nix
tests/modules/programs/beets/mpdupdate-expected.yaml
tests/modules/programs/beets/mpdupdate.nix

Allow configuration of mpdstats and mpdupdate plugins for Beets using Home Manager.
```
```

beets: add mpdIntegration

---

modules/programs/taskwarrior.nix

Adds a `package` option to `taskwarrior` module.
This allows wrapping taskwarrior to have custom path for plugins.
```
```

taskwarrior: add package option

---

modules/services/window-managers/i3-sway/lib/functions.nix
tests/modules/services/window-managers/i3/i3-bar-focused-colors-expected.conf
tests/modules/services/window-managers/i3/i3-followmouse-expected.conf
tests/modules/services/window-managers/i3/i3-fonts-expected.conf
tests/modules/services/window-managers/i3/i3-keybindings-expected.conf
tests/modules/services/window-managers/i3/i3-workspace-default-expected.conf
tests/modules/services/window-managers/i3/i3-workspace-output-expected.conf
tests/modules/services/window-managers/sway/sway-bar-focused-colors.conf
tests/modules/services/window-managers/sway/sway-bindkeys-to-code-and-extra-config.conf
tests/modules/services/window-managers/sway/sway-default.conf
tests/modules/services/window-managers/sway/sway-modules.conf
tests/modules/services/window-managers/sway/sway-null-package.conf
tests/modules/services/window-managers/sway/sway-workspace-default-expected.conf
tests/modules/services/window-managers/sway/sway-workspace-output-expected.conf

The `indent` function unindents the first and last line by default, so the `"bar {"` `"}"` wrapper should go inside the list.
Replaces https://github.com/nix-community/home-manager/pull/3976
```
```

i3-sway: fix indentation of `bar` blocks

---

modules/programs/ssh.nix
tests/modules/programs/ssh/match-blocks-attrs-expected.conf
tests/modules/programs/ssh/match-blocks-attrs.nix

Add support for the `SetEnv` option in the `programs.ssh` module.
It allows to set environment variables and send them to the server.
```
```

ssh: add setEnv option

---

modules/systemd.nix
tests/modules/systemd/services.nix

Allow for values of type derivation to be used as values for systemd options. This allows for instance to assign the result of `pkgs.writeShellScript` to `ExecStart` directly, without needing to call `toString` every time.
It is also closer to what people might be used to from NixOS.
~~Note: I don't really like the formatting of having one `attrsOf` on a separate line, but the auto-formatter seems to insist on doing it that way...~~
```
```

systemd: accept derivations as values for systemd options

---

modules/programs/kitty.nix
tests/modules/programs/kitty/example-settings-expected.conf

Kitty provides integrations for bash, fish and zsh. The new programs.kitty.shellIntegration options allow the configuration of these integrations.
See https://sw.kovidgoyal.net/kitty/shell-integration for more details
```
```

kitty: add shellIntegration

---

modules/programs/zellij.nix
tests/modules/programs/zellij/enable-shells.nix

I added the shell integrations back in this PR: https://github.com/nix-community/home-manager/pull/3926
There was some early feedback suggesting that shell integrations shouldn't be enabled by default, so I'm opening this PR to make it more convenient for the maintainers to pivot to this options if desired.
```
```

zellij: disables shell integrations by default

---

.github/CODEOWNERS
modules/misc/news.nix
modules/modules.nix
modules/programs/fuzzel.nix
tests/default.nix
tests/modules/programs/fuzzel/default.nix
tests/modules/programs/fuzzel/empty-settings.nix
tests/modules/programs/fuzzel/example-settings-expected.ini
tests/modules/programs/fuzzel/example-settings.nix

[fuzzel](https://codeberg.org/dnkl/fuzzel) is a lightweight app launcher for Wayland.
This module adds a simple way to configure it using HM.
```
```

fuzzel: add module

---

modules/misc/news.nix
modules/programs/ssh.nix
tests/modules/programs/ssh/default-config.nix
tests/modules/programs/ssh/forwards-dynamic-bind-path-with-port-asserts.nix
tests/modules/programs/ssh/forwards-dynamic-valid-bind-no-asserts.nix
tests/modules/programs/ssh/forwards-local-bind-path-with-port-asserts.nix
tests/modules/programs/ssh/forwards-local-host-path-with-port-asserts.nix
tests/modules/programs/ssh/forwards-remote-bind-path-with-port-asserts.nix
tests/modules/programs/ssh/forwards-remote-host-path-with-port-asserts.nix
tests/modules/programs/ssh/includes.nix
tests/modules/programs/ssh/match-blocks-attrs.nix
tests/modules/programs/ssh/match-blocks-match-and-hosts.nix

Fixes: #3667
Add `programs.ssh.package` option and install the ssh client. It's not clear to me if this change is backwards-compatible or not, but at least we have something concrete to look at now.
```
```

ssh: install an ssh client

---

modules/programs/kitty.nix

Improve the error message in https://github.com/nix-community/home-manager/issues/3988
```
```

kitty: improve error message when theme not found

---

tests/default.nix

Updates nmt to latest revision that includes @ncfavier's [space leak fix and improved error reporting](https://git.sr.ht/~rycee/nmt/commit/4df00c569b1badfedffecd7ccd60f794550486db).
```
```

tests: bump nmt to latest

---

tests/modules/programs/neomutt/neomutt-with-binds-invalid-settings.nix

Fixes tests on Darwin where neomutt currently fails to build https://github.com/NixOS/nixpkgs/issues/232074

neomutt: add missing stub in test

---

.github/PULL_REQUEST_TEMPLATE.md
docs/contributing.adoc

Allows for running with the `nixpkgs` from the lock file, as well as using a more familiar interface for users of the experimental CLI, which would've avoided me opening #3971.
Also updates the corresponding note in `docs/contributing.adoc` to have the correct invocation path.
```
```

PR_TEMPLATE: Note nix3 test method in checklist

---

modules/programs/helix.nix
tests/modules/programs/helix/example-settings.nix
tests/modules/programs/helix/languages-expected.toml

Updates the generation of `languages.toml` by supporting every option in it with `programs.helix.languages`. This is a breaking change (which IMHO is justified, as it should be more future-proof).
It closes #3911 as well, as it achieves basically the same (support serializing `grammar` and `use-grammars`) with less code (but a breaking change as mentioned above).
But #2871 is not fixed by this, as this seems to be a little bit more tricky (see discussion in this issue).
Motivation for this is support for multiple language servers (https://github.com/helix-editor/helix/pull/2507)
I've included a comment in the example of this option, which I will remove once a new stable helix version is out (but this will likely take some time, as just a new version came out).
```
{component}: …
```

helix: update languages.toml generation (support every option in languages.toml)

---

home-manager/home-manager

Before this commit, running the hasFlakeSupport function causes an error message
error: experimental Nix feature 'nix-command' is disabled; use
'--extra-experimental-features nix-command' to override
when the Nix installation does not support the nix tool.
```
```

home-manager: fix spurious error message in flake check

---

modules/files.nix
modules/lib/file-type.nix
modules/misc/xdg.nix
modules/programs/neovim.nix

Currently they all point to `home.file`.
Fixes https://github.com/nix-community/home-manager/issues/4005
```
```

lib/file-type: fix xrefs

---

modules/programs/helix.nix

https://github.com/nix-community/home-manager/pull/4003#issuecomment-1564355930
The warning message for programs.helix.languages was unclear and did not specify the full path of the option. This commit changes the warning message to include the full path and make it easier for users to understand how to update their configuration.
```
```

helix: improve warning message for languages option

---

modules/misc/news.nix
modules/programs/ssh.nix
tests/modules/programs/ssh/default-config.nix
tests/modules/programs/ssh/forwards-dynamic-bind-path-with-port-asserts.nix
tests/modules/programs/ssh/forwards-dynamic-valid-bind-no-asserts.nix
tests/modules/programs/ssh/forwards-local-bind-path-with-port-asserts.nix
tests/modules/programs/ssh/forwards-local-host-path-with-port-asserts.nix
tests/modules/programs/ssh/forwards-remote-bind-path-with-port-asserts.nix
tests/modules/programs/ssh/forwards-remote-host-path-with-port-asserts.nix
tests/modules/programs/ssh/includes.nix
tests/modules/programs/ssh/match-blocks-attrs.nix
tests/modules/programs/ssh/match-blocks-match-and-hosts.nix

Make use of the [recently added](https://github.com/NixOS/nixpkgs/pull/232808) nullable `mkPackageOption` feature to disable installing an SSH client by default: most people should use the client provided by their system (see https://github.com/nix-community/home-manager/pull/3668#issuecomment-1560496213).
```
```

ssh: don't install a client by default

---

.github/PULL_REQUEST_TEMPLATE.md

The `.github/CODEOWNERS` file was dropped in #3990, so remove this leftover requirement - as it doesn't make sense anymore.
Noticed this while creating #4032.
```
```

Drop remaining CODEOWNERS reference from PR template

---

modules/lib/file-type.nix

It doesn't make sense to pass `executable = null` to `writeTextFile`.
Fixes https://github.com/nix-community/home-manager/issues/4035
```
```

lib/file-type: convert `executable` to bool

---

modules/programs/waybar.nix

This changes the programs.waybar.style option type from `either path str` to `either path lines`, allowing multiple definitions to be merged. This is useful for example to defining custom waybar modules in separate nixos modules,before merging them together
```
```

waybar: merge multiple style definitions

---

modules/misc/news.nix
modules/programs/ripgrep.nix

Following the [conversation](https://github.com/nix-community/home-manager/pull/4017#discussion_r1215501801), I am removing the `configDir` argument and hard-coding the configuration location to `$XDG_CONFIG_HOME/ripgrep/ripgreprc`.
```
```

ripgrep: remove configDir

---

tests/modules/programs/autojump/default-settings.nix
tests/modules/services/git-sync/basic.nix
tests/stubs.nix

Currently, stub packages can't be used with `getExe`, see https://github.com/nix-community/home-manager/pull/3291#issuecomment-1572756632.
Setting `outputSpecified` prevents `getOutput` from descending into outputs, which don't have an overridden `outPath`.
Alternatives:
- removing all outputs makes things fail
- also overriding `outPath` in outputs is more code
```
```

tests: fix `getOutput` on stubs

---

modules/services/window-managers/i3-sway/lib/functions.nix
tests/modules/services/window-managers/i3/i3-workspace-output-expected.conf
tests/modules/services/window-managers/sway/sway-workspace-output-expected.conf

They can contain spaces.
Fixes https://github.com/nix-community/home-manager/issues/4058
```
```

i3-sway: quote output names

---

modules/programs/wezterm.nix
tests/modules/programs/wezterm/bash-integration-default.nix
tests/modules/programs/wezterm/bash-integration-disabled.nix
tests/modules/programs/wezterm/bash-integration-enabled.nix
tests/modules/programs/wezterm/default.nix
tests/modules/programs/wezterm/zsh-integration-default.nix
tests/modules/programs/wezterm/zsh-integration-disabled.nix
tests/modules/programs/wezterm/zsh-integration-enabled.nix

Adds a new option `programs.wezterm.enableBashIntegration` that
sources WezTerm's Bash integration script in `.bashrc`.
```
```

wezterm: add integrations for Bash and Zsh

---

modules/misc/nix.nix
modules/misc/nixpkgs.nix

`isCoercibleToString` and `defaultPriority` will start raising warnings when 22.11 goes EOL.
~~Note that `mkOverride defaultOverridePriority` is a no-op, so we can just remove it.~~
```
```

Clean up deprecated lib functions

---

modules/lib/maintainers.nix
modules/services/espanso.nix
tests/modules/services/espanso/basic-configuration.nix
tests/modules/services/espanso/basic-configuration.yaml
tests/modules/services/espanso/basic-matches.yaml

Espanso module does not work with 2.x version.  In the new version configuration and matches are put into different folders as below.
```
config/
default.yml
match/
base.yml
```
The updated module supports creating multiple files for both config and matches. Users have the full flexibility to create multiple files for different apps.
```
```

Espanso: Fix broken module to be compatible with Espanso version 2.x

---

modules/services/window-managers/i3-sway/sway.nix
tests/modules/services/window-managers/sway/default.nix
tests/modules/services/window-managers/sway/sway-default.target
tests/modules/services/window-managers/sway/sway-no-xwayland.nix
tests/modules/services/window-managers/sway/sway-null-config.nix
tests/modules/services/window-managers/sway/sway-systemd-autostart.nix
tests/modules/services/window-managers/sway/sway-systemd-autostart.target

Using the option `wayland.windowManager.sway.systemd.xdgAutostart`, users can now choose to start applications present in `$XDG_CONFIG_HOME/autostart` when starting their sway session.
This change also renames `wayland.windowManager.sway.systemdIntegration` to `wayland.windowManager.sway.systemd.enable`;
```
```

sway: add support for XDG autostart using systemd

---

tests/default.nix

https://github.com/NixOS/nixpkgs/pull/236749 is in all channels now.
```
```

browserpass: test on Darwin again

---

.github/workflows/test.yml
modules/lib/maintainers.nix
modules/services/espanso.nix
tests/default.nix
tests/modules/services/espanso/basic-configuration.nix
tests/modules/services/espanso/basic-configuration.yaml
tests/modules/services/espanso/basic-matches.yaml
tests/stubs.nix

Backport #4066 to 23.05 since that has espanso 2.
```
```

[23.05] backport #4066

---

modules/accounts/calendar.nix
modules/accounts/contacts.nix
modules/misc/news.nix
modules/modules.nix
modules/programs/khal-accounts.nix
modules/programs/khal-calendar-accounts.nix
modules/programs/khal.nix
modules/programs/vdirsyncer-accounts.nix
modules/programs/vdirsyncer.nix
modules/services/vdirsyncer.nix

This also adds the modules
- programs.vdirsyncer,
- programs.khal, and
- services.vdirsyncer
that integrate with the new infrastructure.
Co-authored-by: Andrew Scott <3648487+ayyjayess@users.noreply.github.com>
Co-authored-by: Sebastian Zivota <sebastian.zivota@mailbox.org>
This is a rebased version of the longstanding PR ( > 3 years ?) made to add contact and calendar support.
I've commented out "locale" support for khal since it was causing issues.
With it in its current state I was able to configure vdirsyncer and khal.
My proposition is to merge this wiht all its faults otherwise we can still wait 4 years before having  anything working.
We have 6 months before release to iron things out and until then we make it clear that the module is experimental.
``` …
```

Add infrastructure for contacts and calendars

---

modules/modules.nix

seems like I missed some code when rebasing  https://github.com/nix-community/home-manager/pull/4078 . Will try to do some more cleanup + prepare automatic labeling
```
```

calendars: add missing modules

---

modules/modules.nix

I've tried to fix the missing vdirsyncer include based on feedback here: https://github.com/nix-community/home-manager/issues/2335#issuecomment-1589137573
```
```

vdirsyncer: Add missing include of services module

---

modules/misc/qt.nix

This allow you to configure Qt integration using KDE instead of `qgnomeplatform` or `qtstyleplugins`. Useful if your theme supports both GTK and KDE, for example Nordic.
To use this properly you will need to do some manual configuration for now. You can set the theme settings using `~/.config/kdeglobals`.
Example:
```nix
{ ... }:
{
qt = {
enable = true;
platformTheme = "kde";
};
xdg = {
configFile.kdeglobals.text = lib.generators.toINI { } {
General = {
ColorScheme = "nordicbluish";
Name = "nordic-bluish";
shadeSortColumn = true;
};
Icons = {
Theme = "Nordic-bluish";
};
KDE = {
LookAndFeelPackage = "Nordic-bluish";
contrast = 4;
};
};
dataFile = {
color-schemes = {
source = "${pkgs.nordic}/share/color-schemes";
recursive = true;
};
plasma = {
source = "${pkgs.nordic}/share/plasma"; …
```

qt: add "kde" to qt.platformTheme

---

modules/misc/news.nix
modules/modules.nix
modules/programs/git-credential-oauth.nix

Adds a module to enable the Git OAuth credential helper, which is a much more secure alternative to the `store` method that is common practice.
```
```

git-credential-oauth: init

---

modules/misc/news.nix
modules/modules.nix
modules/programs/comodoro.nix
modules/services/comodoro.nix
tests/default.nix
tests/modules/programs/comodoro/comodoro.nix
tests/modules/programs/comodoro/default.nix
tests/modules/programs/comodoro/expected.toml
tests/modules/services/comodoro/comodoro.nix
tests/modules/services/comodoro/default.nix
tests/modules/services/comodoro/expected.service

**Comodoro, a CLI to manage your time**. Key features:
- Centralized server timer controllable by multiple clients at the same time
- Multi protocols (only TCP for now, but you can build your own)
- Cycles customizable via config file (Pomodoro style, 52/17 style, custom)
- Server and timer hooks customizable via config file
Website & doc: https://pimalaya.org/comodoro/
Sources: https://github.com/soywod/comodoro
```
```
@toastal

comodoro: add module

---

modules/misc/qt.nix

Don't use aliases as those may be disabled.
https://github.com/nix-community/home-manager/commit/4e09c83255c5b23d58714d56672d3946faf1bcef#commitcomment-118365867
It would be good to build the manual with `allowAliases = false` in CI so we can detect these errors, but currently I don't think we even build the manual in CI?
```
```

qt: fix breeze-qt5 path

---

home-manager/home-manager

In 176e455 the order between the action of `-I` parameters getting added to `EXTRA_NIX_PATH` and the action of a static path getting added to `EXTRA_NIX_PATH` was reversed, also reversing the order of `-I` parameters and the static `-I home-manager=...` leading to the static `-I home-manager=...` to always come before any of the `-I` parameters to later calls to nix commands.
This made it imposible to override the static home-manager path when calling the home-manager tool with `-I home-manager=...`. This was previously posible.
```
``` …

home-manager-tool: prioritize `-I` parameters

---

modules/services/vdirsyncer.nix

-------
vdirsyncer requires the global options to arrive before the command:
``` shellsession
$ vdirsyncer sync --verbosity INFO
Usage: vdirsyncer sync [OPTIONS] [COLLECTIONS]...
Try 'vdirsyncer sync --help' for help.
Error: No such option: --verbosity
$ vdirsyncer --verbosity INFO sync
Syncing …
```
```
```

vdirsyncer: Fix service by moving the options before the command

---

modules/programs/starship.nix
tests/modules/programs/starship/default.nix
tests/modules/programs/starship/fish_with_transience.nix
tests/modules/programs/starship/fish_without_transience.nix

Starship has an advanced, experimental feature where fancy stuff in the prompt can be replaced with something more simple after the command is ran. This is very helpful for copy and pasting shell history somewhere else.
docs: https://starship.rs/advanced-config/#transientprompt-and-transientrightprompt-in-fish
Fish is currently the only shell as far as I can tell that both home-manager and starship support for this feature. Since the function has to be called after starship is loaded, this seems like the best place to put it. Without putting it inside home-manager itself, you would have to forego the provided `programs.fish.interactiveShellInit` entirely just so you can be sure to only call the new function after starship is loaded, which seems like a shame.
I did run just the …

starship: add enable_transience for fish

---

modules/programs/waybar.nix
modules/services/clipman.nix
modules/services/copyq.nix

#3747 renamed the option `wayland.windowManager.sway.systemdIntegration` to `wayland.windowManager.sway.systemd.enable`.
This PR simply updates documentation to reference the new option instead. 
```
```

Update documentation to mention renamed option name.

---

modules/programs/borgmatic.nix
tests/modules/programs/borgmatic/basic-configuration.nix

Fix #3760 by adding output and hooks top-level configuration groups.
```
```

borgmatic: Add missing support for output and hooks

---

modules/home-environment.nix

Was disabled in https://github.com/nix-community/home-manager/commit/dc2a4e4146d1626bc6a916cb57c9e12be2399ca3#diff-5c980e4c769c045b39cdf1cf9597e9cb2d45929f77e106ee8d9abbcdd7b501a0 and never re-enabled. No wonder we're getting so many bug reports caused by out of sync nixpkgs!
This should be backported to 23.05, and maybe even to 22.11.
It might make sense to have a short "grace period" around branch-off, so that you can keep using home-manager master and nixpkgs master together even if one of them has bumped its version. This should happen automatically, as turning the release check off and on is prone to forgetting and if we're ready to do that we might as well just bump `.version`. I'm not sure how to best implement this; I think one way would be to ensure that master always "knows" …

Re-enable nixpkgs release check

---

modules/home-environment.nix

See https://github.com/nix-community/home-manager/issues/4019#issuecomment-1568659267
```
```

home-environment: allow skipping sanity checks

---

modules/programs/helix.nix

Whether to configure Helix as the default editor.
```
```

helix: add defaultEditor

---

modules/misc/gtk.nix

Add gtk4.extraCss option that works like gtk3.extraCss.
I use it to remove shadows and rounded corners from popover menus since they show an ugly black rectangle if compositing is disabled.
```
```

gtk: Add gtk4.extraCss option

---

modules/programs/starship.nix

Many of the terminals supported inside emacs work perfectly fine with STARSHIP.
The TERM=dumb case already handles the tramp and eterm cases, so as far as I can
tell, this is basically just a check for the benefit of OLD versions of
term-mode (see
https://www.emacswiki.org/emacs/AnsiTerm#:~:text=Historically%2C%20'M%2Dx%20ansi%2Dterm,the%20older%20'C%2Dc'%20binding.,
which indicates that it also now handles colors).
```
```

starship: Remove INSIDE_EMACS checks when enabling shell integration

---

modules/programs/bat.nix
modules/programs/gallery-dl.nix
modules/programs/keychain.nix
modules/programs/ledger.nix
modules/programs/lsd.nix
modules/programs/mcfly.nix
modules/programs/navi.nix
modules/programs/ncspot.nix
modules/programs/noti.nix
modules/programs/opam.nix
modules/programs/papis.nix
modules/programs/pazi.nix
modules/programs/rbenv.nix
modules/programs/rtorrent.nix
modules/programs/sqls.nix
modules/programs/starship.nix
modules/programs/tealdeer.nix
modules/programs/translate-shell.nix
modules/programs/yt-dlp.nix
modules/programs/z-lua.nix
modules/programs/zoxide.nix

treewide: remove marsam as maintainer

---

docs/contributing.adoc

https://github.com/nix-community/home-manager/pull/4122#issuecomment-1597921787

docs/contributing: link to NMT's bash-lib

---

modules/misc/news.nix
modules/modules.nix
modules/programs/antidote.nix
tests/default.nix
tests/modules/programs/antidote/antidote.nix
tests/modules/programs/antidote/default.nix

antidote:  add module  , a zsh plug manager

---

modules/programs/antidote.nix
tests/modules/programs/antidote/antidote.nix

fix bug in latest added module antidote.  
since the package submit into nixpkgs is different from my local overlays, relocating zsh path
```
```

fix: antidote zsh path changed

---

home-manager/home-manager

Previously it would fetch the master branch.
```
```

home-manager: use correct branch in generated flake

---

modules/programs/fish.nix

After switching to fish, I noticed that some man pages are not considered when generating completions.
This is because
- Some packages provide man pages in extraOutputs, e.g. tmux and tmux.man and
- Some packages link man pages, e.g. if a package is wrapped with `buildEnv`.
To fix this I added `extraOutputsToInstall` an source for man pages, similar to nixpkgs `buildEnv`
```
```

fish: consider extra outputs to install completions

---

.builds/manual.yml

This builds the manual on builds.sr.ht and pushes it for availability on
https://home-manager.dev/manual/unstable or
https://home-manager.dev/manual/{version}
depending on which release branch is built.
```
```

ci: build manual and push to home-manager.dev

---

modules/programs/antidote.nix

add $HOME to pin .zsh_plugin path in zshrc , keeping antidote from creating empty .zsh_plugins.txt in pwd while new zsh process starting
```
```

antidote: fix  missing `$home` for static files

---

tests/modules/programs/broot/broot.nix

We can't test for the whole contents of the config file because that is out of our control and may change unexpectedly. Only check for the settings we know should be set.
```
```

broot: fix test

---

flake.nix
format

Closes https://github.com/nix-community/home-manager/issues/3615

flake: add formatter

---

modules/programs/zsh.nix
tests/modules/programs/zsh/default.nix
tests/modules/programs/zsh/syntax-highlighting.nix

Commit message:
> Custom styles allow overriding the default colors.
> Example:
> ```nix
> {
>   zsh.syntaxHighlighting.styles.comment = "fg=#6c6c6c";
> }
> ```
> 
> See https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters.md
The motivation for adding this is to workaround https://github.com/zsh-users/zsh-syntax-highlighting/issues/510
I also made the package configurable since we have a module now.
```
```

zsh: allow setting custom syntax highlighting styles

---

docs/installation.adoc

Update a "dead" link in the installation instructions, also use correct option name. The option has been changed somewhene during 2022.
```
```

docs: update link to allowed users setting

---

modules/programs/kakoune.nix

Add an option for setting `kak` as the default `$EDITOR`, consistent with the other editors available as home-manager options.
```
```

kakoune: add defaultEditor option

---

modules/programs/lsd.nix

Hi,
The current `lla` alias, together with the `total-size` option try to get the size of the `..` directory, and for this has to recursively open all sibling folders. This may be super slow if some of those siblings contain too many files, and raise a ton of useless errors if some of those siblings contains non-readable files.
I'm suggesting to use `-A` instead, which will skip the obvious `.` and `..` folders.
While here, I think we could also add `llt`.
```
```

lsd: use -A instead of -a in aliases

---

README.md

This removes the Nix Pills reference, because they are not a good introduction to the Nix ecosystem, but rather a thorough explanation of many disparate things. Reading through them might give some light bulb moments for an intermediate reader, but that does not mean that they're good for a beginner.
I've also removed the mention of infinite recursion without source location. That's an old meme for a problem that has been mostly solved. Mentioning it here has two effects
- Propagate the outdated meme
- Make users insensitive to bad errors. Learned helplessness. That kind of thing. What we really want is for them to report bad error messages, so that they can be fixed. And they can be fixed; just report them at `NixOS/nix`
```
```
See …

README: Remove the pills

---

modules/services/sxhkd.nix
tests/modules/services/sxhkd/configuration.nix
tests/modules/services/sxhkd/sxhkdrc

This makes it consistent with some other options, like `systemd.user.services.Service.ExecStart`.
```
```

sxhkd: allow usage of derivations as keybind commands

---

modules/programs/chromium.nix

`commandLineArgs` were only being applied when the user didn't override the `package` option.
```
```

chromium: fix `commandLineArgs` to use the user specified package

---

modules/misc/news.nix
modules/modules.nix
modules/services/ssh-agent.nix

Add a simple module for ssh-agent, fixes #1087.
```
```

ssh-agent: init module

---

home-manager/home-manager

```
Nix interprets a path-like URI as a git repository if any of the path's parents is a git repository. Since home-manager uses a default flake URI of ~/.config/nixpkgs/flake.nix, if you have a git repository as your home directory and a '*' .gitignore it leads to the following problems:
evaluating derivation 'git+file:///Users/dongcarl?dir=.config%2fnixpkgs#homeConfigurations."dongcarl".activationPackage'
The following paths are ignored by one of your .gitignore files:
.config
This is solved by explicitly specifying the `path:` URI type prefix for the default flake URI argument.
```
I hope that this fix gets backported to release branches.

home-manager: Use `path:` URI type for flake default

---

modules/misc/xfconf.nix

In some cases, I'd like to remove xfconf properties. For example, if you set a keyboard shortcut's value to an empty string:
```
xfconf.settings.xfce4-keyboard-shortcuts."commands/custom/<Alt><Super>s" = "";
```
Rather than removing the property, this will cause an error. A property must be removed with `xfconf-query -r ...`.
I had considered adding a separate list of properties for removal:
```
xfconf.unsettings.xfce4-keyboard-shortcuts = [ "commands/custom/<Alt><Super>s" ]
```
but that would allow for both setting and unsetting the same property and doesn't allow for defaults vs. overrides, etc.
```
```

xfconf: remove properties with null values

---

modules/config/i18n.nix
nixos/default.nix
tests/modules/config/i18n/default.nix
tests/modules/home-environment/session-variables.nix
tests/modules/misc/xdg/system-dirs.nix
tests/modules/systemd/session-variables.nix

This will reduce the system closure size by about 200MB under NixOS by sharing the `glibcLocales` package.
When home-manager is installed on Linux without the NixOS module, all glibc locales are installed, as before.
Resolves #2333

i18n: Use glibcLocales from NixOS if possible (#2333)

---

modules/services/vdirsyncer.nix

Without this, the service will never synchronize things like calendar/contact
display names and calendar colors.
```
```

vdirsyncer: synchronize metadata as well

---

modules/services/window-managers/i3-sway/lib/options.nix

Deprecated in cacb8d4, see #265
```
```
@sumnerevans @alexarice

i3: remove deprecated example in i3.config.startup

---

modules/services/imapnotify.nix
tests/default.nix
tests/modules/programs/goimapnotify/default.nix
tests/modules/programs/goimapnotify/launchd.nix
tests/modules/programs/goimapnotify/launchd.plist

This extends the imapnotify (goimapnotify) configuration with a launchd agent that matches the systemd unit (and shares as much code as possible).
~Annoyingly I'd forgotten that `goimapnotify` is malconfigured in `nixpkgs`, in that it works (and is supported) on macos, but the metadata `platforms` are linux only. So while this is blocked on that, I'm making the PR now, and I'll update it when the upstream change is merged.~
Edit: NixOS/nixpkgs#193797 (now merged, ~awaiting~ and deployed [deployment to nixos-unstable](https://nixpk.gs/pr-tracker.html?pr=193797))
~I added a semi-golden test: it uses the `goimapnotify` store path, so I've passed that as a parameter. I've seen the `pkgs.writeText` pattern used in other tests, but I didn't spot this case, so I hope it's ok.~
I've seen that …

imapnotify: Add launchd agent

---

modules/services/unison.nix

Unison supports the same option to be given several times as a command
line argument (e.g. unison -path xxx -path yyy).
This commit adds Home Manager support for this by allowing a list of
strings to be given to services.unison.pairs.<name>.commandOptions values.
(new to Nix and first PR, did not manage to fill all the checklist yet)
- [ x] Commit messages are formatted like
```
```
@pacien

 unison: Allow using same option multiple times

---

tests/modules/programs/beets/mpdstats-external.nix
tests/modules/programs/beets/mpdstats.nix
tests/modules/programs/beets/mpdupdate.nix
tests/modules/programs/goimapnotify/launchd.nix
tests/modules/programs/nnn/nnn.nix
tests/modules/programs/qutebrowser/keybindings.nix
tests/modules/programs/qutebrowser/quickmarks.nix
tests/modules/programs/qutebrowser/settings.nix
tests/modules/programs/terminator/config-file.nix
tests/modules/programs/topgrade/settings.nix
tests/modules/programs/vscode/keybindings.nix
tests/modules/programs/vscode/tasks.nix
tests/modules/programs/zplug/modules.nix

Also minor test cleanup.
```
```

goimapnotify: remove test dependency on notmuch

---

modules/misc/news.nix
modules/modules.nix
modules/programs/darcs.nix
tests/default.nix
tests/modules/programs/darcs/author-expected.txt
tests/modules/programs/darcs/author.nix
tests/modules/programs/darcs/boring-expected.txt
tests/modules/programs/darcs/boring.nix
tests/modules/programs/darcs/default.nix

This adds a pretty simple module for the [Darcs](http://darcs.net) package manager, with support for two commonly-used configuration options: "author" (commiter name/email) and "boring" (akin to `.gitignore`).
```
```

Darcs: new module

---

modules/misc/news.nix
modules/modules.nix
modules/programs/pyenv.nix
tests/default.nix
tests/modules/programs/pyenv/bash.nix
tests/modules/programs/pyenv/default.nix
tests/modules/programs/pyenv/fish.nix
tests/modules/programs/pyenv/zsh.nix

Add a module `programs.pyenv` for [pyenv](https://github.com/pyenv/pyenv).
Note for reviewers: pyenv was only [recently added to Nixpkgs](https://github.com/NixOS/nixpkgs/pull/239499). Make sure you're using a sufficiently recent Nixpkgs version when reviewing without flakes.
Since this is my first time messing with HM modules, I based the module off of `programs.atuin` which is (very) roughly similar in structure. Just in case I accidentally missed a remaining reference to Atuin somewhere - which I'm pretty sure I didn't, but you never know...
```
``` …

pyenv: add module

---

modules/programs/himalaya.nix
tests/modules/programs/himalaya/notmuch-sendmail-expected.toml

Previously, IMAP was preferred over `notmuch`, even if `notmuch` was configured, causing problems with setting account flavor (which automatically sets IMAP settings). The new backend order is:
`notmuch` > IMAP > maildir
This also fixes the `notmuch` DB path being set to the wrong location. The `notmuch` DB is located at the maildir base path, not in each account's maildir.
https://github.com/nix-community/home-manager/blob/c24deeca64538dcbc589ed8da9146e4ca9eb85b7/modules/programs/notmuch.nix#L23
```
``` …

himalaya: Fix notmuch backend

---

modules/programs/nushell.nix
tests/modules/programs/nushell/example-settings.nix
tests/modules/programs/nushell/login-expected.nu

Nushell has the option to source from the login.nu file upon logging in, in the case that nushell is used as a login shell.
See https://www.nushell.sh/book/configuration.html#configuring-nu-as-a-login-shell for more information.
This change adds the login file alongside the existing config and env files as another configuration option.
(tested with `nix develop --ignore-environment .#tests.nushell-example-settings`)
```
```

nushell: adds login.nu configuration option

---

modules/misc/news.nix
modules/services/ssh-agent.nix

See https://github.com/nix-community/home-manager/pull/4178#discussion_r1249460142
```
```

ssh-agent: add assertion and fix news entry

---

modules/programs/aerc-accounts.nix
modules/programs/aerc.nix
tests/modules/programs/aerc/assertion.nix
tests/modules/programs/aerc/default.nix

The aerc configuration file `aerc.conf` can contain 10 sections, but only the UI section supports what the aerc manual calls contextual configuration. This works by appending to the section heading either `:account=name` or `:folder=bar`. It's supported in `config.accounts.email.accounts.<name>.aerc.extraConfig.*.*`, as the aerc-accounts module applies a
function to add `<name>` to section headings.
However, this means home-manager will generate files like:
```
[general:account=default]
log-file=...
```
and the options will not be recognized by aerc.
This change only adds the account name to the UI section by adding a `attrsets.filterAttrs` check to `mkAccountConfig`. This could be confusing if a user only wants to apply their configuration to one account, and a possible alternative could …

aerc: add assertion to limit per-account extraConfig to UI config

---

modules/config/home-cursor.nix

The gtk configurations are not generated unless config.gtk is enabled. This is a point of confusion because config.home.pointerCursor.gtk can essentially be disabled, despite having it enabled.
I changed the home.pointerCursor.gtk option such that it also enables the gtk module. The pointerCursor.gtk option essentially does nothing when the gtk module is disabled, so I think it is safe to assume that you would want to enable gtk when using this option. My cursor size was not consistent between applications, and it admittedly took me way too long to figure out that this was the problem..
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent …

home-cursor.nix: enable gtk module when enabling gtk config generation

---

modules/services/window-managers/i3-sway/lib/options.nix

The floating modifier can consist of a combination of modifier keys. Trying to model this with a regex doesn't seem worth it, so just use `str`.
Fixes https://github.com/nix-community/home-manager/issues/4216
```
```

i3-sway: allow arbitrary floating modifier

---

modules/programs/zsh.nix
tests/modules/programs/zsh/syntax-highlighting.nix

Previously, customizing a highlighting style with `programs.zsh.syntaxHighlighting.styles.comment = "fg=#6c6c6c"` did not work because in `.zshrc` it added `ZSH_HIGHLIGHT_STYLES['comment']='fg=#6c6c6c'` which changes the key `'comment'` instead of `comment`.
This pull request changes the syntax to `ZSH_HIGHLIGHT_STYLES+=('comment' 'fg=#6c6c6c')` which does not add the quotes to the key.
```
```
@ThinkChaos

zsh: fix custom syntax highlighting styles

---

modules/services/imapnotify-accounts.nix
modules/services/imapnotify.nix

goimapnotify's configuration is JSON-based, and the recommended configuration has:
```
"tlsOptions": {
"rejectUnauthorized": true
},
```
However, since HM only allows an attrset of str/int/bool in `accounts.email.accounts.<name>.imapnotify.extraConfig`, it's impossible to configure such options.
This change changes the type to the JSON type provided by nixpkg's `formats.json`.
@NickHu

imapnotify: Use JSON type for extraConfig

---

home-manager/default.nix
home-manager/home-manager
home-manager/po/home-manager.pot
modules/po/hm-modules.pot

Depricate hard-coded fallback home-manager paths. Specificly "${XDG_CONFIG_HOME:-$HOME/.config}/nixpkgs/home-manager" and "$HOME/.nixpkgs/home-manager".
Use @HOME_MANAGER_PATH@ if it has been provided and points to something that exisits. Warn the user if it does not point to something.
If we have not been provided with a @HOME_MANAGER_PATH@ that exisits, then for both hard-coded paths show a warning if something exisits where the paths are pointing.
This no longer attempts to use either of the hard-coded paths as fallbacks for the home-manager path.
Alternative to https://github.com/nix-community/home-manager/pull/4084
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) …

home-manager-tool: Depricate home-manager paths

---

modules/programs/jujutsu.nix

This change updates the `programs.jujutsu` module to align with a breaking change in the version 0.8.0 landed to nixpkgs unstable recently.
```
```
@shikanime

jujutsu: update for Jujutsu 0.8.0

---

modules/programs/script-directory.nix

Fixes the broken documentation link for the sd options.
```
```
@Janik-Haag

script-directory: fix documentation link

---

modules/misc/news.nix
modules/modules.nix
modules/services/window-managers/hyprland.nix
tests/default.nix
tests/modules/services/window-managers/hyprland/default.nix
tests/modules/services/window-managers/hyprland/inconsistent-config.nix
tests/modules/services/window-managers/hyprland/simple-config.conf
tests/modules/services/window-managers/hyprland/simple-config.nix

Add the Hyprland module, ported from
https://github.com/hyprwm/Hyprland/blob/main/nix/hm-module.nix,
which was adapted from the sway module.
CC: @Mic92
```
```

hyprland: init

---

modules/services/window-managers/hyprland.nix
tests/modules/services/window-managers/hyprland/simple-config.conf
tests/modules/services/window-managers/hyprland/simple-config.nix

The `settings` attribute now handles `$variables` and `bezier`s differently,
putting them at the top of the file.
Also, proper indentation has been implemented.
EDIT(@ncfavier): fixes https://github.com/nix-community/home-manager/issues/4262
```
```

hyprland: prioritize variables and beziers

---

modules/services/git-sync.nix
tests/default.nix
tests/modules/services/git-sync-darwin/basic.nix
tests/modules/services/git-sync-darwin/default.nix
tests/modules/services/git-sync-darwin/expected-agent.plist

`services.git-sync` support on darwin
- On darwin, creates a launch agent to run git-sync on an interval and when the `path` changes.
- The `uri` option is not used on Darwin. The auto-creation of the local git directory from the `uri` is a feature of the
[git-sync-on-inotify](https://github.com/simonthum/git-sync/blob/master/contrib/git-sync-on-inotify) wrapper (which won't work on Darwin afaik) and not `git-sync` itself.
```
```
@imalison  @cab404
_Disclaimer: new-ish to …

git-sync: darwin support

---

modules/programs/firefox.nix

Fixes https://github.com/nix-community/home-manager/issues/4112
```
```

firefox: make package nullable

---

modules/services/window-managers/hyprland.nix

Freshly added in https://github.com/NixOS/nixpkgs/pull/244819
Tracking: https://nixpk.gs/pr-tracker.html?pr=244819
```
```

hyprland: use `toKeyValue`'s `indent` argument

---

modules/programs/gnome-terminal.nix
tests/modules/programs/gnome-terminal/bad-profile-name.nix
tests/modules/programs/gnome-terminal/default.nix

Without the assert the profile will just not show up in Gnome Terminal and it is a bit tricky to find out why.
```
```

gnome-terminal: add assertion on profile names

---

modules/programs/gh.nix
tests/modules/programs/gh/credential-helper.git.conf
tests/modules/programs/gh/credential-helper.nix

`gh` can also be used with github enterprise hosts, for which there exists no easy option to enable the credential helper except for directly working with `programs.git.extraConfig`.
Therefore I've added the option `programs.gh.extraGitCredentialHelperHosts`. The name is up for debate since it's maybe a bit verbose.
Not sure if this is a needed addition since it's somewhat niche, at the same time it's not very complex and makes the life of github enterprise users a little easier.
```
```
@Gerschtli @berbiche

gh: option to enable helper for additional hosts

---

modules/programs/man.nix

man: fix caches generation in cross-compiled system

---

modules/programs/direnv.nix
modules/programs/nushell.nix
tests/modules/programs/nushell/env-expected.nu
tests/modules/programs/nushell/example-settings.nix

let-env has been deprecated in nushell's latest release.
This PR aims to fix the errors that this causes.
```
```

nushell: deprecation of let-env

---

modules/programs/jujutsu.nix

In jujutsu 0.8, the library that generates shell completions was upgraded, and the new version no longer requires truncating the last line in order to work, and in fact, outputs an error message if you do (because the completion code is now missing the `fi` to close an `if` statement). The guidance upstream for enabling completion [has been updated accordingly](https://github.com/martinvonz/jj/issues/1393), and this change updates the home-manager module to match.
```
```

jujutsu: fix zsh completion

---

modules/programs/zsh.nix

Fixes https://github.com/nix-community/home-manager/issues/4247.
```
```
@ncfavier

zsh: Add `zsh.history.ignoreAllDups` config option

---

modules/programs/aerc-accounts.nix
tests/modules/programs/aerc/extraAccounts.expected

This option was deprecated in 0.15.0, +insecure schema is suggested instead.
Thus, we can just copy imap logic, which already uses +insecure.
```
```
@lukasngl

aerc: do not use smtp-starttls

---

modules/services/taffybar.nix

taffybar restarts very quickly right now which can lead to a very quick failure in cases where the display is not ready in time
```
```

taffybar: Avoid restarting too quickly

---

modules/programs/mu.nix
tests/modules/programs/mu/basic-configuration.nix

mu: add package option

---

modules/services/kanshi.nix

Adds a configuration option to turn the `adaptive_sync on/off` option in the config
```
```
@nurelin

kanshi: support adaptive sync

---

modules/programs/khal.nix

While the locale options were declared, the weren't used in the generation of the config file, because the locale submodule missed a default, which failed the tests. I added an empty attribute set as a default, which fixes the test, and works with the defaults in the submodule options as expected.
Closes #4283 
```
```
Not really maintainer, but @teto

khal: uncomment locale config

---

modules/programs/lf.nix
tests/modules/programs/lf/all-options.nix

Don't try to validate a limited set of hardcoded options, instead just convert them as-is. Now, users can keep all their options in a single attribute set, including arbitrary `user_{option}`s which was impossible to express with a hard-coded submodule. As a plus, there is also less maintainence burden.
```
```
@owm111

lf: simplify option validation

---

home-manager/default.nix
home-manager/home-manager
modules/home-environment.nix

Nix 2.17 changed the format of the `nix profile list` output. This commit adds support for parsing the new JSON profile list format.
Fixes #4298
```
```

home-manager: handle profile list in Nix >2.17

---

modules/services/window-managers/hyprland.nix

Remove `xwayland.hidpi` option, since we're dropping HiDPI XWayland patches support, opting to use the builtin xwayland:force_zero_scaling option instead. It is described in more detail in https://wiki.hyprland.org/Configuring/XWayland.
This change needs to be merged right after https://github.com/NixOS/nixpkgs/pull/247008 hits unstable, so that people don't get a broken module.
Reference PRs for this change:
- hyprwm/Hyprland#2870
- hyprwm/hyprland-wiki#282
```
```

hyprland: remove xwayland.hidpi

---

modules/misc/xdg-desktop-entries.nix
modules/programs/tmate.nix

Backporting https://github.com/nix-community/home-manager/pull/4324
(cherry picked from commit 7b8d43fbaf8450c30caaed5eab876897d0af891b)
```
```

[23.05] modules: types.string throws error now (#4324)

---

modules/misc/news.nix
modules/programs/xplr.nix

Adds a home-manager module for [xplr](https://github.com/sayanarijit/xplr)
```
```

xplr: add module

---

modules/config/home-cursor.nix

An IFD was introduced in https://github.com/nix-community/home-manager/commit/bdb5bcad01ff7332fdcf4b128211e81905113f84, from reading the top-level directories of the
`home.pointerCursor.package` at instantiation time.
This commit removes the IFD introduced when linking icon directories by linking only the icon directory matching `home.pointerCursor.name` in `home.pointerCursor.package`. This should have the same effect as linking all top-level directories of the supplied icon package as the module generates cursor configurations pertaining to the cursor identified by `home.pointerCursor.name`. Since any additional icon directories present are not explicitly referenced by the module, any difference in behavior would be attributed to impurities and should be eliminated.
fixes …

home-cursor: remove IFD when linking icon directories

---

modules/programs/bat.nix

bat: generate cache file in XDG cache home

---

modules/misc/news.nix
modules/modules.nix
modules/programs/qcal.nix
tests/default.nix
tests/modules/programs/qcal/default.nix
tests/modules/programs/qcal/http-calendar.json-expected
tests/modules/programs/qcal/http-calendar.nix
tests/modules/programs/qcal/mixed.json-expected
tests/modules/programs/qcal/mixed.nix
tests/modules/programs/qcal/webdav-calendar.json-expected
tests/modules/programs/qcal/webdav-calendar.nix

@teto suggested I write a home-manager module for qcal. qcal is a CLI calendar application, which does not cache anything, unlike most other similar applications.
While I played around in the recent months, I still feel rather new to nix, please review my code carefully.
My module and tests are heavily inspired by the existing khal module. I tried to make the tests such that config files can be semantically compared, not just diffed. The only problem I have there is that for qcal the "order" of calendars doesn't matter and as such the order in the list in the json file doesn't matter, but that is not included in the "semantic" comparison. If you have an idea on how to implement that, please tell me.
qcal has been very recently added to nixpkgs, ~qcal hasn't even made it to …

qcal: add module

---

modules/programs/chromium.nix

This patch adds support for installing hunspell dictionaries in chromium.
Follow up to https://github.com/NixOS/nixpkgs/pull/238805
```
```

chromium: add support for dictionaries

---

modules/programs/khal.nix
tests/modules/programs/khal/config.nix
tests/modules/programs/khal/khal-config-expected

The current khal module doesn't provide options to add settings in the [default] and [view] sections of the configuration file. This PR adds optional settings for both. I chose a generic option instead of separately defining all possible settings, due to the amount of them and the future maintenance required for keeping the list up to date.
```
```

khal: add options for default and view sections

---

tests/modules/programs/helix/settings-expected.toml
tests/modules/programs/i3status-rust/with-extra-settings.nix

The generated format seems to have changed with the merge of <https://github.com/NixOS/nixpkgs/pull/245440>.
```
```

tests: update to match latest TOML output

---

modules/misc/tmpfiles.nix

In `modules/misc/tmpfiles.nix`, replace the single use of `xdg.dataFile` with `xdg.configFile`, which was used anyways.
Not only is this a small (positive) refactor, but it minimises the impact of #4397, as setting `xdg.dataHome` outside the homedir will not break `tmpfiles` anymore.
@dawidsowa

tmpfiles: use only `xdg.configFile`

---

modules/accounts/email.nix

This adds proper TLS port configuration for runbox.com IMAP and SMTP servers.
```
```
@rycee (not too sure, could not find meta.maintainers, sorry)

email: fix runbox.com TLS setup

---

modules/misc/news.nix
modules/modules.nix
modules/programs/carapace.nix
tests/default.nix
tests/modules/programs/carapace/bash.nix
tests/modules/programs/carapace/default.nix
tests/modules/programs/carapace/fish.nix
tests/modules/programs/carapace/nushell.nix
tests/modules/programs/carapace/zsh.nix

This introduces the programs.carapace.* options to use carapace-bin as the way for bash, zsh and fish to handle shell autocompletion. This aligns completion support for different executables across the shells.
The integration of carapace-bin into the shells in this PR is based on the instructions from the carapace-bin readme:
https://github.com/rsteube/carapace-bin#getting-started
```
```

carapace: add module

---

modules/programs/emacs.nix

A recent change[1] in Nixpkgs makes version attribute non-optional.
This change fixes evaluation of user configurations where `programs.emacs.extraConfig` is used.
[1]: https://github.com/NixOS/nixpkgs/pull/253448
```
```

emacs: add version for default.el package

---

home-manager/completion.bash
home-manager/completion.zsh

home-manager: fix some completions commands

---

nixos/default.nix

I'm experiencing timeouts for home-manager-$USER.service in my NixOS VM tests. The NixOS testing framework increases the default timeout from 1m30 to 5m, but since home-manager specifies a timeout, that value wins.
There's no point in having a tight timeout value, so increase it to 5m.
```
```

nixos: increase TimeoutStartSec from 1m30s to 5m

---

modules/programs/swaylock.nix

This adds a note about how swaylock can actually be made to unlock sessions when swaylock-specific PAM configuration is not yet set up.
The note on how to do it on NixOS seems like a useful hint, it's probably the most common use case where this will fail, but shout if NixOS-specific notes are not right here.
- N/A
```
```
- N/A
@rcerc

swaylock: Document the need for host PAM configuration

---

tests/modules/programs/emacs/extra-config.nix

Fix emacs test: https://github.com/nix-community/home-manager/issues/4453
```
```
@rycee

emacs: fix emacs-extra-config test

---

modules/programs/bat.nix
tests/modules/programs/bat/bat.nix

adds an option to add custom syntax files to bat's cache, analogous to the existing programs.bat.themes option.
- (also currently in use in my own home config)
```
```
maintainer list is empty; @rycee made the last commit touching the module

bat: allow adding custom syntaxes

---

home-manager/home-manager
home-manager/po/ca.po
home-manager/po/cs.po
home-manager/po/da.po
home-manager/po/de.po
home-manager/po/es.po
home-manager/po/fa.po
home-manager/po/fi.po
home-manager/po/fr.po
home-manager/po/home-manager.pot
home-manager/po/id.po
home-manager/po/it.po
home-manager/po/ja.po
home-manager/po/ko.po
home-manager/po/lt.po
home-manager/po/nb_NO.po
home-manager/po/nl.po
home-manager/po/pl.po
home-manager/po/pt.po
home-manager/po/pt_BR.po
home-manager/po/ro.po
home-manager/po/ru.po
home-manager/po/sv.po
home-manager/po/tr.po
home-manager/po/uk.po
home-manager/po/zh_Hans.po
home-manager/po/zh_Hant.po
modules/po/hm-modules.pot
modules/programs/carapace.nix

home-manager.pot: fix typo

---

modules/programs/i3status-rust.nix

Adds automatic reloading of i3status-rust on config change.
This is done via sending SIGUSR2, which is now supported since [v0.20.0](https://github.com/greshake/i3status-rust/blob/master/NEWS.md#new-blocks-and-features-21)
The previous method of attempting to restart i3 in its entirety didn't work at least on my system, and is now overkill anyways.
```
```
@thiagokokada

i3status-rust: reload on config change

---

modules/lib/maintainers.nix
modules/misc/news.nix
modules/modules.nix
modules/programs/rio.nix
tests/default.nix
tests/modules/programs/rio/default.nix
tests/modules/programs/rio/empty-settings.nix
tests/modules/programs/rio/example-settings.nix

Adds a `programs.rio` module to control Rio installation and configuration.
```
```

rio: add module

---

modules/services/pasystray.nix
tests/default.nix
tests/modules/services/pasystray/default.nix
tests/modules/services/pasystray/expected.service
tests/modules/services/pasystray/service.nix

e.g. for `-g`.
Adds support for extra arguments to `pasystray`.
```
```
@pltanton

pasystray: add extraOptions

---

modules/services/window-managers/fluxbox.nix

Self-explanatory, fixes #4457 
```
```
@AndersonTorres

fluxbox: Try fix xsession cmdline

---

modules/programs/rofi-pass.nix

This is useful for swapping out the default package for the still unstable but soon normally available rofi-pass-wayland package
```
```

rofi-pass: allow the user to set the package

---

modules/programs/starship.nix

For starship 1.16 it is recommended by upstream to use `use`. Earlier starship verions did not support the use of `use`, so `use` or `source` are used depending on the configure starship version.
```
```

starship: use `use` instead of `source` for nushell with starship v1.16+

---

modules/services/window-managers/i3-sway/lib/options.nix
tests/modules/services/window-managers/sway/sway-bar-focused-colors.conf
tests/modules/services/window-managers/sway/sway-bindkeys-to-code-and-extra-config.conf
tests/modules/services/window-managers/sway/sway-default.conf
tests/modules/services/window-managers/sway/sway-modules.conf
tests/modules/services/window-managers/sway/sway-post-2003.conf
tests/modules/services/window-managers/sway/sway-post-2003.nix
tests/modules/services/window-managers/sway/sway-workspace-default-expected.conf

Fixes nix-community/home-manager#4488
```
```
@Scrumplex, @alexarice, @sumnerevans, @SebTM, and @oxalica

i3-sway: separate trayOutput values for sway

---

modules/programs/direnv.nix

The current syntax is invalid for the latest release of nushell (`0.85.0`). I think this is related to https://github.com/nushell/nushell/pull/10103.
The latest nushell release is ~~not yet~~ packaged in `nixpkgs`  (https://github.com/NixOS/nixpkgs/pull/256330), however this change is backwards compatible. I verified by testing it with the both the current unstable version `0.84.0` and the latest version `0.85.0`.
```
```

direnv: fix nushell syntax

---

modules/programs/lsd.nix
tests/default.nix
tests/modules/programs/lsd/default.nix
tests/modules/programs/lsd/example-colors-expected.yaml
tests/modules/programs/lsd/example-settings-expected.yaml
tests/modules/programs/lsd/example-settings.nix

This PR add new `colors` option for user to configure lsd colors.
I have tested the related option on my machines, and they should work as expected.
```
```

lsd: allow user to configure colors

---

tests/stubs.nix

This is to avoid warnings being printed while tests are run.
```
```

tests: add mainProgram to stub packages

---

modules/programs/neovim.nix

Currently, there are 5 packages that can be managed with Home Manager that expose `finalPackage` option publicly: `pandoc`, `rofi`, `timidity`, `emacs`, `hyprland`. This commit adds the 6th one: `neovim`. While the final package that is being built after all of the modifications should be considered an implementation detail, in cases of complex software like `neovim` this could hide important details.
One particular case that comes to mind is using `lazy.nvim` package manager. It exposes a number of useful APIs that really help managing configuration, such as conditional keybindings, dependency tree building, merging configurations, and so on. Questions about using it on NixOS come up often, because manually recreating this functionality is hard, and it's a very popular method of managing …

neovim: expose finalPackage

---

modules/misc/qt.nix

Removes references to qtstyleplugin-kvantum-qt4 which has been removed because it depended on qt4.
Throwing at rebuild:
```
… while calling the 'head' builtin
at /nix/store/av6ibf16025dfc1s0dwz9d27dcdwjckb-nixos/nixos/lib/attrsets.nix:820:11:
819|         || pred here (elemAt values 1) (head values) then
820|           head values
|           ^
821|         else
… while evaluating the attribute 'value'
at /nix/store/av6ibf16025dfc1s0dwz9d27dcdwjckb-nixos/nixos/lib/modules.nix:807:9:
806|     in warnDeprecation opt //
807|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
|         ^
808|         inherit (res.defsFinal') highestPrio;
(stack trace truncated; use '--show-trace' to show the full trace)
error: qtstyleplugin-kvantum-qt4 has been …
```

remove qtstyleplugin-kvantum-qt4

---

modules/programs/direnv.nix

Add package options for direnv and nix-direnv so that we can more easily override the packages used.
```
```

direnv: add package options

---

modules/misc/news.nix
modules/modules.nix
modules/programs/awscli.nix
tests/default.nix
tests/modules/programs/awscli/aws-config.conf
tests/modules/programs/awscli/aws-credentials.conf
tests/modules/programs/awscli/awscli.nix
tests/modules/programs/awscli/default.nix

Add `programs.awscli` module to:
* Automatically install awscli2 in your home environment
* Configure your ~/.aws/config and ~/.aws/credentials files
Also added myself as maintainer of the `programs.awscli` module.
```
```

awscli: add module

---

home-manager/home-manager

Fixes #4403.
Due to a possible bug in nix v2.15.0 - v2.17.0, `nix run` no longer creates the default profile, which makes the flake installation of home-manager fail on new nix installations. This PR makes sure that `nix-env -q` is executed in order to create the profile.
```
```
@rycee

home-manager: fix for missing profile directory in nix v2.17.0

---

modules/lib/maintainers.nix
modules/misc/news.nix
modules/modules.nix
modules/programs/wpaperd.nix
tests/default.nix
tests/modules/programs/wpaperd/default.nix
tests/modules/programs/wpaperd/wpaperd-example-settings.nix
tests/modules/programs/wpaperd/wpaperd-expected-settings.toml

This PR adds home-manager module for program wpaperd.
```
```

wpaperd: add wpaperd configuration

---

modules/misc/news.nix
modules/modules.nix
modules/programs/khard.nix
tests/default.nix
tests/modules/programs/khard/basic_config.nix
tests/modules/programs/khard/basic_config_expected
tests/modules/programs/khard/default.nix
tests/modules/programs/khard/empty_config.nix
tests/modules/programs/khard/empty_config_expected
tests/modules/programs/khard/multiple_accounts.nix
tests/modules/programs/khard/multiple_accounts_expected

Add support for [khard](https://github.com/lucc/khard), integrating it with the recently merged contact infrastructure.
/cc @teto as author of the calendar and contacts infra PR.
```
```

khard: Add module

---

modules/programs/scmpuff.nix
tests/modules/programs/scmpuff/bash.nix
tests/modules/programs/scmpuff/default.nix
tests/modules/programs/scmpuff/fish.nix
tests/modules/programs/scmpuff/no-aliases.nix
tests/modules/programs/scmpuff/no-bash.nix
tests/modules/programs/scmpuff/no-shell.nix
tests/modules/programs/scmpuff/zsh.nix

Currently, `scmpuff` is giving their aliases  (e.g. `ga`, `gd`, `gco`) by default. I already have my own aliases for git and personally don't like theirs. I added `enableAliases` so we can enable or disable it.
Reference: https://github.com/mroth/scmpuff#can-i-disable-or-change-the-default-git-shortcut-aliases
```
```
@cpcloud

scmpuff: enable or disable aliases

---

modules/lib/maintainers.nix
modules/misc/news.nix
modules/modules.nix
modules/programs/zsh/zsh-abbr.nix
tests/modules/programs/zsh/default.nix
tests/modules/programs/zsh/zsh-abbr.nix

Add `zsh-abbr` module under `zsh`.
Add `zsh-abbr.abbrs` option so we can use fish-like abbreviations in zsh.
References: https://github.com/olets/zsh-abbr
```
```

zsh-abbr: add module

---

modules/programs/firefox.nix
tests/modules/programs/firefox/profile-settings-expected-bookmarks.html

For some reason, Firefox completely discards the ADD_DATE and LAST_MODIFIED attributes if they are set to 0. This has been confirmed by exporting a sample set of bookmarks generated by Nix using home-manager and comparing it to the same sample of bookmarks set manually and then exported.
Missing these attributes can cause problems for extensions and other tools that try to read bookmarks. A known example is the Tridactyl extension.
```html
<!DOCTYPE NETSCAPE-Bookmark-file-1>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<meta http-equiv="Content-Security-Policy"
content="default-src 'self'; script-src 'none'; img-src data: *; object-src 'none'"></meta>
<TITLE>Bookmarks</TITLE>
<H1>Bookmarks Menu</H1>
<DL><p>
<DT><A HREF="https://example.com/">MenuMark1</A>
<DT><H3 …
```

firefox: set ADD_DATE and LAST_MODIFIED of bookmarks to 1

---

modules/programs/bat.nix
tests/modules/programs/bat/default.nix
tests/modules/programs/bat/deprecated-options.nix

The way the `bat` module is currently written makes it essentially impossible to
use themes and syntaxes without IFD, since you must provide the contents as
string, instead of just giving a path to be linked.
With this change, setting themes/syntaxes by-string will start issuing warnings,
and a new attribute model is added, lightly inspired by how
`programs.zsh.plugins` avoided this issue.
```
```
cc. @stuebinm, @rycee, @lugray

bat: allow setting themes/syntaxes without IFD

---

modules/services/window-managers/hyprland.nix
tests/modules/services/window-managers/hyprland/inconsistent-config.nix
tests/modules/services/window-managers/hyprland/simple-config.conf

Fixes #4484
Allows users to customize which environment variables to import in DBus and SystemD user environments, and to specify which commands will be run after the environment activation.
```
```

hyprland: allow customizing systemdIntegration

---

flake.nix

 flake: fix nixpkgs `config`

---

modules/services/unison.nix

So that one can use the lighter headless version of Unison.

unison: add package option

---

modules/programs/zsh.nix
tests/modules/programs/zsh/history-substring-search.nix

Switch from single to double quotes.
Also adds suggestion that I found helpful to descriptions (taken from
the project's [README](https://github.com/zsh-users/zsh-history-substring-search/blob/4abed97b6e67eb5590b39bcd59080aa23192f25d/README.md?plain=1#L71-L74)).
See above.
There may be an argument for adding `$terminfo[kcuu1]` and `$terminfo[kcud1]` to the defaults although I don't know enough about `terminfo` to know if the variable will be defined for everyone's environments.
```
```
- If this PR adds …

zsh: allow variable expansion for `zsh-history-substring-search` key codes

---

modules/programs/borgmatic.nix
tests/modules/programs/borgmatic/basic-configuration.nix
tests/modules/programs/borgmatic/exclude-hm-symlinks-nothing-else.nix
tests/modules/programs/borgmatic/exclude-hm-symlinks.nix
tests/modules/programs/borgmatic/include-hm-symlinks.nix

-------
The configuration file format of borgmatic has changed in version
1.8.0:
https://projects.torsion.org/borgmatic-collective/borgmatic/src/branch/main/NEWS
This commit makes home-manager generates borgmatic's configuration file
using the new format.
Even though the NEWS file indicates that old configuration files are
compatible, this is not 100% the case: empty sections work fine in old
borgmatic but stop working in new ones. I've reported the bug upstream
by email as I couldn't create an account on the forge.
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/ma …

borgmatic: fix configuration generation for version 1.8.0

---

modules/modules.nix
modules/services/cliphist.nix
tests/default.nix
tests/modules/services/cliphist/cliphist-sway-session-target.nix
tests/modules/services/cliphist/default.nix

This adds a module for https://github.com/sentriz/cliphist and is strongly inspired by the clipman module but still has some differences.  
```
```

cliphist: add module

---

tests/modules/programs/firefox/default.nix
tests/modules/programs/firefox/deprecated-native-messenger.nix
tests/modules/programs/firefox/duplicate-profile-ids.nix
tests/modules/programs/firefox/profile-settings.nix
tests/modules/programs/firefox/setup-firefox-mock-overlay.nix
tests/modules/programs/firefox/state-version-19_09.nix

- Make firefox test run in all cases
- Refactor firefox tests to avoid duplication of overlay definition
- Add test for duplicate profile id assertion
```
```

Improve firefox tests

---

docs/installation.adoc

This is necessary.
Without this a new user got
```
error: The option `home-manager.users.X.home.stateVersion' is used but not defined.
```
And was wondering why it's not in this block after I told the user to add it.
```
```

docs: add stateVersion to the nixos module doc

---

.editorconfig

Sets the basic editor settings to home-manager style guide
Many editors support this file and will behave accordingly.
```
```

home-manager: add .editorconfig

---

modules/i18n/input-method/fcitx5.nix

Fixes fcitx5 not working on Qt6-based application due to missing plugins.
```
```
@Kranzes

im/fcitx5: fix missing plugins on Qt6

---

modules/programs/thefuck.nix
tests/modules/programs/thefuck/default.nix
tests/modules/programs/thefuck/integration-enabled-instant.nix

This adds the option to add `--enable-experimental-instant-mode` to the initiation of `thefuck`.
I also moved the init command to a variable to be more DRY.
```
```
@ilaumjd

thefuck: add instant mode option

---

modules/programs/fzf.nix

Since fzf 0.43.0, the `fzf_key_bindings` function is only defined when fish is running interactively, see [1].
This caused errors when entering non-interactive fish shells since we called `fzf_key_bindings` during startup.
[1]: https://github.com/junegunn/fzf/commit/7e89458a3b58c047c10494a5cb53d921fb08b4f3
```
```

fzf: fix fish integration

---

modules/programs/qutebrowser.nix
tests/modules/programs/qutebrowser/default.nix
tests/modules/programs/qutebrowser/greasemonkey.nix

This adds the `programs.qutebrowser.greasemonkey` option, a list of packages that represent greasemonkey userscripts.
This PR finalizes the changes in #3301 since it hasn't been touched in a while and had changes requested recently.
```
```
@somasis @sumnerevans

Qutebrowser userscripts

---

modules/programs/eza.nix

make eza work with nushell
```
```
@cafkafk

make eza work with nushell

---

modules/programs/aerc.nix
tests/modules/programs/aerc/settings.nix

Fix the config paths in the `programs.aerc` module so that they work on darwin.
```
```
@lukasngl

aerc: fix config paths on darwin

---

modules/services/sxhkd.nix
tests/modules/services/sxhkd/service.nix

When a process inside the sxhkd scope is OOM killed, if the OOM policy is set to `stop` then the sxhkd scope itself will exit, terminating every process launched from the keyboard.
This is undesirable, set it to `continue` instead to keep other processes running.
```
```
@0qq

sxhkd: set scope OOMPolicy to continue

---

modules/services/window-managers/hyprland.nix

Duplicates the tray.target from xsession module. Same thing as done for sway (https://github.com/nix-community/home-manager/pull/2713).
```
```
@fufexan

hyprland: add tray.target

---

modules/services/swayidle.nix

this makes the default setup support other window-managers, and is the trend followed by waybar, clipman, copyq, wlsunset.
Changes sway-session to graphical-session, removing the need to set manually on any window manager other than sway.
I can see that this is done by many other tools, so it seems logical to make them match
```
```

swayidle: change target to generic session

---

modules/programs/zsh.nix

This PR simply has the environment variable `ZDOTDIR` export to the shell, so all child processes from the shell can see the variables. Fixes #4286 and topgrade-rs/topgrade#514.
```
```
@ThinkChaos

zsh: made ZDOTDIR export to the shell

---

modules/programs/k9s.nix
tests/modules/programs/k9s/example-hotkey-expected.yml
tests/modules/programs/k9s/example-settings.nix

This PR adds an option to customise k9s hotkeys.
The keyword `hotKey` must be in camel case on the user config and it store the file at `k9s/hotkey.yml`.
```
```
@katexochen

k9s: add hotkey option

---

modules/programs/borgmatic.nix
tests/modules/programs/borgmatic/basic-configuration.nix

This is preparing an upcoming change in borgmatic to make repositories consisting of paths only unusable. This addresses issue #4580 .
This PR:
1. Is backwards compatible. Paths only in the config will be translated to the required `{ path = "path/to/repo"; }`
2. Paths can be given as
```
{
path = "path";
label = "label";
}
```
3. Paths can be given as just `{ path = "path/to/repo"; }`, however, this resolves to a config file, which contains `null` as label, which is forbidden by `borgmatic`.
```
borgmatic-program-basic-configuration: OK
borgmatic-program-exclude-hm-symlinks: OK
borgmatic-program-exclude-hm-symlinks-nothing-else: OK
borgmatic-program-include-hm-symlinks: OK
borgmatic-service-basic-configuration: OK
```
```
```
See …

Prepare borgmatic change

---

modules/lib/maintainers.nix
modules/misc/news.nix
modules/modules.nix
modules/programs/granted.nix
tests/default.nix
tests/modules/programs/granted/default.nix
tests/modules/programs/granted/integration-disabled.nix
tests/modules/programs/granted/integration-enabled.nix

Add granted module https://github.com/common-fate/granted in order to simplify setup, so that others don't encounter the issue referenced in this issue https://github.com/NixOS/nixpkgs/issues/258867.
Granted require an alias set to work correct and they don't take nix into account, hence this module solves the basic setup issue.
```
```

granted: add module

---

modules/services/clipmenu.nix

The clipmenud service uses environment variables for configuration (such as `CM_MAX_CLIPS` to set a history size limit and `CM_SELECTIONS` to pick whether to use clipboard/primary/secondary selection).
With `Environment` as a string there was no way for me to set those additional env vars, but using a list allows me to write:
```nix
systemd.user.services.clipmenu.Service.Environment = ["CM_SELECTIONS=clipboard"];
```
There should probably be an option on the module to allow specifying those vars along with the service, but in the mean time this allows users to append options separately.
I noticed a similar change (#3083) in the git history. I wonder if _all_ services should use lists for `Environment` so that they're more easily modifiable.
```
{long …
```

clipmenu: set Environment to a list

---

modules/config/home-cursor.nix

This commit fixes a typo in XDG data directory link location in the `home.pointerCursor` module where the link is placed at $XDG_DATA_HOME/.icons instead of the correct location $XDG_DATA_HOME/icons.
Fixes https://github.com/nix-community/home-manager/issues/4638
```
```
@rycee

home-cursor: fix typo in XDG data directory link

---

modules/programs/firefox.nix
tests/modules/programs/firefox/default.nix
tests/modules/programs/firefox/duplicate-container-ids.nix
tests/modules/programs/firefox/duplicate-profile-ids.nix
tests/modules/programs/firefox/profile-settings-expected-containers.json
tests/modules/programs/firefox/profile-settings.nix

Generate containers for https://support.mozilla.org/en-US/kb/containers.
```
```

Add support for firefox containers

---

modules/services/swayidle.nix
tests/modules/services/swayidle/basic-configuration.nix

Occasionally, swayidle crashes with a failure to connect to the Wayland session. Ideally, swayidle should automatically restart instead of leaving the system in a vulnerable state.
```
```
@c0deaddict

swayidle: always restart systemd unit on failure

---

modules/programs/firefox.nix
tests/modules/programs/firefox/default.nix
tests/modules/programs/firefox/policies.nix

```
```
/cc @rycee @kira-bruneau

firefox: add support for specifying policies

---

home-manager/home-manager

Given that the default `home.nix` template is meant to be part of the default out of box experience when you run `home-manager init`, I felt like the comment could be made clearer to new-comers so I took a stab.
I'm not sure what component this is... help
```
```
No obvious maintainer

Improve the clarity of the comment home.sessionVariables comment

---

modules/i18n/input-method/fcitx5.nix
modules/misc/qt.nix
tests/modules/misc/qt/qt-platform-theme-gnome.nix
tests/modules/misc/qt/qt-platform-theme-gtk.nix

Remove remaining Qt 4 support from `qt` module since `nixpkgs` does not support Qt 4 anymore.
Export `QT_PLUGIN_PATH` and `QML2_IMPORT_PATH`, necessary for some plugins to work (e.g. `qt6ct`).
Remove top-level `with lib`.
Add missing style mappings.
Add `lxqt` support.
+ Removal of Qt 4 technically is not backwards compatible, but I don't think nobody cares.
```
```

qt: multiple fixes

---

home-manager/home-manager

Backport lazy set profile path variables

---

modules/programs/zsh.nix
tests/modules/programs/zsh/syntax-highlighting.nix

I added an option to enable individual highlighters (eg. bracket highlighting) for zsh.
Closes #4353.
```
```
@ThinkChaos

zsh: allow enabling syntax highlighters

---

modules/misc/qt.nix
tests/modules/misc/qt/default.nix
tests/modules/misc/qt/qt-basic.nix
tests/modules/misc/qt/qt-platform-theme-gtk3.nix

After #4579 the usage of the module when just `qt.enable = true` is set was broken with an evaluation error. This PR fixes it.
```
```

qt: fix basic usage when just `qt.enable = true` is set

---

modules/services/picom.nix
tests/modules/services/picom/picom-basic-configuration-expected.service

Motivation is to be able to use different packages such as [compfy](https://github.com/allusive-dev/compfy).
```
```

picom: use getExe instead of hardcoded binary

---

modules/misc/news.nix
modules/modules.nix
modules/programs/ruff.nix
tests/default.nix
tests/modules/programs/ruff/default.nix
tests/modules/programs/ruff/expected.toml
tests/modules/programs/ruff/ruff.nix

ruff is Python linter and code formatter, written in Rust.
https://docs.astral.sh/ruff/
```
```

ruff: add module

---

modules/programs/bat.nix
tests/modules/programs/bat/bat.nix

Previously, users cannot enable boolean flags like `--show-all` in bat's config since all options were expected to be either a string, or a list of strings. With this commit boolean flags are simply appended to the end of the config if they are set to `true`, and discarded otherwise.
For example, the config
```nix
{
theme = "TwoDark";
show-all = true;
lessopen = false;
}
```
would produce a config file that looks like
```
--theme='TwoDark'
--show-all
```
Fixes #4657
```
```

bat: support boolean flags in config (fixes #4657)

---

modules/programs/fish.nix
tests/modules/programs/fish/abbrs.nix
tests/modules/programs/fish/default.nix

resolves #3706 
https://github.com/fish-shell/fish-shell/releases/tag/3.6.0
I added abbrModule with referring to the functionModule implementation. 
abbrModule follows the "add" subcommand. (https://fishshell.com/docs/current/cmds/abbr.html)
The backward compatibility is preserved by setting the type of fish.shellAbbrs to attrsOf (either str abbrModule). I have confirmed this in the tests added this time.
Also, the --global option is no longer needed. I have removed it from the abbrsStr configuration.
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for …

fish: support flexible abbreviations

---

modules/misc/news.nix
modules/modules.nix
modules/services/signaturepdf.nix
tests/default.nix
tests/modules/services/signaturepdf/basic-configuration.desktop
tests/modules/services/signaturepdf/basic-configuration.nix
tests/modules/services/signaturepdf/basic-configuration.service
tests/modules/services/signaturepdf/default.nix

New signaturepdf service. https://github.com/24eme/signaturepdf/
```
```

signaturepdf: add service

---

modules/programs/firefox.nix
tests/modules/programs/firefox/profile-settings-expected-bookmarks.html

Previously the generated `bookmarks.html` was malformed which lead to the inability to add folders to the toolbar(#4568)
I've also updated the documentation to reflect that the `toolbar` option doesnt add the folder to the toolbar, but that folder is the toolbar itself.
```
```

firefox: fix folders not showing in toolbar (#4568)

---

docs/home-manager-manual.nix

docs: use relative paths to static resources

---

modules/services/caffeine.nix

This pull request removes the `ProtectHome=yes` line from the systemd unit file for this service. This option causes caffeine to be unable to start via the systemd service. See #4696 for more information.
Got a weird error with `nix develop --ignore-environment .#all`:
```
error: executing '/nix/store/q1c2flcykgr4wwg5a6h450hxbk4ch589-bash-5.2-p15/bin/bash': Argument list too long
```
That's the only line of the log file.
```
```
@uvNikita

caffeine: remove ProtectHome service option

---

modules/misc/news.nix
modules/services/window-managers/hyprland.nix
tests/modules/services/window-managers/hyprland/simple-config.conf
tests/modules/services/window-managers/hyprland/simple-config.nix

Add the option sourceFirst to the hyprland module. When this option is enabled source entries will be put near the top of the file, so that the variables declared in other files can be used by the other configuration entries.
Add "source" to the list of important prefixes when the former option is enabled.
Resolves: #4729 
```
```
@fufexan

hyprland: add option sourceFirst

---

modules/programs/msmtp.nix

msmtp: add configurable package

---

docs/manual/installation/nix-darwin.md

The example is missing a `;` which causes this error when you attempt a `darwin-rebuild switch`.
```
error: syntax error, unexpected '=', expecting ';'
at /Users/968713/.nixpkgs/darwin-configuration.nix:17:30:
16|   }
17|   home-manager.users.eve = { pkgs, ... }: {
|                              ^
18|     home.packages = [
```
```
```

docs: fix nix-darwin module configuration example

---

modules/programs/awscli.nix

This change allows one to have writetable config or credentials files by not providing options for the config or the credentials file.
In my case, external tools write to `credentials`, which is why I don't want it to be managed by home-manager.
The change is to wrap the file generation in a `lib.mkIf (cfg.credentials != { })`
```
```

awscli: Only write config files when not empty

---

modules/programs/ssh.nix
tests/modules/programs/ssh/default-config-expected.conf
tests/modules/programs/ssh/forwards-dynamic-valid-bind-no-asserts-expected.conf
tests/modules/programs/ssh/match-blocks-attrs-expected.conf
tests/modules/programs/ssh/match-blocks-match-and-hosts-expected.conf

add addKeysToAgent option to ssh module
```
```

ssh: add addKeysToAgent option

---

modules/services/window-managers/hyprland.nix

When using the previous approach I've always gotten errors that I can't reload config on the .lock file that exists in /tmp when you run a standard configured hyprland.
This commit improves this by using hyprctl to find instances to reload instead.
We can remove the HYPRLAND_INSTANCE_SIGNATURE bogus assignment once https://github.com/hyprwm/Hyprland/issues/4088 is resolved.
Note: I've set my home-manager url to my local repo and run a home-switch, verified that hyprland reloads the config and that there's no error message anymore.
```
``` …

hyprland: improve config reload

---

modules/services/window-managers/hyprland.nix
tests/modules/services/window-managers/hyprland/simple-config.conf

`plugin` and `source` are moved to beginning of config file.
These often are necessary for other configuration, e.g. defining variables or enabling other layouts
```
```
cc @fufexan

hyprland: plugin and source with higher priority

---

modules/programs/yazi.nix
tests/modules/programs/yazi/bash-integration-enabled.nix
tests/modules/programs/yazi/fish-integration-enabled.nix
tests/modules/programs/yazi/nushell-integration-enabled.nix
tests/modules/programs/yazi/zsh-integration-enabled.nix

Passes additional arguments from the ya alias to the yazi command. This allows commands like `ya /etc/nixos` and `ya --help` to be used.
```
```
@XYenon

yazi: pass additional args to ya alias

---

modules/programs/fish.nix

Wrap babelfish version of `hm-session-vars.sh` into a function to ensure this can be safely evaluated at session startup. The current session vars shell script uses a `return` statement and this breaks the generated script.
Ensure that the fzf key bindings function is not called in non-interactive scenarios when fzf does not declare the function.
- This PR wraps the hm-session-vars into a immediately called function.
- This PR does not evaluate fzf_key_bindings in interactive mode
- @yu-re-ka 
- @emilazy

fish: 2 fixes

---

modules/misc/gtk.nix

Haven't dug into any code, but my best guess is GTK 4 ignores it on purpose since devs campaigned against theming: https://stopthemingmy.app
According to the following link, it's fine for users to do it as long as they don't expect support from app devs. And the campaign was against distributions applying custom themes by default.
https://github.com/GradienceTeam/Gradience/tree/0.4.1#%EF%B8%8F-gradience-stopthemingmyapp-and-adwaita-developers
```
```
@rycee

gtk: fix GTK 4 theme being ignored

---

home-manager/home-manager
modules/home-environment.nix

If nix.settings.use-xdg-base-directories is true, the ~/.nix-profile directory may not exist, and home.profileDirectory should be checked intead
```
```
@rycee

home-manager: fix nix profile detection when use-xdg-base-directories == true

---

docs/manual/usage/configuration.md
docs/release-notes/rl-1903.md
docs/release-notes/rl-1909.md
docs/release-notes/rl-2003.md
docs/release-notes/rl-2009.md
docs/release-notes/rl-2105.md
docs/release-notes/rl-2111.md
docs/release-notes/rl-2205.md
docs/release-notes/rl-2211.md
docs/release-notes/rl-2305.md
docs/release-notes/rl-2311.md

This PR updates links in the release notes from rendering as e.g. `opt-home.user` to rendering as `home.user`.
```
```

docs: fix link texts in release notes

---

home-manager/home-manager

Prints the package list in sorted order (ignoring case). Fixes #4788
```
```

home-manager: sort list packages output

---

modules/misc/news.nix
modules/modules.nix
modules/programs/sapling.nix
tests/default.nix
tests/modules/programs/sapling/default.nix
tests/modules/programs/sapling/sapling-basic.nix
tests/modules/programs/sapling/sapling-most.nix

sapling: add module
Adds a program module for [Sapling](https://sapling-scm.com/).
Since Sapling itself is very similar in nature to Mercurial,
`modules/programs/mercurial.nix` was copied to make this module with the
ignore pieces removed (Sapling respects gitignore).

sapling: add module

---

modules/misc/news.nix
modules/modules.nix
modules/programs/gradle.nix
tests/default.nix
tests/modules/programs/gradle/alternate-home-settings.nix
tests/modules/programs/gradle/default.nix
tests/modules/programs/gradle/empty-settings.nix
tests/modules/programs/gradle/example-settings.nix
tests/modules/programs/gradle/external-init-script.gradle
tests/modules/programs/gradle/init-scripts-settings.nix

Introduces a new program called gradle for managing files stored in the
home directory by the [Gradle Build Tool](https://gradle.org). Gradle
uses the $HOME/.gradle folder for all it's configuration.
Features of the new program module are:
- Automatically setting programs.java.enable = true to make a Java
installation available for running Gradle.
- Specifying an alternate Gradle home directory
- Setting of abitrary values for gradle.properties stored inside the
Gradle home directory.
- Defining init scripts either by pointing to a directory that will be
linked to init.d inside the Gradle home directory or by specifying
a list of init script definitions.
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/c …

gradle: add module

---

modules/programs/gradle.nix
tests/modules/programs/thefuck/integration-disabled.nix
tests/modules/services/window-managers/sway/sway-stubs.nix

Due to a recent change in Nixpkgs, the version field is required for the sway package.
```
```

sway: fix failing tests

---

README.md

Fixes broken link to home-manager options in README.md
no code, no checklist

docs: fix broken home-manager options link

---

modules/programs/direnv.nix
tests/modules/programs/direnv/nushell.nix

Nushell allows defining a `ENV_CONVERSIONS` environment variable used to transform the variables passed between nu and the system (by default it will transform `PATH` and `Path` into lists). However, those transformations aren't applied when `load-env`ing them, as nu assumes the string passed to it is intended to be a string.
This PR makes the direnv hook read `ENV_CONVERSIONS` and apply the transformations accordingly. Other than being less surprising/annoying it also prevents some bugs like new binaries in the path not being autocompleted.
The nushell hook is written in such a way that it won't break if any expected value is missing.
While at it, I took the liberty of removing all the `/bin` paths in the file in favor of `lib.getExe` (but that can be removed if not desired 😁 ).
``` …
```

Better direnv nushell integration

---

modules/programs/direnv.nix

I had a base case of works on my machine™️ when testing #4787. I excitedly tried it today after cleaning up my config, and... it didn't work. At all. Turns out I had the direnv hook defined twice in my config and things kept (apparently) working fine.
I can confirm this works on a clean config now 🥲
Btw, I use nushell and direnv daily, so I'd be happy to keep maintaining this module in the foreseeable future :)
```
```

direnv: Fix nushell integration ENV_CONVERSIONS

---

modules/programs/fish.nix
tests/modules/programs/fish/abbrs.nix

Commit 8cedd6 `fish: support flexible abbreviations` removed shell escaping for fish shell abbr values. This was a dangerous breaking change offered little value and made writing abbr expansions more difficult. This commit restores automatic shell escaping of fish abbr values.
Fixes #4710 
In my opinion these abbr should be escaped like they always have been. Currently this config:
```nix
shellAbbrs = {
foo = "printf \"great job\"";
bar = "mkdir $(date %H:%M:%S%Z)";
};
```
will yield:
```
abbr --add -- foo "printf "great job
abbr --add -- bar "mkdir $(date %H:%M:%S%Z)"
```
This `foo` abbr is messed up with the quotes and `bar` abbr's `date` command will run once when the shell is started and hardcode the time into the abbr. This is just confusing behavior that is completely solved by …

fish: escape abbr expansions once again

---

modules/programs/nix-index.nix
modules/programs/zoxide.nix

We don't need these in non-interactive shells, so there's no point initialising them in that case.
```
```

Fish: init command-not-found and zoxide only in interactive shells

---

modules/programs/aerc-accounts.nix
tests/modules/programs/aerc/extraAccounts.expected
tests/modules/programs/aerc/settings.nix

aerc-accounts now is aware of the mbsync.subFolders setting
A account for aerc now uses a `maildirpp://` url if  `mbsync.subFolders` is set accordingly.
Closes #4652 
```
```
I'm not sure if @patwid or @lukasngl 🙈.

aerc-accounts: support for maildirpp

---

modules/programs/firefox.nix

closes https://github.com/nix-community/home-manager/issues/4630
old way of cfg.enableTridactylNative is deprecated upstream
```
```

firefox: update docs example for nativeMessagingHosts

---

modules/services/unison.nix

The service was never marked with a failed state with the previous
approach, which could lead broken synchronisation pair states to go
undetected.
The module now uses a timer instead of unlimited restarts, which does
not have this issue.

unison: better retry/restart reporting failures

---

modules/home-environment.nix

This fixes the error:
error: profile '/nix/var/nix/profiles/per-user/enzime/profile' is incompatible with 'nix-env'; please use 'nix profile' instead
This error occurs when using `home-manager.useUserPackages` set to `true`.
```
```

home-environment: fix incompatible profile error

---

modules/programs/oh-my-posh.nix
tests/modules/programs/oh-my-posh/default.nix
tests/modules/programs/oh-my-posh/nushell.nix

Adds nushell integration for the oh-my-posh module, similar to atuin, zoxide, etc.
```
```
@arjan-s

oh-my-posh: enable nushell integration

---

modules/programs/gh.nix
tests/modules/programs/gh/config-file.nix
tests/modules/programs/gh/warnings.nix

Fixes #4744
~~Currently can cause problems with data migrations so leaving it as a draft until a call can be made on a better solution: https://github.com/nix-community/home-manager/issues/4744#issuecomment-1847220726~~
```
```

gh: automatically insert version key to settings

---

modules/programs/gh.nix

Having the module enabled but never using gh will result in the config file
existing without a hosts.yml. In that scenario we won't have anything to
migrate, so only test for hosts.yml.
Fixes #4812 
```
```
@rycee

gh: test for existence of hosts file

---

modules/services/gpg-agent.nix

NixOS stopped building gtk2 pinentry by default in https://github.com/NixOS/nixpkgs/pull/270266 and it does not appear to me that there is a reasonable other default.
```
```

gpg-agent: don't set a default for pinentry

---

modules/misc/news.nix
modules/modules.nix
modules/services/osmscout-server.nix
tests/default.nix
tests/modules/services/osmscout-server/basic-setup.nix
tests/modules/services/osmscout-server/default.nix

Osmscout-server includes a setting in its UI to create a systemd user service and socket to run the server on demand. This does not function correctly on NixOS, for two reasons:
1. It assumes that the binary path is stable (e.g. /usr/bin/osmscout-server), which is not the case on NixOS.
2. It auto-detects the unwrapped binary path, which doesn't work.
This module allows the user to access the same functionality on NixOS.
```
```

osmscout-server: add module

---

modules/programs/zsh/prezto.nix

fixes #4452 
The example path in `programs.zsh.prezto.pmoduleDirs` is not compatible with shell environment variables like `$HOME`.
Thus it must be replaced with nix compatible variables eg: `home.homeDirectory`.
```
```

zsh prezto: fix path in example for 'prezto.pmoduleDirs'

---

modules/misc/news.nix
modules/modules.nix
modules/programs/sftpman.nix
tests/default.nix
tests/modules/programs/sftpman/assert-on-no-sshkey.nix
tests/modules/programs/sftpman/default.nix
tests/modules/programs/sftpman/example-settings.nix
tests/modules/programs/sftpman/expected-mount1.json
tests/modules/programs/sftpman/expected-mount2.json
tests/modules/programs/sftpman/expected-mount3.json

Add a module for [sftpman](https://github.com/spantaleev/sftpman), an application that handles sshfs/sftp file systems mounting.
```
```

sftpman: add module

---

modules/programs/gh.nix

Closes: https://github.com/nix-community/home-manager/issues/4814
> fix(modules/programs/gh): idempotently consider existing symlinks
>
> > -e file
> >        True if file exists.
> > -f file
> >        True if file exists and is a regular file.
> > [...]
> > -L file
> >        True if file exists and is a symbolic link.
> >
> > (Source: bash(1))
```
```
@Gerschtli, @berbiche, @msfjarvis, @rycee

gh: idempotently consider existing symlinks

---

modules/programs/alacritty.nix
tests/modules/programs/alacritty/default.nix
tests/modules/programs/alacritty/example-settings-expected.toml
tests/modules/programs/alacritty/example-settings-expected.yml
tests/modules/programs/alacritty/settings-merging.nix
tests/modules/programs/alacritty/settings-toml-expected.toml
tests/modules/programs/alacritty/toml_config.nix

The config file is in TOML from 0.13 onwards.
This PR makes the alacritty module compatible with 0.13 while retaining compatibility with previous versions.
```
```

alacritty: make module compatible with alacritty 0.13

---

tests/modules/programs/oh-my-posh/nushell.nix

Fix test failing when run in Darwin.
```
```

oh-my-posh: fix test under Darwin

---

modules/programs/zoxide.nix

Nushell v0.88 removes all support (already deprecated) for `def-env`.
[Zoxide still hasn't released a version which updates their config relying on `def-env`](https://github.com/nix-community/home-manager/issues/4818)
- NOT done. This triggers an error in some other HM-configurable program on my machine. Without having looked into it, this makes me feel like someone else didn't check.
```
$ nix develop --ignore-environment .#all
[160 built, 56 copied (527.6 MiB), 86.0 MiB DL] evaluating derivation 'git+file:///home/x10an14/Documents/github/home-manage
trace: warning: The cfg.enableGnomeExtensions argument for `firefox.override` is deprecated, please add `pkgs.gnome-browser-connector` to `nativeMessagingHosts.packages` instead
error: hash mismatch in fixed-output derivation …
```

bug: Make zoxide v0.9.2 work w/Nushell >= v0.88

---

modules/lib/maintainers.nix
modules/misc/news.nix
modules/modules.nix
modules/programs/bemenu.nix
tests/default.nix
tests/modules/programs/bemenu/basic-configuration.nix
tests/modules/programs/bemenu/default.nix
tests/modules/programs/bemenu/empty-configuration.nix

Add bemenu module https://github.com/Cloudef/bemenu with ability to configure options through `BEMENU_OPTS` environment variable.
Configuration of bemenu globally is done through setting this environment variable as opposed to using a config file as mentioned [here](https://github.com/Cloudef/bemenu/issues/15) and [here](https://github.com/Cloudef/bemenu/issues/158).
```
```

bemenu: add module

---

modules/services/lorri.nix

lorri needs to be able to write to /run/user/uid for the socket, to its own cache directory ~/.cache/lorri and to the directory for gc roots.
I wonder how this ever worked. Did systemd change?
Please backport this change to 23.11
tests pass except for a hash mismatch with `trying https://keys.openpgp.org/pks/lookup?op=get&options=mr&search=0x36cacf52d098cc0e78fb0cb13573356c25c424d4`
```
```
cc @Gerschtli

lorri: unbreak due to too tight sandboxing

---

modules/misc/news.nix
modules/modules.nix
modules/programs/i3blocks.nix
tests/default.nix
tests/modules/programs/i3blocks/default.nix
tests/modules/programs/i3blocks/with-ordered-blocks.nix

Added a configuration module (and tests) for i3blocks.
```
```

i3blocks: added configuration module

---

modules/misc/news.nix
modules/misc/xdg-portal.nix
modules/modules.nix
tests/modules/misc/xdg/default.nix
tests/modules/misc/xdg/portal.nix
tests/modules/misc/xdg/sway-portals-expected.conf

Adds `xdg.portal` options. Fixes https://github.com/nix-community/home-manager/issues/1167
Most of it came from the equivalent NixOS module, with a few changes to work here.
---
The `xdg-desktop-portal` receives requests and forwards them to the right portal, based on:
- [Configurations](https://github.com/flatpak/xdg-desktop-portal/blob/b1a3d1ef86951689227c2418f57e3fb633de2d5f/doc/portals.conf.rst.in#L47)
- Provided by the user (`{~/.config,etc}/xdg-desktop-portal`) and/or DE (i.e. `$prefix/share/xdg-desktop-portal`).
- Can be global (`portals.conf`) or per-DE `foo-portals.conf`
- [Portal definitions](https://github.com/flatpak/xdg-desktop-portal/blob/b1a3d1ef86951689227c2418f57e3fb633de2d5f/src/portal-impl.c#L277)
- Each portal [has …

xdg-portal: add new module

---

modules/programs/xplr.nix

Would close https://github.com/nix-community/home-manager/issues/4520. Please see that issue (and the upstream discussion linked within) for more information.
Change the implementation of the `programs.xplr.plugins` option to correctly set the `package.path` in the written Lua config file.
Specifically, each component path of the `package.path` must have appropriate wildcard/template characters (what Lua calls "interrogation marks" or `?` characters).
Furthermore, due to the need (in the current implementation) to use `programs.xplr.extraConfig` to call `require(<plugin-name>).setup`, this implementation ensures that plugins in the Nix store are inside a predictably-named directory.
Unfortunately not. The `cfg.plugins` option currently takes a list for while it is proposed that it takes …

xplr: fix cfg.plugins implementation for more than one plugin

---

modules/programs/thunderbird.nix
tests/modules/programs/thunderbird/thunderbird-expected-first.js
tests/modules/programs/thunderbird/thunderbird-expected-second.js
tests/modules/programs/thunderbird/thunderbird.nix

The identity's signature  will be configured according to `signature.text` and `signature.showSignature`. Signature commands are not supported by Thunderbird.
```
```
@d-dervishi @jkarlson

thunderbird: configure signature if set

---

.github/workflows/test.yml
docs/release-notes/rl-2405.md
home-manager/home-manager
modules/home-environment.nix
modules/lib-bash/activation-init.sh
modules/misc/uninstall.nix
modules/modules.nix

This adds a Boolean option `uninstall`. When enabled this option will reset side-effecting configurations to their "empty" state. The intent is that this will cause the activation script to remove all managed files and packages.
Doing it this way should hopefully be more robust than the previous solution. It also allows a somewhat more convenient uninstall process when using Flakes; put `uninstall = true` in your existing configuration and then do a switch.
Also add simple uninstall test in CI test job.
```
```

home-manager: internalize uninstall

---

modules/programs/gh.nix

We currently run the migration unconditionally which can cause the `home-manager-$user.service` unit to fail if the gh auth token is stored in the OS keychain, since the keychain is not accessible when the service runs on system boot. Adding a simple test to skip the migration if it's already done works around this problem.
Fixes #4816 
```
```
@rycee

gh: only run migration when required

---

modules/services/listenbrainz-mpd.nix

The ability for listenbrainz-mpd to notify systemd when it's ready was added in 2.3.2: <https://codeberg.org/elomatreb/listenbrainz-mpd/releases/tag/v2.3.2>
listenbrainz-mpd in Nixpkgs is built with the `systemd` feature enabled, so this just works.
```
```
@Scrumplex

listenbrainz-mpd: use sdnotify when possible

---

docs/default.nix
tests/default.nix

Fixes #4879
Depends on https://github.com/NixOS/nixpkgs/pull/280467 being in NixOS unstable.
```
```

Use nmt and nmd from Nixpkgs

---

modules/lib-bash/activation-init.sh

Fixes https://github.com/nix-community/home-manager/pull/4873#issuecomment-1890979485.
```
```
@rycee

home-manager: check profile exists in nixProfileRemove

---

flake.nix

Old URL to Release Notes for deprecated attributes (`extraModules` etc) did not work ("html" vs. "xhtml").
```
```
@rycee @emilazy ?

Update Release Notes URL in flake.nix

---

modules/xsession.nix

After years of my last change adding xplugd to this module, today it crashed and I had to relearn what was going on here in this subsystem.
It seems to have just been a transient error or something from updating my systems. This should let it recover a bit better.
Related: https://github.com/nix-community/home-manager/pull/2450
```
```
@berbiche, merger of last PR.

xsession: allow xplugd to restart on failure

---

modules/programs/firefox.nix
tests/modules/programs/firefox/policies.nix

This PR makes it possible to specify Firefox' extraPolicies through:
programs.firefox.package = pkgs.firefox.override {
extraPolicies = {... }
}
This was possible in the past but was broken by:
3feeb7715584fd45ed1389cec8fb15f6930e8dab
firefox: add support for specifying policies (#4626)
```
```
@jian-lin @rycee

firefox: bring back backward compatibility for extraPolicies

---

modules/programs/gradle.nix

The gradle package from nixpkgs will install a default Java version and
pass it to the gradle executable without polluting the global env.
Users can customize this by overriding the gradle package like so:
```nix
programs.gradle = {
package = (pkgs.gradle.override {
java = pkgs.jdk21;
});
}
```

gradle: Don't enable programs.java

---

modules/programs/gh.nix

We should add `gist.github.com` to credential hosts in `.gitconfig` to match the default behavior of gh. 
```
```
@Gerschtli @berbiche

gh: add github gist to default credential hosts

---

docs/default.nix
tests/default.nix

Turns out pulling nmt and nmd from Nixpkgs causes an IFD, even when the packages are fixed-output derivations. I don't particularly understand why referring to a fixed-output derivation inside Nixpkgs would cause an IFD but after experimenting a bit I could not find any good way to resolve it.
Thus, since Sourcehut is up and well, we can revert to simply fetching nmd and nmt directly.
See discussion in <https://github.com/nix-community/home-manager/pull/4884>.
```
```

docs, tests: revert to fetchTarball for nmd and nmt

---

modules/services/window-managers/hyprland.nix
tests/modules/services/window-managers/hyprland/simple-config.conf
tests/modules/services/window-managers/hyprland/simple-config.nix

The plugin setting in the hyprland config is used both for defining plugin paths and configuring the plugins. This fix removes the silent override of the plugins settings converting them to the `plugin:<name> { ...settings }` syntax.
```
```
@fufexan

hyprland: do not override existing plugins settings in config

---

modules/programs/mcfly.nix

This PR adds integration for [mc-fly](https://github.com/bnprks/mcfly-fzf), what it does it just adds `eval "$(${pkgs.mcfly-fzf}/bin/mcfly-fzf init $shell)"` to each of the shells (bash, zsh, and fish) right after mcfly's initialization script. This is ensures mcfly-fzf is loaded in order (it has to be loaded after mcfly); also checks if any of the shell integrations are disabled (since if those are disabled, then there's no way to add the initialization script for it anyway). 
```
```
@marsam 
@aisamu

mcfly: Add mcfly-fzf integration

---

modules/services/window-managers/hyprland.nix
tests/modules/services/window-managers/hyprland/simple-config.conf

Sorry for being back so quickly, but digging in the hyprland source code (and debugging my config) I found out that the syntax that I used in #4915 will lead to a [silent](https://github.com/hyprwm/Hyprland/blob/f40e382fc6208d4fe2e53581ea27510cb62417dd/src/config/ConfigManager.cpp#L455C13-L455C40) wrong config parsing. The result is that all the sections after a `plugin:name` section are ignored (just the sections, not the fields).
There is no documentation, just the [source code](https://github.com/hyprwm/Hyprland/blob/main/src/config/ConfigManager.cpp#L1574). 
With this update the plugins paths are generate right before the full config and the plugins settings are generated like the other fields.
```
```
See …

hyprland: change plugins settings generation

---

tests/modules/programs/mise/custom-settings.nix

`assertPathExists` is not a valid `nmt` assertion. I think I copy-pasted `assertPathNotExists` and removed `Not` 😓 
```
```
@pedorich-n

mise: fix test

---

modules/programs/bemenu.nix
tests/modules/programs/bemenu/basic-configuration.nix

The CLI option --width-factor controls the width of the launcher and is set to a value between 0-1.
Change allowed type list from `[str int bool]` to `[str float bool]` to make it possible to set --width-factor which requires float value.
```
```
- ~Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).~
@omernaveedxyz

bemenu: allow using floats to set width-factor in bemenu.settings

---

modules/programs/zoxide.nix

Hi, this is my first pull request to home-manager, so I would appreciate if someone could double-check that my fix does not break backwards compatibility (or anything else). I don't think it does, as the current version of home-manager has the broken versions. Please let me know if I'm wrong here.
Since nushell 0.89, automatically spreading lists is deprecated. This commit introduces a string replace for the zoxide init script to replace the deprecated code.
See: https://github.com/ajeetdsouza/zoxide/issues/662
Fixes: #4916
```
```
- If …

zoxide: fix nushell 0.89 deprectation

---

modules/programs/tealdeer.nix
tests/default.nix
tests/modules/programs/tealdeer/default-settings.nix
tests/modules/programs/tealdeer/default.nix

Since by default `tldr`'s cache [auto-update is disabled](https://dbrgn.github.io/tealdeer/config_updates.html#auto_update) this activation script will call `tldr --update` on home-manager switch. 
Build  similar to [`programs.bat`](https://github.com/nix-community/home-manager/blob/2d47379ad591bcb14ca95a90b6964b8305f6c913/modules/programs/bat.nix#L162-L168)
```
```
No maintainer

tealdeer: add cache update activation script

---

docs/release-notes/rl-2405.md
home-manager/home-manager
lib/bash/home-manager.sh
modules/files.nix
modules/home-environment.nix
modules/launchd/default.nix
modules/lib-bash/activation-init.sh
modules/misc/dconf.nix
modules/misc/uninstall.nix
modules/misc/xdg-user-dirs.nix
modules/misc/xfconf.nix
modules/programs/bat.nix
modules/programs/gh.nix
modules/programs/gpg.nix
modules/programs/mbsync.nix
modules/programs/mu.nix
modules/programs/taskwarrior.nix
modules/programs/vscode.nix
modules/services/dropbox.nix
modules/systemd-activate.sh
modules/targets/darwin/fonts.nix
modules/targets/darwin/keybindings.nix
modules/targets/darwin/user-defaults/default.nix
tests/modules/programs/gpg/mutable-keyfiles.nix
tests/modules/programs/mu/basic-configuration.nix
xgettext

This adds the `dryRun` helper function. It deprecates the `DRY_RUN_CMD` and `DRY_RUN_NULL` variables.
```
```

Deprecate `DRY_RUN_CMD` and `DRY_RUN_NULL`

---

modules/programs/firefox.nix

Fixes #1586, #1487
Links FF native messaging hosts to ~/.mozilla uses cfg.package.nativeMessagingHosts if it's defined, but for ease of use we also add a package list to the module (easier discovery).
I haven't gotten native messaging to work without linking to ~/.mozilla, not sure what I'm doing wrong, but this solves the issue.
```
```

firefox: implement native messaging hosts

---

modules/programs/firefox.nix
tests/modules/programs/firefox/container-id-out-of-range.nix
tests/modules/programs/firefox/default.nix

`userContextIdInternal.webextStorageLocal` is used by certain extensions without they don't work correctly <https://searchfox.org/mozilla-central/rev/762f24e00a9548d80ebba1b985c871ba6d9b829d/toolkit/components/contextualidentity/ContextualIdentityService.sys.mjs#93-96>. `userContextIdInternal.thumbnail` is some default added by firefox, so I just added it as well.
> This userContextId is used by ExtensionStorageIDB.jsm to create an IndexedDB database
> opened with the extension principal but not directly accessible to the extension code
> (do not change the userContextId assigned here, otherwise the installed extensions will
> not be able to access the data previously stored with the browser.storage.local API).
```
```
See …

firefox: add default containers

---

modules/default.nix

home-manager.lib.homeManagerConfiguration now has an additional attribute that can be used to extend a home manager configuration with additional modules outside the project tree.
It works similar to the result of lib.nixosSystem from nixpkgs. This PR closes #4943 .
```
```
@rycee

core: add extendModules attribute to homeManagerConfiguration result

---

modules/services/network-manager-applet.nix

The Network Manager Applet package provides, for example, some icons that are good to have accessible in an XDG data directory.
```
```

network-manager-applet: add XDG data directory

---

modules/programs/firefox.nix

https://wiki.mozilla.org/WebExtensions/Native_Messaging
```
Mac 	User 	~/Library/Application Support/Mozilla/NativeMessagingHosts/<name>.json
Linux 	User 	~/.mozilla/native-messaging-hosts/<name>.json
```
Related: #4952 
```
```

firefox: fix darwin NativeMessagingHostsPath

---

modules/misc/news.nix
modules/modules.nix
modules/services/wob.nix
tests/default.nix
tests/modules/services/wob/default.nix
tests/modules/services/wob/wob-service-expected.ini
tests/modules/services/wob/wob-service-expected.service
tests/modules/services/wob/wob-service-expected.socket
tests/modules/services/wob/wob-service.nix

Adds a HM module for [wob](https://github.com/francma/wob).
The only odd thing about this one is that the ini config's default section has to be an empty string (`""`).
```
```

wob: add module

---

lib/bash/home-manager.sh
modules/systemd-activate.sh

home-manager: remove the export of `run`

---

modules/programs/tealdeer.nix

Add option to disable updating tealdeer cache on activation, since it's a network operation it can be quite annoying on shitty connections like trains and such.
```
```

tealdeer: add option to toggle update on activation

---

modules/programs/helix.nix

The change to languages.toml referred to by the comment was released
with helix 23.10 which is the version currently on nixpkgs 23.11. See
- https://helix-editor.com/news/release-23-10-highlights/#multiple-language-servers
- https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/applications/editors/helix/default.nix#L5

helix: remove outdated comment

---

tests/modules/i18n/input-method/fcitx5-stubs.nix
tests/modules/programs/beets/mpdstats.nix
tests/modules/programs/mpv/mpv-example-settings.nix
tests/modules/programs/mpv/mpv-invalid-settings.nix
tests/modules/programs/mpv/mpv-stubs.nix

Try to reduce the download size when running tests.
```
```

tests: reduce closure sizes

---

modules/services/window-managers/hyprland.nix

`/tmp/hypr` must be present so `hyprctl` doesn't crash.
```
```

hyprland: fix hyprctl crash

---

modules/programs/vdirsyncer-accounts.nix
modules/programs/vdirsyncer.nix

Saves some unnecessary cycles and store entries.
```
```
@teto

vdirsyncer: only create postHook script when non-empty

---

modules/programs/kitty.nix
tests/modules/programs/kitty/example-settings-expected.conf

This ensures that `KITTY_SHELL_INTEGRATION` is manually set to the user's `shellIntegration.mode`. This is necessary because the variable is not automatically set in subshells, `kitty @ launch`, etc. `shellIntegration.mode` is also now ensured to always contain `no-rc`.
Note that this is intended behavior, `KITTY_SHELL_INTEGRATION` is not always guaranteed to be set in all cases: https://github.com/kovidgoyal/kitty/issues/6783
```
```

kitty: always export `KITTY_SHELL_INTEGRATION`

---

modules/programs/vscode.nix

In order to manage the extensions and configs from openvscode-server, the only additional requirement was some mapping missing between the name of the package and the default configDir/extensionDir
```
```

vscode: Add openvscode-server to the vscode module.

---

modules/programs/mcfly.nix

Adds a configurable option to the mcfly program to set `MCFLY_INTERFACE_VIEW` envvar.
```
```

mcfly: add interfaceView option

---

modules/modules.nix
modules/services/nix-gc.nix
tests/default.nix
tests/modules/services/nix-gc-darwin/basic.nix
tests/modules/services/nix-gc-darwin/default.nix
tests/modules/services/nix-gc-darwin/expected-agent.plist
tests/modules/services/nix-gc/basic.nix
tests/modules/services/nix-gc/default.nix
tests/modules/services/nix-gc/expected.service
tests/modules/services/nix-gc/expected.timer

Add `nix-gc` module that configures systemd unit for linux and launchd agent for macOS to automatically run the `nix-collect-garbage` executable at a specified `frequency`.
```
```

nix-gc: add automatic garbage collector for nix

---

docs/home-manager.1
home-manager/home-manager

Check VISUAL for a visual editor before EDITOR, as per Unix convention
and as followed by Git, crontab, mutt, and other tools.

home-manager: Check VISUAL before EDITOR for editor

---

modules/services/swayosd.nix
tests/modules/services/swayosd/swayosd.nix

Replaces swayosd dinary with swayosd-server new one.
Closes  #4857
```
```

swayosd: update executable

---

modules/programs/neomutt.nix
tests/modules/programs/neomutt/hm-example.com-expected
tests/modules/programs/neomutt/hm-example.com-gpg-expected.conf
tests/modules/programs/neomutt/hm-example.com-msmtp-expected.conf
tests/modules/programs/neomutt/hm-example.com-no-folder-change-expected.conf
tests/modules/programs/neomutt/hm-example.com-signature-command-expected
tests/modules/programs/neomutt/hm-example.com-signature-expected
tests/modules/programs/neomutt/hm-example.com-starttls-expected
tests/modules/programs/neomutt/neomutt-expected.conf
tests/modules/programs/neomutt/neomutt-not-primary-expected.conf
tests/modules/programs/neomutt/neomutt-with-binds-expected.conf
tests/modules/programs/neomutt/neomutt-with-named-mailboxes-expected.conf

Move `crypt_use_gpgme` configuration option from the account config to the global config.
Fixes config load error since newer versions of neomutt don't allow `crypt_use_gpgme` to be loaded dynamically (from folder hooks).
```
```
@fpletz @ncfavier @sumnerevans

neomutt: move crypt_use_gpgme from account to global config

---

modules/lib/maintainers.nix
modules/misc/news.nix
modules/modules.nix
modules/programs/jetbrains-remote.nix

This adds a module that allows you to select the IDEs accessible using gateway and a ssh connection
```
```

Jetbrains remote dev

---

modules/programs/zellij.nix
tests/modules/programs/zellij/enable-shells.nix

Use exact command when calling `zellij` instead of relying on it being in the `PATH` already.
```
```

zellij: use exact cmd instead of relying on $PATH being set

---

modules/services/window-managers/i3-sway/sway.nix
tests/modules/services/window-managers/sway/sway-bar-focused-colors.conf
tests/modules/services/window-managers/sway/sway-bindkeys-to-code-and-extra-config.conf
tests/modules/services/window-managers/sway/sway-default.conf
tests/modules/services/window-managers/sway/sway-followmouse-expected.conf
tests/modules/services/window-managers/sway/sway-followmouse-legacy-expected.conf
tests/modules/services/window-managers/sway/sway-modules.conf
tests/modules/services/window-managers/sway/sway-null-package.conf
tests/modules/services/window-managers/sway/sway-post-2003.conf
tests/modules/services/window-managers/sway/sway-workspace-default-expected.conf
tests/modules/services/window-managers/sway/sway-workspace-output-expected.conf

workspace 10 is part of upstream's default config, but was missing in home-manager.
The initial "sway: add module" PR (#829, 02d60400035028d4c8affab24557344ca371b9fd) went through multiple iterations and had workspace 10 included for a brief moment. Until the author removed it in a force-push commenting
> Have removed the last change which added bound ${modifer}+0 to workspace number 10 as this messed up workspace numbering in sway.
https://github.com/nix-community/home-manager/pull/829#issuecomment-575087553
The reason might have been, that sway used to sort the workspaces in the order they appeared in the config.
Attribute sets in nix are sorted, but not "naturally sorted", meaning `bindsym Mod1+0 workspace number 10` comes before `bindsym Mod1+0 workspace number 1`.
It's unclear if …

sway: fix workspace 10 missing from default config

---

modules/services/imapnotify.nix
tests/modules/services/imapnotify/imapnotify-config.json
tests/modules/services/imapnotify/imapnotify.nix

Since version 2.3.10 goimapnotify supports starttls. In version 2.3.11 a typo in the settings was fixed, using tlsOptions.starttls to enable it.
This commit enables starttls in the goimapnotify config file if it is enabled in the email account's imap settings.
Global tests failed because of a unrelated problem, but the module tests succeed.
```
```

imapnotify: enable STARTTLS if enabled in email account config

---

modules/programs/emacs.nix

fix annoying warning:
```
building the system configuration...
trace: warning: `overrideScope'` (from `lib.makeScope`) has been renamed to `overrideScope`.
```
https://github.com/NixOS/nixpkgs/blob/master/lib/customisation.nix#L328

emacs: use `overrideScope` instead of `overrideScope'`

---

tests/modules/programs/mpv/mpv-stubs.nix
tests/modules/programs/neomutt/hm-example.com-imap-expected.conf
tests/modules/programs/neomutt/neomutt-with-imap-expected.conf
tests/modules/programs/neomutt/neomutt-with-imap-type-mailboxes-expected.conf

mpv: create doc output in tests

---

flake.nix
home-manager/home-manager
tests/integration/default.nix
tests/integration/nixos/basics.nix
tests/integration/standalone/alice-flake-init.nix
tests/integration/standalone/alice-home-init.nix
tests/integration/standalone/alice-home-next.nix
tests/integration/standalone/flake-basics.nix
tests/integration/standalone/standard-basics.nix

This introduces some rudimentary integration tests using the NixOS
test framework. The intent is to better catch regressions when doing
more elaborate changes that may affect overall Home Manager behavior.
Note, the tests are currently not run automatically.
```
```

tests: add basic integration tests

---

home-manager/home-manager
home-manager/po/home-manager.pot
modules/po/hm-modules.pot

This should ensure that the necessary profile directories are created. Also fix an incorrect log message.
```
```

home-manager: add Nix sanity check

---

modules/programs/tealdeer.nix
tests/modules/programs/tealdeer/custom-settings.nix
tests/modules/programs/tealdeer/default-settings.nix
tests/modules/programs/tealdeer/default.nix

As discussed in https://github.com/nix-community/home-manager/pull/4968#issuecomment-1927480035:
- Cache update on HM activation removed;
- `freeformType` settings;
- More tests added;
- Platform-dependent tests;
- Maintainer added;
```
```
N/A

tealdeer: module improvements

---

modules/programs/jujutsu.nix

This issue has come up before, and the recommendation was to remove the shell completion logic from Home Manager. This pull request now does just that.
- https://github.com/martinvonz/jj/pull/2945
- https://github.com/nix-community/home-manager/pull/5016#issuecomment-1947449541
- https://github.com/nix-community/home-manager/pull/5037#pullrequestreview-1888843990
``` sh
$ for sh (--bash --fish --zsh); jj util completion "$sh" >/dev/null
Warning: `jj util completion --bash` will be removed in a future version, and this will be a hard error
Hint: Use `jj util completion bash` instead
Warning: `jj util completion --fish` will be removed in a future version, and this will be a hard error
Hint: Use `jj util completion fish` instead
Warning: `jj util completion --zsh` will be removed in a …
```

jujutsu: Remove superfluous shell completion

---

modules/programs/zsh.nix

Zsh configuration breaks when `programs.zsh.dotDir` is set to a path containing spaces due to the spaces not being escaped. This PR fixes that by surrounding the path in quotes in the resulting Zsh startup scripts.
The motivation for this is, on Darwin, setting `xdg.configHome` to be `~/Library/Application Support` to try to follow file system conventions on macOS.
```
```
@uvNikita (based on `git blame`)

zsh: fix broken ZDOTDIR when path contains spaces

---

modules/services/lorri.nix

- **lorri: systemd allow access to cache directories**
Lorri fails builds with fetchers if it can't write to .cache/nix;
This PR adds that to ReadWrite
```
```
@gerschtli
Am also adding myself as a maintainer, as I've been doing my best to maintain Lorri itself.

lorri service cachedir

---

modules/services/window-managers/hyprland.nix

Fixes hyprctl erroring out due to HIS.
Fixes https://github.com/hyprwm/Hyprland/issues/4825.
```
```
@Lillecarl do you mind reviewing this?

Hyprland: fix config reload

---

modules/services/window-managers/river.nix
tests/modules/services/window-managers/river/init

exec does not do any shell parsing and does not understand the && which is how the extraCommands are added after dbus activation. There seems to be no clear need for exec here anyway so just remove it and allow shell parsing.
The error you'll get when there are extraCommands (and there are by default) looks like this:
```sh
bash: /nix/store/3n8s5m00h7qqvbmahhr4fxskkbz85z03-dbus-1.14.10/bin/dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP NIXOS_OZONE_WL XCURSOR_THEME XCURSOR_SIZE && systemctl --user stop river-session.target && systemctl --user start river-session.target: No such file or directory
```
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more …

river: fix systemd activation

---

tests/modules/i18n/input-method/fcitx5-stubs.nix
tests/stubs.nix

Should hopefully fix the tests. I guess there may be more work to fully support qt6 but I'll leave that for somebody else.
CC recent committers @thiagokokada @sefidel
```
```

fcitx5: fix reference to fcitx5-with-addons

---

modules/accounts/contacts.nix
modules/programs/khal-accounts.nix
modules/programs/khal-calendar-accounts.nix
modules/programs/khal-contact-accounts.nix
modules/programs/khal.nix
tests/modules/programs/khal/config.nix
tests/modules/programs/khal/khal-config-expected

Currently, birthday calendars added to Khal via `accounts.contact` throw `error: attribute 'type' missing`. This PR:
- Fixes a bug to correctly add `khal.type = "birthdays"` to these calendars;
- Moves options `color`/`priority` to global Khal configuration (these options can also be set for birthday calendars, and Nix currently throws an error if non-defined);
- Adds multiple calendars for each contact collection (fixing an issue similar to #4531):
- New option `khal.collections`;
- Also supports null-collections (as seen [here](https://github.com/nix-community/home-manager/issues/4531#issuecomment-1748332523));
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for …

khal: fix contact integration

---

modules/services/pueue.nix
tests/integration/nixos/basics.nix
tests/integration/standalone/alice-home-next.nix
tests/integration/standalone/flake-basics.nix
tests/integration/standalone/standard-basics.nix

This adds a service (pueue since it is pretty light weight) to the integration tests.
Note, this also fixes #4295 by including a `shared` field by default.
```
```

Include service in integration tests

---

modules/accounts/calendar.nix
modules/programs/khal-calendar-accounts.nix

This PR addresses all problems (mentioned in https://github.com/nix-community/home-manager/issues/4675) that multiple users had while trying to setup the calendar submodule with khal (and vdirsyncer).
```
```

Simplify calendar setup

---

modules/services/window-managers/i3-sway/i3.nix
modules/services/window-managers/i3-sway/sway.nix

I'm currently not planning to switch back to sway so I would like to remove myself.
```
```

i3/sway: remove sebtm maintainer

---

modules/programs/gallery-dl.nix
tests/modules/programs/gallery-dl/gallery-dl.nix

Adds `package` option to `programs.gallery-dl` so that users can customize the package.
```
```

gallery-dl: add package option

---

modules/programs/vdirsyncer-accounts.nix
modules/programs/vdirsyncer.nix

Vdirsyncer options for calendar/contacts accounts specify the "verify" option as types.bool. However, this is not how vdirsyncer treats the option - it expects a path to certificate to verify against.
```
```
@teto

vdirsyncer: fix verify option type

---

modules/programs/zsh.nix
tests/modules/programs/pls/zsh.nix

This patch improves `programs.zsh.shellAliases` so that it doesn't choke on an alias whose name begins with (or consists entirely of) a `-`.
**_yes, but_ something failed and I'm not sure it's related to my change:**
```console
home-manager on  zsh-aliases 
❯ nix develop --ignore-environment .#all
error: hash mismatch in fixed-output derivation '/nix/store/1gc9h74vp75ibbvbhqlkgrm044v6zkwq-lookup?op=get-options=mr-search=0x36cacf52d098cc0e78fb0cb13573356c25c424d4.drv':
specified: sha256-9Zjsb/TtOyiPzMO/Jg3CtJwSxuw7QmX0pcfZT2/1w5E=
got:    sha256-Pvm0CpH13pvnD/c+IJAkRElR5/IhZt8pg7RjT/dZdfM=
error: 1 dependencies of derivation '/nix/store/q63vwwi40imdsxcdw53nkb9lx9g6a9md-gpg-pubring.drv' failed to build
error: 1 dependencies of derivation …
```

zsh: support shellAliases beginning with a `-`

---

modules/misc/xdg-user-dirs.nix

When a non-directory, such as a file or a dead symlink, already exists, mkdir -p fails with "cannot create directory ‘...’: File exists".
This is a problem when, for example, a symlink points to a directory on a filesystem that isn't mounted yet.
This PR simply checks for an existing symlink before calling mkdir.
```
```
@pacien

xdg-user-dirs: check for existing symlink

---

modules/programs/himalaya.nix
tests/modules/programs/himalaya/basic-expected.toml

Account configurations are now prefixed by `accounts.` in the TOML file, hence the modification of the home manager module.
I open this PR as draft because the nixpkgs PR is not yet merged: https://github.com/NixOS/nixpkgs/pull/291335
See the full changelog at https://github.com/soywod/himalaya/releases/tag/v1.0.0-beta.3
```
```

himalaya: adjust code for v1.0.0-beta.3

---

modules/programs/rio.nix
tests/modules/programs/rio/example-settings.nix

`rio` now uses the same config location for both Linux and macOS: 
> MacOS and Linux configuration file path is `~/.config/rio/config.toml`.
Ref: https://raphamorim.io/rio/docs/configuration-file
```
```
@otavio

fix(rio): use XDG config for both linux and darwin

---

modules/lib/maintainers.nix
modules/misc/news.nix
modules/modules.nix
modules/programs/ranger.nix
tests/default.nix
tests/modules/programs/ranger/configuration-rc.conf
tests/modules/programs/ranger/configuration-rifle.conf
tests/modules/programs/ranger/configuration.nix
tests/modules/programs/ranger/default.nix

Add module `programs.ranger`
Supersedes #3264 
```
```

ranger: add module

---

lib/bash/home-manager.sh
modules/files.nix
modules/home-environment.nix
modules/lib-bash/activation-init.sh

This pull request contains two changes:
Adds a `--quiet` flag to `run`, which functions similarly to (but is mutually exclusive with) its existing `--silence` flag. When applied, this redirects _only_ standard output (unlike `--silence`, which also redirects standard error) to `/dev/null`, allowing errors and other diagnostics to be seen. This commit also replaces various usages of `--silence` with `--quiet` where the latter seems more appropriate.
Before this change, gratuitous suppression of diagnostic output resulted in me running into the following (rather confusing) failure message:
```
Feb 25 00:51:03 dysnomia systemd[1]: Starting Home Manager environment for v...
Feb 25 00:51:03 dysnomia hm-activate-v[2558844]: Starting Home Manager activation
Feb 25 00:51:04 dysnomia …
```

Fix activation under Nix 2.3 and stop run function from discarding error messages

---

modules/programs/borgmatic.nix
tests/modules/programs/borgmatic/both-sourcedirectories-and-patterns.nix
tests/modules/programs/borgmatic/default.nix
tests/modules/programs/borgmatic/neither-sourcedirectories-nor-patterns.nix
tests/modules/programs/borgmatic/patterns-configuration.nix

Add option option for pattern matching in Borgmatic backups. It is mutually exclusive with the existing `sourceDirectories` option, so assertions have been added to make sure that both aren't set at once (but also that at least one of them is).
```
```
@DamienCassou

borgmatic: add option for pattern matching

---

modules/targets/generic-linux.nix

Fixes warnings about the non-existent `~/.nix-defexpr` folder when using `use-xdg-base-directories = true`.
Example:
```
warning: Nix search path entry '/home/user/.nix-defexpr/channels' does not exist, ignoring
Starting Home Manager activation
Activating checkFilesChanged
Activating checkLinkTargets
Activating writeBoundary
Activating installPackages
replacing old 'home-manager-path'
installing 'home-manager-path'
Activating dconfSettings
Activating linkDesktopApplications
Activating linkGeneration
Cleaning up orphan links from /home/user
No change so reusing latest profile generation 13
Creating home file links in /home/user
Activating onFilesChange
Activating reloadSystemd
warning: Nix search path entry '/home/user/.nix-defexpr/channels' does not exist, ignoring
```
```
{component}: …
```

targets/generic-linux: use xdg path for defexpr

---

modules/programs/bat.nix

Fixes #4826
When `programs.bat.enable = true` and `~/cache` is present, activation currently fails due to `cache` in `bat cache --build` being interpreted as a path instead of a subcommand.
This PR modifies the activation script to run `bat cache --build` in an empty directory.
```
```
@lovesegfault

programs.bat: handle existing cache in activation script

---

modules/programs/pqiv.nix
tests/modules/programs/pqiv/settings.nix

Adds a `extraConfig` text option to `programs.pqiv`, so that non-INI config such as `actions` or `keybindings` can be added.
```
```
@donovanglover

pqiv: add extraConfig option

---

modules/programs/eza.nix

This commit replaces the enableAliases option with enable$SHELLIntegration options for each shell. This lets works more similarly to other programs in home-manager and lets users choose which shell's should use these aliases. 
```
```
@cafkafk

eza: replaced enableAliases with shell integration options

---

README.md

The option search website has moved to a new location. This is an README.md update.

new location to home-manager-option-search

---

modules/programs/eza.nix

Using `mkDefault` for the individual aliases makes it easier to override or
replace individual entries by the user, without having to use `mkForce` which
is often confusing for new users.
```
```
* @cafkafk

eza: use `mkDefault` for aliases

---

modules/programs/offlineimap.nix

Fixes #5097
```
```
@teto Do you know if this makes sense? Should it be `starttls = imap.tls.useStartTls` instead, although that seems a bit odd to me. Thanks!

offlineimap: disable starttls if tls is disabled

---

modules/services/gpg-agent.nix
tests/modules/services/gpg-agent/default-homedir.nix

Fix a reference to a non-existent variable.
```
```
@rycee

fix(gpg-agent): fix broken variable reference

---

modules/services/fusuma.nix
tests/modules/services/fusuma/expected-service.service
tests/modules/services/fusuma/service.nix
tests/modules/services/fusuma/settings.nix

This PR adds `pkgs.xorg.xprop` and `pkgs.xdotool` to the environment for `systemd.user.services.fusuma`, which is needed for fusuma to work correctly.
This PR also fixes #4945 by changing the name of the config file that will be created from `config.yaml` to `config.yml`.
```
```
@iosmanthus @pluiedev

fusuma: fix #4945 and add missing dependencies

---

modules/programs/qutebrowser.nix
tests/modules/programs/qutebrowser/keybindings.nix

The documentation for the option says...
> If you want a default binding to be passed through to the website, bind it to null.
but if you actually try to set a key to `null`, it causes an error.
> A definition for option `programs.qutebrowser.keyBindings."<Ctrl+Shift+Tab>".normal is not of type 'strings concatenated with " ;; "'.
So this commit implements unbinding as it is documented.
```
```

programs.qutebrowser.keyBindings: actually implement unbinding

---

modules/misc/news.nix
modules/modules.nix
modules/services/activitywatch.nix
tests/default.nix
tests/modules/services/activitywatch/basic-setup.nix
tests/modules/services/activitywatch/default.nix
tests/modules/services/activitywatch/empty-server-settings.nix

Adding [ActivityWatch](https://activitywatch.net/) service which is [fully intended to be local for the user](https://docs.activitywatch.net/en/latest/remote-server.html) so adding this to home-manager is a nice fit.
This service is fully deployed and managed by systemd instead of the [traditional way of using it by running `aw-qt`](https://docs.activitywatch.net/en/latest/getting-started.html#usage) which opens up a system tray.
```
```

activitywatch: add module

---

modules/lib/generators.nix
modules/programs/senpai.nix
tests/default.nix
tests/lib/generators/default.nix
tests/lib/generators/tokdl.nix
tests/lib/generators/toscfg-empty.nix
tests/lib/generators/toscfg-err-dir-empty-name.nix
tests/lib/generators/toscfg-example-result.txt
tests/lib/generators/toscfg-example.nix
tests/modules/programs/senpai/default.nix
tests/modules/programs/senpai/empty-settings-expected.conf
tests/modules/programs/senpai/empty-settings.nix
tests/modules/programs/senpai/example-settings-expected.conf
tests/modules/programs/senpai/example-settings.nix

Switch to SCFG format for the configuration file following an upstream change. Supersedes #4086. Closes #2534.
Related to #4614.
Change is not backwards compatible because upstream renamed (nick -> nickname, addr -> address) and depreceted (no-tls) options.
```
```
@malte-v @ncfavier @jleightcap

senpai: switch to scfg format

---

modules/services/nix-gc.nix

The systemd.time documentation defines the shorthands `daily` and
`minutely` which are currently not included in the nix-gc module.
This commit adds the `daily` option, but omits `minutely` since it's not
a timescale that would make sense to run a gc for.
https://www.freedesktop.org/software/systemd/man/latest/systemd.time.html
---
Note that I am unable to test if the daily option works under MacOS. It should, as it follows the same pattern as the other date declarations. Still, would love someone to check it.
```
```
- If this PR adds a …

nix-gc: add daily frequency option

---

modules/programs/zsh/prezto.nix

See https://github.com/nix-community/home-manager/issues/2255.
This causes a really noticeable slowdown that is quite hard to track down!
Implements the fix from https://github.com/nix-community/home-manager/issues/2255
```
```
@NickHu

Enable caseSensitive by default in prezto module

---

modules/i18n/input-method/kime.nix
tests/modules/i18n/input-method/kime-configuration.nix

Switches the kime configuration format to use unstructured text. This is necessary since version 3 and upwards use yaml tags. Closes #4261. Something like this was already done in nixpkgs, cf. https://github.com/NixOS/nixpkgs/pull/211937.
Kime has updated its configuration format following version 3 to use the yaml tag functionality. This is not supported by the yaml tooling in nixpkgs, leaving kime essentially unusable in home-manager (or at least unconfigurable). This PR switches the configuration setting to an unstructured text format, which is unfortunate but at least usable.
```
``` …

kime: fix configuration

---

modules/misc/xdg-portal.nix
tests/modules/misc/xdg/portal.nix

Nixpkgs has recently(ish) made a few major changes to its xdg-desktop-portal package (https://github.com/NixOS/nixpkgs/pull/268197), which silently breaks our module here:
- The NIXOS_XDG_DESKTOP_PORTAL_CONFIG_DIR variable patch has been removed (in favor of putting portal configurations in /etc or XDG_CONFIG_HOME).
- A new variable, NIX_XDG_DESKTOP_PORTAL_DIR, was introduced in a patch to avoid setting XDG_DESKTOP_PORTAL_DIR (which also affected portal configuration reading, not only portal definitions)
I updated our module to match the changes, but this breakage also made me revisit this module and look into some improvements.
Long story short, I think it's worth it to make it more similar to the NixOS one, as it will make behavior more predictable and consistent.
The main change is …

xdg-portal: update env vars, match nixos module

---

modules/accounts/calendar.nix
modules/programs/vdirsyncer-accounts.nix
modules/programs/vdirsyncer.nix

Fixes #4399 
```
```
@pjones @teto

vdirsyncer: add urlCommand and userNameCommand options

---

home-manager/home-manager
modules/lib-bash/activation-init.sh

The `-q` option does not actually exist, nix-build expects `--quiet`.
```
```

home-manager: fix nix-build option `-q`

---

modules/programs/antidote.nix

The antidote module hardcodes `/nix/store`, which breaks in the (rare!) case where a custom store directory is being used.
```
```

antidote: use builtins.storeDir rather than /nix/store

---

modules/programs/khal-accounts.nix
modules/programs/khal.nix
tests/modules/programs/khal/config.nix
tests/modules/programs/khal/khal-config-expected

The current module constrains to values in enum but khal supports RGB colors as well
khal.readthedocs.io/en/latest/configure.html#the-calendars-section ! (be careful when setting an RGB value, it has to be quoted else it is ignored, got bitten by it with a manual config )
NB: It's also not possible to set addresses khal.readthedocs.io/en/latest/configure.html#the-calendars-section
fix the rgb part of https://github.com/nix-community/home-manager/issues/5148
```
```

programs.khal: ability to set RGB color

---

flake.nix

```
```
@rycee 
I added myself as a maintainer of the `home-manager` module as my changes directly affect it, however this might not the followed convention (I'm not sure) so I am OK on removing myself from it.
Fixes:
#4824
References:
https://discourse.nixos.org/t/home-manager-not-found/31337
https://www.reddit.com/r/Nix/comments/15mhb50/recurring_home_manager_not_found_error_after/

home-manager: fix missing string context

---

modules/services/window-managers/hyprland.nix

Using the current example causes the dbus-update-activation-environment command to fail, also leading to the target not being started. 
```
```
@fufexan

hyprland: fix systemd variables example

---

modules/services/window-managers/xmonad.nix

xmonad: fix cp failure if libFiles with subdirectories

---

modules/programs/zoxide.nix

since zoxide [9.3](git@github.com:gabevenberg/home-manager.git), no string replacements are needed for nushell integration. This should maintain backwards compatibility as even nix stable is on 9.3 (latest is 9.4)
- [ x ] Change is backwards compatible.
- [ x ] Code formatted with `./format`.
- [ x ] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.
- [ x ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).
```
```

deleted str replacents that are not needed in new zoxide versions.

---

modules/programs/khal-accounts.nix
modules/programs/khal.nix
tests/modules/programs/khal/config.nix
tests/modules/programs/khal/khal-config-expected

- Remove mistaken new line in khal config, refer to [1].
- Make necessary changes on the expected config files
[1]: https://github.com/nix-community/home-manager/pull/5192#pullrequestreview-1975091763
Refer to the commit msg.
```
```
@teto

programs.khal: remove extra new line on config

---

modules/programs/yazi.nix
tests/modules/programs/yazi/bash-integration-enabled.nix
tests/modules/programs/yazi/fish-integration-enabled.nix
tests/modules/programs/yazi/nushell-integration-enabled.nix
tests/modules/programs/yazi/zsh-integration-enabled.nix

Backport https://github.com/nix-community/home-manager/pull/4699 https://github.com/nix-community/home-manager/pull/4746 https://github.com/nix-community/home-manager/pull/4846 to 23.11
```
```

[Backport 23.11] yazi: shell integration

---

modules/files.nix
modules/files/check-link-targets.sh

Extract a single inline-string shell script into a file, so that it is amenable to shellcheck and autoformatting. (To make this diff easier to review, I have not fixed the two existing shellcheck errors, nor have I formatted the file.)
Note that module/files.nix is currently excluded from autoformatting, but I have tried to structure this such that it doesn't look too awful when `nixfmt` is applied to it.
For reference, here's the diff displayed in Beyond Compare:
This should be a no-op, so of course feel free to reject. If this is accepted, I may start doing this to more of the chonky inline shell scripts.
There's a solid argument for passing these things in as env vars instead, rather than doing string replacements; shout if you want that and I can try and work out how.
```
{component}: …
```

home-manager: Extract inline shell script to a file

---

modules/lib/maintainers.nix
modules/misc/news.nix
modules/modules.nix
modules/programs/bun.nix

Bun is a fast JavaScript all-in-one runtime toolkit.
This module includes support for [bunfig.toml](https://bun.sh/docs/runtime/bunfig) and [adds support for bun.lockb files in `git diff`](https://bun.sh/docs/install/lockfile#how-do-i-git-diff-bun-s-lockfile) with `enableGitIntegration`.
```
```

bun: add module

---

modules/programs/firefox.nix

Firefox, upon exit, creates the default containers.json file in place of the one that home-manager created. This leads to errors when switching to a new profile, as home-manager is careful with overwriting existing files. The added option toggles that behaviour.
Closes: https://github.com/nix-community/home-manager/issues/4989
---
I guess it would be best if this was inlined into the existing `containers` field, in a backwards compatible way; e.g.,
``` nix
containers = {
force = true;
"name" = {
id    = 1;
color = "purple";
};
```
but I haven't managed to make that work.
```
``` …

firefox: Add `containersForce`

---

modules/programs/fish.nix

The flag style has been deprecated and will eventually be removed.
```
```

fish: use the subcommand style for the status command

---

modules/programs/foot.nix
tests/modules/programs/foot/systemd-user-service-expected.service

Adds foot bin path to systemd service environment. If left out, foot's terminal spawning shortcut will not work as the `footclient` binary is not on the server's PATH.
```
```
@plabadens

foot: set PATH in server's systemd unit file

---

modules/programs/rio.nix

This is an error as of https://github.com/NixOS/nixpkgs/pull/303841
It seems to have been missed in https://github.com/nix-community/home-manager/pull/4215
```
```
@otavio @emilazy

rio: remove redundant `lib.mdDoc` call

---

modules/programs/nushell.nix
tests/modules/programs/carapace/nushell.nix
tests/modules/programs/direnv/nushell.nix
tests/modules/programs/nushell/example-settings.nix
tests/modules/programs/oh-my-posh/nushell.nix
tests/modules/programs/yazi/nushell-integration-enabled.nix

Fixes #5248 
I'm not sure about the exact situation on darwin, whether this should be set by default (i.e. remove the if check completely), since nushell only loads from that path when `XDG_CONFIG_HOME` is set. As this requires `config.xdg.enable = true`.
(when this is the right solution, I'll fix the other programs/modules that depend on nushell such as yazi etc.) 
```
```

nushell: fix nushell config path on darwin

---

modules/services/espanso.nix
tests/default.nix
tests/modules/services/espanso-darwin/basic-configuration.nix
tests/modules/services/espanso-darwin/default.nix
tests/modules/services/espanso-darwin/launchd.plist

This enables espanso as a service on darwin.
```
```
@lucasew
@bobvanderlinden
@liyangau

espanso: enable module on darwin

---

README.md
docs/manual/installation.md
docs/manual/nix-flakes.md
docs/manual/nix-flakes/standalone.md
modules/programs/firefox.nix
modules/programs/qutebrowser.nix
tests/modules/programs/firefox/profile-settings-expected-bookmarks.html
tests/modules/programs/firefox/profile-settings-expected-search.json
tests/modules/programs/firefox/profile-settings.nix

This changes the links from the unofficial wiki to the official wiki.
```
```

treewide: prefer the official wiki

---

home-manager/home-manager
home-manager/po/home-manager.pot
modules/po/hm-modules.pot

Instead of an error
line 958: $1: unbound variable
we now emit an error such as
missing argument for --cores
Note, this is not perfect. In many cases you still get sub-optimal error messages.
```
```

home-manager: error out on missing option argument

---

modules/misc/news.nix
modules/modules.nix
modules/programs/fd.nix

`fd` is a simple, fast and user-friendly alternative to `find`.
This module includes support for the [`.fdignore`/`$XDG_CONFIG_HOME/fd/ignore`](https://github.com/sharkdp/fd#excluding-specific-files-or-directories) global ignore file (`ignores`), the search hidden files and directories `--hidden` option (`hidden`), and `extraOptions` for additional CLI flags.
```
```
N/A
I've refrained from adding myself to `modules/lib/maintainers.nix` as I have an upstream PR that adds myself as a maintainer in nixpkgs: …

fd: add module

---

modules/programs/bash.nix

bash: add bash package to home.packages

---

modules/programs/helix.nix
tests/modules/programs/helix/example-settings.nix
tests/modules/programs/helix/ignore-expected

Add global ingore file option. More information available here:
https://docs.helix-editor.com/configuration.html#editorfile-picker-section
```
```
@Philipp-M

helix: add ignores option

---

modules/lib/maintainers.nix
modules/misc/news.nix
modules/modules.nix
modules/programs/spotify-player.nix
tests/default.nix
tests/modules/programs/spotify-player/app.toml
tests/modules/programs/spotify-player/default.nix
tests/modules/programs/spotify-player/keymap.toml
tests/modules/programs/spotify-player/settings.nix
tests/modules/programs/spotify-player/theme.toml

Adds a module for `spotify-player` with the fields `enable`, `package`, `settings`, `themes`, `keymaps`.
```
```

spotify-player: add module

---

modules/services/kdeconnect.nix

Since kdeconnect-indicator is a tray application, it should require "tray.target", as is the case for flameshot[0].
[0]: https://github.com/nix-community/home-manager/blob/b1a5b3d6a524c80c7dd20888bff227d52adf5f03/modules/services/flameshot.nix#L58
```
```

kdeconnect: require "tray.target" for kdeconnect-indicator

---

modules/programs/alacritty.nix
tests/modules/programs/alacritty/settings-toml-expected.toml
tests/modules/programs/alacritty/toml_config.nix

See https://github.com/nix-community/home-manager/pull/4817#discussion_r1441710049
```
```
@ncfavier

alacritty: fix escape sequence in example and test

---

modules/programs/alacritty.nix
tests/modules/programs/alacritty/empty-settings.nix
tests/modules/programs/alacritty/example-settings-expected.toml
tests/modules/programs/alacritty/example-settings.nix
tests/modules/programs/alacritty/settings-merging-expected.yml
tests/modules/programs/alacritty/settings-merging.nix
tests/modules/programs/alacritty/toml_config.nix

This is based on top of #4853. It removes the compat code for 0.12, which is no longer in nixpkgs.
```
```
@ncfavier

alacritty: post 0.13 cleanup

---

modules/services/window-managers/i3-sway/sway.nix
tests/modules/services/window-managers/sway/default.nix
tests/modules/services/window-managers/sway/sway-systemd-variables.conf
tests/modules/services/window-managers/sway/sway-systemd-variables.nix

Adds environment variable propagation and command customization to environment initialization, similar to how it's done in #4490.
```
```
@Scrumplex @alexarice @sumnerevans @SebTM @oxalica

sway: systemd customization

---

modules/misc/news.nix
modules/modules.nix
modules/services/remmina.nix
tests/default.nix
tests/modules/services/remmina/basic-config.nix
tests/modules/services/remmina/default-config.nix
tests/modules/services/remmina/default.nix

Create a module to enable managing Remmina, an RDP client, with a home-manager module, providing a systemd service and mimetype integration that can be disabled if so desired.
```
```

remmina: Init module

---

modules/misc/qt/kconfig.nix
modules/modules.nix

Fixes https://github.com/nix-community/home-manager/issues/607 by providing a way to programattically set kde configuration files. 
However as note that any theme changed with this module requires a logout, as the proper way would be to exec `plasma-apply-*` and those commands seem to require a working DBus and thus https://github.com/nix-community/home-manager/pull/2548 for testing on my setup.
```
```

kconifg:init

---

modules/services/window-managers/hyprland.nix

Hyprland no longer requires patching to work on Nvidia
So remove the nvidiaPatches option.
Per https://github.com/NixOS/nixpkgs/commit/79ddf33f84364fa3b857ac3d06ecce91d8429ba5
@fufexan

hyprland: remove enableNvidiaPatches option

---

modules/services/kdeconnect.nix

The PR #5299[0] actually adds the requirement on "tray.target" for the kdeconnect service, when kdeconnect-indicator is set to true. What it should do is add the requirement directly to the latter. This commit fixes it.
[0]: https://github.com/nix-community/home-manager/pull/5299#issue-2252834123
```
```

kdeconnect: require "tray.target" on the correct service

---

modules/misc/qt.nix

The PR #5156 broke the automatic installation of packages needed for the `qt.platformTheme.name` option in some cases: If `qt.platformTheme.package` is left to the default (null), then `home.packages` (in line 261) will be set to an empty list instead of the list defined in `platformPackages`. The reason for this is that `lib.optionals` doesn't return `null` if the condition is false but an empty list which will still be selected by the `lib.findFirst` function. This changes this so that `lib.findFirst` ignores empty lists. It doesn't need to check for `null` since `lib.optionals` already does that.
```
``` …

qt: fix platform theme package install

---

modules/programs/joplin-desktop.nix

This PR is a fix for two issues that cause rebuild to fail. 
The first was caused when `sync.target` and `sync.interval` were not set, this was fixed by changing the default values from `null` to `"undefined"` and filtering these out later.
The second error occurred when the `.config/joplin-desktop` directory didn't exist (e.g. when installing Joplin for the first time) which caused the `touch` command to fail. This was fixed using `mkdir` to ensure that `.config/joplin-desktop` exists.
Closes #5222 
```
```
@rycee @sumnerevans @berbiche

joplin-desktop: fix rebuild failure for undefined options

---

modules/misc/news.nix
modules/modules.nix
modules/programs/poetry.nix
tests/default.nix
tests/modules/programs/poetry/custom-settings.nix
tests/modules/programs/poetry/default-settings.nix
tests/modules/programs/poetry/default.nix

Create new module for poetry. I added the corresponding tests based on those used by `tealdeer`, but strangely the test `poetry-custom-config` is failing even though it works if I include the new module in my own nixos configuration. That is also why this PR is marked as draft at the moment. I would be more than happy for suggestions as to why the test is failing.
Edit: I identified the issue: I forgot to include the new module in the file `modules/modules.nix`, so it was not picked up during the tests. I marked the PR as ready to review.
```
``` …

poetry: init module

---

modules/programs/bat.nix

Allow users to override the `bat` package used.
```
```

bat: allow overriding package

---

modules/programs/foot.nix
tests/modules/programs/foot/systemd-user-service-expected.service

This reverts commit 40ab43ae98cb3e6f07eaeaa3f3ed56d589da21b0 #5254 
Fixes #5302 
This change caused footclient to launch with the set path on some systems, making the shell unusable. There may be a way to keep it working while fixing the initial problem #5254 was solving, but I think this should be done in the meantime. 
```
```
@plabadens

foot: unset PATH in server's systemd unit file

---

modules/misc/news.nix
modules/modules.nix
modules/services/amberol.nix

Amberol is a small and simple music player.
Added a module for it that can allow us to customize (the only) 2 settings. It also enables the gapplication-service for background playback.
Please check if everything's fine as haven't worked on home-manager before, mostly copypasted from existing easyeffects module.
```
```

amberol: add module 

---

modules/programs/tealdeer.nix

_Almost_ harmless typo (I learned about it by blindly copying it into my config and getting a build error 🙈)
```
```
@pedorich-n

tealdeer: documentation typo

---

home-manager/home-manager
tests/integration/standalone/alice-home-init.nix

The comment description on hm-session-vars.sh is confusing to the point of being misleading. Others have indicated a similar sentiment ([https://discourse.nixos.org/t/home-manager-doesnt-seem-to-recognize-sessionvariables/8488/11?u=dotconfig404](discourse comment) or the fact that theres a FAQ section on it)). This small addition hopefully helps clear it up a little. 
```
```

comments: clearer description of home session variables

---

modules/services/swayosd.nix
tests/modules/services/swayosd/swayosd.nix

Add custom style path file option
> The new option is part of this new version https://github.com/NixOS/nixpkgs/pull/305672 
```
```
@pltanton

swayosd: add custom style option

---

modules/programs/zsh.nix

To configure zsh's autosuggest "highlight style" we use `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE` but it's currently set to `AUTOSUGGESTION_HIGHLIGHT_COLOR` (via `autosuggestion.highlight`). This change was apparently made [back in 2016](https://github.com/zsh-users/zsh-autosuggestions/pull/91) or earlier.
Fixes #5290 
```
```
@teto

zsh: use correct autosuggestion style variable

---

home-manager/home-manager

Fixes https://github.com/nix-community/home-manager/issues/5033
This should be backported to the stable release after merge.
This is still fragile and will probably fail for other reasons like a space in the username, but it's less broken.

home-manager: remove duplicate slashes in news-read-ids file path

---

modules/misc/xdg-portal.nix

Addresses https://github.com/nix-community/home-manager/pull/5158#issuecomment-2012171515
When using the NixOS module with `useUserPackages = true`, `share/xdg-desktop-portal` from `home-manager-path` won't get linked into the profile, similarly to bash completions and friends.
This PR adds a note on the fix, that is simply adding it to `pathsToLink` on the system configuration.
```
```

xdg-portal: add note about useUserPackages and pathsToLink

---

modules/services/cliphist.nix

Adds an option to also store images in cliphist's store. This requires creating another systemd service which watches wl-paste with dedicated change type.
I didn't find in any explicit requirement about this in cliphist, however it did solve the issue for me. Also this is the way presented in hyprland docs and accepted solution in this issue https://github.com/sentriz/cliphist/issues/28
```
```
@Janik-Haag

cliphist: option to include images in clipboard history

---

modules/programs/direnv.nix
tests/modules/programs/direnv/nix-direnv.nix
tests/modules/programs/direnv/stdlib-and-nix-direnv.nix
tests/modules/programs/direnv/stdlib.nix

This PR allows using the module system to create the `direnvrc` file.
I wanted to globally run `nix_direnv_manual_reload` in `direnvrc`, but wasn't able to because sourcing `nix-direnv` was hardcoded at the end of the file. The only possible solution was to disable `nix-direnv` and manually add it to the config (doable, but not ideal).
Based on review comments, sourcing the `nix-direnv` file was removed altogether in favour of adding it to direnv's lib. In practice, this makes it load _before_ the `direnvrc`, instead of at the end of it. I'm open to change it back with the premise of avoiding creating unneeded files in the user's home (which I'm all for 🙂). 
~~Now, the contents are `mkMerge`d, allowing `mkAfter`, `mkBefore`, and family to be used to enforce the order of the lines.~~
~~I …

direnv: Make stdlib mergeable/sortable

---

modules/programs/thefuck.nix
tests/modules/programs/thefuck/integration-disabled.nix
tests/modules/programs/thefuck/integration-enabled.nix

Add `nushell` integration to `thefuck`.
```
```
@ilaumjd

thefuck: add nushell integration

---

modules/programs/mpv.nix
tests/modules/programs/mpv/mpv-example-settings-expected-bindings
tests/modules/programs/mpv/mpv-example-settings.nix

Adds an option `programs.mpv.extraInput` for appending additional lines to `$XDG_CONFIG_DIR/mpv/input.conf`.
One use case for this is adding menu entries in uosc (an alternative osc). Especially when not assigned to a key. See https://github.com/tomasklaen/uosc?tab=readme-ov-file#menu-1.
Closes #5212.
```
```
@tadeokondrak @thiagokokada @chuangzhu

mpv: add extraInput option

---

modules/programs/neomutt.nix
tests/modules/programs/neomutt/neomutt-expected.conf
tests/modules/programs/neomutt/neomutt-not-primary-expected.conf
tests/modules/programs/neomutt/neomutt-with-binds-expected.conf
tests/modules/programs/neomutt/neomutt-with-imap-expected.conf
tests/modules/programs/neomutt/neomutt-with-imap-type-mailboxes-expected.conf
tests/modules/programs/neomutt/neomutt-with-named-mailboxes-expected.conf

In the generated neomutt configuration, source the optional `vim-keys.rc` before applying the `binds` configuration, to allow the user to override keybindings from `vim-keys.rc`.
```
```

neomutt: allow binds to override vimKeys

---

modules/lib/generators.nix
modules/services/window-managers/hyprland.nix
tests/modules/services/window-managers/hyprland/default.nix
tests/modules/services/window-managers/hyprland/multiple-devices-config.conf
tests/modules/services/window-managers/hyprland/multiple-devices-config.nix
tests/modules/services/window-managers/hyprland/sourceFirst-false-config.conf
tests/modules/services/window-managers/hyprland/sourceFirst-false-config.nix

Creating a library module to be used amongst the various hypr ecosystem modules. In response to https://github.com/nix-community/home-manager/pull/5324#issuecomment-2080203195. I had to refactor the function when moving to a separate module so I created a test to verify that it didn't break anything. 
```
```
@fufexan

lib/generators.nix: init toHyprconf generator

---

modules/files/check-link-targets.sh

The checkLinkTarget activation script currently prints an error message that is misleading when home-manager is used as an NixOS module. I.e., it suggests moving files or using `home-manager switch -b backup`.
Closes #5350
```
```
@rycee

files: adjust error message in checkLinkTargets activation script

---

modules/misc/news.nix
modules/modules.nix
modules/programs/freetube.nix
tests/default.nix
tests/modules/programs/freetube/basic-configuration.db
tests/modules/programs/freetube/basic-configuration.nix
tests/modules/programs/freetube/default.nix

FreeTube is a YouTube client for Windows, Mac, and Linux.
This module enables declarative configuration of its options.
```
```

freetube: add module

---

modules/services/swaync.nix

When the swaync.style option is set to a path: `style = ./swaync-style.css`, then the CSS file will just be a string to the store path. This fixes that problem.
```
```
@abayomi185

swaync: fix style path

---

modules/services/cliphist.nix
tests/modules/services/cliphist/cliphist-extra-options.nix
tests/modules/services/cliphist/default.nix

Add an extraOptions option that would be appended to the cliphist command.
```
```
@Janik-Haag

cliphist: add extraOptions option

---

modules/misc/news.nix
modules/modules.nix
modules/services/hypridle.nix
tests/default.nix
tests/modules/services/hypridle/basic-configuration.nix
tests/modules/services/hypridle/default.nix
tests/modules/services/hypridle/hypridle.conf

Adding hypridle module so i can remove another input from my flake and just use the config in home-manager. Meant to do a long time ago but forgot to create PR.
```
```
@fufexan

Hypridle: add module

---

modules/services/wlsunset.nix
tests/modules/services/wlsunset/wlsunset-service-expected.service

Adds the `output`, `sunrise` and `sunset` config options to wlsunset.nix
```
```
@matrss

wlsunset: update options

---

modules/programs/git.nix
tests/modules/programs/git/git-with-email-expected.conf
tests/modules/programs/git/git-with-email.nix
tests/modules/programs/git/git-with-msmtp-expected.conf
tests/modules/programs/git/git-with-msmtp.nix

We currently have no way of specifying the sender's name inside the `From` field, making a patch sent through `git send-email` appear as coming from "xxx@domain.com".
In this commit we make this field follow the standard `realName <email>` format whenever applicable.
```
```
@rycee

git: sendemail: add realName to From field

---

modules/misc/news.nix
modules/modules.nix
modules/programs/gnome-shell.nix
tests/default.nix
tests/modules/programs/gnome-shell/default.nix
tests/modules/programs/gnome-shell/gnome-shell.nix

Adds programs.gnome-shell for customizing Gnome Shell extensions and theme.
This is take two on #1795 by @tadfisher. Generally just rebased and updated with all new conventions.
- Changed maintainer to myself as I am not sure if @tadfisher is interested in this anymore
- Switched from uuid to extensionUuid without fallback (as it was quite a while that landed in nixpkgs and no-one is using this new module yet)
- Updated changelog
- This setting is now some kind of gVariant and needs to access the value as such `config.dconf.settings."org/gnome/shell".enabled-extensions.value`
```
``` …

programs/gnome-shell: init module

---

modules/programs/jujutsu.nix

based on https://github.com/martinvonz/jj/wiki/Emacs#ediff-as-a-merge-tool
```
```
@shikanime

jujutsu: add ediff option

---

modules/services/kanshi.nix
tests/modules/services/kanshi/default.nix
tests/modules/services/kanshi/new-configuration.conf
tests/modules/services/kanshi/new-configuration.nix

Update Kanshi's nix configuration to better reflect kanshi's configuration format.
Mark the previous format as deprecated.
Closes https://github.com/nix-community/home-manager/issues/5374
- Ran kanshi tests
```
```

Kanshi: Better configuration options

---

modules/misc/news.nix
modules/modules.nix
modules/programs/hyprlock.nix
tests/default.nix
tests/modules/programs/hyprlock/basic-configuration.conf
tests/modules/programs/hyprlock/basic-configuration.nix
tests/modules/programs/hyprlock/complex-configuration.conf
tests/modules/programs/hyprlock/complex-configuration.nix
tests/modules/programs/hyprlock/default.nix

Adding the hyprlock module, similar to https://github.com/nix-community/home-manager/pull/5324
```
```
@fufexan

Hyprlock: add module

---

modules/misc/news.nix
modules/modules.nix
modules/services/hyprpaper.nix
tests/default.nix
tests/modules/services/hyprpaper/basic-configuration.nix
tests/modules/services/hyprpaper/default.nix
tests/modules/services/hyprpaper/hyprpaper.conf

Adding the hyprpaper module, similar to https://github.com/nix-community/home-manager/pull/5324
Looked like https://github.com/nix-community/home-manager/pull/5059 was abandoned so I created this along the same lines as the other hypr modules i'm setting up. 
Closes #5059
Closes #4632
```
```
@fufexan

Hyprpaper: add module

---

modules/services/window-managers/hyprland.nix

Using the option `wayland.windowManager.hyprland.systemd.xdgAutostart`, users can now choose to start applications present in `$XDG_CONFIG_HOME/autostart` when starting their sway session.
See 0144ac418ef633bfc9dbd89b8c199ad3a617c59f and https://github.com/nix-community/home-manager/pull/3747
```
```
@fufexan

hyprland: add support for XDG autostart using systemd

---

modules/misc/news.nix
modules/modules.nix
modules/programs/yambar.nix
tests/default.nix
tests/modules/programs/yambar/default.nix
tests/modules/programs/yambar/empty-settings.nix
tests/modules/programs/yambar/example-settings-expected.yml
tests/modules/programs/yambar/example-settings.nix

This adds a module for [Yamber](https://codeberg.org/dnkl/yambar), a modular status panel for X11 and Wayland.
```
```

yambar: add module

---

modules/targets/darwin/user-defaults/opts-allhosts.nix

Adding a few defaults options as I move this from nix-darwin. home-manager is the right place for this as they are per-user, not nix-darwin (which should be a NixOS analogue for darwin, iow not handle per-user settings).
```
```

darwin: more options: dock orientation etc

---

modules/services/mopidy.nix
tests/modules/services/mopidy/basic-configuration.nix
tests/modules/services/mopidy/default.nix
tests/modules/services/mopidy/mopidy-scan.nix

The systemd service `mopidy-scan` provided by this module depends on `mopidy local` which is only available via an optional extension package. When the extension isn't installed, the service fails to start.
This PR checks if `mopidy-local` is part of `cfg.extensionPackages` before enabling the service.
```
```

mopidy: make scan service depend on `mopidy-local`

---

modules/programs/jujutsu.nix
tests/modules/programs/jujutsu/empty-config.nix
tests/modules/programs/jujutsu/example-config.nix

Use the new supported XDG config place instead of home directory to make it cleaner
```
```
@shikanime

jujutsu: update module to respect XDG config placement

---

modules/home-environment.nix

Recent Nix versions fail when running `nix profile remove` with no argument. If packages are externally managed, and we have nothing to remove, do not run the `nix profile remove` command.
This was fixed on master, but I have a setup on NixOS 23.11 which uses an unstable Nix version, so this is a very "minimal" backport of the fix.
I have a test issue that seems unrelated:
```
error: hash mismatch in fixed-output derivation '/nix/store/pyna25yf5k1bl14pi0lcy2a8lvb6691f-lookup?op=get-options=mr-search=0x36cacf52d098cc0e78fb0cb13573356c25c424d4.drv':
specified: sha256-9Zjsb/TtOyiPzMO/Jg3CtJwSxuw7QmX0pcfZT2/1w5E=
got:    sha256-Pvm0CpH13pvnD/c+IJAkRElR5/IhZt8pg7RjT/dZdfM=
error: 1 dependencies of derivation '/nix/store/8lq1zp4xm5bl3lsnyvbdrpf6dx7cyg99-gpg-pubring.drv' failed to build
error: 1 …
```

[23.11] home-environment: fix installPackages with recent Nix versions

---

modules/services/espanso.nix

espanso: add n8henrie to maintainers

---

modules/services/kanshi.nix

Kanshi: Fix configuration examples by adding enclosing braces/brackets.
Somewhat closes https://github.com/nix-community/home-manager/issues/5443
```
```

kanshi: fix configuration example

---

modules/programs/fd.nix

Without this change a dummy alias `{ fd = "fd ";}` is created.
There are no tests for this module, so I tested it manually.
```
```

fd: don't create shell aliases with empty args

---

modules/programs/eza.nix

Without this change a dummy alias `{ eza = "eza ";}` is created.
There are no tests for this module, so I tested it manually.
```
```

eza: don't create shell aliases with empty args

---

modules/programs/yazi.nix
tests/modules/programs/yazi/bash-integration-enabled.nix
tests/modules/programs/yazi/fish-integration-enabled.nix
tests/modules/programs/yazi/zsh-integration-enabled.nix

cd conflicts with aliases that dont support -- syntax
Enabling the zoxide --cmd cd will break this alias. Need to use the builtin cd behavior. 
```
```

yazi: use builtin cd

---

modules/programs/bash.nix

reference: https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html#index-HISTCONTROL
- [ofc(:] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.
```
```

bash: Add missing 'ignoreboth' to historyControl allowed values

---

modules/services/window-managers/hyprland.nix

Fixes Hyprland's onChange check for versions >= 0.40.0, as the socket has now moved to $XDG_RUNTIME_DIR.
```
```
@fufexan

hyprland: onChange: check XDG_RUNTIME_DIR as well

---

modules/programs/topgrade.nix
tests/modules/programs/topgrade/settings-expected.toml
tests/modules/programs/topgrade/settings.nix

Topgrade config format changed to use misc and thus the example becomes invalid, topgrade tries to migrate it but since /nix is readonly it fails. So the correct example is this.
```
```

topgrade: update example config

---

modules/services/listenbrainz-mpd.nix

The [option name](https://codeberg.org/elomatreb/listenbrainz-mpd/src/commit/e340e990c7bdb61f3646991c02adb091ce1bc727/config.toml.sample#L14) is actually `token_file`, not `tokenFile`, so it's useful to change the example here in case someone gets tripped up by this. 
```
```
@Scrumplex

listenbrainz-mpd: change config example to accurate one

---

modules/services/gpg-agent.nix

`splitString "" "some string"` would throw exception `error: invalid regular expression` on Darwin (or accurately, on Nix built against libc++). Refer to https://github.com/NixOS/nix/issues/7208 for details.
Before Nix handles that issue correctly, we should refrain from using `splitString ""`, and luckliy `lib.stringAsChars` can do the same thing. 
```
```
@rycee

gpg-agent: fix usage of splitString

---

home-manager/home-manager

Since nixpkgs commit 993baa587c4b82e791686f6ce711bcd4ee8ef933, `networking.hostName` is not allowed to be a FQDN.
Add `hostname --fqdn` to the default flake attribute names that are searched.
If
netorking.hostname = "hostname";
networking.domain = "example.com";
is set in the system NixOS configuration, this allows defining
homeConfigurations."username@hostname.example.com" = ...
and still use
home-manager switch --flake .
instead of having to type out
home-manager switch --flake .#$(whoami)@$(hostname --fqdn)
- Technically no if someone happens to have both `homeConfigurations."username@hostname"` and `homeConfigurations."username@hostname.example.com"`.
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) …

home-manager: check FQDN for '--flake .' attribute

---

home-manager/home-manager

MacOS doesn't support the long-style `--fqdn` option to `hostname` that
was added by 1b589257f72c9c54e92d1d631e988e5346156736.
Switch to short style `-f` that should be supported on every platform.
```
```

home-manager: use short -f instead of --fqdn

---

modules/services/swayidle.nix

to avoid this kind of message:
swayidle[181123]: - [Line 1054] Unable to connect to the compositor. If your compositor is running, check or set the WAYLAND_DISPLAY environment variable.
```
```

services.swayidle: wait for WAYLAND_DISPLAY

---

modules/services/nix-gc.nix
tests/modules/services/nix-gc/expected.timer

Closes: https://github.com/nix-community/home-manager/issues/5465
```
```

nix-gc: add `persistent` option

---

.github/workflows/github_pages.yml
.github/workflows/labeler.yml
.github/workflows/test.yml
.github/workflows/update-flake.yml

* cachix/install-nix-action: v23 -> v27
Release: https://github.com/cachix/install-nix-action/releases/tag/v27
* actions/labeler: v4 -> v5
Release: https://github.com/actions/labeler/releases/tag/v5.0.0
* DeterminateSystems/update-flake-lock: v21 -> v22
Release: https://github.com/DeterminateSystems/update-flake-lock/releases/tag/v22
Closes https://github.com/nix-community/home-manager/pull/5418
Closes https://github.com/nix-community/home-manager/pull/4765
```
``` …

ci: bump all actions versions

---

.github/labeler.yml

actions/labeler@v5 had breaking changes that I failed to update for in https://github.com/nix-community/home-manager/pull/5496. This PR should hopefully fix it.
I was unfortunately not able to catch the issue because the labeler config seems to be based on whatever is in the `master` branch, so CI didn't catch it on the original PR.
I'm going to need @rycee to help bail me out here.
```
```

ci/labeler: upgrade to v5 format

---

.github/labeler.yml

YAML is so annoying :)
```
```

ci/labeler: fix upgrade to v5 format

---

modules/accounts/email.nix

Add clarifying documentation for maildirBasePath value.
Fixes #2946 in the documentation.
```
```

accounts.email: Add clarifying documentation

---

tests/modules/i18n/input-method/fcitx5-stubs.nix

Since https://github.com/NixOS/nixpkgs/pull/308725, fcitx5-with-addons expects share/dbus-1/services/ to be present.
This patch updates the fcitx5 stub to reflect that.
```
```

fcitx5: fix tests

---

docs/home-manager-manual.nix
docs/options.html

After migrating to nixos-render-docs, the extension move to .xtml. Unfortunately, this broke links to the previous Options Page.
This patch provides a basic redirect support to the new Options Page.
Fixes https://github.com/nix-community/home-manager/issues/5002
```
```

docs: add redirect from the previous options.html

---

modules/services/window-managers/hyprland.nix

Installs the `xwayland` package if `cfg.xwayland.enable = true;`. This allows XWayland to work even without enabling the NixOS Hyprland option.
Fixes #5503.
```
```

hyprland: install xwayland if enabled

---

modules/programs/waybar.nix
tests/modules/programs/waybar/deprecated-modules-option.nix
tests/modules/programs/waybar/settings-complex-expected.json

I prefer to handle modules-* imperatively for more flexibility, I do this via waybar "includes" (https://github.com/Alexays/Waybar/wiki/Configuration). Current HM defaults modules-* to `[]` instead of null for most other settings, so they get written to ~/.config/waybar/config even though I've configured nothing.
And they take precedence over the impartives ones because of how waybar's includes work:
====
Paths to additional configuration files.
Each file can contain a single object with any of the bar configuration options. In case of duplicate options, the first defined value takes precedence, i.e. including file -> first included file -> etc. Nested includes are permitted, but make sure to avoid circular imports. For a multi-bar config, the include directive affects only current bar …

programs.waybar: remove modules-* from defaults

---

modules/programs/mpv.nix

`wrapMpv` was removed from nixpkgs since this PR: https://github.com/NixOS/nixpkgs/pull/304349
```
```

mpv: fix package if wrapMpv not found

---

modules/misc/news.nix
modules/misc/nix.nix
tests/modules/misc/nix/default.nix
tests/modules/misc/nix/empty-settings.nix
tests/modules/misc/nix/example-channels-xdg.nix
tests/modules/misc/nix/example-channels.nix
tests/modules/misc/nix/example-settings.nix
tests/modules/misc/nix/keep-old-nix-path.nix

This adds a new option, `nix.channels`. It's the Nix channels equivalent of the `nix.registry` option, and compatible with pre-Flake Nix tooling including nix-env and nix-shell. Like `nix.registry`, this option is useful for pinning Nix channels.
Channels defined in the new option can coexist with channels introduced through the `nix-channel` command. If the same channel exists in both, the one from Home Manager will be prioritized.
This PR builds on #2677 with minor changes and additional tests.
Closes #2677.
```
```
See [CONTRIBUTING](https://github.com/nix-community/home-manager/blob/master/docs/contributing.adoc#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) …

nix: add a declarative alternative to Nix channels

---

tests/modules/programs/firefox/profile-settings-expected-containers.json

Fixes the outdated test result from https://github.com/nix-community/home-manager/pull/4851#issuecomment-2002072810.
Nothing to format.
Only tested the updated test.
Updated `firefox-profile-settings`.
```
```

firefox: update expected container settings

---

modules/misc/gtk.nix

Fixes #5562
I originally thought about changing the default of `hm.types.fontType` to 10, but just decided to do a null check in the gtk module since the new default wouldn't apply outside of gtk.
```
```
@rycee

gtk: explicitly set default font size

---

modules/services/stalonetray.nix

Move `$HOME/.stalonetrayrc` file to be symlinked to `$XDG_CONFIG_HOME/stalonetrayrc`.
See the [README](https://github.com/kolbusa/stalonetray?tab=readme-ov-file#description), and https://github.com/kolbusa/stalonetray/issues/1 for support details.
For the most part, unless someone has external scripts that depends on the location of this file? I find it unlikely.
```
```

stalonetray: move config file to `XDG_CONFIG_HOME`

---

modules/systemd-activate.sh

If the user has template services in their systemd configuration, these can't be restarted, and will produces warnings during the activation phase.  Avoid those warnings by skipping any uninstantiated templates when looking for services to start or stop.
If a user has template files in their systemd configuration `unit@.service` rather than `unit.service` or `unit@instance.service`, these will produce error messages during the Home Manager activation phase, as they can't be activated or queried; systemctl will only let you activate/query instances of those templates. Avoid this by ignoring such files when looking for units that might want to be stopped or started.
This is fundamentally only a cosmetic change; the warnings are benign, they're just also unnecessary and unhelpful. I'm seeing …

systemd: don't try to restart templates

---

modules/programs/rbw.nix

rbw expects a protocol for its base_url setting. Otherwise fails with `rbw unlock: failed to parse base url: relative URL without a base`.
See [README.md#configuration](https://github.com/doy/rbw/blob/741a72cf0d7d45fcd32b0326b69f6238733e5a56/README.md#configuration).
```
```
@ambroisie

rbw: fix url option examples

---

modules/misc/news.nix
modules/modules.nix
modules/services/glance.nix
tests/default.nix
tests/modules/services/glance/default-settings.nix
tests/modules/services/glance/default.nix
tests/modules/services/glance/example-settings.nix
tests/modules/services/glance/glance-default-config.yml
tests/modules/services/glance/glance-example-config.yml
tests/modules/services/glance/glance.service

Adds module `services.glance` which is a self-hosted feed dashboard. Their repo: https://github.com/glanceapp/glance/.
```
```

glance: add module

---

modules/programs/sm64ex.nix
modules/services/pbgopy.nix

ivar was removed as a maintainer from upstream nixpkgs due to inactivity: https://github.com/NixOS/nixpkgs/pull/322266
```
```

maintainers: remove ivar

---

modules/programs/yazi.nix
tests/modules/programs/yazi/default.nix
tests/modules/programs/yazi/init-lua-string.nix

Currently `programs.yazi.initLua` only accepts a path/module which seems unnecessarily constraining and I doubt most users will be creating a separate file for what is likely very little lines of Lua code. This change makes the `initLua` option work for literal strings as well.
```
```
@eljamm @XYenon

yazi: allow literal string for `initLua`

---

modules/services/mpd.nix
tests/modules/services/mpd/default.nix
tests/modules/services/mpd/start-when-needed.nix
tests/modules/services/mpd/start-when-needed.service
tests/modules/services/mpd/start-when-needed.socket

This allows `systemctl --user restart mpd.socket` to work properly.
```
```

mpd: specify dependency of service on socket

---

modules/services/window-managers/hyprland.nix

This updates the description of the Hyprland module to clarify what it does and does not do, hopefully clearing some of the confusion between the HM module and the NixOS module.
```
```
@fufexan

Update Hyprland Description

---

modules/programs/mpv.nix

I'm no longer using home-manager.
```
```

mpv: remove tadeokondrak as maintainer

---

modules/services/dunst.nix

"lib.cartesianProductOfSets is a deprecated alias of lib.cartesianProduct."
Rename happened in nixpkgs commit `228621e42dc43f936b66e0ed042c90c511aa0535`.
```
```

dunst: fix warning for lib.cartesianProductOfSets

---

modules/programs/starship.nix

This PR will close https://github.com/nix-community/home-manager/issues/4786.
<details>
<summary>Original comment</summary>
<blockquote>
Type checking for `programs.starship.settings` is nearly a redundant, since:
- It can hardly prevent invalid options in advance, as we cannot copy the whole schema from starship.
- The settings will be passed to `tomlFormat.generate`, which does check the type.
- It can be incomplete and refuse some valid options, e.g., `listOf (listOf str)`.
Just keep the type check as simple as possible, and `starship` will emit warings/errors when it sees invalid options.
</blockquote>
</details>
Changes the original `type` to `tomlFormat.type`, so `programs.starship.settings` can accept all valid TOML-style values.
``` …
```

starship: fix type of settings to allow all valid value

---

modules/systemd.nix
tests/integration/nixos/basics.nix
tests/integration/standalone/flake-basics.nix
tests/integration/standalone/standard-basics.nix

Avoid potential problems when we have an old generation but it does not contain any systemd units.
Also update integration tests to match recent changes in sd-switch behavior.
```
```

systemd: only set old units directory when available

---

modules/programs/atuin.nix

atuin: use 'lib.getExe'

---

modules/misc/xdg-desktop-entries.nix

`terminal` should not be set for desktop entries of `type = Directory`, as per the [Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#value-types)
> Some keys only make sense in the context when another particular key is also present and set to a specific value. Those keys should not be used if the particular key is not present or not set to the specific value. For example, the Terminal key can only be used when the value of the Type key is Application.
Testing of this behavior is already enforced by `desktop-file-validate` during the `checkPhase` of `make-desktopitem` in nixpkgs; it errors if you currently try to create a desktop entry of type Directory.
```
```
See …

xdg-desktop-entries: allow `terminal` to be null

---

modules/services/gnome-keyring.nix

`pkgs.gnome.gnome-keyring` has been moved to `pkgs.gnome-keyring` in nixpgkgs-unstable.
Change happened in https://github.com/NixOS/nixpkgs/commit/1369411184ce66bf812935ede91f52789252e1e5
:warning: I think ? I've seen a review commit from @rycee on [another PR](https://github.com/nix-community/home-manager/pull/5605) stating that home-manager is only targetting nixpkgs-unstable branch so I think we're good
```
```
@rycee

gnome-keyring: update package

---

modules/systemd.nix

In the course of applying a workaround for #5552, I discovered that the `sd-switch` reload script assumes that systemd units are always located in `home-files/.config`. However, this is not necessarily the location of systemd user units, as a user wanting a tidier home folder may have `xdg.configHome` set.
Therefore, this PR seeks to update the `sd-switch` reload script to respect `xdg.configHome`. It does not seek to address a similar problem in the `legacy` or `suggest` reload scripts.
Note 1: In an ideal world, `xdg.configHome` would be relative to the user's home folder, so we could simply template it into the path used by the reload script. However: `xdg.configHome` is conventionally a string containing an absolute path. Therefore, we have to discover the expected subfolder for the …

sd-switch: respect xdg directory specifications

---

modules/programs/papis.nix

- Add `programs.papis.package` option to override default pkg used. This can be useful to track latest rev from repository via a flake.
```
```
@marsam

papis: add `program.papis.package` option

---

modules/services/kbfs.nix

The kbfs service does not seem to actually work with a PrivateTmp. A
PrivateTmp seems as appropriate for kbfs as anything else, but the
upstream service does not use it either
<https://github.com/keybase/client/blob/master/packaging/linux/systemd/kbfs.service>
This PR sets `PrivateTmp` to false in the kbfs service definition, which at
least allows kbfs to run.
Closes #4722
```
```
@tadfisher

kbfs: avoid using PrivateTmp for systemd service

---

modules/services/swayosd.nix
tests/modules/services/swayosd/swayosd.nix

Should fix an issue where swayosd.service would stop without starting again after restarting too quickly.
Triggered by ending a Hyprland session and logging in with tuigreet.
Related: https://github.com/nix-community/home-manager/pull/4316
```
```
@pltanton

swayosd: avoid restarting too quickly

---

modules/programs/zsh.nix

zsh: add programs.zsh.autosuggestions.strategy option like in nixpkgs.
The option defaults to history.
```
```

zsh: add programs.zsh.autosuggestions.strategy option

---

modules/programs/gnome-terminal.nix
tests/modules/programs/gnome-terminal/bad-profile-name.nix
tests/modules/programs/gnome-terminal/gnome-terminal-1.nix

The ``pkgs.gnome.gnome-terminal`` package was moved to ``pkgs.gnome-terminal``. The former is now a deprecated alias that throws a warning whenever a configuration enabling the module is used:
```
The ‘gnome.gnome-terminal’ was moved to top-level. Please use
‘pkgs.gnome-terminal’ directly.
```
Related: https://github.com/NixOS/nixpkgs/pull/319659
Related: https://github.com/nix-community/home-manager/pull/5611
```
```
@kamadorueda, @rycee

gnome-terminal: update package name

---

modules/config/home-cursor.nix
modules/lib/maintainers.nix
modules/misc/nix.nix
modules/programs/bottom.nix
modules/programs/watson.nix
modules/services/fnott.nix
modules/services/window-managers/i3-sway/swaynag.nix

As per https://github.com/NixOS/nixpkgs/pull/328969, I don't have time to actively participate in the Nix ecosystem now and likely won't be able to in the foreseeable future. I am grateful for the things I learned over the years trying to help and improve Nixpkgs and home-manager, as insignificant as those efforts may be in the grand scheme of things. Thanks for opening my eyes to what is possible with declarative configuration management.
```
```

maintainers: remove polykernel

---

modules/programs/jujutsu.nix
tests/modules/programs/jujutsu/empty-config.nix
tests/modules/programs/jujutsu/example-config.nix

Follow up to #5207, fixing jujutsu module on darwin targets.
Closes #5544 (duplicate)
If the module is evaluated on a Darwin platform, place config in `Library/Application Support` instead of unsupported XDG directory.
If someone could test it on Darwin, it would be great (e.g. @bnjmnt4n) :
```sh
nix develop --ignore-environment .#jujutsu-example-config
nix develop --ignore-environment .#jujutsu-empty-config
```
```
```
@shikanime

jujutsu: support darwin guidelines for config placement

---

modules/programs/eww.nix

Use eww's shell-completions command to generate completions for bash, zsh and fish.
```
```
@mainrs

eww: add terminal integration options

---

home-manager/home-manager

`hostname -f` could fail depending on the resolver. Discard any stderr
and test for the exit status before using the value for flake attribute
lookup.
I was unable to repro the exact bad exit status in #5665.
With
- nscd disabled,
- nsswitch.conf pointing to 'files',
- hostname entry removed from /etc/hosts
`hostname -f` from inetutils-2.5 fell back to showing just the nodename
from `uname(2)`. Injecting an empty string into the
`(struct utsname).nodename` field of `uname(2)` using strace still
exited with empty output and 0 exit-status.
Fixes #5665
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/mas …

home-manager: ignore hostname -f lookup errors

---

modules/services/nix-gc.nix
tests/modules/services/nix-gc/basic.nix
tests/modules/services/nix-gc/expected.service

This will match the behavior in the upstream service which allows the user to set options to something that uses shell syntax.
```
```
@shivaraj-bh

nix-gc: call nix-gc in a shell script to match upstream behavior
