modules/programs/firefox/mkFirefoxModule.nix

Example css wasn't valid for Firefox 69+.
Fixes #5667 
```
```

firefox: fix userChrome example

---

modules/services/nix-gc.nix
tests/modules/services/nix-gc/basic.nix
tests/modules/services/nix-gc/nix-gc-script-expected

Fixes small issue introduced by https://github.com/nix-community/home-manager/pull/5657. 
```
```
@rycee

nix-gc: remove extraneous quotes from shell script

---

modules/services/dunst.nix

This ensures that in dunst's systemd service, the `-config` flag is only used when `configFile` is set. This is because when passing `-config` to dunst, dunst does not look for config files other than the specified path. This breaks dunst's drop-in functionality, where files can be placed in `~/.config/dunst/dunstrc.d` to override settings in `~/.config/dunst/dunstrc`.
```
```
@rycee

dunst: only use `-config` flag when `configFile` is set

---

modules/programs/fastfetch.nix

Using the present version of the example, trows an error:
```
JsonConfig Error: `display.binaryPrefix` has been renamed to `display.size.binaryPrefix`. Sorry for another break change.
```
It occurs because of change in fastfetch 2.19 of JsonConfig - moving `display.binaryPrefix` to `display.size.binaryPrefix`
To not confuse the users, this commit changes the example to fit current standard
[link to fastfetch's changelog ](https://github.com/fastfetch-cli/fastfetch/blob/b3ac696312824cce12df76e398b5362973cde481/CHANGELOG.md?plain=1#L85)
```
``` …

fastfetch: update example for JsonConfig settings

---

modules/programs/bash.nix

This PR adds the `programs.bash.package` option to allow specifying which `bash` package to install (default `pkgs.bashInteractive`). This brings `bash` to parity with `fish`, `zsh`, and `nushell`, which already have analogous options.
I found myself wanting this functionality when writing additional logic around my shell configuration (in particular, `exec`ing into the `nixpkgs` version of `bash`).
Default `package` is `pkgs.bashInteractive`, which was previously hard-coded. 
```
```
@rycee

bash: add package option

---

modules/programs/zsh.nix

This change adds the programs.zsh.history.append option in
order to manage the configuration of the APPEND_HISTORY zsh option.

zsh: add option: history.append

---

modules/systemd.nix
tests/integration/nixos/basics.nix
tests/integration/standalone/flake-basics.nix
tests/integration/standalone/standard-basics.nix

This switches `systemd.user.startServices = true` to be the same as `systemd.user.startServices = "sd-switch"`, previously it would use the "legacy" method. It also introduces a warning that triggers if the user explicitly have `systemd.user.startServices = "legacy"`.
See #5452
```
```

systemd: fully deprecate legacy switcher

---

modules/misc/submodule-support.nix

This way the end user can easily check whether the home-manager configuration is part of the module or not. Example of use:
```nix
{ lib, nixosConfig, ... }:
let
mkIfNixos = lib.mkIf nixosConfig != null;
in
{
programs.foot.enable = mkIfNixos true;
}
```
related: https://github.com/NixOS/nixpkgs/issues/311709
many thanks to @roberth for the explanation
```
```

submodule-support: add default values for top-level configs

---

modules/programs/git.nix

Just adds an option to override difftastic package.  
```
```
@rycee

git: add option to override difftastic package

---

modules/services/taskwarrior-sync.nix

Add option to change which package is used for taskwarrior-sync, to e.g. taskwarrior3.
```
```
@minijackson @pacien

taskwarrior-sync: add package option

---

modules/services/window-managers/i3-sway/sway.nix
tests/modules/services/window-managers/sway/sway-modules.conf

The sway configuration maps attrsets into configuration blocks in the sway configuration files (typically ~/.config/sway/config).
The options nested inside curly braces are usually indented with 2 spaces, like is the case for `mode` (see: `modeStr` in [modules/services/window-managers/i3-sway/lib/functions.nix](https://github.com/nix-community/home-manager/blob/master/modules/services/window-managers/i3-sway/lib/functions.nix#L49)).
Nonetheless, some other configuration blocks are not indented, so it results looking like this:
```
output "eDP-1" {
position 0 0
resolution 1536x960@120Hz
}
```
rather than:
```
output "eDP-1" {
position 0 0
resolution 1536x960@120Hz
}
```
This PR fixes the indentation for `input`, `output` and `seat`.
```
```
See …

sway: indent sway configuration options

---

modules/misc/xdg.nix
tests/modules/misc/xdg/file-gen.nix

Same motivation as `xdg.dataFile` (I don't see a use-case for an `xdg.cacheFile`, but for consistency we could add one as well...)
```
```
@rycee

xdg: add option 'xdg.stateFile'

---

modules/services/window-managers/i3-sway/lib/options.nix
tests/modules/services/window-managers/i3/i3-fonts-deprecated.nix
tests/modules/services/window-managers/i3/i3-fonts-expected.conf
tests/modules/services/window-managers/i3/i3-fonts.nix

This PR adds support for i3/sway font size with `px` suffix (e.g. `10px`), which is supported both in i3 & sway (https://i3wm.org/docs/userguide.html#fonts).
Previously, the type is restricted to float and impossible to add such config.
```
```
@sumnerevans @Scrumplex @alexarice @oxalica

i3/sway: support str type for font size

---

modules/programs/taskwarrior.nix
modules/services/taskwarrior-sync.nix
tests/modules/programs/taskwarrior/taskwarrior.nix

Support taskwarrior3 migration, following the approach in https://github.com/NixOS/nixpkgs/pull/303632 to avoid breaking changes.
Closes: https://github.com/nix-community/home-manager/issues/5310
```
```
- `taskwarrior-sync.nix`
- @minijackson
- @pacien
- `taskwarrior.nix`
- @Leixb
- @x10an14

taskwarrior: support taskwarrior3 migration

---

modules/programs/firefox/mkFirefoxModule.nix

lastUserContextId should match the highest context id from the containers set in a given profile.  mapAttrsToList uses the container name for sorting.  foldlAttrs ensures we get the largets commit id.
```
```
@brckd @rycee @kira-bruneau

firefox: correct lastUserContextId output from firefox containers

---

modules/programs/k9s.nix
tests/modules/programs/k9s/example-settings.nix

This adds a new option `programs.k9s.skinPath` to define a custom theme from a path/derivation.
```
```
@katexochen
@liyangau

k9s: allow defining custom theme file

---

modules/programs/k9s.nix

I haven't got the time to maintain this anymore, see https://github.com/nix-community/home-manager/pull/4662#issuecomment-2336640088
```
```

k9s: remove katexochen as maintainer

---

modules/programs/pqiv.nix
tests/modules/programs/pqiv/settings.nix

Now possible to use the pqiv module with `true` instead of `1`
```
```
@iynaix

pqiv: add boolean support

---

home-manager/default.nix
home-manager/home-manager

Closes #5711.
Since 89670e27e101b9b30f5900fc1eb6530258d316b1, FQDN lookup errors from `hostname -f` may cause an early exit of the whole program. This PR offers **two solutions** to the problem:
- The first commit fixes the issue at hand by absorbing the FQDN query inside the `if` statement.
- The second commit simply reverts back to the older simple logic, but now we pull in the GNU `inetutils` dependency whose `hostname` does not panic on failing FQDN queries. See: #5692.
@gauravjuvekar @rycee I am okay with either solution, feel free to pick one!
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/mas …

home-manager: fix early exit due to FQDN error

---

.editorconfig
modules/services/gpg-agent.nix
tests/default.nix
tests/modules/services/gpg-agent/default-homedir.nix
tests/modules/services/gpg-agent/expected-agent.plist
tests/modules/services/gpg-agent/override-homedir.nix

This adds a Darwin Launchd agent along with its sockets to make gpg-agent starts at load or whenever the sockets are needed.
Fixes: https://github.com/nix-community/home-manager/issues/3864
Supersedes: https://github.com/nix-community/home-manager/pull/2964
```
```
@rycee

gpg-agent: add launchd service agent and sockets

---

modules/programs/helix.nix

Removes the outdated comment about the language-server option and adds an example for use with evil-helix
```
```
@Philipp-M Here's the updated PR

helix: update comments

---

modules/services/kanshi.nix
tests/modules/services/kanshi/alias-assertion.nix
tests/modules/services/kanshi/default.nix
tests/modules/services/kanshi/new-configuration.conf
tests/modules/services/kanshi/new-configuration.nix

- Add `services.kanshi.profiles.<name>.outputs.*.alias` to support new alias directive from kanshi [1].
- Add relevant coverage by modifying the existing "new-configuration" test.
[1]: https://git.sr.ht/~emersion/kanshi/commit/1ed86ce523553240ceb81e9d466b88d3554a66bb
_Refer to the commit msg_
```
```
@nurelin

kanshi: add support for output aliases

---

modules/lib/maintainers.nix
modules/misc/news.nix
modules/modules.nix
modules/programs/neovide.nix
tests/default.nix
tests/modules/programs/neovide/default.nix
tests/modules/programs/neovide/expected.toml
tests/modules/programs/neovide/neovide.nix

Neovide is a simple, no-nonsense, cross-platform graphical user interface for Neovim See <https://neovide.dev/>
Used ruff's module as reference during creation
Implemented a neovide module which can be used to generate its `config.toml`
Introduced this PR in the past here #5774 
Same PR and commit but just updated time and news. 
Solves #5791 
```
```

neovide: add module

---

modules/programs/eza.nix
modules/programs/fish.nix

Added support for fish abbreviations instead of aliases in `enableFishIntegration`
```
```
@cafkafk

eza: add support for fish abbreviations

---

modules/programs/git.nix

This adds a new diff-highlight option to make use of the simple included git diff highlighter that comes with canonical git. `diff-highlight` is a perl script that high lights the changes in changed lines. This makes it human-readable and easy to see changes in diffs.
For more info, see https://github.com/git/git/blob/master/contrib/diff-highlight/README
This was inspired by https://github.com/nix-community/home-manager/pull/2882 and https://github.com/nix-community/home-manager/pull/2850
Before:
After:
```
``` …

git: add diff-highlight diff pager option

---

modules/programs/lsd.nix
modules/programs/pls.nix
modules/programs/z-lua.nix

Added support for enabling fish abbreviations for these modules if `preferAbbrs` is enabled
```
```
@arjan-s

{lsd, pls, z-lua}: add support for fish abbreviations

---

modules/services/borgmatic.nix
tests/modules/services/borgmatic/basic-configuration.service

This fixes the permissions of the borgmatic service. Please see #5749  for further info
```
```
@DamienCassou

borgmatic: fix service permissions (#5749)

---

modules/programs/firefox/mkFirefoxModule.nix

Fixes #5820 and prevent `programs.firefox.policies` from being overriden by `setAttrByPath modulePath`. This also adds support for Firefox derivatives to use the `programs.firefox.languagePacks` option.
```
```
@rycee @kira-bruneau @brckd

firefox: fix languagepacks policy

---

modules/programs/thunderbird.nix
tests/modules/programs/thunderbird/thunderbird-expected-second.js
tests/modules/programs/thunderbird/thunderbird.nix

This sets Thunderbird's `settings` option to use a JSON type, just like the Firefox module, so that nested sets can be used.
Tests failed due to something gpg-related before this change.
It might also be worthwhile to extract out Firefox and Thunderbird's modules to some generic Mozilla module so that these common options can be shared 🤷.
```
```
@d-dervishi 
@jkarlson

thunderbird: change settings type to json

---

modules/programs/firefox/mkFirefoxModule.nix

Fixes https://github.com/nix-community/home-manager/pull/5128#discussion_r1727796541. Alltho this hasn't created any issues yet, it makes more sense semantically.
```
```
@rycee @kira-bruneau @brckd

firefox: fix policies availability

---

modules/programs/zoxide.nix

Replace `--no-aliases` flag with `--no-cmd`
Simple update to the "options" example. There's currently only one example flag listed but it's no longer valid, since it was renamed back in 2021 ([0.8.1](https://github.com/ajeetdsouza/zoxide/blob/main/CHANGELOG.md#081---2021-04-23)).
```
```

zoxide: replace outdated flag in "options" example

---

modules/programs/firefox/mkFirefoxModule.nix

PR aims to fix https://github.com/nix-community/home-manager/issues/5717 
add an option for profiles general version 
```
```

firefox: expose profiles version as an option. So firefox can be lanuched ono darwin

---

modules/programs/neovim.nix

Instead of manually adding it as an alias for each and every individual shell, which inevitably ends up missing some.
```
```

neovim: use `home.shellAliases` for the `vimdiffAlias` option

---

modules/services/ssh-agent.nix

According to the documentation, hm-session-vars.sh may be sourced by POSIX compatible shells. Therefore, home.sessionVariablesExtra should only include code that conforms to POSIX.

ssh-agent: use POSIX-conform test for session variables

---

modules/services/poweralertd.nix

Enable passing CLI args to poweralertd.
```
```
@thibautmarty

poweralertd: Enable passing CLI args to the daemon

---

docs/release-notes/rl-2411.md
modules/misc/news.nix
modules/services/swayidle.nix

The option -w causes swayidle to wait on timeouts/events to finish. This can cause problems with certain timeout/event commands (see https://github.com/swaywm/swaylock/issues/86#issuecomment-662702180).
This PR lets the user choose if he wants to use the option. It defaults to the current behavior.
-> swayidle-basic-configuration: OK
```
```
@c0deaddict

swayidle: make -w optional

---

modules/services/swayidle.nix
tests/modules/services/swayidle/basic-configuration.nix

Mostly just code rearrangement, usage of `getExe`, and making the test more explicit.
```
```
@c0deaddict

swayidle: minor cleanups

---

modules/programs/zoxide.nix

`programs.zoxide.options` are passed to `zoxide init` at shell init time, not to the command itself when it's called by the user from their shell. This change makes that a little bit clearer in the documentation. 
I had to look this up when I was setting up zoxide; with this change, I wouldn't have had to.
```
```

zoxide: Clarify `options` option

---

.github/workflows/test.yml

They have been broken for a long time now and makes the PR flow quite cumbersome. Thus we disable them until somebody is able to get them to work again.
```
```

ci: disable the tests for macos

---

modules/programs/direnv.nix
tests/modules/programs/direnv/nushell.nix

Nushell 0.98 makes it so external commands returning non-zero is considered an exception. Wrap the direnv invocation in a try-catch, so that even if direnv fails, we get the message from direnv, but not the traceback from nushell.
```
```

direnv: update for new nushell behavior

---

modules/programs/direnv.nix
tests/modules/programs/direnv/nushell.nix

try/catch in a pipeline does not always work correctly in 0.98, so use `do | complete` instead.
Upstream issue: https://github.com/nushell/nushell/issues/13868
Fixes #5880.
```
```

direnv: work around nushell bug

---

modules/programs/direnv.nix

Avoid do | complete, because it swallows stderr, which can contain direnv debug output.
```
```

direnv: even better nushell fix

---

tests/modules/services/window-managers/river/configuration.nix
tests/modules/services/window-managers/river/init

Specifically, overriding the dbus package can cause rebuilds of many packages.
```
```

river: reduce risk of large rebuilds in test

---

modules/programs/direnv.nix
tests/modules/programs/direnv/nushell.nix

direnv: hopefully final nushell fix

---

modules/programs/borgmatic.nix
tests/default.nix

The current borgmatic module works on Darwin as-is;
mark the platform as supported.
- [N/A] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).
```
```
- [N/A] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).
@DamienCassou

programs.borgmatic: note Darwin platform support

---

modules/services/pass-secret-service.nix

This is nescesarry for non-default locations, and without it, many
programs like element-desktop break in very confusing ways.
Signed-off-by: Christina Sørensen <christina@cafkafk.com>
```
```
@cab404 @cyntheticfox

pass-secret-service: add GNUPGHOME to service env vars

---

modules/services/megasync.nix

This fixes the problem described in #5889, where enabling the `megasync` service resulted in a failed systemd unit.
It was seemingly solved by delaying the launching of the service to after `graphical-session.target` instead of `graphical-session-pre.target`.
```
```
@GaetanLepage

megasync: fix issue with service failing to launch

---

modules/programs/kitty.nix
tests/modules/programs/kitty/example-settings-expected.conf
tests/modules/programs/kitty/example-settings.nix

Extends the values allowed in kitty settings to also include floating-point values, as upstream allows this in some settings.
```
```

kitty: allow float values in settings

---

modules/programs/zathura.nix

Changed the type for `programs.zathura.options` to accept float values as well. You can check their man page (https://manpages.ubuntu.com/manpages/trusty/man5/zathurarc.5.html) as well. In the beginning, they mention:
```
set - Changing options
In  addition  to  the  build-in :set command zathura offers more options to be changed and
makes those changes permanent. To overwrite  an  option  you  just  have  to  add  a  line
structured like the following
set <option> <new value>
The option field has to be replaced with the name of the option that should be changed and
the new value field has to be replaced with the new value the option should get. The  type
of the value can be one of the following:
• INT - An integer number
• FLOAT - A floating point number
• STRING - A character string
• …
```

zathura: Fix the type for config options

---

modules/misc/xdg-mime.nix
tests/modules/misc/xdg/default.nix
tests/modules/misc/xdg/mime-disabled.nix
tests/modules/misc/xdg/mime-expected.cache
tests/modules/misc/xdg/mime-packages.nix
tests/modules/misc/xdg/mime.nix

This PR adds package options for `shared-mime-info` and `desktop-file-utils` for the purpose of allowing users to override the version in nixpkgs. This with overridden version of `shared-mime-info` should  resolve #4955, #5102, #4682, and possibly #4941. I also added a couple basic tests for the module. An example of using the override can be found at notalltim/home-manager-config#4. I did not see a maintainer let me know if I missed one.
```
```

xdg-mime type package options

---

docs/home-manager-manual.nix

We want to expose home-manager in https://search.xn--nschtos-n2a.de/ / https://github.com/NuschtOS/search and for that we need the nixos options json exposed.
```
```
@considerate

home-manager-manual: expose options.json

---

modules/misc/news.nix
modules/modules.nix
modules/services/snixembed.nix
tests/default.nix
tests/modules/services/snixembed/basic-configuration.desktop
tests/modules/services/snixembed/basic-configuration.nix
tests/modules/services/snixembed/basic-configuration.service
tests/modules/services/snixembed/default.nix

https://git.sr.ht/~steef/snixembed
This is used by SafeEyes (another home-manager) module to show a
systemtray icon.
This fixes issue #5728.
```
```

snixembed: add module

---

modules/lib/maintainers.nix
modules/misc/news.nix
modules/modules.nix
modules/programs/vifm.nix
tests/default.nix
tests/modules/programs/vifm/default.nix
tests/modules/programs/vifm/empty-settings.nix
tests/modules/programs/vifm/example-settings.nix

Add new module for program [`vifm`](https://github.com/vifm/vifm).
```
```

vifm: add module

---

modules/programs/pls.nix
tests/modules/programs/pls/bash.nix
tests/modules/programs/pls/fish.nix
tests/modules/programs/pls/zsh.nix

The argument should be perm not perms
The argument should be `perm` instead of `perms`. 
I changed the argument from `perms` to `perm`. Just a little typo. 
- [] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).
- [] Coverage for edge cases considered.
```
```
@arjan-s

pls: fixed perm argument to pass via pls

---

modules/programs/firefox.nix
modules/programs/firefox/mkFirefoxModule.nix
modules/programs/firefox/profiles/search.nix
modules/programs/thunderbird.nix

- Splits firefox search engine configuration into a separate submodule so it can be reused in thunderbird
- Removes myself maintainer for all of firefox, and adds myself as a maintainer for just the search engine submodule
Submodule already tested in `firefox-profile-search` tests.
```
```
Firefox:
@rycee @brckd
Thunderbird:
@d-dervishi

thunderbird: support setting search engines

---

docs/release-notes/rl-2411.md
modules/programs/eza.nix

Fix icons option for eza which was breaking completion in zsh.
Fixes #5800.
```
```
@cafkafk

eza: Fix icons option

---

modules/lib/default.nix
modules/lib/nushell.nix
modules/lib/types.nix
modules/programs/nushell.nix
tests/modules/programs/nushell/env-expected.nu
tests/modules/programs/nushell/example-settings.nix

This PR supersedes #5795.
It adds a nushell generator that works with basic primitive types, records and lists. It also adds a `nushell-inline` to allow generating nushell code instead of strings.
```
```
@Philipp-M @rycee

Nushell generator

---

modules/programs/fish.nix

Add a config option to optionally disable the generation of command completions based upon man pages.
- [?] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.
The tests fail on the master branch for me my changes made no difference.
```
```

programs.fish: Configurable generation of completions.

---

modules/programs/broot.nix

To allow multiple keys the verb options need to accept `listOf str`.
- [-] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef). (I don't think this applies)
```
```
@aheaume  @dermetfan

broot: allow multiple keyboard keys per verb

---

tests/modules/services/activitywatch/basic-setup.nix

This also reduces test flakiness.
```
```

activitywatch: reduce test closure

---

modules/programs/direnv.nix
tests/modules/programs/direnv/nushell.nix

nushell 0.99 does not like early returns in hooks. So, what if we just didn't? Rewrite the entire hook to work as one single pipeline.
```
```

direnv/nushell: simplify, work around nushell/nushell#14112

---

modules/programs/firefox/mkFirefoxModule.nix
modules/programs/thunderbird.nix
tests/modules/programs/firefox/common.nix
tests/modules/programs/firefox/profiles/shared-path.nix

When using multiple profiles that share the same path we still try to evaluate the file even when search customization isn't enabled. 
Follow up to https://github.com/nix-community/home-manager/pull/5697#issuecomment-2411177495 to only evaluate when the profile wants a search.json.mozlz4 file generated. 
```
```
@teto @rycee @kira-bruneau

firefox, thunderbird: conditional search file

---

modules/services/espanso.nix
tests/modules/services/espanso/basic-configuration.service

- Use `launcher` command instead of `daemon`. Additionally we remove `Type` and add `RestartSec` as defined in the source: https://github.com/espanso/espanso/blob/b421bcf73fa13506938d62425459d6c16c6a8d0a/espanso/src/res/linux/systemd.service#L5-L7C1
```
```
@n8henrie @lucasew @liyangau

espanso: use `launcher` command on Linux

---

modules/misc/news.nix
modules/modules.nix
modules/programs/nh.nix

nh is a Nix CLI helper designed to provide beautiful outputs when rebuilding system or garbage collecting. Module already exists for NixOS, and so should for home manager too.
This PR
- adds `programs.nh` option
- Add nh to news
- Add johnrtitor as maintainer
initial PR, I'll be maintaining this HM module

nh: add module

---

modules/programs/neovim.nix

Just trying to fix the recent breakage with config generation, follow up to https://github.com/NixOS/nixpkgs/pull/344541. @teto  would like you to sanity check me here... 
```
```
@rycee @teto

modules/neovim: fix config generation

---

modules/accounts/calendar.nix
modules/accounts/contacts.nix

Fixes that the defaultText gets rendered as string at https://search.nüschtos.de/?query=.local.path&scope=Home%20Manager&option=home-manager.users.%3Cname%3E.accounts.calendar.accounts.%3Cname%3E.local.path
```
```

accounts/{calendar,contacts}: fix defaultText rendering

---

modules/services/gpg-agent.nix

Under certain conditions, `$(tty)` placed in `programs.zsh.initExtra` evaluates to `not a tty` instead of `/dev/pts/*`, which breaks terminal-based pinentry. (see [here](https://unix.stackexchange.com/questions/608842/zshrc-export-gpg-tty-tty-says-not-a-tty) for more information). 
Fixed by using the [`TTY` parameter](https://zsh.sourceforge.io/Doc/Release/Parameters.html#index-TTY) set by Zsh instead.
likely fixes #5888 
```
```
@rycee

gpg-agent: use $TTY parameter in zsh intergration

---

modules/programs/spotify-player.nix
tests/modules/programs/spotify-player/keymap.toml
tests/modules/programs/spotify-player/settings.nix

Add support for configuring actions added in the new [v0.19.1](https://github.com/aome510/spotify-player/releases/tag/v0.19.1) release.
@repparw
```
```

spotify-player: add support for actions

---

modules/programs/htop.nix

Read https://github.com/NixOS/nixpkgs/issues/85508 for why it's a bad idea to use the attrs type.
I noticed this problem while trying to use `mkDefault` for one of the options, which did not work and instead failed with the unhelpful error message `error: cannot coerce a set to a string`.
The new type is a little more strict than the old type. I could have probably used something like `attrsOf anything` but making the type a little more explicit seems like a good idea. Let me know if 100% backwards compatibility is more important.
```
``` …

htop: use attrsOf type instead of attrs as the settings type

---

docs/manual/usage.md
docs/manual/usage/gpu-non-nixos.md
modules/misc/news.nix
modules/misc/nixgl.nix
modules/modules.nix

This PR integrates `nixGL` into home manager in a way that does not introduce a `nixGL` dependency, and attempts to make user configuration as simple as possible. This accomplishes the same goal as #5332, namely making it simpler for users to run applications which require `libGL` on non-nixos systems managed by home manager. There's some elaboration on why I think this is a better API in the [original issue](https://github.com/nix-community/home-manager/issues/3968#issuecomment-2087810068).
It makes use of [a wrapper](https://github.com/guibou/nixGL/issues/114#issuecomment-1585323281) which I have been using for some months to run a few GPU-bound applications on Ubuntu. Judging by post reactions it seems that many other users have also found success with this wrapper. By default it is a …

init: nixgl module

---

modules/programs/yazi.nix

The `programs.yazi.enableNushellIntegration`, `programs.yazi.enableFishIntegration`, and `programs.yazi.enableZshIntegration` options were previously set to `false` by default. 
I didn't find a clear convention, but most of the modules I reviewed set these options to `true` by default. Following this pattern, it seems more appropriate to enable these integrations by default to enhance the user experience.
```
```

yazi: set default integration values for Nushell, Fish, and Zsh to true

---

modules/services/nix-gc.nix
tests/modules/services/nix-gc/basic.nix
tests/modules/services/nix-gc/expected.timer

There's no launchd equivalent to this option, so this is a no-op on Darwin.
```
```
@shivaraj-bh

nix-gc: add `randomizedDelaySec` option

---

modules/programs/git-credential-oauth.nix

Adds a new `extraFlags` option to the `programs.git-credential-oauth` module.
This facilitates a legitimate use-case for browserless systems. From the README:
> On systems without a web browser, set the -device flag to authenticate
> on another device using [OAuth device flow]:
```ini
[credential]
helper = cache --timeout 7200	# two hours
helper = oauth -device
```
[OAuth device flow]: https://www.rfc-editor.org/rfc/rfc8628
~~Please note that, for the documentation about the man-page to be accurate, https://github.com/NixOS/nixpkgs/pull/302922 must be merged~~ (done a while ago).
```
``` …

git-credential-oauth: add extraFlags option

---

modules/programs/eza.nix

This adds an option for the `--color` flag.
```
```
@cafkafk

eza: add color option

---

modules/programs/direnv.nix
tests/modules/programs/direnv/default.nix
tests/modules/programs/direnv/mise.nix

This patch is aim to add support for the already existing program `mise`.
```
```

Add support for mise integration in direnv

---

modules/programs/git-credential-oauth.nix
tests/default.nix
tests/modules/programs/git-credential-oauth/basic.nix
tests/modules/programs/git-credential-oauth/default.nix
tests/modules/programs/git-credential-oauth/extra-flags.nix

* Fix #6005
* Add tests to prevent obvious bugs like the above from slipping through
```
```
@tomodachi94 (no clue who this human is /lh)

git-credential-oauth: fix, add tests

---

modules/programs/git-credential-oauth.nix

when adding storage helpers via git.extraConfig,
git-credential-oauth is not last is `.git/config`, which is the desired state: [ git-credential-oauth must be configured last](https://github.com/hickford/git-credential-oauth?tab=readme-ov-file#how-it-works).
without the correct order, the storage helper is never called.
added mkAfter in git.extraConfig to ensure our oauth is last, as required to work with additional helpers
```
```
@tomodachi94

git-credential-oauth: fix ensure git extraConfig is last in list

---

modules/programs/git.nix

Call to git-maintenance in the systemd user service was using a eroneous value for exec-path flag. Removing the flag is fine.
```
```
@rycee

git: Fix maintenance service

---

modules/home-environment.nix

Closes: https://github.com/nix-community/home-manager/issues/6027
```
```
@rycee

docs: home.sessionVariables clarification

---

modules/programs/helix.nix

This makes extraPackages the default, but they do not shadow the env.
So you can still have packages (e.g. LSPs) with a different version than the global one in you local env like nix's shells.
I guess this is not really backwards compatible but to me this is the expected behaviour. This PR is there to discuss my point.
I checked and it seems there is no test to update. I'm not sure adding a test is necessary.
```
```
@Philipp-M

helix: change wrapping when adding extraPackages to suffix

---

tests/modules/programs/alacritty/settings-toml-expected.toml
tests/modules/programs/spotify-player/theme.toml
tests/modules/services/espanso/basic-matches.yaml

We briefly refactored the tests for three modules to conform to, mostly cosmetic, changes to how TOML and YAML are generated by nixpkgs.
We also had to update the flake.lock to test the changes, as the nixpkgs update happened some time since the last flake.lock update and home-manager-bot couldn't update master since, because of the broken test.
Closes #6049.
Makes #6048 redundant.
Removes implicit blocker of #6042.
```
```
Alacritty TOML: @r-vdp
Espanso YAML: @liyangau
Spotify-Player TOML: @diniamo

Refactor four tests to conform to nixpkgs TOML/YAML changes

---

modules/services/git-sync.nix
tests/modules/services/git-sync/default.nix
tests/modules/services/git-sync/whitespace.nix

We fixed the home-manager git-sync to properly escape the arguments that get written into the users git-sync-\<name\>.service.
We additionally bumped the nixpkgs-unstable version to include our recently merged update PR for git-sync.
git-sync was 2 years out of date and also had a bug with repo paths containing whitespaces.
```
```
@colonelpanic8 @cab404 @ryane

Fix git-sync crash when whitespace in path

---

modules/services/kanshi.nix

Currently, enabling `services.kanshi` does not make the `kanshi` executable on the user `$PATH`.
Although the goal of this module is providing a systemd service for `kanshi`, it can still be useful to run the software manually from time to time.
For instance, this can be used to manually select a profile.
```
```
cc @nurelin

kanshi: add package to home.packages

---

modules/programs/feh.nix
tests/modules/programs/feh/default.nix
tests/modules/programs/feh/feh-empty-settings.nix
tests/modules/programs/feh/feh-themes-expected
tests/modules/programs/feh/feh-themes.nix

- added themes option
- added themes test
- updated broken man page links
```
```
No `meta.maintainers` list for this module, so @-ing those who have last touched it.
@sumnerevans 
@ncfavier 
@rycee

feh: add themes option

---

nixos/default.nix

Currently, the home-manager systemd service will only get restarted when the home-manager configuration changes. This can lead to issues in users' home directories not getting corrected for a while.
$ rm ~/.zshrc
$ sudo nixos-rebuild switch
$ ls ~/.zshrc
ls: cannot access '/home/enzime/.zshrc': No such file or directory
```
```
cc @rycee

nixos: always run home-manager on NixOS activation

---

nixos/default.nix

By adding `key`, this allows users to disable this shared module or they can choose to not disable this shared module (by filtering by key before disabling)
This means users can disable all shared modules if all modules are paths or attrsets with a key:
`configuration.nix`:
```nix
{ config, ... }:
{
home-manager.users.enzime = { ... }: {
disabledModules = config.home-manager.sharedModules;
};
}
```
Or disabling just this module specifically:
```nix
{ ... }:
{
home-manager.users.enzime = { ... }: {
disabledModules = [ { key = "home-manager#nixos-shared-module"; } ];
};
}
```
Or disabling all modules when you have modules you can't disable (like lambdas):
```nix
{ ... }:
{
home-manager.users.enzime = { ... }: {
disabledModules = lib.filter (v: lib.isString v || lib.isPath v || (lib.isAttrs …
```

nixos: add `key` to shared module to allow disabling it

---

modules/misc/gtk.nix
modules/services/dunst.nix

`adwaita-icon-theme` has been moved out of the `gnome` scope and into the top level with https://github.com/NixOS/nixpkgs/pull/319659.
Replaces every instance of `pkgs.gnome.adwaita-icon-theme` with `gnome.adwaita-icon-theme` in the `options.package.examples` for `gtk` and `dunst`. Doing so prevents an evaluation warning about the scope change to top-level.
```
```

{gtk, dunst}: replace `pkgs.gnome.adwaita-icon-theme` with `pkgs.adwaita-icon-theme` in the examples

---

modules/lib/file-type.nix

This is something that is useful, we should not hide it from the docs.
```
```

lib/file-type: Make `force` option visible

---

modules/programs/firefox/mkFirefoxModule.nix
modules/programs/firefox/profiles/search.nix
modules/programs/thunderbird.nix

Using a fixed application name in the salt for the search engine name hash can break with minor branding changes. For example, LibreWolf 127 used the application name "LibreWolf", but in version 128 it's "Firefox".
The proper name can be found in about:support -> Application Basics.
Because it doesn't have to be related to the product name visible in most of the browser (for example in the window title and help menus), we shouldn't rely on cfg.name for that.
The application name can be read from lib/*/application.ini and we can use that if the browser was installed via home-manager. If not, we can fall back to cfg.name.
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent …

firefox: read the appName for search engine disclaimer from package

---

modules/programs/firefox/mkFirefoxModule.nix
modules/programs/librewolf.nix

librewolf: use mkFirefoxModule

---

modules/services/syncthing.nix
tests/modules/services/syncthing/common/extra-options.nix

This PR expands the Syncthing config to allow declarative settings. Code mostly pulled from [Nixpkgs module](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/networking/syncthing.nix). Addresses #4049.
Removed the following options:
- `user`, `group`, `systemService`: Unnecessary since Syncthing always runs as the user declaring the config.
- `dataDir` `configDir`, `databaseDir`: Pointed to ~/.local/state/syncthing, the default Syncthing directory.
- `openDefaultPorts`: We don't have access to the system firewall.
Furthermore, multiple changes to `systemd` services were made to maintain consistency with other `home-manager` modules, sandboxing options might need to be reviewed further.
I have marked the PR as a draft while I test it over the next week or so.
@rycee

syncthing: expand declarative config

---

modules/config/home-cursor.nix

add the option to enable hyprcursor support by setting the relevant environment variables
"hyprcursor is a new cursor theme format that has many advantages over the widely used xcursor." - https://wiki.hyprland.org/Hypr-Ecosystem/hyprcursor/
This pull request is for adding an option to home-cursor to set the two variables needed for hyprcursor to set a theme, `HYPRCURSOR_THEME` and `HYPRCURSOR_SIZE`
I think the specific size option should be included, as that is specifically one benefit of hyprcursors, since all sizes are supported and not just a few common ones like in xcursor, but if this is not desired I can just remove it (I also don't know if this is the best way to make the size optional so that if it is not set to just use the size from xcursor)
```
{long …
```

home-cursor: add hyprcursor support

---

modules/services/conky.nix

Currently systemd ExecStart uses pks.conky as executable path, this commit changes it to the package defined by services.conky.package
```
```
@kaleocheng

conky: update systemd exec path to config package

---

modules/services/podman-linux/default.nix
tests/modules/services/podman-linux/configuration-containers-expected.conf
tests/modules/services/podman-linux/configuration-policy-expected.json
tests/modules/services/podman-linux/configuration-registries-expected.conf
tests/modules/services/podman-linux/configuration-storage-expected.conf
tests/modules/services/podman-linux/configuration.nix
tests/modules/services/podman-linux/default.nix

Copied some useful options from NixOS podman module and adapted the configuration to home-manager.
Also setting `services.podman.enable = true` will now add `podman` to `PATH`.
```
```
@bamhm182 @n-hass

podman: install package if enabled and create config files

---

modules/services/hyprpaper.nix
tests/modules/services/hyprpaper/default.nix
tests/modules/services/hyprpaper/no-configuration.nix

> Applies the same fix here from <https://github.com/nix-community/home-manager/pull/6131>.
The the systemd user service depends on `config.xdg.configFile."hypr/hyprpaper.conf".source` for `X-Restart-Triggers`. When `cfg.settings` is the default `{}`, this causes failure since `config.xdg.configFile."hypr/hyprpaper.conf".source` will not exist.
Making the addition conditional on `cfg.settings` actually having content, which would mean `xdg.configFile."hypr/hyprpaper.conf"` does exist, avoids the error.
```
``` …

hyprpaper: fix service when no config file

---

modules/programs/abook.nix

Abook is also available on other platforms, eg Darwin
```
```

programs.abook: remove platform linux assertion

---

modules/services/volnoti.nix
tests/default.nix
tests/modules/services/volnoti/default.nix
tests/modules/services/volnoti/package-option.nix

The `services.volnoti.package` option was not used for the systemd user service. This PR fixes the issue, as well as adds myself to the module's maintainers and a test case.
```
```
@colonelpanic8

 volnoti: use cfg.package instead of pkgs

---

modules/services/mopidy.nix

Restart the systemd service on failure to ensure the service is always running even if it crashes.
```
```

mopidy: restart the systemd service on failure

---

modules/services/mopidy.nix
tests/modules/services/mopidy/basic-configuration.nix

The Mopidy service is not restarted when the config changes.
This PR adds `X-Restart-Triggers` to the unit to ensure that the service is restarted on config file changes.
```
```

mopidy: restart service on config changes

---

modules/programs/tmux.nix
tests/modules/programs/tmux/default-shell.conf
tests/modules/programs/tmux/disable-confirmation-prompt.conf
tests/modules/programs/tmux/emacs-with-plugins.conf
tests/modules/programs/tmux/mouse-enabled.conf
tests/modules/programs/tmux/prefix.conf
tests/modules/programs/tmux/shortcut-without-prefix.conf
tests/modules/programs/tmux/vi-all-true.conf

In #5952, it was pointed out that tmux has changed how it handles shells, and because of this, the tmux.shell option doesn’t work properly unless tmux-sensible is turned off.
However, tmux-sensible hasn’t been updated for over two years, as mentioned [here](https://github.com/tmux-plugins/tmux-sensible/pull/70#issuecomment-2127666779). Since it’s no longer actively maintained, keeping it enabled by default is becoming more of a problem.
This PR suggests turning off tmux-sensible by default to avoid these issues and improve usability.
```
``` …

tmux: Disable tmux-sensible by Default (bug fix)

---

modules/services/kdeconnect.nix

Plasma6 has been out for a while now and the service still points to the old, incompatible version.
Upgrade the default version of kde-connect to use Plasma6.
The current one, based on Plasma5, is 23.08 and incompatible with Plasma6.
```
```
@adisbladis

kdeconnect: Upgrade default version to Plasma6

---

modules/services/mopidy.nix

Using Mopidy extensions is broken in multiple ways currently, which is apparent when cross building. The first issue is the error `error: makeWrapper/makeShellWrapper must be in nativeBuildInputs`, which has an obvious solution.
The other issue stems from Python dependency conflicts between Mopidy and any enabled extensions. This is an issue upstream in `nixpkgs`. See nixos/nixpkgs#297539. I've created a PR to fix the issue upstream in nixos/nixpkgs#354069.
```
```

mopidy: fix issues with building extensions

---

modules/services/lorri.nix

Since https://github.com/nix-community/lorri/pull/128, lorri no longer uses this legacy path for gcroots, and instead delegates to the Nix daemon. Leaving the path here causes the service to fail to start if the directory does not exist on the user's system:
```
nov 28 11:49:14 meitan (lorri)[50058]: lorri.service: Failed to set up mount namespacing: /nix/var/nix/gcroots/per-user/kmicklas: No such file or directory
nov 28 11:49:14 meitan systemd[2265]: lorri.service: Main process exited, code=exited, status=226/NAMESPACE
nov 28 11:49:14 meitan systemd[2265]: lorri.service: Failed with result 'exit-code'.
```
```
``` …

lorri: fix ReadWritePaths for new gcroots behavior

---

modules/programs/zsh/zsh-abbr.nix

Add package option to zsh-abbr so users can switch to a different version of zsh-abbr (i.e. use unstable version of zsh-abbr). 
```
```
@ilaumjd

zsh-abbr: Add package option

---

modules/programs/yazi.nix
tests/modules/programs/yazi/keymap-expected.toml
tests/modules/programs/yazi/settings.nix

Update description and tests for the `yazi.keymap` option to reflect upstream changes.
```
```
cc @XYenon @eljamm

yazi: update keymap config

---

modules/misc/news.nix
modules/modules.nix
modules/programs/kubecolor.nix
tests/default.nix
tests/modules/programs/kubecolor/default.nix
tests/modules/programs/kubecolor/empty-config.nix
tests/modules/programs/kubecolor/example-config-default-paths.nix
tests/modules/programs/kubecolor/example-config-xdg-paths.nix

Add support for [kubecolor](https://github.com/kubecolor/kubecolor) program.
```
```

kubecolor: add module

---

modules/programs/alot.nix

This PR allows to configure which `alot` binary should be used in the `programs.alot` module.
This allows to e.g. easily work with the upstream flake: https://github.com/pazz/alot/blob/master/flake.nix
```
```

alot: make package used by module configurable

---

modules/services/podman-linux/services.nix
tests/modules/services/podman-linux/container-expected.service
tests/modules/services/podman-linux/integration-container-expected.service
tests/modules/services/podman-linux/integration-network-expected.service
tests/modules/services/podman-linux/network-expected.service

Fix the current CI failure by adapting the relevant snapshot.
```
```

podman-container: fix test

---

modules/programs/tmux.nix
tests/modules/programs/tmux/default-shell.conf
tests/modules/programs/tmux/disable-confirmation-prompt.conf
tests/modules/programs/tmux/emacs-with-plugins.conf
tests/modules/programs/tmux/mouse-enabled.conf
tests/modules/programs/tmux/prefix.conf
tests/modules/programs/tmux/shortcut-without-prefix.conf
tests/modules/programs/tmux/vi-all-true.conf

With `tmux-sensible` being disabled by default (#6091), add an easy toggle to enable this functionality.
Disabled by default, as in upstream `tmux` (I _could_ see an argument for enabling it by default, as `sensibleOnTop` was enabled by default and enabled this option unconditionally, but historically that's not been the way default option values have been chosen for this module).
```
```
@rycee

tmux: add 'focusEvents'

---

modules/programs/atuin.nix

This configures the atuin daemon for Linux and Darwin systems using systemd and launchd, respectively. For systemd, a socket is also automatically configured to exist at atuin's default socket location.
I also added myself as a maintainer of this module.
Closes #5797.
```
```
@hawkw

atuin: configure daemon using systemd and launchd

---

modules/programs/kakoune.nix

Honestly I don't know how this slipped through I must have added it to my local option and forgotten to include it in the branch for the pr #5653 , oops.
```
```

kakoune: add missing '.source' from colorSchemePackage xdg file

---

modules/misc/qt/kconfig.nix

Update to configuration tool for plasma6.
Not sure why we had this `test -f` in the activation code?
```
```
cc @tschai-yim @thiagokokada @JulianFP

qt: use kwriteconfig6 in qt.kde.settings and actually call the tool

---

modules/config/home-cursor.nix
modules/xresources.nix

`xsession.initExtra` is executed after systemd graphical-session.target, which means graphical applications started by graphical-session.target can get these x settings.
```
```
@rycee @polykernel @league

home-cursor, xresources: use `profileExtra` instead of `initExtra`

---

modules/programs/zsh.nix

~The current implementation completely overrides any declaration of ZSH_AUTOSUGGEST_STRATEGY, which can break some user's settings (in my case, breaks adding abbr's suggestion strategy). New implementation now allows for users to define more than just `history`, `completion`, and `match_prev_cmd` and will auto append the variable if there are existing declarations of ZSH_AUTOSUGGEST_STRATEGY in the user's zshrc; and if there isn't any existing declaration, then simply just set the variable. Additionally, it can be left to empty (`[  ]`) which would completely disable the accompanying code; allowing users to fully decide where they want to place ZSH_AUTOSUGGEST_STRATEGY. And finally, use `typeset -U` to remove any possible duplicate values in the variable.~ The original scope of this PR …

zsh: make autosuggest strategy accept more options

---

modules/programs/mangohud.nix

mangohud: fix a non-working example of settingsPerApplication

---

modules/misc/news.nix
modules/programs/starship.nix
tests/modules/programs/starship/default.nix
tests/modules/programs/starship/fish_with_interactive.nix
tests/modules/programs/starship/fish_without_interactive.nix

- Some fish plugins such as [fish-async-prompt](https://github.com/acomagu/fish-async-prompt) require that starship be initialized as non-interactive.
When the `programs.starship.enableInteractive` option is enabled, starship is initialized at the end of the init script, outside the interactive block.
**Note:** Don't know if other shells need this, so I only added this for fish for now.
- Also changed the initialization method from `eval` to `source` as per the [starship installation](https://starship.rs/guide/#%F0%9F%9A%80-installation) guide.
Closes #5445 
```
```

starship: add `enableInteractive` option for fish

---

modules/services/imapnotify.nix
tests/modules/services/imapnotify/imapnotify.service

Some tools are a bit too painful to get working without PATH.
This includes some useful presetting for notmuch and mbsync.
```
```
@NickHu

imapnotify: provide an option for setting PATH

---

modules/programs/thunderbird.nix
tests/modules/programs/thunderbird/thunderbird-expected-first.js

Previously, only the main identity of an account would get the proper SMTP server assigned. Identities corresponding to aliases would not get an SMTP server assigned at all, leading to a (Thunderbird-internal) fallback to the SMTP server associated to the primary account. This is obviously wrong for non-primary accounts having aliases associated to them. Fix it by specifying the SMTP server explicitly for all identities.
```
```

thunderbird: set the correct SMTP server for aliases

---

modules/programs/atuin.nix

Use systemd path specifiers for appropriate path prefixes instead of assuming paths. This PR is future compatible with 18.4.0 preferring XDG_RUNTIME_PATH over XDG_DATA_DIR.
```
```
@hawkw @water-sucks

atuin: Do not hardcode daemon socket path

---

modules/misc/news.nix
modules/programs/nushell.nix
tests/modules/programs/nushell/example-settings.nix

When the version of Nushell or any Nushell plugin changes, the plugin registry must be regenerated.  This adds an option that takes a list of Nushell plugin derivations and recreates the plugin registry file (`~/.config/nushell/plugin.msgpackz`) on profile activation.
Thanks to @crabdancing for most of the work: https://github.com/nushell/nushell/discussions/12997#discussioncomment-9638977
I believe this is worth adding a news entry even though it is only adding an option, because this has been a significant pain point for anyone using plugins with Nushell managed by home-manager.
```
``` …

nushell: allow installing plugins

---

modules/misc/qt.nix

Following discussions at https://github.com/NixOS/nixpkgs/pull/362949, this PR fixes file dialogs when KDE is not installed but `qt.platformTheme = "kde"` (common for theming purposes). Without it, file dialogs fail to show files and folders. Only an issue when KDE is not installed, because KDE installs kio in its own module.
```
```
@rycee @thiagokokada

qt: install kio when qt.platformTheme = "kde"

---

modules/services/gpg-agent.nix

D-Bus services are queried from Home Manager packages too. NixOS is not required.
```
```

gpg-agent: fix GCR DBus package note

---

modules/misc/news.nix
modules/programs/mbsync-accounts.nix
modules/programs/mbsync.nix
tests/modules/programs/mbsync/mbsync-expected.conf
tests/modules/programs/mbsync/mbsync.nix

This is a backport of  #5918. `isync` was also updated in `nixos-24.11`, so the option deprecation warning appears there as well. I think this should be backwards compatible.
```
```
@KarlJoad

[24.11 backport] isync/mbsync: update module for 1.5.0 changes

---

home-manager/home-manager

The home manager script fails when `$USER` contains special characters.
For example, my work PC is managed by company's LDAP and username is `<COMPANY>\<user>`). When running `home-manager switch` I get the following error:
```
error: flake 'path:/home/<COMPANY>/<user>/.config/home-manager' does not provide attribute 'packages.x86_64-linux.homeConfigurations."<COMPANY>\<user>".activationPackage', 'legacyPackages.x86_64-linux.homeConfigurations."<COMPANY>\<user>".activationPackage' or 'homeConfigurations."<COMPANY>\<user>".activationPackage'
Did you mean <COMPANY><user>?
```
There are two types of strings that need escaping:
- strings in Nix expressions (e.g. `home.nix` generated by `home-manager init`)
they need backslashes before special chars 
- flake URI (passed to `nix build`)
they …

home-manager: support username with special chars

---

tests/modules/programs/gpg/immutable-keyfiles.nix

would fail on tests
with
```
trying https://www.rsync.net/resources/pubkey.txt
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  1855  100  1855    0     0   5086      0 --:--:-- --:--:-- --:--:--  5082
100  2584  100  2584    0     0   3462      0 --:--:-- --:--:-- --:--:--  3459
error: hash mismatch in fixed-output derivation '/nix/store/vfb9lh1nqla2aym1pkngc7f85bsy2f7g-lookup?op=get-options=mr-search=0x44CF42371ADF842E12F116EAA9D3F98FCCF5460B.drv':
specified: sha256-u01QTYEFSY1feJWX3JJjXB6thiVO4WOnrqNmzg6vIDs=
got:    sha256-bSluCZh6ijwppigk8iF2BwWKZgq1WDbIjyYQRK772dM=
error: 1 dependencies of derivation '/nix/store/06y1mjj51ldssghilhk7vwsvfk8dhvzw-gpg-pubring.drv' failed to build
error: 1 dependencies of …
```

programs.gpg: fix hash of test

---

modules/programs/gnome-shell.nix
tests/modules/programs/gnome-shell/gnome-shell.nix

Else I get a
===
… while calling the 'throw' builtin
at /nix/store/afpmddfrmx5df3h16bdh00yy8i7db8w4-source/pkgs/desktops/gnome/default.nix:96:28:
95|   gnome-shell = throw "The ‘gnome.gnome-shell’ was moved to top-level. Please use ‘pkgs.gnome-shell’ directly."; # Added on 2024-08-28.
96|   gnome-shell-extensions = throw "The ‘gnome.gnome-shell-extensions’ was moved to top-level. Please use ‘pkgs.gnome-shell-extensions’ directly."; # Added on 2024-08-11.
|                            ^
97|   gnome-software = throw "The ‘gnome.gnome-software’ was moved to top-level. Please use ‘pkgs.gnome-software’ directly."; # Added on 2024-08-11.
error: The ‘gnome.gnome-shell-extensions’ was moved to top-level. Please use ‘pkgs.gnome-shell-extensions’ directly.
===
on rebuild
```
{component}: …
```

programs.gnome-shell: fix extensions' default

---

modules/services/kanshi.nix
tests/modules/services/kanshi/new-configuration.conf

kanshi always writes a config. Dont write if if in absence of nix settings.
```
```

kanshi dont write config in absence of nix settings

---

docs/release-notes/rl-2411.md

Fix typo: 24.05 should be 24.11.
```
```

docs: fix typo in 24.11 release notes

---

modules/programs/thunderbird.nix

Similar to what we did for firefox for darwin support.
Follow up to https://github.com/nix-community/home-manager/pull/5723
Haven't been using the firefox module on my macbook and ran into the same issue. Using my fork so I can use thunderbird again. 
```
```

thunderbird: add profileVersion

---

home-manager/home-manager
tests/integration/default.nix
tests/integration/standalone/home-with-symbols-init.nix
tests/integration/standalone/home-with-symbols.nix

home-manager: improve path handling when building news

---

modules/programs/yazi.nix
tests/modules/programs/yazi/settings-expected.toml
tests/modules/programs/yazi/settings.nix
tests/modules/programs/yazi/theme-expected.toml

Yazi changed the allowed values for:
- its [setting `manager.sort_by`](https://yazi-rs.github.io/docs/configuration/yazi/#manager.sort_by). Option `modified` is now called `mtime`.
- its [setting `theme.filetype.rules.mime-type`](https://yazi-rs.github.io/docs/configuration/theme#filetype) to no longer use `x-` prefix for mime types. For example, `application/x-bzip` is not called `appliation/bzip`.
This PR makes the settings suggested by hm to be fully compatible with Yazi 0.4.
- It is not, but it is also only a change in the example for an option value. And users get a nice warning when the option "modified" is used.
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent …

yazi: Fix example option values for settings

---

modules/lib/maintainers.nix
modules/misc/news.nix
modules/modules.nix
modules/programs/pay-respects.nix
tests/default.nix
tests/modules/programs/pay-respects/default.nix
tests/modules/programs/pay-respects/integration-disabled.nix
tests/modules/programs/pay-respects/integration-enabled.nix

Add pay-respects module including shell integration support for bash, zsh, fish and nushell
```
```

pay-respects: add module

---

modules/programs/waybar.nix

waybar: add systemd restart triggers

---

modules/xresources.nix
tests/modules/xresources/xresources-expected.conf
tests/modules/xresources/xresources.nix

`.Xresources` contains properties such as `faceSize` which specifies the font's *pointsize*.
https://www.x.org/archive/X11R6.7.0/doc/xterm.1.html#:~:text=facesize%20(class%20facesize)
> faceSize (class FaceSize)
>     Specify the pointsize for fonts selected from the FreeType library if support for that library was compiled into xterm. The default is ``14.''
This means that floating point values should be allowed in the config.
```
```
@rycee

xresources: allow floating point values

---

modules/misc/nixgl.nix

Currently, wrapping packages with `nixGL.wrap` will break any options in home manager modules that use `override` to modify the package.
This change overrides `override` on the wrapper package, such that it will instead forward the call to the internal package, and return a wrapped version of the result with the same arguments.
Tested via the `programs.chromium.commandLineArgs` option mentioned in #6016, with several other wrapped packages in my config to regression test.
Fixes #6016.
```
```

nixgl: forward override calls to wrapped package

---

modules/programs/mu.nix
tests/integration/default.nix
tests/integration/standalone/mu/config-account-without-mu.nix
tests/integration/standalone/mu/config-no-accounts.nix
tests/integration/standalone/mu/config-one-account.nix
tests/integration/standalone/mu/config-one-alias.nix
tests/integration/standalone/mu/config-two-accounts.nix
tests/integration/standalone/mu/default.nix
tests/modules/programs/mu/basic-configuration.nix

When the user changes which addresses mu should consider 'personal', mu's store should be reinitialized.
After this change, the activation script parses the previously configured list of addresses and compares it with the new one. If they differ, it runs the init command even when the store has already been initialized.
```
```
@KarlJoad

mu: run initialization command when personal addresses change

---

modules/programs/swayr.nix

Avoids IFD in the swayr module.
Confirm IFD on `master` with
```nix
nix build --no-allow-import-from-derivation .\#test-swayr-basic-configuration
```
It fails due to IFD not being allowed.
On this branch the same command succeeds because IFD is not used. 
```
```
@9p4

swayr: avoid IFD

---

modules/programs/pqiv.nix

Issue: #6212
Due to flawed logic, configuration file for `programs.pqiv` was only written if both `settings` and `extraConfig` were set.
Desired behaviour is that either form of supplied configuration should trigger the creation of the config file. 
```
```
@donovanglover @iynaix

programs.pqiv.nix: write configuration if either settings or extraConfig are set

---

modules/services/copyq.nix
tests/default.nix
tests/modules/services/copyq/basic-configuration.nix
tests/modules/services/copyq/basic-expected.service
tests/modules/services/copyq/default.nix
tests/modules/services/copyq/dont-force-x-configuration.nix
tests/modules/services/copyq/dont-force-x-expected.service

The current CopyQ service always forces the use of XWayland, this PR adds option to disable that.
```
```
@DamienCassou

copyq: add option to disable XWayland

---

modules/programs/bacon.nix
tests/modules/programs/bacon/bacon.nix
tests/modules/programs/bacon/default.nix
tests/modules/programs/bacon/empty-config.nix

bacon reads its preferences from a different directory on Darwin. Fix the path to read out of:
~/Library/Application\ Support/org.dystroy.bacon/prefs.toml Linux behavior should be unchanged.
```
```
@shimunn

bacon: fix configuration file location on Darwin

---

format

This can cause failures if the user has configuration that is incompatible with the version of git pinned in the format script.
Potentially it could have other undesired effects as well.
Fix #5736
```
```
@rycee

format: ignore system and user git config

---

home-manager/po/home-manager.pot
modules/files.nix
modules/home-environment.nix
modules/lib-bash/activation-init.sh
modules/po/hm-modules.pot
tests/integration/standalone/flake-basics.nix

This commit separates profile management (setting profile and creating GC root) from file management (removing and adding managed files within the user's home directory).
This is a step towards deprecating profile management within the activation script, instead relying on the caller of the activation script managing the profile.
```
```

home-manager: move profile management

---

modules/programs/ghostty.nix

Turns out that `*/ghostty/config` doesn't work. So updated it to use `xdg.configHome` instead.
```
```

ghostty: fix configuration for bat syntax

---

modules/modules.nix
modules/programs/waybar.nix
modules/services/avizo.nix
modules/services/clipman.nix
modules/services/dunst.nix
modules/services/fnott.nix
modules/services/hypridle.nix
modules/services/hyprpaper.nix
modules/services/kanshi.nix
modules/services/swayidle.nix
modules/services/swaync.nix
modules/services/swayosd.nix
modules/services/wob.nix
modules/wayland.nix
tests/modules/programs/waybar/deprecated-modules-option.nix
tests/modules/programs/waybar/settings-complex.nix
tests/modules/programs/waybar/settings-with-attrs.nix
tests/modules/programs/waybar/styling.nix
tests/modules/programs/waybar/systemd-with-graphical-session-target.nix
tests/modules/programs/waybar/systemd-with-graphical-session-target.service
tests/modules/services/clipman/clipman-sway-session-target.service
tests/modules/services/fnott/systemd-user-service-expected.service
tests/modules/services/swayidle/basic-configuration.nix
tests/modules/services/swaync/swaync.nix

Second try of PR https://github.com/nix-community/home-manager/pull/6239.
Graphical services that are meant for Wayland environment are all over the place:
- Some set `After = [ "graphical-session-pre.target" ]`, that is almost always a mistake ([see](https://github.com/Vladimir-csp/uwsm/issues/40)), others set `After = [ "graphical-session.target" ]`
- Some have `systemd.target` (or `systemdTarget`) to allow changing the default target, some does not
- Some set `ConditionEnvironment = "WAYLAND_DISPLAY"`, some does not
This PR tries to standardize this by:
- Adding `wayland.systemd.target` that is a new option for the default systemd target for all Wayland services. Defaults to `graphical-session.target`
- Set `After`, `PartOf` and `Wanted` to `cfg.systemd.target` 
- Adding …

treewide: standardize wayland graphical services

---

modules/lib/maintainers.nix
modules/services/network-manager-applet.nix

I changed the maintainer list to reflect my username and email changes.  Also, I updated any modules that had me as a maintainer in the modules' metadata to the one used in nixpkgs repo.
```
```
@rycee

maintainers: updated username to midirhee12

---

modules/programs/ghostty.nix

Runs `ghostty +validate-config` when the configuration file changes.
```
```
@HeitorAugustoLN

ghostty: Validate configuration on change

---

modules/programs/neomutt.nix

I stumbled over this, and figured I add some documentation about how to do it.
```
```
@gbirke @Cybolic

Document how to bind Ctrl keys in neomutt config

---

home-manager/home-manager

From the discussions in https://github.com/nix-community/home-manager/issues/4198, it seems like folks prefer the default Nix behaviour, and there's been no progress on https://github.com/NixOS/nix/issues/8710
So let's revert https://github.com/nix-community/home-manager/pull/3646 (I was the original author)

Revert "home-manager: Use path: URI type for flake default"

---

modules/programs/neomutt.nix

The allowed entries for `programs.neomutt.sort` were missing the `last` prefix, as shown in the [documentation](https://neomutt.org/man/neomuttrc), under the `sort` entry.
Fixes #6263
```
```

neomutt: added missing sort options

---

modules/services/gpg-agent.nix

When `services.gpg-agent.enableSshSupport` is set, the module adds script to `home.sessionVariablesExtra` with non-portable double bracket `[[` syntax.
The script is written to `hm-session-vars.sh`, which will be referenced by `~/.profile` (if managed by home-manager) and sourced by `sh` which doesn't support this syntax. (e.g. when logging in graphical session with uwsm, it uses `sh` to source `~/.profile` to get environment variables)
The portable single bracket `[` syntax also supports the `-z` operator, so we can just use it instead.
```
``` …

gpg-agent: fix compatibility with sh when enableSshSupport

---

modules/programs/go.nix
tests/default.nix
tests/modules/programs/go/default.nix
tests/modules/programs/go/go-telemetry.nix

This PR adds 2 options for `programs.go` to configure Go telemetry mode. This is the same as running `go telemetry <mode>` manually, with a pre-configured date.
```
```
@rvolosatovs

go: add telemetry options

---

modules/lib/maintainers.nix
modules/modules.nix
modules/programs/todoman.nix
tests/modules/programs/todoman/config.nix
tests/modules/programs/todoman/default.nix
tests/modules/programs/todoman/todoman-config-expected

Adds Mikilio as maintainer for new module for todoman a standards-based task manager based on iCalendar
```
```
@rycee

todoman: add todoman module

---

modules/modules.nix
modules/services/ollama.nix
tests/default.nix
tests/modules/services/ollama/basic.nix
tests/modules/services/ollama/default.nix
tests/modules/services/ollama/set-environment-variables.nix

This adds the service ollama, based on the [corresponding NixOS module](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/misc/ollama.nix)
It skips some of the options that doesn't make sense for the user unit and of course work with the Home Manager `systemd.user.services` which is slightly different.
Fix #5152
```
```

ollama: add module

---

modules/programs/mangohud.nix
tests/modules/programs/mangohud/basic-configuration.conf

mangohud: make `false` values actually disable
Currently the following, will produce `some_opt=false` in the rendered config:
```nix
programs.mangohud.settings = {
some_opt = false;
};
```
With the intention being to disable the option, this would be incorrect, as per
the following stated at:
<https://github.com/flightlessmango/MangoHud/blob/0575c8eb1f61692a2e5ca152c4f8ed70bef55ee2/data/MangoHud.conf#L3C5-L4C1>
> Use some_parameter=0 to disable a parameter (only works with on/off
> parameters)
As such, I changed the rendering to follow this. This will be output instead: `some_opt=0`
`nix develop --ignore-environment .#all` using Flakes.
[example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).
``` …
```

mangohud: make `false` values actually disable

---

modules/services/window-managers/i3-sway/lib/options.nix

* allow using `--i3` for hideEdgeBorders
* add `smart_no_gaps` option
```
```
@Scrumplex 
@alexarice
@sumnerevans
@oxalica

sway: allow sway specific hideEdgeBorders options

---

modules/programs/hyprlock.nix

Since hyprwm/hyprlock@00d2cbf hyprlock supports the animation and bezier keywords from Hyprland. But, bezier needs to be defined before an animation can use it.
Closes https://github.com/nix-community/home-manager/issues/6316
```
```
@rycee @fufexan

hyprlock: add bezier to importantPrefixes

---

modules/programs/sbt.nix
tests/modules/programs/sbt/plugins.nix

Sometimes plugins doesn't follow the form
```
addSbtPlugin("${plugin.org}" % "${plugin.artifact}" % "${plugin.version}")
```
for instance
```
addDependencyTreePlugin
```
This commit allow free form plugin dependency.
Got a repetitive "core dump" error so I ran the sbt tests specifically:
```
❯ nix-shell --pure tests -A list | grep sbt
sbt-credentials
sbt-deprecated-options
sbt-plugins
sbt-repositories
sbt-user-config-path
❯ nix-shell --pure tests -A run.sbt-credentials run.sbt-deprecated-options 
error: getting status of '/home/jprudent/projects/home-manager/run.sbt-deprecated-options': No such file or directory
❯ nix-shell --pure tests -A run.sbt-deprecated-options
building '/nix/store/4hxh0dr4jc0pz3ms7fjmgyr1a0zcf0ib-assertions.expected.drv'...
building …
```

sbt: allow irregular plugins to be configured

---

modules/services/syncthing.nix

Add --wait flag to tray to avoid loading before bar. Attempts to fix #3416 per the comments. It appears that #4548 already has some work towards this, but that's been sitting stale so this present and trivial PR is a just to tide us over until that gets sorted out.
```
```

syncthing: have tray wait for bar to load

---

modules/i18n/input-method/fcitx5.nix

Now there's `libsForQt5.fcitx5` and `kdePackages.fcitx5` in nixpkgs, we should allow user to choose which one to use.
```
```
@Kranzes

fcitx5: allow to set fcitx5-with-addons

---

modules/programs/mu.nix
tests/modules/programs/mu/basic-configuration.nix
tests/modules/programs/mu/custom-configuration.nix
tests/modules/programs/mu/default.nix

Supersedes and closes #5535
Allows for the database path for mu to be configured. Useful for keeping the maildir and mu xapian cache together without having to modify XDG_CACHE_HOME. Add test to check for custom home setting.
Fixes #5534
```
```
@Karljo

mu: allow option to set muhome

---

modules/programs/lsd.nix

Cleanup that didn't got in in the previous PR (#5966)
```
```
@Avimitin @marsam (@rycee)

lsd: remove with lib;

---

modules/misc/news.nix
modules/programs/yazi.nix
tests/modules/programs/yazi/fish-integration-enabled.nix
tests/modules/programs/yazi/fish-integration-expected.fish

Improve yazi fish integration:
Calls yazi as `command yazi`, allowing to use "yazi" as `shellWrapperName` without infinite recursion. This could be backward-incompatible for users who have an alias named "yazi" and expect this shell wrapper to call that alias instead of the yazi executable directly.
Also defines the wrapper with `programs.fish.functions` instead of `interactiveShellInit`, which seems to be the preferred way.
```
```
@XYenon @eljamm

yazi: improve fish integration

---

modules/programs/ghostty.nix

Adds some keybinds to the example for programs.ghostty.settings. Should make it more obvious to users how to define them since Nix doesn't allow duplicate keys.
```
```
@HeitorAugustoLN

ghostty: add keybinds to settings example

---

modules/programs/nh.nix

`nh.clean.enable = true;` on my home-manager standalone installation gave me two evaluation errors.
First because osConfig is `null` which breaks the warning (for when GC is enabled both in nh and in NixOS configuration).
Then because `config.nix.package` can't be added to the nh-clean systemd service if evaluates to `null` (which is the default value).
After testing I found that nix doesn't need to be on path for nh to run so I removed the addition to path. 
I actually found a few problems with the systemd service. 
* `exec` is not found when I run it (bash built-in)
* I don't think `$PATH` would evaluate in a unit file like this
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information …

nh: fix conditional for warning (when osConfig is null) and remove potential null variable config.nix.package

---

.github/PULL_REQUEST_TEMPLATE.md
docs/manual/contributing/tests.md
docs/release-notes/rl-2505.md
flake.nix
tests/flake.nix
tests/modules/programs/neovim/plugin-config.nix

Having the tests available in the main Nix Flake introduces unnecessary evaluation for non-developer users and, worse, a dependency on the nmt library.
Fixes #6354
```
```

home-manager: move tests into new test flake

---

modules/programs/himalaya.nix
tests/modules/programs/himalaya/basic-expected.toml

This PR make the home manager module compatible with Himalaya CLI `v1.x.x`. It also removes the watcher, as watching is not part of Himalaya anymore (see https://github.com/nix-community/home-manager/pull/5297#issuecomment-2567375413).
```
```

himalaya: update for `v1`

---

modules/programs/firefox/mkFirefoxModule.nix
tests/modules/programs/firefox/common.nix
tests/modules/programs/firefox/final-package.nix

When `cfg.package` is already wrapped, and wrapped without the `ExtensionSettings` key set, this would always add that key, even if its value was blank. This would result in `cfg.finalPackage` being a functionally-identical, but differently-input-addressed package. This is generally undesirable as it may result in multiple derivations being built, and also if the value of `cfg.package` is expected to be unchanged by the user (e.g. because they want it to be consistent between NixOS and HM configuration).
Add a test to ensure this does not regress in the default case. Only test on newish stateVersion since the logic for `isWrapped` differs on older versions.
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-styl …

firefox: Avoid unnecessarily overriding package

---

modules/services/window-managers/hyprland.nix

Adds integration with the `xdg.portal` options. Adds the `portalPackage` option, used to change the `xdg-desktop-portal-hyprland` package.
```
```
@khaneliman @rycee

hyprland: add xdg.portal configuration

---

modules/services/cliphist.nix
tests/modules/services/cliphist/cliphist-multiple-session-targets.nix
tests/modules/services/cliphist/default.nix

Using a space separated list of targets as a single string element in the list doesn't work properly. Change property to support list of targets and backwards compatibility with warning for single string.
```
```

cliphist: support multiple systemdTargets properly

---

modules/programs/ghostty.nix

Currently nixpkgs does not contain a package definition for ghostty compatible with Darwin. Darwin users may still want to use this module to manage their config or share config between systems. This carries over behaviour from the beta period where this same technique was used.
see: https://github.com/clo4/ghostty-hm-module/blob/887e13a6e7acf5ffaab0119d96e476d84db90904/module.nix#L167-L173
Also improves validation to cover theme files.
Requested via ghostty discord. Testing included building against a local copy of nixpkgs with the ghostty package deleted and marked as broken.
cc @HeitorAugustoLN 
closes #6295

ghostty: allow darwin users to manager their config

---

modules/lib/maintainers.nix
modules/misc/news.nix
modules/modules.nix
modules/programs/aerospace.nix
tests/default.nix
tests/modules/programs/aerospace/aerospace.nix
tests/modules/programs/aerospace/default.nix
tests/modules/programs/aerospace/settings-expected.toml

aerospace: add module

---

modules/programs/thunderbird.nix
tests/modules/programs/thunderbird/thunderbird.nix

This change allows to enable native hosts modules for Thunderbird, similar to Firefox. For reference, [this](https://github.com/booxter/nix/blob/85096699428b0c8e849dfa2992b9e02895360012/modules/home-manager/modules/thunderbird.nix#L5) is how it looks like in nix config.
```
```
@d-dervishi @jkarlson

thunderbird: add native host support

---

modules/programs/atuin.nix

With atuin 18.4.0, it looks for the socket file in `XDG_RUNTIME_DIR` by default. But the launchd daemon we run doesn't have access to that variable, so it is created at the default `socket_path` which is `XDG_DATA_HOME/atuin`.
To fix this, we provide a default value for the socket path which is `XDG_DATA_HOME/atuin/daemon.sock`
```
```
@hawkw @water-sucks

Fix atuin daemon on darwin

---

modules/programs/thunderbird.nix
tests/modules/programs/thunderbird/thunderbird.nix

This reverts commit 608b26d16ee69384580b1b14ac947d81d0240beb.
Forgot to test with my config before merging... looks like we have 2 modules trying to write to the same location with different options. Reverting to fix the conflict, we can re-implement it. 
```
```

Revert "thunderbird: add native host support (#6292)"

---

modules/programs/waybar.nix

This allows making the systemd user unit appear without it autostarting, which is useful if you want to start it manually from a specific display manager config only.
```
```
@berbiche

waybar: allow setting systemd.target to null

---

modules/programs/waybar.nix

This is undocumented, but this allows showing the bar above all windows, including fullscreen ones.
```
```
@berbiche

waybar: allow setting layer to overlay

---

modules/services/window-managers/hyprland.nix

Makes `wayland.windowManager.hyprland.package` nullable.
Should xwayland still be installed, if the package is null?
```
```
@fufexan

hyprland: make package nullable

---

modules/misc/xdg-autostart.nix
modules/modules.nix
tests/modules/misc/xdg/autostart.nix
tests/modules/misc/xdg/default.nix

This module allows creating autostart entries using Home Manager.
```
```

xdg-autostart: add module

---

default.nix
flake.nix

Without this fix a `nix-buid . -A home-manager` would successfully
create a `home-manager`. And one could use the included binary until
the next garbage collection, after that it would fail with an
error that it can not find the `home-manager` sources.
Similarily a `nix-copy-closure`d `home-manager` would fail with the
same error on the copies target machine.
This problem existed on both, the flake as well as the non-flake build
of `home-manager`.
```
```
@rycee

home-manger: fix runtime closure

---

modules/lib/maintainers.nix
modules/misc/news.nix
modules/modules.nix
modules/services/linux-wallpaperengine.nix
tests/default.nix
tests/modules/services/linux-wallpaperengine/basic-configuration-expected.service
tests/modules/services/linux-wallpaperengine/basic-configuration.nix
tests/modules/services/linux-wallpaperengine/default.nix

Adds the `linux-wallpaperengine` systemd service.
The original project is here: https://github.com/Almamu/linux-wallpaperengine.
It simply converts options into command-line arguments and provides a systemd service to run `linux-wallpaperengine` in the background.
```
```

linux-wallpaperengine: add module

---

docs/manual/nix-flakes.md
docs/manual/nix-flakes/flake-parts.md
flake-module.nix
flake.nix

Add a [flake-parts](https://flake.parts) module, output as `flakeModules.home-manager` and `flakeModules.default`.
The module defines options for `flake.homeModules` and `flake.homeConfigurations`, based on the respective nixos equivalents; [`flake.nixosModules`](https://github.com/hercules-ci/flake-parts/blob/9126214d0a59633752a136528f5f3b9aa8565b7d/modules/nixosModules.nix) and [`flake.nixosConfigurations`](https://github.com/hercules-ci/flake-parts/blob/9126214d0a59633752a136528f5f3b9aa8565b7d/modules/nixosConfigurations.nix).
This is mostly useful for people who want to define modules or configs in multiple flake modules. Without the options, they can still be defined, but the definition must be unique.
I've added some initial documentation, although I don't know how to build/browse …

Add flake-parts module

---

modules/programs/bat.nix
modules/programs/btop.nix
modules/programs/direnv.nix
modules/programs/fastfetch.nix
modules/programs/fzf.nix
modules/programs/ghostty.nix
modules/programs/git.nix
modules/programs/kitty.nix
modules/programs/lazygit.nix
modules/programs/neovim.nix
modules/programs/nix-index.nix
modules/programs/ripgrep.nix
modules/programs/waybar.nix
modules/programs/wezterm.nix
modules/programs/yazi.nix
modules/services/cliphist.nix
modules/services/swaync.nix

Adding myself to modules I'm using and would like to maintain. 
```
```

treewide: add khaneliman maintainer 

---

docs/manual/nix-flakes/flake-parts.md
flake-module.nix

The naming was quite confused in #5229.
```
```

flake-module: fix naming

---

tests/modules/services/window-managers/bspwm/bspwm-stubs.nix
tests/modules/services/window-managers/bspwm/configuration.nix
tests/modules/services/window-managers/herbstluftwm/herbstluftwm-no-tags.nix
tests/modules/services/window-managers/herbstluftwm/herbstluftwm-simple-config.nix
tests/modules/services/window-managers/herbstluftwm/herbstluftwm-stubs.nix
tests/modules/services/window-managers/hyprland/hyprland-stubs.nix
tests/modules/services/window-managers/hyprland/inconsistent-config.nix
tests/modules/services/window-managers/hyprland/multiple-devices-config.nix
tests/modules/services/window-managers/hyprland/null-all-packages-config.nix
tests/modules/services/window-managers/hyprland/null-package-config.nix
tests/modules/services/window-managers/hyprland/null-portal-package-config.nix
tests/modules/services/window-managers/hyprland/simple-config.nix
tests/modules/services/window-managers/hyprland/sourceFirst-false-config.nix
tests/modules/services/window-managers/i3/i3-stubs.nix
tests/modules/services/window-managers/river/configuration.nix
tests/modules/services/window-managers/river/river-stubs.nix
tests/modules/services/window-managers/spectrwm/spectrwm-simple-config.nix
tests/modules/services/window-managers/spectrwm/spectrwm-stubs.nix
tests/modules/services/window-managers/sway/sway-stubs.nix
tests/modules/services/window-managers/wayfire/configuration.nix
tests/modules/services/window-managers/wayfire/wayfire-stubs.nix
tests/modules/services/window-managers/wayfire/wf-shell.nix

Reduces closures from 500 -> 357 MB for most of them, Hyprland is a larger one of 1.2 GB -> 357 MB.
```
```

window-managers: reduce closure sizes

---

modules/i18n/input-method/fcitx5.nix
tests/modules/i18n/input-method/fcitx5-configuration.nix

Fixes: https://github.com/nix-community/home-manager/issues/5264
This patch adds new option to the fcitx5, which allows to specify that user wishes to use it with wayland, so environment variables which are necessary for the X11, should not be automatically set.
The same change was already made for the nixos repo: https://github.com/NixOS/nixpkgs/pull/278765
I've confirmed on my machine, that with this change, fctix5 no longer sets  "GTK_IM_MODULE" and "QT_IM_MODULE" environment variables.
```
```

fcitx5: add waylandFrontend option to not set env vars

---

modules/lib/maintainers.nix
modules/misc/news.nix
modules/modules.nix
modules/programs/lapce.nix
tests/default.nix
tests/modules/programs/lapce/default.nix
tests/modules/programs/lapce/example-keymaps-expected.toml
tests/modules/programs/lapce/example-keymaps.nix
tests/modules/programs/lapce/example-settings-expected.toml
tests/modules/programs/lapce/example-settings.nix

Adds the 'programs.lapce' module for configuring lapce text editor.
Options for settings, plugins and keymaps are available. Idea #4541
Using the module would look something like this:
```
...
programs.lapce = {
enable = true;
package = pkgs.lapce;
settings = {
core = {
custom-titlebar = false;
color-theme = "Custom";
icon-theme = "Material Icons";
};
editor = {
font-family = "FiraCode Nerd Bold Font, monospace";
font-size = 22;
tab-width = 2;
cursor-surrounding-lines = 4;
render-whitespace = "all";
bracket-pair-colorization = true;
highlight-matching-brackets = true;
};
ui = {
font-size = 20;
open-editors-visible = false;
};
nushell-lsp = {
path = "${pkgs.nushell}/bin/nu";
args = [ "--lsp" ];
};
lapce-nix.lsp-path = "${pkgs.nil}/bin/nil";
};
plugins = [
{
author = "timon-schelling";
name …
```

lapce: add module

---

modules/programs/git.nix

Right now, if other signing options are defined without `key` specified, home-manager switch will fail.
```
```
@rycee

git: add default value null to programs.git.signing.key

---

modules/programs/yazi.nix

Yazi is deprecating init.lua for main.lua usages. This adds support for main.lua in plugins.
Closes https://github.com/nix-community/home-manager/issues/6393
```
```
@eljamm @XYenon

yazi: add main.lua support to plugins

---

docs/manual/nix-flakes/flake-parts.md
flake-module.nix

Renamed flake.homeModules to flake.homeManagerModules. It is the most common way to define home-manager modules in a nix flake.
```
```

flake-module: rename `homeModules` to `homeManagerModules`

---

modules/programs/mpv.nix
tests/modules/programs/mpv/mpv-example-settings-expected-config
tests/modules/programs/mpv/mpv-example-settings.nix

to allow mixing imperative and declarative config
```
```

mpv: support includes directives

---

default.nix
flake.nix
lib/default.nix

This patch moves the lib functionality from the flake into a file and imports in both the `flake.nix` and `default.nix` which makes it accessible for non-flake users.
```
```

home-manager: add lib support for non-flake users

---

modules/services/gpg-agent.nix

This is a pretty common configuration option, and one that many people
will find useful to discover, specially if they're not using a desktop
environment.
I thought I would add it. It is also useful to have for
`pass-secret-service` in the future, since you'd likely want to avoid DE
keyrings.
Signed-off-by: Christina Sørensen <ces@fem.gg>
```
```
@rycee

gpg-agent: no-allow-external-cache option

---

modules/programs/firefox/mkFirefoxModule.nix

Within the context of the profiles submodule, `${name}` refers to the profile name, and not the firefox fork name.
This fixes all descriptions to use `${cfg.name}` instead (even where it's not necessary, for consistency).
```
```
@brckd @rycee

firefox: fix referencing firefox fork name in profile-specific docs

---

modules/programs/bash.nix
tests/modules/programs/bash/bash-history-control-with-file.nix
tests/modules/programs/bash/default.nix

-------
If HISTFILE's directory doesn't exist, bash history doesn't work. This PR fixes this.
```
```

bash: Make sure HISTFILE's directory exists

---

modules/services/window-managers/hyprland.nix
modules/services/window-managers/i3-sway/sway.nix
modules/services/window-managers/river.nix
modules/services/window-managers/wayfire.nix
modules/wayland.nix
modules/xsession.nix

As it current stands, the tray target is only created if xsession is
enabled. This causes services that depend on it to fail on wayland
sessions on configurations that do not have `services.xsession.enable =
true;` or the workaround as the following:
```nix
{config, lib, ...}: {
systemd.user.targets.tray = lib.mkIf (!config.xsession.enable) {
Unit = {
Description = "Home Manager System Tray";
Requires = [ "graphical-session-pre.target" ];
};
};
}
```
This PR addresses [#6329](https://github.com/nix-community/home-manager/issues/6329) and
[#2064](https://github.com/nix-community/home-manager/issues/2064),
albeit I do not think it is the greatest solution, since it allows the
targets defined by the xsession and wayland modules to be kept out of
sync.
I'd recommend defining `tray.target` …

wayland: create tray.target if xsession is not enabled

---

modules/modules.nix
modules/programs/tealdeer.nix
modules/services/tldr-update.nix
tests/default.nix
tests/modules/services/tldr-update/default.nix
tests/modules/services/tldr-update/tldr-update.nix
tests/modules/services/tldr-update/tldr-update.service
tests/modules/services/tldr-update/tldr-update.timer

This PR adds a simple systemd timer to automatically run `tldr --update`
```
```
CC @pedorich-n (maintainer of tealdeer module)

tldr-update: init

---

flake-module.nix

chasing up on my comments on https://github.com/nix-community/home-manager/pull/5229#discussion_r1941882290
```
```

flake-module: change type from lazyAttrsOf raw to lazyAttrsOf deferredModule

---

modules/lib/maintainers.nix
modules/services/ludusavi.nix

This adds a module for Ludusavi, that runs it daily with a systemd service, and allows you to configure it using Nix.
```
```

ludusavi: create Ludusavi module

---

modules/programs/neomutt.nix

https://github.com/nix-community/home-manager/pull/1885  changed 'map' from a string to a list of string but the default wasn't updated accordingly. When not defining map, you would get the warning `evaluation warning: teto profile: Specifying 'programs.neomutt.(binds|macros).map' as a string is deprecated, use a list of strings instead. See `.
```
```

neomutt: fix default for 'map' in macros/binds

---

modules/programs/eww.nix
tests/default.nix
tests/modules/programs/eww/basic-config.nix
tests/modules/programs/eww/config-dir/eww.scss
tests/modules/programs/eww/config-dir/eww.yuck
tests/modules/programs/eww/default.nix
tests/modules/programs/eww/null-config.nix

The eww module does not evaluate because of a missing attribute `types.isNull` being used for the `confDir` option config.
I have replaced `!types.isNull` with `!= null` to fix this error.
I also added a test, as tests were missing.
Issue: #6435 
```
```
@mainrs

eww: fix confDir using missing attribute "types.isNull" and add test

---

modules/programs/zellij.nix

zellij: `programs.zellij.settings` are serialized as kdl and not yaml from version 0.32.0 onwards

---

modules/programs/aerospace.nix
tests/modules/programs/aerospace/settings-expected.toml

with the default to `{}`, this TOML table is always set in the generated config. this change allows `null` for
`workspace-to-monitor-force-assignment` and sets the default to `null`.
```
```

aerospace: fix workspace assignment config

---

modules/programs/bash.nix

I assume it's not necessary to extend the tests for this change, right?
I would like to not have HISTFILESIZE and HISTSIZE set in the generated .bashrc 
```
```
@rycee

bash: Make HISTFILESIZE and HISTSIZE nullable

---

modules/services/syncthing.nix

Currently, all references are hardcoded even though we offer package options. Update to use package options.
Closes https://github.com/nix-community/home-manager/issues/6426
```
```

syncthing: use package options

---

nixos/common.nix

This prevents problematic references to `nix.package` when Nix management is disabled in the host OS.
Drafted until the corresponding `nix.enable` functionality is merged into nix-darwin, since this is probably more useful there than on NixOS.
---
**Note:** This work was funded by Determinate Systems. The design is my own.
```
```
@rycee

nixos/common: forward `nix.enable` from the OS configuration

---

modules/modules.nix
modules/services/yubikey-agent.nix
tests/default.nix
tests/modules/services/yubikey-agent-darwin/default.nix
tests/modules/services/yubikey-agent-darwin/service.nix
tests/modules/services/yubikey-agent/default.nix
tests/modules/services/yubikey-agent/service.nix

[yubikey-agent](https://github.com/FiloSottile/yubikey-agent) socket-activated service module for Linux & Darwin - works nicely on both :)
```
```

yubikey-agent: init service module

---

modules/programs/vscode.nix

`windsurf` was added to `nixpkgs` recently. It is a drop-in replacement for VSCode. These directories are the defaults for config and extensions.

vscode: add windsurf directories

---

nixos/common.nix

Backport of https://github.com/nix-community/home-manager/pull/6383.
or `nix build --reference-lock-file flake.lock ./tests#test-all` using Flakes. *(failed in `user-defaults` test due to escaping changes but seems unrelated)*
```
```
@rycee

[24.11] nixos/common: forward `nix.enable` from the OS configuration

---

modules/programs/git.nix

Original change was created before 24.11 release. We are in 25.05 now.
Follow up to https://github.com/nix-community/home-manager/pull/5516
```
```

git: change stateVersion check for compatiblity

---

modules/services/syncthing.nix

This PRs extends the recently merged PR #5616, which expanded the Synching config to allow declarative settings under Linux, such that it also works under Darwin.
To simplify the review process, I left split the PR into several commits for now:
* The first five commits perform some minor refactoring tasks of the module code such that parts of it can be reused in the Darwin specific changes.
* Commit six implements the actual Darwin specific changes. It does the following:
* Update the module's `syncthing` launchd agent to copy the synching key/certificate before starting syncthing, analogously to the systemd service from the above mentioned PR #5616.
* Adds an `syncthing-init`launchd agent (analogously to the systemd service `synching-init` from the above mentioned PR #5616) that updates …

syncthing: expand declarative config to Darwin

---

modules/misc/nixpkgs-disabled.nix

When `useGlobalPkgs` is enabled, setting `nixpkgs.config` and `nixpkgs.overlays` in the home config has no effect. There is an assertion in place intended to throw an error if the user tries to set these options in this scenario, but it uses an OR instead of an AND, allowing for _one_ of them to be set. This PR replaces this OR for an AND.
Fixes #6079.
```
```
@thiagokokada

Fix assertion that `config.nixpkgs` cannot be set if `useGlobalPkgs` is enabled

---

modules/programs/floorp.nix
modules/programs/librewolf.nix

The path for messaging hosts seems to have been
~/.mozilla/native-messaging-hosts/ all along.
This PR fixes that
Solves #5190
```
```
@bricked

firefox: correct vendorPath of firefox forks

---

flake-module.nix

This should *help* prevent bad imports.
Made after the discussion in https://github.com/nix-community/home-manager/pull/6392.
```
```

flake-module: set _class

---

nixos/common.nix

This was resolving to `lib.options.nix.enable.visible or true`, which is always `true`, and therefore using `nix.enable` where it shouldn’t be used. Oops…
```
```
@rycee @khaneliman

nixos/common: fix `options` reference

---

modules/misc/nixpkgs-disabled.nix

Temporarily fixes backwards compatibility as issued in #6172.
```
```
@thiagokokada @justDeeevin

nixpkgs-disabled: warn instead of assert

---

nixos/common.nix

Backport of https://github.com/nix-community/home-manager/pull/6473.
```
```
@rycee @khaneliman

[24.11] nixos/common: fix `options` reference

---

modules/programs/mpv.nix

Closes https://github.com/nix-community/home-manager/issues/6234
wrapMpv doesn't exist anymore for a while.
```
```

mpv: drop old wrapMpv compatibility

---

modules/programs/git.nix
tests/modules/programs/gh/credential-helper.git.conf
tests/modules/programs/git/default.nix
tests/modules/programs/git/git-with-email-expected.conf
tests/modules/programs/git/git-with-email.nix
tests/modules/programs/git/git-with-msmtp-expected.conf
tests/modules/programs/git/git-with-str-extra-config-expected.conf
tests/modules/programs/git/git-without-signing.conf
tests/modules/programs/git/git-without-signing.nix

Closes https://github.com/nix-community/home-manager/issues/6472
```
```

git: support not configuring signing.format

---

modules/programs/nh.nix

A valid flakespec is not necessarily a valid path
Related to #6325
```
```
@JohnRTitor

nh: change flake option type to singleLineStr

---

modules/programs/nh.nix

Cherry picked @pedorich-n's #6325 to get address:
- Remove flake path assertion
- Add warning when HM's `nix.gc.automatic` is enabled
That I missed in my PR (#6350), as per @Weathercold's suggestion.
- ~Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).~
```
```
- ~Added myself as module maintainer. See …

 nh: fixes and addition to warnings/assertions

---

modules/programs/git.nix

With the following config:
```
programs.git = {
enable = true;
signing = {
format = "ssh";
key = "~/.ssh/id_ed25519";
signByDefault = true;
};
userName = fullName;
userEmail = userEmail;
};
```
on stateVersion 25.05, you get the following error:
```
The option `home-manager.users.timo.programs.git.signing.format` is defined both null and not null, in `/nix/store/ip7y1cxy95vwscjy8ll86m5ls9i5kiad-source/modules/programs/git.nix' and `<unknown-file>'.
```
This PR fixes this by using `setOptionDefault` instead of just setting it to `null`
**Workaround**
Use `lib.mkForce` when setting the format in your config.
```
```
See …

git: fix setting format on >=25.05

---

modules/services/mako.nix

Add `max-history` option for mako
- If someone add `max-history` to extraConfig, then mako doesn't work because cannot parse the config, so this case can be ignored
```
```
@onny

mako: add max-history option

---

modules/programs/mise.nix
tests/modules/programs/mise/default.nix
tests/modules/programs/mise/nushell-integration.nix

Enable `nushell` [integration](https://mise.jdx.dev/installing-mise.html#nushell) for `mise`.
```
```

mise: enable nushell integration

---

flake.nix

Since the `imports` attributes of modules allows for paths we can remove the `import` making the consumption of nixosModules, darwinModules and flakeModules cheaper
I'm currently on darwin, so i'm unable to run the tests. :p
```
```

flake: don't import modules

---

flake.nix

Multiple stable releases removed from inception. Don't need to keep it around anymore.
https://nixos.org/blog/announcements/2022/nix-280/
```
```

flake.nix: remove deprecations

---

modules/programs/firefox/mkFirefoxModule.nix

Prevents extensions settings from accidentally being overriden when using `profiles.<name>.extensions.settings`. Adds the `profiles.<name>.extensions.force` option to acknowledge the risk. See https://github.com/nix-community/home-manager/pull/6389#issuecomment-2666634695.
```
```
@khaneliman @rycee @brckd

firefox: prevent extensions settings override

---

tests/default.nix
tests/modules/config/home-cursor/default.nix
tests/modules/config/home-cursor/expected-index.theme

Working on module and needed test to verify expected behavior.
Created to aid in confidence with #6492
```
```

tests/home-cursor: init

---

flake-module.nix

ops typo 😓  https://github.com/nix-community/home-manager/pull/6408#issuecomment-2671424776
```
```

flake-module: use raw for homeConfgurations and deferredModule for modules

---

modules/misc/mozilla-messaging-hosts.nix
modules/modules.nix
modules/programs/firefox/mkFirefoxModule.nix
modules/programs/thunderbird.nix
tests/modules/programs/firefox/common.nix
tests/modules/programs/firefox/null-package.nix
tests/modules/programs/thunderbird/default.nix
tests/modules/programs/thunderbird/thunderbird-native-messaging-host.nix
tests/modules/programs/thunderbird/thunderbird-with-firefox.nix
tests/modules/programs/thunderbird/thunderbird.nix

- **Reapply "thunderbird: add native host support (#6292)" (#6371)**
- **thunderbird, firefox: fix file conflict for native messaging hosts**
This is the second attempt to implement native messaging hosts for Thunderbird.
The previous attempt was reverted because it broke activation when both Firefox
and Thunderbird were installed. This happened because on Linux, both
applications use the same directory for native messaging hosts, and the module
did not handle this case correctly.
Note: I've added maintainers of the Firefox module to maintainers for the new
helper module since this is a relocated code that is now a dependency for the
main Firefox module.
```
```
See …

thunderbird: support native messaging hosts (2nd attempt)

---

modules/misc/news.nix
modules/modules.nix
modules/programs/swayimg.nix
tests/default.nix
tests/modules/programs/swayimg/default.nix
tests/modules/programs/swayimg/empty-settings.nix
tests/modules/programs/swayimg/example-settings-expected.ini
tests/modules/programs/swayimg/example-settings.nix

Added a module for [swayimg](https://github.com/artemsen/swayimg) and the ability to generate the `swayimgrc` (just called `config` on disk) file using hm.
Swayimg description (taken from their README): 
> Fully customizable and lightweight image viewer for Wayland based display servers.
```
```

swayimg: add module

---

modules/config/home-cursor.nix

Not sure if it should use `*` or `seat0` for the configuration, as I'm not sure what the difference in semantics would be.
```
```
@Scrumplex @alexarice @sumnerevans @oxalica @league

home-cursor: add sway support

---

modules/programs/jetbrains-remote.nix

If you use `programs.jetbrains-remote` for the first time, `rm` will fail, as there are nothing to delete yet. I've tested this on my machine and it fixed an issue with the module
<details>
<summary>There is an issue with other module when running tests the easy way</summary>
</details>
```
```
@GenericNerdyUsername

Fix jetbrains-remote - do not fail if files do not exist yet

---

modules/i18n/input-method/fcitx5.nix

Make fcitx5-daemon boot after `graphical-session.target`, fixed fcitx5 not working on WM by default.
```
```
@Kranzes @rycee

fcitx5: make boot after graphical session

---

modules/misc/news.nix
modules/modules.nix
modules/services/wluma.nix

Adds a module for wluma, a service for automatic screen brightness adjustment.
There was also #5811, which was closed for no obvious reason. I've taken that as a basis and applied some minor changes on top of it.
Related: #2420 #5811
```
```

wluma: init module

---

modules/services/psd.nix

*Recreated from #5558 due to stuck pipeline and no activity.*
This change adds configurable options to psd and creates the corresponding config file, it also adds missing packages to the envPath. 
Previously the config file would not be automatically created, which broke psd and made it not function like it should.
I added config options that I think are relevant. I deliberately left out options like `USE_OVERLAYFS` and `USE_SUSPSYNC` as they have additional dependencies that would need to have assertions to check if they are met.
Closes #5454 
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) …

psd: add missing module config options

---

modules/accounts/email.nix
modules/programs/mu.nix
modules/programs/notmuch.nix
modules/programs/thunderbird.nix

Provide options for setting `realName` in `accounts.email.accounts.*.aliases`.
```
```
@d-dervishi

accounts/email: provide realName option for alias

---

modules/services/imapnotify-accounts.nix
modules/services/imapnotify.nix
tests/modules/services/imapnotify/imapnotify.nix
tests/modules/services/imapnotify/imapnotify.service

`wait` is no longer a part of the goimapnotify's config, but one of its
cli options.
```
```
@nickhu

imapnotify: add `wait` option to imapnotify-accounts

---

modules/misc/news.nix
modules/modules.nix
modules/programs/jqp.nix
tests/default.nix
tests/modules/programs/jqp/basic-configuration.nix
tests/modules/programs/jqp/basic-configuration.yaml
tests/modules/programs/jqp/default.nix

I added `jqp` module with the ability to set the `jqp` configuratin within nix. I have tested the module and it creates the `~/.jqp.yaml` file with the nix config settings
```
```
I added a test case based on the Polybar example mentioned above but still couldn't manage to get the test working after half a day. I only found in the Home Manager manual how to run them. Is there any documentation available on how to write these tests with comments?

jqp: add module

---

modules/programs/firefox/mkFirefoxModule.nix

Add a new option `programs.firefox.pkcs11Modules` to add PKCS11 modules to firefox directly.
```
```

firefox: Allow to add PKCS11 modules

---

modules/programs/htop.nix

As of https://github.com/htop-dev/htop/commit/5e8fc97a96dd2dea1aad8c6c4f2e872aede38ead, htop creates a new config file and renames it over home-manager's symlink. This PR works around this by moving the whole $XDG_CONFIG_HOME/htop directory into the nix store, preventing such overwrites.
```
```
@bjpbakker

htop: write-protect entire configuration directory

---

modules/targets/darwin/linkapps.nix

Not all packages supply a bundled macOS application, and I would like to configure where apps get placed since I use Raycast instead of Spotlight.
```
```
@midchildan

targets/darwin: allow configuring application linking

---

tests/default.nix
tests/modules/programs/firefox/default.nix
tests/modules/programs/firefox/librewolf.nix
tests/modules/programs/firefox/multiple-derivatives.nix

The issue itself was resolved with:
https://github.com/nix-community/home-manager/pull/6460
This patch only adds a test case to make sure we don't ever regress by
installing firefox and librewolf and floorp at the same time.
Closes: #6467
```
```

tests: check that all firefox derivatives can be installed

---

modules/programs/chromium.nix

Should only be generating when provided
Closes https://github.com/nix-community/home-manager/issues/6514
```
```

chromium: optional nativeMessagingHosts

---

modules/programs/waybar.nix

Support for passing `GTK_DEBUG` in the service to enable inspect
```
```
@berbiche

waybar: support enable inspect from service

---

tests/modules/services/mpd/basic-configuration.service
tests/modules/services/mpd/start-when-needed.service
tests/modules/services/swayidle/basic-configuration.nix

Apparently, bash was changed to bashInteractive by default https://github.com/NixOS/nixpkgs/pull/379368
Updating tests to reflect change to unblock CI. 
```
```

tests: bash -> bash-interactive

---

tests/modules/programs/neovim/plugin-config.nix

```
Assigning a plain list to extraLuaPackages is deprecated.
Please assign a function taking a package set
as argument, so
extraLuaPackages = [ pkgs.lua51Packages.xxx
];
should become
extraLuaPackages = ps: [ ps.xxx ];
```
```
```

tests/neovim: resolve deprecation

---

modules/misc/xdg.nix

Some programs (e.g: `less`) will not make use of `$XDG_STATE_HOME` if the directory does not exist (even if the variable is set).
```
```
@rycee @teto (no `meta.maintainers`)

xdg: create '$XDG_STATE_HOME'

---

modules/programs/firefox.nix
modules/programs/firefox/mkFirefoxModule.nix
modules/programs/floorp.nix
modules/programs/librewolf.nix

This is a reaction to PR #6460
```
```
@booxter @khaneliman @brckd

firefox: deprecate vendorPath

---

modules/programs/tmux.nix

tmux: fix example in tmux.nix

---

modules/services/xidlehook.nix

Set `Restart=always` for `xidlehook` service.
```
```

xidlehook: set Restart=always

---

modules/services/screen-locker.nix
tests/modules/services/screen-locker/basic-configuration.nix

Set `Restart=always` for `xss-lock` and `xautolock` services. This is in line with NixOS counterparts.
```
```

screen-locker: set Restart=always for all services

---

modules/services/mpd.nix
tests/modules/services/mpd/basic-configuration.conf
tests/modules/services/mpd/xdg-music-dir.conf

-------
Make mpd service work on Darwin. This PR requires https://github.com/nix-community/home-manager/issues/6476 to be fixed before moving it forward.
```
```

mpd: Add support for darwin

---

modules/misc/xdg.nix

Add xdg.cacheFile to mimic configFile, dataFile, stateFile.
```
```
@rycee

xdg: add option 'xdg.cacheFile'

---

modules/programs/librewolf.nix

Removed an unnecessary Linux assertion. Although I don't understand why it was there in the first place, the module have never had anything Linux-specific.
```
```
@chayleaf @onny

librewolf: support darwin

---

modules/misc/xdg.nix
tests/default.nix
tests/modules/misc/xdg/default-locations.nix
tests/modules/misc/xdg/default.nix
tests/modules/misc/xdg/linux.nix
tests/modules/programs/k9s/empty-settings.nix
tests/modules/programs/k9s/example-settings.nix

XDG tweaks for fixing a legacy behavior found while testing on darwin. Pulling out of https://github.com/nix-community/home-manager/pull/6550 to get it into master quicker since that might be a longer process.. 
```
```

xdg: legacy fix and test tweaks

---

modules/programs/firefox/mkFirefoxModule.nix

Upated the mkFirefoxModule to respect user's global extension configuration force option
```
```
@rycee @brckd @HPsaucii

Firefox: Apply global extension force setting

---

modules/programs/git.nix
tests/modules/programs/git/git-with-msmtp-expected.conf
tests/modules/programs/git/git-with-msmtp.nix

In manpage of `git-send-email`,
> For backward compatibility, this option can also specify 
> full pathname of a sendmail-like program instead; the program
>  must support the -i option. This method does not support
> passing arguments or using plain command names. For those use
> cases, consider using --sendmail-cmd instead.
```
```

git: apply sendmailCmd instead of smtpServer

---

modules/programs/mbsync.nix

If the user's requested mail directory has spaces or other special shell characters, our activation script breaks. Use `escapeShellArg` to prevent issues by wrapping with single quotes if there are special characters.
Closes #6569.
Cannot run tests on my desktop.
```
$ nix build --reference-lock-file flake.lock ./tests#test-all
error: opening directory '/nix/store/dvck5q5lsir2b217w6d2l1rpqq9a0hbp-hm_fishcompletionstraefik.fish': Too many open files
```
```
$ nix-shell --pure tests -A run.all
...
error: 'vinegar' was removed due to being blocked by Roblox, rendering the package useless
```
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-co …

mbsync: Wrap final maildir path with single quotes to prevent escapes

---

modules/programs/vscode.nix

Support Cursor AI IDE as a VSCode family.
```
```

vscode: Support Cursor AI

---

modules/misc/specialisation.nix

The specialisation name is included in home.extraBuilderCommands without being properly escaped and checked. This commit fixes that.
The specialisation name is currently not escaped when included in the command to create the symlink in home.extraBuilderCommands. This PR properly escapes it and adds an assertion to ensure it does not contain a forward slash.
This PR, for example, prevents people from running commands through the specialisation name:
```nix
home-manager.users.tobor.specialisation."test && echo 'test' > $out/test.txt".configuration = { };
```
After rebuilding, the test.txt file is present in the built derivation:
```bash
❯ cat .local/state/home-manager/gcroots/current-home/test.txt
test
```
Note: specialisation.nix was probably implemented by copying how it works in nixpkgs, …

misc/specialisation: escape specialisation name

---

modules/programs/firefox/mkFirefoxModule.nix

A path may be preferred for some uses, and allowing it avoids the user needing to `builtins.readFile`, thus creating duplicates and making it more difficult to determine the actual store path.
```
```

firefox: Support paths for userChrome & userContent

---

tests/default.nix
tests/modules/programs/neovim/runtime.nix

tests/neovide: fix deprecation; tests: move vinegar to linux only

---

modules/programs/gh-dash.nix
tests/modules/programs/gh-dash/config.nix

Missing mkIf, update test to catch integration with `gh` properly. 
Resolves https://github.com/nix-community/home-manager/issues/6584
```
```

gh-dash: fix

---

modules/services/xembed-sni-proxy.nix

Use new `kdePackages` version by default. Users can pass the legacy package, if they wish.
Closes https://github.com/nix-community/home-manager/issues/6580
```
```

xembed-sni-proxy: change default package

---

docs/manual/nix-flakes/flake-parts.md
flake-module.nix

This reverts commit 066ba0c5cfddbc9e0dddaec73b1561ad38aa8abe.
Follow up to discussion https://github.com/nix-community/home-manager/pull/6392#issuecomment-2633445057 
```
```
@rycee @teto @MattSturgeon

flake-module: revert rename 

---

modules/programs/zsh.nix
tests/modules/programs/zsh/syntax-highlighting.nix

The current syntax of highlighting style is outdated and not working as well. So this pr aims to update it so follow `zsh-syntax-highlight` new syntax [example](https://github.com/zsh-users/zsh-syntax-highlighting/blob/e0165eaa730dd0fa321a6a6de74f092fe87630b0/highlighters/main/main-highlighter.zsh#L32). 
```
```
@rycee

zsh: correct syntax option to syntax-highlighting

---

modules/programs/navi.nix

When xdg is enabled, use the xdg config home on darwin.
Closes https://github.com/nix-community/home-manager/issues/6559
```
```

navi: handle xdg directory on darwin

---

modules/services/podman-linux/services.nix

podman: fix podman-user-wait-network-online

---

modules/config/home-cursor.nix
modules/home-environment.nix
modules/i18n/input-method/fcitx5.nix
modules/lib/shell.nix
modules/misc/debug.nix
modules/misc/qt.nix
modules/targets/generic-linux.nix
tests/modules/home-environment/default.nix
tests/modules/home-environment/session-path.nix
tests/modules/home-environment/session-search-variables.nix

This PR introduces `home.sessionSearchVariables` option, that is created to be a "generic" version of `home.sessionPath` for any environment variables that is similar to PATH (e.g.: MANPATH). This allows composition of those variables between multiple modules, avoiding issues like this one:
https://github.com/nix-community/home-manager/pull/4579/files#r1364374048
This PR also reimplements `home.sessionPath` as terms of `home.sessionSearchVariables`, to reduce code duplication and show that the code is correct, and migrates the `im/fcitx5` module to use it for `QT_PLUGIN_PATH`.
Replaces: https://github.com/nix-community/home-manager/pull/4582.
+ It is since this change the behavior from append to prepend in `PATH`, but the impact should be small.
or `nix build --reference-lock-file …

home-environment: add home.sessionSearchVariables, 2nd try

---

modules/misc/debug.nix

Fixup of daab32302b0bdd9bfff9e75d32375353d95b9c4f.
-------
NIX_DEBUG_INFO_DIRS is the wrong shape.
```
```

debug: make NIX_DEBUG_INFO_DIRS a list of strings

---

modules/home-environment.nix
tests/modules/home-environment/session-variables.nix

PR #6593 broke activation when `sessionVariablesExtra` is used, e.g.: `services.ssh-agent` because it concatenate the strings without a line break, so the resulting `hm-session-vars.sh` file became:
```bash
export XCURSOR_PATH="/etc/profiles/per-user/thiagoko/share/icons${XCURSOR_PATH:+:}$XCURSOR_PATH"if [ -z "$SSH_AUTH_SOCK" ]; then
export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent
fi
```
This commit fixes it by enforcing a line break between `sessionSearchVariables` and `sessionVariablesExtra`.
```
``` …

home-environment: add line-break after sessionSearchVariables

---

modules/programs/thunderbird.nix

When email account is gmail in thunderbird, set additional server settings.
As of March 2025, gmail only allows ssl/oauth0 authentication, so here I set the authMethod accordingly.
Also setting 'is_gmail' to true in thunderbird settings such that labels and trash work out of the box when the email account flavor is "gmail". This brings in the gmail configs for how it handles folders, labels, and archiving messages.
```
```

thunderbird: set additional gmail server settings

---

modules/programs/zoxide.nix

I updated my flake a few weeks back and `zoxide` has been giving me an error recently:
```
zoxide: detected a possible configuration issue.
Please ensure that zoxide is initialized right at the end of your shell configuration file (usually ~/.bashrc).
If the issue persists, consider filing an issue at:
https://github.com/ajeetdsouza/zoxide/issues
Disable this message by setting _ZO_DOCTOR=0.
```
To be fair, I haven't noticed any issues with `zoxide` apart from this error message.
The `zoxide` eval statement in my `.bashrc` is not "right at the end" of the file as mentioned in the message which isn't surprising given that it is given a `mkOrder 150`. In my own config, I increased this to `2000` (to ensure it comes after any `mkAfter`s which are `mkOrder 1500`) to ensure it happens at the …

`zoxide`: update `mkOrder` to place bash configuration at end of bashrc

---

modules/lib/maintainers.nix
modules/misc/news.nix
modules/modules.nix
modules/programs/mods.nix
tests/default.nix
tests/modules/programs/mods/basic-configuration.nix
tests/modules/programs/mods/basic-configuration.yml
tests/modules/programs/mods/default.nix

This change adds a module that configures [charmbracelet/mods](https://github.com/charmbracelet/mods)
```
```

mods: add a mods module

---

modules/misc/qt.nix

Follow up to #6493, sorry for my mistake 😓 
```
```
@rycee
@thiagokokada
@khaneliman

qt: add missing styleName for kde6

---

modules/programs/granted.nix

Without `$argv` the function will not pass any flags or arguments to the `assume.fish` script.  These are necessary to use assume to access the AWS console or use IAM role chaining.
Fixes issue raised in PR comments
https://github.com/nix-community/home-manager/pull/6549#issuecomment-2713885598
```
```
@wcarlsen

granted: fix fish shell integration

---

modules/services/screen-locker.nix
tests/modules/services/screen-locker/basic-configuration.nix
tests/modules/services/screen-locker/moved-options.nix

I use `xsecurelock` as a screen locker and it's mainly configurable through environment variables.
Instead of having to directly access the systemd service like this:
```nix
systemd.user.services.xss-lock.Service.Environment = "XSECURELOCK_PAM_SERVICE=xsecurelock";
```
I would like to add the environment through an option I called `lockCmdEnv`.
```
```
@jrobsonchase @rszamszur

screen-locker: add lockCmdEnv option

---

modules/programs/swaylock.nix

Currently, `path` values are not accepted as `programs.swaylock.settings` values:
```
error: A definition for option `home-manager.users.gaetan.programs.swaylock.settings.image' is not of type `boolean or floating point number or signed integer or string'.
```
This would allow for:
```nix
programs.swaylock = {
enable = true;
settings.image = ./wallpaper.png;
};
```
```
```
cc @rcerc

swaylock: accept path type for settings values

---

modules/config/home-cursor.nix
tests/modules/config/home-cursor/default.nix

Added the `.enable` pattern to `home.pointerCursor` for the selfish reason that is https://github.com/catppuccin/nix/blob/24dac16e6babd41961d985eef3dce6a30dab2e91/modules/home-manager/cursors.nix#L26-L27.
And made the `.icons` directory "toggleable" via `home.pointerCursor.doticons.enable`. Which in my opinion is easier than writing:
```nix 
{
lib,
config,
...
}:
{
home.file = lib.mkIf (config.home.pointerCursor != null) {
".icons/default/index.theme".enable = false;
".icons/${config.home.pointerCursor.name}".enable = false;
};
}
```
partially addresses https://github.com/nix-community/home-manager/issues/6268
And removing the top-level `with lib`
```
```
See …

home-cursor: modernize

---

modules/modules.nix
modules/services/macos-remap-keys/default.nix
modules/services/macos-remap-keys/keytables.nix
tests/default.nix
tests/modules/services/macos-remap-keys/basic-agent.plist
tests/modules/services/macos-remap-keys/basic-configuration.nix
tests/modules/services/macos-remap-keys/default.nix

A module to remap keys using macos native tool (hidutil)
```
```

macos-remap-keys: add

---

tests/default.nix
tests/modules/programs/zsh/zshrc-content-priorities.nix

Previous test didn't verify they were actually in correct order, updating test to check configuration is generated, as expected.
```
```

tests/zsh: fix zshrc content priority test

---

modules/services/syncthing.nix

closes https://github.com/nix-community/home-manager/issues/6620
```
```

synthing: fix synthing config being deleted on rebuild

---

modules/services/megasync.nix

Add a option for megasync to run on wayland.
```
```
@GaetanLepage

megasync: add option to enable wayland

---

modules/programs/kubecolor.nix
tests/modules/programs/kubecolor/default.nix
tests/modules/programs/kubecolor/does-have-openshift.nix
tests/modules/programs/kubecolor/does-not-have-openshift.nix

- Add a kubecolor alias for `oc`. See https://github.com/kubecolor/kubecolor/blob/main/README.md#whats-this
- Add an option `enableZshIntegration` which fixes ZSH completions for `kubectl` (and `oc`). See https://kubecolor.github.io/setup/shells/zsh/#completions 
```
```
@ajgon

Kubecolor oc alias and zsh completions

---

modules/programs/zsh.nix

Fix zsh `initContent` option example display error, see previous discussion: https://github.com/nix-community/home-manager/pull/6479#discussion_r1997554441
```
```
@teto

zsh: update zsh initContent example to use lib.literalExpression

---

modules/lib/maintainers.nix
modules/modules.nix
modules/services/swww.nix
tests/default.nix
tests/modules/services/swww/default.nix
tests/modules/services/swww/swww-graphical-session-target.nix
tests/modules/services/swww/swww-graphical-session-target.service

Adds services/swww.nix module to start swww-daemon with a systemd service.
```
```

swww: add swww service module for swww-daemon

---

docs/home-manager.1
home-manager/completion.bash
home-manager/completion.fish
home-manager/completion.zsh
home-manager/home-manager

You can now pass `--log-format FORMAT` to `nix-build`, useful for piping into `nix-output-monitor`.
Closes #6093.
```
```

home-manager: support passing `--log-format` to `nix-build`

---

modules/programs/firefox/mkFirefoxModule.nix
modules/programs/firefox/profiles/bookmarks.nix
tests/modules/programs/firefox/profiles/bookmarks/default.nix
tests/modules/programs/firefox/profiles/bookmarks/expected-bookmarks-user.js
tests/modules/programs/firefox/profiles/shared-path.nix

This splits the bookmarks submodule into a seperate file, to make it easier to maintain (like how the search module was previously split out in #5697).
This also refactors bookmarks to require a new `force` option, to be more explicit about overriding existing bookmarks.
```
```
@brckd @rycee

firefox: split bookmarks into separate submodule file

---

modules/lib/maintainers.nix
modules/modules.nix
modules/programs/rclone.nix
tests/integration/default.nix
tests/integration/standalone/rclone/default.nix
tests/integration/standalone/rclone/home.nix
tests/integration/standalone/rclone/no-secrets.conf
tests/integration/standalone/rclone/no-secrets.nix
tests/integration/standalone/rclone/with-secrets-in-store.conf
tests/integration/standalone/rclone/with-secrets-in-store.nix

Rclone is a command-line program to manage files on cloud storage, it also featrues support for FUSE mounts.
"Users call rclone *"The Swiss army knife of cloud storage"* and *"Technology indistinguishable from magic"*" - https://rclone.org/
This module manages the configuration of rclone remotes, including handling rclones secrets-in-config-ness, see #2703. 
Resolves #2703
```
```

rclone: add module

---

modules/services/podman-linux/containers.nix
tests/modules/services/podman-linux/container-expected.service
tests/modules/services/podman-linux/integration-container-bld-expected.service
tests/modules/services/podman-linux/integration-container-expected.service

Podman uses `systemd-run` to setup transient systemd timers, e.g. for healthchecks.
On systems where `systemd` is not present in `/run/current-system/sw/bin` or `~/.nix-profile/bin` (like one of my Ubuntu hosts), setting up the transient timers will fail. For containers with healthchecks configured, this results in the container being stuck in `starting` state.
Relevant issue here: https://github.com/containers/podman/issues/25034
This PR adds `systemd` to the quadlets service PATH in order for healthchecks to be setup correctly.
```
``` …

podman: include systemd in quadlet service path

---

modules/lib/maintainers.nix
modules/modules.nix
modules/programs/waylogout.nix

90% of the code is copied over from swaylock so thanks to the creator of that module!
```
```

waylogout: added configuration module

---

modules/misc/news.nix
modules/services/easyeffects.nix
tests/default.nix
tests/modules/services/easyeffects/default.nix
tests/modules/services/easyeffects/example-preset.json
tests/modules/services/easyeffects/example-preset.nix
tests/modules/services/easyeffects/service.nix

- added options to import presets
- added tests
- added hausken as maintainer
(tested with `nix-shell --pure tests -A run.easyeffects-service` and `nix-shell --pure tests -A run.easyeffects-example-preset`)
```
```
@fufexan

easyeffects: add option to import presets

---

modules/misc/news.nix
modules/modules.nix
modules/programs/tex-fmt.nix
tests/default.nix
tests/modules/programs/tex-fmt/custom-settings.nix
tests/modules/programs/tex-fmt/default-settings.nix
tests/modules/programs/tex-fmt/default.nix

tex-fmt is a LaTeX source code formatter written in Rust, and uses a user configuration file in the .toml format.
```
```

tex-fmt: add module

---

modules/services/megasync.nix

megasync: use getExe instead of getExe'

---

modules/programs/fish.nix
tests/modules/programs/fish/abbrs.nix

The fish shell has added a flag to the abbr command which allows one to expand it only if it is typed after a real command e.g.:
git s<Space> -> git status
s<Space> -> s
Also see the last example here: https://fishshell.com/docs/current/cmds/abbr.html#examples
Also every test ran fine, but one firefox related one, which doesn't seem to relate to my change.
```
```
@isabelroses

fish: add command option for abbreviations

---

modules/modules.nix
modules/services/librespot.nix

Librespot is a Spotify client. While there is already a module for spotifyd, which uses Librespot as a library, this adds one for the upstream frontend.
```
```

librespot: init module

---

tests/modules/programs/firefox/setup-firefox-mock-overlay.nix

Sometimes get errors related to this locally while running tests.
```
```

tests/firefox: add applicationName to mock

---

modules/lib/maintainers.nix
modules/modules.nix
modules/programs/onlyoffice.nix
tests/default.nix
tests/modules/programs/onlyoffice/default.nix
tests/modules/programs/onlyoffice/example-config.conf
tests/modules/programs/onlyoffice/example-config.nix

Added programs/onlyoffice.nix module, that provides `enable`, `package` and `settings` options at `programs.onlyoffice`.
All the available settings at `settings` can be deduced by modifing the config in the GUI and observing the changes in ~/.config/onlyoffice/DesktopEditors.conf.
```
```

onlyoffice: add module

---

docs/manual/installation/nixos.md

Added instructions for a different installation method for home manager on NixOS.
Excuse my removal of the other headings of the issue template, but they seemed arbitrary for a small code change)..

Added declarative installation instructions

---

modules/programs/mcfly.nix

mcfly-fzf's initialization steps don't properly check for interactive shells. It does check, but only after checking if mcfly has been initialized. Because mcfly does not initiate itself on non-interactive shells, that causes mcfly-fzf to return an exit code, breaking non-interactive shells.
Closes https://github.com/nix-community/home-manager/issues/6663
```
```
@trueNAHO @rycee @iofq

mcfly: fix mcfly-fzf in non-interactive shells

---

modules/programs/mcfly.nix

In #6669 I accidentally swapped the condition syntax for zsh and fish. When I fixed that, I just swapped the entire blocks. That caused the shells to be backwards though, so it is currently broken on master. Sorry! This PR fixes it.
```
```
@khaneliman

mcfly: Fix swapped shell names

---

modules/modules.nix
modules/services/hyprpolkitagent.nix
modules/services/lxqt-policykit-agent.nix
modules/services/polkit-gnome.nix
tests/default.nix
tests/modules/services/hyprpolkitagent/basic-configuration.nix
tests/modules/services/hyprpolkitagent/default.nix
tests/modules/services/lxqt-policykit-agent/basic-configuration.nix
tests/modules/services/lxqt-policykit-agent/default.nix
tests/modules/services/polkit-gnome/basic-configuration.nix
tests/modules/services/polkit-gnome/default.nix

Supersedes https://github.com/nix-community/home-manager/pull/5619
Resolves https://github.com/nix-community/home-manager/issues/3739
This adds polkit agent services for hyprland, gnome and lxqt. I have had the one from lxqt in my own configuration for a while and served me well, but recently wanted to check out other polkits and eventually switched to gnome's one.
I thought I'd add these to home-manager as well this time.
I was contemplating adding `security.polkit.agent = "gnome" or "hyprland" or "lxqt"`, but since there was no `security` directory I wasn't sure that was the right call for now and could be a future step.
All 3 of these tools do not have configuration(-files).
``` …
```

{hyprpolkitagent, lxqt-policykit-agent, polkit-gnome}: init modules

---

modules/modules.nix
modules/programs/iamb.nix

Add a new module for configuring iamb.
```
```

iamb: new module

---

modules/lib/maintainers.nix
modules/modules.nix
modules/programs/distrobox.nix
tests/default.nix
tests/modules/programs/distrobox/default.nix
tests/modules/programs/distrobox/example-config.ini
tests/modules/programs/distrobox/example-config.nix

Added programs/distrobox.nix module. It provides the option "programs.distrobox.containers", which makes it possible to declare a list of containers to be created. Since building those containers is not possible at build time (because none container backend is available at that time), I also added a Systemd Unit to build those containers after switching the configuration.
Ready to be merged!
```
```

distrobox: add module

---

modules/misc/xdg-mime.nix

[24.11 backport] xdg-mime: Fix cross compilation

---

modules/programs/rclone.nix
tests/integration/standalone/rclone/default.nix
tests/integration/standalone/rclone/no-type.nix
tests/integration/standalone/rclone/secrets-with-whitespace.conf
tests/integration/standalone/rclone/secrets-with-whitespace.nix

rclone: correctly escape whitespace in secrets + type check remote configs

---

modules/lib/maintainers.nix
modules/modules.nix
modules/services/davmail.nix
tests/default.nix
tests/modules/services/davmail/custom-settings.nix
tests/modules/services/davmail/default.nix
tests/modules/services/davmail/imitateOutlook.nix

Initialize a module for the [DavMail](https://davmail.sourceforge.net/) service.
The code is mostly copied from the corresponding NixOS module; but slightly refactored. In addition, some restrictions on the systemd service were released to allow DavMail to launch a GUI when necessary.
```
```

davmail: init module

---

modules/programs/firefox/mkFirefoxModule.nix
modules/programs/firefox/profiles/bookmark-types.nix
modules/programs/firefox/profiles/bookmarks.nix
tests/modules/programs/firefox/common.nix
tests/modules/programs/firefox/profiles/bookmarks/attrset.nix
tests/modules/programs/firefox/profiles/bookmarks/default.nix
tests/modules/programs/firefox/profiles/bookmarks/expected-bookmarks.html

The legacy attrset option type for `firefox.profiles.<name>.bookmarks` was accidentally removed in 9d55428. This adds back support for this type by refactoring the bookmarks submodule. This also adds a new test ensuring this won't happen again.
```
```
@kira-bruneau

firefox: fix bookmarks backwards compatibility

---

modules/programs/firefox/mkFirefoxModule.nix

Fixes https://github.com/danth/stylix/issues/1049. I missed replacing `profileName` -> `config.name` when refactoring profile-specific assertions in #6402 :melting_face:.
Thanks for tracking the issue to my commit @danth!
```
```
@brckd @khaneliman

firefox: fix assertion when missing force for extensions

---

tests/modules/programs/firefox/profiles/search/expected-migrate-search-v7.json

I'm not sure why this wasn't caught by the CI run in #6505, but this fixes one of the new tests I added in that PR so that it works for all firefox forks.
```
```
@brckd @khaneliman

firefox: fix migrate search v7 test for all firefox forks

---

modules/programs/firefox/mkFirefoxModule.nix

Continuing from #6670, this stops the migration warning from being shown if you didn't have any bookmarks set.
```
```
@khaneliman @brckd

firefox: don't show migration warning when bookmarks isn't set

---

modules/misc/news.nix
modules/programs/zellij.nix
tests/modules/programs/zellij/enable-shells.nix

Closes https://github.com/nix-community/home-manager/pull/6037
Follow up to discussion in https://github.com/nix-community/home-manager/pull/6358
Seems like interest was lost in that PR. Decisions made for restructuring from their approach:
- The environment variables mentioned, are only checked inside the `auto-start` scripts. It is also clearly described in their documentation. https://zellij.dev/documentation/integration.html
- https://github.com/search?q=repo%3Azellij-org%2Fzellij%20ZELLIJ_AUTO_ATTACH&type=code
- https://github.com/search?q=repo%3Azellij-org%2Fzellij+ZELLIJ_AUTO_EXIT&type=code
```
```
See …

zellij: Add additional options for integrating with shells; default integration disabled again

---

modules/programs/zsh.nix
tests/modules/programs/zsh/aliases.nix
tests/modules/programs/zsh/default.nix

Accidentally bump the lines against each other. Adding a newline to move global aliases to another line when you have both.
Closes https://github.com/nix-community/home-manager/issues/6697
```
```

zsh: fix concatenation of aliases and global aliases

---

modules/programs/fish.nix
tests/modules/programs/fish/default.nix
tests/modules/programs/fish/manpage.nix

Manual pages with spaces in their paths can lead to argument injection.
```console
$ man -w 'MPSCNNBatchNormalizationDataSource -p'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man3/MPSCNNBatchNormalizationDataSource -p.3
$ nix log /nix/store/...
usage: create_manpage_completions.py [-h] [-c CLEANUP_IN] [-d DIRECTORY] [-k]
[-m] [-p] [-s] [-v {0,1,2}] [-z]
[file_paths ...]
create_manpage_completions.py: error: unrecognized arguments: -.3
```
Alternatively, we can use `find -print0 | xargs -0` but let's use `find -exec` and save an invocation to `xargs`.
```
```
See …

fish: Fix manpage completion generation with paths containing spaces

---

modules/modules.nix
modules/programs/mergiraf.nix
tests/default.nix
tests/modules/programs/mergiraf/basic-configuration.nix
tests/modules/programs/mergiraf/default.nix
tests/modules/programs/mergiraf/mergiraf-git-attributes.conf
tests/modules/programs/mergiraf/mergiraf-git.conf

This adds git integration for [mergiraf](https://mergiraf.org/). It sets up git to use mergiraf to automatically resolve merge conflicts. See https://mergiraf.org/usage.html#registration-as-a-git-merge-driver
```
```

mergiraf: init module

---

modules/programs/carapace.nix
tests/modules/programs/carapace/fish.nix

This disables a workaround used for getting carapace to work correctly with the fish shell.
This workaround stopped being necessary with fish 4.0 (which has been in nixpkgs unstable for a few weeks now), as noted in https://carapace-sh.github.io/carapace-bin/setup.html#fish.
I was debating removing this workaround entirely instead of just adding a version check, but I wasn't sure if it's okay to assume that home-manager `master` users also use nixpkgs unstable.
```
``` …

carapace: conditionally disable unnecessary fish completion workaround

---

modules/modules.nix
modules/programs/ripgrep-all.nix
tests/default.nix
tests/modules/programs/ripgrep-all/custom-arguments.nix
tests/modules/programs/ripgrep-all/default-arguments.nix
tests/modules/programs/ripgrep-all/default.nix

Add module for [ripgrep-all](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/text/ripgrep-all/default.nix).
```
```

ripgrep-all: Add module

---

modules/programs/helix.nix
tests/modules/programs/helix/example-settings.nix
tests/modules/programs/helix/settings-expected.toml

Add an extraConfig option for Helix. Fixes #6513
**NOTE: I am assuming the tests pass, as I am facing an unrelated error on both of my machines. All the tests in the actions pass.**
```
```

helix: add extraConfig option

---

modules/lib/maintainers.nix
modules/misc/news.nix
modules/modules.nix
modules/services/mpdscribble.nix
tests/default.nix
tests/modules/services/mpdscribble/basic-configuration.nix
tests/modules/services/mpdscribble/basic-configuration.service
tests/modules/services/mpdscribble/default.nix

This PR adds the module `services.mpdscribble` based on the NixOS module of the same name.
Old feature request: #4963 
```
```

mpdscribble: add module

---

modules/programs/fzf.nix

fzf history keybind (^R) was being rewritten by omz.
This PR moves the initialization of the fzf zsh integration just after omz integration (but sill before other history managers, eg: atuin)
Fixes https://github.com/nix-community/home-manager/issues/6704
```
```

fzf: fix zsh integration (keybinds rewritten by omz)

---

modules/programs/fzf.nix

ensure that fzf is initialized after plugins (fixes https://github.com/nix-community/home-manager/issues/6704#issuecomment-2758808689)
we could also add a config to disable plugin lazy loading 🤔 
```
```
@khaneliman

fzf: update zsh integration to be after plugins

---

modules/programs/helix.nix

Avoids IFD in the helix module which was introduced in #6575.
The helix module fails to build when `--no-allow-import-from-derivation` is enabled.
Command to reproduce the results:
```
nix build --reference-lock-file flake.lock --no-allow-import-from-derivation ./tests#test-helix-example-settings
```
```
```
@Philipp-M

helix: avoid IFD

---

modules/programs/thunderbird.nix

When email account is gmail in thunderbird, set additional server settings.
Addition to already merged https://github.com/nix-community/home-manager/pull/6579.
As seen in https://github.com/nix-community/home-manager/issues/4988 the smtp authMethod wasn't include in the merge and is also needed, because without the authMethod is by default set to password only.
Please provide a brief description of your change.
Added a default option for the setting `mail.smtpserver.smtp_${id}.authMethod` exactly like in the above mentioned pr.
```
``` …

thunderbird: set additional gmail smtpserver settings

---

modules/lib/maintainers.nix
modules/misc/news.nix
modules/modules.nix
modules/programs/sesh.nix
tests/default.nix
tests/modules/programs/sesh/basic-configuration.nix
tests/modules/programs/sesh/basic-configuration.toml
tests/modules/programs/sesh/default.nix

Sesh is a CLI that helps you create and manage tmux sessions quickly and easily using zoxide. See https://github.com/joshmedeski/sesh for more.
```
```

sesh: add module

---

modules/programs/alacritty.nix
modules/programs/eclipse.nix
modules/programs/eww.nix
modules/programs/fish.nix
modules/programs/foot.nix
modules/programs/git.nix
modules/programs/ion.nix
modules/programs/java.nix
modules/programs/keychain.nix
modules/programs/kitty.nix
modules/programs/mangohud.nix
modules/programs/mercurial.nix
modules/programs/mods.nix
modules/programs/obs-studio.nix
modules/programs/opam.nix
modules/programs/pqiv.nix
modules/programs/qutebrowser.nix
modules/programs/swayimg.nix
modules/programs/terminator.nix
modules/programs/tint2.nix
modules/programs/tiny.nix
modules/programs/tmate.nix
modules/programs/tmux.nix
modules/programs/urxvt.nix
modules/programs/wezterm.nix
modules/programs/zoxide.nix
modules/services/lorri.nix
modules/services/polybar.nix
modules/services/swayidle.nix

Converting all the `mkOption` definitions to use the upstreamed `mkPackageOption` helper. 
https://github.com/nixos/nixpkgs/blob/master/lib/options.nix#L309-L309
```
```

treewide: use mkPackageOption

---

modules/launchd/default.nix

Closes https://github.com/nix-community/home-manager/issues/6536
Rework to drop the conflict check, these are home-manager generated and controlled plists and not user data. We will drop and redeploy whenever we need. 
Updated implementation for the deploy to unload and deploy without skipping an agent if there are any runtime issues from `launchd` so we don't skip deploying agents because of an agent that might have been deleted improperly. 
Tested scenarios:
- No changes:
- We don't try to drop/recreate services
- Agent removed
- We unload and remove plist
- Agent changed
- We unload, remove, install, and load agent
- Plist deleted
- We install and load agent
- When bootstrap fails, we continue and don't block other agent activations
NOTE: 
This should fix issues with deploying the …

launchd: refactor implementation

---

modules/services/podman-linux/podman-lib.nix

If a podman container contains the string `podman-`, the activation will fail:
```nix
services.podman.containers."podman-exporter" = {
image = "quay.io/navidys/prometheus-podman-exporter:latest";
};
```
The generated `~/.config/podman/containers.manifest` will only contain `exporter` and thus the non-existing container with that name is considered orphaned. Attempting to remove that container will fail:
```
Loading manifest from /home/niklas/.config/podman/containers.manifest...
Removing orphaned container: podman-exporter
Running: /nix/store/kixsa8zkgkgdhaaw94w97ibz4ljmajn7-podman-5.4.1/bin/podman container stop podman-exporter/nix/store/kixsa8zkgkgdhaaw94w97ibz4ljmajn7-podman-5.4.1/bin/podman container rm -f podman-exporter
Error: --filter takes no arguments
Command failed: …
```

podman: fix service name in generated manifest

---

docs/manual/nix-flakes/nix-darwin.md
docs/manual/nix-flakes/nixos.md
templates/nix-darwin/flake.nix
templates/nixos/flake.nix

This change improves the module system's error messages.
Importing `home.nix` via `import home.nix` prevents information about the file path from being passed to the module system, which makes errors worse. The `home-manager.users.USER` option is of type submodule, which means modules can be set as value. A path can be a module, meaning the `import` is unnecessary.
```
```

docs: correct improper import of home.nix to improve error messages

---

modules/programs/granted.nix

I would like to use the unstable version in my home-manager so let's make it possible to override.
```
```
@wcarlsen

granted: Add override for package

---

modules/services/home-manager-auto-upgrade.nix

Fixes https://github.com/nix-community/home-manager/issues/3127
Tested on my servers with the following configuration:
```
services.home-manager.autoUpgrade = {
enable = true;
frequency = "03:40";
};
systemd.user.services.home-manager-auto-upgrade.Service.ExecStart = lib.mkForce ("${pkgs.writeShellApplication {
name = "home-manager-auto-upgrade";
text = ''
echo "Update Nix's channels"
nix-channel --update
echo "Upgrade Home Manager"
home-manager switch
'';
runtimeInputs = with pkgs; [
nix
(callPackage <home-manager/home-manager> { path = config.programs.home-manager.path; })
];
}}/bin/home-manager-auto-upgrade");
```
By running:
```
home-manager switch
systemctl --user start home-manager-auto-upgrade.service
journalctl --user -u home-manager-auto-upgrade.service -f
```
And then confirming …

auto-upgrade: unbreak on unattended, loginctl enable-linger systems

---

modules/misc/xdg-autostart.nix
tests/modules/misc/xdg/autostart-readonly.nix
tests/modules/misc/xdg/default.nix

Some programs add a `.desktop` file to `XDG_CONFIG_HOME/autostart` when they are started (can't remember from the top of my head which program did for me, and I've already deleted the file), but I want to be able to explicitly grant programs permission to autostart in my home manager configuration. This PR adds a `xdg.autostart.readOnly` option to make that possible.
When `readOnly` is set to `true` the autostart entries are linked from a readonly directory in the nix store and `XDG_CONFIG_HOME/autostart` is a link to that directory, so that programs cannot install arbitrary autostart services.
I haven't added a test yet because I first wanted to check whether this has a chance of being merged and if we really need the `readOnly` option, or if we should just always make …

xdg-autostart: Add readOnly option

---

modules/programs/newsboat.nix

The newboat module did not have a package option. 
```
```
@sumnerevans

newsboat: add a package option to the module

---

docs/default.nix
nixos/common.nix

Changes the strategy how home-manager integrates with `users.users.<name>.packages` to pull instead of push. This side-steps the potential circular dependency when the attribute sets `home-manager.users` or `users.users` are calculated from each other.
```
```

Fix potential recursion between users.users and home-manager.users

---

modules/programs/mcfly.nix

In the fzf module, there is a comment about overriding the order to prevent this from happening:
```nix
programs.fish.interactiveShellInit =
mkIf cfg.enableFishIntegration (mkOrder 200 fishIntegration);
```
However it does not work, and mcfly appears in a separate block in config.fish, *before* fzf, since mcfly is not using interactiveShellInit, meaning the ctrl+r bind is the fzf bind when the intended behavior is to prioritise mcfly. Example:
```fish
/nix/store/anzmx9jfbl2gf2m2ivy5fnavl99kf13c-mcfly-0.9.3/bin/mcfly init fish | source
if status is-interactive
eval "$(/nix/store/80l3p88i1kkbskf6zq14yz4kg520rbv5-mcfly-fzf-0.1.3/bin/mcfly-fzf init fish)"
end
status is-interactive; and begin
/nix/store/8p7nggqkcdz1spffg99hlgdl9pyawcxr-fzf-0.60.3/bin/fzf --fish | source
end
```
This commit …

mcfly: Fix fzf overriding mcfly's Ctrl+R bind

---

modules/programs/msmtp.nix

Closes https://github.com/nix-community/home-manager/issues/6740
```
```

msmtp: fix missing inherits

---

modules/misc/news.nix
modules/modules.nix
modules/programs/streamlink.nix
tests/default.nix
tests/modules/programs/streamlink/config
tests/modules/programs/streamlink/default.nix
tests/modules/programs/streamlink/dummy.py
tests/modules/programs/streamlink/streamlink-custom-plugins.nix
tests/modules/programs/streamlink/streamlink-settings.nix

Closes https://github.com/nix-community/home-manager/issues/6020.
```
```

streamlink: add module

---

modules/i18n/input-method/fcitx5.nix

Sets `SDL_IM_MODULE` to `fcitx`to make fcitx5 work with sdl2 programs.
See https://fcitx-im.org/wiki/Setup_Fcitx_5#SDL_IM_MODULE and https://wiki.archlinux.org/title/Fcitx5#IM_modules
```
```
@Kranzes

fcitx5: set SDL_IM_MODULE

---

modules/files.nix

docs: add docs for mkOutOfStoreSymlink

---

modules/misc/news.nix
modules/programs/jq.nix

added "color for object keys" option
https://jqlang.org/manual/#colors
Change is not backwards compatible. 
Anyone who have programs.jq.colors option not empty will have to add objectKeys value
```
```
@liff @bb010g

jq: add missing color option

---

modules/programs/atuin.nix
modules/programs/carapace.nix
modules/programs/nix-your-shell.nix
modules/programs/oh-my-posh.nix
modules/programs/pay-respects.nix
modules/programs/starship.nix
modules/programs/zoxide.nix
tests/modules/programs/carapace/nushell.nix
tests/modules/programs/nix-your-shell/enable-shells.nix
tests/modules/programs/oh-my-posh/nushell.nix
tests/modules/programs/pay-respects/integration-disabled.nix
tests/modules/programs/pay-respects/integration-enabled.nix
tests/modules/programs/starship/fish_with_interactive.nix
tests/modules/programs/starship/fish_without_interactive.nix

Instead of running programs that print their shell config to stdout every time nushell initializes and saving their output to disk in .cache directory then sourcing it in the main config.nu file, just generate the config during nix build and source it directly from the nix store.
If you want you can implement something similar for all other shells too. It's just that for nushell this seems to be the only rational way.
also pay-respects nushell integration didn't ever work, now it generates the configuration correctly.
but even though the configuration that pay-respects generates is added to nushell config.nu correctly now it still doesn't work for me. On invocation it gives suggestions for the command that invoked it so not the last one before it that it is supposed to fix.
By the way, I …

Build-time nushell config generation

---

modules/services/cliphist.nix

Was running into issues with it not starting properly. This fixed my issue.
```
```

cliphist: use configured systemdTargets throughout service

---

modules/services/swaync.nix

Calls swanyc-client with the argument reload-css/reload-config when config/CSS is changed.
I have simply added calls to `swaync --reload-css` and `swaync --reload-config` for when the config or CSS are changed, so that changes take effect immediately.
```
```
@abayomi185

swaync: Add onChange

---

modules/services/swaync.nix

swaync: use lib.getExe

---

modules/home-environment.nix

Automatically adds `home.shellAliases` to nushell aliases because they are supposed to be shell agnostic and work in bash,zsh,fish AND nushell.
If a bash-only alias was added by the user to `home.shellAliases` and it causes problems with nushell then it's a user error and such aliases should be moved to `programs.bash.shellAliases` by the user.
```
```

home-environment: enable home aliases for nushell

---

modules/services/redshift-gammastep/lib/options.nix
tests/modules/services/redshift-gammastep/default.nix
tests/modules/services/redshift-gammastep/gammastep-tray-configuration-expected.service
tests/modules/services/redshift-gammastep/gammastep-tray-configuration.nix
tests/modules/services/redshift-gammastep/redshift-tray-configuration-expected.service
tests/modules/services/redshift-gammastep/redshift-tray-configuration.nix

Fix a missing dependency for `tray.target` in `redshift/gammastep` module when the tray feature is enabled.
This caused a race condition that could result in the redshift/gammastep systemd user unit failing because the tray provider (e.g. waybar) isn't ready yet.
```
```
@rycee 
@thiagokokada

Gammastep tray

---

modules/services/swaync.nix
tests/modules/services/swaync/swaync.nix

Try to use x-restart-triggers to hot reload on file change, since users with impermanence setups were running into issues with onChange.
Tested myself and works to reload swaync when doing home-manager activation with changing styling. Just not as seamless of a reload as using the cli, but will help prevent issues with impermanence users. 
```
```

swaync: use x-restart-triggers for reload

---

modules/programs/swayr.nix
modules/services/cliphist.nix
modules/services/wlsunset.nix
tests/modules/services/wlsunset/wlsunset-service-expected.service

Closes https://github.com/nix-community/home-manager/issues/6706
```
```

{cliphist, wlsunset, swayr}: systemdTargets default to wayland.systemd target

---

modules/programs/broot.nix
tests/modules/programs/broot/broot.nix

As requested in https://github.com/nix-community/home-manager/issues/6616#issuecomment-2775115182.
- More or less, see description of original PR.
- `test-neovim-plugin-config` fails, but already does so prior to this PR.
```
```
@aheaume

(backport to 24.11) broot: get rid of IFDs (#6723)

---

modules/programs/astroid.nix
modules/programs/kitty.nix

Module was rewritten to use it from `lib`, when it is actually in `builtins`
```
```
@khaneliman

astroid: Fix use of `fromJSON`

---

modules/programs/aerospace.nix
tests/modules/programs/aerospace/aerospace.nix
tests/modules/programs/aerospace/settings-expected.toml

The current aerospace.nix module produces incorrect TOML when for `userSettings.on-window-detected`. Using the following 
```nix
{
on-window-detected = [
{
"if" = { app-id = "com.apple.MobileSMS"; };
run = [ "move-node-to-workspace 10" ];
}
{
"if" = { app-id = "ru.keepcoder.Telegram"; };
run = [ "move-node-to-workspace 10" ];
}
{
"if" = { app-id = "org.whispersystems.signal-desktop"; };
run = [ "move-node-to-workspace 10" ];
}
];
}
```
produces 
```toml
[[on-window-detected]]
run = ["move-node-to-workspace 10"]
[on-window-detected.if]
app-id = "com.apple.MobileSMS"
[[on-window-detected]]
run = ["move-node-to-workspace 10"]
[on-window-detected.if]
app-id = "ru.keepcoder.Telegram"
[[on-window-detected]]
run = ["move-node-to-workspace 10"]
[on-window-detected.if]
app-id = …
```

Aerospace: Flatten on-window-detected.*.if values to fix incorrect TOML

---

.github/workflows/test.yml
flake.lock
flake.nix
format

Removing input until I have time to migrate usage to a dev flake for all the dev dependencies.
Follow up to discussion in matrix and https://github.com/nix-community/home-manager/pull/6772#issuecomment-2787276350
```
```

flake.nix: remove treefmt-nix input

---

modules/programs/ssh.nix

Allow configuring `identityAgent` in the ssh config.
I manually set up the identity agent/paths to better handle/understand how forwarding/agents work in my various usages (local, remote with gpg forwarded, etc).
This is a pretty straight-forward module-option -> config key change.
```
```

modules/programs/ssh: support identityAgent

---

modules/programs/swaylock.nix

Currently, `path` settings values are converted to strings using `builtins.toString`.
This **does not** create a proper dependency to the path destination for the swaylock config.
Hence, the referenced file is subject to being garbage-collected, making the config file invalid.
This patch instead properly interpolates the path which fixes this issue.
Before (no dependency on the referenced file)
After:
```
```
cc @rcerc

swaylock: fix path values in config file

---

modules/services/window-managers/hyprland.nix
tests/modules/services/window-managers/hyprland/multiple-devices-config.conf
tests/modules/services/window-managers/hyprland/simple-config.conf

Change to match the behavior of hyprland flake - https://github.com/hyprwm/Hyprland/pull/9836
Should eliminate crashes / plugin version mismatches when updating hyprland.
```
```
@fufexan

hyprland: load plugins using exec-once

---

flake.nix

Problem: i use jujutsu as a VCS these days https://jj-vcs.github.io/jj/ and when using jujutsu workspaces, they dont contain the `.git` file/folder that git worktrees have. `nix fmt` thus fails `with Error: failed to load config: failed to find tree-root based on tree-root-file: could not find [.git/index] in /home/teto/hm2`
solution: use a different (unique) root file. I first tried with flake.nix for instnace but we have several in the tree while there is only one "release.json"
```
``` …

formatter: use a different treefmt root

---

modules/programs/sesh.nix

related to https://github.com/nix-community/home-manager/pull/5789#issuecomment-2779323292
```
```
@michaelvanstraten

sesh: use '--icons'

---

modules/services/window-managers/xmonad.nix

This patch along with https://github.com/NixOS/nixpkgs/pull/397767 allows pre-built xmonad running on `armv7l` target.
GHC converts `armv7l` and similar to just `arm` https://git.science.uu.nl/f100183/ghc/-/blob/8fa4bf9ab3f4ea4b208f4a43cc90857987e6d497/aclocal.m4#L1874 making `hostPlatform.system` point to `xmonad-arm7l-linux` instead of correct `xmonad-arm-linux`.
```
```

xmonad: fix binary name lookup on armv7l when cross-compiled

---

modules/accounts/contacts.nix

As I described
[here](https://github.com/nix-community/home-manager/issues/4531#issuecomment-2795286473),
the local module for contact does not have proper defaults so the module always
has to be explicitly defined. This change sets hopefully sensible defaults so
it doesn't have to be explicitly configured. The defaults match the calendar module
```
```
@teto

Add sensible defaults to the localModule similar to the calendar localModule

---

modules/programs/jujutsu.nix
tests/modules/programs/jujutsu/example-config.nix

else the file might ignore some options
```
```

jujutsu: evaluate the settings after merging with other options

---

modules/programs/aerospace.nix
tests/modules/programs/aerospace/aerospace.nix
tests/modules/programs/aerospace/settings-expected.toml

This reverts commits 95861b5d9fc73f080b385776167c3dd2874e355b and d2c014e1c73195d1958abec0c5ca6112b07b79da (PR #6778), as they broke Aerospace configuration loading. Whilst the generated TOML configuration wasn't the best, it was completely valid, whereas after the aforementioned PR it was no longer valid.
The reason it's no longer valid is because the "if.app-id" in quotes is interpreted as a full key, instead of being nested in the "if" table. As a visual demonstration of the issue in JSON form, it's meant to be like this:
```json
{
"if": {
"app-id": "asdf"
}
}
```
Whereas after the PR it was this, because of the quotes:
```json
{
"if.app-id": "asdf"
}
```
Which isn't valid Aerospace configuration. For reference here is the error that occurred after the PR was merged:
<details> …

aerospace: revert flattening on-window-detected rules

---

modules/services/way-displays.nix

The use of `lib.mkDefault` causes problems in the generated yaml. I am seeing:
```yaml
CALLBACK_CMD:
_type: override
content: /nix/store/sg9dlv7zva7285340idna4czhsmp418x-libnotify-0.8.4/bin/notify-send
"way-displays ${CALLBACK_LEVEL}" "${CALLBACK_MSG}"
priority: 1000
```
for the defaults. It should just be:
```yaml
CALLBACK_CMD: /nix/store/sg9dlv7zva7285340idna4czhsmp418x-libnotify-0.8.4/bin/notify-send "way-displays ${CALLBACK_LEVEL}" "${CALLBACK_MSG}"
```
But the use of `lib.mkDefault` is not necessary here, since we are using `mergeSets` anyway, so the option can be overridden by a user without `lib.mkForce`.
```
```
See …

way-displays: fix failing use of `lib.mkDefault`

---

modules/programs/helix.nix

The waybar module has similar functionality. Adding this because stylix team would like to be able to use a string/path for the theme as disused in https://github.com/danth/stylix/pull/1125#issuecomment-2791094566 
```
```
@Philipp-M

helix: add support for path and string themes

---

modules/programs/foot.nix
tests/modules/programs/foot/default.nix
tests/modules/programs/foot/regex-modes-expected.ini
tests/modules/programs/foot/regex-modes.nix

closes #5873
```
```
@plabadens

foot: enable duplicate keys

---

modules/programs/nh.nix

Recently switched from FLAKE to NH_FLAKE
```
```

nh: support 4.0 for flake option

---

modules/programs/yazi.nix

Contains IFD and unnecessarily restricts user's configuration.
Came up in previous issues and on matrix again recently. 
```
```

yazi: remove assertions

---

modules/modules.nix
modules/programs/superfile.nix
tests/default.nix
tests/modules/programs/superfile/default.nix
tests/modules/programs/superfile/empty-settings.nix
tests/modules/programs/superfile/example-config-expected.toml
tests/modules/programs/superfile/example-hotkeys-expected.toml
tests/modules/programs/superfile/example-settings.nix
tests/modules/programs/superfile/example-theme-expected.toml
tests/modules/programs/superfile/example-theme2-expected.toml
tests/modules/programs/superfile/partial-theme-settings-expected.toml
tests/modules/programs/superfile/partial-theme-settings.nix

Add initial support for `superfile`. Basic settings & theme file creation.
Closes #6609 
```
```

superfile: initial support

---

modules/programs/direnv.nix
tests/modules/programs/direnv/default.nix
tests/modules/programs/direnv/silent.nix

see https://github.com/direnv/direnv/issues/68 (bottom of thread)
Closes https://github.com/nix-community/home-manager/issues/6822
```
```
@rycee @khaneliman @shikanime

direnv: fix silent option after update to direnv v2.36.0

---

modules/programs/nh.nix

From what I understand, the warning relating to the system GC conflicting with the nh user GC (added in #6470)  was incorrect. There shouldn't be any conflict between osConfig.nix.gc and programs.nh.clean as our home-manager service only cleans user profiles (which nix-collect-garbage does not do).
In this scenario they should both work at the same time as they are cleaning two different things.
~~- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).~~
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) …

nh: remove incorrect warning on gc conflicts

---

home-manager/home-manager

Feature testing flakes / nix-command is more robust over configuration sniffing. Ultimately, the deciding factor should be if flakes work -- not if the config looks like they will / won't work.
This alternative test both asserts that the `nix` command is enabled, and that flakes are enabled, without depending on whether or not flakes are emitted as an experimental feature.
This is both repairing support for Determinate Nix 3, and prepares for a potential future where Nix itself considers Flakes stable.
Closes #6702
Backport of #6824 
```
``` …

home-manager: Feature test for flake support

---

modules/programs/firefox/mkFirefoxModule.nix

This allows `programs.firefox.profiles.*.userChrome` to be set to a:
derivation, path/path-like string to directory or file, or multiline
text to be used as content verbatim.
This allows setting, for example(s):
```nix
programs.firefox.profiles."jacob.default".userChrome = pkgs.wavefox;
programs.firefox.profiles."jacob.default".userChrome =
"${pkgs.wavefox}/userChrome.css";
```
```
```

progs: firefox: *.userChrome may be path or drv 

---

modules/modules.nix
modules/programs/chawan.nix

This is a super cool TUI browser capable of CSS and other cool stuff. Reminiscent of ELinks but modern and better.
More info here: https://sr.ht/~bptato/chawan/
```
```

chawan: init module

---

modules/programs/firefox/mkFirefoxModule.nix
tests/modules/programs/firefox/profiles/userchrome/chrome/userChrome.css
tests/modules/programs/firefox/profiles/userchrome/default.nix
tests/modules/programs/firefox/profiles/userchrome/expected-userchrome.css

Closes https://github.com/nix-community/home-manager/issues/6834
```
```

mkFirefoxModule: fix userChrome with leading comment

---

tests/modules/programs/firefox/profiles/userchrome/default.nix

Tests passed, but looks like `nmt` was swallowing the command not found errors.
```
```

tests/firefox: fix test commands

---

modules/modules.nix
modules/programs/keepassxc.nix
tests/default.nix
tests/modules/programs/keepassxc/default-settings.nix
tests/modules/programs/keepassxc/default.nix
tests/modules/programs/keepassxc/example-settings.nix
tests/modules/programs/keepassxc/keepassxc-example-config.ini
tests/modules/services/window-managers/labwc/autostart
tests/modules/services/window-managers/labwc/labwc-autostart.nix

Add module for [KeePassXC](https://keepassxc.org/), a popular password manager.
Implements handling of config file.
```
```

keepassxc: add module

---

tests/default.nix
tests/modules/config/home-cursor/default.nix
tests/modules/config/home-cursor/expected-index.theme
tests/modules/programs/broot/broot.nix
tests/modules/programs/thunderbird/thunderbird-native-messaging-host.nix
tests/modules/programs/thunderbird/thunderbird-with-firefox.nix
tests/modules/programs/thunderbird/thunderbird.nix

Not relevant for testing and CI broken because of upstream issues. 
```
```

tests: dont use realPkgs

---

.github/workflows/conflicts.yml

Add labeler for merge conflicts to automate what i've been doing manually (poorly)
```
```

workflows/conflicts: init

---

modules/lib/maintainers.nix
modules/misc/news/2025-04-18_10-58-18.nix
modules/modules.nix
modules/programs/inori.nix
tests/default.nix
tests/modules/programs/inori/default-config.nix
tests/modules/programs/inori/default.nix
tests/modules/programs/inori/full-config.nix
tests/modules/programs/inori/full-config.toml

This adds a module to configure [Inori](https://github.com/eshrh/inori), a MPD client written in Rust.
This depends on NixOS/nixpkgs#371762 getting merged first. Tests are expected to fail since the package doesnt exist yet.
This also depends on features that are expected to come out in the upcoming 0.2.3 release (should be within the next few days).
CC: @eshrh @stephen-huan
```
```

inori: init module

---

modules/programs/kitty.nix

Kitty supports a diff tool integration. This allows enabling it easily for a user.
https://sw.kovidgoyal.net/kitty/kittens/diff/#integrating-with-git
```
```

kitty: add git diff integration

---

modules/programs/fish.nix
tests/modules/programs/fish/abbrs.nix

Allows the use of multiple commands for one abbreviation like so:
```nix
s = {
command = ["git" "hg"];
expansion = "status";
};
```
This then expands `s` to `status` if there is `git` or `hg` typed before.
```
```
no maintainer – @zhaofengli hope you don’t mind checking since you were the last to edit :)

fish: allow multiple commands for command option in abbreviations

---

modules/modules.nix
modules/services/restic.nix
tests/default.nix
tests/integration/default.nix
tests/integration/standalone/restic-home.nix
tests/integration/standalone/restic.nix
tests/modules/services/restic/backup-configs.nix
tests/modules/services/restic/default.nix
tests/modules/services/restic/unit-files.nix

Restic! (finally :3) The module is modeled off the NixOS one, I've tried to maintain the public API as best I can, and port over the integration tests.
Resolves #5009
```
```

restic: init module

---

modules/lib/maintainers.nix
modules/misc/news/2025-04-20_00-39-01.nix
modules/modules.nix
modules/programs/wallust.nix
tests/default.nix
tests/modules/programs/wallust/default.nix
tests/modules/programs/wallust/expected.toml
tests/modules/programs/wallust/wallust.nix

closes #6566.
note this wallust module is still relatively modest compared to the existing pywal one, which is a bit more opinionated, coming with templates for a few applications.
if anything tho, it already enables configuring the program using nix.
```
```
@aguirre-matteo

wallust: add module

---

modules/lib/maintainers.nix
modules/modules.nix
modules/programs/vesktop.nix
tests/default.nix
tests/modules/programs/vesktop/basic-configuration.nix
tests/modules/programs/vesktop/basic-settings.json
tests/modules/programs/vesktop/basic-theme.css
tests/modules/programs/vesktop/basic-vencord-settings.json
tests/modules/programs/vesktop/default.nix

I have added a module for configuring vesktop settings, and also options for configuring the theme and enabled plugins through vencord, in addition to adding myself to the maintainer list.
```
```

vesktop: add module

---

modules/modules.nix
modules/programs/uv.nix
tests/default.nix
tests/modules/programs/uv/default.nix
tests/modules/programs/uv/example-settings.nix
tests/modules/programs/uv/no-settings.nix

Fixes #5154 
Adds a new module for the python package manager uv. Includes support for writing settings to a config file and enabling shell integrations for bash/zsh/fish. I also added multiple tests (based on those for `atuin`).
```
```

uv: init module

---

modules/modules.nix
modules/services/shikane.nix
tests/default.nix
tests/modules/services/shikane/basic-configuration.nix
tests/modules/services/shikane/default.nix
tests/modules/services/shikane/expected.toml

This adds shikane, another dynamic output configuration tool that automatically detects and configures connected outputs on wayland compositors.
Gitlab repo: https://gitlab.com/w0lff/shikane
```
```

shikane: init module

---

modules/programs/ranger.nix
tests/modules/programs/ranger/configuration.nix

ranger: nullable package support

---

modules/misc/qt/kconfig.nix

Previously shell arguments were not escaped properly, leading to breakage on group names containing characters with special meaning to the shell (in particular spaces); theoretically keys containing single quotes would be affected too. Escape all arguments passed to the shell properly instead.
```
```

kconfig: escape arguments properly

---

modules/programs/direnv.nix

Discussion and retesting in
https://github.com/NixOS/nixpkgs/pull/398717. The env variable is actually not needed when you use the config.
```
```

direnv: only set sessionVariable for old version

---

modules/programs/atuin.nix

Right now, building the configuration reports a warning:
> trace: evaluation warning: The type `types.string` is deprecated. See https://github.com/NixOS/nixpkgs/pull/66346 for better alternative types.
Technically the code is not equivalent because `str` and `string` behave differently, but given that the change was introduced ~4h ago I wouldn't consider it _that_ breaking.
```
```
@hawkw @water-sucks

atuin: Fix deprecated string type warning

---

modules/programs/vesktop.nix
tests/modules/programs/vesktop/basic-configuration.nix
tests/modules/programs/vesktop/basic-vencord-settings.json

adds to #5587
```
```
@Flameopathic @LilleAila

vesktop: add support for multiple themes

---

modules/services/lorri.nix

https://github.com/nix-community/home-manager/pull/6871#issuecomment-2819526793
```
```

lorri: fix missing makeSearchPath

---

modules/services/xsettingsd.nix

Remove `lib.` inserted into xsettingsd with treewide remove of  `with lib` usage.
```
```

xsettingsd: Remove erroneous `lib.` insertion

---

modules/misc/xdg-autostart.nix

Replace `runcommandNoCCLocal` by `runCommandLocal` because the former is an alias of the latter. This change fixes builds where `allowAliases = false`.
```
```
@Scrumplex

xdg-autostart: fix runCommandNoCCLocal deprecation

---

.github/labeler.yml

motivated by https://github.com/nix-community/home-manager/pull/6839
```
```

ci: label msmtp changes with "mail"

---

modules/programs/keepassxc.nix

Register KeepassXC as a native messaging host in supported browsers to integrate with KeepassXC's browser extension.  See [this Discourse thread](https://discourse.nixos.org/t/keepassxc-browser-extension-integration/39553) for more information.
```
```
@d-brasher

keepassxc: register as native messaging host

---

modules/i18n/input-method/fcitx5.nix
tests/modules/i18n/input-method/fcitx5-configuration.nix

- Adds `themes` option with several suboptions
- Adds `classicUiConfig` option for `classicui.conf` configuration
```
```

fcitx5: add `themes` and `classicUiConfig` options

---

.github/labeler.yml

fixup of https://github.com/nix-community/home-manager/pull/6881#pullrequestreview-2784700134
```
```

ci: fixed redundant rule

---

modules/programs/firefox/mkFirefoxModule.nix
tests/modules/programs/firefox/profiles/userchrome/default.nix

Reverting all the recent userChrome changes because of too many issues and bikeshedding.
Closes https://github.com/nix-community/home-manager/issues/6882
```
```

mkFirefoxModule: revert userChrome changes

---

modules/programs/zsh.nix

https://github.com/nix-community/home-manager/pull/6479 introduced a more comprehensive option that allows fine tuning location of zsh config. Encourage using that over the predetermined locations.
```
```

zsh: deprecate initLocation options in favor of initContent

---

modules/i18n/input-method/default.nix
modules/i18n/input-method/fcitx5.nix
modules/i18n/input-method/hime.nix
modules/i18n/input-method/kime.nix
modules/i18n/input-method/nabi.nix
modules/i18n/input-method/uim.nix
tests/modules/i18n/input-method/default.nix
tests/modules/i18n/input-method/kime-configuration.nix
tests/modules/i18n/input-method/old-fcitx5-enable.nix
tests/modules/misc/qt/qt-platform-theme-gtk.nix

confusing for home-manager to use the deprecated style from nixos 
see: https://github.com/NixOS/nixpkgs/pull/310708
```
```
@Kranzes

i18n.inputMethod: align enable option with nixos

---

modules/programs/vesktop.nix

Prevent generating empty settings files that prevent using the application's writable settings files.
```
```

vesktop: only generate settings when configured

---

.github/workflows/conflicts.yml
.github/workflows/update-flake.yml

github keeps sending me emails b/c they are failing on my fork (e.g. https://github.com/awwpotato/home-manager/actions/runs/14610278483/job/40986902179, https://github.com/awwpotato/home-manager/actions/runs/14609635006/job/40985133944)
```
```

workflows: only run conflicts and update flake on main repo

---

modules/i18n/input-method/fcitx5.nix
tests/modules/i18n/input-method/fcitx5/old-enable.nix

not sure why the tests didn't catch this.
```
```

fcitx5: fix iniFormat usage

---

format

See commit message for details. Fixes https://github.com/nix-community/home-manager/issues/6858
```
```

format: fix failing with newer treefmt; use /var/empty for temp home

---

modules/modules.nix
modules/programs/waybar.nix
modules/services/avizo.nix
modules/services/clipman.nix
modules/services/dunst.nix
modules/services/fnott.nix
modules/services/hypridle.nix
modules/services/hyprpaper.nix
modules/services/kanshi.nix
modules/services/swayidle.nix
modules/services/swaync.nix
modules/services/swayosd.nix
modules/services/window-managers/hyprland.nix
modules/services/window-managers/i3-sway/sway.nix
modules/services/window-managers/river.nix
modules/services/wob.nix
modules/wayland.nix
modules/xsession.nix
tests/modules/programs/waybar/deprecated-modules-option.nix
tests/modules/programs/waybar/settings-complex.nix
tests/modules/programs/waybar/settings-with-attrs.nix
tests/modules/programs/waybar/styling.nix
tests/modules/programs/waybar/systemd-with-graphical-session-target.nix
tests/modules/programs/waybar/systemd-with-graphical-session-target.service
tests/modules/services/clipman/clipman-sway-session-target.service
tests/modules/services/fnott/systemd-user-service-expected.service
tests/modules/services/swayidle/basic-configuration.nix
tests/modules/services/swaync/swaync.nix

Backport of #6253 (standardize wayland graphical services) and #6332 (create tray.target if xsession is not enabled).
IMO this should be backported because it fixes a common activation failure, which impacted other activation steps like stylix.
The first PR was already backwards compatible, I merely removed a change for a module that isn't in stable.
The second PR wasn't initially backwards compatible, but I added `lib.mkDefault` to ensure that configurations with the workaround discussed in #2064 still work.
Feel free to reject it if you don't want this backported.
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more …

Backport #6253 and #6332

---

modules/programs/thefuck.nix
tests/modules/programs/thefuck/integration-enabled-instant.nix
tests/modules/programs/thefuck/integration-enabled.nix

Added an alias option supported by bash, zsh, fish, and nushell integration
```
```
@ilaumjd

thefuck: Add alias option

---

modules/modules.nix
modules/programs/rmpc.nix
tests/default.nix
tests/modules/programs/rmpc/default.nix
tests/modules/programs/rmpc/example-config.nix
tests/modules/programs/rmpc/example-config.ron

This PR adds a module for configuring [RMPC](https://github.com/mierak/rmpc), a terminal based Media Player.
Since the config format of RMPC is the Rusty Object Notation (RON), and Nixpkgs doesn't have a generator for that,
I added the `extraConfig` options instead of `settings`. Closes #6611.
```
```

rmpc: add module

---

modules/misc/news.nix
modules/misc/news/2025-04-26_18-56-13.nix
modules/services/espanso.nix
tests/modules/services/espanso/basic-configuration.nix
tests/modules/services/espanso/default.nix

Tested on
- kde plasma x11 
- kde plasma wayland
- niri wm (wayland)
- xfce (x11)

espanso: add wayland support

---

modules/programs/neomutt.nix

neomutt currently depends transitively via notmuch on emacs.
As currently phrased, building the neomutt config unconditionally takes nixpkgs's neomutt, not the one home-manager has been configured to use, so it pulls in emacs even if you use `package = pkgs.neomutt.override {withNotmuch = false;};`.
I've manually tested that the resulting home-manager doesn't depend on `emacs` when building with neomutt's `package = pkgs.neomutt.override {withNotmuch = false;};`. The build without that `package = ` config gets as far as trying to build emacs on my machine with this home-manager, which I take to mean that existing users are unbroken by this change.
```
```
See …

neomutt: use correct neomutt in config file

---

modules/programs/zsh.nix

zsh: add type to zprof.enable option

---

modules/programs/eza.nix
tests/darwinScrublist.nix
tests/default.nix
tests/modules/programs/eza/bash.nix
tests/modules/programs/eza/default.nix
tests/modules/programs/eza/fish.nix
tests/modules/programs/eza/ion.nix
tests/modules/programs/eza/nushell.nix
tests/modules/programs/eza/theme.nix
tests/modules/programs/eza/zsh.nix

Reverting default behavior for this module again since the nushell integration causes a breaking behavior with the `ls` alias.
Closes https://github.com/nix-community/home-manager/issues/6687
```
```

eza: default disable nushell integration again

---

modules/programs/firefox/mkFirefoxModule.nix

Closes https://github.com/nix-community/home-manager/issues/6902
```
```

mkFirefoxModule: support wrapped darwin derivations

---

modules/modules.nix
modules/programs/kickoff.nix
tests/default.nix
tests/modules/programs/kickoff/default.nix
tests/modules/programs/kickoff/example-config.nix
tests/modules/programs/kickoff/example-config.toml

This PR adds a module for configuring [kickoff](https://github.com/j0ru/kickoff) a minimal program launcher.
Closes #6076.
```
```

kickoff: add module

---

modules/programs/gh.nix
tests/modules/programs/gh/default.nix
tests/modules/programs/gh/hosts-file.nix

Add a `programs.gh.hosts` option that -- similar to `programs.gh.settings` -- gives structured access to `$XDG_CONFIG_HOME/gh/hosts.yml`.
```
```
@gerschtli
@berbiche

gh: add `hosts` option

---

modules/programs/nh.nix

to sync with upstream option
```
```

nh: add path option for flake

---

modules/programs/rclone.nix

Pass `--non-interactive` flag to `rclone config update` calls so that an incomplete config is not used, resulting in failure on some remotes, for example gdrive.
Resolves #6920.
Refer to the linked issue.
```
```
@ttrssreal

rclone: make secret injection non-interactive

---

modules/services/gpg-agent.nix
tests/modules/services/gpg-agent/default-homedir.nix
tests/modules/services/gpg-agent/default.nix
tests/modules/services/gpg-agent/override-homedir.nix
tests/modules/services/gpg-agent/pinentry-program.nix

Just declaring an alternative solution to https://github.com/nix-community/home-manager/pull/6874 for allowing a user to provide which binary they want to use for their `pinentry-program`.
Closes https://github.com/nix-community/home-manager/pull/6874 
Not sure if we want to make this more generic of a solution for package options treewide... 
```
```

gpg-agent: pinentryPackage -> pinentry.package and add pinentry.program` 

---

modules/programs/pls.nix
tests/modules/programs/pls/bash.nix
tests/modules/programs/pls/fish.nix
tests/modules/programs/pls/zsh.nix

Allow granular control of alias creation utilizing our shell integration options.
```
```
@arjan-s

pls: enableAliases -> enableShellIntegration

---

nixos/common.nix

I think it would be cool to propagate the `_class`, similar to `config` via `osConfig`. I went with `_osClass` after nixpkgs uses `_class`.
also see: https://github.com/NixOS/nixpkgs/pull/395141
```
```

nixos,darwin: add _osClass as a specialArg

---

modules/programs/carapace.nix

`carapace _carapace nushell` adds `/homeless-shelter/.config/carapace/bin` to PATH, this changes it to ` $HOME/.config/carapace/bin`. Other shells don't have this problem as they run the relevant command and source on startup whereas Nix writes the command output to a file as part of the build.
```
```
@Weathercold
@bobvanderlinden

carapace: fix nushell PATH env var

---

modules/i18n/input-method/kime.nix

Since the `kime` command basically runs other subcommands, such as `kime-wayland`, and then exits, it should be defined as a oneshot service.
```bash
● kime-daemon.service - Kime input method editor
Loaded: loaded (/home/user/.config/systemd/user/kime-daemon.service; enabled; preset: ignored)
Active: active (exited) since Sun 2025-04-27 05:59:02 UTC; 3 days ago
Invocation: c45e54817331430d91d448935bd6edad
Main PID: 3532 (code=exited, status=0/SUCCESS)
Tasks: 6 (limit: 18609)
Memory: 165M (peak: 199M)
CPU: 4min 26.547s
CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/kime-daemon.service
├─3534 /nix/store/7xwccammjd3b78328bha9vwm56h23bvf-kime-3.1.1/bin/kime
├─3536 kime-xim
├─3538 kime-wayland
└─3539 kime-indicator
Apr 27 05:59:02 host systemd[3335]: Starting Kime input method …
```

kime: fix systemd service

---

modules/services/restic.nix
tests/integration/standalone/restic-home.nix
tests/integration/standalone/restic.nix

Restic: fix `pruneOpts` erroring

---

home-manager/home-manager

Makes the formatting of the generated initial `flake.nix` match the RFC style format.
```
```

home-manager: new formatting of generated configuration

---

.gitlab-ci.yml

This removes the automatic update of the Home Manager packaging in <https://gitlab.com/rycee/nur-expressions/>. That setup is very old and brittle, it should therefore not be used.
```
```

ci: remove GitLab rycee/nur-expression update

---

flake.lock

Bump Nixpkgs in the flake lock.
```
```

flake: bump nixpkgs

---

modules/home-environment.nix
modules/programs/fish.nix

- Adds `home.extraDependencies`, which (like `system.extraDependencies` in NixOS) adds a package to the runtime closure without exposing it elsewhere.
- Uses this to keep empty Fish completions around. These are otherwise needlessly garbage-collected: garbage-collecting them saves almost no space (just an empty directory) and they're usually rebuilt soon after. See #6157.
The diff for the Fish change looks large, but all it does is add the inputs to `destructiveSymlinkJoin` to `home.extraDependencies` too: I have to move some code around to make that possible.
(nmt-test-firefox-profiles-search and nmt-test-floorp-profiles-search fail, but they do so on master too... I'll try to find some time to track down …

Stop garbage-collection empty fish completion packages

---

modules/modules.nix
modules/services/clipcat.nix
tests/default.nix
tests/modules/services/clipcat/cfg/ctl.toml
tests/modules/services/clipcat/cfg/daemon.toml
tests/modules/services/clipcat/cfg/menu.toml
tests/modules/services/clipcat/default.nix
tests/modules/services/clipcat/example-config.nix

This PR adds a module for configuring Clipcat (clipcatctl, clipcatd, clipcat-menu) and its respective Systemd Unit. Closes #6297.
NOTE: I didn't added `{ nullable = true; }` to the package option since the package is needed in the Systemd Unit (`"${cfg.package}/bin/clipcatd"`). Feel free to show me an alternative.
```
```

clipcat: add module

---

modules/services/restic.nix
tests/integration/standalone/restic-home.nix
tests/integration/standalone/restic.nix

restic: allow the convenience script to source environmentFile

---

modules/lib/nushell.nix

This PR prevents `lib.hm.nushell.toNushell` from unconditionally aborting the evaluation if an error is detected, allowing consumers to `tryEval` the result and provide a fallback value.
The `abort` was there originally because it's what the `toLua` function it's based on does, but I think it makes sense to `throw` in most cases. I'd even argue this should be a treewide change :)
```
```
@Philipp-M @aidalgol

nushell: throw instead of abort

---

modules/modules.nix
modules/programs/visidata.nix
tests/default.nix
tests/modules/programs/visidata/config
tests/modules/programs/visidata/default.nix
tests/modules/programs/visidata/example-config.nix

This PR adds a module for configuring [Visidata](https://www.visidata.org/), an interactive multi-tool for tabular data. Closes #6202.
```
```

visidata: add module

---

modules/programs/thunderbird.nix

Even if no accounts were configured, it was defaulting to just account1, which meant all other accounts were deleted every time thunderbird was restarted. This fixes that by defaulting to the empty list (so it remains unset in the user.js).
Introduced #6310 (probably)
Fixes #6800
Btw, I'm not even sure whether `account1` always corresponds to the local folders account; on my machine, it instead corresponds to the first email account I added. I feel like trying to handle thunderbird account management through home-manager is inherently fragile.
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent …

thunderbird: fix accounts being removed

---

modules/programs/thunderbird.nix
tests/modules/programs/thunderbird/thunderbird.nix

- **thunderbird: deprecate darwinSetupWarning option**
```
```

thunderbird: darwin cleanup

---

modules/programs/firefox/mkFirefoxModule.nix
tests/default.nix
tests/modules/programs/firefox/policies.nix
tests/modules/programs/firefox/profiles/bookmarks/attrset.nix
tests/modules/programs/firefox/profiles/bookmarks/default.nix
tests/modules/programs/firefox/profiles/containers/default.nix
tests/modules/programs/firefox/profiles/extensions/default.nix
tests/modules/programs/firefox/profiles/overwrite/default.nix
tests/modules/programs/firefox/profiles/search/default.nix
tests/modules/programs/firefox/profiles/settings/default.nix
tests/modules/programs/firefox/profiles/userchrome/default.nix
tests/modules/programs/firefox/setup-firefox-mock-overlay.nix
tests/modules/programs/firefox/state-version-19_09.nix

Signed-off-by: Ihar Hrachyshka <ihar.hrachyshka@gmail.com>
Enable all firefox tests on darwin.
```
```

tests: enable all firefox tests on darwin (plus derivations)

---

modules/services/mako.nix
tests/default.nix
tests/modules/services/mako/config
tests/modules/services/mako/default.nix
tests/modules/services/mako/example-config.nix

This PR refactors the `services.mako` module to replace all its configuration options with `settings` and `criterias`. I also added a test for the configuration. . Indirectly closes #6251.
```
```

mako: refactor

---

modules/programs/wofi.nix
tests/modules/programs/wofi/default.nix
tests/modules/programs/wofi/style-local-file.nix

This PR allows the option `programs.wofi.style` to be set to either a string or a path. Closes #5448.
```
```

wofi: allow path to style.css

---

modules/modules.nix
modules/programs/i3bar-river.nix
tests/default.nix
tests/modules/programs/i3bar-river/config.toml
tests/modules/programs/i3bar-river/default.nix
tests/modules/programs/i3bar-river/example-config.nix

This PR adds a module for configuring [i3bar-river](https://github.com/MaxVerevkin/i3bar-river). Closes #5291.
```
```

i3bar-river: add module

---

modules/services/mako.nix
tests/modules/services/mako/example-config.nix

causing issue in stylix because we have to disable typo checks https://github.com/danth/stylix/pull/1211/files#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0
```
```

mako: fix criterias typo

---

modules/programs/ghostty.nix

Home Manager creates broken link to the Ghostty config syntax highlighting definition file, because it has different location on Darwin. This PR updates path to the config for Darwin users.
Fixes #6961
```
```
@HeitorAugustoLN
@khaneliman

ghostty: fix config syntax file location on darwin

---

modules/modules.nix
modules/programs/sway-easyfocus.nix
modules/services/mako.nix
tests/default.nix
tests/modules/programs/sway-easyfocus/config.yaml
tests/modules/programs/sway-easyfocus/default.nix
tests/modules/programs/sway-easyfocus/example-config.nix

This PR adds a module for configuring Sway-Easyfocus. Closes #5050.
```
```

sway-easyfocus: add module

---

modules/programs/television.nix

fixes https://github.com/nix-community/home-manager/issues/6979
```
```

television: add shell integrations

---

modules/lib/default.nix
modules/lib/deprecations.nix
modules/lib/strings.nix
modules/services/mako.nix
tests/darwinScrublist.nix
tests/modules/programs/man/apropos.nix

Follow up to https://github.com/nix-community/home-manager/pull/6987#issuecomment-2856395024
```
```

lib/strings: add {toKebabCase,toSnakeCase,toCaseWithSeparator}; lib/deprecations: add mkSettingsRenamedOptionModules with transform

---

modules/misc/tmpfiles.nix

Make sure that tmpfiles entries that ask for files/directories to be removed, are also executed
```
```
@dawidsowa

tmpfiles: also remove files that need to be removed during activation

---

modules/programs/alot.nix
tests/modules/programs/alot/alot-expected.conf

Previously, maildir path was not escaped in any way, so using a path with commas lead to a TypeError:
```
TypeError: expected string or bytes-like object, got 'list'
```
This change wraps the maildir path in quotes to allow commas and other special characters to be tolerated.
```
```

alot: allow commas in maildir path

---

modules/programs/sbt.nix
tests/modules/programs/sbt/credentials.nix

In Sbt (prior to 2.0) a sbt key not scoped to `ThisBuild` will always be at the project level, rather than at the build level.
In order to do some things, like use a private repository configured by sbt with sbt-scalafix, we need the credentials scope to the build, otherwise the credentials show as non-existant.
```
```
@kubukoz

Sbt credentials scoping to build rather than projects.

---

modules/modules.nix

This partially reverts a0461b67ff657b6b6e51bb4a547ad98907d28dc8, where a duplicate entry for `./programs/vim.nix` was erroneously added.
```
```
@khaneliman @rycee

modules/modules.nix: drop duplicate entry

---

modules/programs/git.nix
tests/darwinScrublist.nix
tests/modules/programs/git/default.nix
tests/modules/programs/git/git-patdiff-expected.conf
tests/modules/programs/git/git-patdiff.nix

This adds the ability to enable the `patdiff` program as git differ.
Website of the project: https://opensource.janestreet.com/patdiff/
I have tested it via a test and not building it myself, since I'm still on 24.11 and it doesn't evaluate.
```
```
@rycee

git: configure patdiff through [patdiff] git section

---

modules/programs/rofi.nix
tests/modules/programs/rofi/custom-theme-config.rasi
tests/modules/programs/rofi/valid-config-expected.rasi
tests/modules/programs/rofi/valid-config.nix

Adds `programs.rofi.modes` option.
For the tiny convenience of supporting the custom mode syntax.
```
```

rofi: modes option

---

modules/programs/rofi.nix
tests/modules/programs/rofi/custom-theme-config.rasi

Don't include the modes option if it hasn't been used.
Follow up to https://github.com/nix-community/home-manager/pull/6115
```
```

rofi: modes optional

---

modules/modules.nix
modules/programs/wayprompt.nix
tests/default.nix
tests/modules/programs/wayprompt/default.nix
tests/modules/programs/wayprompt/empty-settings.nix
tests/modules/programs/wayprompt/example-settings-expected.ini
tests/modules/programs/wayprompt/example-settings.nix

Add module for [Wayprompt](https://git.sr.ht/~leon_plickat/wayprompt), a password-prompter, (including pinentry for GnuPG) for Wayland.
See also this [reddit post](https://www.reddit.com/r/swaywm/comments/xoawfu/wayprompt_layer_shell_pinentry_dropin_replacement/) for some usage examples.
```
```
@khaneliman

wayprompt: init module

---

modules/lib/maintainers.nix
modules/modules.nix
modules/programs/lutris.nix
tests/default.nix
tests/modules/programs/lutris/default.nix
tests/modules/programs/lutris/empty.nix
tests/modules/programs/lutris/runners-configuration.nix
tests/modules/programs/lutris/wine-configuration.nix

Add a lutris module.
I've been using a similar version on my personal config for a while, only ever added features I found absolutely necessary to use lutris properly:
- Add any number of wine packages
- Add any number of proton packages
- Link runners directly from nix instead of using lutris.
- Specify the steam package lutris should use.
- Extra packages passed to lutris (mainly since it's often missing essential things, such as umu-launcher)
I'm aware #6213 has an implementation already, but I do not agree that runners should be added to the user's home path, instead for normal runners I set the runner's config variable 'runner_executable' to the package executable directly.
As a side effect of "hijacking" the runner's config for this I also added the ability to configure these …

lutris: add module

---

docs/manual/contributing/guidelines.md

Since 613dbb35dbc142fd5cadca847f8677e64a502bfa, the manual produces an `index.xhtml` file, instead of a plain `index.html`.
```
```
@awwpotato @khaneliman

docs: update filename of generated HTML manual

---

modules/modules.nix
modules/programs/waveterm.nix
tests/default.nix
tests/modules/programs/waveterm/cfg/bookmarks.json
tests/modules/programs/waveterm/cfg/settings.json
tests/modules/programs/waveterm/cfg/termthemes.json
tests/modules/programs/waveterm/default.nix
tests/modules/programs/waveterm/example-config.nix

This PR adds a module for configuring WaveTerm. It provides options for its settings, themes and bookmarks. Closes #6997.
```
```

waveterm: add module

---

modules/programs/neovide.nix

neovide: fix error when no settings are declared

---

modules/misc/news/2025-05-08_17-45-24.nix

Add missing news entry for the recently added Wayprompt module.
See #7002.
Folks, in the official docs, it is stated that if you contribute a module, you don’t have to add the news entry, and that the merger will take care of that (to reduce merge conflicts). OTOH, with the recent introduction of `create-news-entry.sh`, this shouldn’t be a problem anymore, and in fact some of the last module contributions include a news entry in their PR.
Should we update the docs to reflect this?
```
``` …

wayprompt: add news entry for linux

---

modules/programs/direnv.nix

Direnv exports PATH as a string, nu expects it to be a list and breaks some functionality like external command completion. This requires nushell 0.104.0, which is merged into nixpkgs-unstable.
Change loosely based on [this](https://github.com/nushell/nushell.github.io/pull/1878) while trying to not change the logic too much
```
```
@khaneliman
@rycee
@shikanime

direnv: update nushell env conversion logic

---

modules/programs/jujutsu.nix
tests/modules/programs/jujutsu/empty-config.nix
tests/modules/programs/jujutsu/example-config.nix

Following https://github.com/jj-vcs/jj/pull/6300, Jujutsu has deprecated support for configuration files in `~/Library/Application Support` for darwin. The XDG-standard configuration location can be used instead, for all platforms.
```
```

jujutsu: store configuration in $XDG_CONFIG_HOME for all platforms

---

modules/programs/distrobox.nix

This PR adds an option `enableSystemdUnit` to the Distrobox module to make the Systemd Unit optional, and hard coded as is now.
```
```

distrobox: make systemd unit optional

---

docs/manual/contributing/guidelines.md
docs/manual/contributing/news.md
flake.nix

Easier to `nix run .#create-news-entry` instead of finding the location to run.
```
```

flake.nix: expose create-news-entry as a package

---

modules/lib/maintainers.nix
modules/services/autorandr.nix

- Add myself as a maintainer in home-manager for `services/autorandr`.
- Add a `package` option to be able to easily override the packages and add `matchEdid` and `extraOptions` for configuration of the `autorandr` service.
~~- [ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).~~; There are no test cases for this service, it simply creates a systemd configuration.
```
``` …

services/autorandr: improve service configurability

---

modules/lib/maintainers.nix
modules/misc/news/2025-05-10_21-08-48.nix
modules/modules.nix
modules/programs/numbat.nix
tests/default.nix
tests/modules/programs/numbat/default.nix
tests/modules/programs/numbat/empty-config.nix
tests/modules/programs/numbat/example-config.nix

This PR adds a module for configuring [Numbat](https://numbat.dev/), a high-precision scientific calculator with full support for physical units. It uses [RFC 42](https://github.com/NixOS/rfcs/blob/master/rfcs/0042-config-option.md)-style `settings` and provides `enable` and `package` options.
```
```

programs.numbat: add module

---

modules/files.nix
modules/lib/file-type.nix
modules/misc/mozilla-messaging-hosts.nix

#5381 But scoped to firefox and thunderbird
I don't know how to name this `home.file` option better and what description to write for it, suggestions are welcome.
```
```
@rycee @kira-bruneau @Lillecarl @mlyxshi @khaneliman

Fix firefox native messaging hosts with relative symlinks

---

modules/programs/bacon.nix

bacon: add prefs location to settings decription

---

docs/manual/nix-flakes.md
docs/manual/nix-flakes/flake-parts.md
flake-module.nix
flake.nix

closes https://github.com/nix-community/home-manager/issues/7016
```
```

[Backport release-24.11] flake-module: add flake-parts module

---

modules/programs/wayprompt.nix

Show that the hex values can be entered without the '0x' prefix.
```
```
@khaneliman @awwpotato

wayprompt: tweak example

---

modules/programs/halloy.nix
tests/modules/programs/halloy/example-config.nix
tests/modules/programs/halloy/my-theme.toml

follow up to https://github.com/nix-community/home-manager/pull/7034
cc @surfaceflinger 
```
```
@aguirre-matteo

halloy: add themes option

---

modules/programs/halloy.nix

halloy isn't functional if there aren't any servers configured, without any servers it fails with
```
Error reading configuration file
TOML parse error at line 1, column 1
missing field `servers`
```
```
```

halloy: add note about servers being required

---

modules/services/mako.nix
tests/modules/services/mako/default.nix
tests/modules/services/mako/deprecated-criteria.nix
tests/modules/services/mako/example-config.nix
tests/modules/services/mako/renamed-options-config
tests/modules/services/mako/renamed-options.nix

Follow up to https://github.com/nix-community/home-manager/pull/6977#issuecomment-2868993720
```
```

mako: settings better freeform support; deprecate criteria

---

.github/labeler.yml
modules/misc/news/2025/05/2025-05-12_15-21-57.nix
modules/modules.nix
modules/programs/foliate.nix
tests/default.nix
tests/modules/programs/foliate/basic-theme.nix
tests/modules/programs/foliate/default.nix

~I'm intentionally not including a settings option because it uses dconf and I don't want to deal with that right now.~ I did add a settings option but it's kinda hacky.
```
```

foliate: init

---

modules/programs/foliate.nix
tests/modules/programs/foliate/basic-theme.nix

turns out it needs `.json` on the end
```
```

foliate: fix theme settings example

---

modules/services/emacs.nix

Currently on Darwin, `services.emacs.defaultEditor = true` isn't respected, as the variable is only configured on Linux.
This PR simply moves the variable out to a common block, so it's applied on all platforms.
```
```
@tadfisher

emacs: respect `defaultEditor` on Darwin

---

modules/lib/darwin.nix
modules/lib/default.nix
modules/services/borgmatic.nix
modules/services/nix-gc.nix
tests/default.nix
tests/modules/services/borgmatic-darwin/basic-configuration.nix
tests/modules/services/borgmatic-darwin/default.nix
tests/modules/services/borgmatic-darwin/expected-agent.plist
tests/modules/services/borgmatic-darwin/frequency-assertion.nix
tests/modules/services/nix-gc-darwin/darwin-nix-gc-interval-assertion.nix
tests/modules/services/nix-gc-darwin/default.nix

On darwin, services.borgmatic should create a launchd agent.
```
```

Add initial support for borgmatic on darwin

---

modules/services/mako.nix

Closes https://github.com/nix-community/home-manager/issues/2028
```
```

Mako: provide dbus service file

---

modules/programs/rclone.nix
tests/integration/standalone/rclone/default.nix
tests/integration/standalone/rclone/mount.nix

rclone: declarative mounts

---

modules/services/borgmatic.nix
modules/services/nix-gc.nix

In https://github.com/nix-community/home-manager/pull/7066, a bug was introduced to the documentation of `nix.gc.frequency`.
```
```

Fix documentation of nix-gc

---

modules/lib/maintainers.nix
modules/misc/news/2025/05/2025-05-15_14-37-58.nix
modules/modules.nix
modules/programs/pgcli.nix
tests/default.nix
tests/modules/programs/pgcli/default.nix
tests/modules/programs/pgcli/empty-settings.nix
tests/modules/programs/pgcli/example-settings.nix

Init [`pgcli`](https://www.pgcli.com/) ([nixpkg](https://github.com/NixOS/nixpkgs/blob/75d6654eebd55b9264fbeac146e09f6726874c47/pkgs/development/python-modules/pgcli/default.nix)), allowing for simple configuration of the config through nix.
```
```

pgcli: init

---

nix-darwin/default.nix

This is important on multi-user systems for example:
```
{
home-manager.users.user1.home.activation.setDefaultBrowser = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
${lib.getExe pkgs.defaultbrowser} firefox
'';
home-manager.users.user2.home.activation.setDefaultBrowser = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
${lib.getExe pkgs.defaultbrowser} chrome
'';
}
```
If I run activation as `user1` then `user2`'s `defaultbrowser chrome` command will fail to work without the `launchctl asuser`.
See: https://github.com/nix-darwin/nix-darwin/pull/1341#discussion_r1989887502
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more …

nix-darwin: use `launchctl asuser` to get correct Mach bootstrap context

---

flake-module.nix

flake-module: use toString primop

---

modules/programs/yazi.nix

Yazi is deprecating init.lua for main.lua usages. This adds support for main.lua in plugins.
(cherry picked from commit 18fa9f323d8adbb0b7b8b98a8488db308210ed93)
Closes https://github.com/nix-community/home-manager/issues/7088
```
```

[Backport release-24.11] yazi: add main.lua support to plugins (#6394)

---

modules/services/home-manager-auto-expire.nix
tests/default.nix
tests/modules/services/home-manager-auto-expire-darwin/basic-configuration.nix
tests/modules/services/home-manager-auto-expire-darwin/default.nix
tests/modules/services/home-manager-auto-expire-darwin/expected-agent.plist
tests/modules/services/home-manager-auto-expire-darwin/frequency-assertion.nix

When on darwin, services.home-manager.autoExpire will now generate a launchd agent.
```
```
@thiagokokada

Add support for darwin to services.home-manager.autoExpire

---

modules/misc/fontconfig.nix
tests/modules/misc/fontconfig/no-font-package.nix

Make home-manager provide fontconfig's default config files in `home-path/etc/font`, this fixes and issue where fonts would render incorrectly if the system was not already providing the fontconfig default config files.
Using standalone hm, with fontconfig disabled in my NixOS config and enabled in hm, I have been experiencing font rendering issues in several programs, particularly in mako emojis would be oversized. This was due to fontconfig not being able to find its default config files that come with the package. This fixes that issue.
This change can be a starting point to then add all of the fontconfig options that NixOS provides in home-manager as well (as the implementation is similar so far).
``` …
```

fontconfig: Provide default fontconfig config files

---

modules/misc/gtk.nix

This adds `gtk.gtk2.force` enable option which maps directly onto `home.files.${cfg2.configLocation}.force` to allow overwrite of the `gtkrc-2.0` file (workaround for bug #6188).
```
```
@rycee

home-manager: add force option for gtk-2 config

---

modules/files/check-link-targets.sh

The new error message created in f8e6694 truncates the actual colliding files error within the systemd log, leading to a lot of confusion from newer Nix users. This fix moves the colliding files to the end, making it visible again.
```
warning: the following units failed: home-manager-iynaix.service
× home-manager-iynaix.service - Home Manager environment for iynaix
Loaded: loaded (/etc/systemd/system/home-manager-iynaix.service; enabled; preset: enabled)
Active: failed (Result: exit-code) since Tue 2024-06-04 08:46:52 +08; 52ms ago
Duration: 46min 26.136s
Process: 88527 ExecStart=/nix/store/7i0d80cp7l2f3kzphp2pgl75f8k9bqal-hm-setup-env /nix/store/zw7il0w4kc897jjm2mm4flvssm6s00hw-home-manager-generation (code=exited, status=1/FAILURE)
Main PID: 88527 (code=exited, status=1/FAILURE)
IP: 0B …
```

files: show colliding files at bottom in checkLinkTargets

---

modules/programs/direnv.nix

I'm running nightly nushell, where, after https://github.com/nushell/nushell/pull/15654, the direnv integration fails due to `default` behaving differently when passing a closure. 
The fix is more verbose and less idiomatic than the original code, but keeping it that way would require a version check, something like this:
```nix
''
| default ${
if (lib.versionAtLeast config.programs.nushell.package.version "0.104.1") then
"{ {|x| $x} }"
else
"{|x| $x}"
}
''
```
```
``` …

direnv: Fix `default` syntax for nushell integration

---

modules/misc/fontconfig.nix
tests/modules/misc/fontconfig/no-font-package.nix

This reverts commit 65d2282ff6cf560f54997013bd1e575fbd0a7ebf.
Due too #7098, reverting for now.
```
```

Revert "fontconfig: Fix missing default fontconfig files (#7045)"

---

modules/misc/news/2023/03/2023-03-16_00_12-00.nix

Noticed a warning about invalid timestamp in the logs of https://github.com/katexochen/hmnews-bot
```
```

news: fix timestamp

---

.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/issue.yaml

I'd like to tenure my resignation from maintainership of the home-manager project. I haven't been able to contribute nearly as much as I would have liked to over the last years.
Thank you for the opportunity to help maintain this great project. I will happily to continue to occasionally contribute as a normal contributor rather than a maintainer going forward.
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/m …

github: remove Sumner as automatic assignee on issues

---

modules/misc/news/2025/05/2025-05-24_18-18-40.nix
modules/modules.nix
modules/services/wayvnc.nix
tests/default.nix
tests/modules/services/wayvnc/default.nix
tests/modules/services/wayvnc/simple-config
tests/modules/services/wayvnc/simple.nix
tests/modules/services/wayvnc/simple.service

Module for [wayvnc](https://github.com/any1/wayvnc).
```
```

wayvnc: init

---

modules/misc/dconf.nix
tests/modules/home-environment/session-variables.nix

Dconf: Fix config section not appling correctly

---

modules/programs/superfile.nix

<https://superfile.netlify.app/list/plugin-list>
Metadata option requires `exiftool` to work.
```
```
@LucasWagler 
@mdaniels5757

superfile: add exiftool when metadata enabled

---

modules/services/window-managers/i3-sway/sway.nix
tests/modules/services/window-managers/sway/default.nix
tests/modules/services/window-managers/sway/sway-bindswitches.conf
tests/modules/services/window-managers/sway/sway-bindswitches.nix

Adds the bindswitches option to the sway module.
Bindswitches allows you to run a sway command when a state changes (when a certain event occurs).
See https://github.com/swaywm/sway/wiki#clamshell-mode and sway(5) for more information
It was already possible to configure this through sway.extraConfig but I find this approach dirty as described by the [Nix RFC 42](https://github.com/NixOS/rfcs/blob/master/rfcs/0042-config-option.md#part-1), and there is currently no settings as it describes.
- I copied the documentation from the man page, it should be fine in terms of license because sway is also using MIT
- This is my first contribution to Home Manager, so I'm not sure this is the right way to do it, but it works
- I tested this PR on my nixos configuration, and it works fine, see this …

sway: add bindswitches option

---

modules/lib/maintainers.nix
modules/modules.nix
modules/services/jellyfin-mpv-shim.nix
tests/modules/services/jellyfin-mpv-shim/default.nix
tests/modules/services/jellyfin-mpv-shim/jellyfin-mpv-shim-example-settings-expected-bindings
tests/modules/services/jellyfin-mpv-shim/jellyfin-mpv-shim-example-settings-expected-config
tests/modules/services/jellyfin-mpv-shim/jellyfin-mpv-shim-example-settings-expected-settings
tests/modules/services/jellyfin-mpv-shim/jellyfin-mpv-shim-example-settings.nix

Init of service jellyfin-mpv-shim, emulating plex-mpv-shim already provided.
```
```

jellyfin-mpv-shim: add module

---

modules/programs/fish.nix
tests/modules/programs/fish/binds.nix
tests/modules/programs/fish/default.nix

binds options that will be save in fish_user_key_bindings function
```
```

fish: add binds option

---

modules/xsession.nix

xsession: add xdg-desktop-autostart to requires of hm-graphical-session

---

modules/programs/yambar.nix

As discussed in https://github.com/nix-community/home-manager/pull/3353 it would be nice to have a yambar systemd service. This PR provides one.

yambar: add systemd service

---

modules/programs/kodi.nix

Allow `list` of `attrset` in the kodi settings to be able to define path substitutions.
```
```

kodi: make type for settings less restrictive

---

modules/misc/mozilla-messaging-hosts.nix
modules/programs/firefox.nix
modules/programs/firefox/mkFirefoxModule.nix
modules/programs/floorp.nix
modules/programs/librewolf.nix

Current native messaging hosts implementation do not support LibreWolf.
mkFirefoxModule links to `.mozilla/native-messaging-hosts` by default, but LibreWolf use their own paths for native messaging hosts, requiring users to create the symlink manually.[1] 
I tested this on Firefox, LibreWolf, and Floorp on my nixos machine but couldn't test darwin. Additionally, I did a bit of refactoring to reduce code duplication.
[1]: https://librewolf.net/docs/faq/#how-do-i-get-native-messaging-to-work
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information …

misc: add librewolf native messaging hosts

---

modules/misc/dconf.nix
tests/modules/home-environment/session-variables.nix

In some setups, this would cause missing Gio modules that cause e.g. Nautilus to not be able to view the XDG trash, and potentially other issues.
Fixes: ec8205c3 ("dconf: set env var")
Fixes: #7143
```
```

dconf: Fix Gio module variable breakage

---

modules/services/linux-wallpaperengine.nix
tests/modules/services/linux-wallpaperengine/default.nix
tests/modules/services/linux-wallpaperengine/null-options-expected.service
tests/modules/services/linux-wallpaperengine/null-options.nix

This fixes evaluation error "cannot coerce null to a string" when setting either `services.linux-wallpaperengine.clamping` or `assetsPath` to null or leave as default.   
I received an email notification from @ccalhoun1999 from my mailbox, but I didn't see their comment on the original pull request, so I'll mention them here for reference.   
```
```
myself

linux-wallpaperengine: Fix evaluation error when passing null as options

---

.github/workflows/backport.yml
.github/workflows/update-flake.yml

As I was recently adding this workflow to Nixvim, I figured home-manager would benefit too.
Adds a GitHub workflow to create backport PRs when merged PRs have a "backport" label.
This uses the very flexible https://github.com/korthout/backport-action and is based on the [workflow used by nixpkgs](https://github.com/NixOS/nixpkgs/blob/2566f9dc/.github/workflows/backport.yml), which is also [used by Stylix](https://github.com/nix-community/stylix/blob/0512b0f/.github/workflows/backport.yml) and [most recently, Nixvim](https://github.com/nix-community/nixvim/pull/3411). See [how it works](https://github.com/korthout/backport-action#how-it-works).
Currently, the workflow [will assume](https://github.com/korthout/backport-action#label_pattern) that backport labels follow the regex `backport …

ci: add backport workflow

---

.github/workflows/backport.yml

ci: fix backport if condition

---

.github/workflows/backport.yml

Followup to:
- #7167
- #7165
Ideally, the if condition checks that the necessary vars are available. This allows testing workflows on a fork of the repo, by first configuring required vars and secrets.
However it that's not possible, due to _secrets_ always being "falsy" and not having any _vars_, we can explicitly check this is not a fork using `github.repository_owner == 'nix-community'`.
This is a better solution than dynamically checking in a step, as it avoids running any jobs at all. This also avoids a "failure" if the workflow is accidentally run on a fork, because `if` conditions are considered neutral.
``` …
```

ci: alternative fix for backport if condition

---

.github/workflows/test.yml
lib/default.nix
modules/lib/stdlib-extended.nix

{ci,lib}: remove 22.11 deprecations

---

modules/misc/news/2024/12/2024-12-08_17-22-13.nix
modules/misc/news/2024/12/2024-12-10_22-20-10.nix
modules/misc/news/2024/12/2024-12-21_17-07-49.nix
modules/misc/news/2024/12/2024-12-22_08-24-29.nix
modules/misc/news/2025/01/2025-01-01_15-31-15.nix
modules/misc/news/2025/01/2025-01-01_23-16-35.nix
modules/misc/news/2025/01/2025-01-02_11-21-19.nix
modules/misc/news/2025/01/2025-01-04_15-00-00.nix
modules/misc/news/2025/01/2025-01-21_17-28-13.nix
modules/misc/news/2025/01/2025-01-26_16-40-00.nix
modules/misc/news/2025/01/2025-01-29_17-34-53.nix
modules/misc/news/2025/01/2025-01-29_19-11-20.nix
modules/misc/news/2025/01/2025-01-30_09-18-55.nix
modules/misc/news/2025/02/2025-02-07_22-31-45.nix
modules/misc/news/2025/02/2025-02-11_15-25-26.nix
modules/misc/news/2025/02/2025-02-12_15-56-00.nix
modules/misc/news/2025/02/2025-02-16_17-00-00.nix
modules/misc/news/2025/02/2025-02-20_18-39-31.nix
modules/misc/news/2025/02/2025-02-21_16-53-20.nix
modules/misc/news/2025/02/2025-02-22_16-46-56.nix
modules/misc/news/2025/02/2025-02-22_16-53-20.nix
modules/misc/news/2025/03/2025-03-11_02-34-43.nix
modules/misc/news/2025/03/2025-03-19_18-10-56.nix
modules/misc/news/2025/03/2025-03-24_15-29-33.nix
modules/misc/news/2025/03/2025-03-24_22-31-45.nix
modules/misc/news/2025/03/2025-03-29_04-16-57.nix
modules/misc/news/2025/03/2025-03-31_16-39-41.nix
modules/misc/news/2025/04/2025-04-02_00-00-00.nix

During migration to new format and removing from the inline files. We lost some entries.
```
```

news: re-add dropped news entries

---

.github/workflows/backport.yml
.github/workflows/update-flake.yml

Followup to #7165.
Workflows will now push to PRs as a "bot user" (GitHub App), which will still trigger CI. This is more idiomatic than a "machine" user which is in reality a normal user account.
Its tokens are short lived, so more secure than a PAT that doesn't expire.
This PR is **blocked** by a GitHub App being created for Home Manager and the relevant APP ID and PRIVATE KEY being added to the repo's vars and secrets respectively. A nix-community admin will be able to do this, see [previous matrix thread](https://matrix.to/#/!PbtOpdWBSRFbEZRLIf:numtide.com/$copbS2S4-Jk8Cqvp-DFkZtxfdwmUUPWV1edITMvSnIA?via=matrix.org&via=envs.net&via=nixos.dev) for an example.
Additionally, I've improved the PR body for the update workflow.
`nix-shell -p treefmt nixfmt-rfc-style keep-sorted --run …

ci: switch to a GitHub App

---

.github/workflows/test.yml
tests/default.nix
tests/flake.nix

Talked about in matrix a while back, kept forgetting to implement. Annoying to have unexpected CI failures before a flake lock update. 
```
```

ci: use flake lock for tests 

---

modules/programs/fzf.nix

fzf version 0.53.0 and later now prefers using `source` for its Zsh integration. - https://github.com/junegunn/fzf/pull/3794
Also updated in homebrew. - https://github.com/Homebrew/homebrew-core/pull/172980
This PR only updates the Zsh part of 0.48.0 integrations - https://github.com/nix-community/home-manager/pull/5239
```
```
@khaneliman

fzf: prefer `source` for Zsh integration

---

docs/manual/nix-flakes/prerequisites.md

`nix.package = nixFlakes` isn't necessary for a couple of years anymore… Basically since the release of 2.4…
Also `nix.settings` is prefered over `nix.extraOptions` for at least a year as well now.
```
```

doc: fix instructions for enabling flakes in NixOS

---

modules/services/dwm-status.nix

This turns of verbose logging such as printing that the time has updated every second.
~~Depends on https://github.com/NixOS/nixpkgs/pull/411463~~
```
```

dwm-status: run with --quiet

---

modules/misc/xdg-desktop-entries.nix

The links were previously outdated, and even though they didn't 404, they did not point to the relevant section.
```
```
@cwyc

xdg.desktopEntries: Update outdated links in docs

---

modules/modules.nix
modules/programs/aichat.nix
tests/darwinScrublist.nix
tests/default.nix
tests/modules/programs/aichat/default.nix
tests/modules/programs/aichat/settings.nix
tests/modules/programs/aichat/settings.yml

[aichat](https://github.com/sigoden/aichat) is an all in one CLI tool for AI interactions.
On first run it prompts you to create a config so I made a home manager module to do this declaratively.
```
```

aichat: init

---

modules/misc/dconf.nix
tests/modules/home-environment/session-variables.nix

Providing dconf via hm in this manner provided to be problematic for  user with systems that were already providing dconf (like ubunut).
Revert ff73544e4a59dce43a6de7051858a453186ae9bb
Fixes #7193
```
```

dconf: revert: dconf: Provide dconf

---

modules/misc/dconf.nix
tests/modules/home-environment/session-variables.nix

revert: dconf: Provide dconf (Backport)

---

modules/services/jellyfin-mpv-shim.nix

jellyfin-mpv-shim can't read its configuration file if it's not writeable (see https://github.com/nix-community/home-manager/pull/7129#issuecomment-2925542595).
or `nix build --reference-lock-file flake.lock ./tests#test-all` using Flakes.  
I can't run the tests on my platform (`aarch64-linux`).
```
```
@repparw

jellyfin-mpv-shim: make sure the config file is read properly

---

modules/programs/zsh.nix
tests/modules/programs/zsh/default.nix
tests/modules/programs/zsh/plugins.nix

Autocompletion scripts and additional plugin functions are located in specific directories that might not match the plugin source script but need to be included in fpath before calling compinit.
An option to provide a path to these scripts is added to add the paths to fpath before calling completionInit.
Closes https://github.com/nix-community/home-manager/pull/5458
```
```
- If this PR adds a …

zsh: add plugins.*.completions paths to fpath

---

modules/programs/zed-editor.nix
tests/modules/programs/zed-editor/extensions.nix
tests/modules/programs/zed-editor/keymap.nix
tests/modules/programs/zed-editor/settings.nix

Merges frozen config from HM into dirty config.
Fixes https://github.com/nix-community/home-manager/issues/6835
```
```
@libewa

zed-editor: respect user interactivity with settings and keymaps

---

modules/programs/chawan.nix

as per cha-config, keybindings should be under section `page` and not `pager`.
Also replaced an example for duckduckgo search because current one wasn't working properly
```
```
@Noodlez1232

chawan: fix example for settings

---

lib/default.nix

Using ./. forces Nix to copy the flake to the store a second time. Using builtins.path like this, forcing the name to be "source", reduces the extraneous copy.
ref:
```
warning: Copying '/nix/store/b3sj22x9pqf3dyw0409dhpzwi9vswwx7-source' to the store again
You can make Nix evaluate faster and copy fewer files by replacing `./.` with the `self` flake input, or `builtins.path { path = ./.; name = "source"; }`
Location: /nix/store/b3sj22x9pqf3dyw0409dhpzwi9vswwx7-source/lib/default.nix:23:68
```
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more …

lib/default.nix: remove inefficient second copy

---

modules/programs/zed-editor.nix

zed-editor: userKeymaps default to empty array

---

modules/programs/ghostty.nix

The ghostty [script](https://github.com/ghostty-org/ghostty/blob/269d29624bb91066ee75558a81c0cac609d080e6/src/shell-integration/fish/vendor_conf.d/ghostty-shell-integration.fish) adds hooks that are only relevant in an interactive shell session.
```
```
- @HeitorAugustoLN
- @khaneliman

ghostty: only source fish shell integration script when shell is interactive

---

modules/services/hypridle.nix

Added `systemdTarget` option to `hypridle`. It's the same as in neighbor module `swayidle`.
```
```
@khaneliman @fufexan

hypridle: add systemdTarget option

---

tests/integration/standalone/alice-home-init.nix
tests/integration/standalone/home-with-symbols-init.nix
tests/integration/standalone/nh.nix

They previously failed. I'm not sure why the nh test no longer picks up the activation script output but at least it seems to get activated.
```
```

home-manager: fix integration tests

---

modules/programs/neovim.nix
tests/modules/programs/neovim/plugin-config.expected
tests/modules/programs/neovim/plugin-config.nix

Fix an issue where the generated `~/.config/nvim/init.lua` lacks a newline after the `vim.cmd [[source ...]]` directive. Without this newline, subsequent lua configuration is concatenated onto the same line, breaking lua syntax.
`init.lua` Before:
```
vim.cmd [[source /nix/store/...]]vim.opt.rtp:prepend(...)
```
After:
```
vim.cmd [[source /nix/store/...]]
vim.opt.rtp:prepend(...)
```
@khaneliman

fix: ensure newline after vim.cmd[[source...]] in neovim init.lua

---

.github/labeler.yml

ci: fix bars labeler

---

modules/programs/meli.nix
tests/modules/programs/meli/expected.toml

these hardcoded freeformat settings dont add anything over the default, worse they generate empty sections which can then clash with user included config (my usecase). It's best to move those to example.
```
```

meli: move freeformat settings to example

---

.github/labeler.yml
modules/programs/meli.nix

Fixes https://github.com/nix-community/home-manager/issues/7261
```
```

fix meli eval warning 

---

modules/programs/atuin.nix

This change fixes the URLs for the atuin docs since the old ones either redirect or land on a 404 page.
It only touches option descriptions and does not include any functional changes.
@hawkw
@water-sucks

atuin: fix docs url

---

modules/services/way-displays.nix

This is good for when displays are not considered part of the home configuration and are instead considered ephemeral.
Great for laptops but I use it for my desktop as well.
```
```
@jolars

way-displays: support stateful configuration file

---

modules/programs/sketchybar.nix

Since we're creating a new derivation, we drop the original package attributes. Add our own meta.mainProgram to resolve those warnings.
```
```

sketchybar: add meta.mainProgram to finalPackage

---

.github/workflows/labeler.yml

Should resolve issue with needing to create labels. Related https://github.com/actions/labeler/issues/870
```
```

ci: labeler issues permission

---

modules/lib/strings.nix

Added PascalCase support for lib.hm.strings.toCaseWithSeperator 
```
```
@khaneliman

lib/strings: add PascalCase support for toCaseWithSeperator

---

modules/programs/firefox/profiles/bookmark-types.nix
modules/programs/firefox/profiles/bookmarks.nix
tests/modules/programs/firefox/profiles/bookmarks/default.nix
tests/modules/programs/firefox/profiles/bookmarks/expected-bookmarks.html

Allow users to put separators in their bookmarks
Closes #6312
```
```

firefox: allow separators in bookmarks

---

modules/programs/hyprlock.nix
modules/services/hypridle.nix
modules/services/hyprpaper.nix
modules/services/window-managers/hyprland.nix

As I noticed in <https://github.com/nix-community/home-manager/pull/7277#issuecomment-2985781610>, it seems hyprland changed its domain name from `hyprland.org` to `hypr.land`. (The old domain redirects to the new one).
These changes are made by the following:
```
find . \( -type d -name .git -prune \) -o -type f -print0 | xargs -0 sed -i 's/hyprland\.org/hypr.land/g'
```
```
```
- If this PR …

hyprland: update wiki domain name

---

modules/programs/helix.nix
tests/modules/programs/helix/default.nix
tests/modules/programs/helix/only-extraconfig-expected.toml
tests/modules/programs/helix/only-extraconfig.nix

Fix so that you can still generate `programs.helix.extraConfig` without using `programs.helix.settings`. Useful particularly in the case of `extraConfig = lib.readFile ./config.toml;`.
My test code passes:
```
/aux/code/home-manager> nix build --reference-lock-file flake.lock "./tests#test-helix-only-extraconfig"
```
I get an unrelated error trying to run the entire test suite.
```
error: builder for '/nix/store/0ahpc06wbspycw9ih4i0r2kg8p7khh88-nmt-test-firefox-profiles-bookmarks-attrset.drv' failed with exit code 1;
last 11 log lines:
> Expected /nix/store/j2avbbv232xh00ldmd9ycl0dbpik5hqn-bookmarks.html to be same as /nix/store/iiz9myl298nqpm9hbidr8p6hmqvkzapb-expected-bookmarks.html but were different:
> --- …
```

helix: don't ignore extraConfig when no other settings

---

modules/services/way-displays/default.nix

Closes #7296. Thanks for the suggested fix, @teto. The fix works locally for me.
```
```

way-displays: use `mkOptionDefault` in `systemd.variables`

---

modules/programs/hyprpanel/default.nix
tests/modules/programs/hyprpanel/basic-config.json
tests/modules/programs/hyprpanel/basic-config.nix
tests/modules/programs/hyprpanel/default.nix
tests/modules/programs/hyprpanel/with-hypridle.json
tests/modules/programs/hyprpanel/with-hypridle.nix

https://github.com/Jas-SinghFSU/HyprPanel: Bar/Panel for Hyprland with extensive customizability (https://github.com/NixOS/nixpkgs/pull/379994)
I have been daily driving everything from this PR since the 2025 new year, so everything is pretty well tested
```
```
CC @JohnRTitor

programs/hyprpanel: init

---

modules/programs/aerospace.nix
tests/modules/programs/aerospace/aerospace-service-expected.plist
tests/modules/programs/aerospace/aerospace.nix

This commit introduces a `launchd` agent to automatically start AeroSpace at login, significantly improving its integration.
Solve issue #6725 
```
```

aerospace: Add launchd agent and enhance configuration

---

modules/services/syncthing.nix

We have a configuration option `services.syncthing.guiAddress` which is an explicit option because we need it in the syncthing-init service, but why not _also_ set it in the actual syncthing config as well as (or instead of?) the current CLI override? This way other software that parses the config file / REST API like syncthingtray just works with it instead of erroring out and unexpectedly requesting user interaction.
I guess we could actually also scrap the explicit `services.syncthing.guiAddress` option in favor of the syncthing-native `services.syncthing.settings.gui.address` because these two (valid!) options conflict otherwise.
Also, a next PR (or addition to this one) could be to make sure the `syncthing-init` service treats `services.syncthing.settings.gui` differently by not …

Add guiAddress to syncthing configuration

---

home-manager/home-manager
home-manager/home-manager.nix

I keep finding myself wanting to inspect the computed result of my Home Manager config. NixOS has `nixos-rebuild repl`, which launches the REPL with the NixOS configuration already loaded; it's essentially a shortcut for `nix repl --file '<nixos/nixos>'`.  This PR adds similar function to `home-manager`.
No tests, as this is fundamentally an interactive user-facing tool command that doesn't lend itself well to automated testing. All the existing tests pass, except for the "Argument list too long" error I also saw in #5576, which (a) I'm confident isn't related and (b) I'm now investigating separately.
Similar to the `nixos-rebuild repl` command, `home-manager repl` will launch the Nix read-evaluate-print-loop environment with the Home Manager configuration loaded.
To make that more …

home-manager: add repl subcommand

---

modules/programs/direnv.nix

Since version 0.105.0, cell-paths are case-sensitive by default, since the record we are using is lowercase it doesn't convert `$env.PATH`.
Alternatively, instead of making it uppercase, we could build an actual `cell-path` value instead of relying on the string value of `$key`, which would comply with `$env` remaining a case-insensitive record (this also seems backwards compatible).
```nu
let key_path = [ # becomes $.<key>!
[value, optional, insensitive];
[$key, false, true]
]
get -i $key_path
```
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for …

direnv: fix nushell cell-path handling

---

.github/workflows/test.yml

Not every PR requires the overhead of spinning up runners and running our entire test suite. Filter on paths affected and only run the relevant steps/jobs.
Would rather just split up into multiple jobs ala https://github.com/nix-community/home-manager/pull/6539 but I can't change the checks on repo so just doing conditional steps. 
```
```

ci: conditional test step runs

---

.github/workflows/update-flake.yml

Make it easier to distinguish which flake.lock update a pr is for.
```
```

ci: prefix flake update prs

---

modules/programs/mpvpaper.nix

Currently just enabling the module with `programs.mpvpaper.enable = true;` will cause an error:
```
error: The option `xdg.configFile."mpvpaper/pauselist".source' was accessed but has no value defined. Try setting the option.
```
The fix will not attempt to evaluate the config files if no settings for stopList and pauseList are set.
```
```
@aguirre-matteo

mpvpaper: fix eval if no settings are defined

---

modules/programs/kitty.nix

Add the signal to darwin to allow for kitty config update durring activation
```
```

kitty: add config change signal on darwin

---

.github/workflows/test.yml

Group by branch and cancel existing queued runs when a new push happens so we don't unnecessarily run jobs that are irrelevant.
```
```

ci: add concurrency to test workflow

---

.github/workflows/tag-maintainers.yml

Was relying on flawed logic and fragile parsing to identify maintainers on changed files. Rework to use nix eval to grab the `meta.maintainers` to use when requesting a review.
```
```

ci: tag-maintainers fix fetching maintainers

---

.github/workflows/tag-maintainers.yml

Tested https://github.com/khaneliman/home-manager/pull/575
Make sure we properly request reviews on PR opening, reopening, changes made to files, etc. Also remove reviewers that are no longer relevant. Fixes issue where a PR that opens doesn't tag reviewers and requires toggling between draft and reopening again. 
```
```

ci: maintainer pings refactor

---

modules/services/podman-linux/default.nix
tests/modules/services/podman-linux/configuration-mounts-expected.conf
tests/modules/services/podman-linux/configuration.nix

podman: support mounts configuration

---

modules/misc/news/2025/06/2025-06-14_21-49-02.nix
modules/programs/anki/default.nix
modules/programs/anki/helper.nix
tests/modules/programs/anki/default.nix
tests/modules/programs/anki/full-config.nix
tests/modules/programs/anki/minimal-config.nix

Anki is a popular spaced repetition flashcards learning program. This PR introduces a module for configuring Anki settings and add-ons. It is the counterpart to my [nixpkgs PR](https://github.com/NixOS/nixpkgs/pull/404045) that has now reached unstable. ~~Home Manager's flake.lock is currently too out of date for this. #7273~~
Because of how Anki's configuration is stored, I was not able to add anything like `extraConfig`. That's why there are so many options. I've used official Anki APIs wherever possible to prevent breakage; it has worked for many months for me without issue.
Addons added with `programs.anki.addons` don't seem to show up when Anki is built via tests but do in normal usage. I'm not sure why.
or `nix build …

anki: add module

---

modules/programs/numbat.nix
tests/modules/programs/numbat/default.nix
tests/modules/programs/numbat/empty-config.nix
tests/modules/programs/numbat/example-config.nix
tests/modules/programs/numbat/external-initfile.nix
tests/modules/programs/numbat/init.nbt

This PR picks up where #7159 left off, providing an `initFile` option for `programs.numbat` to allow the user to supply custom units, functions, and constants for Numbat to use.
The first commit in this PR implements this using just (`lib.types.nullOr`) `lib.types.lines`; the second additionally allows specifying a path to the `init.nbt` file to use as a source. Though I was drawn to `lib.hm.types.sourceFileOrLines` initially, it has some extra logic around directories that is unnecessary (and perhaps confusing) for this.
```
```
See …

Numbat: add initFile

---

modules/programs/opencode.nix
tests/modules/programs/opencode/config.json
tests/modules/programs/opencode/default.nix
tests/modules/programs/opencode/settings.nix

This PR adds an opencode module that is compatible with opencode v0.1.194.
```
```

opencode: init

---

modules/programs/firefox/mkFirefoxModule.nix

Adds the `release` option to declare what upstream release version is used to fetch rom `releases.mozilla.org`. Used to fetch language packs. See https://github.com/nix-community/home-manager/issues/6758#issuecomment-2781465236. 
Closes #6758
```
```
@getchoo @brckd @HPsaucii

firefox: add release option

---

modules/services/window-managers/i3-sway/lib/options.nix

Currently, we aggressively limit what modifier can be used in the module system that blocks valid configurations. Allow any strings to unblock these configs. But, could be refactored further to support list of modifiers and automatically convert to a config string.
Closes https://github.com/nix-community/home-manager/issues/4838
```
```

i3-sway/lib: modifier accepts any string

---

modules/programs/firefox/mkFirefoxModule.nix
modules/programs/librewolf.nix
tests/modules/programs/firefox/profiles/bookmarks/default.nix

Closes https://github.com/nix-community/home-manager/issues/5821
Closes https://github.com/nix-community/home-manager/issues/6852
```
```

mkFirefoxModule: set NoDefaultBookmarks when bookmarks are enabled; librewolf: allow bookmark configuration

---

.github/ISSUE_TEMPLATE/issue.yaml

Needless spam and doesn't really make sense to default to repo maintainers. Also, clearly hasn't been utilized for a long time. Also makes it really hard to see when an issue is ACTUALLY being worked on by someone. 
```
```

issue_template: remove assignees

---

modules/programs/wlogout.nix

Allows the wlogout style to be set when merging multiple modules - same as waybar
```
```

wlogout: use lines for css style

---

modules/programs/neomutt/default.nix

If there's an account under `accounts.email.accounts` with `neomutt.enable` set to true but neither `passwordCommand` nor `neomutt.sendMailCommand` set, then building the Neomutt rc file will fail.  Ensure that failure has a useful error message, rather than a confusing type error.
While we're here, make the module code slightly less repetitious by just building the set of email accounts that have Neomutt enabled once, rather than multiple times in multiple contexts.
or `nix build --reference-lock-file flake.lock ./tests#test-all` using Flakes. (See #7412 for failures with the non-flake test, and #7413 for failures on aarch64-linux, but flake test passes on x86_64-linux.)
- ~[ ] Test cases updated/added. See …

Improve error when failing to build Neomutt config

---

modules/services/hyprshell.nix
tests/modules/services/hyprshell/config.json
tests/modules/services/hyprshell/default.nix
tests/modules/services/hyprshell/example-config.nix
tests/modules/services/hyprshell/style.css

This pull request adds a module for configuring Hyprshell. Closes #7290.
```
```

hyprshell: add module

---

modules/programs/lutris.nix
tests/modules/programs/lutris/default.nix

Marked the lutris module as x86_64-linux only for now since the upstream package uses many x86_64 only applications.
I'm unsure if this is the right way to do this, I couldn't find any references.
Should fix #7413.
```
```

lutris: make module x86_64-linux only

---

modules/programs/firefox/mkFirefoxModule.nix
tests/modules/programs/firefox/common.nix
tests/modules/programs/firefox/profiles/extensions/assertions.nix

Adds extension permissions as suggested in #7001. Adds the 'profiles.<name>.extensions.settings.<name>.permissions' to Firefox derivatives. If set, this option adds an assertion that fails if an extension package requests permissions that weren't added to the permissions option. In order to not require 'profiles.<name>.extensions.force' to be set when only permissions, but no extension settings were defined, the relevant assertions were changed. They now check whether any 'extensions.settings.<name>.settings' was set instead of checking whether 'extensions.settings' was set. Closes #7001.
``` …
```

firefox: add extension permissions

---

modules/programs/trippy.nix
tests/modules/programs/trippy/default.nix
tests/modules/programs/trippy/example-config.nix
tests/modules/programs/trippy/trippy.toml

This pull request adds a module for configuring [trippy](https://github.com/fujiapple852/trippy).
```
```

trippy: add module

---

modules/services/cliphist.nix

Use lib.getExe.
I am using a drop in replacement for cliphist, this way it won't hard code the binary name.
```
```
@Janik-Haag @khaneliman

cliphist: use lib.getExe

---

modules/misc/gtk/gtk2.nix

Missed during migration
Follow up to https://github.com/nix-community/home-manager/pull/7349#issuecomment-3063439781
```
```

gtk2: fix missing force option

---

modules/programs/vscode/default.nix
tests/modules/programs/vscode/default.nix
tests/modules/programs/vscode/mcp.nix

Add an option to define mcp configuration in it's own file (separate from settings) as [required by VS Code 1.102](https://code.visualstudio.com/updates/v1_102#_mcp-migration-support).
VS Code 1.102 separates MCP configuration from `settings.json` to a profile-specific `mcp.json`. VS Code automatically performs this separation if MCP configuration is detected inside `settings.json` which conflicts with the immutability of the settings.json that home-manager supplies.
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent …

vscode: enable defining `mcp.json` separate from `settings.json`

---

home-manager/home-manager

Extend the `home-manager repl` command to support flakes.  This is heavily based on the equivalent `nixos-rebuild repl` code.
I originally wrote the `home-manager repl` command without support for flakes, because I wasn't using them.  Now I am, and I wanted flake support, so I added it.
```
```
No obvious maintainer, but tagging @khaneliman as the person …

home-manager: add flake support for repl command

---

modules/programs/zellij.nix
tests/modules/programs/zellij/default.nix
tests/modules/programs/zellij/layout.nix

Adds a layouts option to support generating layout files for zellij to use.
closes https://github.com/nix-community/home-manager/issues/4485
```
```

zellij: add support for layouts generation

---

tests/integration/standalone/alice-home-init.nix
tests/integration/standalone/home-with-symbols-init.nix
treefmt.toml

These were removed as part of dead code removal, but they are actually needed in the integration tests for comparing with the configuration generated by the installation.
```
```

tests: re-add module argument

---

modules/programs/gurk-rs.nix

https://github.com/nix-community/home-manager/pull/7466#issuecomment-3067369495
```
```

gurk-rs: fix missing s in home.packages

---

modules/services/dunst.nix

Added Install field for systemd service, which is needed for autostart to work properly under compositors launched under UWSM
```
```

dunst: UWSM compatibility

---

tests/modules/services/wayfire/configuration.ini
tests/modules/services/wayfire/configuration.nix

The `configuration.nix` test was failing on aarch-64. ~~I'm not sure this is the cleanest way to fix this, wavnc seems to get the `/nix/store/00000000000000000000000000000000-dummy` by default? See [here](https://github.com/nix-community/home-manager/blob/master/tests/modules/services/wayvnc/simple.nix#L5) and [here](https://github.com/nix-community/home-manager/blob/master/tests/modules/services/wayvnc/simple.service#L5)~~
Closes #7477
```
``` …

wayfire: fix broken configuration.ini test

---

.github/workflows/tag-maintainers.yml

accidentally broke when refactoring
```
```

ci: fix tag-maintainers

---

.github/workflows/github_pages.yml

Limit to only forks and allow ad-hoc runs.
```
```

ci: dont run github_pages on forks

---

modules/programs/starship.nix
tests/modules/programs/starship/settings.nix

The reason for doing this is so that when you use `sudo su`, you can pass that env variable to the root shell to have the same terminal prompt as the current user.
Docs: <https://starship.rs/config/#config-file-location>
```
```

starship: set `STARSHIP_CONFIG` var and add option to set config path

---

modules/programs/radio-cli.nix
tests/modules/programs/radio-cli/config.json
tests/modules/programs/radio-cli/default.nix
tests/modules/programs/radio-cli/example-config.nix

This PR adds a module for configuring [radio-cli](https://github.com/margual56/radio-cli).
```
```

radio-cli: add module

---

modules/programs/zed-editor.nix
tests/modules/programs/zed-editor/default.nix
tests/modules/programs/zed-editor/tasks-empty.nix
tests/modules/programs/zed-editor/tasks.nix

Just like other features, they can merge with preexisting JSON5
settings.

zed-editor: support tasks

---

modules/programs/neomutt/default.nix

If neither neomutt.sendMailCommand nor passCmd are set, leave configuration for sending emails unset.  This will leave neomutt to manage sending emails itself, which matches the existing description of the `accounts.email.accounts.<name>.neomutt.sendMailCommand` configuration option.
This also removes the assertion added in #7414 / bd680a8c (neomutt: allow default email sending behaviour, 2025-07-12), since it is now valid to have neither passCmd nor neomutt.sendMailCommand on an account.
- ~[ ] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d …

neomutt: allow default email sending behaviour

---

modules/programs/yarn/default.nix
tests/modules/programs/yarn/default.nix
tests/modules/programs/yarn/empty-config.nix
tests/modules/programs/yarn/example-config.nix
tests/modules/programs/yarn/example-config.yml

This PR adds a yarn module allowing to write the .yarnrc file in the home directory of a user
```
```

yarn: add module

---

modules/programs/trippy.nix
tests/modules/programs/trippy/example-config.nix

This pull request adds the option `programs.trippy.forceUserConfig`. Closes #7471.
```
```

trippy: add forceUserConfig option

---

modules/services/mpd.nix

mpd: fix typo

---

modules/misc/xdg-terminal-exec.nix

port xdg.terminal-exec from nixos to hm
```
```

xdg-terminal-exec: init

---

modules/home-environment.nix

I do not fully understand how dependency tracking (build time vs "runtime") works but this implementation copied the nixpkgs mechanism so should be fine *if* `home.activationPackage` is the analogue of `baseSystem` in nixos/modules/system/activation/top-level.nix. (https://github.com/NixOS/nixpkgs/blob/f859c5d293108245d6a364ce679f6f3cf15c1f4c/nixos/modules/system/activation/top-level.nix#L57-L77)
Note for nixpkgs implementation: `system.checks` becomes part of `system.systemBuilderArgs` which is passed as an argument to `baseSystem = pkgs.stdenvNoCC.mkDerivation ...`.
This should have the same effect `system.checks` has in nixpkgs: adds paths to the build closure without being becoming part of the generated configuration.
This is useful for built-time checks as these should not leave a …

home-environment: add `home.checks`

---

modules/programs/command-not-found/command-not-found.pl
modules/programs/command-not-found/default.nix

Updates command-not-found.pl and adds fish compatibility.
I think nix-index needs to be updated since this adds fish compatibility, would appreciate some advice here.
https://github.com/nix-community/home-manager/blob/d0300c8808e41da81d6edfc202f3d3833c157daf/tests/modules/programs/nix-index/integrations.nix#L15-L18
https://github.com/nix-community/home-manager/blob/d0300c8808e41da81d6edfc202f3d3833c157daf/tests/modules/programs/nix-index/assert-on-command-not-found.nix#L10-L13
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and …

command-not-found: sync with nixpkgs

---

modules/programs/docker-cli.nix
modules/programs/yarn/default.nix
tests/modules/programs/docker-cli/empty-config.nix
tests/modules/programs/docker-cli/example-config.nix

- docker-cli and yaar: Fix example text
- docker-cli: Set DOCKER_CONFIG env to the path of the config files instead of a single file
- docker-cli: Separate path to folder and config name
- docker-cli: Update tests
```
```

docker-cli and yarn: fixups

---

lib/nix/extract-maintainers.nix
lib/python/extract-maintainers.py

Currently, we send all files as a list but it can be problematic with files that can't be evaluated properly. Instead of crashing the entire extraction process, we will send a file at a time for eval so we can just bypass files causing issues.
```
```

ci: extract maintainers with single file eval

---

modules/misc/nixgl.nix
modules/programs/ashell.nix
modules/programs/chromium.nix
modules/programs/codex.nix
modules/programs/firefox/mkFirefoxModule.nix
modules/programs/hyprlock.nix
modules/programs/keychain.nix
modules/programs/obsidian.nix
modules/programs/swayr.nix
modules/programs/vscode/default.nix
modules/programs/yambar.nix
modules/services/cliphist.nix
modules/services/hyprshell.nix
modules/services/window-managers/hyprland.nix
modules/services/window-managers/i3-sway/lib/options.nix
modules/services/window-managers/i3-sway/sway.nix
modules/services/wlsunset.nix

Tested with rebased
https://github.com/nix-community/home-manager/pull/6411 so I could find all instances of config usage in docs.
```
```

treewide: remove config dependency on docs

---

modules/misc/xdg-terminal-exec.nix
modules/modules.nix
modules/programs/opencode.nix

Make sure xdg-terminal-exec module is imported (see #7527). Also minor option description fixes.
```
```
@nukdokplex

Various minor fixes

---

docs/default.nix
nixos/common.nix

This fixes a few modules such that their documentation no longer depends on `config`. To reduce the risk of similar problems in the future this PR also introduces a "poison module" when building documentation. The poison module will abort the documentation build if a reference is made to any attribute inside `config` other than `_module`.
```
```

docs: reduce dependencies on user's configuration

---

modules/programs/zsh/plugins/default.nix

Fixes a regression from https://github.com/nix-community/home-manager/pull/7442 that caused plugins to be deployed to the home directory even if zsh itself wasn't actually enabled
I kept this `cfg.enable` guard scoped to the `home.file` definition, as the other `programs.zsh` options touched here are already guarded correctly
```
```
@khaneliman (not …

zsh: only apply plugins when zsh is enabled

---

lib/python/manage-reviewers.py

Try to prevent issue occurring in https://github.com/nix-community/home-manager/pull/7575 with CI re-adding someone over and over. I thought I handled this already, but seemed to be a flaw in logic. 
```
```

ci: manage reviewers add dry run option; ci: manage reviewers doesn't re-add manually removed reviewers

---

modules/services/arrpc.nix
tests/modules/services/arrpc/custom-target-expected.service
tests/modules/services/arrpc/custom-target.nix
tests/modules/services/arrpc/default.nix

arrpc: assert linux; tests/arrpc: enhance service module test coverage

---

modules/services/window-managers/hyprland.nix
tests/modules/services/hyprland/simple-config.conf
tests/modules/services/hyprland/simple-config.nix

Add "output" to `importantPrefixes` option default to support `monitorv2` Hyprland syntax.
Fixes #7230.
Expand `test-hyprland-simple-config` to include a `monitorv2` option.
```
```
@fufexan

hyprland: Add `"output"` to `importantPrefixes` option default

---

modules/services/udiskie.nix

Fixes an assertion warning when building the udiskie systemd service with default package, as `pkgs.udiskie` doesn't have a default executable.
```
```

udiskie: fix getExe warning

---

nixos/default.nix
tests/integration/nixos/basics.nix

It was a bit too ambitious to also remove production of the gcroot, we need it to keep track of the currently active Home Manager configuration.
Fixes #7583
```
```

home-manager: re-enable gcroot handling for NixOS module

---

modules/programs/nh.nix
tests/modules/programs/nh/darwin/config.nix
tests/modules/programs/nh/linux/config.nix

nh provides an environment variable setting for defining the default flake, which is available as the programs.nh.flake setting. However, nh also provides three environment-specific settings for OS, home-manager, and Darwin. These are useful when, for one reason or another, different flakes are used for configuring the OS and the user's environment (e.g. on a shared machine).
This PR makes the other three settings available in a similar manner.
```
``` …

nh: Add options for specific flakes

---

modules/programs/tmux.nix
tests/modules/programs/tmux/prefix.conf
tests/modules/programs/tmux/shortcut-without-prefix.conf

adjusting the tmux lines for setting the prefix.
previously the prefix option would be set in the prefix key table, causing it to not register correctly.
the settings for the shortcut option would set an unrelated keybinding for the prefix.
```
```

tmux: shortcut and prefix settings

---

nixos/common.nix

Also applies to nix-darwin module.
```
```

nixos: improve description of enableLegacyProfileManagement

---

modules/programs/nushell.nix

I'm not using nushell, and it doesn't look like, that this changes anytime soon, additionally the code has changed quite a bit since I added the module (including nushell itself), that I don't see myself as an effective maintainer anymore.
```
```

nushell: remove Philipp-M as maintainer

---

modules/programs/zsh/default.nix
tests/modules/programs/zsh/default.nix
tests/modules/programs/zsh/siteFunctions-mkcd.nix

Add an option to the Zsh module that allows defining autoloadable site functions.
```
```

zsh: option to define autoloadable site-functions

---

modules/programs/gcc.nix

Add a module for GCC, mainly to configure its colours through `$GCC_COLORS`.
```
```

gcc: init module

---

modules/misc/news/2023/07/2023-07-25_07-16-09.nix
modules/misc/news/2024/11/2024-11-14_18-16-21.nix
modules/misc/news/2024/11/2024-11-24_21-15-57.nix
modules/misc/news/2025/03/2025-03-25_19-48-21.nix
modules/misc/news/2025/03/2025-03-25_20-44-04.nix
modules/misc/news/2025/03/2025-03-25_21-37-24.nix
modules/misc/news/2025/03/2025-03-29_23-32-11.nix
modules/misc/news/2025/05/2025-05-08_17-45-24.nix
modules/misc/news/2025/06/2025-06-27_18-53-10.nix
tests/default.nix
tests/modules/misc/news/default.nix

Had a few issues recently with news eval. Create a test that will run to catch them. 
Example failure: 
https://buildbot.nix-community.org/#/builders/6042/builds/119/steps/1/logs/stdio
```
```

tests/news: add new test for news entries

---

modules/programs/git-credential-keepassxc.nix
tests/modules/programs/git-credential-keepassxc/custom-groups.nix
tests/modules/programs/git-credential-keepassxc/default-config.nix
tests/modules/programs/git-credential-keepassxc/default.nix

Add a module for [git-credential-keepassxc](https://github.com/Frederick888/git-credential-keepassxc).
```
```

git-credential-keepassxc: init module

---

modules/programs/git-credential-keepassxc.nix

Not sure why this didn't get caught in CI...
Follow up to https://github.com/nix-community/home-manager/pull/7630#discussion_r2257898347
```
```

git-credential-keepassxc: fix eval

---

modules/programs/keepassxc.nix
tests/modules/programs/keepassxc/autostart.nix
tests/modules/programs/keepassxc/default.nix

Add an option to automatically start KeePassXC on login.
```
```

keepassxc: add autostart option

---

treefmt.toml

treefmt: handle deadnix excludes

---

modules/programs/mullvad-vpn.nix

Fixes typo in mullvad-vpn PR here https://github.com/nix-community/home-manager/pull/7638
```
```

mullvad-vpn: fix home.package -> home.packages

---

tests/darwinScrublist.nix

tests: add mullvad-vpn to darwin scrublist

---

modules/launchd/default.nix
modules/launchd/launchd.nix
modules/misc/news/2025/07/2025-07-01_22-15-34.nix
modules/targets/darwin/keybindings.nix
modules/targets/darwin/user-defaults/default.nix
tests/modules/launchd/agents.nix
tests/modules/launchd/expected-agent.plist
tests/modules/services/macos-remap-keys/basic-agent.plist

https://github.com/NixOS/nixpkgs/pull/356502 introduced an argument escape to lib.generators.toPlist which makes it escape special characters in the XML. This PR makes nix-darwin use it everywhere.
This is a breaking change, as https://github.com/nixos/nixpkgs/pull/356502#issuecomment-2480637115.
```
```
@midchildan
@khaneliman

launchd+targets/darwin: Escape XML in plists

---

modules/programs/jrnl.nix

Adds a module for the `jrnl` program: https://jrnl.sh/
```
```

jrnl: add module

---

modules/programs/firefoxpwa.nix

A ULID is 26 characters, not 16
```
```

firefoxpwa: fix ULID length typo

---

modules/lib/maintainers.nix
modules/programs/gemini-cli.nix
tests/modules/programs/gemini-cli/changelog.toml
tests/modules/programs/gemini-cli/default.nix
tests/modules/programs/gemini-cli/fix.toml
tests/modules/programs/gemini-cli/settings.json
tests/modules/programs/gemini-cli/settings.nix

This module adds the (gemini-cli)[https://github.com/google-gemini/gemini-cli] `programs.gemini-cli` option. I've configured the `settings.json` and `commands/**/*.toml` using the `*.settings` and `*.commands` options. 
Note: unfortunately I was unable to find a way to have the `commands` option take an arbitrarily nested attribute set, which would have been ideal to model the intended directory structure (`git.file` becomes `git/file.toml`) so instead I've just gone with specifying the path in the attribute set name to have custom namespaced commands. If anyone has any input on how to solve the infinite recursion problem when adding a recursive type for an option, im all ears. …

gemini-cli: init module

---

modules/programs/keepassxc.nix

Mention the problems that can occur when enabling the KeePassXC module and its possible fixes.
Closes #7298.
```
```

keepassxc: note the native messaging hosts manifest installation conflict

---

modules/programs/tmux.nix

This makes the `program.tmux.package` argument nullable, allowing use of system `tmux`.
- not required?
```
```
- not applicable
- not applicable

tmux: make package nullable

---

modules/lib/maintainers.nix
modules/misc/news/2025/08/2025-08-16_03-35-44.nix
modules/programs/hyprshot.nix

Add a new program module: Hyprshot the Hyprland screenshot utility.
A note on the tests. I ran all tests as instructed but they seem to be failing even on the `master` branch. The test I have written passes when run locally.
```
```

hyprshot: init module

---

modules/services/ssh-agent.nix
modules/services/ssh-tpm-agent.nix
tests/modules/services/ssh-agent/basic-service-expected.service
tests/modules/services/ssh-agent/basic-service.nix
tests/modules/services/ssh-tpm-agent/as-ssh-agent-proxy.nix
tests/modules/services/ssh-tpm-agent/default.nix
tests/modules/services/ssh-tpm-agent/standalone.nix

This PR fixes a bug in the ssh-tpm-agent module. `ssh-tpm-agent` can act as proxy to `ssh-agent` as showcased in its [README](https://github.com/Foxboron/ssh-tpm-agent#proxy-support). In contrast to the solution shown in the README, the [systemd unit shipped by upstream](https://github.com/Foxboron/ssh-tpm-agent/blob/master/contrib/services/user/ssh-tpm-agent.service) does not connect to a running ssh-agent through the `-A <socket>` option but through the `$SSH_AGENT_PID` environment variable that is set when the ssh-agent is initialized by `eval "$(ssh-agent)"`.
However, when the ssh-agent is started through systemd, like in its corresponding HM module, `$SSH_AGENT_PID` is not set, such that `ssh-tpm-agent` fails to connect to `ssh-agent`. You can verify this by trying to add a regular …

ssh-tpm-agent: act as ssh-agent proxy

---

modules/programs/aerospace.nix
tests/modules/programs/aerospace/aerospace-colemak.nix
tests/modules/programs/aerospace/colemak-settings-expected.toml
tests/modules/programs/aerospace/default.nix

Allow colemak as value for key-mapping.presets.
See https://github.com/nikitabobko/AeroSpace/commit/a8cd536ca182996ceffc04ebec55c4e3ac54f27a
```
```

aerospace: allow colemak on key-mapping

---

modules/programs/nh.nix

Changed `osFlake`, `darwinFlake` and `homeFlake` option types to allow either an absolute path or `singleLineStr`, aligning their behavior with the existing `flake` option.
```
```

nh: allow absolute flake paths

---

modules/programs/nix-search-tv.nix
tests/modules/programs/nix-search-tv/television.nix

Add quotes to the preview command in television integration to prevent the shell from interpreting options with `<name>` as writing the output of the command `name` to a file with the name of the remainder of the option name. 
For example, when running the command to preview `accounts.calendar.<name>.remote` (`nix-search-tv preview ...`), the shell  would interpret this as `name > .remote`, create the file `.remote`, and error out because the command `name` was not found.
```
``` …

programs/nix-search-tv: add quotes to fix shell misinterpretation 

---

modules/services/nix-gc.nix
tests/modules/services/nix-gc/darwin/basic.nix
tests/modules/services/nix-gc/darwin/changed-options.nix
tests/modules/services/nix-gc/darwin/darwin-nix-gc-interval-assertion.nix
tests/modules/services/nix-gc/darwin/default.nix
tests/modules/services/nix-gc/linux/changed-options.nix
tests/modules/services/nix-gc/linux/default.nix

This PR renames the `nix.gc.frequency` option to `nix.gc.dates` to match upstream NixOS' module. Closes #5106.
[example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and
[recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.
[example](https://github.com/nix-community/home-manager/blob/a51598236f23c89e59ee77eb8e0614358b0e896c/modules/programs/lesspipe.nix#L11). …

nix-gc: rename frequency to dates

---

modules/programs/ssh.nix

Provide a code snippet of the equivalent of `enableDefaultConfig` to `matchBlocks."*"` in the option description.
```
```

ssh: provide code snippet in enableDefaultConfig description

---

modules/services/pizauth.nix
tests/modules/services/pizauth/basic-config.nix

- added onChange pizauth reload for config file
- clientSecret is not required for outlook365 so should be nullable
```
```

pizauth: reload on change and fix option type

---

modules/programs/rclone.nix
tests/integration/standalone/rclone/default.nix
tests/integration/standalone/rclone/secrets-arbitrary-characters.nix

rclone-mount services are changed to be `Type=notify`; according to <https://rclone.org/commands/rclone_mount/#systemd>, it should be possible to set `Type=notify` to ensure that the service is not marked as started until the mountpoint has actually been successfully mounted, and this is what the project recommends when using as a systemd service.
Furthermore, the `key=value` syntax is used in `rclone config update` to ensure that the secret value cannot be interpreted as a flag (which could happen if the secret value begins with `-`). I don't know if tests really ought to be added for this, but I was kinda struggling to run the tests for `rclone` tbh. I'm open to adding a test though (or maybe making the `secrets-with-whitespace` test scope a bit broader).
`nix-shell -p treefmt nixfmt …

programs.rclone: various fixes

---

modules/misc/qt.nix
tests/modules/misc/qt/default.nix
tests/modules/misc/qt/qt-platform-theme-kde6-migration.nix

Modeled after the changes in Nixpkgs from https://github.com/NixOS/nixpkgs/pull/435823, platform `kde6` is removed and platform `kde` now means Plasma 6.
Also fixes evaluation error due to missing attribute `libsForQt5.breeze-qt5` (closes https://github.com/nix-community/home-manager/issues/7728).
- This is a **breaking change**.
```
```
- If this PR adds an exciting new feature or contains a breaking …

qt: Remove Plasma 5 and related Qt5 packages

---

modules/programs/jq.nix

Make `colors` and `package` nullable, and since according to commit
f9b5172d956c79add5f6c8acccea2c7ca7f904c9 the defaults are the upstream values, default `colors` to null.
Setting JQ_COLORS is just unnecessary environment clutter when using the default colors.
Although the module now does nothing besides (optionally) installing `jq` when `colors` is left at its default value, that is still useful: from a flake with multiple home-manager configurations, some of which have `jq` provided through other means, setting/forcing `programs.jq.package` to null is more convenient than conditionally adding `jq` to `home.packages`.
`nix run .#tests -- test-all` fails for reasons that look unrelated …

jq: make `colors` and `package` nullable

---

modules/programs/firefox/default.nix
modules/programs/firefox/mkFirefoxModule.nix

mkFirefoxModule: policies option work for darwin

---

modules/services/window-managers/hyprland.nix

This PR adds support for [hyprland submaps](https://wiki.hypr.land/Configuring/Binds/#submaps) in the Hyprland HM module.
This is my first PR here, and this implementation is aimed to be basic, submap support could be extended in the future. The only "flashy" things in this PR are an assertion for submap name `reset` and warnings for non-binds in submaps.
Still slightly WIP : the added features seem to function all as expected (as far as my testing went), but there are still some things to do (I'm open for advice on how to get these done):
I'm also all open for discussion on the implementation details and option structure, formatting or any comment really
or `nix build --reference-lock-file flake.lock ./tests#test-all` …

hyprland: add support for submaps (#6062)

---

modules/misc/news/2025/09/2025-09-01_14-57-54.nix
modules/services/swayosd.nix
tests/modules/services/swayosd/default.nix
tests/modules/services/swayosd/deprecated-options.nix
tests/modules/services/swayosd/swayosd.nix

swayosd: Remove non-existing `display` arg option

---

modules/programs/aerospace.nix

White technically any example would do, it's better to use the one from
upstream docs, otherwise we may confuse users trying to repeat upstream
aerospace sketchybar plugin recipe. (I for one fell a victim of the
confusion...)
https://nikitabobko.github.io/AeroSpace/goodies#show-aerospace-workspaces-in-sketchybar
```
```

aerospace: use upstream example for exec-on-workspace-change

---

modules/services/polybar.nix

To avoid future problems when #7706 is merged.
```
```

polybar: make sure X-Restart-Triggers is a list

---

modules/services/syncthing.nix
tests/modules/services/syncthing/extra-options.nix

syncthing v2 changed its CLI API.
https://github.com/syncthing/syncthing/releases/tag/v2.0.0
```
```

syncthing: Fix for syncthing v2 (#7762)

---

modules/services/hyprsunset.nix

Hyprsunset does not evaluate when hyprsunset package is set to `null`
```
error: attempt to call something which is not a function but a set: { }
at /nix/store/g1jaiwcamlaxia17xhhww0s63iyns1xv-source/modules/services/hyprsunset.nix:203:10:
202|       }
203|       // lib.optionalAttrs (config.wayland.windowManager.hyprland.package != null) lib.mapAttrs' (
|          ^
204|         name: transitionCfg:
```
I wrapped `lib.mapAttrs' (...) cfg.transitions` in brackets to fix this issue.
```nix
{
wayland.windowManager.hyprland = {
enable = true;
package = null;
portalPackage = null;
};
services.hyprsunset = {
enable = true;
settings = {
profile = [
{
time = "6:00";
identity = true;
}
{
time = "00:00";
temperature = 3500;
gamma = 0.4;
}
];
};
};
}
```
I wonder if the …

hyprsunset: fixed evaluation when hyprland package is null

---

modules/misc/gtk.nix
modules/misc/gtk/gtk2.nix
modules/misc/gtk/gtk3.nix
modules/misc/gtk/gtk4.nix
modules/misc/gtk/lib.nix
tests/modules/misc/gtk/default.nix
tests/modules/misc/gtk/gtk-colorscheme.nix
tests/modules/misc/gtk/gtk-global-inheritance-gtk3-expected.ini
tests/modules/misc/gtk/gtk-global-inheritance-gtk4-expected.ini
tests/modules/misc/gtk/gtk-global-inheritance.nix

Fixes https://github.com/nix-community/home-manager/issues/7154
Provide an option to specify gtk's `prefer-dark` or `prefer-light`.
```
```

gtk: add color scheme option

---

modules/programs/oh-my-posh.nix

Fix an issue with `oh-my-posh` cached paths breaking during garbage collection.
`oh-my-posh` creates script files in `~/.cache/oh-my-posh` which include old derivation paths. Once the path is garbage collected, oh-my-posh stops working, preventing to successfully create new shells. With this error -
```
bash: /nix/store/5ddhz8nsahf1d03smzx2xpmynjspjfh8-oh-my-posh-26.8.0/bin/oh-my-posh: No such file or directory
```
```
```

oh-my-posh: add cache clearing on package version changes

---

modules/programs/rclone.nix

It's not really clear why this was done in the first place, and furthermore it means that the secrets are being printed to stdout and appearing in the user's journal.

rclone: check existence of file rather than using `cat`

---

nix-darwin/default.nix

Redirects activation output to stderr on Nix-Darwin. Every other activation script on Darwin does this and some tools like `nh` only print stderr and not stdout, so when using those the output wasn't shown before.
```
```

nix-darwin: redirect output to stderr

---

modules/programs/lutris.nix
tests/modules/programs/lutris/runners-configuration.nix

- Add a defaultWinePackage option, a convenient way for users to specify to lutris which wine package to use by default.
- Make it clearer that runners.package is not compatible with all runners, warn those who try to set it for wine.
Should close #7764 
```
```

lutris: add defaultWinePackage option

---

modules/services/podman-linux/containers.nix

Newer versions of Podman with some Netavark configurations expect nftables to be on PATH. Adding it explicitly here to ensure its available.
Will resolve issues with Podman 5.6.0 containers not starting and journal logs similar to:
```
Error: netavark: nftables error: unable to execute "nft": No such file or directory (os error 2)
```
```
```
- If this PR adds an exciting new feature or contains a breaking …

podman: add nftables to default container path

---

modules/programs/khard.nix
tests/modules/programs/khard/default.nix
tests/modules/programs/khard/discover_type.nix
tests/modules/programs/khard/discover_type_expected

This adds support for discover type entries, which were introduced in khard 0.20.0, which work very similar to the equally-named khal feature.
```
```

khard: support discover entries

---

all-maintainers.nix
modules/services/window-managers/i3-sway/sway.nix

I do not use sway anymore. It seems no other module is maintained by me, thus also remove me from `all-maintainers.nix`.
The commit is signed by (the signing subkey of) the GPG key touched in the diff.
```
```

sway: drop oxalica from maintainer

---

modules/misc/news/2025/09/2025-09-13_13-36-15.nix
modules/programs/cudatext.nix
tests/darwinScrublist.nix
tests/modules/programs/cudatext/default.nix
tests/modules/programs/cudatext/example-config.nix
tests/modules/programs/cudatext/keys.json
tests/modules/programs/cudatext/keysLexerC.json
tests/modules/programs/cudatext/keysLexerPython.json
tests/modules/programs/cudatext/lexerC.json
tests/modules/programs/cudatext/lexerPython.json
tests/modules/programs/cudatext/lexerRust.json
tests/modules/programs/cudatext/user.json

This PR adds a module for configuring [CudaText](https://cudatext.github.io/).
```
```

cudatext: add module

---

modules/programs/oh-my-posh.nix
tests/modules/programs/oh-my-posh/assertion-all-three.nix
tests/modules/programs/oh-my-posh/assertion-settings-config-file.nix
tests/modules/programs/oh-my-posh/assertion-settings-theme.nix
tests/modules/programs/oh-my-posh/assertion-theme-config-file.nix
tests/modules/programs/oh-my-posh/config-file.nix
tests/modules/programs/oh-my-posh/default.nix
tests/modules/programs/oh-my-posh/settings.nix

Closes https://github.com/nix-community/home-manager/pull/6108
```
```

oh-my-posh: added option to supply config path

---

modules/systemd.nix
tests/modules/services/ssh-tpm-agent/as-ssh-agent-proxy.nix

This is some experiments in making the systemd unit descriptions more typed by using freeform modules.
_Technically no, with this change we would, for example, reject `ExecStart = 42` (which is nonsense) but quite possibly also valid configurations._
```
```
_Will do this if leaving draft._

systemd: make unit definitions freeform modules

---

modules/misc/news/2025/09/2025-09-15_18-14-27.nix
modules/programs/nvchecker.nix
tests/modules/programs/nvchecker/basic-config.nix
tests/modules/programs/nvchecker/basic-config.toml
tests/modules/programs/nvchecker/default.nix
tests/modules/programs/nvchecker/empty-config.nix
tests/modules/programs/nvchecker/empty-config.toml

`nvchecker` checks if a new version of some software was released.
These fail for me because of #7818. But the tests I added do pass on x86_64-linux and aarch64-darwin.
```
```

nvchecker: add module

---

modules/programs/mise.nix
tests/modules/programs/mise/nushell-integration.nix

Generating the nushell config at build-time has a bunch of advantages:
- It saves ~10ms of shell startup time in my system
| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `mise activate nu` | 9.8 ± 1.0 | 7.9 | 13.2 | 1.00 |
- It is pure, as it doesn't depend on a file outside of the store
- It follows the existing convention with nushell integrations as far as I can see
Static generation is added to nushell mostly because it lacks `eval` support, but this change could be applied to all the other shells as well, for some of the above reasons.
As a bonus, I added checks for `cfg.package != null` to all the integrations. When the package is null, we emit a warning telling the user that the shell integration won't be added. Which is true, because the …

mise: statically generate nushell config

---

modules/programs/nushell.nix
tests/modules/programs/nushell/config-dir.nix
tests/modules/programs/nushell/default.nix

This PR exposes the nushell configuration directory through the `programs.nushell.configDir` option.
Nushell has different defaults for the configuration dir depending on the OS: `Library/Application Support/nushell` on MacOS and `.config/nushell` on Linux. However, setting `XDG_CONFIG_HOME` will override the default config unconditionally.
This means that there exists the possibility of the configuration not working in systems where users have `XDG_CONFIG_HOME` managed outside of home-manager (see https://github.com/nix-community/home-manager/issues/6484 for a related example).
This also allows just overriding the default location in general, for whatever the user might want to use it or for setting up integrations (adding files to `$nu.user-autoload-dirs` for example)
or `nix build …

nushell: expose config dir location as option

---

modules/misc/news/2025/09/2025-09-19_01-12-11.nix
modules/misc/nix-remote-build.nix
modules/modules.nix
tests/default.nix
tests/modules/misc/nix-remote-build/default.nix
tests/modules/misc/nix-remote-build/empty-settings.nix
tests/modules/misc/nix-remote-build/example-settings-expected
tests/modules/misc/nix-remote-build/example-settings.nix

Add a new module to declare [nix remote builders](https://nix.dev/manual/nix/2.28/advanced-topics/distributed-builds).
This module is a direct adaptation of the [corresponding Nix module](https://search.nixos.org/options?channel=unstable&query=nix.buildMachines).
See the relevant manual page here: https://nix.dev/manual/nix/2.28/advanced-topics/distributed-builds
- **nix-remote-build: add module**
- **news: add entry for nix-remote-build**
cc @lillecarl
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits …

nix-remote-build: add module

---

modules/programs/zed-editor.nix

This is a backport of https://github.com/nix-community/home-manager/pull/7220 to 25.05.
Apologies if this is dumb, I couldn't see anything in the guidelines about how it's decided what is allowed to be backported or how to send backports. I'm also fuzzy on whether this commit counts as a bug fix or a feature.
- x] Code formatted with `nix fmt` or
`nix-shell --pure tests -A run.all`. [Running, will update].
```
```
- If this PR adds an exciting …

Backport nullable programs.zed-editor.package

---

modules/services/syncthing.nix

This change allows configuring per-folder encryption passwords declaratively (and without leaking them into the store), modeled after the upstream Nixpkgs changes from https://github.com/NixOS/nixpkgs/pull/383442.
Closes https://github.com/nix-community/home-manager/issues/7318.
```
```

syncthing: handle per-folder `encryptionPasswordFile`

---

modules/misc/nixgl.nix

Some home manager modules depend on the name, so changing it in the wrapper can break them.
Fixes #6608 
```
```

nixgl: use original package name

---

tests/modules/services/syncthing/linux/tray.nix

Make the test a bit more valid.
```
```

syncthing: assert tray service content in test

---

flake.lock
modules/misc/news/2025/09/2025-09-25_17-32-18.nix
modules/programs/desktoppr.nix

Adds a module for [desktoppr](https://github.com/scriptingosx/desktoppr), a small utility to manage the desktop picture (macOS < 13) / wallpaper (macOS >= 13).
I'm not sure how I would create tests for this module. I tried to create tests where it would set the desktop picture and color, then read it to ensure it was set, but it seems like the tests run in the build sandbox, so the picture/color never gets set and reading the picture/color always returns an empty string. So I don't think it's possible to test it inside the sandbox.
```
```
See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information …

desktoppr: init module

---

modules/programs/mods.nix

No need to use the HM list since @ipsavitsky is now in the Nixpkgs maintainers list.
```
```

mods: get ipsavitsky from Nixpkgs maintainers list

---

modules/lib/maintainers.nix
modules/services/syncthing.nix

Adds `syncthing.tray.package` to `home.packages` if `syncthing.tray.enable` is `true`, or adds `pkgs.syncthingtray-minimal` if the deprecated `syncthing.tray = true` is used.
Also adds me as maintainer for the Syncthing module.
Closes #4309.
- Does adding an extra package to existing installations count as a breaking change?
```
```

syncthing: install tray package when `syncthing.tray` is enabled

---

modules/misc/news/2025/09/2025-09-25_19-15-33.nix
modules/programs/aichat.nix
tests/modules/programs/aichat/llama.yaml
tests/modules/programs/aichat/openai.yaml
tests/modules/programs/aichat/settings.nix

This PR adds the `programs.aichat.agents` option to allow users to declare agent-specific settings for Aichat as described [here](https://github.com/sigoden/aichat/wiki/Configuration-Guide#agent-specific). 
```
```

aichat: add agents option

---

modules/services/macos-remap-keys/keytables.nix

Adds a key code for NonUSBackslash (`§/±`) present in non-US keyboards (EU variants in particular).
This allows to move the backtick (GraveAccent/Tilde) key to the "usual" location, below `Escape` key, for example:
```nix
services.macos-remap-keys = {
enable = true;
keyboard = {
NonUSBackslash = "GraveAccent";
GraveAccent = "NonUSBackslash";
};
```
**N.B.** I believe this should not impact any tests, so I've skipped the two steps below
```
``` …

macos-remap-keys: add NonUSBackslash keycode

---

modules/lib/shell.nix
modules/lib/zsh.nix
modules/programs/zsh/default.nix
modules/programs/zsh/history.nix
modules/programs/zsh/plugins/default.nix
tests/darwinScrublist.nix
tests/modules/programs/fabric-ai/zshrc
tests/modules/programs/zsh/aliases.nix
tests/modules/programs/zsh/default.nix
tests/modules/programs/zsh/history-substring-search-expected.zshrc
tests/modules/programs/zsh/history-substring-search.nix
tests/modules/programs/zsh/plugins.nix
tests/modules/programs/zsh/prezto.nix
tests/modules/programs/zsh/session-variables.nix
tests/modules/programs/zsh/smart-formatting-expected.zshrc
tests/modules/programs/zsh/smart-formatting.nix
tests/modules/programs/zsh/zshrc-content-priorities.nix

Just doing some loops for adding to path and sourcing to clean up the generated code. 
Plugin path: 
```bash
path+="/Users/khaneliman/.config/zsh/plugins/fzf-tab"
fpath+="/Users/khaneliman/.config/zsh/plugins/fzf-tab"
path+="/Users/khaneliman/.config/zsh/plugins/zsh-nix-shell"
fpath+="/Users/khaneliman/.config/zsh/plugins/zsh-nix-shell"
path+="/Users/khaneliman/.config/zsh/plugins/zsh-vi-mode"
fpath+="/Users/khaneliman/.config/zsh/plugins/zsh-vi-mode"
path+="/Users/khaneliman/.config/zsh/plugins/fast-syntax-highlighting"
fpath+="/Users/khaneliman/.config/zsh/plugins/fast-syntax-highlighting"
path+="/Users/khaneliman/.config/zsh/plugins/zsh-autosuggestions"
fpath+="/Users/khaneliman/.config/zsh/plugins/zsh-autosuggestions"
path+="/Users/khaneliman/.config/zsh/plugins/zsh-better-npm-completi …
```

zsh: generated plugin loading cleanup/improvements

---

modules/programs/gurk-rs.nix

The 'data_path' key was deprecated upstream a while ago.
See commit d9b538d0 (https://github.com/boxdot/gurk-rs/commit/d9b538d0)
for details.

gurk-rs: remove references to deprecated 'data_path' option from documentation

---

modules/lib/zsh.nix
modules/programs/zsh/default.nix
tests/modules/programs/zsh/prezto.nix
tests/modules/programs/zsh/session-variables.nix
tests/modules/programs/zsh/session-variables.zshenv

Follow up to https://github.com/nix-community/home-manager/pull/7849
Closes https://github.com/nix-community/home-manager/issues/7896
```
```

zsh: fix sessionVariables variable expansion

---

modules/programs/fish.nix
tests/modules/programs/fish/default.nix
tests/modules/programs/fish/themes.nix

Supersedes #5394
Allows for linking fish plugin theme files to [fish's themes folder](https://fishshell.com/docs/current/cmds/fish_config.html#theme-files). Fully allowing for theme plugins to properly be installed declaratively. Fixes #3724
```
```

fish: support theme plugins

---

modules/files/check-link-targets.sh

This change improves the formatting of the collision error message in `modules/files/check-link-targets.sh`.
Previously, the error message was wrapped across multiple lines mid-sentence due to 80-character source formatting. When rendered through systemd logs, this wrapping caused important lines — **specifically the file path responsible for the collision** — to be truncated. Users often had to run `journalctl` to retrieve the missing context.
This update restructures the string concatenation so that each bullet point is rendered on a single line at runtime, while still respecting source formatting guidelines. As a result, the collision error message now displays the full file path directly in the standard log output.
- Ensures file path information is immediately visible in service …

files: improve collision error message formatting for readability

---

modules/files.nix
modules/files/check-link-targets.sh
nix-darwin/default.nix
nixos/common.nix
nixos/default.nix

Closes https://github.com/nix-community/home-manager/issues/4199.
When using the `backupFileExtension` option, if the backup file exists, the activation process fails. This adds an opt in option to instead overwrite the old backup instead of failing.
This feature is highly requested, the issue above is the 6th most liked issue on the tracker.
I have not added a help text mentioning this option on collision to be conservative. This setting removes data, so I don't think suggesting it for any collision is responsible.
There was a previous attempt at implementing this here https://github.com/nix-community/home-manager/pull/4971 but the contributor gave up due to opposition to overwriting data. Since then [Hjem](https://github.com/feel-co/hjem) (A minimal home-manager alternative) has …

home-manager: add backup overwrite option

---

modules/misc/news/2025/10/2025-10-02_12-54-47.nix
modules/programs/alistral.nix
tests/modules/programs/alistral/config.json
tests/modules/programs/alistral/default.nix
tests/modules/programs/alistral/settings.nix

This PR adds a module for configuring [alistral](https://github.com/RustyNova016/Alistral).
```
```

alistral: add module

---

modules/services/lorri.nix

Without this fix, the notifications service would need to start by hand
every time.
@moduon MT-1075

lorri: make notifications service auto-start if enabled

---

modules/misc/news/2025/10/2025-10-05_14-55-44.nix
modules/programs/am2rlauncher.nix
tests/modules/programs/am2rlauncher/config.xml
tests/modules/programs/am2rlauncher/default.nix
tests/modules/programs/am2rlauncher/settings.nix

This PR adds a module for configuring [AM2RLauncher](https://github.com/AM2R-Community-Developers/AM2RLauncher).
```
```

am2rlauncher: add module

---

modules/programs/discocss.nix
tests/darwinScrublist.nix
tests/modules/programs/discocss/basic-configuration.nix
tests/modules/programs/discocss/default.nix
tests/modules/programs/discocss/no-css.nix
tests/modules/programs/discocss/no-packages.nix
tests/modules/programs/discocss/with-custom-css-expected.css

discocss: fix discordPackage override

---

modules/programs/smug.nix

Adds 'selected' option for tmux windows
```
```

smug: add new option introduced by v0.3.7

---

modules/programs/dircolors.nix
tests/modules/programs/dircolors/settings.nix
tests/modules/programs/dircolors/xdg-config-settings.nix

Adds nushell support to dircolors module
```
```
@justinlovinger

dircolors: add nushell integration

---

modules/misc/news/2025/10/2025-10-07_09-39-32.nix
modules/programs/amoco.nix
tests/modules/programs/amoco/config
tests/modules/programs/amoco/default.nix
tests/modules/programs/amoco/settings.nix

This PR adds a module for configuring [Amoco](https://github.com/bdcht/amoco). It supports a config file at `$HOME/.config/amoco/config` ([see](https://github.com/bdcht/amoco/blob/3e36c5247283a7abba57ce3c06910a7271ab1b9a/amoco/config.py#L256), especially lines 268 and 276), but I didn't find an example config file.
```
```

amoco: add module
